### ISSUE TITLE
s.decomposition() doesn't work on my Gatan EDS dm3's

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1002]
For some reason `.decomposition()` doesn't do anything to my EDS files. Please attempt running the following code on [EDS-Spectrum-Image.dm3](https://files.gitter.im/hyperspy/hyperspy/x1Bu/EDS-Spectrum-Image.dm3)

``` python
import hyperspy.api as hs

s = hs.load("EDS-Spectrum-Image.dm3")
s.decomposition()
s.plot_explained_variance_ratio()
```

For reference, EELS SIs acquired in exactly the same region (with the same dimensions) work just fine.

**Comment by magnunor** [comment]
I tried this on both the current master, v0.8.4 and 0.8.x branch, and this seem to work in all:

```Python
import hyperspy.api as hs
s = hs.load("EDS-Spectrum-Image.dm3")
s.change_dtype('float64')
s.decomposition()
s.plot_explained_variance_ratio()
s1 = s.get_decomposition_model(4)
```
And `s.plot_explained_variance_ratio()` and `s1` works as I'd expect them to do.

Only difference between master and 0.8.x, is the master branch does not output any text when running `s.decomposition()`.

What version are you using?

**Comment by thomasaarholt** [comment]
Might have to do with the dtype then. Will try again this evening.

**Comment by thomasaarholt** [comment]
Looks like our EDS system returns `int`s to DM. That makes sense as they're counts, and I guess it makes sense that it can't do decomposition on whole numbers. That said, would be nice if it reported an error or warning.

```python
>>> s.data
array([[ 47, 121, 127, ...,   0,   0,   0],
       [ 38,  98, 107, ...,   0,   1,   0],
       [ 50, 124, 125, ...,   0,   0,   0],
       ..., 
       [ 61, 120, 124, ...,   0,   0,   0],
       [ 62, 138, 123, ...,   0,   0,   0],
       [ 64, 104, 132, ...,   0,   0,   0]], dtype=uint32)
```

**Comment by magnunor** [comment]
It should give you a message if you need to change the dtype, I saw it in both current master and 0.8.x. Not certain why you didn't get that warning.

**Comment by thomasaarholt** [comment]
This is strange. I do not see a message (until `plot_explained_variance ratio()` returns an error.
<img width="1114" alt="screenshot 2016-05-20 09 28 59" src="https://cloud.githubusercontent.com/assets/2721423/15421894/945e3bcc-1e6d-11e6-8e73-b7baf4fb20c6.png">

**Comment by k8macarthur** [comment]
I also reproduced this error when I tried it on my mac. Are using a Mac @thomasaarholt? Is this a Mac vs PC problem again?

**Comment by thomasaarholt** [comment]
I am using Mac :)

**Comment by magnunor** [comment]
Possible cause:

The decomposition functions uses the `logging` library to output the warning, and the default setting on OS X might be to not show these warnings.

https://github.com/hyperspy/hyperspy/blob/d4c341868e52dea6d884f8e0382807a21057d1c2/hyperspy/learn/mva.py#L167

**Comment by to266** [comment]
Try running this somewhere before decomposition?
```python
hs.set_log_level('WARNING')
```

**Comment by thomasaarholt** [comment]
`hs.set_log_level('WARNING')` gives no change :/

**Comment by dnjohnstone** [comment]
I'm getting the same error on the master... tried to decompose some uint8 data and it just didn't do anything without complaining - changed it to float and it was fine.

I think this maybe a numpy versions thing... as in #1033 I also can't make some things fail that probably should atlough with numpy 1.10.4 I think  I should be on the latests version

**Comment by thomasaarholt** [comment]
@dnjohnstone What OS are you running?

**Comment by ericpre** [comment]
I can confirm I have the same problem: no message raised when checking the data type.
Adding a print [there](https://github.com/hyperspy/hyperspy/blob/ba707c24c69aed41c9c6fac8281b16d33ad5c9ac/hyperspy/learn/mva.py#L165) works.
It looks like the `_logger.warning()` is not working, neither rising a message in the console, nor writing a warning in the log file (even after calling `hs.set_log_level('WARNING')`).

I would suggest, it would be good to fix this before the release since it can be quite misleading to inexperienced users; particularly if people start to play with EDS data from bcf files, for example!

I don't really know how the logger works, so I can't make a pull request right now, sorry!

**Comment by ericpre** [comment]
OK, too late... #1140 next one then! ;)

**Comment by francisco-dlp** [comment]
:)

**Comment by thomasaarholt** [comment]
@ericpre, it looks like this is a Jupyter Notebook bug. I can't seem to get any output either. Are you on Mac as well?

**Comment by ericpre** [comment]
I have been testing it in a jupyter qtconsole on linux. I have just tested in jupyter console right now and I am getting the warning in the console but not in the log.

**Comment by thomasaarholt** [comment]
Jupyter Notebook now correctly shows the warning on Mac. I'm closing this, as it seemed to be a Mac-Jupyter-related issue.
