### ISSUE TITLE
s.crop_spectrum GUI not working in master

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#1004]
```Python
import numpy as np
s = hs.signals.Spectrum(np.arange(1000))
s.crop_spectrum() # Select some area, press ok or apply
```
This returns: 
```Python
RuntimeError: xdata and ydata must be the same length
```
It also leaves a broken signal, due to the `axes_manager` and the data not having the same lengths:
```Python
s.axes_manager[0].size
1000
s.data.shape
(249,)
```

The CLI version works fine:
```Python
import numpy as np
s = hs.signals.Spectrum(np.arange(1000))
s.crop_spectrum(100,200)
```
The 0.8.x version also works fine.

**Comment by magnunor** [comment]
On a more general note: is there some way to make tests for GUI functions? Most of the CLI function bugs are caught by our tests, since we can write them. But the current situation is not so optimal, since the GUI things can break in subtle ways. 

Also, since (I guess) most of the developers use the CLI functions, these GUI bugs are more rarely caught. However, new users will probably use these GUI functions. And if they're buggy, they can turn people away (even if the CLI functions are pretty robust).

**Comment by to266** [comment]
I'm not aware how to easily test the GUI functions - hence we don't. I suppose you could try doing that with a complicated collection of `Mock`s, but I doubt it's worth the effort..

**Comment by francisco-dlp** [comment]
#1116
