### ISSUE TITLE
%matplotlib error with fresh windows install

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1006]
I just installed 0.8.4 using the single-user settings from the 64-bit binary. Everything works fine until I try either `%matplotlib` or `s.plot()`

The former returns [this error,](https://gist.github.com/thomasaarholt/d183247fb0db7af84e4fd603eb05910e) whilst the latter results in two windows (signal and navigator) which immediately freeze (nothing is plotted).

Should mention that this is installed on a computer without admin rights.

**Comment by francisco-dlp** [comment]
In which order did you execute the commands?

From `0.8.4` the right order is:

```python

%matplotlib qt4
import hyperspy.api as hs

```

**Comment by thomasaarholt** [comment]
Ah, that’s it. It doesn’t care on my mac, so I’ve just forgotten about that.


Thomas Aarholt
thomasaarholt@gmail.com

**Comment by francisco-dlp** [comment]
Great, I'll close it then. Thanks for reporting the issue, I'm sure that you're not the only one getting caught by this subtle change in 0.8.4.
