### ISSUE TITLE
Windows 0.8.4 installation unsuccessful

### ISSUE THREAD

**Issue by RowanLeary** [hyperspy/hyperspy#1009]
Jupyter notebook and console options available in right click menu, but fail to start. Any guidance much appreciated.
![hyperspy04installproblem](https://cloud.githubusercontent.com/assets/15276900/15497808/63c1b456-2194-11e6-9c78-8e15a771e11e.jpg)

**Comment by francisco-dlp** [comment]
This is a permissions problem (and a bug, thanks for reporting it!).

You can workaround it by changing the permissions of the HyperSpy folder to allow writing by your user.

**Comment by RowanLeary** [comment]
Thanks, solved :)

**Comment by francisco-dlp** [comment]
Thanks for the feedback.

The "solution" above is not a fix, just a workaround, so I'll reopen this issue.

**Comment by dnjohnstone** [comment]
@francisco-dlp if this is a bug - which bit of HyperSpy is broken to cause this? i.e. is there anything we can do about it or is it something external? If it's something external (which seems likely to me) is the 'fix' to improve the documentation to tell people to do this on install?

**Comment by tjof2** [comment]
My experience: 

- It doesn't always result in the permissions error (for example I've never had a problem on Windows 10).
- However,  a while back on Windows 8.1 I did have this problem after about a week of using HyperSpy. It worked fine for the first week, then this error happened. When I changed the permissions as @francisco-dlp suggests, it broke my installation further (a whole heap of Windows error messages occurred).

**Comment by francisco-dlp** [comment]
I have tried to fix this with a new release of `start_jupyter_cm`,  `1.1.2`, which is know hacked when creating the bundled hyperspy/hyperspy-bundle#13.

We will release a beta version of `HyperSpy 0.8.5` later in the day, so it'll be great if those who are affected by this bug could test it and provide feedback here.
