### ISSUE TITLE
plot_images broken in master

### ISSUE THREAD

**Issue by dnjohnstone** [hyperspy/hyperspy#1018]
Not sure when this crept in but broken as below 
![plot_images_broken](https://cloud.githubusercontent.com/assets/10629656/15544719/9ef5a552-2291-11e6-98fe-cfdd4c28f9ac.png)

**Comment by dnjohnstone** [comment]
Actually this is a little odd - the code doesn't seem to have changed much here compared to 0.8.x but this works fine in 0.8.x....

**Comment by dnjohnstone** [comment]
I've fixed this - github is being slow for a minute though...

**Comment by francisco-dlp** [comment]
#1020
