### ISSUE TITLE
eels_spectrum_simulation.py commented

### ISSUE THREAD

**Issue by dnjohnstone** [hyperspy/hyperspy#1042]
@francisco-dlp  What's the story with the fact that all the code in eels_spectrum_simulation is commented?

**Comment by francisco-dlp** [comment]
This is another remnant of EELSLab (HyperSpy's ancestor). When we turned it into HyperSpy we did not keep all EELSLab's features. Some where simply removed and others, such as this one, commented out in the hope that we'll reimplement it later on. I have better code than this one to produce EELS "toy" simulations based on atomic cross sections, so we can safely remove this file.

**Comment by dnjohnstone** [comment]
#1076
