### ISSUE TITLE
Uncertainty over Mac install Python 3

### ISSUE THREAD

**Issue by RowanLeary** [hyperspy/hyperspy#1053]
A number of people new to hyperspy and I want to install on Mac OS X. With the recent switch to Python 3, how should we proceed?

Should we download and install anaconda with Python 3?

Do we need to uninstall the Mac system Python? Do we need to uninstall any previous anaconda, if present?

**Comment by to266** [comment]
# System python:
No, you don't have to uninstall system Python. Anaconda should be completely independent, that's kind of the point of it.

# Previous anaconda:
This one might be slightly tricky. One of the main points of the anaconda is to have an isolated Python environment. What's more, it can contain not just one, but as many as you like environments of different python versions and configurations. There are a number of ways to go forward here:

### 1. Uninstall previous the anaconda
The "nuke it all" approach, when you don't want to deal with the complexity of additional environments AND don't care about any other packages installed in anaconda. After uninstalling the old one, just install a brand new with Python 3 as the default. After that proceed to the HyperSpy installation steps.

__Drawbacks:__
Does not preserve anything from the old environment.

### 2. Create a new Python3 (or HyperSpy) environment
When you want to keep the current anaconda environment as it is currently (hence probably with the old HyperSpy), but still get the new version. 

This involves following steps laid our [here](http://hyperspy.readthedocs.io/en/stable/user_guide/install.html#creating-conda-environment-for-hyperspy). Hopefully this environment file is up to date... it should be! ;)

__Drawbacks:__
If running commands from a command-line interface, the new HyperSpy environment has to be `activate`'ed first. 

For me this activation has to be done with every new terminal, so quite inconvenient if used frequently.
Note that if just Jupyter Notebooks are used, then separate kernels for different anaconda environments can be added like described [here](http://stackoverflow.com/a/30492913/3589924), and don't have to be activated to use (just picking the correct kernel in the drop-down menu on the notebook itself is enough).

### 3. Update the root environment to Python 3
As described [here](http://stackoverflow.com/a/28460907/3589924), you can upgrade the current (so probably the default "root") environment to Python 3.

It is noted that you'll have to reinstall all packages installed using `pip`. At the very least that will probably involve reinstalling hyperspy, so might look something like this:
```bash
# first uninstall hyperspy and any additional packages installed using pip.
pip uninstall hyperspy #other_package
# prepating for the big update
conda update conda
# the big update
conda update --all python=3.5

# install HyperSpy and the two dependencies
conda install -c conda-forge traits traitsui
pip install hyperspy
```

an equivalent that should still work, but add [conda-forge](https://conda-forge.github.io/) to the default channels would be as follows (HyperSpy will eventually be added to conda forge, and then updates and installing will be significantly simpler, just running `conda update hyperspy` or something along those lines):

```bash
conda config --add channels conda-forge
conda update conda
conda update --all python=3.5
pip install -U hyperspy
```

**Comment by to266** [comment]
Let's first see if that worked for @RowanLeary, since I have not tested the last part myself

**Comment by thomasaarholt** [comment]
Mac user, here. The Anaconda environment referred to in @to266's second point is probably the easiest.  You should not need to uninstall Anaconda (in any case, just update it by `conda update conda` and `conda update anaconda` The first command appears to have to happen outside any virtual environment.)

If you run into complications, just install Anaconda from https://www.continuum.io/downloads and then `pip install hyperspy` in the terminal. 

Don't mess with the built-in python on Mac at all. You *will* break something.

I also highly recommend virtual environments, like @to266 mentioned. In order to combat the `source activate 'my_environment_name'`, I use [iTerm](https://www.iterm2.com), which gives me the option to have a default *profile* / *line of code* entered in any new terminal window I open. CMD + 1-9 let's me switch between such "profiles" quickly.

**Comment by jeinsle** [comment]
Francisco and I worked out a method that worked nicely, but we had to build three wheels first as sometimes the installer would get them and sometimes not.  I will try to find the steps for these but they are on my computer at work. 

Will update on Monday.

**Comment by thomasaarholt** [comment]
Is there a plan on putting Hyperspy on Anaconda?
`conda install hyperspy`

**Comment by to266** [comment]
Kind of. There is a plan to put it on [conda-forge](https://github.com/conda-forge/staged-recipes/pull/679) , which will hopefully end up as trivial to install :

```bash
conda install -c conda-forge hyperspy
```

**Comment by sem-geologist** [comment]
hmm maybe there is the place to ask this. From #949 it is possible to build osx wheels (I saw it is done for 1.0 release draft already). The thing is travis allows to setup different versions of osx. now it is produced only one: macosx_10_6_x86_64. Will this not work on all osx versions? Will the wheels make osx user life easier? Does it work at all (I could not test the produced wheels as I have no mac osx)

**Comment by thomasaarholt** [comment]
Tell me what to do, and I'll try it in a virtual environment on my mac.

On 14 July 2016 at 15:27, Petras Jokubauskas <notifications@github.com>
wrote:

> hmm maybe there is the place to ask this. From #949
> <https://github.com/hyperspy/hyperspy/pull/949> it is possible to build
> osx wheels (I saw it is done for 1.0 release draft already). The thing is
> travis allows to setup different versions of osx. now it is produced only
> one: macosx_10_6_x86_64. Will this not work on all osx versions? Will the
> wheels make osx user life easier? Does it work at all (I could not test the
> produced wheels as I have no mac osx)
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/hyperspy/hyperspy/issues/1053#issuecomment-232681409>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACmGj7ekwFPAU6_7U0OcnmO2lZABge8Mks5qVkdJgaJpZM4Itbhk>
> .
>



-- 
Thomas M. Aarholt
Reading for DPhil in Nuclear Materials
University of Oxford

Mobile: 07794820885
Email: thomasaarholt@gmail.com

**Comment by to266** [comment]
FYI the conda-forge PR was just merged, so should be available in a bit!

(`conda install -c conda-forge hyperspy`)

**Comment by thomasaarholt** [comment]
We heard good things about the conda install. I'll check it out in a bit.

**Comment by francisco-dlp** [comment]
I've tested it in windows and it works like a charm! @thomasaarholt, have you tested it in mac?

@to266, would you consider posting the news in the mailing list? I've just sent a PR #1158 to update the docs.

**Comment by thomasaarholt** [comment]
Yep, works like a charm!

**Comment by tjof2** [comment]
I think this can be closed now - we test on Mac via azure pipelines and the user guide should cover all the details already?
