### ISSUE TITLE
Release milestones

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#1060]
Since from v1.0 we'll be following the [semantic versioning](http://semver.org/) standard I suggest creating the three following milestones:

* patch (current next_maintenance_release)
* minor (anything but bug fixes that don't break the API)
* major (API changes)

Do you agree? Maybe something more verbose is better e.g. `next_patch_release`?

**Comment by dnjohnstone** [comment]
I think the approach you've taken and as described in #1170 is the right one. Would propose considering this issue closed as I think everyone has had time to raise objections if they had felt moved to do so.
