### ISSUE TITLE
Archlinux installation instructions are old

### ISSUE THREAD

**Issue by to266** [hyperspy/hyperspy#1069]
As the title says, the archlinux installation instructions are old / deprecated (written for python2 as well). As it stands now, they should be at least removed from the user guide, preferably updated with a working set of steps.

**Comment by francisco-dlp** [comment]
Fixes in #1070

**Comment by jat255** [comment]
If you leave this open, I should be able to actually fix it in the next few days or so.

**Comment by ericpre** [comment]
It looks like the files in doc/package_lists are also out of date.

See #451 for details.
https://aur.archlinux.org/packages/hyperspy-git/ should also be out of date. How easily/likely would it be updated?

**Comment by jat255** [comment]
Whoops, looks like I never actually got around to fixing it. Sorry about that. @to266 made the AUR package. I think we should get that updated, and then update the documentation just pointing to the AUR. That would be the easiest in terms of maintenance.

**Comment by ericpre** [comment]
That sounds good! Does it mean that the files in the `doc/package_lists` folder will not be necessary anymore?

How robust do you think it will be? Particularly, if the library dependency is changed -for example, it could be changing version dependency or adding one more library? Something to mention in the dev guide?

**Comment by jat255** [comment]
Yes, I believe that the `package_lists` could be removed in that case. 

It should be pretty robust, since all the package does is clone the git repo and call `python setup.py install`. If the dependencies are handled by Python's `setuptools`, then there shouldn't be any problems (in theory).

**Comment by ericpre** [comment]
Sounds easy enough! :)

**Comment by to266** [comment]
https://aur.archlinux.org/packages/hyperspy/

Note that this does not work particularly well due to the `pyqt4` bug, even though `python-pyqt4` is installed. I guess we'll have to check once it's fixed on our end

**Comment by jlaehne** [comment]
I updated the AUR package https://aur.archlinux.org/packages/hyperspy/ and added the `hyperspy-gui-...` and `link-traits` packages.
(dependencies are defined and listed there so that aur-helpers like yay would install them automatically from the arch repos/AUR).

Currently, Arch is not mentioned any longer in the documentation. Should we add a one-liner that points to the existence of this AUR package? Whoever is using arch should not need more detailed instructions for the installations, but might be good to point out that option.

**Comment by ericpre** [comment]
If the AUR package is easy enough to maintain and would not be deprecated anytime soon, a line in the user guide would be good!

**Comment by francisco-dlp** [comment]
I think that, unless there is a maintainer of the AUR package (somebody using an ARCH distributions obviosuly) we should not add it to the user guide. @jlaehne, can we count with you for that?

Shall we consider adding openSUSE too?

**Comment by jat255** [comment]
I also use Arch, so I could help maintain an AUR package, if needed

**Comment by jlaehne** [comment]
Well, I'm planning on maintaining the packages, it is not much of an effort. And would be nice if it helps others and not only the one colleague of mine who asked me to do so in the first place.

**Comment by jat255** [comment]
Having a `hyperspy-git` package that points to the Release next minor (for users looking for new features) could also be a good idea. Structuring a git-versioned `PKGBUILD` is a little different, but is nice because it stays constantly up to date

**Comment by jlaehne** [comment]
For the `hyperspy_gui_...` packages it would be good if there are proper releases again in the future - at the moment it downloads the master file, so I have to change the hash on every merge (but in the end there are not so many merges for the gui packages).

**Comment by jlaehne** [comment]
From the thread above, there used to be a `hyperspy-git` package, which was apparently deleted? So far I do not have experience with such a `PKGBUILD`, but I guess there should be enough examples around.

**Comment by jlaehne** [comment]
@jat255 I could add you as co-maintainer on the AUR if you like (same username?). I took over the package half a year ago as it was largely outdated.

**Comment by jat255** [comment]
@jlaehne yes, please do add me (same username). I can take care of the `hyperspy-git` package, since I've done a few of them. Since there are not firm releases of the GUI packages, I suppose it doesn't make sense to do the same for those.

**Comment by jlaehne** [comment]
I will have a look at the `hyperspy-git` once you created it. Might actually be a solution for the gui packages as well as long as they do not have firm releases (but instead and not in addition)?

**Comment by jat255** [comment]
I discovered #2518 while testing this out, but I believe I have the `PKGBUILD` set up correctly. I'll upload it tomorrow (it's late here) so you can test it out @jlaehne.

**Comment by jlaehne** [comment]
@jat255, I created the new python-* packages on the AUR and asked for a merge of the old ones.

**Comment by jat255** [comment]
@jlaehne Awesome, hopefully it doesn't take them too long to merge them. Can you test out https://aur.archlinux.org/packages/python-hyperspy-git/ ? I built the package in a clean chroot, and verified it works cloning directly from AUR, so I think it should work, but it's always good to get a second set of eyes on it

EDIT: AUR is being really slow for me right now (I don't think it's just me), but it eventually worked to download

**Comment by jat255** [comment]
I just tested your `python-hyperspy` and the GUI packages, and they appear to work okay for me (i.e. they built, installed, and I did some very basic testing in Python)

**Comment by jlaehne** [comment]
I also tested the built, install and basic use of `python-hyperspy-git` just now. LGTM

**Comment by ericpre** [comment]
Great!
