### ISSUE TITLE
Failed to find module tqdm

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1072]
Having just done a big update of all my python modules (by `conda update --all`), I'm finding issues with importing hyperspy.api.

`ImportError: No module named 'tqdm'` is the error, and below is the context. It probably has to do with my updating or the fact that I'm on Mac. Will investigate.

```python
import hyperspy.api as hs

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-6-5e09b9d2af1c> in <module>()
----> 1 import hyperspy.api as hs

/Users/thomas/Dropbox/0_Git/GitHub Desktop/hyperspy/hyperspy/api.py in <module>()
     61 
     62 from hyperspy.Release import version as __version__
---> 63 from hyperspy import signals
     64 from hyperspy.io import load
     65 from hyperspy.defaults_parser import preferences

/Users/thomas/Dropbox/0_Git/GitHub Desktop/hyperspy/hyperspy/signals.py in <module>()
     37 # -*- coding: utf-8 -*-
     38 
---> 39 from hyperspy._signals.spectrum import Spectrum
     40 from hyperspy._signals.image import Image
     41 from hyperspy._signals.eels import EELSSpectrum

/Users/thomas/Dropbox/0_Git/GitHub Desktop/hyperspy/hyperspy/_signals/spectrum.py in <module>()
     23 
     24 from hyperspy.exceptions import DataDimensionError
---> 25 from hyperspy.signal import Signal
     26 from hyperspy.gui.egerton_quantification import SpikesRemoval
     27 

/Users/thomas/Dropbox/0_Git/GitHub Desktop/hyperspy/hyperspy/signal.py in <module>()
     53 from hyperspy.defaults_parser import preferences
     54 from hyperspy.misc.io.tools import ensure_directory
---> 55 from hyperspy.external.progressbar import progressbar
     56 from hyperspy.gui.tools import (
     57     SpectrumCalibration,

/Users/thomas/Dropbox/0_Git/GitHub Desktop/hyperspy/hyperspy/external/progressbar.py in <module>()
     17 # along with  HyperSpy.  If not, see <http://www.gnu.org/licenses/>.
     18 
---> 19 from tqdm import tqdm
     20 
     21 

ImportError: No module named 'tqdm'
```

**Comment by to266** [comment]
Well it's a new requirement for hyperspy.

Either 
`pip install tqdm`

or
`conda install -c conda-forge tqdm`

**Comment by thomasaarholt** [comment]
Yep, just after posting I tried and realised I just didn't have the package. Is the pip install hyperspy aware that tqdm is a dependency? I'm just trying to figure out why it didn't install it when I tried.

**Comment by thomasaarholt** [comment]
Hah. I just spotted the changes in the latest commits. I don't know why it didn't work for me. I probably did something less-than-intelligent.

**Comment by francisco-dlp** [comment]
Actually it seems that tqdm is missing from the anaconda environment.

**Comment by to266** [comment]
yes, hence why my suggestion is to use `conda-forge` :)

**Comment by francisco-dlp** [comment]
I see. However, anybody trying to follow the instructions to install hyperspy using the conda environment will face this issue...

**Comment by knageswara78** [comment]
In Anaconda, steps to install the package.

1. Navigate to ‘Environments” and Search for your package. 
2. That package will be displayed and click on Apply. 

Now the package is installed and it can be used right away.

Please share your feedback.
