### ISSUE TITLE
Remove simulation subclasses

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#1103]
Currently there are four simulation signal subclasses: `Simulation`, `EELSSpectrumSimulation`, `ImageSimulation`, `SpectrumSimulation`. However, these classes are mostly empty, except for a couple of methods which simply add noise to the data. Here I propose to simply remove them as, in my opinion, these subclasses make little sense. HyperSpy is about multi dimensional data analysis—why analysing a simulated signals should be any different from analysing experimental ones?

Ones #1058 is merged I propose to submit a PR to remove these classes, unless we decide here otherwise.

**Comment by tjof2** [comment]
I think this sounds like a good idea, especially since `EELSSpectrumSimulation` could lead people to think HyperSpy does DOS calculations...! 

That said, keeping the functions to add noise, to e.g. test denoising methods, would be useful. Perhaps moved elsewhere?

**Comment by francisco-dlp** [comment]
Implemented in #1126.
