### ISSUE TITLE
TEMParametersUI has no attribute beam_current

### ISSUE THREAD

**Issue by dnjohnstone** [hyperspy/hyperspy#1108]
The set_parameters UI for TEM_EDS signals is broken for the current master following changes to the metadata structure with the addition of new methods for EDS quantification.

The error is "TEMParametersUI has no attribute 'beam_current'"

Should be easy to fix.

**Comment by k8macarthur** [comment]
Oops, I thought I fixed this. Can you show the error?

**Comment by k8macarthur** [comment]
I've checked this with my current workbook and can't seem to reproduce that specific error. However, when I saw this before I think I worked out that the code seemed to care about the order of the set_microscope_parameters assignment. 

The following seems to work fine for me with no error:
`
Pt_wedge.set_microscope_parameters(beam_energy = 200)
Pt_wedge.set_microscope_parameters(live_time = 1)
Pt_wedge.set_microscope_parameters(beam_current = 0.05) #in nA
Pt_wedge.set_microscope_parameters(real_time = 3.5) #dwell time per pixel
`

**Comment by francisco-dlp** [comment]
@dnjohnstone or @k8macarthur, could you confirm that #1135 fixes this issue?
