### ISSUE TITLE
Plot "already connected to" error 

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1109]
I've been getting this error on and off for the past month or so. This is on Mac, running the latest Jupyter notebook and hyperspy.
Sometimes, when plotting the same signal twice (rerunning s.plot() for instance), I get the attached error. 

I suspect that it has something to do with the matplotlib backend, but I'm not sure. For reference, during my code (for no real reason) I start off with `%matplotlib`, and later on run `%matplotlib inline` a few times.

Here's a screenshot, and a [gist of the error](https://gist.github.com/thomasaarholt/4ca2451ac729afa9e0f8f24a7023247f).
<img width="771" alt="screenshot 2016-06-30 19 04 44" src="https://cloud.githubusercontent.com/assets/2721423/16498889/cce9cd50-3ef5-11e6-8fd9-3b9a8da55c8e.png">

**Comment by vidartf** [comment]
Does #879 fix this issue?

**Comment by thomasaarholt** [comment]
I'll try checking it out.

**Comment by thomasaarholt** [comment]
This appears to completely solve the issue.

**Comment by francisco-dlp** [comment]
Can this be closed then?

**Comment by thomasaarholt** [comment]
Yes, I believe so. I haven't tested it extensively, but I'm almost certain
the pull request fixes it.
