### ISSUE TITLE
s.plot_explained_variance_ratio() plots the same plot twice. Almost.

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1119]
Bit of an odd one. `s.plot_explained_variance_ratio()` plots the same plot twice on the same plot, separated by a small distance. `s.get_explained_variance_ratio()` works fine. This has been an issue for the past month (I normally plot the data via matplotlib rather than s.plot...)

<img width="693" alt="screen shot 2016-07-04 at 12 33 25" src="https://cloud.githubusercontent.com/assets/2721423/16559305/faafde46-41e3-11e6-82a4-4231956c2187.png">

**Comment by francisco-dlp** [comment]
I couldn't reproduce this issue, which MPL version are you using?

**Comment by thomasaarholt** [comment]
This is no longer a problem, it would seem. Not sure why.
