### ISSUE TITLE
HyperSpy's hdf5 format needs standard for date and time

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#1136]
Currently HyperSpy doesn't have a standard way of storing date and time metadata. There are many standards available. We could simply choose one that is well supported by a standard python library.

**Comment by dnjohnstone** [comment]
I think this is a good idea - any thoughts on which one might be the one to take?

**Comment by ericpre** [comment]
I looked a bit around on google to handle date and time:
- [python datetime](https://docs.python.org/3.5/library/datetime.html)
- [numpy datetime](http://docs.scipy.org/doc/numpy/reference/arrays.datetime.html)

There are other libraries that have their own date and time implementation with much more features.
Numpy offers higher precision than the python datetime (microsecond precision).
Shall we go for numpy datetime? I think it would make sense for a data analysis library and it's possibly the most straighforward to use.

**Comment by francisco-dlp** [comment]
Sounds good, it seems that the default format of numpy's datetime is ISO 8601 and that it has ns accuracy. +1 for storing dates in ISO 8601 txt with up to ns accuracy. Would parsing dates in file readers using numpy and storing them in metadata as ISO 8601 strings be a sensible action plan?

**Comment by francisco-dlp** [comment]
We could keep our current `General.time` and `General.date` entries, and just agree to store time and date information there in ISO 8601.

**Comment by ericpre** [comment]
What would be better: to have `General.time` and `General.date` as a `numpy.datetime64` object or to store it as string?
Or maybe make a `Metadata` class that inherits from `DictionaryTreeBrowser` and can handle the [metadata specification](http://hyperspy.org/hyperspy-doc/current/user_guide/metadata_structure.html) with specific methods? This would allow storing the `numpy.datetime64` object as a private attribute and display the date and time in `General` as strings, which will looks much more readable for the user.

**Comment by francisco-dlp** [comment]
I think that storing the date and time in string would be better. Currently they're not used anywhere in the code. The rule of thumb is too keep things as simple as possible.

If any functions uses it, it can easily convert the string to e.g. numpy datetime64 for consumption. Such as function could be e.g. stack which could automatically order a set of files for stacking using date and time info.

**Comment by ericpre** [comment]
Fixed in #1240.
