### ISSUE TITLE
ENH: run tests on minimal environment

### ISSUE THREAD

**Issue by sem-geologist** [hyperspy/hyperspy#1146]
with this #1144 emergent fixes, I got the idea if it would not be clever to prevent such stuff in future by testing stuff also on minimalistic environment, without lxml, h5py, cython, compilers etx. present. The linux on travis is anyway undersaturated as now builds waits mostly for osx. So we could add one more linux environment to the travis matrix, which would test things on very minimalistic environment with bare minimum.

**Comment by francisco-dlp** [comment]
Sounds like an excellent idea.

**Comment by sem-geologist** [comment]
the feature got added, so closing
