### ISSUE TITLE
SAMFire crashes when starting it after closing the plot figures

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#1148]
SAMFire crashes after closing the previously plotted plot window.

You can workaround this issue by setting the SAMFire instance `_plot` attribute to `None` before starting SAMFire e.g.
 
```python

samf._figure=None

```

**Comment by to266** [comment]
....actually I'm not able to reproduce this bug - I may have accidentally fixed it at some point and forgotten. I'll close for now
