### ISSUE TITLE
Mixed types in unbcf_fast

### ISSUE THREAD

**Issue by tjof2** [hyperspy/hyperspy#1166]
@sem-geologist is probably best placed to answer this. I think I missed it when the PR was still open.

Line 145-146 in [`unbcf_fast.pyx`](https://github.com/hyperspy/hyperspy/blob/master/hyperspy/io_plugins/unbcf_fast.pyx) is:
```
cdef int dummy1, line_cnt, i, j
cdef uint32_t height, width, pix_in_line, pixel_x, add_pulse_size
```
Then in lines 152 (and again in 154) you are doing a for-loop over a range, which in C becomes:
```
for (int linecnt = 0;  linecnt < height; linecnt+=1) { ... }
```
where height is `uint32_t`. 

As a result, my compiler goes crazy with warnings about comparing signed and unsigned integers. Warnings are a little bit annoying :-D

Also note that your maximum loop variable is defined as:

-  +32,767 when `int` is 16-bit
-  +2,147,483,648 when `int` is 32-bit

But `height` can be up to 4,294,967,296. I know that seems rather silly, but particularly since `int` is [not guaranteed to be 32-bit](http://stackoverflow.com/questions/1231147/is-int-in-c-always-32-bit) might it be better to update this to be consistent?

**Comment by sem-geologist** [comment]
Elephants will fly, before Bruker with its delphi based solutions will even dream about such a raster size. Both pre v2 and v2 Esprit systems can't save larger rasters than 4096x4096 pixels.
However I think I should check the int/uint32 and unify it in both places. Thank you for report. @francisco-dlp , could you mark this as a bug?

**Comment by tjof2** [comment]
I did think it was a large raster size!

**Comment by sem-geologist** [comment]
@tjof2 , could you test this #1168 out?

**Comment by tjof2** [comment]
@sem-geologist  done, see PR

**Comment by sem-geologist** [comment]
@tjof2 ,as #1168 got merged this could be closed
