### ISSUE TITLE
TestSamfireMain.test_multiprocessed fails randomly

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#1182]
See e.g. [this build](https://travis-ci.org/francisco-dlp/hyperspy/builds/146081056)

**Comment by to266** [comment]
https://github.com/hyperspy/hyperspy/pull/1191

**Comment by francisco-dlp** [comment]
Still failing see e.g. [this](https://travis-ci.org/francisco-dlp/hyperspy/jobs/147705930). Wouldn't just seed fix the issue for good?

**Comment by to266** [comment]
That's how I fixed it for 64bits, yes. 
As you can see even now it actually uses the seed, it just does not work well enough for 32bits:
https://github.com/hyperspy/hyperspy/pull/1191/files#diff-e341fa460a1e5ab7761895d60672eef2R310

I'll see what I can do

**Comment by ericpre** [comment]
This issue seems to be gone, because it didn't occur for a while!!
