### ISSUE TITLE
multifit broken?

### ISSUE THREAD

**Issue by dnjohnstone** [hyperspy/hyperspy#1186]
Currently getting an error "suspend_update() got an unexpected keyword argument 'update_on_resume'" when using multifit with a Model2D in master - not 100% certain where this is from though with all the recent changes.

It may well be only for Model2D.

**Comment by dnjohnstone** [comment]
I've fixed this locally - it did only apply to Model2D. It had happened before for the same reason and had been fixed but was presumably reverted in one of the many merges that affected model fitting.

I'll make a PR in the next couple of days when I've separated out the fix from my local branch of many changes.

**Comment by francisco-dlp** [comment]
Fixed in #1187.

**Comment by francisco-dlp** [comment]
@dnjohnstone, can you provide a more detailed description of the bug in title and first comment?
