### ISSUE TITLE
NEW: Cameca EMPA impDat file reader

### ISSUE THREAD

**Issue by sem-geologist** [hyperspy/hyperspy#1209]
I hope hyperspy community have some knowledge of electron microprobe (that such machines do exist) which are equipped with multi WDS spectrometers.
Differently than SEM-TEM EDS techniques, WDS is selective, and during element mappings not all the spectra but just selected measured narrow bands of generated  X-rays and optionally the backgrounds are measured and saved.  
I would like to make a reader for Cameca's EMPA impDat format.
I think implementing this format could enlarge the hyperspy userbase (not very much, as there are not so many machines in the world compared to SEM and TEM), and element mappings done on those machines would benefit a lot from using hyperspy data crunching techniques.
As I have no specification of this format provided by cameca or third parties differently than #1154, this would be based completely on reverse engineering (which is WIP).
The format:
- The format is binary, non human readable
- The format from one point of view is much simpler than RE by me bruker bcf, as it contains no compression, no chunking, no virtual file systems, tables of files and so on.
- On the other hand cameca format is very dynamic (the size of data is different, it is impossible to jump straight to address and to get to mapping arrays data have to be read step by step). The arrays itself are not disrupted, so numpy is enough to read them effectively (no need of cython, xml parsing). (means that dependency will be just `python + numpy`)

While I am near the end of RE of format, I have many uncertanities how to map the data into hyperspy format. The format contains such info/structure:
- can contain multiply data-sets where such dataset contains:
  - counts/second  2D array (image with depth of float32) (sometimes multiply arrays which have to be summed and averaged to get the counts of particular element)
  - metadata:
    - stage coordinates (x,y,z)
    - resolution
    - dwell time
    -  many internal options how the data are gathered
    - datestamp
    - dataset comment
    - positions, type of crystal in spectormeter (WDS) and configuration of gas proportional counters (PHA and such stuff if it says anything)
    - HV and beam current
    - It can contain standard for given element (not tested)

So my main question is: what could be the best strategy in returning the data? stack of images or rather a list of signals? what type of signals I should use (2D, 0D?)

**Comment by dnjohnstone** [comment]
I think this is a good idea but would just flag that this is exactly the kind of thing that makes me a bit unsure about how best to implement #821.

Many people would not consider this or #1154 to be 'Electron Microscopy' - so if we have a situation where we've split the current HyperSpy into hyperspy and hyperspy-em -- where should they go?

It seems a bit pointless to me to have an EMPA package and a SIMS package, and an XPS package and a Raman package and an IR package -- but once you start splitting them off, where do you stop?

I should add that I think separating off the general 'data processing' approach might make that core general stuff more attractive to the more hardcore coders which would be great for the project - so I do think some kind of split is good.

**Comment by to266** [comment]
@dnjohnstone for me the obvious way then is to split hyperspy into:
 - `hyperspy` (the core)
 - `hyperspy-em` (all em-related stuff, like components, quantifications, etc.)
 - `hyperspy-io` (input/output plugins that this and #1154 would go to). The name is obviously just a quick random thing here.

**Comment by to266** [comment]
The additional benefit then would be that the core `hyperspy` will only have to truly support its own file format (i.e. the hdf5), while the rest would be left to their own individual things.

The best (probably) way to do this would be to actually have `hyperspy-io` be a thin wrapper / api thing, and a bunch of submodules that point to other repos, where the actual users of the plugins are able to keep it up to date

**Comment by dnjohnstone** [comment]
ok - but lets say the next step is to make a class EMPA or a class SIMS -- where will we expect that to go? Or will it necessitate the creation of a new package, and if that is the case, is that what we want?

**Comment by francisco-dlp** [comment]
I would say, why not? If you're a SIMS users you're most likely just interested in reading the data and using core hyperspy. You don't care about the EM features. So, installing hs-core + hs-sims is better that installing the current hyperspy if if hs-sims just provides support for reading a SIMS format.

**Comment by magnunor** [comment]
At the risk of derailing the original issue too much:

It would maybe be useful to have a hs-misc (?) where for example SIMS functionality could be included, and if it grows sufficiently large it can be spun off into its own separate package. I'm guessing making too many separate small packages would add unnecessary amount of complexity.

**Comment by sem-geologist** [comment]
but EMPA is electron microscopy! just giving more attention to precise and tightly controled x-ray measurement, also some of the mappings is hybrid, (WDS and EDS). (however I should check out if it is not possible to save whole eds spectra per pixel. (in the previous software there were some options to do that). Also single spectras can be optained by wds scan which can be converted into eds like spectra, there is a lot of stuff overlaping with wha is allready implemented in hyperspy and I think could be subclassed and used for WDS.

**Comment by dnjohnstone** [comment]
My point was not so much that it shouldn't be included in EM but that splitting off as only EM leads to arbitrary delineation between techniques. For sure if, for example, EMPA was in a separate package generates work. I'm going to comment further on #821 because that's the right place for it... I'm just trying to make a point about potential pitfalls with splitting off hyperspy-em -- perhaps this wasn't the best example.

I do think this is a good idea in any case - and I also would consider EMPA and WDS pretty standard materials characterisation techniques.

**Comment by francisco-dlp** [comment]
@sem-geologist, #1220 introduces a powerful and general tool to customise HyperSpy's view of the dataset.Therefore, I would argue that when loading data from files we should keep the data exactly in the same order as it was recorded and it is up to the user to configure the axes after loading. Notice that this is not what most reader do currently, but I would consider this a bug.

Whether the signal should be 0D or 2D depends on the operations that are most commonly performed on this sort of signal. If the majority operate in 2D, then 2D, otherwise 0D.

Does it make sense?

**Comment by thomasaarholt** [comment]
I'm sorry I didn't see this previously - I spent a chunk of time reverse engineering Cameca's `.im` format last month, so I'm very happy to help with this! 
Have you created a pull request yet? I'd like to see the code!

**Comment by sem-geologist** [comment]
@thomasaarholt , I am aware of your work, and looked to the matlab code you linked before... I can be sure that formats are completely different. EMPA software is made in .net and of course all bad practices which is embraced by .net is used. It looks for me that very likely the format is partial memory dump :/ M$ frameworks and it using crowds loves that approach. (just look to the terrible doc or docx formats). I guess the format were made by completely different team. I am actually very much outraged by my findings: software generally is very crashy and have tons of tons of graphical glitches is syncronoes (freezes gui every time something is changed) lags like a hell on xenon workstation. while our old software made for SUN workstation with solaris (if i remeber rigth it had 16MB of ram) was fully asyncronoes, blazing fast. generally work which could be done in few minutes (saving and exporting of data) now takes an hour (that is called progress and moving to modern os).
ok enougth of rant...

I still didt created pull request as I am still trying to sort out the structure of the file which looks.
I have plans to get fully RE all of cameca EMPA formats which have some overlaping structure. that approuch also allows me to better understand what some unkown records or places in the file would hold. generally EMPA produces 4 type of files with such extensions:
- wdsDat — files which are used to save datasets with WDS scans. this could be of interset in the future to implement in hyperspy, as dataset also can be not only single points but allso a grid.
- imDat — files where are mapping datasets saved or the simple BSE, SEI or CL images. this is planed to implement to hyperspy now.
- calDat — files with calibrations for selected elements and selected spectrometers. this probably will be of no use i hyperspy. 
  - .ovl — files containing peak overlap corections acompanieing calDat fils if overlap corection is used.
- qtiDat — files containing datasets of quantified analyses. same as wds files, if dataset would be grid then it would have some potential t be implemented to hyperspy.

there is 4 corseponding file formats for setups which use part of same file structure but those are rather off interest as I am not iterseted in generating input/control files for that crapy cameca's software. the time would be much better spent RE low level control of machine (which is done through ethernet interface) but those could be far far future plans...

I mentioned datasets...EMPA is automated machine, and different places of interset can be analysed sequentually. the dataset types are: point, beam line, stage line, beam grid, stage grid, polygon (basically grid with mask)...
so everything ehat canbe grid could be implemented i hyperspy.

structure:
- first byte gives a hint about what kind of file it is (wds, wds setup, image, image setup...)
  then there is 'fxs' string... yeah parts of strings in cameca files are in reversed order, so reversing it is 'sxf' which marks general class of camecs empa machines (SX. i.e. Model SX-100, SX-50, SX-5FE..) and can mean SX file. so there is general file header used in most file types which holds: file discussed file signature, track of file changes, comment of the file (this is same for all 9 known file types).
- then for results there is dataset header struct which contains few flags of instrument control (i.e. how often to measure background) where last element in this structure is the number of datasets in the file.
- then every dataset have its own header, where it is same for every type of results (contains such info as x,y,z dwell time, accumulation of frames position of the beam, resolution and so on...where in the end of struct it have number of itemz in the dataset)
- item of dataset have header (which is same for all types), data (which is different for every format), outer (my main headache now, it is dfferent for different kind of files, contains some offsets with lenght of !=4 bytes) which contains such important data as the date stamp, or if it is grid- coordinates.
- then there is dynamic lenght outer with differnet kind of flags for intrumen control.

**Comment by thomasaarholt** [comment]
Jesus. And I thought **I** had a bad time. I wanted to set the whole format on fire. Several times. 
With the .im format, I just couldn't understand why they had different orders to saving the file depending on whether you saved it on Windows or Unix (not talking about endianness/byte order - the actual byte positions were completely different).

I think that at some point the team must have changed for the im format as well, as the accompanying clear-text info file contains information that is available in the binary file, just frigging impossible to get at. I think they just went "screw this" and created an extra file with the information they needed the most.

**Comment by sem-geologist** [comment]
I guess different kind of endiannes were used due to simply dumping the memory to file, so it would be layed so as the OS were using it in the internal memory. endianness is not such a huge problem in my opinion, cmplete incompetence of using proper types I think is most outstanding issue! they use float (not double, but just 32 bit single precission float) for stuff which could be saved with 16bit int, or use int where float type would be more appropriate. I also found that the gui crashes in some cases as it is excpecting to read int, but file have float... yeah...

**Comment by thomasaarholt** [comment]
Re memory dumping: thanks for explaining that. I was just so surprised to see it done this way. It's icky!

**Comment by sem-geologist** [comment]
I am keen on closing this issue, as that is niche formats (there is like just more than a thousand of cameca electron microprobes in the world much less than SEM/TEM). BTW after 8 years I finally had reverse engineered Cameca formats - Oh that feeling...
