### ISSUE TITLE
Update some metadata specification

### ISSUE THREAD

**Issue by ericpre** [hyperspy/hyperspy#1222]
As discussed in #1173 and #1136, we need to update some of the metada specifications:

- [x] Add authors attribute to `General`
- [x] Add date and time information as attribute of `General`. This most simple way to implement it is store it as string that can be parsed easily to numpy.datetime64 for processing.
- [x] Add doi attribute to `General`
- [x] Add notes attribute to `General`
- [x] Add quantity attribute to `Signal` as "name (units)"
- [x] Add `camera_length` and `camera_length_units` attribute to `Acquisition_instrument.TEM` and 

The quantity metadata can then be used for the intensity axes, see #546.

If there any other issue that could be related to this one? Any other relevant information to add to metadata?

**Comment by dnjohnstone** [comment]
+1 for date and time using numpy.datetime
+1 for notes - that seems reasonable
+1 for authors - assuming you mean the person who saved the file, can be useful within groups at least

Not sure which doi you mean? The HyperSpy one? If so, what for?

Quantity sounds a bit vague? - what's the thinking there?

**Comment by francisco-dlp** [comment]
I think that the idea behind authors and doi is making it easy to know how to cite the data. So doi should be the data doi and authors those who performed the experiment or simulation.
quantity would be e.g. "temperature". This is basically the "name" of the intensity axis. Is there a better word for this?
