### ISSUE TITLE
ROI lacking exception error message

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1229]
Calling the following with left, right... outside the range of the plot raises a `ValueError` without message. It would be useful to add messages to indicate what is failing.

Calling it with `top > bottom` or `left > right` raises a `TypeError`, again with no message.

``` python
s.plot()
Rect = hs.roi.RectangularROI(left,right,top,bottom)
sRect = Rect.interactive(s)
```

**Comment by ericpre** [comment]
This has been fixed since then.
