### ISSUE TITLE
Metadata from digital micrograph files

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#1238]
Currently, when loading dm-files in HyperSpy much of the metadata is not included in s.metadata. However, there is a lot of metadata contained in the s.original_metadata. 

We could include things like microscope type, camera length, time of acquisition and pixel time into s.metadata.

**Comment by francisco-dlp** [comment]
+1!

**Comment by ericpre** [comment]
Except for the camera length, #1232 should fix it? I will add camera length to the metadata. Is there any other information worth adding to metadata?
Some of the metadata was not mapped properly from the DM files, but it should be fixed now. I m almost finished with #1232, I will push the commits soon.

**Comment by magnunor** [comment]
@ericpre, some possible metadata fields from DM which could be nice to add:
- `ImageList.TagGroup0.ImageTags.Session_Info.Operator`
- `ImageList.TagGroup0.ImageTags.Session_Info.Specimen`

Also, for EELS-data it could be useful to include some of the spectrometer information. This can be included in `s.metadata.Acquisition_instrument.TEM.Detector.EELS`:
- `ImageList.TagGroup0.ImageTags.EELS_Spectrometer.Aperture_label`
- `ImageList.TagGroup0.ImageTags.EELS_Spectrometer.Dispersion_eVch`
- `ImageList.TagGroup0.ImageTags.EELS_Spectrometer.Instrument_name`

**Comment by francisco-dlp** [comment]
Would it make sense to map Operator to authors? Specimen -> Sample.description? Instrument_name -> TEM.microscope?

How is Dispersion_eVch different for the scale of the energy loss axis?

**Comment by magnunor** [comment]
True, no need to add Dispersion_eVch to the metadata as well.

Instrument_name refers to the spectrometer name, so I guess it can go both places. Both in the EELS and the microscope metadata "box".

**Comment by FWin22** [comment]
It just appeared to me that the acquisition time of the data loaded from the metadata of dm3 files may cause problems due to the time formatting in `digital_micrograph._get_time` and `digital_micrograph._get_date`  such as`dt = datetime.strptime(date, "%m/%d/%Y")`. If the data was acquired on a computer with non english system the time stamp might be different for other countries. This will cause errors when loading the file.

**Comment by magnunor** [comment]
@ericpre, https://github.com/hyperspy/hyperspy/pull/1240 implemented most of this. Thanks!

Loading a random EELS line scan gives me this metadata:

```
├── Acquisition_instrument
│   └── TEM
│       ├── Detector
│       │   └── EELS
│       │       ├── aperture_size = 2.5
│       │       ├── collection_angle = 100.0
│       │       ├── frame_number = 1
│       │       └── spectrometer = GIF Quantum ER
│       ├── acquisition_mode = STEM
│       ├── beam_current = 0.0
│       ├── beam_energy = 200.0
│       ├── camera_length = 15.0
│       ├── convergence_angle = 0.0
│       ├── magnification = 5000000.0
│       └── microscope = JEM-ARM200F
├── General
│   ├── original_filename = EELS Spectrum Image.dm3
│   └── title = EELS Spectrum Image
├── Sample
│   └── description = DWNC
└── Signal
    ├── Noise_properties
    │   └── Variance_linear_model
    │       ├── gain_factor = 1.0
    │       └── gain_offset = 0.0
    ├── binned = True
    ├── quantity = Intensity (Counts)
    └── signal_type = EELS
```

Having the acquisition time would be nice, what do we have to do to sort out the issues noted above? I'm guessing Digital Micrograph has some way of keeping the time and date correct between different time locales?

**Comment by ericpre** [comment]
@magnunor, normaly, the date and time are parsed to the metadata from the tag:
`ImageList.TagGroup0.ImageTags.DataBar.Acquisition Date`, [there](https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/hyperspy/io_plugins/digital_micrograph.py#L811).
Do you have this tag in the origin tags of your DM file?

@FWin22: thanks for reporting, this need a bug fix.... And I don't how we can obtain the location settings of the computer on which was acquired the data... so the best we can do for now, it's just to try a few commun formatting...

**Comment by FWin22** [comment]
@ericpre: I don't even think that DM necessarily saves this information. I have the impression they just save the time as a string. This could of course solve our problem as well. However using `datetime.strptime` is definitely more elegant.

**Comment by magnunor** [comment]
@ericpre, datasets acquired using the Spectrum Image functionality does not seem to have the `DataBar` tags. However, the time information can be found in `s.original_metadata.ImageList.TagGroup0.ImageTags.SI.Acquisition.Date`, `s.original_metadata.ImageList.TagGroup0.ImageTags.SI.Acquisition.Start_time` and `s.original_metadata.ImageList.TagGroup0.ImageTags.SI.Acquisition.End_time`.

I've also experienced the bug when loading datasets due to the locale.

On a more general note: should we maybe "encapsulate" the metadata loading inside a `try, except` to avoid bad metadata stopping people from loading datasets? Since not being able to load data like that can be very annoying for people who doesn't know how to fix them manually.

**Comment by FWin22** [comment]
@magnunor: Would you encapsulate the whole loading sequence in one big `try, except` block or make one `try, except` for every single metadata item. 
I am asking this, because it would be bad if all the metadata is thrown away when loading the file, only because one single item causes an error, such as the local time setting.

**Comment by magnunor** [comment]
@FWin22, having it for every one would maybe make the code a little messy? Not really certain how to best do it. At least the error-prone ones could have the encapsulating. 

The best way would maybe be to make a function which we call when we want to retrieve a specific metadata tag, and the function includes the `try, except`.

**Comment by FWin22** [comment]
@magnunor: Yes, we should not make the code too messy. Using a function seems reasonable to me.

**Comment by ericpre** [comment]
Done in #1312.
