### ISSUE TITLE
Resizing a plot's window cuts off the labels

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1239]
Resizing the window of a plot by dragging the edge of the window cuts off the labels (see x-axis on this image). Should I just be plotting it with fixed width and height instead? I am dragging the edges in order to "compress" the plot a bit on the y-axis.

<img width="752" alt="screenshot 2016-08-08 23 01 53" src="https://cloud.githubusercontent.com/assets/2721423/17497955/51499e92-5dbc-11e6-9f72-e29460c04072.png">

**Comment by francisco-dlp** [comment]
You could try calling tight_layout after resizing. This is rather a mpl issue.

**Comment by thomasaarholt** [comment]
Yes, that seems to do it. Thanks.
