### ISSUE TITLE
Colorbar label

### ISSUE THREAD

**Issue by FWin22** [hyperspy/hyperspy#1255]
It would be good to have an option to add labels to the colorbar (i.e. 'intensity'). 
Or is this option available already and i just didn't find it?

Moreover, it would be good if this label also adjusts to the signal type. If for example a phase is calculated from a ComplexSignal, the colorbar should be labeled with 'phase (rad)' or 'phase shift (rad)' or something like this.
## TODO
- [x] `Signal2D` Add quantity to colorbar title
- [x] `Signal1D` Add quantity to ylabel title

**Comment by francisco-dlp** [comment]
Good point! Now that #1240 has added `quantity` to the metadata (believe it or not this information was missing from the metadata until now!), we should use this information in the plots: the colorbar title for `signal2D` and the ylabel for `signal1D`.

**Comment by FWin22** [comment]
Yes, this would be very useful and should be easy to implement.

**Comment by francisco-dlp** [comment]
I have updated your comment with a checklist.

**Comment by francisco-dlp** [comment]
Fixed in #1256

**Comment by francisco-dlp** [comment]
@FWin22, we've just release v1.1.2 and you are credited for your contributions in the [doi](https://zenodo.org/record/240660#.WHjGqLPqSV4) as FWin22. If you would like to get the credit to your real name in the next release you may like to add your real name to your GitHub profile.

**Comment by FWin22** [comment]
Wonderful, i will do it straight away.
Many thanks for this information.

Best wishes,
Florian

Am 13.01.17 um 13:24 schrieb Francisco de la Peña:
