### ISSUE TITLE
roi.profile_line -> Signal1D

### ISSUE THREAD

**Issue by FWin22** [hyperspy/hyperspy#1257]
Wouldn't it be good if `roi.profile_line` returns a `Signal1D` instead of a numpy array?
It would then be much easier to plot it with the good labels which can be extracted from the metadata of the original 2D signal.

**Comment by francisco-dlp** [comment]
@FWin22, `roi(im)` should return a `Signal1D` containing the line profile—is it what you want?

**Comment by FWin22** [comment]
Yes, at the moment `roi.profile_line` just returns a numpy array.
To me it seems more reasonable to return a `Signal1D` as further processing is much easier then, because one can easily keep all the metadata information from the original data.

**Comment by francisco-dlp** [comment]
I see, but `roi(im)` does return a `Signal1D` and it uses `profile_line` internally i.e. basically the feature is there, only that somewhere else.
I think that the method's name, `profile_line`, may be confusing, what about renaming it to: `get_line_data`? Or may I misunderstood you?

**Comment by FWin22** [comment]
Ah okay, i see. Renaming it might make sense.
But if `roi(im)` does return a `Signal1D` it should be fine.

**Comment by francisco-dlp** [comment]
Can we close this then?

**Comment by FWin22** [comment]
Yes.

**Comment by vidartf** [comment]
We could consider renaming `profile_line` to `_profile_line` to indicate it is an internal function.
