### ISSUE TITLE
Arrow-key support for plotting more than two navigation dimensions

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1273]
Currently when plotting anything with more than two navigation dimensions, the arrow keys stop working for moving between coordinates (at least on my Mac). It would be nice to add arrow key support for two of the dimensions, as well as keys for the third dimension (perhaps `,` and `.`?

**Comment by ericpre** [comment]
Done in https://github.com/hyperspy/hyperspy/issues/1866.
