### ISSUE TITLE
General documentation suggestions

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1276]
I was looking through the documentation today and thinking of more general things we can do to improve it.
- We currently have quite a few "New in version X.X.X" text fields in the documentation. Quite a few are from v0.7 and v0.8. At what point should one remove these and let features be an assumed part of Hyperspy?
- In the table of contents, the number of version changelogs is becoming quite long and will just keep on growing. Do we want to either shorten that up to 0.5, 0.6, 0.7... (rather than 0.5, 0.5.1 etc), or remove them from the table of contents altogether (leaving "What's New" or changing it to "Changelog")?
- We still haven't got an example notebook database (#1003). It would be nice to create one and add it somewhere sensible in the documentation.

Are there any other suggestions?

**Comment by magnunor** [comment]
> We currently have quite a few "New in version X.X.X" text fields in the documentation. Quite a few are from v0.7 and v0.8. At what point should one remove these and let features be an assumed part of Hyperspy?

Agreed. I guess we can only keep the N most recent versions?

> In the table of contents, the number of version changelogs is becoming quite long and will just keep on growing. Do we want to either shorten that up to 0.5, 0.6, 0.7... (rather than 0.5, 0.5.1 etc), or remove them from the table of contents altogether (leaving "What's New" or changing it to "Changelog")?

Yeah, I think it takes up too much space in the table of contents. In my opinion the "Getting started" headline should be visible without having to scroll, to make it a little bit easier for new users to find the starting information.

**Comment by thomasaarholt** [comment]
Some more suggestions:

There is no section that describes how one should modify the documentation, and I think quite a few people new to developing hyperspy (and to developing in general) find it a bit scary.

Having just had to reinstall sphinx again, here are the prerequisites for building hyperspy docs

```
pip install sphinx
pip install sphinxcontrib.napoleon
pip install sphinx_rtd_theme
```

In order to build the docs, one navigates to hyperspy/docs in a local repository, and type `make html`. This builds the docs into the subfolder `hyperspy/docs/_build/html` and can be seen by opening `index.html`. A lot of red text does appear, and that is because we haven't been very thorough in fixing warnings, not because a new user has done something wrong.

**Comment by ericpre** [comment]
For installing doc dependencies, this should be fixed in #1819.

**Comment by thomasaarholt** [comment]
That's great! 

A blurb in the docs would still be useful, I think, but that definitely lowers the barrier for writing documentation. Thanks for pointing it out. I'll see if I can add some docs about this.

**Comment by ericpre** [comment]
All points mentioned here have been fixed.
