### ISSUE TITLE
hs.interactive() works only if the related ROI has been manipulated before 

### ISSUE THREAD

**Issue by kociak** [hyperspy/hyperspy#1279]
Hi

it seems that hs.interactive() works only if the related ROI has been manipulated on the image before.
If I execute:

`%matplotlib qt4

import hyperspy.api as hs
import numpy as np
Spim = hs.load()
Roi = hs.roi.RectangularROI(left=3, right=7, top=2, bottom=5)
Roi2D = Roi.interactive(Spim, navigation_signal = Spim,out=None)
SpectrumRoi = hs.interactive(Roi2D.sum,axis = (0,1))
`
I get the traceback found at the end of the report.

If I select the spectrum or the image in the backend, I got the same
However, if I enlarge the ROI manually on the image before I run
`SpectrumRoi = hs.interactive(Roi2D.sum,axis = (0,1))`
it is all fine

Running Mac OS 10.8.5, hyperspy version >1 (but don't know how to get the version number!)

thanks, Mathieu

> ---
> 
> TraitError                                Traceback (most recent call last)
> <ipython-input-5-f25e8415b234> in <module>()
> ----> 1 SpectrumRoi = hs.interactive(Roi2D.sum,axis = (0,1))

//anaconda/lib/python3.4/site-packages/hyperspy/interactive.py in interactive(f, event, recompute_out_event, _args, *_kwargs)
    103 
    104 def interactive(f, event=None, recompute_out_event=None, _args, *_kwargs):
--> 105     cls = Interactive(f, event, recompute_out_event, _args, *_kwargs)
    106     return cls.out
    107 

//anaconda/lib/python3.4/site-packages/hyperspy/interactive.py in **init**(self, f, event, recompute_out_event, _args, *_kwargs)
     62             self.out = self.kwargs.pop('out')
     63         else:
---> 64             self.out = self.f(_self.args, *_self.kwargs)
     65         try:
     66             fargs = list(inspect.signature(self.f).parameters.keys())

//anaconda/lib/python3.4/site-packages/hyperspy/signal.py in sum(self, axis, out)
   4054             axis = self.axes_manager.navigation_axes
   4055         return self._apply_function_on_data_and_remove_axis(np.sum, axis,
-> 4056                                                             out=out)
   4057     sum.__doc__ %= (MANY_AXIS_PARAMETER, OUT_ARG)
   4058 

//anaconda/lib/python3.4/site-packages/hyperspy/signal.py in _apply_function_on_data_and_remove_axis(self, function, axes, out)
   4002             ar_axes = ar_axes[0]
   4003 
-> 4004         s = out or self._deepcopy_with_new_data(None)
   4005 
   4006         if isinstance(ar_axes, tuple) and np.ma.is_masked(self.data):

//anaconda/lib/python3.4/site-packages/hyperspy/signal.py in _deepcopy_with_new_data(self, data)
   3025             old_models = self.models._models
   3026             self.models._models = DictionaryTreeBrowser()
-> 3027             ns = self.deepcopy()
   3028             ns.data = np.atleast_1d(data)
   3029             return ns

//anaconda/lib/python3.4/site-packages/hyperspy/signal.py in deepcopy(self)
   4661 
   4662     def deepcopy(self):
-> 4663         return copy.deepcopy(self)
   4664 
   4665     def change_dtype(self, dtype):

//anaconda/lib/python3.4/copy.py in deepcopy(x, memo, _nil)
    164             copier = getattr(x, "__deepcopy__", None)
    165             if copier:
--> 166                 y = copier(memo)
    167             else:
    168                 reductor = dispatch_table.get(cls)

//anaconda/lib/python3.4/site-packages/hyperspy/signal.py in **deepcopy**(self, memo)
   4643 
   4644     def **deepcopy**(self, memo):
-> 4645         dc = type(self)(**self._to_dictionary())
   4646         if dc.data is not None:
   4647             dc.data = dc.data.copy()

//anaconda/lib/python3.4/site-packages/hyperspy/_signals/eels.py in __init__(self, _args, *_kwards)
     44 
     45     def **init**(self, _args, *_kwards):
---> 46         Spectrum.**init**(self, _args, *_kwards)
     47         # Attributes defaults
     48         self.subshells = set()

//anaconda/lib/python3.4/site-packages/hyperspy/_signals/spectrum.py in __init__(self, _args, *_kwargs)
     34 
     35     def **init**(self, _args, *_kwargs):
---> 36         Signal.**init**(self, _args, *_kwargs)
     37         self.axes_manager.set_signal_dimension(1)
     38 

//anaconda/lib/python3.4/site-packages/hyperspy/signal.py in **init**(self, data, **kwds)
   2837         self.learning_results = LearningResults()
   2838         kwds['data'] = data
-> 2839         self._load_dictionary(kwds)
   2840         self._plot = None
   2841         self.auto_replot = True

//anaconda/lib/python3.4/site-packages/hyperspy/signal.py in _load_dictionary(self, file_data_dict)
   3096             file_data_dict['axes'] = self._get_undefined_axes_list()
   3097         self.axes_manager = AxesManager(
-> 3098             file_data_dict['axes'])
   3099         if 'metadata' not in file_data_dict:
   3100             file_data_dict['metadata'] = {}

//anaconda/lib/python3.4/site-packages/hyperspy/axes.py in **init**(self, axes_list)
    588             obj : The AxesManager that the event belongs to.
    589             """, arguments=['obj'])
--> 590         self.create_axes(axes_list)
    591         # set_signal_dimension is called only if there is no current
    592         # view. It defaults to spectrum

//anaconda/lib/python3.4/site-packages/hyperspy/axes.py in create_axes(self, axes_list)
    749             axes_list.sort(key=lambda x: x['index_in_array'])
    750         for axis_dict in axes_list:
--> 751             self._append_axis(**axis_dict)
    752 
    753     def _update_max_index(self):

//anaconda/lib/python3.4/site-packages/hyperspy/axes.py in _append_axis(self, _args, *_kwargs)
    792 
    793     def _append_axis(self, _args, *_kwargs):
--> 794         axis = DataAxis(_args, *_kwargs)
    795         axis.axes_manager = self
    796         self._axes.append(axis)

//anaconda/lib/python3.4/site-packages/hyperspy/axes.py in **init**(self, size, index_in_array, name, scale, offset, units, navigate)
    119         self.high_index = self.size - 1
    120         self.low_index = 0
--> 121         self.index = 0
    122         self.update_axis()
    123         self.navigate = navigate

//anaconda/lib/python3.4/site-packages/traits/trait_types.py in _set(self, object, name, value)
   1783                 pass
   1784 
-> 1785         self.error( object, name, value )
   1786 
   1787     def _typed_value ( self, value, low, high ):

//anaconda/lib/python3.4/site-packages/traits/trait_handlers.py in error(self, object, name, value)
    171         """
    172         raise TraitError( object, name, self.full_info( object, name, value ),
--> 173                           value )
    174 
    175     def full_info ( self, object, name, value ):

TraitError: The 'index' trait of a DataAxis instance must be 0 <= a number <= -1, but a value of 0 <class 'int'> was specified.

**Comment by magnunor** [comment]
I'm not familiar with the interactive functionality or MacOS, so I'll leave that for the others. Answers might be a bit slow, since most of the developers are at the EMC conference this week.

To get the HyperSpy version: `hs.__version__`

**Comment by kociak** [comment]
Hi Magnus

Thanks; I was not expecting quick answers anyway: all our team but 3 of us are in Lyon, so my feeling is that any microscopy work is lagging ;)

thanks for he version!

cheers

Mathieu Kociak

**Comment by kociak** [comment]
The issue does not appear in version 1.1.1 (previous was 0.8.4)
Therefore, I am closing the issue
