### ISSUE TITLE
Bug: s.integrate_in_range and scaling

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#1280]
``` Python
s = hs.signals.Signal1D(np.arange(10000)) 
s.isig[100.:1000.].sum(0).data[0] # Gives 494550 
s.integrate_in_range((100.,1000.)).data[0] # Gives 494000.5 

s.axes_manager[0].scale = 0.3

s.isig[100.:1000.].sum(0).data[0] # Gives 5497500 
s.integrate_in_range((100.,1000.)).data[0] # Gives 1648700.25
```

Something goes wrong when using `s.integrate_in_range` on a signal with `s.axes_manager[0].scale` not equal to 1.

Thanks to @AndrewHerzing on Gitter for finding the bug

**Comment by to266** [comment]
This is not a bug, and things are working as intended.
It is succinctly explained [here in the documentation](http://hyperspy.org/hyperspy-doc/current/api/hyperspy.html?highlight=sum#hyperspy.signal.BaseSignal.integrate1D) 

The main idea is that  "integration" for a binned and non-binned signals actually are different. 

If the signal is not binned, then you essentially have a continuous PDF that you have sampled along the axis you are integrating. As such, you have to do it properly (e.g. using the trapezoidal rule or something similar).

If the signal is binned, it has already been integrated, and we have many integration results, not just samples along the PDF. As such "give me the integrated value in this range" is actually equivalent to "sum all the values in this range".

It's actually quite simple once it's been drawn, and I'll try to make the figure to illustrate this, and leave this explanation for now.
