### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by cvskiran** [hyperspy/hyperspy#1291]
Dear group, 
I am new here. 
During following the installation procedure, i had some problems:
I used the following command: conda env create -f /Users/cvskiran/anaconda/envs/anaconda_hyperspy_environment.yml
Command "/Users/cvskiran/anaconda/envs/hyperspy/bin/python -u -c "import setuptools, tokenize;**file**='/private/var/folders/q0/vsmq1zfx59sgn88hdrphxp8r0000gn/T/pip-build-jxd3d4cc/traits/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /var/folders/q0/vsmq1zfx59sgn88hdrphxp8r0000gn/T/pip-scwt5e65-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/q0/vsmq1zfx59sgn88hdrphxp8r0000gn/T/pip-build-jxd3d4cc/traits/
Error: pip returned an error.

Any suggestions please..
Regards,
Kiran

**Comment by to266** [comment]
Hi Kiran, welcome

A better (and more robust) way to install hyperspy to an anaconda environment is this:

``` bash
conda install -c conda-forge hyperspy
```

Then you can update everything (e.g. when new hyperspy versions are released) with 

``` bash
conda update -c conda-forge --all
```

or just hyperspy and its dependencies:

``` bash
conda update -c conda-forge hyperspy
```

**Comment by francisco-dlp** [comment]
@cvskiran, did @to266 reply fix the issue? If yes, would you like to close it?
