### ISSUE TITLE
installation v1.1 using the bundle in Windows 7 64 bit. No right-click start

### ISSUE THREAD

**Issue by mwalls** [hyperspy/hyperspy#1294]
Hello, I'm trying to install on a Windows 7 64-bit computer. I install it as administrator for all users, so with right click activated. Everything seems to work and the "hyperspy" folder exists in the "programmmes" folder. But the console and Jupyter lines do not appear in the context menu. I realise I no longer know how to start it in any other way.

Any ideas? Has anyone tried Windows 7?

**Comment by mwalls** [comment]
I also tried to follow the recommendation and the link on the download page:
_If HyperSpy fails to start install the Visual C++ 2015 (x64 and x86 for CPython 3.5) redistributable packages._
but the link seems to be broken. I get a blank page.

**Comment by to266** [comment]
Hi Mike,

Some time ago we separated the right click shortcuts part into a package on its own, namely this one:
https://github.com/hyperspy/start_jupyter_cm

I guess you are installing the bundle? In this case I can't recall how things are handled there, and you may have to install the shortcuts yourself, which in turn may be a difficult thing, if I remember it correctly.

My advice, as it has been for some time now, is to rather go the [anaconda](http://hyperspy.org/hyperspy-doc/current/user_guide/install.html#quick-instructions-to-install-hyperspy-using-anaconda-linux-macos-windows) way. In the end the installation is much more flexible, versatile and easy to upgrade.

Let me know if you need any further help with this!

**Comment by mwalls** [comment]
Hi Tomas,
Thanks. I'll try it that way. However, the bundle has succeeded in installing the short cuts on several other computers around here. It specifically mentions it when asking you whether you want an all-user installation or a personal one. The right-click option seems only to apply to an all-user installation. If we're now recommending anaconda we should change the current installation instructions for windows:

_The easiest way to install HyperSpy in Windows is installing the HyperSpy Bundle. This is a customised WinPython distribution that includes HyperSpy, all its dependencies and many other scientific Python packages. HyperSpy Bundle does not interact with any other Python installation in your system, so it can be safely installed alongside other Python distributions. Moreover it is portable, so it can be installed to a USB key. When installing it with administrator rights for all users it adds context (right-click) menu entries to start the Jupyter Notebook and Juypter QtConsole inside the folder being clicked. See start_jupyter_cm for details._

However, I won't try to change this until someone confirms that that the bundle no longer offers the short cuts.

**Comment by to266** [comment]
Clearly the bundle still installs shortcuts, since you managed it on other computers.

It may be just my personal impression, but maintaining the bundle has become (even with the recent extremely helpful continuous integration adoption for releases) a significant hassle... And I'm convinced that we should try to (slowly) push people using other installation methods not only due to their obvious advantages, but mostly due to how little maintenance they require from the developers point of view.

This obviously makes the installation slightly less straight-forward (not just "Download this .exe and run it"), so I am keen to help and figure out which parts of the installation are difficult, so that we (or mainly me) can make the transition smoother.

**Comment by mwalls** [comment]
Ok i tried to do it using Anaconda. Anaconda was apparently installed successfully. I then typed the command 
conda config --add channels conda-forge in a window terminal and got an error. I attach an image of the terminal since I don't know how to copy text in it. Not sure if it will be visible.

![conda error](https://cloud.githubusercontent.com/assets/1022064/18549927/bc339426-7b51-11e6-8acf-460a38ef806b.PNG)

**Comment by to266** [comment]
Huh, it clearly clashes with the cygwin install... Which I have not seen before.

Could you try running `anaconda-navigator`? It will most likely be just a runnable program, not a command, hence I would try looking for it using the windows search

**Comment by mwalls** [comment]
it runs ok but it just offers me 3 python terminals: Jupyter, qtconsole and spyder. I don't know what to do in them.

**Comment by to266** [comment]
One moment then, I'll create a couple of images that show what to do

**Comment by to266** [comment]
Select **Environments** and then (probably the only one) **root**
![2](https://cloud.githubusercontent.com/assets/3384140/18551928/739f58de-7b52-11e6-9011-989ebc2b1731.png)

Select **Channels**, **add**, and then type in the `conda-forge` and **update channels**
![3](https://cloud.githubusercontent.com/assets/3384140/18551932/73a2d216-7b52-11e6-8f32-8a0cef51ae8b.png)

Then from the drop-down list select **all** packages
![4](https://cloud.githubusercontent.com/assets/3384140/18551929/739fb18a-7b52-11e6-98aa-701360faf81d.png)

And in the package search look for `hyperspy`, right-click the found package name and **Mark for installation**
![5](https://cloud.githubusercontent.com/assets/3384140/18551931/73a219b6-7b52-11e6-907d-ca76c5d2c1b8.png)

Finally, in the lower right corner press **Apply**
![6](https://cloud.githubusercontent.com/assets/3384140/18551933/73a46324-7b52-11e6-9a3d-7ffd0226399b.png)

**Comment by mwalls** [comment]
Hi Tomas. sorry for the delay. I've just tried to do it. I am blocked at the "add channels" stage. As soon a s I click on "Add" the "update channels" box greys out and does not become clickable when I enter "conda-forge". Neither can I click the tick box to the left of where "conda-forge" is written.

**Comment by to266** [comment]
Hi Mike,

Let's try to approach this in a different way... Please copy what you get when you run the following in the command terminal:

``` bash
conda config --show-sources
```

**Comment by mwalls** [comment]
Ok here it is:
![conda 2](https://cloud.githubusercontent.com/assets/1022064/18584303/217997fe-7c10-11e6-8019-d7d2706188a5.PNG)

**Comment by to266** [comment]
could you try copying file `C:\Users\Marta\.condarc` to `C:\cygwin\home\Marta\.condarc`?
I hope the first file exists.. If not, then you can copy / download this, and put it in the cygwin folder:
https://gist.github.com/to266/5af6500f3535c815e3be7d898b246a7b

**Comment by mwalls** [comment]
Ok I did that and then tried the previous command you send and got this (found out how to copy command prompt):
_C:\Users\Marta>conda config --add channels conda-forge
Warning: 'conda-forge' already in 'channels' list, moving to the front

C:\Users\Marta>_

Looks like it was already there somehow? So then I typed the next line form the site instructions and got this:

_C:\Users\Marta>conda env create -f anaconda_hyperspy_environment.yml
Using Anaconda Cloud api site https://api.anaconda.org
Error: Can't process without a name
anaconda_hyperspy_environment.yml file not found
There is no requirements.txt_

**Comment by mwalls** [comment]
By the way, for info, the file ".condarc" was not present. I had to copy if from your link.

**Comment by to266** [comment]
Sorry, just noticed your reply. Looks like the cygwin has a global `$HOME` variable, which confuses conda where to look for configuration files.

Now that you have them (albeit not in the default location, but as long as you don't uninstall cygwin, this should not be a problem), you can just run

``` bash
conda install hyperspy
```

To get the right-click shortcuts, do the following:
1. `pip install start_jupyter_cm`
2. Close the conda prompt
3. Open the conda prompt **as an administrator** (via the right-click menu).
4. There run `jupyter_context-menu_add`

**Comment by mwalls** [comment]
Sorry I was off-line for the w/e. I ran "conda install hyperspy" and "pip install start_jupyter_cm", apparently successfully. I'm afraid I have now to ask the rather ignorant question: what is the "conda prompt"?

**Comment by mwalls** [comment]
incidentally there is only an administrator account on the computer (It's actually Marta's own PC, as you will have guessed.)

**Comment by mwalls** [comment]
I've found it I think! Sorryto be dim

**Comment by mwalls** [comment]
It worked! Thanks for your help.  I'm not sure what the consequences should be for the site's installation instructions. I can help with them (as guy who makes things go wrong) if we decide to re-write them a bit. Especially if the decision to dump the bundle is final...
Thanks again!

**Comment by to266** [comment]
You are welcome, and sorry it was way more complicated than I expected.

As you can tell, there are advantages to the bundle - the install would have been only "run this .exe"..

On the other hand, you can now always update everything in the anaconda python (including hyperspy, if there is a new version released) by just running `conda update --all`. And it's much more likely that things will work as expected!

**Comment by francisco-dlp** [comment]
I can't agree more with @to266 arguments to dump the bundle. However, I think that this exchange has shown that installing HyperSpy using Anaconda is not always as straightforward as it seems. Even if it was, most Windows users without Python experience (a big fraction of HyperSpy users) will be discouraged by any installation procedure that involves more than one step.

Regarding the original issue, I'm pretty sure that the context menu entries are installed properly in W7 because that's the OS that I use for testing. Other than permission issues, it may be a locale issue as I have never tested it with non-english W7.

**Comment by mwalls** [comment]
It has worked on other French PCs. I don't know the difference between Marta's and mine. I have Windows 7 too in fact. I think that was a red herring created by me. Sorry.  So I don't know whether Marta's is a one-off. One thing I don't understand but may contain a clue is that Marta has only one account which is as administrator, so I initially ignored Tomas's instruction to run anaconda prompt specifically as an administrator, since I thought I was one already. But I got "access denied" and had to run it again specifically as an administrator by right-clicking as Tomas had suggested. So is it some strange permission setting?

**Comment by mwalls** [comment]
I now remember you, Fran, advising me to change the permission settings on the "Programmes" folder during some previous installation. Can't remember the details but will try and find out. Maybe there is a setting in which administrator has especially to authorise certain changes if they're being proposed by an external connection? Maybe Marta had it?

**Comment by to266** [comment]
In windows being an administrator does not automatically grant you all permissions - it just allows you to **get** these permissions when you choose so (i.e. allows selecting "run as administrator"). Hence by default you are just like a normal user, and you get a (hopefully) obvious pop-up that is the only thing visible on the screen when you elevate your permissions.
