### ISSUE TITLE
Permanent markers

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#1307]
Currently when using `s.add_marker`, the marker will only be temporary: it will disappear if the plot is closed, then replotted.

It would be nice if these markers could be permanently added to a signal by adding them to the metadata, which would be checked when plotting.

In addition, the markers should be stored when saving the signal as a HDF5-file.

First step could be to add a `to_dictionary` function to the markers, so they could easily be saved in the HDF5.

**Comment by thomasaarholt** [comment]
Would these sit in the `s.metadata` or elsewhere?

**Comment by magnunor** [comment]
This was added in https://github.com/hyperspy/hyperspy/pull/1431

**Comment by thomasaarholt** [comment]
I don't think that PR is what you think it is :)

**Comment by magnunor** [comment]
You probably got the initial message, which linked to 143. Fixed now :)

**Comment by thomasaarholt** [comment]
It was actually my ridiculously fast reflexes that opened the issue to see if the PR had been merged.
