### ISSUE TITLE
signal dimension error

### ISSUE THREAD

**Issue by peiliu1986** [hyperspy/hyperspy#1319]
![11](https://cloud.githubusercontent.com/assets/23247845/19987484/b7d3caf4-a21b-11e6-956b-535e58010539.png)

I try to run the demo TEM EDX, however I had the signal dimension error. Does any one can help me fix that error? Thanks a lot!

**Comment by thomasaarholt** [comment]
Hi peiliu1986!
If you replace the box with the following, it should work. You've found both a bug and a error in the example, I think!

``` python
image1 = c.get_lines_intensity()
image1 = [image.as_signal2D((0,1)) for image in image1]
image2 = cs.get_lines_intensity()
image2 = [image.as_signal2D((0,1)) for image in image2]


axes = hs.plot.plot_images(image1,scalebar='all', axes_decor=None, per_row=2, cmap='RdBu')
axes = hs.plot.plot_images(image2,scalebar='all', axes_decor=None, per_row=2, cmap='RdBu')
```

**Comment by peiliu1986** [comment]
Thank you very much, it's works. :)

**Comment by francisco-dlp** [comment]
@peiliu1986, would you like to close this issue?
