### ISSUE TITLE
[EELS] s.estimate_thickness() has dimensions the wrong way round

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1326]
For an EELS low-loss signal, s.estimate_thickness() returns the correct result, but the signal has the wrong dimensions. Where it should have shape (|X,Y), it has (X,Y|).

**Comment by thomasaarholt** [comment]
I guess this is up for discussion in the same manner as s.get_lines_intensity().

**Comment by francisco-dlp** [comment]
As discussed in gitter, this is by design, so I think that it is not a bug.
