### ISSUE TITLE
git hooks fail on windows

### ISSUE THREAD

**Issue by vidartf** [hyperspy/hyperspy#1327]
It seems the script creating the git hooks get confused about back-slashes.
```
.git/hooks/post-checkout: line 4: c:usersvidarminiconda3python.exe: command not found
```
The line in the hook script looks like this: `c:\users\vidar\miniconda3\python.exe ....`, which is incorrect, as backslashes need to be escaped in shell scripts.

**Comment by francisco-dlp** [comment]
#1371
