### ISSUE TITLE
shift1D (and anything else that iterates over the signal) slow with inline plotting

### ISSUE THREAD

**Issue by andyroo101** [hyperspy/hyperspy#1329]
When using %matplotlib rather than %matplotlib qt4 (on windows) using the shift1D function takes 1000 times longer to apply the shifts. 

```python
%matplotlib
import hyperspy.api as hs
from numpy import *
s = hs.load("Some EELS data")
myShifts = loadtxt("My shift values.csv")
s.shift1D(myShifts) # takes 3 hours with a 510x510x61 data set
```
Alternatively:
```python
%matplotlib qt4
import hyperspy.api as hs
from numpy import *
s = hs.load("Some EELS data")
myShifts = loadtxt("My shift values.csv")
s.shift1D(myShifts) # takes 10 seconds with a 510x510x61 data set
```

Windows 10, Hyperspy 1.1.1, using Jupyter notebook.
The version of the notebook server is 4.2.3 and is running on:
Python 3.5.2 |Anaconda custom (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]
IPython 5.1.0 -- An enhanced Interactive Python.

**Comment by francisco-dlp** [comment]
Thanks for reporting this issue!

**Comment by thomasaarholt** [comment]
I suspect that this might be caused, not by being in qt4 rather than inline, but by having a plot open with s.plot. I think I just experienced this on Mac.

**Comment by ericpre** [comment]
This is most likely not happening anymore. In the past, the plot was being refresh when iterating over the navigation axis but this is not the case anymore. Other than that, using `%matplotlib qt` is significantly faster than using `%matplotlib notebook`.
