### ISSUE TITLE
MSA file read Signal_type issue

### ISSUE THREAD

**Issue by smc204** [hyperspy/hyperspy#1341]
In cases where the saved MSA file has a field Signal_type but it is left blank when the MSA is written, the MSA read step (io_plugin/msa.py) fails because quantity is not assigned. An additional case where quantity is assigned to a default or an empty string (not sure about down-stream consequences of this in full) might be useful.

**Comment by francisco-dlp** [comment]
Thanks for reporting the issue.

**Comment by francisco-dlp** [comment]
#1380
