### ISSUE TITLE
Different Evolution fitting bounded=True fails

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1346]
Attempting `m.fit(fitter="Differential Evolution", bounded=True)` returns the following error.

I think it might be because only some of the components have bounds set to them, although I'm uncertain.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-123-a3120aa8700a> in <module>()
----> 1 m.fit(fitter="Differential Evolution", bounded=True)

/Users/thomas/Dropbox/0_Git/GitHub/hyperspy_aar/hyperspy/model.py in fit(self, fitter, method, grad, bounded, ext_bounding, update_plot, **kwargs)
   1168                                    b if b is not None else np.inf) for a, b in de_b))
   1169                     self.p0 = differential_evolution(tominimize, de_b,
-> 1170                                                      args=args, **kwargs).x
   1171 
   1172                 else:

/Users/thomas/anaconda/envs/sims/lib/python3.5/site-packages/scipy/optimize/_differentialevolution.py in differential_evolution(func, bounds, args, strategy, maxiter, popsize, tol, mutation, recombination, seed, callback, disp, polish, init)
    203                                          callback=callback,
    204                                          disp=disp,
--> 205                                          init=init)
    206     return solver.solve()
    207 

/Users/thomas/anaconda/envs/sims/lib/python3.5/site-packages/scipy/optimize/_differentialevolution.py in __init__(self, func, bounds, args, strategy, maxiter, popsize, tol, mutation, recombination, seed, maxfun, callback, disp, polish, init)
    357         if (np.size(self.limits, 0) != 2 or not
    358                 np.all(np.isfinite(self.limits))):
--> 359             raise ValueError('bounds should be a sequence containing '
    360                              'real valued (min, max) pairs for each value'
    361                              ' in x')

ValueError: bounds should be a sequence containing real valued (min, max) pairs for each value in x

**Comment by to266** [comment]
Yes, essentially every parameter in every component should have its bounds set in order to run this particular optimiser (unless it's not free, of course)

**Comment by thomasaarholt** [comment]
It would be fantastic if we could write a short description for each algorithm, especially now that we have many and some are acronyms ("TNC").

**Comment by to266** [comment]
...Actually looking at the code I'm not sure my explanation is correct

**Comment by tjof2** [comment]
Courtesy of scipy (https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.optimize.differential_evolution.html). Perhaps I overlooked the parameter check for this method.

> "Bounds for variables. (min, max) pairs for each element in x, defining the lower and upper bounds for the optimizing argument of func. It is required to have len(bounds) == len(x). len(bounds) is used to determine the number of parameters in x."

One could of course have HyperSpy raise the warning that `len(bounds) != len(x)` rather than letting it fail later.

**Comment by tjof2** [comment]
With regards to the different algorithms, the vast majority of users will likely never need to use anything other than the default optimizers.

If the default isn't working for you and you are thinking about switching, I would wager that you know enough about optimization already to understand what BFGS is (as an example). 

Lastly, by converting everything as I did to be consistent with `scipy.optimize`, you can just read the documentation there: https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.optimize.minimize.html#scipy.optimize.minimize
