### ISSUE TITLE
RPCA_GoDec slow

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1350]
The robust PCA implementation is quite slow - is it normal for it to keep going over 10 minutes on a 400x50x1200 SI? It takes seconds with the normal PCA algorithm.

**Comment by tjof2** [comment]
Parameter choices are crucial here, especially `rank` and `lambda1`.

- Try `lambda1 = 1/sqrt(400*50)` and `lambda1 = 1/sqrt(1200)` to see if there is any speed change (I *may* have specified the wrong default here).
- Make sure `rank` is sensible, i.e. 3 or 4 components typically.
- Also set `power = 1` to see if the initialization is poor.

Also do try ORPCA, there's no real reason not to use it (better memory usage etc.) - GoDec is in some ways a reference implementation.

**Comment by thomasaarholt** [comment]
ORPCA is amazing. Closing this.
