### ISSUE TITLE
BUG: Casting complex values using map method (without reshaping of signal)

### ISSUE THREAD

**Issue by woozey** [hyperspy/hyperspy#1351]
It seems that new `map` method has problems if the input function casts complex values while the original data was real:

> In[2]: def test_func(data, reshape=None):
...     if reshape:
...         data = np.reshape(data, reshape)
...     return np.sqrt(np.complex128(data))
...     
In[3]: tt = -np.arange(24).reshape((2,3,4))
In[4]: tts = hs.signals.Signal2D(tt)
In[5]: tts
Out[5]: <Signal2D, title: , dimensions: (2|4, 3)>
In[6]: tts1 = tts.deepcopy()
In[7]: tts1.map(test_func)
./hyperspy/hyperspy/signal.py:3455: ComplexWarning: Casting complex values to real discards the imaginary part 
 self.data[:] = res_data
In[8]: tts1.data
Out[8]: 
array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],
       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

Interestingly, if the function reshapes the output, than `map` works as expected:

> In[9]: tts.map(test_func, reshape=(4,3))
In[10]: tts
Out[10]: <Signal2D, title: , dimensions: (2|3, 4)>
In[11]: tts.data
Out[11]: 
array([[[ 0.+0.j        ,  0.+1.j        ,  0.+1.41421356j],
        [ 0.+1.73205081j,  0.+2.j        ,  0.+2.23606798j],
        [ 0.+2.44948974j,  0.+2.64575131j,  0.+2.82842712j],
        [ 0.+3.j        ,  0.+3.16227766j,  0.+3.31662479j]],
       [[ 0.+3.46410162j,  0.+3.60555128j,  0.+3.74165739j],
        [ 0.+3.87298335j,  0.+4.j        ,  0.+4.12310563j],
        [ 0.+4.24264069j,  0.+4.35889894j,  0.+4.47213595j],
        [ 0.+4.58257569j,  0.+4.69041576j,  0.+4.79583152j]]])

**Comment by to266** [comment]
Ok, this is actually straightforward to fix. 

In the mean time (i.e. if you're just using this and not writing libraries / scripts), passing `inplace=False` should get around this (albeit creating new signals).

https://github.com/hyperspy/hyperspy/pull/1219 will be rewriting this part anyway, but I guess I'll have to PR a quick fix :)
