### ISSUE TITLE
unbcf_fast library?

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1356]
So, now that Jupyter Notebook reports warnings inline on Mac, I'm aware of everything that can clutter the screen.
When I load hyperspy, I get the following warning:
```python
unbcf_fast library is not present...
Falling back to slow python only backend.
```

I couldn't find anything on what the unbcf format is, or why it didn't come with my git install of hyperspy. If it's not coming back, we should remove it/the warning.

**Comment by to266** [comment]
It's there and alive, you probably just did not install it fully / correctly. It's a cython library that has to be compiled on each machine before use. 

I would try `python setup.py recythonize` in the hyperspy folder

**Comment by thomasaarholt** [comment]
Aha! What does it do though?

**Comment by thomasaarholt** [comment]
Installed cython, ran your command. It mentioned it was cythonizing the fast_unbcf, but then i get this error:
```python
(hs) wolf3947:hyperspy thomas$ python setup.py recythonize
/Users/thomas/miniconda3/envs/hs/lib/python3.5/site-packages/setuptools/dist.py:341: UserWarning: The version specified ('2.0-git-156-gc6850ed') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  "details." % self.metadata.version
running recythonize
```

I updated to setuptools v31 without any change. I'm not sure what it is that is of version 2.0? Maybe my hyperspy branch?

**Comment by francisco-dlp** [comment]
I wouldn't worry about the warning. That's because you're installing from the RELEASE_next_major branch and `setup.py` automatically adds the hashtag to the version number.

**Comment by thomasaarholt** [comment]
Ah, I see. Thanks! Why am I installing from _major though, I wonder.

**Comment by tjof2** [comment]
Tangentially related, why is it called `unbcf`? I can appreciate it might un-BCF something (whatever that means), but surely `bcf` would have been a clearer name - as @thomasaarholt notes, the `unbcf` format isn't a thing.

Furthermore, how do I stop this from recompiling every time I switch branches? Alternatively, can anything be done to make it compile quicker?

**Comment by francisco-dlp** [comment]
It should only recompile when Cython code changes when switching branches. If it doesn't do that, then you've found a bug. Regarding the naming question, only @sem-geologist knows. I find the name enjoyable though.

**Comment by sem-geologist** [comment]
hmm... naming decisions can look weird later. The reason it was called unbcf, because it is separate fast cython module from bcf (pure python), it is like i.e. format 'zip',and to extract we do unzip. So this unbcf do very similar thing: extracts highly packed data, but alone it can't open the bcf, it is only the extractor.

**Comment by sem-geologist** [comment]
I will look into this recompiling stuff during weekend, I am quite busy now. I remember it was quite tricky to do all this automatic cythonization and compiling (some git hook generation involved ), I have to refresh my memory on the subject. I am not sure but I guess the recompilation can be prevented by some dummy file 'hook_ignore' (can't remember exactly)

**Comment by tjof2** [comment]
I don't think the compilation itself is necessarily slow, it just seems to repeat itself quite a bit. As in, when I switch branches I get at least 50 instances of this in my terminal window, which to me suggests it keeps recompiling over and over? It's been running for 5 minutes now...

```
[1/1] Cythonizing hyperspy/tests/misc/cython/test_cython_integration.pyx
running clean
removing 'build/temp.linux-x86_64-3.5' (and everything under it)
removing 'build/lib.linux-x86_64-3.5' (and everything under it)
'build/bdist.linux-x86_64' does not exist -- can't clean it
'build/scripts-3.5' does not exist -- can't clean it
removing 'build'
running build_ext
building 'hyperspy.tests.misc.cython.test_cython_integration' extension
creating build
creating build/temp.linux-x86_64-3.5
creating build/temp.linux-x86_64-3.5/hyperspy
creating build/temp.linux-x86_64-3.5/hyperspy/tests
creating build/temp.linux-x86_64-3.5/hyperspy/tests/misc
creating build/temp.linux-x86_64-3.5/hyperspy/tests/misc/cython
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/anaconda3/include/python3.5m -c hyperspy/tests/misc/cython/test_cython_integration.c -o build/temp.linux-x86_64-3.5/hyperspy/tests/misc/cython/test_cython_integration.o
creating build/lib.linux-x86_64-3.5
creating build/lib.linux-x86_64-3.5/hyperspy
creating build/lib.linux-x86_64-3.5/hyperspy/tests
creating build/lib.linux-x86_64-3.5/hyperspy/tests/misc
creating build/lib.linux-x86_64-3.5/hyperspy/tests/misc/cython
gcc -pthread -shared -L/anaconda3/lib -Wl,-rpath=/anaconda3/lib,--no-as-needed build/temp.linux-x86_64-3.5/hyperspy/tests/misc/cython/test_cython_integration.o -L/anaconda3/lib -lpython3.5m -o build/lib.linux-x86_64-3.5/hyperspy/tests/misc/cython/test_cython_integration.cpython-35m-x86_64-linux-gnu.so
building 'hyperspy.io_plugins.unbcf_fast' extension
creating build/temp.linux-x86_64-3.5/hyperspy/io_plugins
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/anaconda3/include/python3.5m -c hyperspy/io_plugins/unbcf_fast.c -o build/temp.linux-x86_64-3.5/hyperspy/io_plugins/unbcf_fast.o
creating build/lib.linux-x86_64-3.5/hyperspy/io_plugins
gcc -pthread -shared -L/anaconda3/lib -Wl,-rpath=/anaconda3/lib,--no-as-needed build/temp.linux-x86_64-3.5/hyperspy/io_plugins/unbcf_fast.o -L/anaconda3/lib -lpython3.5m -o build/lib.linux-x86_64-3.5/hyperspy/io_plugins/unbcf_fast.cpython-35m-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-3.5/hyperspy/tests/misc/cython/test_cython_integration.cpython-35m-x86_64-linux-gnu.so -> hyperspy/tests/misc/cython
copying build/lib.linux-x86_64-3.5/hyperspy/io_plugins/unbcf_fast.cpython-35m-x86_64-linux-gnu.so -> hyperspy/io_plugins
.git/hooks/post-checkout: 238: .git/hooks/post-checkout: hon-*.so: not found
running clean
removing 'build/temp.linux-x86_64-3.5' (and everything under it)
removing 'build/lib.linux-x86_64-3.5' (and everything under it)
'build/bdist.linux-x86_64' does not exist -- can't clean it
'build/scripts-3.5' does not exist -- can't clean it
removing 'build'
running build_ext
building 'hyperspy.tests.misc.cython.test_cython_integration' extension
creating build
creating build/temp.linux-x86_64-3.5
creating build/temp.linux-x86_64-3.5/hyperspy
creating build/temp.linux-x86_64-3.5/hyperspy/tests
creating build/temp.linux-x86_64-3.5/hyperspy/tests/misc
creating build/temp.linux-x86_64-3.5/hyperspy/tests/misc/cython
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/anaconda3/include/python3.5m -c hyperspy/tests/misc/cython/test_cython_integration.c -o build/temp.linux-x86_64-3.5/hyperspy/tests/misc/cython/test_cython_integration.o
creating build/lib.linux-x86_64-3.5
creating build/lib.linux-x86_64-3.5/hyperspy
creating build/lib.linux-x86_64-3.5/hyperspy/tests
creating build/lib.linux-x86_64-3.5/hyperspy/tests/misc
creating build/lib.linux-x86_64-3.5/hyperspy/tests/misc/cython
gcc -pthread -shared -L/anaconda3/lib -Wl,-rpath=/anaconda3/lib,--no-as-needed build/temp.linux-x86_64-3.5/hyperspy/tests/misc/cython/test_cython_integration.o -L/anaconda3/lib -lpython3.5m -o build/lib.linux-x86_64-3.5/hyperspy/tests/misc/cython/test_cython_integration.cpython-35m-x86_64-linux-gnu.so
building 'hyperspy.io_plugins.unbcf_fast' extension
creating build/temp.linux-x86_64-3.5/hyperspy/io_plugins
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/anaconda3/include/python3.5m -c hyperspy/io_plugins/unbcf_fast.c -o build/temp.linux-x86_64-3.5/hyperspy/io_plugins/unbcf_fast.o
creating build/lib.linux-x86_64-3.5/hyperspy/io_plugins
gcc -pthread -shared -L/anaconda3/lib -Wl,-rpath=/anaconda3/lib,--no-as-needed build/temp.linux-x86_64-3.5/hyperspy/io_plugins/unbcf_fast.o -L/anaconda3/lib -lpython3.5m -o build/lib.linux-x86_64-3.5/hyperspy/io_plugins/unbcf_fast.cpython-35m-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-3.5/hyperspy/tests/misc/cython/test_cython_integration.cpython-35m-x86_64-linux-gnu.so -> hyperspy/tests/misc/cython
copying build/lib.linux-x86_64-3.5/hyperspy/io_plugins/unbcf_fast.cpython-35m-x86_64-linux-gnu.so -> hyperspy/io_plugins
```

And @francisco-dlp it does happen each time I switch branches.

**Comment by sem-geologist** [comment]
oh :O :O when it is a bug... I guess something went wrong with git hooks, it is regenerating everytime the branch is switched, so probably instead of replacing it accumulated these 50 instructions to recompile... nasty... ,by the way what os you have this issues on??? I see there were some commits after my implementation

**Comment by tjof2** [comment]
@sem-geologist  Ubuntu 14.04

**Comment by sem-geologist** [comment]
as work around for now you could try deleting '.git/hooks/post-checkout', also try making dummy file '.hook_ignore'

**Comment by sem-geologist** [comment]
or better.... could you post that hook file here? ('post-checkout')

**Comment by sem-geologist** [comment]
I hated those hooks from the beginning. I think my implementation is more scruffy than my beard...  Too much code for so simple thing (it is literally taking 1/3 of setup.py). I should reexamine the problem and rethink something better. So actually **when** we want to compile/recythonize?
If between checkouts some of those got changed:
1. If cython version got updated
2. If python version got updated (numpy got updated? it is one of dependencies)
3. If pyx file itself got updated(the code which is recompiled/recythonized)
4. If compiler got updated (???)
5. If userspace c libraries got updated
6. If c files are missing (first time clone)

I believe setuptools checks for 6. so this is not concerning. But how to check 1-5, such information should be recorded somewhere in under .git and then checked out after `git checkout`. How to check that pyx file changed? checksum, or maybe git itself can help here as it is tracking all changes?

**Comment by jat255** [comment]
I just saw this for the first time (doing a new install). It would be helpful if there was some documentation somewhere (user guide?) about what steps are necessary to resolve this warning. I would suggest something like:

```
unbcf_fast library is not present...
Falling back to slow python only backend.
See www.instructions-to-fix.com for more information.
```

**Comment by sem-geologist** [comment]
@jat255 , is the solution in #1409 satisfactory for you?

**Comment by ericpre** [comment]
What is the status of this? #1409 fixes @jat255's comment but what's about @tjof2's issue with switching branches?

**Comment by sem-geologist** [comment]
I think switching branches and post-checkout hook is different thing than this bug. I am opening new issue, so this can be closed.

**Comment by ericpre** [comment]
Normal install works fine and development install is documented in the dev guide.
It may be necessary to run `python setup.py recythonize build_ext --inplace` if there were changes to the bcf reader when checking out different branch.
