### ISSUE TITLE
problems loading BCF file

### ISSUE THREAD

**Issue by mgsephton** [hyperspy/hyperspy#1364]
I have a BCF file from Bruker Quantax software (attached).  When I try to open it with hyperspy, it produces an AttributeError: no such child: DX from line 533 of hyperspy\io_plugins\bcf.py, due to an attempt to assign semData.DX to self.image.x_res.

Here is my code for opening the file:

import hyperspy.api as hs
s=hs.load("Cathode_161007_70.bcf")

If I modify hyperspy\io_plugins\bcf.py file so that arbitrary values are assigned to self.image.x_res and self.image.y_res in place of semData.DX and semData.DY respectively, then I get a different error:
 
  File "hyperspy-1.1-py3.5-win-amd64.egg\hyperspy\io_plugins\bcf.py", line 598, in _set_sum_edx
    str(i))[0])

IndexError: list index out of range

[Cathode_161007_70.zip](https://github.com/hyperspy/hyperspy/files/671979/Cathode_161007_70.zip)

**Comment by sem-geologist** [comment]
@mgsephton , could you provide more details about your configuration? (microscope, Esprit version). From retrieved xml part from your file I see that a load of things are missing, I suspect that you have very primitive configuration (Bruker system gets no metadata from microsocope), or you forgot to activate something on microscope side (we can replicate such situation if we don't switch on RS232 link between our Zeiss microscope PC and Bruker PC. Then Esprit knows nothing about resolution. But it can be that your configuration is such and no scale on bruker/Esprit side is possible.
Another peculiarity is that ChannelFactor parameter is completely missing, I suspect that you are using quite old Esprit system, and it is lacking of that. I want to fix this as soon as possible, more information will help to understand how to isolate this issue.

**Comment by sem-geologist** [comment]
also AzimutAngle is missing... this is really weird... fix is of course possible

**Comment by sem-geologist** [comment]
btw, @mgsephton , could we use this file which you share, or maybe you could produce and share some other without any scientific value, which we could include to the tests. The most of bcf we tested are from Esprit at least v1.9.3, your file would be a perfect sample for less sophisticated microscope configurations and/or older Esprit bcf files.

**Comment by mgsephton** [comment]
@sem-geologist, thanks for the reply.  The microscope is a Hitachi TM3030Plus Benchtop SEM with Quantax 70 EDS system.  I couldn't see an obvious way to set up a scale bar on the EDX side when I was using the system and am not sure if it is possible.

I will try to obtain a similar BCF file to supply you for inclusion in your tests in the next week or two.  
Let me know if you require any further information.

**Comment by sem-geologist** [comment]
It is possible that Bruker Esprit scale is not set-up (Esprit uses and
queries the magnitude). To setup the scale you need to go to System and
then Imaging section. There it is possible on the left to draw/modify the
line representing known length.
