### ISSUE TITLE
Migrate to py.test?

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#1372]
It seems that `nose` is no longer under development and, although its being rewritten in a new project called [nose2](https://github.com/nose-devs/nose2),  most projects these days seem to use py.test. Other projects (e.g. matplotlib/matplotlib#6731) have started migrating to py.test, should we?

**Comment by magnunor** [comment]
Switching away from `nose` sounds like a good idea, due to lack of development.

I've been using `unittest` for my own stuff, and it seems like the main advantage of py.test is less boilerplate, easier assertions and running the tests in parallel?

**Comment by vidartf** [comment]
As far as I understand, `py.test` also allows for plugins :)
