### ISSUE TITLE
s.plot_explained_variance_ratio(small_int) axis label bug

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1382]
The x-axis has duplicates of the integer values for small ints fed for n components to the method.
![screenshot 2017-01-12 17 42 27](https://cloud.githubusercontent.com/assets/2721423/21901165/8a3a66f2-d8ee-11e6-8e53-3433f2a80962.png)

**Comment by thomasaarholt** [comment]
Seems like it is only for 5 and lower n, so perhaps this isn't much of a problem.

**Comment by jat255** [comment]
This is probably do the way I [hacked the labeling of that axis](https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/hyperspy/learn/mva.py#L1105-L1117). We can undo it, since I think it might cause additional problems.

**Comment by jat255** [comment]
https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/hyperspy/learn/mva.py#L1105-L1117

**Comment by jat255** [comment]
I've also noticed that when zooming in or panning using the interactive mpl tools, the axis labeling is incorrect, so we'll need a better way to do the labeling.

**Comment by francisco-dlp** [comment]
Fix in #1382
