### ISSUE TITLE
Bug when twinning an edge onset energy and gaussian centre parameters.

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1386]
When twinning the onset_energy of a EELSCLEdge to a gaussian, there is sometimes a difference between the two values. In this case, the difference is 85eV. This shouldn't happen (afaik).

```python
>>> m = Zr.create_model()
>>> Zr_L3 = m["Zr_L3"]
>>> Zr_L2 = m["Zr_L2"]

>>> G1 = hs.model.components1D.Gaussian()
>>> G2 = hs.model.components1D.Gaussian()

>>> G1.centre.value = Zr_L3.onset_energy.value
>>> Zr_L3.onset_energy.twin = G1.centre

>>> G2.centre.value = Zr_L2.onset_energy.value
>>> Zr_L2.onset_energy.twin = G2.centre

>>> print(Zr_L3.onset_energy.value - Zr_L3_white.centre.value)
0.0
>>> print(Zr_L2.onset_energy.value - Zr_L2_white.centre.value)
85.0
```

Forcing the relation between the two to be the same by the twin_function method solves the issue, but I still don't know where the 85.0 comes from.

```python
>>> Zr_L3.onset_energy.twin_function = lambda x: x
>>> Zr_L3.onset_energy.twin_inverse_function = lambda x: x

>>> Zr_L2.onset_energy.twin_function = lambda x: x
>>> Zr_L2.onset_energy.twin_inverse_function = lambda x: x

>>> print(Zr_L3.onset_energy.value - Zr_L3_white.centre.value)
0.0
>>> print(Zr_L2.onset_energy.value - Zr_L2_white.centre.value)
0.0
```

Here is the file tested on:

[test.hdf5.zip](https://github.com/hyperspy/hyperspy/files/713514/test.hdf5.zip)

The behaviour remains the same after fitting, and the discrepancy is visible (and annoying!) on the plot.

**Comment by francisco-dlp** [comment]
The issue is that the onset energy of L2 is twinned by default to L3's onset energy and, by twinning it to the gaussian, you are overwriting its twin without overwriting resetting its twin function. Anyway, you've found the solution on your own: resetting the twin functions too. Resetting the `Zr_L3` twin functions is probably unnecessary.

**Comment by thomasaarholt** [comment]
Of course. Thank you francisco. Legend!
