### ISSUE TITLE
`m.fit` does not fail graciously when analytical gradient is not available for a parameter

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1388]
```python
>>> m.fit(fitter="L-BFGS-B", bounded=True, grad=True)
```
fails, where grad=False does not.

Please see error here: https://gist.github.com/thomasaarholt/d9506d0fc25657d3da3aab5aad50a735

**Comment by thomasaarholt** [comment]
```python
m.fit(fitter="TNC", bounded=True, grad=True)
```
fails in the same way

**Comment by tjof2** [comment]
Does e.g. "BFGS" fail with `grad=True` and `bounded=False`? If so I've made a mess of passing the Jacobian to scipy's minimize function: https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.optimize.minimize.html

**Comment by thomasaarholt** [comment]
Tried both `BFGS ` and `L-BFGS-B` with `grad=True` and `bounded=False`, and it fails with the jacobian as before.

**Comment by tjof2** [comment]
Ok this extends to all Jacobians passed to scipy's minimize function, which are seemingly different to the form taken by `leastsq`. It boils down to fixing the following:

**`leastsq` details**: `jac(x, *args, **kwargs)`, and should return a good approximation (or the exact value) for the Jacobian as an `array_like` (`np.atleast_2d` is applied)

**`minimize` details**: `jac` can also be a callable returning the gradient of the objective. In this case, it must accept the same arguments as `fun`.

**Comment by tjof2** [comment]
@francisco-dlp I think https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/hyperspy/model.py#L1134 is the offending line, something is going wrong when it passes `fprime`?

**Comment by francisco-dlp** [comment]
I can't reproduce the issue, for example the following works fine:

```python

import hyperspy.api as hs
import numpy as np
s = hs.signals.Signal1D(np.arange((100)))
s.add_gaussian_noise(10)
m = s.create_model()
m.append(hs.model.components1D.Expression("a * x", "line"))
m.fit(grad=True, fitter="L-BFGS-B")

````

**Comment by tjof2** [comment]
@francisco-dlp interesting...what happens if you add `bounded=True` to any of those?

**Comment by francisco-dlp** [comment]
It works with bounds too.

**Comment by francisco-dlp** [comment]
```python

import hyperspy.api as hs
import numpy as np
s = hs.signals.Signal1D(np.arange((100)))
s.add_gaussian_noise(10)
m = s.create_model()
m.append(hs.model.components1D.Expression("a * x", "line"))
m.components.line.a.bmin = 0
m.components.line.a.bmax = 2
m.fit(grad=True, fitter="L-BFGS-B", bounded=True)

````

**Comment by tjof2** [comment]
Curious, I suppose we should await @thomasaarholt's response!

**Comment by thomasaarholt** [comment]
Well, @francisco-dlp's code runs fine, but mine does not. Ran them after each other on the same kernel. Investigating. It has nothing to do with the GOS or the fact that I convolved with the low loss, just tried removing those.

**Comment by thomasaarholt** [comment]
Right, it fails due to
`Zr_L3.onset_energy.twin = Zr_L3_white.centre` (EELSCLEdge twinned with a gaussian).

**Comment by tjof2** [comment]
Presumably a problem with the EELSCLEdge gradient...?

**Comment by francisco-dlp** [comment]
That's interesting. It should work for the case where the twinning function is ``lambda x: x``, but there is no unittest for this, so it might be broken, good catch!

Also, we should at least document that it doesn't work when the twinning function is something different. Even better, we should use Sympy to compute the gradient automatically in this case too.

**Comment by thomasaarholt** [comment]
Hm, this is strange. I reduced my example down to see what is making it fail, and it's something to do with the twin:
[twintest.hdf5.zip](https://github.com/hyperspy/hyperspy/files/714339/twintest.hdf5.zip)

```python
%matplotlib inline
import hyperspy.api as hs

Zr = hs.load("twintest.hdf5")
m = Zr.create_model( auto_add_edges=False)

m["PowerLaw"].A.bmin = 1
m["PowerLaw"].A.bmax = 1e20
m["PowerLaw"].r.bmin = 0
m["PowerLaw"].r.bmax = 5

Zr_L3 = hs.model.components1D.EELSCLEdge("Zr_L3", GOS="Hartree-Slater")
Zr_L3.intensity.bmin = 0
Zr_L3.intensity.bmax = 0.1

m.append(Zr_L3)

Zr_L3_white = hs.model.components1D.Gaussian()
Zr_L3_white.name = "Zr L3 White Line"
Zr_L3_white.centre.value = 2230.0
Zr_L3_white.centre.bmin = 2218.0
Zr_L3_white.centre.bmax = 2240.0
Zr_L3_white.sigma.bmin=0
Zr_L3_white.sigma.bmax=3
Zr_L3_white.A.bmin = 0
Zr_L3_white.A.bmax = 1e10
m.append(Zr_L3_white)

Zr_L3.onset_energy.twin = Zr_L3_white.centre

m.fit(grad=True, fitter="L-BFGS-B", bounded=True)
```

However, modifying @francisco-dlp's example to include a twin does not call an error:
```python
import hyperspy.api as hs
import numpy as np
s = hs.signals.Signal1D(np.arange((100)))
s.add_gaussian_noise(10)
m = s.create_model()
e1 = hs.model.components1D.Expression("a * x", "line")
e2 = hs.model.components1D.Expression("a * x", "line2")

m.append(e1)
m.append(e2)

e2.a.twin = e1.a

m.components.line.a.bmin = 0
m.components.line.a.bmax = 2
m.components.line2.a.bmin = 0
m.components.line2.a.bmax = 2
m.fit(grad=True, fitter="L-BFGS-B", bounded=True)
```

**Comment by francisco-dlp** [comment]
The issue is that `EELSCLEdge` doesn't provide an analytical gradient for `onset_energy`. That's because it's not trivial since shifting the energy requires recomputing the XS.

So this is not the bug that we thought it was, but there are at lest two bugs/issues here:

1. When the analytical gradient is not provided it should fail more graciously.
2. We should provide default `grad` methods that compute the numerical gradient so that 1. is no longer necessary.
3. It should use approach 2. when the twinning function is not ``lambda x: x``, currently it computes the gradient (wrongly) without complaining in this case. Even better, we should use Sympy to automate the task.

**Comment by francisco-dlp** [comment]
(I have edited the title of the issue to better reflex the nature of the bug.)

**Comment by tjof2** [comment]
"We should provide default grad methods that compute the numerical gradient" - worth noting that scipy's `minimize` and `leastsq` will do this automatically if provided the appropriate Jacobian - i.e. `False` or `None`

**Comment by francisco-dlp** [comment]
Sorry for not explaining myself: I was thinking on passing a jacobian that is computed analytically where available and numerically where not.
