### ISSUE TITLE
shortcut for getting current signal

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1390]
At the moment, `s = ui.get_selected_signal()`. Could I propose changing this to `s = ui.get_current_signal()`, copying matplotlib behaviour and allowing for the acronym-method `s = ui.gcs()`. In matplotlib, one normally gets ahold of the current figure by `plt.gcf()`, so something similar would be welcome. The current call is quite long, which isn't ideal.

**Comment by francisco-dlp** [comment]
Was this intended for hyperspy/hyperspyui?

**Comment by thomasaarholt** [comment]
Yep. Oops.
