### ISSUE TITLE
improve camera and stage metadata

### ISSUE THREAD

**Issue by ericpre** [hyperspy/hyperspy#1396]
As mentioned in #1385, it would be good to add more camera and stage metadata.
Currently the exposure time in TEM is stored in `Acquisition_instrument.TEM.exposure` and for STEM, there is `Acquisition_instrument.TEM.dwell_time`.

If we add a `camera` node, I guess it would be good to move the `Acquisition_instrument.TEM.exposure` leaf to `Acquisition_instrument.TEM.Detector.camera`. In this case, it would be considered as a "detector node" similar to EELS and EDS ones.
Regarding STEM mode, should the `Acquisition_instrument.TEM.dwell_time` leaf stay as it is? Is there any io plugins that import metadata about STEM detector? As far as I know, the DM and FEI don't support it and we don't even know the kind of detector.

If we are moving the `Acquisition_instrument.TEM.exposure` leaf, it will break the API, so I guess the PR would need to be made to the `RELEASE_next_major` branch?

**Comment by ericpre** [comment]
See this [commit](https://github.com/hyperspy/hyperspy/pull/1385/commits/ffe95289899db257ac7009cd2ca5648de06b151d) for camera metadata.

**Comment by woozey** [comment]
> If we add a camera node, I guess it would be good to move the Acquisition_instrument.TEM.exposure leaf to Acquisition_instrument.TEM.Detector.camera. In this case, it would be considered as a "detector node" similar to EELS and EDS ones.

That makes the most sense to me, as camera is a detector too. In the https://github.com/hyperspy/hyperspy/pull/1385/commits/ffe95289899db257ac7009cd2ca5648de06b151d mentioned above my first ideas about what necessary camera metadata may look like.

Regarding stage metadata it could contain quite advanced information (though it is rarely saved together with images at the moment...). For example:
-  Position: x,y,z, alpha, beta, azimuth
-  Stage type (holder type in this case)
-  Temperature
-  Applied voltage, current and magnetic field (?) Actually this part may even need another branch in `TEM` called `insitu`.
-  Also I dream about the day when all lens and other optical element currents will be saved together with data...

**Comment by sem-geologist** [comment]
IMHO stage data could also be handy not only for TEM but also for SEM

what is the parameters alpha, beta and azimuth? for possition?

maybe for stage position also rotation could be added, or is this the azimuth parameter?

**Comment by woozey** [comment]
> what is the parameters alpha, beta and azimuth? for possition?

These are tilt/rotation angles. Specifically in TEM alpha is a tilt about specimen holder (x-)axis, azimuth is rotation about beam (z-)axis and beta is a tilt about y-axis

**Comment by sem-geologist** [comment]
hmm... If I think about SEM it have similar functionality, you can tilt stage to one of directions (normally it depends from stage, it is either Y or either X), have rotation of stage, and some SEM have rotation of scanning which is different rotation

**Comment by ericpre** [comment]
Fixed in #1563.
