### ISSUE TITLE
BUG: RPL io plugin does not save title information

### ISSUE THREAD

**Issue by jat255** [hyperspy/hyperspy#1404]
See [gitter discussion](https://gitter.im/hyperspy/hyperspy?at=588b6cb5c0f28dd8624dfd42) for some background.

Basically, the .rpl writer doesn't store any title information, and the reader doesn't try to read any title information, so the round-trip of saving/reading a file to .rpl format will lose that metadata information.

Also, the documentation of the `signal` keyword is wrong. Docstring says:

```
signal   str         # Name of the signal stored, e.g. HAADF
```

But in actuality, that keyword is put into the metadata as `signal_type`.

**Comment by francisco-dlp** [comment]
I am not sure if this is a bug. Indeed ``signal`` should store the ``signal_type`` not the title. The internal comment is indeed wrong and we should fix it. If you would like to add the ability to save a title feel free to make a PR: we have already added quite a few extras to the specification of the format which, by the way, seems to have vanished from NIST's website.

**Comment by jat255** [comment]
Yes, I suppose you're right that it's a combo of a bug fix and new feature. Although, I would argue that losing information during a round-trip save/load is a bug as well.

**Comment by jat255** [comment]
As for the website, NIST did a revamp of their web properties over the past few months, and some sites were mysteriously lost. It's still accessible through the web archive: http://web.archive.org/web/20050403160408/http://www.nist.gov/lispix/

I'll see if I can't find someone around here who knows how to get it back online, since David Bright has retired...

**Comment by francisco-dlp** [comment]
That's a fair point but we do mention in the docs that saving to anything but hdf5 loses information. In this case the reason is that the title is not part of the specification and nobody has cared before about adding support for it.

**Comment by jat255** [comment]
Well if it doesn't hurt anything, consider this as me caring 😄 

I'll submit a PR about it in a bit.

**Comment by jat255** [comment]
Also, the testing code for ripple is a little buggy. It doesn't actually do any testing of metadata because of the `range(1)` in [test_ripple](https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/hyperspy/tests/io/test_ripple.py#L83), and the metadata testing code that does exist didn't check for spaces in parameters or check the titles at all, which is probably why this wasn't caught before.

**Comment by francisco-dlp** [comment]
#1408
