### ISSUE TITLE
s.split() fails after reloading a stacked set of signals

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1405]
```python
s = hs.signals.Signal1D([1,2,3])
s.save("test")
hs.load("test.hdf5").split()
```
Fails with a truth error.

```
/Users/thomas/Dropbox/0_Git/hyperspy/hyperspy/signal.py in split(self, axis, number_of_parts, step_sizes)
   2378 
   2379         if number_of_parts == len_axis \
-> 2380                 or step_sizes == [1] * len_axis:
   2381             for i, signal1D in enumerate(splitted):
   2382                 signal1D.data = signal1D.data[

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by thomasaarholt** [comment]
Part of the error is that
`step_size = [1, 1, 1]` before saving and reloading, but `step_size = 1` after.

**Comment by to266** [comment]
While the example does not in fact reproduce the error for me, the bug is there, albeit triggered like so:
```python
s = hs.signals.Signal1D([1,2,3])
hs.stack([s,s,s]).save('test')
hs.load("test.hdf5").split()
```

**Comment by thomasaarholt** [comment]
I've noticed that `type(hs.stack([s,s,s]).metadata._HyperSpy.Stacking_history.step_sizes)` is `int` before saving an `numpy.int64` after.

**Comment by thomasaarholt** [comment]
That's it! There is a case that checks for `if isinstance(step_sizes, int):`, which won't catch the int64 I think.

**Comment by thomasaarholt** [comment]
I've made a PR. sending in a bit.

**Comment by thomasaarholt** [comment]
#1407. I've not found the cause for why step_sizes is read back in as a `np.int64`because I haven't got time to look. Feel free to modify the PR if necessary.

**Comment by francisco-dlp** [comment]
#1407
