### ISSUE TITLE
Nosetests using image comparisons

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#141]
As we are implementing more and more visualization functions, it would be nice to write some tests which actually check if they plot things correctly.

Matplotlib has a way to do this: http://matplotlib.org/devel/testing.html (Writing an image comparison test). And it is fairly easy to write the tests themselves.

What do you think?

**Comment by tjof2** [comment]
See #1253

**Comment by ericpre** [comment]
Done in #1253.
