### ISSUE TITLE
FEI tests issue

### ISSUE THREAD

**Issue by ericpre** [hyperspy/hyperspy#1414]
As mentioned in #1413, there are two questionable FEI tests about the import of linescans (1D navigation axis). More precisely, the issue seems to concern the name of the navigation axis.

In the current implementation the name of the navigation axis is `y`, mainly because of the way how linescans and spectrum images are imported. When I looked at it, I first thought that it was wrong, but since the linescan can be vertical, horizontal or oblique, we can't really use the same convention than for spectrum images (`x` and `y`).
Should we change the navigation axis name? Is it worth it?

**Comment by francisco-dlp** [comment]
Maybe ``PositionX`` and Y can help determine if its "x", "y" or oblique?

**Comment by ericpre** [comment]
Yes, but what name do we put if it's oblique?

**Comment by francisco-dlp** [comment]
I would suggest "x". This shows that we may need to add a coordinates attribute to ``DataAxis`` for the cases like this one.

**Comment by ericpre** [comment]
If we put `x` for a oblique linescan, it will be wrong and confusing because the convention (actually I don't know to what extend it's correct) is to have `x` as horizontal axis and `y` as vertical axis.
Maybe, something more generic like `Position`?

**Comment by francisco-dlp** [comment]
Sounds good.

**Comment by to266** [comment]
#1420
