### ISSUE TITLE
.get_lines_intensity() not consistent

### ISSUE THREAD

**Issue by adrianler** [hyperspy/hyperspy#1418]
The function `.get_lines_intensity()`, is dissimilar when applied to a EDSTEM spectrum and its belonging model. 

On a spectrum containing some elemental x_ray lines in the metadata, the function returns a list of intensities on the form:
 `[<EDSTEMSpectrum, title: X-ray line intensity of Al - Bulk: Al_Ka at 1.49 keV, dimensions: (1|)>,...`.
Calling the same function on a model, returns:
`[<EDSTEMSpectrum, title: Intensity of Al_Ka at 1.49 keV from Al - Bulk, dimensions: (|1)>,...`

For the model, this list is not easily used as the list of intensities needed in `bulk.quantification() `.

**Comment by francisco-dlp** [comment]
#1440
