### ISSUE TITLE
Cropped signals lack a scale bar

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1421]
I don't particularly like the built-in scalebar in HS, but it's missing if one uses the UI to crop a signal. From @francisco-dlp: The issue is that the scalebar position is not updated when updating the plot...hence it's a hspy bug.

**Comment by tjof2** [comment]
@thomasaarholt is this still a bug?

**Comment by ericpre** [comment]
The following example shows that this bug is not an issue anymore:

```python
import numpy as np
import hyperspy.api as hs

s = hs.signals.Signal2D(np.arange(100).reshape(10, 10))
s.plot()

s.crop_image(2., 8., 2., 8.)
```

However, I think it may be worth considering using https://github.com/ppinard/matplotlib-scalebar to make the scalebar because it will fix the issue of the scalebar not being updated when zooming interactively on an image.

**Comment by tjof2** [comment]
@ericpre what about #1066 and #1718?
