### ISSUE TITLE
Large spectrum images are hard to navigate

### ISSUE THREAD

**Issue by jat255** [hyperspy/hyperspy#1435]
This has always somewhat bugged me, and I think we could do better in terms of interactive usability, so I wanted to gather some thoughts on it.

## Frustrating behavior

Two issues I often see when browsing "large" spectrum images (such as an EELS or EDS spectrum on the energy axis, which is often ~2000 channels):

1) The red navigator box often becomes so small that it is very difficult to grab onto. This is very frustrating, especially for new users
2) The navigator box can be adjusted using the arrow keys (good) but does not respond when the arrow keys are held down, meaning you have to mash a key to go more than just one pixel (bad). Enabling repeated movement when the key is held down would be very useful, I think.

## Potential solutions

I'm not overly familiar with the GUI code enabling this, but potential solutions I can imagine:

1) Make a separate control for the "draggable" box that is larger and invisible, which is centered on the existing red box; alternatively, make a little draggable flag that is always the same size, regardless of spectrum image dimensions (like DigitalMicrograph has)
2) Enable repeated movement when arrow keys are held down.

Anyone else have any thoughts about this?

**Comment by magnunor** [comment]
I completely agree. 

I'm not that familiar with the GUI elements, but the GUI wizard @vidartf should know how to do these things :)

**Comment by francisco-dlp** [comment]
As I remember 2. was not supported by matplotlib the last time that I checked. We provide a poor-man-solution to the problem: Pg Up/Down controls the size of the step. Of course, if anybody knows how to achieve 2. ideas or PRs are more than welcome.

Regarding 1., I fully agree. The minimalistic approach is good for pixelated navigators as it minimises the part of the plot that is masked, but its certainly an issue for non-pixelated navigators. Although it's possible to increase the size of the pointer using the + key, most users are unaware of this and others get confused thinking that the signal is integrated over the square. Making the pointer always the same size (and maybe non-square) sounds like a good idea to me.

**Comment by francisco-dlp** [comment]
I'll label this as a bug as I think that many users would consider it a bug indeed.

**Comment by jat255** [comment]
Wow, I had no idea about those keyboard shortcuts! I must have missed them when originally going through the user guide. That will help me for now until we figure out a more elegant solution.

**Comment by vidartf** [comment]
1. Logic can be added in the widget for selecting outside its data area (the size of the selection area could even be specified in screen pixels). This does not require a second patch/widget, but processing of mouse events.
 2. Seems auto-repeat key events are in the loop for MPL 2.1: https://github.com/matplotlib/matplotlib/pull/6302. I would avoid doing anything until then.

**Comment by vidartf** [comment]
Refreshing my memory, what you need to do for (1) is to set the picker radius for the patch. As I guess we only want this for the square widget, [this](https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/hyperspy/drawing/_widgets/rectangles.py#L49) is the line to modify. I guess it should preferably be set from a member variable, but it could be hardcoded as well (replace `picker=True` with e.g. `picker=5`).

**Comment by ericpre** [comment]
I would suggest to close this, since the repeated movement are now enabled in matplotlib 2.1 and the setting the picker radius will be enabled in #1668.

To test the repeated movement:
```python
import hyperspy.api as hs
import numpy as np
n = 100
s = hs.signals.Signal1D(np.arange(n*n*n).reshape((n, n, n)))
s.plot()
```

**Comment by jat255** [comment]
Cleaning up old issues; closing...
