### ISSUE TITLE
EMD files with bytes string will not load

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#1436]
Some EMD files which were saved using a Python2 file writer have their metadata like axis names encoded in bytes, and they fail when trying to load them the HyperSpy EMD-reader: `TraitError: The 'name' trait of a DataAxis instance must be a string, but a value of b'scanY' <class 'bytes'> was specified.`.

This can be fixed by adding a check in the file reader, to see if the metadata strings are `bytes` or `str`. And if they are `bytes`, change them to `str` when loading.

**Comment by francisco-dlp** [comment]
By the way, the [website of the EMD format specification](http://emdatasets.lbl.gov/) seems to have banished...

**Comment by magnunor** [comment]
Still alive, but moved: https://emdatasets.com/

**Comment by francisco-dlp** [comment]
#1439
