### ISSUE TITLE
ENH: Website, endorsements

### ISSUE THREAD

**Issue by woozey** [hyperspy/hyperspy#1442]
This is a suggestion to enhance HyperSpy's website by putting endorsements from users (who can be also developers). The purpose is to create some kind of quality stamp that the website visitors see who is using the software and that the reputation of users and their institutes certifies HyperSpy's quality. This may sound redound to the scientific publication that acknowledge HyperSpy, but there might be people ending up at the website without being aware of the publications and not willing to read them up or even browse through them. The endorsements can be just short statements saying how life would be annoying without HyperSpy signed by a person's name and affiliation. There shouldn't be thousands of this statements, 10 would be enough for the start.

I can start collecting those from users I know, and I guess most of you know one or two people, who can be asked too. 

Please let me know if it sounds a good idea.

**Comment by francisco-dlp** [comment]
I think that this is an excellent idea. Does anybody know of any way to make it dynamic so that random people rather than the people we know can leave little thank you notes to the project. In a quick search I've found [saythanks.io](https://saythanks.io/) which is nice but it seems to be aimed at thanking individual developers rather than projects (although I may have got it wrong).

**Comment by tjof2** [comment]
Dynamic could be implemented down the line, but I think in the first instance (unless there is a very simple way to make it dynamic!) then @woozey 's straightforward suggestion of three or four short quotes displayed on the homepage can be implemented statically very quickly.

Also editorial judgment can be applied to select quotes from well-known users or institutions ;-)

**Comment by francisco-dlp** [comment]
For any website PR this is the repo https://github.com/hyperspy/hyperspy-website

**Comment by thomasaarholt** [comment]
This would be very nice to include. I've just spent some time looking at Sphinx and figuring out making the website. Does anyone have any thoughts on where to put the "endorsements" page? @francisco-dlp suggests removing the "News" page and putting it there. I think that may be a good idea, but then it means that next time we have something "really cool" to show off, we can't use that.

**Comment by francisco-dlp** [comment]
I've rather suggested to remove the News sections from the frontpage. We probably still want to keep the news page ;)

**Comment by thomasaarholt** [comment]
Sorry, that is what I meant. I'm sleepy from a run and still a bit hungover from handing in.

**Comment by woozey** [comment]
Why one would remove anything from the page? I'd put it either right before the news section or after it. Otherwise one may think of removing Support, since it seem to be redundant with the support in the sidebar. 
Regarding making it dynamic, it will be definitely better than having it static. Though I have no clue how to implement it...

**Comment by francisco-dlp** [comment]
@woozey, see hyperspy/hyperspy-website#26

**Comment by francisco-dlp** [comment]
Just in case that you're wondering, we've collected exactly 1 thank you messages using saythanks.io so far, and, sure enough, that single one was from our fellow @thomasaarholt (thank you @thomasaarholt!).

I am wondering if the current endorsements make more harm than good as both are from HyperSpy developers. It gives the impression that only hspy developers are using it...which is very far from the truth.

**Comment by thomasaarholt** [comment]
You're most welcome 😄

So I just showed this to my girlfriend, and she was like "so this seems a bit biased. What if I didn't like it?". She has a point. Perhaps a "leave a comment" concept would be better?

Regarding your second paragraph, I don't think people necessary realise that Vadim and I are hyperspy developers.

**Comment by jan-car** [comment]
I'm in favor of changing it to "comment".
I also added a note.
You can see it like that: Vadim and I started as simple HyperSpy users, but are so invested and convinced of the quality that we started contributing ;-)...

**Comment by francisco-dlp** [comment]
saythanks.io doesn't allow much customisation. We can simply stop using it. I think that the idea behind saythanks.io is provide a channel for developers to hear from happy users as, otherwise, we only hear from them when something doesn't work. For ideas and constructive criticism we already have the GH issues.

@CodeMonkeyJan, that's an excellent point. Actually we've always aimed at making the user/developer distinction blurred.

**Comment by tjof2** [comment]
The website has some endorsements now. saythanks.io was removed as it stopped working.
