### ISSUE TITLE
DOC: link to HyperSpy bundle from the user guide

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#1454]
Currently in the install portion of the user guide, there is no easy way to actually download the bundle: http://hyperspy.org/hyperspy-doc/current/user_guide/install.html#hyperspy-bundle-for-microsoft-windows

There should be a link to the download section on the webpage (http://hyperspy.org/download.html), so if someone gets to the documentation, they can easily get to the bundle.

**Comment by ericpre** [comment]
The download section does not exist anymore but there is a link in the user guide.
