### ISSUE TITLE
hs.stack very slow?

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1459]
I'm finding hs.stack() to be quite slow. On my Mac the command below takes minutes to run.
```python
eds = hs.datasets.example_signals.EDS_TEM_Spectrum()
eds = hs.stack(2000*[eds])
```

**Comment by to266** [comment]
The main purpose of `hs.stack` is to combine different signals while preserving their individual metadata. The metadata is in this case what takes most of the time (in particular `slugify`, which is a known problem) to record and store.

I would argue that stacking 2000 (!!!!) signals in a minute __while preserving each individual metadata__ is reasonably fast. If you just want to create a larger play signal, I'm afraid that's nearly the least efficient way to do it. A better example that ends up with a very similar result:

```python
In [21]: eds2 = hs.stack([eds, eds]) # to get new axis but preserve metadata

In [22]: eds2.data = np.stack((eds.data for _ in range(2000))) # replace the data with required size

In [23]: eds2.get_dimensions_from_data() # update dimensions

In [24]: eds2
Out[24]: <EDSTEMSpectrum, title: Stack of EDS TEM Spectrum, dimensions: (2000|992)>
```

**Comment by thomasaarholt** [comment]
That makes sense. Whilst working on linear fitting I needed to check that my new multifit was working correctly, so I wanted to make a multi-pixel EDS spectrum quickly. Your suggestion should work well. Thanks.

**Comment by thomasaarholt** [comment]
Yeah, okay. 😊 that is way faster, and my fitting is WAY faster on it. Thanks.
