### ISSUE TITLE
Adding example spectra

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#146]
As mentioned in https://github.com/hyperspy/hyperspy/pull/138 , we should probably have some example EELS and EDX spectra for the user guides and for examples. 

I can probably "donate" some SrTiO3 EELS and EDX spectra. Where should we place them, and what format should we use?

**Comment by magnunor** [comment]
With the implementation fetching single EEL spectra from EELS DB, I'm guessing this has been partly resolved. But as far as I know, it is only possible to upload single spectrum to EELS DB (ergo no line scans are maps).

It would be useful to have easy access to these things directly in HyperSpy.

**Comment by ericpre** [comment]
Artificial data such as EELS linescan has been implemented in #1789.
