### ISSUE TITLE
Dask Dependency Issue

### ISSUE THREAD

**Issue by k8macarthur** [hyperspy/hyperspy#1469]
---------------------------------------------------------------------------

ImportError                               Traceback (most recent call last)
<ipython-input-10-d84f37aef119> in <module>()
      2 import matplotlib
      3 matplotlib.rcParams["backend"] = 'Qt4Agg'
----> 4 import hyperspy.api as hs
      5 import numpy as np
      6 get_ipython().magic('matplotlib qt4')

/Users/macark/Documents/hyperspy/hyperspy/api.py in <module>()
     73 
     74 from hyperspy.Release import version as __version__
---> 75 from hyperspy import signals
     76 from hyperspy.io import load
     77 from hyperspy.defaults_parser import preferences

/Users/macark/Documents/hyperspy/hyperspy/signals.py in <module>()
     41 # -*- coding: utf-8 -*-
     42 from hyperspy.signal import BaseSignal
---> 43 from hyperspy._signals.lazy import LazySignal
     44 from hyperspy._signals.signal1d import (Signal1D, LazySignal1D)
     45 from hyperspy._signals.signal2d import (Signal2D, LazySignal2D)

/Users/macark/Documents/hyperspy/hyperspy/_signals/lazy.py in <module>()
     22 import numpy as np
     23 import dask.array as da
---> 24 import dask.delayed as dd
     25 from dask import threaded
     26 from dask.diagnostics import ProgressBar

ImportError: No module named 'dask.delayed'

**Comment by k8macarthur** [comment]
So I'm having this error on my Mac this afternoon, since the inclusion of lazy signals. According my pip install I already have dark up to date, I just don't seem to have delayed as a function in dask. As I haven't tried using anything related to lazy signals yet I've just commented it out. But I figured it should be sorted for a new release?

**Comment by to266** [comment]
It's almost certainly a problem with your install in particular. How did you install dask to begin with? Which version do you currently have? If it's just something that was installed previously, chances are it's a decently old version, where `delayed` was called `do`, and was in general less integrated part

**Comment by francisco-dlp** [comment]
In that case, this is a bug as ``setup.py`` should state the min version of dask required.

**Comment by k8macarthur** [comment]
So this was using the Dev version of Hyperspy and trying to work on the Linear_Bin branch. Therefore it wasn't really install so much as updated. I ran install just now which didn't update dask. I had to manually update dask (it was previously v0.8.1) it's now v0.13 and I get a new error.

`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-8d62f0491115> in <module>()
      1 import matplotlib
      2 matplotlib.rcParams["backend"] = 'Qt4Agg'
----> 3 import hyperspy.api as hs
      4 import numpy as np
      5 get_ipython().magic('matplotlib qt4')

/Users/macark/Documents/hyperspy/hyperspy/api.py in <module>()
     73 
     74 from hyperspy.Release import version as __version__
---> 75 from hyperspy import signals
     76 from hyperspy.io import load
     77 from hyperspy.defaults_parser import preferences

/Users/macark/Documents/hyperspy/hyperspy/signals.py in <module>()
     41 # -*- coding: utf-8 -*-
     42 from hyperspy.signal import BaseSignal
---> 43 from hyperspy._signals.lazy import LazySignal
     44 from hyperspy._signals.signal1d import (Signal1D, LazySignal1D)
     45 from hyperspy._signals.signal2d import (Signal2D, LazySignal2D)

/Users/macark/Documents/hyperspy/hyperspy/_signals/lazy.py in <module>()
     22 import numpy as np
     23 import dask.array as da
---> 24 import dask.delayed as dd
     25 from dask import threaded
     26 from dask.diagnostics import ProgressBar

//anaconda/lib/python3.5/site-packages/dask/delayed.py in <module>()
      8 from toolz import merge, unique, curry, first
      9 
---> 10 from .utils import concrete, funcname, methodcaller
     11 from . import base
     12 from .compatibility import apply

ImportError: cannot import name 'methodcaller'`

**Comment by francisco-dlp** [comment]
It turns out that hspy requires dask >= 0.13 (latest version)
