### ISSUE TITLE
https for our website

### ISSUE THREAD

**Issue by to266** [hyperspy/hyperspy#1479]
We should get our website support https.
I guess [let's encrypt](https://letsencrypt.org/) is the way to go?

**Comment by to266** [comment]
For later or whoever tackles this:

https://mdjnewman.me/2017/07/migrating-a-github-pages-blog-with-a-custom-domain-to-https/

https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/

**Comment by magnunor** [comment]
We should get this working soonish, as browsers such as Chrome will soon show non-https websites as insecure: https://security.googleblog.com/2018/02/a-secure-web-is-here-to-stay.html

Deadline is July this year.

**Comment by to266** [comment]
FYI: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by francisco-dlp** [comment]
I've just enabled https for the website. That involved updating the DNS records, so it should take a few hours to work properly (currently I get a certificate error in firefox because the DNS update has not yet spreaded here.

**Comment by francisco-dlp** [comment]
It works, so closing.
