### ISSUE TITLE
Importing and preference.gui() trouble

### ISSUE THREAD

**Issue by erh3cq** [hyperspy/hyperspy#1482]
Hello all,

I have been trying to use hyperspy to analyse some line scans (and eventually images).  Great program by the way!   My .edu domain is blocking me from posting in the google group.  I am still a novice, and need some help. Mainly regarding curve fitting, but a few other tasks first.  Here are two:

1.  I have custom functions/components that I have coded.  In what way can I implement them so they are apart of hs.model.components1D? Currently I am adding them as an import in components1d.py (importing from a folder in an external file tree).
example: runningFile.py and _customComponents are in the same folder.  _customComponents contains a custom components and modified deconvolution routines. components1D.py in hyperspy has an import pointing to the _customComponents folder.
 If I do not perform the import in the components1d.py then I receive an error when attempting to plot. 
AttributeError                            Traceback (most recent call last)
<ipython-input-20-6c44ee44c254> in <module>()
      1 get_ipython().magic('matplotlib')
----> 2 model0.isig[zlpLimit.data.mean():40.].plot(plot_components=True)
      3 model0.red_chisq.plot()
      4 plt.savefig(join(saveToFolder,'ratio','')+'chi-square.tif')
C:\Users\mse334\Anaconda3\envs\data-analysis\lib\site-packages\hyperspy\model.py in __getitem__(self, slices)

   1750                 if 'init' in parse_flag_string(flags_str):
   1751                     init_args[k] = value
-> 1752             _model.append(getattr(components, comp._id_name)(**init_args))
   1753         copy_slice_from_whitelist(self.model,
   1754                                   _model,
AttributeError: 'DummyComponentsContainer' object has no attribute 'InterfracePlasmonDrude'

I would like to implement my own functions (that are located in an external folder), because if in the future I pull from github all of the files i edit will be cleaned up (my imports will no longer exist in components1d.py).  Also, since I am importing my functions into the components1d.py file, if I use hyperspy in a folder not containing _customComponents, the import fails, so hyperspy is not happy.

Am I missing an obvious solution?

2.  If I try to use hs.preferences.gui(), I get an error:
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-2-bc7945c7fb7c> in <module>()
      1 os.environ["QT_API"] = "pyqt"
      2 get_ipython().magic('matplotlib')
----> 3 hs.preferences.gui()

C:\Users\mse334\Anaconda3\envs\data-analysis\lib\site-packages\hyperspy\defaults_parser.py in gui(self)
    311         self.EELS.trait_view("traits_view",
    312                              hyperspy.gui.preferences.eels_view)
--> 313         self.edit_traits(view=hyperspy.gui.preferences.preferences_view)
    314 
    315     def save(self):

C:\Users\mse334\Anaconda3\envs\data-analysis\lib\site-packages\traits\has_traits.py in edit_traits(self, view, parent, kind, context, handler, id, scrollable, **args)
   1869 
   1870         return view.ui( context, parent, kind, self.trait_view_elements(),
-> 1871                         handler, id, scrollable, args )
   1872 
   1873     #---------------------------------------------------------------------------

C:\Users\mse334\Anaconda3\envs\data-analysis\lib\site-packages\traitsui\view.py in ui(self, context, parent, kind, view_elements, handler, id, scrollable, args)
    431             kind = self.kind
    432 
--> 433         ui.ui( parent, kind )
    434 
    435         return ui

C:\Users\mse334\Anaconda3\envs\data-analysis\lib\site-packages\traitsui\ui.py in ui(self, parent, kind)
    220                                    dispatch = 'ui' )
    221         self.rebuild = getattr( toolkit(), 'ui_' + kind )
--> 222         self.rebuild( self, parent )
    223 
    224     #---------------------------------------------------------------------------

C:\Users\mse334\Anaconda3\envs\data-analysis\lib\site-packages\traitsui\toolkit.py in ui_live(self, ui, parent)
    218             interface using information from the specified UI object.
    219         """
--> 220         raise NotImplementedError
    221 
    222     def ui_modal ( self, ui, parent ):

NotImplementedError: 

Thank you for the help!

**Comment by francisco-dlp** [comment]
How did you import hyperspy? Unfortunately the order of the commands matter. The following should work assuming that you have qt4 installed:

```python

%matplotlib qt4
import hyperspy.api as hs

```

**Comment by erh3cq** [comment]
True, and thank you!  That fixed 2.  Any idea on 1?

**Comment by francisco-dlp** [comment]
If you can write your component using ``Expression`` then it'll work. If not, unfortunately at present model slicing doesn't support external components because it was designed to enable splitting the fitting to run it in parallel with SAMFire. For your purpose that's irrelevant. it should be possible to add support for slicing model with external components when not using it for SAMFire. Would you like to open an issue about it?

Another option is to create your own fork of HyperSpy containing your components. if you think that they can be of general interest, you could then send a pull request for inclusion in HyperSpy.

**Comment by erh3cq** [comment]
I may do that after I clean it all up. I'm not the best coder.  So far I
have the FourierRatio method deconvoluting any two spectrum (rather than
approximating the ZLP), Skew Lorentzian, and an InterfacePlasmonDrudeModel.
Also, an edit to the .dm3 import.

So I just tried

%matplotlib qt4import hyperspy.api as hs

on my work computer and received an error.  Down graded pyqt to 1.2.1 and
now it works.  Am I correct in that hyperspy does not work with the latest
version of pyqt?
