### ISSUE TITLE
hologram tests failing in minicodan 35 32bit

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#1484]
We thought that it was a random error or an appveyor timeout but it's not, the tests are failing. Unfortunately appveyor doesn't print more details. This is the only issue holding the release.

```hyperspy\tests\signal\test_hologram_image.py ....FFFFFFCommand exited with code -1073741819```

**Comment by francisco-dlp** [comment]
I've been able to reproduce it in winpython 32. However, the issue is only triggered when running all the tests. When running just the holography tests they pass (!). When running all the tests py.test simply crashes after failing several holography tests. I suspect that this is related to the lazy tests. Does anybody have any clue of what's going on?

**Comment by ericpre** [comment]
Recently, there was [one build](https://ci.appveyor.com/project/hyperspy/hyperspy/build/1.0.2011/job/oepjwx9gt5fwk4to) with a more detailed failure message than usual. Just in case, if it can help...

**Comment by to266** [comment]
Well the more detailed error just confirmed that the memory requirements for the test are the problem, which is what we suspected

Ideally the tests in question should be rewritten to be much lighter (and at the same time faster to run!)

**Comment by francisco-dlp** [comment]
Fixed in #1463
