### ISSUE TITLE
Warnings when doing s.remove_background with multidimensional signal

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#1488]
```Python
import hyperspy.api as hs
import numpy as np
s = hs.signals.Signal1D(np.arange(1000)[::-1].reshape(10,100))
s.remove_background(signal_range=(10, 40))
```
gives a lot of warnings:
```Python
WARNING:hyperspy.component:`active_is_multidimensional` already False for PowerLaw
WARNING:hyperspy.component:`active_is_multidimensional` already False for PowerLaw
WARNING:hyperspy.component:`active_is_multidimensional` already False for PowerLaw
WARNING:hyperspy.component:`active_is_multidimensional` already False for PowerLaw
WARNING:hyperspy.component:`active_is_multidimensional` already False for PowerLaw
```
This does not happen with 1D-signals with no navigation dimension.

**Comment by to266** [comment]
I don't really understand why these warnings scare people so much, but at this point I'm just for removing the warning  - it's not really useful. Either you know what you're doing and the warning is useless, or you don't know what the `active_is_multidimensional` does and hence the warning is not only useless but also, apparently, scary. 

A much more laborious solution would disable the warning when the model is sliced internally, however I don't think it's useful to keep it to begin with.

@francisco-dlp, thoughts?

**Comment by thomasaarholt** [comment]
@to266 it is a bit scary, but more so it just clutters the notebook massively if it prints loads of warnings. That's of course a notebook issue (should be able to hide warnings separately from the print), but it's something we can do something about here.

**Comment by francisco-dlp** [comment]
:+1: for removing the warnings.

**Comment by to266** [comment]
https://github.com/hyperspy/hyperspy/pull/1492
