### ISSUE TITLE
GPU acceleration for HyperSpy

### ISSUE THREAD

**Issue by dnjohnstone** [hyperspy/hyperspy#1490]
We're potentially missing a trick by not really enabling any GPU acceleration in HyperSpy.

Any thoughts on the viability of accelerating functions this way - it's becoming particularly necessary with Signal2D datacubes?

I guess NumbaPro is the platform we'd work off? https://docs.continuum.io/numbapro/quickstart

**Comment by tjof2** [comment]
Isn't NumbaPro deprecated? https://docs.continuum.io/numbapro/. ArrayFire is another (under development) option: https://github.com/arrayfire/arrayfire-python but I've not tested it (had some success with the C++ version).

I wonder if profiling certain intensive functions and making use of plain Numba on the CPU might be of use - didn't @francisco-dlp have some success with this recently?

**Comment by to266** [comment]
I agree with the general motion. Which functions do you have in mind in particular?

**Comment by dnjohnstone** [comment]
@tjof2 fair point - there's also the accelerate replacement for numbapro then https://docs.continuum.io/accelerate/

@to266 I think most of the things I was imagining are essentially applications of map(), which I often use to e.g. do a Gaussian blur of an image stack or whatever; also doing FFTs of image stacks (I know we still need to finish the FFT function) with acceleration would be good. As is obvious - I don't really know what I'm talking about on the practicalities though particularly in the case of making this sufficiently general for HyperSpy.

I guess this may be tricky as the functions doing the operations are not in HyperSpy...

**Comment by magnunor** [comment]
@tjof2, we've been using ArrayFire here (the C++) version, and it is very nice since it abstracts away the complexities of writing your own GPU-kernels. But (imo), it can be a big hassle to set up properly currently unless you use a precompiled version. Debian has packages for ArrayFire, but I haven't had much luck using them (but I haven't really tried that much) and it seems the Debian version is lagging behind upstream. Arch Linux has it in AUR which makes things much easier.

**Comment by to266** [comment]
I'd bet on `numba` and `accelerate`. They people behind them created it (as I understand it) _precisely_ to be able to use the GPU and jit'ed (C speeds) functions easily on a variety of hardware without much setup

EDIT: actually I may not know what I'm talking about. I say just see whichever is simpler to implement and them make work on an arbitrary (oldish) NVIDIA windows machine. Here I assume linux is either simpler to setup, or the user is more willing to struggle a little bit, or more competent to make it work ;)

**Comment by francisco-dlp** [comment]
I've tried using gpu with numba in the past and it is great. However, I don't see how we can make use of it as most of the functions that would benefit from GPU acceleration are imported from elsewhere.

**Comment by magnunor** [comment]
As far as I can tell Anaconda Accelerate is not open source?

**Comment by dnjohnstone** [comment]
On reflection - I think it's better to keep this stuff in packages that are imported, as Francisco suggested long ago!
