### ISSUE TITLE
Default signal_type for 3D or higher

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#1493]
When loading EMD-files with no 'signal_type' attribute, the HyperSpy IO function tries to guess the `signal_type` the signal should have using the dtype and signal dimensions.

This works fine for signals with 1 or 2 data dimensions, which are loaded as either `signal1D` or `signal2D`. For signals with 3 dimensions or higher the signal is loaded as a `BaseSignal`, which is not very useful since (as far as I know) there is no easy way to do any plotting with a `BaseSignal`.

So when there is no `signal_type` and the data dimensions are three or higher, the datasets should be loaded as `signal2D`, since this makes it possible visualize the data.

**Comment by francisco-dlp** [comment]
The thing is that there is not way to tell if 1D or 2D plotting is appropriate for the data. Therefore, HyperSpy let's the user decide. It's as simple as calling ``s.as_signal1D`` or ``s.as_signal2D``. Maybe printing an informative warning in the log would do?

**Comment by magnunor** [comment]
That is true, but for my case the datasets are rather big (8 GB+) making using `s.as_signal2D` slow and time consuming. In addition, having the `plot` function available makes it easier to figure out which dimensions one want to use.

I could of course simply add something to my file writer, but there will probably be more and more people generating very large 4D datasets, and having HyperSpy at least showing some kind of visualization by default would be nice.

**Comment by francisco-dlp** [comment]
That's precisely one of the strengths of HyperSpy, you can customise the view of your signal without rearranging the data in memory. Try ``transpose((<x>, <y>))``, that should be fast. You can of course chain it with a plot call ``transpose((<x>, <y>)).plot()``

**Comment by to266** [comment]
While @francisco-dlp  example works because the first kwarg is `signal_axes`, ideally I would still type it out: `s.transpose(signal_axes=2).plot()` or `s.transpose(signal_axes=('x', 'y')).plot()`, etc.

Obviously you can do the same with navigation axes, or even both (but then you have to make sure you specify all of them, whereas in other cases the silent axes are left as "the opposite").

You could even do something like `hs.plot.plot_images(hs.transpose(*siglist, signal_axes=2))`, which would try to make sure all signals in the siglist have two signal axes. Feel free to play with the transpose, as it's essentially what it was made for!

**Comment by magnunor** [comment]
That is much, much faster compared to `s.as_signal`, nice!

But I even if this solves the immediate problem, it would be nice to be able to specific in some way how many signal dimensions one wants in an EMD-file. For example, saving a 3D HyperSpy `Signal2D`, and loading it again gives a `BaseSignal`. Doing the same with a 2D HyperSpy `Signal2D` yields a `Signal2D`.

**Comment by francisco-dlp** [comment]
Maybe that's something to fix on the EMD specification side?

**Comment by magnunor** [comment]
That could be possible, I'll see what the NCEM people think about adding it.

**Comment by ericpre** [comment]
I think this can be close now? Particularly with #2180.
