### ISSUE TITLE
hs.load ignoring signal_type argument in some cases

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#1494]
When loading datasets with the `signal_type` argument, the wrong signal subclass is returned:

```Python
>>> s = hs.signals.Signal1D(np.random.random((100, 10, 10)))
>>> s.save("test.emd")
>>> s1 = hs.load("test.emd", signal_type="EELS")
>>> s1
<BaseSignal, title: __unnamed__, dimensions: (|10, 10, 100)>
```

**Comment by francisco-dlp** [comment]
Even this fails:

```python

>>> s1.set_signal_type("EELS")
>>> s1
<BaseSignal, title: __unnamed__, dimensions: (|10, 10, 100)>
```

**Comment by francisco-dlp** [comment]
It is not actually a bug, the following works:

```python
>>> s1 = hs.load("test.emd", signal_type="EELS").transpose(signal_axes = (-1,))
<EELSSpectrum, title: __unnamed__, dimensions: (10, 10|100)>

```

It is the same story again: as the signal axis is not defined in the file, HyperSpy can't decide for the user and a signal with signal dimension 3 always becomes a ``BaseSignal``.

**Comment by thomasaarholt** [comment]
I guess the solution is to set the last axis to be the signal axis for any signal_type of EELS, EDS, and the last two for signal2Ds like Hologram? Afaik there aren't any signal types at the moment that could be either 1D **or** 2D, so we don't have to worry about that yet?

**Comment by francisco-dlp** [comment]
As you are all positive about this, let's get it into 1.2 in a mild form: I'll add an option to preferences to save using the ``hspy`` extension with default to ``False``. In the next minor release we can make it default to ``True``. In this way, from 1.2 onwards HyperSpy will be able to recognise the new extension and users will have time to adapt.

**Comment by magnunor** [comment]
@thomasaarholt, I think that would be an ok default solution, since I feel actually returning a `BaseSignal` is not very useful. Especially for novice users, which if they get a `BaseSignal`, and try plotting it they'll get the error `ValueError: Plotting is not supported for this view`.

Even though it might go wrong for some datasets, for example 1D spectra being visualized as an image. At least it will show something.

**Comment by to266** [comment]
Would it not be better then to provide a more useful error message instead? For example something like
`"Plotting is not supported in this view. Try 's.transpose(signal_axes=1).plot()' or similar instead"`

**Comment by francisco-dlp** [comment]
I think that specially for novice users it is easier to know where the issue is if we don't set a default plottable view. In this way they'll easy realise that something is wrong and, if we document it properly, they'll know that they have to set the signal axes as the file did not contain this information.

**Comment by magnunor** [comment]
Adding a better warning would improve things, so +1.

But it would be useful to be able to set the signal axes directly from the load function. Maybe something like:

```Python
>>> s = hs.load("test.emd", signal_type='Signal2D', signal_axes=(0,1))
```

And if the `signal_type` and `signal_axes` doesn't match, throw an error.

**Comment by to266** [comment]
I would be against setting this on loading: it complicates the `hs.load` and does not achieve anything that could not be done with two commands in the same line:
```python
s = hs.load("test.emd").transpose(signal_axes=(0,1))
```

**Comment by francisco-dlp** [comment]
I agree with @to266. ZoP:

> There should be one-- and preferably only one --obvious way to do it.

**Comment by francisco-dlp** [comment]
Would anybody like to contribute an informative message to fix this for the 1.2 release?

**Comment by magnunor** [comment]
I can do it, unless someone else has already started.

**Comment by magnunor** [comment]
https://github.com/hyperspy/hyperspy/pull/1495

**Comment by to266** [comment]
Feel free to close if you think it's addressed
