### ISSUE TITLE
CircularROI does not work with lazy_signal on navigation

### ISSUE THREAD

**Issue by dnjohnstone** [hyperspy/hyperspy#1505]
Seems that if you use a circular ROI to sum over navigation axes of a lazy signal it just doesn't work returns a load of nans - is that right or me being stupid?

**Comment by francisco-dlp** [comment]
That's one of the few things that behave differently with lazy signals. See the [User Guide](http://hyperspy.readthedocs.io/en/latest/user_guide/big_data.html#other-minor-differences).

**Comment by francisco-dlp** [comment]
Can this be closed?

**Comment by dnjohnstone** [comment]
Thanks for the info on that!
