### ISSUE TITLE
Anaconda update

### ISSUE THREAD

**Issue by erh3cq** [hyperspy/hyperspy#1515]
Does anyone know how to update hyperspy on anaconda form gitHub?
I have tried the typical with no luck.
`pip install --upgrade https://github.com/hyperspy/hyperspy.git`
`pip install --upgrade git+https://github.com/hyperspy/hyperspy.git`

**Comment by francisco-dlp** [comment]
The second one works for me. What's the error that you get?

**Comment by erh3cq** [comment]
pip install --upgrade git+https://github.com/hyperspy/hyperspy.git Collecting
git+https://github.com/hyperspy/hyperspy.git Cloning https://github.com/hyperspy/hyperspy.git to c:\users\ericho~1\appdata\local\temp\pip-u_41468g-build Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/hyperspy/hyperspy.git C:\Users\ERICHO~1\AppData\Local\Temp\pip-u_41468g-build Cannot find command 'git'

**Comment by francisco-dlp** [comment]
Try this:

```bash
pip install --upgrade --no-deps https://github.com/hyperspy/hyperspy/archive/RELEASE_next_minor.zip
```

**Comment by erh3cq** [comment]
Yep that seems to work.  So what did that do differently? For example if I would like to now update from my branch instead?

**Comment by francisco-dlp** [comment]
Your original command works in Linux but, for some reason, it didn't work for you in Windows, possibly because it couldn't find git. The one I proposed doesn't require git as it downloads the zip file directly from github. Just change the address to point to your branch instead, something like ``pip install --upgrade --no-deps https://github.com/hyperspy/erh3cq/archive/your_branch_name_here.zip``.

**Comment by erh3cq** [comment]
Perfect. Lots of help as always Francisco.  Another curiosity. I have two branches off my fork erh3cq/hyperspy.  Both have had pull requests (one merged already!).  I need both of the branches regardless if they are merged.  Should I merge my forks to RELEASE_next_minor in my fork? Then, update conda from there?

**Comment by francisco-dlp** [comment]
Probably it's better that you create a new "workhorse" branch in your repository where you can merge all the branches (yours and other's) that you need for your work. Also, probably it'll  be easier if you install hyperspy in development mode, so that you don't need to reinstall it every time that the code changes. From your local fork folder:

```bash
pip install -e .
```

**Comment by erh3cq** [comment]
Like this?` pip install -e --no-deps https://github.com/hyperspy/erh3cq/archive/<new branch name>.zip`
Should I delete my previous conda hyperspy install?

**Comment by francisco-dlp** [comment]
Usually you install it using your local repository although a remote one is also possible. It is [documented here](https://pip.pypa.io/en/stable/reference/pip_install/#editable-installs). You don't need to uninstall your current version.

**Comment by erh3cq** [comment]
Seems to have worked (used my local repository as suggested). With one possible concern:
`Installing collected packages: hyperspy`
` Found existing installation: hyperspy 1.3+dev`
`    Uninstalling hyperspy-1.3+dev:`
`      Successfully uninstalled hyperspy-1.3+dev`
`  Running setup.py develop for hyperspy`
`Successfully installed hyperspy-1.1.1`

The last line says that 1.1.1 was installed, but I have the most recent 1.3+Dev version in my local directory.  If I look in the Release.py file, it says that the current version 1.3+Dev.  So I think it installed the correct version and this is a bug (or I did something incorrectly)

**Comment by francisco-dlp** [comment]
That indeed strange. To verify the version that you have installed:

```python

import hyperspy
print(hyperspy.__version__)
print(hyperspy.__file__)
```

**Comment by erh3cq** [comment]
Results:
```
1.3+dev
c:\users\eric hoglund\documents\github\hyperspy\hyperspy\api.py
```

**Comment by francisco-dlp** [comment]
Looks good!

**Comment by erh3cq** [comment]
So it is just a bug in Anaconda that it shows 1.1.2 in the navigator?

**Comment by francisco-dlp** [comment]
I have no idea, I don't use their GUI. By the way, are you aware of our [gitter chat](https://gitter.im/hyperspy/hyperspy)? This may be a better fit for this sort of exchanges.
