### ISSUE TITLE
to little constrained assertations

### ISSUE THREAD

**Issue by sem-geologist** [hyperspy/hyperspy#1532]
Week ago new numpy version started to be used on conda linux, then conda osx (travis).
Today the same tests started to fail on the appveyor (as windows conda started to adapt the new version too).

The problem would not appear in the first place if test would be constructed correctly.
There is `rtol` and `atol` parameters in `assert_allclose` testing function of numpy. The tests without using those parameters leaves the test for numpy developers mercy, and as this happens not first time, small change in numpy behaviour/ defaults brakes testing. My main concern is when tests are made with only half defined parameters. particularly asserting floating point similarity or closeness should contain the precision for such assertions not depending is it testing by testing suit, or is it testing with numpy testing. Never believe in defaults – they change. I think the problem is that in development documentation is only mentioned the tools, I think we should add the sentence about importance of using correct-sane assertation constrains and do not lean on default behavior (rtol, atol).

**Comment by francisco-dlp** [comment]
:+1:

**Comment by sem-geologist** [comment]
so what correct `rtol` and `atol` should be in `hyperspy\tests\signal\test_1D_tools.py` `TestInterpolateInBetween` ?

**Comment by sem-geologist** [comment]
I actually can't understand exactly what `rtol` and `atol` is the numpy documentation have not enough examples to grasp how to set it correctly...

I can make the currently offending test to pass by setting `rtol=1e-02` as I understand it is relative tolerance which would be 1% ? `rtol=5e-03` also works which is 0.5%?

**Comment by sem-geologist** [comment]
actually that whole `TestInterpolateInBetween` test I find quite cryptic... what it exactly checks?

**Comment by sem-geologist** [comment]
@francisco-dlp , it is very highly possible that it is actually not numpy's fault for newly failing tests, but scipy, which was updated recently to 0.19 and changes quite much `interpolate` method. probably test have to be re-investigated and re-tweaked. But real question is: is the test at all needed there? – basically it is a wrapper around scipy, if scipy will be keeping on improving the output of `interpolate` with every release--we will hardly keep adjusting the tests.

1. I mean: what is the point of testing stuff which we do not brake?
2. maybe better idea would be to make test of wrapper methods to raise deprecation when failed instead of nuking everything?

P.S. it is even "better": scipy.interpolate is wrapper for something else... so hyperspy basically does wrapper of wrapper... and test it with hard coded  values. So if scipy changes something – brake. if wrapped library by scipy changes something – brake...

**Comment by to266** [comment]
@sem-geologist I guess most tests can be either testing the actual functionality (i.e. if we implemented the algorithm ourselves) or just making sure that it works as we intended to detect changes that were introduced by upstream libraries, which I assume happened here. This should trigger us checking that the function behaves as we expect, and thus either fix the function or the test.
