### ISSUE TITLE
micro bug fix for components.summary()

### ISSUE THREAD

**Issue by ialxn** [hyperspy/hyperspy#1542]
fix for `model.components.summary()`

`import hyperspy.api as hs`
`g1 = hs.model.components1D.Gaussian(A=500, sigma=70, centre=123.45)`
`g2 = hs.model.components1D.Lorentzian(A=1.0, gamma=2.0, centre=3.0)`
`print('g1.summary')`
`g1.summary()`
`print('g2.summary')`
`g2.summary()`

output before patch (diff -Naur)

:
`g1.summary`
`g2.summary`

output after patch:
`g1.summary`
`A = 500.0 ± None `
`sigma = 70.0 ± None `
`centre = 123.45 ± None `
`g2.summary`
`A = 1.0 ± None `
`gamma = 2.0 ± None` 
`centre = 3.0 ± None`

patch:
`--- component_old.py	2017-03-21 12:33:18.482254646 +0100`
`+++ component.py	2017-03-21 12:34:17.945882411 +0100`
`@@ -1105,10 +1105,10 @@`
`                 is not None else 0`
`             if parameter.twin is None:`
`                 if dim <= 1:`
`-                    return ('%s = %s ± %s %s' % (parameter.name,`
`-                                                 parameter.value,`
`-                                                 parameter.std,`
`-                                                 parameter.units))`
`+                    print ('%s = %s ± %s %s' % (parameter.name,`
`+                                                parameter.value,`
`+                                                parameter.std,`
`+                                                parameter.units))`
` `
`     def __call__(self):`
`         """Returns the corresponding model for the current coordinates`

**Comment by francisco-dlp** [comment]
Thanks for this and #1543. Although we could apply the patches ourselves, it'll be good if you could submit two pull requests branching from RELEASE_next_patch. If you are not familiar with sending pull requests, you'll find some help in our [dev guide](http://hyperspy.org/hyperspy-doc/current/dev_guide.html). Don't hesitate to ask for help in this thread or the [gitter chat](https://gitter.im/hyperspy/hyperspy).
