### ISSUE TITLE
micro bug fix for model.print_current_values()

### ISSUE THREAD

**Issue by ialxn** [hyperspy/hyperspy#1543]
At present `model.print_current_values()` only prints components that have no `__iter__` attribute.

`import hyperspy.api as hs`
`s = hs.load('wobbly_peak.hdf5')`
`sin = hs.model.components1D.Expression('A*sin(b*x + c)', name='sin', A=100, b=0.1, c=10)`
`gaus = hs.model.components1D.Gaussian(centre=500)`
`poly = hs.model.components1D.Polynomial(2)`
`m = s.create_model()`
`m.extend([sin, gaus, poly])`
`m.fit()`
`m.print_current_values()`

Output before patch:
Note, no output for Polynomial.

`Components      Parameter       Value`
`sin`
`                A       3.11476`
`                b       0.105981`
`                c       7.80408`
`Gaussian`
`                A       1`
`                centre  500`
`                sigma   1`
`Polynomial`

after patch:
Naming of the components could be fixed to comply with official style (did not find anything)

`Components      Parameter       Value`
`sin`
`                A       3.11476`
`                b       0.105981`
`                c       7.80408`
`Gaussian`
`                A       1`
`                centre  500`
`                sigma   1`
`Polynomial`
`                a[0]    -0.00117882`
`                a[1]    0.413538`
`                a[2]    -4.8575`

patch
`--- model_old.py	2017-03-21 15:21:32.577933994 +0100`
`+++ model.py	2017-03-21 15:22:55.813400171 +0100`
`@@ -1483,6 +1483,9 @@`
`                     if not hasattr(parameter.value, '__iter__'):`
`                         print("\t\t%s\t%g" % (`
`                             parameter.name, parameter.value))`
`+                    else:`
`+                        for parid in range(len(parameter.value)):`
`+                            print("\t\ta[%d]\t%g" % (parid, parameter.value[parid]))`
 
     def set_parameters_not_free(self, component_list=None,
                                 parameter_name_list=None):

**Comment by francisco-dlp** [comment]
#1549
