### ISSUE TITLE
Widget Javascript not detected.

### ISSUE THREAD

**Issue by ialxn** [hyperspy/hyperspy#1550]
I am getting these warnings quite regularly when using hyperspy in an Ipython console of spyder.

`In [199]: P = s.find_peaks1D_ohaver(maxpeakn=1)[0]`
`Widget Javascript not detected.  It may not be installed or enabled properly.`

I am using a Conda installation on an Ubuntu 16.04 system and installed hyperspy from conda-forge.

`uname -a`
`Linux PC12348 4.4.0-66-generic #87-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux`

conda list (excerpt)
`hyperspy                  1.2                      py36_0    conda-forge`
`ipykernel                 4.5.2                    py36_0  `
`ipython                   5.3.0                    py36_0  `
`ipython_genutils          0.1.0                    py36_0 ` 
`ipywidgets                6.0.0                    py36_0  `

Any help appreciated or is this a Conda/Anaconda issue?

**Comment by francisco-dlp** [comment]
I have no experience with spyder. The ipywidgets AFAIK are only displayed in the Jupyter Notebook. You could try executing the following to see if you stop getting the warnings:

```
jupyter nbextension enable --py --sys-prefix widgetsnbextension

```

**Comment by ialxn** [comment]
I also get the warnings in a Jupyter Notebook:

`jupyter nbextension enable --py --sys-prefix widgetsnbextension`
`Enabling notebook extension jupyter-js-widgets/extension...`
`      - Validating: OK`

And then in the Notebook:

`In[1] :`
`import hyperspy.api as hs`
`s = hs.datasets.example_signals.EDS_TEM_Spectrum()`
`P = s.find_peaks1D_ohaver()[0]`

`Widget Javascript not detected.  It may not be installed or enabled properly.`

`In[2] :`
`print(P)`
`[( 0.27036457,  45.55279061,  0.13452197)`
` ( 2.08728685,  44.17690911,  0.19710746)`
` ( 8.05295601,  29.9608923 ,  0.23578648)`
` ( 9.44615124,  25.66354518,  0.26254275)]`

So this seems to be a more general issue.

**Comment by francisco-dlp** [comment]
In Linux deleting the  "~/.local/share/jupyter/nbextensions" folder has fixed the issue for me in the past. If it doesn't do it for you I would suggest raising the issue in the ipywidgets gitter chat/GH/mailing list.

**Comment by ialxn** [comment]
Did not help with me. I'll report an issue with the ipywidgets people. Thanks anyway

**Comment by to266** [comment]
Shouldn't this be closed?
