### ISSUE TITLE
BUG: Blind source separation with boolean mask fails

### ISSUE THREAD

**Issue by woozey** [hyperspy/hyperspy#1551]
I've tried using masking in BSS. Although the docs says:

> mask : bool numpy array or Signal instance.
    If not None, the signal locations marked as True are masked. The
    mask shape must be equal to the signal shape
    (navigation shape) when `on_loadings` is False (True).

It seems the current implementation allows only the use of Signal instances as mask:

> In [29]: s = hs.signals.Signal1D(np.random.rand(1000).reshape((10,100)))
s
Out[29]:
<Signal1D, title: , dimensions: (10|100)>
In [30]: mask = np.bool8(np.zeros(s.axes_manager.signal_shape))
mask[5] = True
In [31]: s.decomposition()
In [33]: s.blind_source_separation(3, mask=mask)

> AttributeError                            Traceback (most recent call last)
<ipython-input-33-43847959d872> in <module>()
----> 1 s.blind_source_separation(3, mask=mask.T)

> /Users/vadim/Work_Recent/Prog/_Py/hyperspy/hyperspy/learn/mva.py in blind_source_separation(self, number_of_components, algorithm, diff_order, diff_axes, factors, comp_list, mask, on_loadings, pretreatment, **kwargs)
    612                     if diff_axes is not None
    613                     else None)
--> 614                 mask.change_dtype("float")
    615                 mask.data[mask.data == 1] = np.nan
    616                 mask = get_derivative(mask,

> AttributeError: 'numpy.ndarray' object has no attribute 'change_dtype'

Providing mask as `Signal1D` works:
> In [34]: s.blind_source_separation(3, mask=hs.signals.Signal1D(mask))
In [35]: s.learning_results.summary()
Decomposition parameters:

> Decomposition algorithm : 	svd
Poissonian noise normalization : False
Output dimension : None
Centre : None

> Demixing parameters:

> BSS algorithm : sklearn_fasticaNumber of components : 3

I guess, either docs or code should be fixed...

**Comment by francisco-dlp** [comment]
Using an array is deprecated, but we forgot to update the docs. Thanks for reporting the issue!

**Comment by woozey** [comment]
@francisco-dlp 
> Using an array is deprecated

This is certainly a good idea since otherwise it creates ambiguity with use of (y,x) or (x,y) convention, at least for navigation space.
Is it a general rule than? If it is, the `decomposition` still takes nparrays and the docs don't mention `Signal` instances:
> navigation_mask : boolean numpy array
