### ISSUE TITLE
Increasing size of `r_inner` is buggy in CircleROI

### ISSUE THREAD

**Issue by ialxn** [hyperspy/hyperspy#1553]
If you interactively decrease `r_inner` the mask is updated correctly and the newly exposed part of the original signal is also correctly updated. However, if you interactively increase `r_inner` above its initial value at any time the part between the present value of `r_inner` and its new value (the part that should be freshly masked) is not white but filled with some other part of the initial signal.

Running on Ubuntu 16.04 / miniconda / HypderSpy 1.2 (python 3.6)

**Comment by ericpre** [comment]
It looks to me that this is also [due to blitting](https://github.com/hyperspy/hyperspy/issues/1554#issuecomment-815065281). Closing as duplicate of #1554.
