### ISSUE TITLE
spikes_removal_tool() fails on Mac, python 3.4

### ISSUE THREAD

**Issue by woozey** [hyperspy/hyperspy#1559]
For some reason `spikes.removal.tool()` fails on mac with fresh python 3.4 environment (conda), hyperspy installed using `conda install` with both `traits` and `traitsui` updated to the latest version. No other errors detected for other non-ui functions. Any suggestions?

> In [1]: %matplotlib qt
import hyperspy.api as hs
import numpy as np
import matplotlib.pyplot as plt
In [2]: s=hs.load('02.dm3')
In [3]: s.plot()
In [4]:s.spikes_removal_tool()
NotImplementedError                       Traceback (most recent call last)
<ipython-input-37-d42d0b17f940> in <module>()
----> 1 s.spikes_removal_tool()

> /Applications/anaconda/envs/python34/lib/python3.4/site-packages/hyperspy/_signals/signal1d.py in spikes_removal_tool(self, signal_mask, navigation_mask)
    307                            navigation_mask=navigation_mask,
    308                            signal_mask=signal_mask)
--> 309         sr.configure_traits()
    310         return sr
    311 

> /Applications/anaconda/envs/python34/lib/python3.4/site-packages/traits/has_traits.py in configure_traits(self, filename, view, kind, edit, context, handler, id, scrollable, **args)
   2170                 context = self
   2171             rc = toolkit().view_application( context, self.trait_view( view ),
-> 2172                                            kind, handler, id, scrollable, args )
   2173             if rc and (filename is not None):
   2174                 fd = None

> /Applications/anaconda/envs/python34/lib/python3.4/site-packages/traitsui/toolkit.py in view_application(self, context, view, kind, handler, id, scrollable, args)
    289 
    290         """
--> 291         raise NotImplementedError
    292 
    293     #---------------------------------------------------------------------------

> NotImplementedError:

**Comment by woozey** [comment]
Installing `hyperspyui` in addition to main package seem to solve the problem...

**Comment by thomasaarholt** [comment]
Do we have any idea what caused this? Could qt5 have been installed instead of qt4?

**Comment by thomasaarholt** [comment]
Woozey, were you able to reproduce this? I just installed hyperspy in a fresh 3.4 env on my mac and cannot replicate.

**Comment by francisco-dlp** [comment]
If this is a hspy issue, it is likely that it has been fixed in #1544, could you verify it?

**Comment by woozey** [comment]
> Woozey, were you able to reproduce this?

Yes I was able to reproduce it on my non-fresh installation on Mac too with probably older dev version of Hyperspy...

**Comment by ericpre** [comment]
@woozey, is this issue still occurring?

**Comment by woozey** [comment]
@ericpre, sorry for late response. It seem to work on all the systems I have access to... I couldn't check it with traits UI though...

**Comment by ericpre** [comment]
Ok thanks, closing then.
