### ISSUE TITLE
s.get_lines_intensity() results in very large files

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1568]
I just saved two maps gotten from a EDS SI in HyperspyUI. The maps, Nb and Fe, are both extremely large (180 MB), despite being of shape (163, 153).
I think the issue is that the decomposition that I performed on the original EDS SI is kept in the files afterwards. It would be nice if this was removed on `s.get_lines_intensity`.

**Comment by thomasaarholt** [comment]
Btw, the decomposition was performed via the console in normal hyperspy manner.

**Comment by francisco-dlp** [comment]
This is probably due to what's stored in ``metadata``.

**Comment by ericpre** [comment]
Fixed in #2691.
