### ISSUE TITLE
Bug (?) in load_data()

### ISSUE THREAD

**Issue by ialxn** [hyperspy/hyperspy#1570]
I am loading EDS data with `load_data()`. If I read the data as a tuple

`a, b = hs.load(["1.msa", "2.msa"], signal_type='EDS_TEM')`

the data are correctly loaded independent of whether they have the same shape or the same calibration. If I load them as a stack

`s = hs.load(["1.msa", "2.msa"], signal_type='EDS_TEM', stack=True)`

I do get an error (`cannot broadcast`), which is correct, if they do not have the same shape. If the data have the same shape (same number of channels) but are differently calibrated (different values of `offset`, `scale`, and `units`) the data are read without problems but the calibration of the first spectrum read is silently applied to all subsequently read spectra.
We should probably issue an error too in this case.

**Comment by francisco-dlp** [comment]
That's a good point. Arithmetic operations behave in the same way: the calibration is ignored and propagated from left to right, also without warning. This is actually not a bug as the behaviour is intended for the sake of convenience: if the operation is valid for the (uncalibrated) arrays, hyperspy proceeds. Also, comparing calibration is not straightforward as, how close do they have to be to proceed? For example if one scale is 1 and the other one 1.000000000001, should stacking fail? That said, better documenting this behaviour and adding a warnings is certainly desirable.

**Comment by ialxn** [comment]
I agree with almost everything said. Once the data is in hyperspy it should be the user that takes care not to compare apples to bananas. Thus none of the operations in hyperspy should check the calibration data.
However loading the data is a different issue in my view. Also in this case the navigation axes should be ignored. They can be anything. They do not even have to represent a physical variable. The spectral is special. It is alway present and the user is conscious about it. Importing data that use different spectral ranges into a single signal does not seem to be a common case. At least I would splice the ranges together to get a single spectrum before loading the data. Thus, loading data with different spectral calibrations seems to be an user error in most cases and a warning should be issued to allow the user to investigate. Maybe there was an error involved - maybe it was just numerical noise.

Note added. It actually happened to me when I was loading a bunch of EDS data and performed a PCA that the result was really weired. After scratching my head a lot I found the error by pure luck. One of my spectra had `scale` differing by a factor of 2.0!. I would have been happy if a warning would have been issued during `hs.load()`
