### ISSUE TITLE
Inconsistent rcparams for sig and nav plots

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1578]
Setting `matplotlib.rcParams['figure.figsize'] = np.array([6.4, 4.8])/2`* changes the size of new signal plot windows, but not the navigator plot windows.

This implies that the navigator window figure size might be hard coded. It would be nice if it read out the default figure size.

This will become relevant for the `%matplotlib notebook` backend with the new ipywidget UI, as the interactive plot is inline. Huge images will make it difficult to use the controls.

*The list contains default parameters. Instead of `matplotlib`, `plt` can be used.

A way to set the same figure size is to change `matplotlib.rcParams['figure.dpi'] = 80`.

**Comment by ericpre** [comment]
Have you tried changing the dpi only without changing the figsize?

As far as I understood, the notebook backend of matplotlib and the ipywidgets are completely unrelated. You can still use hyperspy plots as before (even with pyqt5 if you are using the qt5 backend of matplotlib).

**Comment by thomasaarholt** [comment]
Just to clarify, the size of the ipywidgets is not in question :) It's just that the window ends up looking like 1 to begin with, and 2 after setting the figsize. 
As I mentioned, changing `"figure.dpi"` works, but that is just a workaround.

**Comment by thomasaarholt** [comment]
[1] with `%matplotlib nbagg`
<img width="273" alt="screen shot 2017-04-08 at 17 35 46" src="https://cloud.githubusercontent.com/assets/2721423/24830660/a6c77776-1c8a-11e7-8485-c0e47855dc7d.png">

**Comment by thomasaarholt** [comment]
[2] with `%matplotlib nbagg` and `mpl.rcParams['figure.figsize'] = np.array([6.4, 4.8])/2`
<img width="448" alt="screen shot 2017-04-08 at 18 39 40" src="https://cloud.githubusercontent.com/assets/2721423/24830668/c339ef4c-1c8a-11e7-8e97-6516434bf180.png">
