### ISSUE TITLE
Increasing marker size (+) doesn't work on %matplotlib nbagg

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1579]
Pressing + to increase the size of the red marker on the navigator plot does not work with the notebook backend.

**Comment by francisco-dlp** [comment]
I have tried to fix it in #1544, could you confirm that it fixes the issue for you?

**Comment by thomasaarholt** [comment]
On Mac, this still does not work. (tested in Chrome)

**Comment by francisco-dlp** [comment]
This works for me in Linux Firefox. I'll close it because if the bug is platform and/or browser dependent, then it's not a HyperSpy but a mpl issue.

**Comment by thomasaarholt** [comment]
Worked on Windows 5 minutes ago too :)

>
