### ISSUE TITLE
Always compile unbcf_fast?

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1581]
When I checkout a new PR, I get the following message:
```
Switched to a new branch 'pr/1580'
rm: /Users/thomas/hyperspy/hyperspy/io_plugins/unbcf_fast.cpython-35m-darwin.so: No such file or directory
Compiling hyperspy/io_plugins/unbcf_fast.pyx because it changed.
[1/1] Cythonizing hyperspy/io_plugins/unbcf_fast.pyx
```
Is there a particular reason this happens? I would think that very few PRs affect unbcf.

**Comment by francisco-dlp** [comment]
The original idea was that this would only be triggered when a pyx file changes across branches, but the current implementation does not include that feature.

**Comment by thomasaarholt** [comment]
👍

**Comment by ericpre** [comment]
Doesn't compile anymore when checking out a branch. See #1919.
