### ISSUE TITLE
s.set_signal_type("random_word") should fail

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1584]
Currently BaseSignal is returned if one enters the wrong name into signal_type. It should raise ~~an error~~ a warning.

**Comment by francisco-dlp** [comment]
Maybe not fail but print warning? If the signal is not supported, I think that it is good practice anyway to describe in this way in the metadata.

**Comment by thomasaarholt** [comment]
Agreed.
