### ISSUE TITLE
spikes_removal_tool() fails on PC Python 3.6.0 Anaconda 4.3.1 (64 bit)

### ISSUE THREAD

**Issue by quee2715** [hyperspy/hyperspy#1603]
For some reason spikes.removal.tool() fails on mac with fresh python 3.6 environment (conda), hyperspy installed using conda install with both traits and traitsui updated to the latest version. Any suggestions to fix it would be much appreciated. I have read pages where it describes the issue ought to be resolved when using Python 3. But this error persists.

in [1]: import hyperspy.api as hs
import numpy as np
%matplotlib qt4

in [2]: sll = hs.load('EELS Spectrum Image (low-loss) (dark ref corrected).dm3')
shl = hs.load('EELS Spectrum Image (high-loss) (dark ref corrected).dm3')

in [3]: sll.plot()

in [4]: sll.crop(1,10,171)
shl.crop(1,10,171)

in[5]: sll.align_zero_loss_peak(also_align=[shl],signal_range=(-5.,5.))

in [6]: sll.save('J2_SI2v2_LL_cropped_ZLPaligned.hdf5')
shl.save('J2_SI2v2_HL_cropped_ZLPaligned.hdf5')

in[7]: shl.spikes_removal_tool()
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-9-4b4625bf8dd3> in <module>()
----> 1 shl.spikes_removal_tool()

c:\programdata\anaconda3\lib\site-packages\hyperspy\_signals\signal1d.py in spikes_removal_tool(self, signal_mask, navigation_mask)
    345                            navigation_mask=navigation_mask,
    346                            signal_mask=signal_mask)
--> 347         sr.configure_traits()
    348         return sr
    349 

c:\programdata\anaconda3\lib\site-packages\traits\has_traits.py in configure_traits(self, filename, view, kind, edit, context, handler, id, scrollable, **args)
   2169                 context = self
   2170             rc = toolkit().view_application( context, self.trait_view( view ),
-> 2171                                            kind, handler, id, scrollable, args )
   2172             if rc and (filename is not None):
   2173                 fd = None

c:\programdata\anaconda3\lib\site-packages\traitsui\toolkit.py in view_application(self, context, view, kind, handler, id, scrollable, args)
    289 
    290         """
--> 291         raise NotImplementedError
    292 
    293     #---------------------------------------------------------------------------

NotImplementedError:

**Comment by francisco-dlp** [comment]
Could you try calling the matplotlib magic before anything else?:

```python

%matplotlib qt4
import hyperspy.api as hs

```

We are working on fixing this recurrent issue for good by providing ipywidgets as an alternative to traitsui, see #1544.

**Comment by quee2715** [comment]
It worked! Thank you very much!

**Comment by thomasaarholt** [comment]
@quee2715 Glad it worked. Could you close this issue?
