### ISSUE TITLE
m.as_signal progress bar bug

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#1604]
When using `m.as_signal(parallel=True, show_progressbar=True)`, in an IPython terminal a large number of what looks like newlines are outputted:

```Python
import hyperspy.api as hs
import numpy as np

s = hs.signals.Signal1D(np.zeros((10, 10)))
m = s.create_model()
m.as_signal(parallel=True, show_progressbar=True)
```
Gives this:
![parallel_true_show_progress_true](https://cloud.githubusercontent.com/assets/1690979/25484510/36388c80-2b52-11e7-8649-cffcca30521f.jpg)

Using `m.as_signal(parallel=True, show_progressbar=False)` still tries to show the progress bar:
![parallel_true_show_progress_false](https://cloud.githubusercontent.com/assets/1690979/25484548/56d1c93e-2b52-11e7-9153-febce60109f9.jpg)

Using `m.as_signal(parallel=False, show_progressbar=False)` and `m.as_signal(parallel=False, show_progressbar=True)` works fine.
![parallel_false_show_progress_false](https://cloud.githubusercontent.com/assets/1690979/25484581/79b7d1dc-2b52-11e7-8f04-df56e4ad446a.jpg)
![parallel_false_show_progress_true](https://cloud.githubusercontent.com/assets/1690979/25484583/7e3b86b8-2b52-11e7-8836-4f957bf4b692.jpg)

**Comment by magnunor** [comment]
Possibly related to this: https://github.com/tqdm/tqdm/issues/323

> From the traceback it seems you are using tqdm in a thread. Support for threading and multiprocessing is still in the works, ill give it another shot in the next few days.

**Comment by tjof2** [comment]
This is due to the level at which the parallelism is applied, resulting in a progressbar for each thread. The easiest thing is probably to simplify the loops.
