### ISSUE TITLE
Signal1D plot should take color argument.

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1612]
Seeing as `s.plot` specifies that `kwargs` are passed to matplotlib, either `color` or `c` should be possible to pass to make the plot plot in a different color:
For instance, the following doesn't work:
```python
hs.datasets.example_signals.EDS_SEM_Spectrum().plot(color="red")
```

**Comment by francisco-dlp** [comment]
I am not sure if this is a good idea as colors have a meaning. It is possible to customise colors using plain matplotlib or the private ``_plot`` API.

**Comment by thomasaarholt** [comment]
I think you are right to say that. My use-case is perhaps a bit too specific.
