### ISSUE TITLE
Getting Started appendix data no longer available

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1614]
The appendix data for [Getting Started](http://nbviewer.jupyter.org/github/hyperspy/hyperspy-demos/blob/master/1_Getting_Started.ipynb) is no longer available. (The url in "Download and unpack the machine learning example data").

Could the person who created it please reupload the test data? :/

**Comment by francisco-dlp** [comment]
Thanks for reporting the issue. It seems that we're having an issue with the local server hosting the data. It's not the first time that it happens, so we should consider moving the data to a more reliable server.
