### ISSUE TITLE
Digital Micrograph like Signal1D navigation

### ISSUE THREAD

**Issue by adriente** [hyperspy/hyperspy#1615]
Hi,

I tried to implement a method of Signal1D that displays :  
--> a span selector on a signal window
--> a fit of this signal's background with the help of the span selected datas
--> the difference between the total signal and the fitted background (i.e. the signal of interest)

Here is the code I wrote inside the Signal1D class :

````python
def bkgd_fitting(self,range_selector,background_type='PowerLaw',polynomial_order=2) :    
        if background_type == 'PowerLaw':
            background_estimator = components1d.PowerLaw()
        elif background_type == 'Gaussian':
            background_estimator = components1d.Gaussian()
        elif background_type == 'Offset':
            background_estimator = components1d.Offset()
        elif background_type == 'Polynomial':
            background_estimator = components1d.Polynomial(polynomial_order)
        else:
            raise ValueError("Background type: " +background_type +" not recognized")
        left_val, right_val = range_selector.left, range_selector.right
        no_bkgd=self._remove_background_cli((left_val,right_val),background_estimator)
        bkgd=-(no_bkgd)+self+np.min(self.data)
        ax=self._plot.signal_plot.ax
        lines=ax.lines
        if len(lines)==3 :
            lines[1].set_ydata(bkgd.data)
            lines[2].set_ydata(no_bkgd.data)
        else :
            ax.add_line(matplotlib.lines.Line2D(self._plot.axis.axis,bkgd.data))
            ax.add_line(matplotlib.lines.Line2D(self._plot.axis.axis,no_bkgd.data,color='g'))   
        return self
````

When I try to use my bkgd_fitting on a signal window, this way : 
````python
bkgd_inter=hs.interactive(roi_spectre.bkgd_fitting,
                          event=range_selector_sig.axes_manager.events.any_axis_changed,
                          recompute_out_event=None,
                          range_selector=range_selector)
````
with roi_spectre being a Signal1D extracted via a ROI and range_selector being a SpanROI object.
It displays correctly the span, the signal and the difference between signal and fitted background. But the background fit is incorrect in the span selected region, it is often way above the datas.
I don't understand why the _remove_background_cli method doesn't work so well to fit the background in my case.

Since I'm not a python/HyperSpy expert, there is (most probably) a better way to code what I want to implement. 

Thanks in advance for your help.

**Comment by francisco-dlp** [comment]
Could you send a complete script to test your function? (It's not clear what e.g. ``range_selector_sig`` is.)

I think that an easier way to attack the problem is to add an extra "backgroundless signal" line to the current [remove background gui code](https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/hyperspy/gui/egerton_quantification.py#L39). If you decide to go this way and you think that you may contribute your efforts back to the project, it may be better to branch from #1544 as the GUI part of the code is undergoing some important changes there.

**Comment by adriente** [comment]
````python
%matplotlib qt
import hyperspy.api as hs
import numpy as np
SPIM=hs.load("170217_SPIM01_top_film_sub.dm4")

SPIM.plot()
shared_roi = hs.roi.RectangularROI(left=3, right=7, top=2, bottom=5)
spim_roi=shared_roi.interactive(SPIM,color='red')
roi_spectre =hs.interactive(spim_roi.sum, event=spim_roi.axes_manager.events.any_axis_changed, recompute_out_event=None)
#Le premier argument est une méthode de la classe Signal1D et non pas un objet Signal1D

roi_spectre.plot()
range_selector=hs.roi.SpanROI(250,300)
range_selector_sig=range_selector.interactive(roi_spectre)
bkgd_inter=hs.interactive(roi_spectre.bkgd_fitting,
                          event=range_selector_sig.axes_manager.events.any_axis_changed,
                          recompute_out_event=None,
                          range_selector=range_selector)
````

This code should work to show what I'm talking about. I will check the #1544 project.

**Comment by francisco-dlp** [comment]
Thanks! It works well for me replacing:

```python

bkgd=-(no_bkgd)+self+np.min(self.data)

```

with 

```python

bkgd=-(no_bkgd)+self

```

(or is there anything that I'm not getting?)

**Comment by adriente** [comment]
Ok, it was very easy after all. It works well with the modification above.

The reason why I put
````python
+ np.min(self.data)
```` 
is because the windows displays the signal with the following limits : (min,max) of the signal. Which is a bit annoying when visualizing the substracted signal.

Using : 
````python
self._plot.signal_plot.ax.set_ylim(0.0,max(self.data))
````
Doesn't work well and I don't know why.

Another solution is to add : 
````python
no_bkgd+=min(self.data)
````

**Comment by francisco-dlp** [comment]
The issue with the y-limits is due to hspy's internal autoscale. You can disable it for the spectrum line and manage from your function. To disable autoscaling:

```python

self._plot.signal_plot.ax_lines[0].autoscale = False

```

**Comment by ericpre** [comment]
Done in https://github.com/hyperspy/hyperspy/pull/2003 and https://github.com/hyperspy/hyperspy/pull/2501.
