### ISSUE TITLE
Interactive operations docs typo

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1618]
In the [docs](http://hyperspy.org/hyperspy-doc/current/user_guide/tools.html#interactive-operations), the first example for interactive operations is missing `obj=s` as an argument to `s.events.data_changed.trigger()
`, as is included in the second example.

The docstring for `.trigger` isn't clear on whether there should be an argument, either.

**Comment by ericpre** [comment]
It seems that it has been fixed at some point.
