### ISSUE TITLE
Missing exception in rebin

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1623]
I'm adding it here in case it isn't covered by @k8macarthur's new method.
One can bin into a shape bigger than the signal without an exception being raised. It does not do anything to the data.

```python
>>> import hyperspy.api as hs
>>> import numpy as np
>>> ones = 100*np.ones((2,2))
>>> s = hs.signals.Signal1D(ones)
>>> s.data.shape
(2, 2)
>>> s2 = s.rebin((10,10)) # This shouldn't work!
>>> s2.data.shape
(2, 2)
```

**Comment by k8macarthur** [comment]
The new method asks for a scale rather than shape. So if you up scale (bin by less than 1) the fast rebin no longer works and my method is applied which splits the pixel accordingly. Feel free to test and double check! :)

**Comment by thomasaarholt** [comment]
I do not have numba installed, and got the following result:
```python
>>> import hyperspy.api as hs
>>> import numpy as np
>>> ones = 100*np.ones((5,5))
>>> s = hs.signals.Signal1D(ones)
>>> s2 = s.rebin((10,10))
WARNING:hyperspy.misc.array_tools:Install numba to speed up the computation of `rebin`
>>> s2.data.shape
(0, 0)
```
Shouldn't this raise an error, instead of a warning? Certainly, the warning is ~~incorrect~~ insufficient (thanks francisco).

**Comment by francisco-dlp** [comment]
Why is it incorrect?

**Comment by thomasaarholt** [comment]
Sorry, "insufficient" - at least if the intention (as @k8macarthur suggested to me), is that it should be possible to upscale the signal.

I am assuming that the reason it isn't working is that numba is not installed.

**Comment by francisco-dlp** [comment]
It should work exactly in the same way but slower when numba is not installed.

**Comment by thomasaarholt** [comment]
Well, in that case, something is wrong :)
Can others replicate the result?

**Comment by francisco-dlp** [comment]
Could you carry on the discussion (bug report/review) in #1306.

I'll label this as bug and you've indeed found a bug in the current code that #1306 fixes.
