### ISSUE TITLE
Difficulties in correctly reading data previously binned in Digital micrograph

### ISSUE THREAD

**Issue by mwalls** [hyperspy/hyperspy#1624]
DM (Version 2.32.888.0 at least) performs its binning in an unorthodox fashion. The values stored in the file appear sometimes to be the averages of the summed pixels rather than their sum. At the time of writing this applies to one installed copy of DM and not to a second one. The origin of the inconsistency is not known. The DM metadata records the binning, but how to determine whether or not to re-multiply the data in consequence is currently unknown. I suggest therefore that until we understand it better, we insert a warning whenever DM data is read explaining that binned data may lead to erroneous statistics.

**Comment by tjof2** [comment]
Anyone know if this is still true or applies to only a specific version?

In any case, there is already a warning in the docs on model fitting: https://hyperspy.readthedocs.io/en/latest/user_guide/model.html. Perhaps it could also be added to https://hyperspy.readthedocs.io/en/latest/user_guide/io.html#gatan-digital-micrograph

**Comment by ericpre** [comment]
Yes, maybe a link to https://hyperspy.readthedocs.io/en/latest/user_guide/model.html in https://hyperspy.readthedocs.io/en/latest/user_guide/io.html#gatan-digital-micrograph to avoid repetition?
