### ISSUE TITLE
Some plotting tests not passing

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#1641]
Currently some plotting tests are not passing in RELEASE_next_minor. However, they are passing for me locally. Any idea of what's going on @ericpre?

**Comment by francisco-dlp** [comment]
ok, I know what's wrong: I generated them using mpl 2.0.2 which is different enough to make the tests fail

**Comment by francisco-dlp** [comment]
Actually, 2.0.2  seems to fix a bug with the alignment of the axes tick labels

**Comment by ericpre** [comment]
The RMS value is small (for most of the image comparison failure), so it should not be a big issue.
Such a small difference may be also explain by a different version of freetype (which may depends on how matplotlib is installed...).

**Comment by francisco-dlp** [comment]
After fixing the version issue, now I am facing the freetype issue that you mention too.

**Comment by ericpre** [comment]
The matplotlib version from pypi should work across different platform/python distribution normally...

**Comment by ericpre** [comment]
I have the following errors on my computer (different from the issues mentioned above...). This is just one example, but it affects most of the plotting capabilities:

```python
________________________________ test_plot_line_markers _________________________________

mpl_cleanup = None

    @pytest.mark.mpl_image_compare(
        baseline_dir=baseline_dir, tolerance=default_tol, style=style_pytest_mpl)
    def test_plot_line_markers(mpl_cleanup):
>       im = _test_plot_line_markers()

test_plot_markers.py:458: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test_plot_markers.py:444: in _test_plot_line_markers
    im.add_marker(m0)
../../signal.py:4300: in add_marker
    self._plot.signal_plot.ax.hspy_fig._draw_animated()
../../drawing/figure.py:50: in _draw_animated
    [ax.draw_artist(a) for a in artists if
../../drawing/figure.py:51: in <listcomp>
    a.get_animated() is True]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <matplotlib.axes._subplots.AxesSubplot object at 0x7f02b04dbba8>
a = <matplotlib.image.AxesImage object at 0x7f028af0fd68>

    def draw_artist(self, a):
        """
            This method can only be used after an initial draw which
            caches the renderer.  It is used to efficiently update Axes
            data (axis ticks, labels, etc are not updated)
            """
        if self._cachedRenderer is None:
            msg = ('draw_artist can only be used after an initial draw which'
                   ' caches the render')
>           raise AttributeError(msg)
E           AttributeError: draw_artist can only be used after an initial draw which caches the render

/opt/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_base.py:2441: AttributeError
```

It looks like it comes from #1544 and it seems related to matplotlib blitting.

**Comment by francisco-dlp** [comment]
Which backend are you using? The agg backend should not attempt to use blitting.

**Comment by ericpre** [comment]
I am using qt4.

**Comment by francisco-dlp** [comment]
Can you reproduce the issue in "real life" usage?

**Comment by ericpre** [comment]
Yes, for example, spikes_removal_tool() is broken, but basic spectrum image plotting is working. Can anyone reproduce or this is something wrong with my install?

**Comment by francisco-dlp** [comment]
Yes, I can reproduce it :(

**Comment by francisco-dlp** [comment]
I think that I've fixed it, I'll PR in a second.

**Comment by francisco-dlp** [comment]
I couldn't fixed in general. Does it affect anything other than the spikes tool?

**Comment by francisco-dlp** [comment]
The spikes tools issue is now fixed in Rnm, thanks for spotting it!

**Comment by ericpre** [comment]
From running the plotting tests, I can spot:
- add_marker()
- update_plot() in some cases...

**Comment by francisco-dlp** [comment]
@ericpre, does #1646 fix the issue for your?

**Comment by ericpre** [comment]
Yes, it does fix the tests and so far it does not seem to brake anything!

**Comment by francisco-dlp** [comment]
Thanks!
