### ISSUE TITLE
`Polynomial` component parameters cannot be independently bounded

### ISSUE THREAD

**Issue by bm424** [hyperspy/hyperspy#1667]
In `Component`, parameters with multiple values (like polynomial coefficients) set the same lower bound for each one when `bmin` is set. Although this can be fixed by explicitly setting `_bounds` for the component, this isn't expected behaviour, I think. An example use-case is defining a line whose slope is known to be negative but whose y-intercept should be positive. Possible  syntax: `Polynomial.bmin = (-1, 1)`

**Comment by thomasaarholt** [comment]
Good call. In the meantime, users could also define their own polynomial using `Expression` with independently bounded coefficients, but that's of course not ideal.

**Comment by to266** [comment]
When someone attempts to fix this, I would rewrite the polynomial component to have as many `Parameter`s as there are actual parameters - and not have one tuple that is difficult to work with. The tuple is trivial to re-create when calling the `.function` method anyway.

**Comment by ericpre** [comment]
Fixed in #1989.
