### ISSUE TITLE
"ImportError" which prevents starting of traitsui

### ISSUE THREAD

**Issue by ananyjlo** [hyperspy/hyperspy#1676]
Hi,
I installed hyperspy using anaconda and downgraded qt to qt4 already.
But still I cannot start traitsui, using the following codes.
"%matplotlib nbagg
import hyperspy.api as hs
hs.preferences.gui(toolkit="traitsui")
import numpy as np
import matplotlib.pyplot as plt"

Best,
Shize

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-2e1a4da360a9> in <module>()
      3 #%matplotlib qt4
      4 import hyperspy.api as hs
----> 5 hs.preferences.gui(toolkit="traitsui")
      6 import numpy as np
      7 import matplotlib.pyplot as plt

C:\Anaconda3\lib\site-packages\hyperspy\ui_registry.py in pg(self, display, toolkit, **kwargs)
    172     def pg(self, display=True, toolkit=None, **kwargs):
    173         return get_gui(self, toolkey=toolkey, display=display,
--> 174                        toolkit=toolkit, **kwargs)
    175     return pg
    176 

C:\Anaconda3\lib\site-packages\hyperspy\ui_registry.py in get_gui(self, toolkey, display, toolkit, **kwargs)
     87     if not TOOLKIT_REGISTRY:
     88         raise ImportError(
---> 89             "No toolkit registered. Install hyperspy_gui_ipywidgets or "
     90             "hyperspy_gui_traitsui GUI elements. If hyperspy_gui_traits"
     91             "is installed, initialize a toolkit supported by traitsui "

ImportError: No toolkit registered. Install hyperspy_gui_ipywidgets or hyperspy_gui_traitsui GUI elements. If hyperspy_gui_traitsis installed, initialize a toolkit supported by traitsui before importing HyperSpy.

**Comment by francisco-dlp** [comment]
Have you installed ``hyperspy_gui_traitsui``?

```bash

conda install hyperspy-gui-traitsui -c conda-forge

```

**Comment by ananyjlo** [comment]
I have installed using the command. I also tried this command again. With the following output.

PS C:\Users\xxxxx> conda install hyperspy-gui-traitsui -c conda-forge
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment C:\Anaconda3:

The following packages will be SUPERSEDED by a higher-priority channel:

    conda:     4.3.22-py35_0 --> 4.3.22-py35_0 conda-forge
    conda-env: 2.6.0-0       --> 2.6.0-0       conda-forge

Proceed ([y]/n)? y

conda-env-2.6. 100% |###############################| Time: 0:00:00 686.97 kB/s
conda-4.3.22-p 100% |###############################| Time: 0:00:00   1.51 MB/s

**Comment by francisco-dlp** [comment]
I just noticed that the issue may be that you're using the nbagg backend, not the qt one. That's why the traitsui gui is not registered. Try:

```python

%matplotlib qt4
import hyperspy.api as hs
hs.preferences.gui(toolkit="traitsui")

```

**Comment by tomas1104** [comment]
Hi,
I have exactly the same problem as above. I am trying to run the tutorial "EELS_analysis" and I also get error message: "No toolkit registered. Install hyperspy_gui_ipywidgets or hyperspy_gui_traitsui GUI elements. If hyperspy_gui_traitsis installed, initialize a toolkit supported by traitsui before importing HyperSpy"
I tried:
- use %matplotlib nbagg
- use %matplotlib qt 
- use %matplotlib qt4
- pip install hyperspy_gui_traitsui (afterwards remove from pip)
- conda install hyperspy-gui-traitsui -c conda-forge

I checked and the hyperspy-gui-traitsui     1.1.1 is in my conda list.
I also doublechecked to verify that I installed it to the correct python environment, in which jupyter notebook is running.
But I am still getting the same error. Any advice?

**Comment by magnunor** [comment]
@tomas1104, when did you install HyperSpy?

Could you try,

```python
%matplotlib qt5
import hyperspy.api as hs
```

and see what you get? In that case you might get a warning about `hyperspy_gui_ipywidgets` instead.

**Comment by tomas1104** [comment]
Hi,
the hyperspy package is installed most probably at the beginning of december 2018 (4.12.2018). I tried using the above mentioned code but without success: "Warning: Cannot change to a different GUI toolkit: qt5. Using nbagg instead."
What worked for me in the end is when I used the hyperspy bundle. But I would still like to know how to have it done without the bundle. 
Btw when using bundle I get the same error (No toolkit, ....), however I am able to do the background subtraction without problems.

**Comment by ericpre** [comment]
Can you please copy the output of `conda list` to check that the library are correctly installed?

> I tried using the above mentioned code but without success: 
 `Warning: Cannot change to a different GUI toolkit: qt5. Using nbagg instead.`

If you already imported matplotlib previously, you will get this warning. To make sure this is not the case, open a new notebook and execute:
```
%matplotlib qt
import hyperspy.api as hs
```

You have two different warnings here, to avoid any confusion, could you make an short example which reproduce your issue?

**Comment by tomas1104** [comment]
I upload both the conda list and pip list. At the moment the hyperspy traitsui is installed by pip, but previously i did it using conda without success as well.  I also attach a short example with commands:
- %matplotlib qt
- import hyperspy.api as hs
- hs.preferences.gui(toolkit="traitsui")

and the following errors.

[conda_list.txt](https://github.com/hyperspy/hyperspy/files/3018596/conda_list.txt)
[example.txt](https://github.com/hyperspy/hyperspy/files/3018597/example.txt)
[pip_list.txt](https://github.com/hyperspy/hyperspy/files/3018598/pip_list.txt)

**Comment by ericpre** [comment]
According to your conda list, your environment is python27 and hyperspy is not installed in this environment. The hyperspy version you are using is from a different environment (named "py36").
To avoid mixing up environment, I would suggest that you create a new environment and install hyperspy using conda.

```
conda create -n hs python
activate hs
conda install -c conda-forge hyperspy
```
The recommand way to install hyperpsy on windows is by using the hyperspy bundle; using conda works fine too but it is easy to break. Typically, mixing pip and conda packages can make problem, so I would avoid doing that, expect if you are sure this is fine.

**Comment by ericpre** [comment]
Reopen if this is still not working.
