### ISSUE TITLE
Line2DROI can't be interactive if the Signal navigation scales have decimal values

### ISSUE THREAD

**Issue by kociak** [hyperspy/hyperspy#1682]
The line2DROI can't be interactively linked if the signal to which they are attached have decimal scales. Below are two examples, plus an example of working situation:

working situation:

```
%matplotlib qt5
#use qt4 if it does not work with qt5
import hyperspy.api as hs
import numpy as np
SI=hs.signals.Signal1D(np.random.random((300,300,400)))

SI.axes_manager[0].scale=1
SI.axes_manager[1].scale=1
SI.axes_manager[2].scale=1

line1 = hs.roi.Line2DROI(10, 10, 60, 60,1)
line_ROI = line1.interactive(SI,color='red')
line_ROI.plot()
```
first type of error-generating script:

```
%matplotlib qt5
#use qt4 if it does not work with qt5
import hyperspy.api as hs
import numpy as np
SI=hs.signals.Signal1D(np.random.random((300,300,400)))

SI.axes_manager[0].scale=1.2
SI.axes_manager[1].scale=1.2
SI.axes_manager[2].scale=1

line1 = hs.roi.Line2DROI(10, 10, 60, 60,1)
line_ROI = line1.interactive(SI,color='red')
#the error does not arise if one modify the line1 widget  size interactively
line_ROI.plot()
```

generates the following error:
```
/anaconda/lib/python3.6/site-packages/hyperspy/roi.py:1113: RuntimeWarning: Mean of empty slice.
  intensities = pixels.mean(axis=1)
/anaconda/lib/python3.6/site-packages/numpy/core/_methods.py:73: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)
```
and a blank `line_ROI`

second type of error-generating script:

```
%matplotlib qt5
#use qt4 if it does not work with qt5
import hyperspy.api as hs
import numpy as np
SI=hs.signals.Signal1D(np.random.random((300,300,400)))

SI.axes_manager[0].scale=0.01
SI.axes_manager[1].scale=0.01
SI.axes_manager[2].scale=1

line1 = hs.roi.Line2DROI(10, 10, 60, 60,1)
line_ROI = line1.interactive(SI,color='red')
#the error does not arise if one modify the line1 widget  size interactively
line_ROI.plot()
```
generates the following error

```
/anaconda/lib/python3.6/site-packages/hyperspy/drawing/_widgets/line2d.py:148: RuntimeWarning: invalid value encountered in true_divide
  return n / np.linalg.norm(n)            # Normalized
```

**Comment by francisco-dlp** [comment]
Good catch @kociak, I'll have a go at fixing this tomorrow.

**Comment by francisco-dlp** [comment]
@kociak, I've just PRed a fix, would you like to test it? #1685

**Comment by kociak** [comment]
with pleasure; but shamelessly I don't know how to get your modification... Is there a command line I can type? sorry for that!

**Comment by francisco-dlp** [comment]
```bash

pip install https://github.com/francisco-dlp/hyperspy/archive/FIX_lineprofile_float.zip

```

**Comment by kociak** [comment]
thanks @francisco-dlp 
I am assuming that the pip install installed and replaced the hs version 1.3 I had with the dev version.
When running the code:

```
%matplotlib qt5
#use qt4 if it does not work with qt5
import hyperspy.api as hs
import numpy as np
SI=hs.signals.Signal1D(np.random.random((300,300,400)))
SI.axes_manager[0].scale=1
SI.axes_manager[1].scale=1
SI.axes_manager[2].scale=1
SI.plot()
line1 = hs.roi.Line2DROI(10, 10, 60, 60,1)
line_ROI = line1.interactive(SI,color='red')
```
I got the following error:

```
NameError                                 Traceback (most recent call last)
<ipython-input-7-2f5512afade5> in <module>()
----> 1 line_ROI = line1.interactive(SI,color='red')

/anaconda/lib/python3.6/site-packages/hyperspy/roi.py in interactive(self, signal, navigation_signal, out, color, **kwargs)
    370                                event=self.events.changed,
    371                                signal=signal,
--> 372                                **kwargs)
    373         else:
    374             return interactive(self.__call__,

/anaconda/lib/python3.6/site-packages/hyperspy/interactive.py in interactive(f, event, recompute_out_event, *args, **kwargs)
    125 
    126 def interactive(f, event="auto", recompute_out_event="auto", *args, **kwargs):
--> 127     cls = Interactive(f, event, recompute_out_event, *args, **kwargs)
    128     return cls.out
    129 

/anaconda/lib/python3.6/site-packages/hyperspy/interactive.py in __init__(self, f, event, recompute_out_event, *args, **kwargs)
     79             self.out = self.kwargs.pop('out')
     80         else:
---> 81             self.out = self.f(*self.args, **self.kwargs)
     82         try:
     83             fargs = list(inspect.signature(self.f).parameters.keys())

/anaconda/lib/python3.6/site-packages/hyperspy/roi.py in __call__(self, signal, out, axes, order)
   1168                                          (self.x2, self.y2),
   1169                                          axes=axes,
-> 1170                                          linewidth=linewidth,
   1171                                          order=order)
   1172         length = np.linalg.norm(np.diff(

NameError: name 'linewidth' is not defined
```
note that if I am changing the 0 or 1 direction (navigation) `scale`property, I got the same error if the scale is larger than 1 and decimal, but also the following  warning (orange frame in jupyter) if the scale is say 0.01:

```
/anaconda/lib/python3.6/site-packages/hyperspy/drawing/_widgets/line2d.py:180: RuntimeWarning: invalid value encountered in true_divide
  return n / np.linalg.norm(n)    
```
thanks for the help

**Comment by francisco-dlp** [comment]
Sorry for that, I made some final changes yesterday and I thought that I had tested it before PRing it, but I probably forgot to restart the kernel. Now it should work. To update the code just run the pip command again.

Regarding the RuntimeWarning in your second example, the reason seems to be that the coordinates of the line profile are out of the axes bounds.

Does it work now for you?

**Comment by kociak** [comment]
sorry, just got back some decent connection. No, unfortunately the message is the same (the one about the linewidth)...

**Comment by francisco-dlp** [comment]
Are you sure that you've updated the code and restarted the kernel? Your example works for me now.

**Comment by kociak** [comment]
Yes; but actually I think I know the issue: conda list tells me that both hs 1.3 and hs 1.3 dev are installed. Probably i am not calling the right hs version: is there a way to force `import hyperspy.api as hs` to point to a given version?

**Comment by francisco-dlp** [comment]
If you check the version as follows it should be '1.3.1.dev'

```python

import hyperspy
hyperspy.__version__

```

If it is not, I would try uninstalling hyperspy and installing the dev version again.

Actually, the most convenient way of testing dev features is installing hyperspy from a local git repository using pip in dev mode. I am about to leave the office so I can't write about this now but some googling + gitter chatting if you get stuck should get you there.

**Comment by kociak** [comment]
unfortunately it tells me it is 1.3.1.dev. hum... let's have a sleep on it and we'll see I am not doing something weird!

**Comment by kociak** [comment]
Your fix fixed the issue, thanks!

Now, to why I didn't see it yesterday:
OK, here was a vicious thing. having uploaded the dev version while the regular one was already in place, i got 
```import hyperspy
hyperspy.__version__
```
giving me 1.3.1dev, but obviously my subsequent calls to `hyperspy.api` where NOT refering to the dev version. I have thus remove both (1.3.1 and 1.3.1dev), then reinstall the dev version through your link, and now everything is right!
No idea why it is so...

**Comment by francisco-dlp** [comment]
Thanks @kociak, I'll leave it open until #1685 gets merged.

**Comment by ericpre** [comment]
#1685 is merged.
