### ISSUE TITLE
.ser image series loads incorrectly

### ISSUE THREAD

**Issue by hentr** [hyperspy/hyperspy#1684]
I'm trying to work with STEM image series recorded as .ser files. The following code works for the same data if the .ser is converted to .dm3 or .tif (through DigitalMicrograph and ImageJ), but not the original .ser.

```
expt_movie = hs.load(filename)
movie_tif = expt_movie
movie_tif.change_dtype('uint16')
movie_tif.save(name+'.tif')
```
The first frame of the new saved file is correct, but the following frames get shifted with a black bar added.

![gif of original](https://github.com/hentr/testing/blob/master/testseries3_0000_1dm3(1-20).gif)
![gif of .ser mess](https://github.com/hentr/testing/blob/master/testseries3_0000_1ser(1-20).gif)

This problem appears with all the .ser image series I have tested so far.

**Comment by francisco-dlp** [comment]
Could you share with us a ser files that suffers from this issue?

**Comment by hentr** [comment]
[heres](https://polybox.ethz.ch/index.php/s/mqo7lTkPAgS6lMT) the original the gifs are from

**Comment by ericpre** [comment]
I started quickly check this and I could not spot obvious error in the code. We have a very similar file in the test suite which does not have this issue, so this is a bit surprising. Before moving forward, could you please confirm that you have the issue with other files, not only this one? If so, I can look at it in more details.

**Comment by hentr** [comment]
I have the problem with all the .ser image series I have tried so far. The shift/black bar also appears to be identical in all files. Recorded with TIA (I think latest version) on a Titan, Windows 7, if that is relevant.

**Comment by francisco-dlp** [comment]
I think that the issue is that hyperspy assumes that the images are stored one after the other in the file. This is true for most files but it seems that in fast image acquisition mode the software writes some useless (?) data in between the images. More explicitly, the ser file header contains the offset of *all* the images in the file, but hyperspy just takes the offset of the first image and assumes that the next image starts where the previous one ends, which in this case is not true.

**Comment by hentr** [comment]
might be helpful to have a look at the [script for reading .ser files into DM](https://polybox.ethz.ch/index.php/s/SIsznBZeHunf7Vd), that read these files correctly.

**Comment by ericpre** [comment]
@francisco-dlp, the good news is your suggestion is correct and it fixes the issue!
The bad news is that I unintentionally push directly to RELEASE_next_patch... :/ Obviously, when I was looking for the branch in my remote repository to open a PR, I understood quickly what happen!! My local branch was tracking hyperspy/RELEASE_next_patch (after checking out from there) and it obviously also pushes there. I used to do that without having writing right and it was _magically_ creating a new branch in my remote repo!
This is possibly not a good practise and there is only simple commit, is it worth reverting it?

I promise, I will be more careful when pushing!!! ;)

**Comment by hentr** [comment]
@ericpre, just tested the updated fei.py and it works great for me, thanks a lot!

**Comment by hentr** [comment]
Recently updated to a new version of TIA on the microscope here, and this problem appear to have returned for all the STEM series I have recorded since. Same if I read from the .emi or .ser.

[sample .emi](https://polybox.ethz.ch/index.php/s/MNKRc1Xo9SAflpz)
[sample .ser](https://polybox.ethz.ch/index.php/s/SQ7unz0zdNGeVjX)

**Comment by francisco-dlp** [comment]
Thanks for reporting the issue and providing the files.

**Comment by ericpre** [comment]
@hentr, downloading the emi file doesn't work, the .ser file is fine, though.

**Comment by hentr** [comment]
ah, as you pointed out in #1766 I was just using the outdated fei.py from a freshly installed hyperspy. The fix still works as it should :)
