### ISSUE TITLE
s.save('filename.tif', overwrite=False) doesn't save file when there is no filename.tif

### ISSUE THREAD

**Issue by hentr** [hyperspy/hyperspy#1687]
`overwrite=True` works as it should and always writes the file, but `overwrite=False` seems to never write a file, whether there is an existing file or not. Have tested with both loading and saving .tif, .ser and .hspy.

**Comment by ericpre** [comment]
PRs are more than welcome, it should not be too difficult to fix this one. If you want to give a go, please have a look at the [dev guide](http://hyperspy.org/hyperspy-doc/current/dev_guide.html).

**Comment by hentr** [comment]
#1689 fixes it at least for me

**Comment by to266** [comment]
It's not yet resolved, since the PR is not yet merged :)

**Comment by francisco-dlp** [comment]
Fixed in #1689
