### ISSUE TITLE
RectangularROI widgets does not initialize properly on Signal1D that have non-squared navigation sizes

### ISSUE THREAD

**Issue by kociak** [hyperspy/hyperspy#1690]
We came accross a vicious and erratic bug with rectangularROI widgets. It seems that for certain Signals1D that are non-squared in their navigation dimensions, the associated widget in an ìnteractive`chain does not initialize properly. See the code and comments below, followed by the traceback. I had difficulties in reproducing the bug from scratch (but unfortunately it happens form time to time on real data) so I couldn't generate a 100% sure example (I don't know if the error is also linked to the signal size, for example). thanks again for looking at it!

```
%matplotlib qt5

import hyperspy.api as hs
import numpy as np
import matplotlib.pyplot as plt


Spim=hs.signals.Signal1D(np.random.random((51,34,160)))

Spim.plot()

rectangle_ROI=hs.roi.RectangularROI(left=1.2001, right=10, top=0, bottom=10)
rroi = rectangle_ROI.interactive(Spim)
```

produces:

a ROI widget on the navigation image (ROI widget size is 1*1 pixel) but the name 'rroi' is not defined in the notebook namespace

 this also generates the following traceback:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-8159865ed2f6> in <module>()
      1 rectangle_ROI=hs.roi.RectangularROI(left=1.2001, right=10, top=0, bottom=10)
----> 2 rroi = rectangle_ROI.interactive(Spim)
      3 

/anaconda/lib/python3.6/site-packages/hyperspy/roi.py in interactive(self, signal, navigation_signal, out, color, **kwargs)
    360             if navigation_signal not in self.signal_map:
    361                 self.add_widget(navigation_signal, color=color,
--> 362                                 axes=kwargs.get("axes", None))
    363         if (self.update not in
    364                 signal.axes_manager.events.any_axis_changed.connected):

/anaconda/lib/python3.6/site-packages/hyperspy/roi.py in add_widget(self, signal, axes, widget, color)
    443 
    444             ax = _get_mpl_ax(signal._plot, axes)
--> 445             widget.set_mpl_ax(ax)
    446         with widget.events.changed.suppress_callback(self._on_widget_change):
    447             self._apply_roi2widget(widget)

/anaconda/lib/python3.6/site-packages/hyperspy/drawing/widget.py in set_mpl_ax(self, ax)
    166             self.connect(ax)
    167             canvas.draw_idle()
--> 168             self.select()
    169 
    170     def select(self):

/anaconda/lib/python3.6/site-packages/hyperspy/drawing/widget.py in select(self)
    180         x, y = self.patch[0].get_transform().transform_point((0, 0))
    181         mouseevent = MouseEvent('pick_event', canvas, x, y)
--> 182         canvas.pick_event(mouseevent, self.patch[0])
    183         self.picked = False
    184 

/anaconda/lib/python3.6/site-packages/matplotlib/backend_bases.py in pick_event(self, mouseevent, artist, **kwargs)
   1881                           guiEvent=mouseevent.guiEvent,
   1882                           **kwargs)
-> 1883         self.callbacks.process(s, event)
   1884 
   1885     def scroll_event(self, x, y, step, guiEvent=None):

/anaconda/lib/python3.6/site-packages/matplotlib/cbook.py in process(self, s, *args, **kwargs)
    552             for cid, proxy in list(six.iteritems(self.callbacks[s])):
    553                 try:
--> 554                     proxy(*args, **kwargs)
    555                 except ReferenceError:
    556                     self._remove_proxy(proxy)

/anaconda/lib/python3.6/site-packages/matplotlib/cbook.py in __call__(self, *args, **kwargs)
    414             mtd = self.func
    415         # invoke the callable and return the result
--> 416         return mtd(*args, **kwargs)
    417 
    418     def __eq__(self, other):

/anaconda/lib/python3.6/site-packages/hyperspy/drawing/widget.py in onpick(self, event)
    671     def onpick(self, event):
    672         if hasattr(super(ResizableDraggableWidgetBase, self), 'onpick'):
--> 673             super(ResizableDraggableWidgetBase, self).onpick(event)
    674         if self.picked:
    675             self._drag_store = (self.position, self.size)

/anaconda/lib/python3.6/site-packages/hyperspy/drawing/widget.py in onpick(self, event)
    436         self._selected_artist = event.artist
    437         if hasattr(super(DraggableWidgetBase, self), 'onpick'):
--> 438             super(DraggableWidgetBase, self).onpick(event)
    439         self.selected = self.picked
    440 

/anaconda/lib/python3.6/site-packages/hyperspy/drawing/widget.py in onpick(self, event)
    954             x = event.mouseevent.xdata
    955             y = event.mouseevent.ydata
--> 956             self.pick_offset = (x - self._pos[0], y - self._pos[1])
    957             self.resizer_picked = False
    958         else:

TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

**Comment by francisco-dlp** [comment]
The ``rroi`` variable is not defined because the line where it is defined has failed.

I have tried to reproduce the issue with your code and a slight modification of it to test 1 pixel size ROI in axes with fraction scales and I couldn't reproduce it:

```python

%matplotlib qt5

import hyperspy.api as hs
import numpy as np
import matplotlib.pyplot as plt


Spim=hs.signals.Signal1D(np.random.random((51,34,160)))
Spim.axes_manager[0].scale = 0.33
Spim.axes_manager[1].scale = 0.66


Spim.plot()

rectangle_ROI=hs.roi.RectangularROI(left=1, right=1.33, top=0, bottom=0.66)
rroi = rectangle_ROI.interactive(Spim)

```

One known issue that may be behind the one that you're experiencing is that the ROIs don't work with negative scales (which is obviously a bug).

**Comment by kociak** [comment]
Thanks Fran. Unfortunately (working on hyperspy 1.3.1dev) I have exactly the same error as before when running your code. I will ask someone else to try to generate the error (someone with a PC maybe? I can't see the difference on such a simple example!)

**Comment by ericpre** [comment]
I can not reproduce neither.

**Comment by kociak** [comment]
I also asked colleague but they can't reproduce it either. I am working extensively with ROIs those days, hopefully I' ll can seek and destroy the bug sooner or later ;)

**Comment by ericpre** [comment]
There was a couples of fixes for plotting and ROIs in the last two year and it seems to work fine now. Please reopen if the issue still occurs.
