### ISSUE TITLE
Events: Cannot clear connected functions

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1697]
I cannot find any way of removing a connected function from events. The [docs](http://hyperspy.org/hyperspy-doc/dev/user_guide/events.html) also don't specify how to do this.

The tested event in question is `s.axes_manager.events.any_axis_changed`.

I connected a function, only to realise I had forgotten to include the `obj` argument. I corrected the argument, then connected it again, only to realise that by connecting the function twice, it was still trying to call the errorenous function.

I've attempted to disconnect the events by calling `s.axes_manager.events.any_axis_changed.connected.clear()`, as well as looping through the connected and removing then by `s.axes_manager.events.any_axis_changed.connected.remove(func)`.

Am I missing something here?

**Comment by francisco-dlp** [comment]
This is a doc issue. To disconnect the function you can use the ``disconnect`` method.

**Comment by thomasaarholt** [comment]
But how would I disconnect a function after having overwritten it? 
This is the only thing I can think of: 
```python 
for ev in s.axes_manager.events.any_axis_changed.connected:
    s.axes_manager.events.any_axis_changed.disconnect(ev)
```

**Comment by francisco-dlp** [comment]
You can't overwrite it, if you connect again the same function you get a ValueError.

**Comment by francisco-dlp** [comment]
Note that if you have created a new function with the same name as the original, both functions will be connected as they're two different Python objects.

**Comment by thomasaarholt** [comment]
That's exactly my point - how could I go about disconnecting the first of the connected functions (where both functions have the same name)?

**Comment by francisco-dlp** [comment]
If you've lost it in the namespace, the only way is to get it from ``connected`` as you've done above.

**Comment by thomasaarholt** [comment]
Oki, good to know. It would perhaps be nice to have a `disconnect_all()` method or something, although I guess it is rare that it would be needed.

**Comment by francisco-dlp** [comment]
That would be a dangerous method...

**Comment by thomasaarholt** [comment]
Ok. Let's close this for now then, reopen if it becomes an issue later.
