### ISSUE TITLE
Implement io plugin for MRCZ format

### ISSUE THREAD

**Issue by ericpre** [hyperspy/hyperspy#1703]
It could be good to add support for the MRCZ format. It should be fairly easy since there is already a python library. Below are a few relevance links:
- https://github.com/em-MRCZ
- https://github.com/em-MRCZ/python-mrcz
- http://www.biorxiv.org/content/early/2017/03/13/116533

To build the Winpython-based HyperSpy build, it may be necessary to use the [blosc library](http://www.lfd.uci.edu/~gohlke/pythonlibs/#blosc) build by Gohlke (in the same way that we upgrade scikit-image in Winpython).

**Comment by robbmcleod** [comment]
Hi gentlemen,

I'm the primary author of MRCZ. I'd be happy to prepare a pull request if you could give me a few lines of introduction on where I should start and what the final interface should look like.

**Comment by ericpre** [comment]
This sounds great! :)

There is a [developer guide](http://hyperspy.org/hyperspy-doc/current/dev_guide.html), which may be worth having a look at it. Please feel free to PR/comments on the developer guide if there is something not clear enough or anything else.

Regarding writing a io plugins, the easiest it to look at a simple io reader to get the idea. For example, you can look at these PRs: [this one](https://github.com/hyperspy/hyperspy/pull/766/files) and [this one](https://github.com/hyperspy/hyperspy/pull/1173/files).

- the code goes in a new module of the io folder;
- add the name of the new module in `hyperspy/io_plugins/__init__.py` so the plugin is recognised in HyperSpy.
- create the `file_reader` and `file_writer` functions in the newly created module. The `file_reader` should simply return a list of dictionaries (one dictionary for each signal to import) with the right contents.
- we use `original_metadata`, `metadata` and a `mapping` function between the two, which generates the signal metadata from the `original_metadata`. The idea is to put all information that you can import into `original_metadata` and to parse the one used in HyperSpy into `metadata` using the `mapping` function, following this [structure](http://hyperspy.org/hyperspy-doc/current/user_guide/metadata_structure.html).

By the end of this PR, we should have a nice paragraph on writing io plugin in the dev guide!

**Comment by robbmcleod** [comment]
I made an initial implementation, not tested yet (https://github.com/robbmcleod/hyperspy/commit/8d785eb2d4ee4f54e650dfbd5e585df063ddd94b). I few more questions before I do a `unittest` commit:

I could probably ask Francesc for permission to upload Windows wheels of blosc to PyPI. I'd be willing to do that for Python 3.5 and 3.6. It's very easy if you have MSVC2015 installed.

How is 3D data supported?

What is this stuff (in `blockfile.py`)?

    # Writing capabilities:
    writes = [(2, 2), (2, 1), (2, 0)]  # TODO
    magics = [0x0102] # TODO

Is any of your meta-data `ndarray` objects?  I use JSON for metadata serialization, but most Python JSON interpreters don't handle `ndarray`s nicely.  I think `ujson` is  the only one that does, but I mostly use `python-rapidjson`.

I have metadata fields for C3 and detector gain but I don't see an existing to map them. Would it also makes sense to map in the compressor library, which is practically  `(None, 'lz4', 'zstd')` and the compression level (`int`) into meta-data, or keep as kwargs?

I also have asynchronous writes and reads implemented (with `concurrent.futures`), how would the interface for that be best implemented?  

1. Pass a kwarg 'do_async' to `file_writer`?
2. Create `async_file_writer` and `async_file_reader`?  

It looks like your `lazy` loading is `np.memmap`?  I  implemented this but I found `memmap` to be very buggy so I've not really used it myself. If it's commonly used I should take another look at it and add it to `unittest`.  Note that I won't implement memory mapping for compressed files until the `c-blosc2` API is finalized, so perhaps it's not worthwhile to support...

Here's the docstrings on using it in asychronous mode.  

    setAsyncWorkers( N_workers )

    Sets the maximum number of background workers that can be used for reading 
    or writing with the functions.  Defaults to 1. Generally when writing 
    to hard drives use 1 worker.  For SSDs and parallel file systems (PFS) 
    network drives more workers can accelerate file IO rates.
    
    Some test results, 30 files, each 10 x 2048 x 2048 x float-32, on a CPU
    with 4 physical cores:

        HD, 1 worker:   42.0 s
        HD, 2 workers:  50.0 s
        HD, 4 workers:  50.4 s
        SSD, 1 worker:  12.6 s
        SSD, 2 workers: 11.6 s
        SSD, 4 workers: 8.9 s
        SSD, 8 workers: 16.9 s

    We observed that caches halted for periods ~5-10 s when too many workers 
    were used.

    asyncWriteMRC( *args, **kwargs )
    @author: Robert A. McLeod

    Calls writeMRC in a seperate thread and executes it in the background. Returns the thread 
    object, so if necessary you can call `Future.result()` to wait for the write to finish, 
    or check with `Future.done()`.abs

        worker = asyncWriteMRC( npImageData, 'my_mrcfile.mrc' )
        # Do some work
        if not worker.done():
            time.sleep(0.001)
        # File is written to disk

    Most of the time you can ignore the return and let the system finish writing 
    when it finishes.  
 
    Valid arguments are as for writeMRC().

    asyncReadMRC( *args, **kwargs )
    @author: Robert A. McLeod

    Returns a `Future` object, call the method `result()` to get the image 
    and metadata.

    E.g. 
    worker = asyncReadMRC( 'someones_file.mrc' )
    # Do some work
    mrcImage, mrcMeta = worker.result()

    Valid arguments are as for readMRC().

**Comment by ericpre** [comment]
> I could probably ask Francesc for permission to upload Windows wheels of blosc to PyPI. I'd be willing to do that for Python 3.5 and 3.6. It's very easy if you have MSVC2015 installed.

Regarding unit testing: we use pytest and for continuous integration, we test in a anaconda distribution on travis (linux and osx) and appveyor. There are different version of blosc for different platform, we just need to make sure that the correct version is installed.
The Winpython-based HyperSpy windows build is tested just before a release and it will make easier to have a windows binaries for blosc in pypi.

> How is 3D data supported?

What kind of 3D dataset? For example, for a stack of images (one navigation axis, two signal axes):
```python
>>> s = hs.signals.Signal2D(np.arange(20 * 40 * 60).reshape(20, 40, 60))
<Signal2D, title: , dimensions: (20|60, 40)>
```

> writes = [(2, 2), (2, 1), (2, 0)]  # TODO

These are the combination of supported signal and navigation dimensions (signal_dim, navigation_dim). See [this line](https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/hyperspy/io.py#L470). Ignore the `magics = [0x0102] # TODO` line, this is internal to the blockfile plugin.

Metadata:
Technically, you should be able to add any python object to the metadata tree, so an array should be no problem. However, the metadata are defined with a specific python type so that there are consistent across different kind of data set and can be use by HyperSpy without any problem.
This will need to be check, but the gain could be possibly stored in `Signal.Noise_properties.Variance_linear_model` of the metadata tree?
C3: this has been discussion a couple of times (but still haven't happen yet), it would be good to have an "optics" node in the metadata tree. I have open #1713.

For lazy data, better to discuss with @to266! ;)

**Comment by robbmcleod** [comment]
Pull request is https://github.com/hyperspy/hyperspy/pull/1716

**Comment by thomasaarholt** [comment]
Are we still missing having mrcz accessible through conda install? For release?

**Comment by ericpre** [comment]
Done in #1716.
