### ISSUE TITLE
Numpy Update Breaks MRC Reader Plugin

### ISSUE THREAD

**Issue by AndrewHerzing** [hyperspy/hyperspy#1705]
Changes to Numpy appear to be causing a TypeError to be thrown when using the MRC Reader plugin.  The error is: TypeError: only integer scalar arrays can be converted to a scalar index

This occurred somewhere between v1.11.3 and v1.13.1.  To fix this, a user can downgrade to NumPy 1.11.3.

The problem arises whenever the code tries to reference the variables NX , NY , NZ , MODE, and NEXT, because each of these is stored as a NumPy array in the std_header dictionary.  Simply adding a '[0]' after each makes the code work again.

**Comment by francisco-dlp** [comment]
Thanks for reporting the issue!

**Comment by ericpre** [comment]
@AndrewHerzing, please feel free to submit a PR! :)
