### ISSUE TITLE
Newbie to Hyperspy looking for some help

### ISSUE THREAD

**Issue by Sputn1k7** [hyperspy/hyperspy#1707]
Hi all,
     I am a TEM user who is looking to have an open source way of analyzing Bruker .bcf files (both v1 and v2). So far, Hyperspy seems like the place to go.

I have been able to successfully get Hyperspy 1.3 working on my Python 3.6 install. This is my opening code in a Jupyter notebook. The Gui test is to make sure traitsui is working.

%matplotlib qt5
import hyperspy.api as hs
hs.preferences.gui(toolkit='traitsui')
import numpy as np
import matplotlib.pyplot as plt

My real question is more about data visualization. I have TEM EDS data in a .bcf file, which I load like this:
s=hs.load(select_type='spectrum')
s.plot(True)

However, the plot that comes up does not have a summed EDS signal from the entire image, like the documentation says it should. In fact, the only way I can get the summed EDS signal is by turning the spectrum data into a Signal2D class. However, when it's a Signal2D class, I can't get plot(True) to show any elements in the map (even though they exist in the metadata).

I have attached the .bcf file in question, and I'm hoping I'm just doing something stupid (I am new to both Python and Hyperspy).

I had to zip the file, but the .bcf file is in there.

I would also be happy to provide more screenshots of my Jupyter notebook, if necessary.

Thanks.

[metrocal.zip](https://github.com/hyperspy/hyperspy/files/1225519/metrocal.zip)

**Comment by francisco-dlp** [comment]
As you've noticed, HyperSpy only displays the sum spectrum of a spectrum image when viewing it as a image stack as, in this case, the sum spectrum serves as "navigator". If you want to display the sum spectrum when viewing it as a spectrum image (which is usually the most convenient way to interact with these datasets) you could try:

```python

s.sum().plot()

```

You may also find the ``downsample`` argument useful:

```python

s = hs.load("metrocal.bcf", downsample=16)[1]

```

**Comment by Sputn1k7** [comment]
Thank you for the quick reply, @francisco-dlp !

I have another question. Is it possible to display the summed spectrum and the hypermap image together? s.plot() would give me both the image and a "EDX signal" navigator window, but obviously the EDX signal was not summed over the image.

I also have noticed the downsample argument, I will use that as necessary.

**Comment by francisco-dlp** [comment]
``s.plot()`` plots is designed to navigate the spectrum image. If you don't need to navigate it, only to display the sum spectrum and the sum image you can achieve it like this:

```python
s.sum().plot()
s.sum(axis=-1).plot()
```

If you would like to navigate a denoised dataset, you could try:


```python

s.decomposition()
s.plot_explained_variance_ratio() # Estimate number of principal components
sc = s.get_decomposition_model(<number of components from previous step>)
sc.plot()

```

**Comment by Sputn1k7** [comment]
Looks like i need to turn the data into float first?

![image](https://user-images.githubusercontent.com/31019888/29325870-2cde5de8-819e-11e7-84e7-eb21a480b53d.png)

**Comment by francisco-dlp** [comment]
Yes, you can do it like this:

```python

s.change_dtype("float32")

```

**Comment by Sputn1k7** [comment]
thank you for the quick tutorial! I will close this.
