### ISSUE TITLE
Cascading merges from RELEASE_next_patch --> ..._minor --> ..._major

### ISSUE THREAD

**Issue by jan-car** [hyperspy/hyperspy#1711]
As a quality of life improvement, it would be nice to have commits in the `RELEASE_next_patch` automatically merged into `RELEASE_next_minor` (the same goes for the commits in `RELEASE_next_minor` being automatically merged into `RELEASE_next_major`).

This way, all bugfixes and additional features are always present in the branches of higher order, without the need to manually merge for every small patch.

Webhooks seem to be a valid strategy of achieving this (see: https://developer.github.com/v3/repos/hooks/).
This blogpost may also help:
https://www.atlassian.com/blog/git/git-automatic-merges-with-server-side-hooks-for-the-win

**Comment by jan-car** [comment]
Apparently, BitBucket supports this feature (see [here](https://confluence.atlassian.com/bitbucketserver/automatic-branch-merging-776639993.html)), sadly I did not find an easy way to do this on GitHub. The webhooks I mentioned above seem to require another server(?), but I have to admit that I'm not proficient enough in these regards to find out how to proceed from here...

**Comment by tjof2** [comment]
It looks like this may now be possible with GitHub actions https://github.com/marketplace?type=actions&query=Merge

**Comment by tjof2** [comment]
For example, there's a nightly merge option. https://github.com/marketplace/actions/nightly-merge

**Comment by tjof2** [comment]
@ericpre any thoughts on using a GitHub action to achieve this? Otherwise this can probably be closed if there's no real appetite for it.

**Comment by ericpre** [comment]
Indeed, if there is a github action for this, it may be very easy to setup!

**Comment by tjof2** [comment]
@ericpre  looks like https://github.com/marketplace/actions/sync-branches might be a better bet but that only creates a PR. Will keep looking

**Comment by tjof2** [comment]
Options:

1. https://github.com/marketplace/actions/nightly-merge, runs on a Cron schedule, disadvantage is it won't run automatically when a PR is merged.
2. https://github.com/marketplace/actions/sync-branches, only creates a PR that won't automatically merge
3. https://github.com/marketplace/actions/action-automerge doesn't look well-used but may do the job
4. https://github.com/marketplace/actions/branch-merge might be a good one.
5. https://github.com/marketplace/actions/merge-branch also looks good.

**Comment by tjof2** [comment]
Don't know enough about setting up /using GitHub actions etc. to be able to offer any more input than the above list

Cc. @francisco-dlp

**Comment by ericpre** [comment]
See for example #2473, this is surprisingly easy! Significantly easier to deal with than appveyor, travis or azure and there is no connection between account to setup, etc.

**Comment by tjof2** [comment]
I _think_ options 4 or 5 are the best

**Comment by ericpre** [comment]
My concern with option 4 and 5 is that it would run additional builds during the day which will take CI resources when we may actually need it! Would one merge every day be enough?

**Comment by tjof2** [comment]
Yeah maybe a nightly merge is sufficient, just to relieve some of the work required from maintainers?
