### ISSUE TITLE
Strange behaviour of `map` with `np.log`

### ISSUE THREAD

**Issue by woozey** [hyperspy/hyperspy#1712]
Simple example:
>sss = hs.signals.Signal2D(np.arange(9).reshape(3,3))
sss.map(np.log)

>---------------------------------------------------------------------------
>ValueError                                Traceback (most recent call last)
<ipython-input-12-00b966ccb30a> in <module>()
----> 1 sss.map(np.log)

>/usr/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/hyperspy-1.3-py3.6-macosx-10.10-x86_64.egg/hyperspy/signal.py in map(self, function, show_progressbar, parallel, inplace, ragged, **kwargs)
   3506         # iterate over the coordinates.
   3507         try:
-> 3508             fargs = inspect.signature(function).parameters.keys()
   3509         except TypeError:
   3510             # This is probably a Cython function that is not supported by

>/usr/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/inspect.py in signature(obj, follow_wrapped)
   2999 def signature(obj, *, follow_wrapped=True):
   3000     """Get a signature object for the passed callable."""
-> 3001     return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
   3002 
   3003 

>/usr/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/inspect.py in from_callable(cls, obj, follow_wrapped)
   2749         """Constructs Signature for the given callable object."""
   2750         return _signature_from_callable(obj, sigcls=cls,
-> 2751                                         follow_wrapper_chains=follow_wrapped)
   2752 
   2753     @property

>/usr/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/inspect.py in _signature_from_callable(obj, follow_wrapper_chains, skip_bound_arg, sigcls)
   2336         raise ValueError(msg)
   2337 
-> 2338     raise ValueError('callable {!r} is not supported by signature'.format(obj))
   2339 
   2340 

>ValueError: callable <ufunc 'log'> is not supported by signature

The same behaviour I see also for `np.abs`.
Running freshly installed:
>hyperspy                  1.3                       (pip)
hyperspy-gui-ipywidgets   1.0.0                     (pip)

under MacOSX in Python 3.6.1
Any ideas what's wrong?

**Comment by francisco-dlp** [comment]
Good catch! This happens because inspect doesn't work for numpy's ufuncs.

Out of curiosity, why not using np.log(sss)?

**Comment by woozey** [comment]
> Out of curiosity, why not using np.log(sss)?

Honestly, I was not aware that it's working for `nav_dim`>0, which I have in real case... ))
