### ISSUE TITLE
Make HyperSpy work with skimage 0.12.3

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#1714]
Currently HyperSpy depends on skimage >= 0.13, which is not currently in the Debian unstable repositories. The current version in the Debian unstable repositories is 0.12.3, and it is not known when this will be upgraded to 0.13.

So if we want to package HyperSpy for the debian repositories, we need to make the tests and the basic functionality work with the 0.12.3 version.

More info: https://github.com/hyperspy/hyperspy/issues/455#issuecomment-322443982

**Comment by thomasaarholt** [comment]
What about Debian support for the newer skimage? Is there a particular reason Debian doesn’t support it yet?

**Comment by magnunor** [comment]
Actually, version 0.13.1 just got pushed to Debian unstable. So this is no longer an issue!

https://packages.qa.debian.org/s/skimage.html
