### ISSUE TITLE
Loading and plotting .bcf files in Hyperspy are consuming a lot of memory

### ISSUE THREAD

**Issue by Sputn1k7** [hyperspy/hyperspy#1720]
All,

I am attempting to load/plot/save a summed spectrum from a Bruker .bcf file.

This file is about 68mb in size. However, when I call my python code:

s=hs.load(select_type='spectrum')
s.sum().plot(True)

My python.exe memory spikes from a few hundred megabytes to ~9GB. I am running other background SW simultaneously which crash because my max system memory is 16GB and the system becomes unstable.

Related:

I have a laptop which has the identical python installation, and I'm running the same load/plot code on a 30MB .bcf file (with a non-lazy load), any my python.exe memory only reads ~2GB, and I have plenty of memory to spare (also 16gb max)

Does anyone have an idea of what could be going on? Also, is it possible to create a graph, modify it, and save it without having to draw it?

I looked at the lazy argument for the hs.load(), but the documentation around the lazy load talks about files in the 100s of GB range, not a ~70MB file. Do you think this could be helpful?

**Comment by Sputn1k7** [comment]
Update: even loading 100mb .bcf files on my laptop system keeps the python.exe memory at the same ~2GB.

**Comment by jat255** [comment]
@Sputn1k7 would it be possible for you to share the file? I'm not overly familiar with the .bcf format, but I'm wondering if the dimensions are particularly large (with a lot of empty channels)? Presumably the .bcf file is compressed, and loading the entire map into python would cause the whole thing to be read into memory, regardless of if a channel is empty or not.

**Comment by Sputn1k7** [comment]
@Jat255 I cannot share the .bcf file that was spiking system memory to 9gb, but I can share the .bcf file that I used on my laptop. It's about 100mb, in the attached .zip file
[quant.zip](https://github.com/hyperspy/hyperspy/files/1252268/quant.zip)

Also both systems have the same Anaconda3 install (Python3.6)

**Comment by ericpre** [comment]
```python
>>> hs.load('quant.bcf')
<EDSTEMSpectrum, title: EDX, dimensions: (1024, 1024|4096)>

>>> 1024*1024*4096
4294967296
````
which makes a bit more than 4 Go. This is the expected behaviour.

You can use the [downsample option](http://hyperspy.org/hyperspy-doc/current/user_guide/io.html#bruker-composite-file) to make smaller dataset; alternatively, you acquire data with better sampling.

**Comment by Sputn1k7** [comment]
does downsampling ruin the fidelity of my data? I am just taking a summed spectrum, not a specific ROI

**Comment by jat255** [comment]
As far as I know, no. Downsampling just does sums of the pixels and recombines it into fewer pixels. All the original data is still present, it's just not attributed to the original pixels.

As @ericpre mentioned, the actual size of your data is ~4 GB, not the 100 MB of the .bcf file, so you'll have to get used to thinking of file sizes in terms of the actual memory taken. This will change if you need to have your data as a float (for certain types of processing) vs. integers, for example.

If you can bear the temporary load on your memory, you should be able to load the data and save the summed spectrum into a new variable, and hopefully Python should clean up from memory what was loaded into memory (you'll have to try this). Something like: 
```python
s_sum = hs.load('file.bcf').sum()
```

You could also try loading and summing using the downsampling option, and then compare the two results to convince yourself that the data has not changed: 
```python
s_downsampled_sum = hs.load('file.bcf', downsample=16).sum()
np.array_equal(s_sum.data, s_downsampled_sum)
```

I tried this out with your data, and it returns `True`, so you know the data stays the same.

**Comment by jat255** [comment]
Playing around with this, it appears that doing 

```python
s = hs.load('file.bcf')
del s
```

does not clear the memory used by HyperSpy, even if doing an explicit `gc.collect()`. @francisco-dlp, do you know why this is?

Likewise, doing a direct sum like I suggested in the last reply causes the memory to remain full, which I would think is not intended behavior.

**Comment by Sputn1k7** [comment]
Thanks! I had to prove with some overlay graphic and np.array comparisons that the data is equal, but this looks like it will be a winner!

To be clear, only the x/y data is downsampled, not the Z (energy) axis, which is why when we sum the ROI, there is no data loss in the summed spectrum, even if we downsample x/y.
