### ISSUE TITLE
EDSTEMSpectrum.decomposition missing standard arguments

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1721]
Whilst EDSSEMSpectrum has decomposition arguments that I would expect, the TEM version does not. "algorithm" and "output_dimension" are missing.

**Comment by ericpre** [comment]
Do you have an example where it fails?

The following example works fine:
```python
s = hs.signals.Signal1D(np.arange(2 * 4 * 6).reshape(2, 4, 6).astype('float'))
s.decomposition(algorithm='nmf', output_dimension=3)
```

Do you mean the docstring should be improved?

**Comment by thomasaarholt** [comment]
Apologies, should have been clearer. It is the docstring that differs from the other signals' docstring.

**Comment by tjof2** [comment]
Isn't this is because `.decomposition()` is wrapped? https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/hyperspy/_signals/eds_tem.py#L603
