### ISSUE TITLE
s.remove_background(fast=False) bad fitting

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#1728]
Sometimes when using `s.remove_background(fast=False)` the fitting leads to several NaN values in the data.

```Python
import numpy as np        
import hyperspy.api as hs 

x = np.arange(370, 570)   
powerlaw = hs.model.components1D.PowerLaw(A=1000000000, r=2, origin=300)                                 

data_list = []            
for i in range(20):       
    data_list.append(powerlaw.function(x) + np.random.random(size=len(x))*10000)                         

data = np.array(data_list)                          
s = hs.signals.Signal1D(data_list)                  
s.axes_manager[-1].offset = 370                     

for i in range(100):      
    s1 = s.remove_background(signal_range=(379., 446.), fast=False)                                      
    if not np.invert(np.isnan(s1.data)).all():      
        print("Bad fit")  
        break
```

One example of this: 
![remove_background_bug](https://user-images.githubusercontent.com/1690979/30250658-4b10a526-964a-11e7-8847-ffbc0b59db77.png)

It only happens occasionally, and if it happens the "bad" region is at different navigation positions.

It does not happen when using `fast=True`, which means something is going wrong here: https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/hyperspy/_signals/signal1d.py#L1013

Also happens for "real" datasets, for example early in the [EELS notebook](https://github.com/hyperspy/hyperspy-demos/blob/master/electron_microscopy/EELS/EELS_analysis.ipynb).

**Comment by ericpre** [comment]
It look to me that this issue has been fixed by #1860?

**Comment by magnunor** [comment]
Maybe, I'll check if the bug still appears.

**Comment by magnunor** [comment]
I ran the above script 1000 times, and bug not not occur even once. So this seems to be fixed!
