### ISSUE TITLE
replace background by another expression

### ISSUE THREAD

**Issue by ZanettaPM** [hyperspy/hyperspy#1736]
I’m interested to fit the background of any EDS signals by a function taking into account physical interaction. I wrote the expression with the help of Francesco and everything works fine. 

But now I would like to fit this expression only where xray_lines are absents . 

The function "fit_background" should work but I think a part of the script is not sufficiently general and work only for polynomial functions. 

```
# disactivate line
 **self.free_background()**
        with stash_active_state(self):
            self.disable_xray_lines()
            self.set_signal_range(start_energy, end_energy)
            for component in self:
                if component.isbackground is False:
                    self.remove_signal_range(
                        component.centre.value -
                        windows_sigma[0] * component.sigma.value,
                        component.centre.value +
                        windows_sigma[1] * component.sigma.value)
            if kind == 'single':
                self.fit(**kwargs)
            if kind == 'multi':
                self.multifit(**kwargs)
            self.reset_signal_range()
        self.fix_background()
```

Free background refer to coefficients present only in polynomial

Could it be possible to adapt this part for all types of expressions ?

Here is my code : 

> for i in range(0,len(P)):
> 
>     m=P[i] .create_model(auto_background=False)
>         
>     expression = "((1250*a*((E0-(x))/(x))) *(exp(-mu*density*0.0001)))*efficiency*coating"
>     g3 = hs.model.components1D.Expression(expression=expression,mu=0,a=0,density=0.2 ,E0=0,  efficiency=0,coating=0, name="fit",module='numexpr')
>         
>     m.extend([g3])
>         
>     g3.mu._number_of_elements=1800
>     g3.mu.value=l.data[i,:] 
>     g3.mu._create_array()
>      
>     g3.efficiency._number_of_elements=1800
>     g3.efficiency.value=f.data
>     g3.efficiency._create_array()
> 
>     g3.coating._number_of_elements=1800
>     g3.coating.value=w.data
>     g3.coating._create_array()
>     
>     g3.a.value=g[i]
>     g3.E0.value=v.data[i]/2048*20.27
>    
>     
>     g3.mu.free = False
>     g3.a.free = False
>     g3.E0.free = False
>     g3.efficiency.free =False
>     g3.coating.free =False
>     g3.density.free = True
>     
>     
>     g3.isbackground=True 
>     m.fit_background()
>     
>     m.fit(fitter='leastsq',grad=True,bounded=True)
>     c[i]=m.as_signal(component_list=["fit"])

Thanks

**Comment by ZanettaPM** [comment]
I think the easiest way is to call parameters used by the fitting rountine "coefficient" in the expression to allow the function fit_background to work properly. 

But the second problem here is that some of my parameters are arrays of 1800 size of data. 

I'm working on: how remove the signal_range on this parameter as the same time as the signal_range of the model is changing.

**Comment by ZanettaPM** [comment]
My a solution: 

```
c=np.empty([27,1800])
b=np.empty([27])
r=np.empty([27,1800])
windows_sigma=[4,3]
t=0

for i in range(0,len(P)):

    m=P[i].create_model(auto_background=False)                                      
    
    expression = "((1250*a*((E0-(x))/(x))) *(exp(-mu*coefficients*0.0001)))*efficiency*coating"
    g3 = hs.model.components1D.Expression(expression=expression,mu=0,a=0,coefficients=0.2 ,E0=0,  efficiency=0,coating=0, name="fit",module='numexpr')
        
    m.extend([g3])
        
    g3.isbackground=True    
    m.background_components.append(g3)
    
    
    g3.a.value=g[i]
    g3.E0.value=v.data[i]/2048*20.27
   
    
    g3.mu.free = False
    g3.a.free = False
    g3.E0.free = False
    g3.efficiency.free =False
    g3.coating.free =False
    g3.coefficients.free = True
    
    m.add_family_lines()
    m.components
    self=m
    from hyperspy.misc.utils import stash_active_state
    
    end_energy = self.end_energy
    start_energy = self.start_energy
    self.set_signal_range(start_energy, end_energy)
    with stash_active_state(self):
            self.disable_xray_lines()
            for component in self:
                if component.isbackground is False:
                    self.remove_signal_range(
                        component.centre.value -
                        windows_sigma[0] * component.sigma.value,
                        component.centre.value +
                        windows_sigma[1] * component.sigma.value)
    
    ns = np.empty(self.axis.axis.shape)
    ns.fill(np.nan)
    ns[self.channel_switches] = 1
    r=ns*l.data[i,:]
    r = [x for x in r if str(x) != 'nan']
    f2=ns*f.data
    f2 = [x for x in f2 if str(x) != 'nan']
    w2=ns*w.data
    w2 = [x for x in w2 if str(x) != 'nan']
    
    self.reset_signal_range()
    
    g3.mu._number_of_elements=len(r )
    g3.mu.value=r
    g3.mu._create_array()
       
    g3.efficiency._number_of_elements=len(f2)
    g3.efficiency.value=f2
    g3.efficiency._create_array()

    g3.coating._number_of_elements=len(w2)
    g3.coating.value=w2
    g3.coating._create_array() 


    m.fit_background()
    
    
    g3.mu._number_of_elements=len(l.data[i,:] )
    g3.mu.value=l.data[i,:]
    g3.mu._create_array()
       
    g3.efficiency._number_of_elements=len(f.data)
    g3.efficiency.value=f.data
    g3.efficiency._create_array()

    g3.coating._number_of_elements=len(w.data)
    g3.coating.value=w.data
    g3.coating._create_array()
    
    
    m.fit(fitter='leastsq',grad=True,bounded=True)
    c[i]=m.as_signal(component_list=["fit"] )
    #m.plot(plot_components=True)
    b[i] =g3.coefficients.value
```

**Comment by ericpre** [comment]
Thanks for reporting this, but it is not very clear where were the issue comes from and how you solve it.
You should be able to add a custom background fairly easily by doing:

```python
import hyperspy.api as hs

s = hs.datasets.example_signals.EDS_SEM_Spectrum()
s.add_elements(['Al', 'Ar', 'C', 'Cu', 'Mn', 'Zr'])
s.set_microscope_parameters(beam_energy=10)

expression = "((1250*a*((E0-(x))/(x))) *(exp(-mu*density*0.0001)))*efficiency*coating"
bg = hs.model.components1D.Expression(expression=expression, mu=1, a=1,
                                      density=1, E0=1, efficiency=1,
                                      coating=1, name="BG", module='numpy')
bg.isbackground = True # you need specify that this component should considered as background

m = s.create_model(auto_background=False)
m.append(bg)

m.fit_background()
m.fit()
m.plot()
```
This example does not raise an error and the value of the background parameters are actually changing. Could it be an model initialisation issue or the background model does not describe well the data? For example, the `mu*coefficient` and `efficiency*coating` should be combined into one parameter each.

You may need to play with the parameters of `fit_background` and `fit`.

What is your conclusion on this?

**Comment by ZanettaPM** [comment]
Hi Eric, thanks for your help.

Sorry if I'm not clear, two problems initially raised an error. 

The first one was: 

If I add `m.background_components.append(bg)` (cause I thought I needed it) then the error was : 

```
<ipython-input-57-6cd3a95f8173> in <module>()
     68     g3.coating._create_array()
     69 
---> 70     m.fit_background(grad=True,windows_sigma=(4,3),bounded=True)
     71     m.fix_background()
     72 

C:\Anaconda3\lib\site-packages\hyperspy\models\edsmodel.py in fit_background(self, start_energy, end_energy, windows_sigma, kind, **kwargs)
    367 
    368         # deactivate line
--> 369         self.free_background()
    370         with stash_active_state(self):
    371             self.disable_xray_lines()

C:\Anaconda3\lib\site-packages\hyperspy\models\edsmodel.py in free_background(self)
    296         """
    297         for component in self.background_components:
--> 298             component.coefficients.free = True
    299 
    300     def fix_background(self):

AttributeError: 'Expression' object has no attribute 'coefficients'

```


But as you mentioned I don't need to add this part of code and it works well !

I don't have already understood why, cause in the sub-function free_background the name of the parameters have to be "coefficients" but OK.



The second error was: 

My free parameter to fit is "coefficients"  as it's mentioned above. But the other one : µ, coating, efficiency, are **dependent** of the energy. In order to integrate those parameters in my fit I've calculated those parameters before and I've added in my model **an array** for each parameter of the **dimension of the signal** (here 1800). 

I've discussed with Francesco about that and we've concluded that was the best way to simplify that. 

It's why I've written :

```
g3.mu._number_of_elements=len(signal_range)
g3.mu.value= data # like mass absorption coefficients for all energy
g3.mu._create_array()
```
were mu is exactly a signal 1D of 1800 values



But in this case, the array do not have the same size as the signal_range during the "fit_background" cause this function deactivate xray_lines. 

To solve this problem I just used a part of the code of fit_background to apply this (multiple)-crop to my array

```
    from hyperspy.misc.utils import stash_active_state
    
    end_energy = self.end_energy
    start_energy =self.start_energy
    self.set_signal_range(start_energy, end_energy)
    with stash_active_state(self):
            self.disable_xray_lines()
            for component in self:
                if component.isbackground is False:
                    self.remove_signal_range(
                        component.centre.value -
                        windows_sigma[0] * component.sigma.value,
                        component.centre.value +
                        windows_sigma[1] * component.sigma.value)
    
    ns = np.empty(self.axis.axis.shape)
    ns.fill(np.nan)
    ns[self.channel_switches] = 1
    r=ns*l.data[i,:] # l contain the value of mu
    r = [x for x in r if str(x) != 'nan']
    f2=ns*f.data # l contain the value of efficiency
    f2 = [x for x in f2 if str(x) != 'nan']
    w2=ns*w.data # l contain the value of coating
    w2 = [x for x in w2 if str(x) != 'nan']
    
    self.reset_signal_range()
```

I will try to make a pull request to modify this problem, in this way we should be able to use parameters of different dimensions. 

Does everything is clear now ?

**Comment by ericpre** [comment]
Yes, it is a bit more clear now, but still not completely clear! ;)

- indeed, you could make a PR to change `free_background` and `fix_background` to free/fix all parameters instead of only `coeffcients`. See the[ dev guide](http://hyperspy.org/hyperspy-doc/current/dev_guide.html).
- what is the reason not to incorporate the energy dependence of mu, coating and efficiency into the expression? Are these not analytical functions, that you need to compute separately?
- would this physical model be robust and reliable enough to be incorporate as an EDS background model?

**Comment by ZanettaPM** [comment]
The parameter mu is calculate by : 

`hs.material.mass_absorption_mixture(elements=P[u].metadata.Sample.elements,weight_percent=r[u], energies=t[k])`

It was easier to calculate this before, and was difficult to write this in the expression. 

And for your last question, initially it was not the idea to construct a model such like this, the first idea was to fit an unknow parameter thanks to this expression. 
But yeah i've started to discuss about that with Francesco and it could be possible, maybe, to incorporate this one as an EDS Background model. 
(could be so cool !)

**Comment by ZanettaPM** [comment]
The real problem is : we need an approximation of the composition, (so integrate peak for exemple), and of the density. 
So the idea is : at first integrate peak, this approximation allow to calculate a first background and a first quantification (background corrected) and after we have to iterate until the composition found become close enough to the precedente iteration

The problem of this method is that the model will be long to fit, and can be apply only on a single spectra i think and not on multiple spectra. 

Maybe you have other idea ?

**Comment by ZanettaPM** [comment]
![figure_stack_of_spectrum_5_signal](https://user-images.githubusercontent.com/25037207/31121428-754d91fa-a838-11e7-9aad-26ec99178b59.png)

I obtain fit such like this for the moment
