### ISSUE TITLE
BUG: Evil bcf localisation

### ISSUE THREAD

**Issue by sem-geologist** [hyperspy/hyperspy#1738]
When opening some of BCF files Traits error is raised.
e.g. : `TraitError: The 'scale' trait of a DataAxis instance must be a float, but a value of [any number, any number] <class 'list'> was specified.`
Error was reported by  @thomasaarholt.
Suddenly all mappings done in our laboratory with same hyperspy version and same Esprit version started to raise this error.
My closer examination revealed, that it happens due to (1) changing Windows locale into European (2) which ignoring the XML specification by Bruker (not a first case) makes some (not all) decimals to be saved into XML with comma (instead of dot), which makes de-serialization of XML to convert such decimal into list instead of float.

How to ~~fix~~ hack it away?
There should be no lists in Bruker xml of length = 2, so before pushing the dictionary to bcf reader, the dict could be scanned, and all flat lists of length 2 should be converted to float.

The problems:
the existence of the problem shows that parts of metadata in Bruker software is not de-localisided before beeing put into XML, thus it is not possible to fix it by only replacing commas into points, as e.g. french would have `1.000,00`, but german `1000,00`...

**Comment by ericpre** [comment]
When you parse the XML value could you do something along the line of:
```python
value = float(original_value_as_string.replace(',', '.'))
```

**Comment by sem-geologist** [comment]
imagine some locale which would write 1000.00 as 1,000.00...
It is no coincidence that both json and XML specification strongly forbids to store decimals in localised form. There is no simple, universal hack to win such situation :/

**Comment by ericpre** [comment]
yes, I was thinking about it... I guess we just need to parse the data correctly and there is only a limited number of possibilities, so even if this is ugly, it will be alright.

**Comment by sem-geologist** [comment]
I have added my hack on the problem in PR #1741 .
It warns the user when error first time appears.
If user wants to use other than en_US locale on EDS machine, he will need to pay the price by adding one line providing the thousand and decimal separators.
I dont deal with locales, as windows call them different than python, and for somebody having no experience with unix it would be painfully cryptic.
Also the change of locale in library is  highly unrecommend in python doc.

I think expecting for user to deal with separators is much more straigh forward.

**Comment by sem-geologist** [comment]
@ericpre , I have used regex to check, isolate and replace the commas into dots–no more user interaction is needed. Issue is fixed with 3 lines of code, and costs up 1-100 ms  (depending from processor and bcf image size, and computing power) per bcf load.

**Comment by ericpre** [comment]
Fixed in #1741.
