### ISSUE TITLE
Add read support for Nexus (HDF5) format?

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#1748]
Seems that the neutron, X-ray, and muon community are also using HDF5 for their files: http://download.nexusformat.org/doc/html/introduction.html#nexus-introduction

It seems well-documented, and due to it being based on HDF5, it should be easy to add a reader for it.

More general info: http://www.nexusformat.org/

**Comment by ericpre** [comment]
Looking a bit around on this, there is the NeXus python API, which binds the NeXus libraries (https://github.com/nexusformat/code) to Python:
https://github.com/nexusformat/python-nxs

and there is a also pure python library to load this format:
https://github.com/nexpy/nexusformat

**Comment by magnunor** [comment]
Some work on getting electron microscopy data included in the NeXus definition: https://github.com/LiberTEM/LiberTEM/tree/master/fileformat

Also includes an example script for loading a NeXus file as a Lazy HyperSpy Signal2D.

**Comment by ericpre** [comment]
Done in #2328.
