### ISSUE TITLE
fix-enh: post-checkout hooks

### ISSUE THREAD

**Issue by sem-geologist** [hyperspy/hyperspy#1754]
### Git post-checkout hooks: fix and enchantment

Some time ago when I implemented fast cython bcf library I got into problem where part of branches were without this new cython code, and that branch had. I were directed to brilliant solution of post-checkout hooks, to check and compile pyx if it was missing. Basically it was tested to work correctly in such cases as switching between branches containing cython code and absent of it. The state of those hacks is really not good, and started to misbehave after most of code/branches started to have the cython code. In real it is obscurely too much code dedicated for so simple stuff (it is literally taking 1/3 of setup.py). I am re-examining the problem and rethinking to replace it with something better and more robust. So actually when we want to compile/recythonize?
If between checkouts some of those got changed:

1.   If cython version got updated
2.    If python version got updated (numpy got updated? it is one of dependencies)
3.    If pyx file itself got updated (the code which is recompiled/recythonized)
4.   If compiler got updated (???)
5.    If userspace c libraries got updated
6.    If c files are missing (first time clone)

And contrary, if any of above were not changed, recompilation is not welcome.

I believe setuptools checks for 6. so this is not concerning. But how to check 1-5, such information should be intercept and saved somewhere in under .git directory during the checkout and then used to do recythonization and recompilation if needed after. How to check that pyx file changed? checksum, or maybe git itself can help here as it is tracking all changes?

I open this discussion, and encourage some suggestion and ideas how to deal with those hooks.

I think there is two radical approaches:
* remove hooks, and let developer to decide when use clean, or manualy delete the *.so and .c files. (that is allready obtanable, by creating .githook_ignore file in the directory of hyperspy).
* wipe all c and .so files after every checkout, and force recompiling/recythonising of everything.

update:
* if pyx file gets updated, calling `setup.py recythonize` have no effect until the c file is deleted.

**Comment by ericpre** [comment]
Indeed, it would be great to make it a bit more tidy!
Some cythonizing issues are cluttered across several issues, but the most relevant one are: 
- #949: initial implementation
- #1356: switching branches and post-checkout hook issue
- #1512: recythonize issue
- #1752: recythonize issue

Some relevant PRs: 
- #1723: fix path to works on windows and unix system
- #1585 and #1575: path issue

The cythonize code makes setup.py quite messy. If it has to stay so long, I would suggest to move this part to a separate file.
I think it would still be very convenient to cythonize automatic, when necessary.

It may be worth having a look at how are doing other projects:
- scikit-learn, they actually improved the way they cythonize in scikit-learn/scikit-learn#7719, scikit-learn/scikit-learn#6254
- scikit-image.

**Comment by sem-geologist** [comment]
@ericpre, @francisco-dlp , I think the best way is simply to get rid of hooks, and leave the business of recompiling the cython code for developers, as only single cython extension is present at the moment.
I think that adopting `scikit-learn` cythonisation approach (looking from few year perspective at hyperspy) is overkill, as there is only a single cython extension.
Scikit's approach could be the best way, but only if more cython extensions would be written.

I can see that the biggest problem of current code (complicated cythonisation code in setup.py and hooks) that it tries to solve something what in a few years had not happened (more cython extensions). I think many dynamic code parts can be simplified. And we could completely remove hooks. instead notice in documentation for proper sequence could be updated (e.g. if wishing to recythonise the code when developing, to use `setup.py clean` or `setup.py clean --all`;

How about it?

**Comment by ericpre** [comment]
Yes, we need to get this sorted for 1.4 and it would be great if it could be used easily by hyperspy-extension, so we need to find a good strategy to deal with it.
Could it be possible to import the functions from scikit-learn and use the same approach?

**Comment by ericpre** [comment]
label as bug since it breaks the documentation build.

**Comment by francisco-dlp** [comment]
Closing as the post checkout hooks have been removed.
