### ISSUE TITLE
hyperspy_gui_ipywidgets does not install automatically

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1763]
The ipywidgets gui does not install when calling `conda install hyperspy` after adding conda-forge. I believe it should be installing it.

**Comment by ericpre** [comment]
ipywidget is not a dependency of hyperspy, so why should it install it? The idea of splitting into several package is to give the user the flexibility to install what he want.

**Comment by thomasaarholt** [comment]
Hm. It is difficult to find the right balance between making hyperspy lightweight and user friendly.

The main reason that I was surprised is that I expected that it would be installed when installing from conda, but that doesn't need to be the case.

I'll comment more in #1599 (splitting hyperspy)

**Comment by francisco-dlp** [comment]
The documentation states that it is installed automatically so this is either a code or doc bug.

As many interactive visualization operations benefit from widgets, I think that people may feel that hyperspy is broken without ipywidgets or traitsui.

On the other hand, it's true that it adds to the dependencies clutter. In the future, after the split, we could offer a ``hyperspy-core`` package without ipywidgets and a "virtual" package (e.g. ``hyperspy-full`` that installs everything)  but, for the moment, I think that installing ipywidgets is the best option for most users.

**Comment by francisco-dlp** [comment]
Fixed in https://github.com/conda-forge/hyperspy-feedstock/pull/15

**Comment by ericpre** [comment]
conda-forge/hyperspy-feedstock#15 is merged and now available in conda-forge.
