### ISSUE TITLE
Problem to read correctly some EDS spectrum images recorded with TIA

### ISSUE THREAD

**Issue by bertrandlacroix** [hyperspy/hyperspy#1766]
Dear all, I am an occasional user of Hyperspy, in particular to perform denoising of EDS/EELS spectrum images. I find this program very powerful and useful for part of my investigation. However, I recently encountered some difficulties with EDS spectrum images acquired using the TIA software on a Talos microscope: when I try to open the .emi (or .ser) files using either HyperspyUI or Jupyter QtConsole, the SI is not loaded correctly since the spectra in individual pixels are not as expected (most of the spectra present flat signal except some channels that have high intensity about 1e9, which is not real when we look the data on TIA). It is important to mention that I recorded similar EDS SI one year ago on the same microscope, and for these data I do no have such a problem (the data are correctly loaded in Hyperspy). I suppose that the problem could be due to an update of the TIA software used to record the SI but I am not sure... I wonder if one of you already observed this problem and I would be grateful if someone can help me to solve this trouble. Thank you in advance for your answer.

Here is the link to download the .emi and .ser files:
https://drive.google.com/file/d/0B-AzjS03KVoLQlBYRXNyUFRFQ3c/view?usp=sharing

**Comment by ericpre** [comment]
This is already fixed in commit 4b0a497c61bb8fa61fc3397109676c6264c08c71. You need to use the "next_release_minor" branch.

**Comment by thomasaarholt** [comment]
@ericpre Thanks for highlighting the commit and fixing the issue. Considering that that was in july, I guess it's about time we update a new hyperspy release? @francisco-dlp 

Thanks for fixing support for TIA stacks, btw. Having recently installed Smart Align I'm realising I'm going to need to use that.

**Comment by ericpre** [comment]
Closing this since this should be already fixed in both the "next_release_patch" and the "next_release_minor" branches.
