### ISSUE TITLE
Image missing in current version of Developer Guide

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#1769]
In the HyperSpy user guide for the current version, in the "Use git and work in managable branches" part, the image `_images/branching_schematic.eps` is not shown.

http://hyperspy.org/hyperspy-doc/current/dev_guide.html#use-git-and-work-in-managable-branches

**Comment by ericpre** [comment]
Fixed in #1770.

**Comment by ericpre** [comment]
Fix in #1798.
