### ISSUE TITLE
Bruker load error on TEM data cube

### ISSUE THREAD

**Issue by ZGainsforth** [hyperspy/hyperspy#1772]
`s = hs.load('Stack2.bcf')`

yields:

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-4-99105eb81d62> in <module>()
----> 1 s = hs.load('Stack2.bcf')

/Users/Zack/anaconda/envs/conda36/lib/python3.6/site-packages/hyperspy/io.py in load(filenames, signal_type, stack, stack_axis, new_axis_name, lazy, **kwds)
    241             objects = [load_single_file(filename, lazy=lazy,
    242                                         **kwds)
--> 243                        for filename in filenames]
    244 
    245         if len(objects) == 1:

/Users/Zack/anaconda/envs/conda36/lib/python3.6/site-packages/hyperspy/io.py in <listcomp>(.0)
    241             objects = [load_single_file(filename, lazy=lazy,
    242                                         **kwds)
--> 243                        for filename in filenames]
    244 
    245         if len(objects) == 1:

/Users/Zack/anaconda/envs/conda36/lib/python3.6/site-packages/hyperspy/io.py in load_single_file(filename, signal_type, **kwds)
    284                                 reader=reader,
    285                                 signal_type=signal_type,
--> 286                                 **kwds)
    287 
    288 

/Users/Zack/anaconda/envs/conda36/lib/python3.6/site-packages/hyperspy/io.py in load_with_reader(filename, reader, signal_type, **kwds)
    293     lazy = kwds.get('lazy', False)
    294     file_data_list = reader.file_reader(filename,
--> 295                                         **kwds)
    296     objects = []
    297 

/Users/Zack/anaconda/envs/conda36/lib/python3.6/site-packages/hyperspy/io_plugins/image.py in file_reader(filename, **kwds)
     61 
     62     """
---> 63     dc = _read_data(filename)
     64     lazy = kwds.pop('lazy', False)
     65     if lazy:

/Users/Zack/anaconda/envs/conda36/lib/python3.6/site-packages/hyperspy/io_plugins/image.py in _read_data(filename)
     81 
     82 def _read_data(filename):
---> 83     dc = imread(filename)
     84     if len(dc.shape) > 2:
     85         # It may be a grayscale image that was saved in the RGB or RGBA

/Users/Zack/anaconda/envs/conda36/lib/python3.6/site-packages/scipy/misc/pilutil.py in imread(name, flatten, mode)
    154     """
    155 
--> 156     im = Image.open(name)
    157     return fromimage(im, flatten=flatten, mode=mode)
    158 

/Users/Zack/anaconda/envs/conda36/lib/python3.6/site-packages/PIL/Image.py in open(fp, mode)
   2450         fp.close()
   2451     raise IOError("cannot identify image file %r"
-> 2452                   % (filename if filename else fp))
   2453 
   2454 #

OSError: cannot identify image file 'Stack2.bcf'

I suspect all that is happening is that there is no STEM image stored in the file.  The EDS cube opens fine in the Bruker software and I have successfully opened other cubes from the same microscope without trouble (though they had HAADF images embedded).

**Comment by sem-geologist** [comment]
@ZGainsforth ,which branch do you use? I saw already this bug in travis ci not long ago, which was caused by weird mess-up with lxml library by anaconda.
As I can see from reported error output, io.py tries to open the bcf using PIL instead using bcf plugin, PIL for obvious reason fails, and bcf_plugin is not used due to lxml bug (which is not obvious from error message).
Can you install next_minor version from git? From that version bcf_plugin have dropped `lxml` and uses `etree`. (I had never any problem with lxml in OS based env, but anaconda somehow keeps messing with libraries constantly).
Optionally, if your data is not very confidential, consider sharing single sample bcf file from your stack, to be sure it works.

**Comment by sem-geologist** [comment]
BTW, bcf_plugin should return all images (HAADF) if present, independently from how many are acquired during hypermap's collection, be it 0 or 10 and more.

**Comment by ZGainsforth** [comment]
OK yes.  That solves it.  I was using 1.3 installed by conda.  Now I'm now using 1.4.dev0+git.99.g681829d5 and it opens the bcf without issue and I can see the data.

Thank you!
