### ISSUE TITLE
BUG: BCF-dask memory leak

### ISSUE THREAD

**Issue by sem-geologist** [hyperspy/hyperspy#1773]
in issue #1720 (which is closed) @jat255 had reported additional observation that deletion of bcf obtained signal does not free memory. I have bumped into this issue after upgrading from 1.1 to 1.3 version which had broke my workflow of dealing with thousands of bcfs.

It is clear that xml part is not involved and something had changed in hypercube reading.
I shortly tested with dummy rpl files same workflow on the same machine and it is clear that only bcf are affected. It is possible that same mem leak is affecting  hyperspy-ui (which I had observed previously with bcfs).

I will work in finding the leak, but suggestions how to do that is welcome.

**locating the source of the leak:**

- [x] Does "pure_python" (calling method `BCF_reader.py_parse_hypermap`) implementation generates destroyable array? YES, it can be deleted instantaneously (no `gc.collect()` is needed – `del` takes care)
- [x] Is cython parsed array (function `unbcf_fast.parse_to_numpy`) destroyable? YES, arrays can be deleted with `del`.
- [x] Is the array destroyable when called through method `BCF_reader.parse_hypermap`? **NO**, both ( when using python or cython) implementations results in indestructible array when abstracted by this function.
- [x] What have changed in that method in between versions 1.1 to 1.3 ? Lazy/dask wrappers were added at 1.2.
- [x] What exactly is leaking? It have nothing to do with any hyperspy code.

**Comment by sem-geologist** [comment]
I tested unbcf_fast.pyx parsing function, the array is destroyable.
I narrowed down the problem - it is lazy loading code!
"pure python" loading is not affected as it missed the lazy-loading code injection.
@to266 , any insight to this problem?

**Comment by sem-geologist** [comment]
I think this can be connected:
https://github.com/dask/dask/issues/2625

btw, I tested above bug on python 3.5 on KDE neon (based on Ubuntu 16.04)

**Comment by sem-geologist** [comment]
oh and btw, my test on rpl files missed the point as it do not use dask.

Could anybody test heavily other formats to see if dask problem persists there too.

**Comment by ericpre** [comment]
Would it be possible to write a test, which checks if the memory have been released after deleting the object? And run this test for all io readers?

**Comment by sem-geologist** [comment]
@ericpre , no need for that. I can replicate the leak without hyperspy. Writing test is the last thing needed in this case.
So what is the problem? it is `dask_delayed`.
At the beginning I though that class methods and instance references of bcf when mingled with `dask_delayed` causes circular reference causing the memory leak.
I tried  to construct class with some artificial methods trying to mimic the mess in the bcf.
However the memory leak can be replicated without classes, using single function.
To lock out that it is not another jupyter's memory management nonsense, I also tried the function run from script.
```python
import numpy as np
import dask.array as da
import dask.delayed as dd
import gc

def gen_delayed(shape, dtype, lazy=False):
    value = dd(np.ones)(shape, dtype=dtype)
    if lazy:
        res = da.from_delayed(value, shape=shape, dtype=dtype)
    else:
        res = value.compute()
    return res

if __name__ == "__main__":
    test_a = gen_delayed((1024,768,1024), np.uint8)
    del test_a
    gc.collect()  # with or without this, memory is not released
    a = input()   # this is to hold-on the python state to check memory  
    print(a)      #
```   

it was tested on:
```
Python 3.5.2 (default, Sep 14 2017, 22:51:06) 
[GCC 5.4.0 20160609] on linux
```

**Comment by sem-geologist** [comment]
@francisco-dlp , for now, would it be ok to strip-off dask/lazy from bcf? It is useless at this state, and I can't recommend people hyperspy-ui/windows distribution as it have these leaks (the last time I tried to demonstrate someone 1.3, I saw memory leak there, but thought it is ui's bug, but now I know where it comes from).

**Comment by francisco-dlp** [comment]
I wouldn't remove the lazy code in HyperSpy because of an external bug. Instead, what about reporting the issue in https://github.com/dask/dask/issues/2625 ? Once they fix it, we can set a min dask version in ``setup.py`` and close this issue. Does it sound good?

**Comment by sem-geologist** [comment]
What about code refactoring? at this moment it wraps the reader through dask even if `lazy=False` (it returns array after dask's `compute()` method instead of primary numpy array);
What if I could refactor `if:... else` logic so that it would not use dask if `lazy=False` but return numpy array, just as at v1.1?
I should mention that in case of lazy=True, it have no memory problems with calculating max(), min() and other data statistics, until calling compute(). Code refactoring would be good compromise, wouldn't it be?

**Comment by sem-geologist** [comment]
I mean these lines to refactor:
[https://github.com/hyperspy/hyperspy/blob/681829d57699eef74bde4564763106a90d517cbb/hyperspy/io_plugins/bcf.py#L944-L973](https://github.com/hyperspy/hyperspy/blob/681829d57699eef74bde4564763106a90d517cbb/hyperspy/io_plugins/bcf.py#L944-L973)

so that `if lazy:` would be the first check instead of the second.

**Comment by francisco-dlp** [comment]
Sounds good! Will you let the dask devs know that this is a problem for us in https://github.com/dask/dask/issues/2625?

**Comment by sem-geologist** [comment]
They already have the link/reference to this issue as I had mentioned them. I think in that it is clear that we are affected by this bug. Should I leave more verbose message?
I am not sure if this is present in python 3.5.4, as I am using 3.5.2; they claim it is gone on 3.5.4 for dask but not for dask.distributed.
Anyway, I think code refactoring is better than constraining minor versions of python.
 Can the small code above (6 posts up) produce memory leak on newer python versions (3.6.2, 3.5.4)?

**Comment by sem-geologist** [comment]
I opened PR #1779 ;

**Comment by sem-geologist** [comment]
as #1779 got merged I am closing this.
