### ISSUE TITLE
C++ hdf5 writer for hyperspy format

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1776]
Has anyone had a go at writing a hyperspy hdf5 writer for C++? I am about to propose the format for use with some STEM simulation software (Prismatic / pyprismatic), and it would be nice to have something to refer to rather than write it from scratch.

**Comment by francisco-dlp** [comment]
Not that I know.

**Comment by thomasaarholt** [comment]
Closing until it gets relevant again
