### ISSUE TITLE
Power law background removal bug?

### ISSUE THREAD

**Issue by mwalls** [hyperspy/hyperspy#1786]
When running the demo by Magnus about EELS quantification. the one that is here:
https://github.com/hyperspy/hyperspy-demos/blob/master/electron_microscopy/EELS/EELS_analysis.ipynb

the data can sometimes disappear partially as indicated in the figures below.
![quantify_problem_signal](https://user-images.githubusercontent.com/1022064/33839347-39b4a15c-de92-11e7-9433-5bf5c8c380b5.png)
![quantify_problem_nav](https://user-images.githubusercontent.com/1022064/33839348-39cba5be-de92-11e7-836b-126449dd7e0a.png)

The problem seems only to occur when not using the 'fast' option. it is not 100% reproducible. Different parts of the data disappear in different tests, possibly as a function of the exact fitting window.

**Comment by mwalls** [comment]
Here is another phenomenon that can occur. In this case the window went from 438 to 448 eV. The last spectrum has some kind of oscillating artefact signal
![quantify_problem_signal3](https://user-images.githubusercontent.com/1022064/33840422-2f3b1dfc-de95-11e7-9529-c739fdfef1dd.png)
![quantify_problem_nav3](https://user-images.githubusercontent.com/1022064/33840423-32019822-de95-11e7-847e-8010b8cd0c4d.png)

 added:

**Comment by mwalls** [comment]
It is also almost completely negative...

**Comment by mwalls** [comment]
In fact the background subtraction seems not to be reproducible. If I run the following code:
`for x in range(1,10):
    sbr=s.remove_background(signal_range=(437,449.0),fast=False)
    sbr.plot()`

I get 10 different backgound removals. Here are 3 of the images:
![figure_eels_spectrum_image_ high-loss _navigator-3](https://user-images.githubusercontent.com/1022064/33886885-44bcb4c0-df48-11e7-9938-1488b323b59b.png)
![figure_eels_spectrum_image_ high-loss _navigator-2](https://user-images.githubusercontent.com/1022064/33886889-46c486a8-df48-11e7-8746-611b3a98e691.png)
![figure_eels_spectrum_image_ high-loss _navigator-1](https://user-images.githubusercontent.com/1022064/33886894-48a10f1e-df48-11e7-9f8a-940dc473e321.png)

**Comment by mwalls** [comment]
Another attempt to show the code:
`for x in range(1,10):
    sbr=s.remove_background(signal_range=(437,449.0),fast=False)
    sbr.plot()`

**Comment by mwalls** [comment]
Have just checked it is non-reproducible with other datasets as well, eg DM SIs.

**Comment by mwalls** [comment]
OK I think I may understand this problem. I've chased it down in the code as far as the fact that when not using fast fitting, it fits the background using 'multifit', which is some iterative fitting routine like 'fit'. I don't know where these come from but they are the ones used in general model fitting and they are iterative, being used as they normally are on more complicated models with several components, and thus large numbers of parameters. A simple least-squares fit of a power law function to a set of data should have an analytical solution not requiring iterations. I think 'fit' or 'multifit' is thus maybe using a sledgehammer to crack a nut, and it doesn't seem to work very well. (Why it's not reproducible I'm not sure, but I've seen that in other fits as well I think...) I don't understand yet how 'multifit' is invoked, or where or what it is, so I can't fix this quickly. If I'm right about all this and someone who understands it better can do it then please do so! Otherwise I'l try and figure it out, but don't hold your breath.

**Comment by mwalls** [comment]
OK I think I may understand this problem. I've chased it down in the code as far as the fact that when not using fast fitting, it fits the background using 'multifit', which calls some fitter (by default least squares). I don't know where the fitters come from but they are the ones used in general model fitting and they are iterative, being used as they normally are on more complicated models with several components, and thus large numbers of parameters. A simple least-squares fit of a power law function to a set of data should have an analytical solution not requiring iterations. I think 'fit' or 'multifit' is in this case maybe using a sledgehammer to crack a nut, and it doesn't seem to work very well. (Why it's not reproducible I'm not sure, but I've seen that in other fits as well I think...) I don't understand yet how 'multifit' invokes, the fitter or where or what it is, so I can't fix this quickly. If I'm right about all this and someone who understands it better can do it then please do so! Otherwise I'll try and figure it out, but don't hold your breath.

**Comment by francisco-dlp** [comment]
Thanks for your insight. Yes, it uses NLLS and, yes, unlike LLS, NLLS can lead to local minima. However, we can't solve this by LLS because the function is not linear. Fitting this background seems to me straightforward enough for the NLLS algorithm to perform the task without issues, specially considering that we use the estimated parameters from the fast method to initialise the parameters. Actually, I think the behaviour that you describe is so weird that there must be something stranger going on.

**Comment by mwalls** [comment]
Can't we just take logs to make it linear (using the doubles of the residuals rather than the squares)?

**Comment by francisco-dlp** [comment]
Would that work to estimate both ``A`` and ``r``? Beside, wouldn't the result of taking logs be biased?

I think that NLLS should work because we use it all the time for more complex models, so I see no reason for it not to work here. In any case, it's probably a good idea to solve this using an estimator specific for the power law instead of the "sledgehammer" NLLS. However, that would have the drawback of assuming a model for the noise, while the current method takes into account the variance in ``metadata.Signal.Noise_properties`` if defined.

**Comment by magnunor** [comment]
I've seen the same issue earlier: https://github.com/hyperspy/hyperspy/issues/1728

It is partly related to not having good initial values, which can be triaged by firstly estimating the values, ignoring the outliers, and using the mean parameters as initial values for the main fitting.

**Comment by mwalls** [comment]
I may be simplifying too much then. Using weighted least squares (back in my day) was justified by the assumption the the variance was the same as the signal. So the squaring took care of the weighting. But it seems to be that it should be possible here. If some transform is applied to make it Gaussian (is that what happens? like with 'True' in decomposition?) then do that and then take logs and use the doubles of the residuals in place of their squares.

But in any case maybe as you say it's something more sinister...

**Comment by mwalls** [comment]
Magnus, Francisco  seems to think that is already done?

**Comment by jat255** [comment]
Just chiming in, I wonder if we properly fix this bad initial values problem, if it would finally nip #726?

**Comment by mwalls** [comment]
Sorry, using the double residuals was obviously not quite right, although it's a reasonable approx for non-noisy data I think.

**Comment by magnunor** [comment]
@mwalls, is it? I haven't noticed https://github.com/hyperspy/hyperspy/issues/1728 being fixed. The "release: next patch" means we want to fix it in the next patch release.

**Comment by mwalls** [comment]
Well, I was wondering if Fran would confirm this or not. But I know he's pretty busy with teaching atm. AFAICS the relevant bit of code is this (from line 1000 in /hyperspy/_components/power_law.py:

 def _remove_background_cli(
            self, signal_range, background_estimator, fast=True,
            show_progressbar=None):
        signal_range = signal_range_from_roi(signal_range)
        from hyperspy.models.model1d import Model1D
        model = Model1D(self)
        model.append(background_estimator)
        background_estimator.estimate_parameters(
            self,
            signal_range[0],
            signal_range[1],
            only_current=False)
        if not fast:
            model.set_signal_range(signal_range[0], signal_range[1])
            model.multifit(show_progressbar=show_progressbar)
        return self - model.as_signal(show_progressbar=show_progressbar)

It looks to me as if it does the quick estimation first, whether fast is True or False.

**Comment by mwalls** [comment]
I admit I am baffled as to how a bad power law parameter estimation could lead to the weird spectrum oscillations I showed above (a few days ago).

**Comment by mwalls** [comment]
Sorry, the code quoted above is in :
/hyperspy/_signals/signal1d.py. 

Sorry for any confusion

**Comment by mwalls** [comment]
I don't think it's the fitting procedure going wrong. I think it's the parameter "out_of_range_to_nan" which is behaving strangely in the line 
return self - model.as_signal(show_progressbar=show_progressbar)
in the code above

Here are the plots of A and r and the final image of the background subtracted data:
![figure_a_parameter_of_powerlaw_component_signal](https://user-images.githubusercontent.com/1022064/34113328-a67026ea-e40f-11e7-8608-c4f8f6a222b9.png)
![figure_r_parameter_of_powerlaw_component_signal](https://user-images.githubusercontent.com/1022064/34113335-a88dadda-e40f-11e7-9620-c872ddf605a1.png)
![figure_eels_spectrum_image_ high-loss _from_fitted_model_navigator](https://user-images.githubusercontent.com/1022064/34113340-ab77c5ee-e40f-11e7-929e-997fa88ebd57.png)
The region where things go wrong corresponds to about 4;5 to 11 nm in X, in which range the A and r parameters are very normal. 


However, in "model.as_signal()"  the option "out of range to nan" is by default set to True. So i'm surprised that there are not nans everywhere outside the fitted region in all the spectra. When I try putting it to "False" it *does* put everything outside the fitting region to nans (as though it were "True"). In the code for .as-signal I can't see where it uses the information about "out-or_range_to_nan". It doesn't seem to care what it is. So I have run out of steam.
Help!

**Comment by francisco-dlp** [comment]
Thanks for catching the bug! The issue seems to be in the code in https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/hyperspy/model.py#L508 .

**Comment by francisco-dlp** [comment]
@mwalls, does #1860 fully fix this issue? If yes, could you close it?

**Comment by ericpre** [comment]
@mwalls, have you had time to have a look at if #1860 fixes this issue? :smile:

**Comment by ericpre** [comment]
Reopen if you notice that the issue still exists.
