### ISSUE TITLE
Update image examples in user guide

### ISSUE THREAD

**Issue by jat255** [hyperspy/hyperspy#1794]
Since the removal of the "Lena" image from `scipy`, our examples in the user guide are out of date. The code of the examples has been changed to use `ascent()` instead of `lena()`, but the actual image files still show examples from the old code, which should be updated.
  
See, for example, [here](http://hyperspy.org/hyperspy-doc/current/user_guide/visualisation.html#plotting-several-images).

**Comment by magnunor** [comment]
We could setup the continuous integration system to automatically generate the figures, which I've done in Atomap: https://gitlab.com/atomap/atomap/blob/master/doc/images/make_test_data_figures.py

**Comment by sem-geologist** [comment]
why Lena got removed?

**Comment by jat255** [comment]
@magnunor that probably looks like the best (most robust) solution going forward. I'll look into that today.

@sem-geologist, there's a whole discussion here: http://article.gmane.org/gmane.comp.python.scientific.devel/19898

As I see it, there were two issues: (1) the image does not have a free copyright, and so could not be included in Debian because it was not compatible with GPL (I think); and (2) it is an image from a Playboy magazine, and so some people think it is one of those subtle ways of biasing against women participating in computer science and related fields. Either way, it's gone, so we should update our docs :)

**Comment by magnunor** [comment]
@jat255, sounds good! The automatic is really nice, since it removes yet another layer of hassle when updating the user guide. If you need more example, there are several in https://gitlab.com/atomap/atomap/tree/master/doc/images

**Comment by jat255** [comment]
@magnunor, does that script get run automatically when the docs are built? Or is it just another step you have to do? I'm trying to see where in the `sphinx` process I could put it. Maybe add a step to https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/doc/Makefile ?

**Comment by magnunor** [comment]
GitLab has a slightly different system, the relevant lines are here: https://gitlab.com/atomap/atomap/blob/master/.gitlab-ci.yml#L68

It is not the "cleanest" way, since we have to manually add each script to the yml-file. But works pretty well.

**Comment by ericpre** [comment]
Fixed in #1798.
