### ISSUE TITLE
Add support for MSA/MAS/AMMS Hyperspectral File format (HMSA)

### ISSUE THREAD

**Issue by jat255** [hyperspy/hyperspy#1795]
This issue should be a proposal and discussion space for the implementation of the MSA HMSA format that was recently announced by Nestor Zaluzec on the `hyperspy-users` mailing list. See the below copy of the email message:

**Sent by Nestor J. Zaluzec <nestor.zaluzec@gmail.com> at 9:36AM:**

> The updated MSA/MAS/AMMS Hyperspectral File format (HMSA)  has been finalized and has been submitted to ISO. This is an update to the original MSA file format which originally only handled single spectra.  This version, designed to promote vendor neutral file sharing, does images, spectra, hyper spectral data, and other multi-dimensional data sets.   It would appropriate to consider  adding  it to HyperSpy. 
>
> The full documentation is available on-line at:
>    https://www.microscopy.org/resources/scientific_data/
>    https://www.microscopy.org/resources/scientific_data/HMSA_Specification-20161100.pdf

>The MSA / MAS / AMAS HyperDimensional Data File (HMSA, for short) is intended to be a common format to permit the exchange of hyper-dimensional microscopy and microanalytical data between different software applications. The expected applications include:
>
>  * Hyper-spectral maps, such as electron energy loss spectroscopy (EELS), energy- dispersive x-ray spectrometry (XEDS), or cathodoluminescence spectroscopy (CL).
>  * ‘Hyper-image’ maps, such as pattern maps using electron backscatter diffraction (EBSD) or convergent beam electron diffraction (CBED).
>  * 3-dimensional maps, such as confocal microscopy, or focused ion beam (FIB) serial section maps.
>  * 4-dimensional maps, such as double-tilt electron tomography.
>  * Time-resolved microscopy and spectroscopy.
>
> In addition to storing hyperdimensional data, the HMSA file format is suitable for storing conventional microscopy and microanalysis data, such as spectra, line profiles, images, and quantitative analyses, as well as experimental conditions and other metadata. 
>
> Nestor Zaluzec
> *Chair of MSA Standards Committee*

**Comment by jat255** [comment]
My personal opinion is that we should try to support this format fully, including reading and writing. An official ISO standard is more likely to get buy-in from vendors, and I think we would do ourselves and the greater microscopy community a service by trying to support it. Thoughts?

**Comment by ericpre** [comment]
There is already an issue open on this, see hyperspy/rosettasciio#21. In short, there is already a pure python library implementing this, so it should be straightforward to do.
We should keep only one of the two issues open to avoid dispersing information.

**Comment by jat255** [comment]
Oh, look at that! I should have searched first, I suppose. I'll close this one in that case.
