### ISSUE TITLE
Units unchanged in metadata when using "hs.material.atomic_to_weight() on EDS quantification

### ISSUE THREAD

**Issue by CorentinLG** [hyperspy/hyperspy#1796]
The output of the s.quantification() function is a list and each has a title in its metadata of the type : "atomic percent of Al_Ka" for instance.

The function hs.material.atomic_to_weight(quantification) converts units, but the "title" of the resulting list remains unchanged and indicates atomic instead of weight%.

It can be confusing.

**Comment by k8macarthur** [comment]
Should be fixed in the pull request #1820

**Comment by ericpre** [comment]
Fixed in #1827.
