### ISSUE TITLE
Interactive region of interest initial plotting not correct

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#1805]
When using an interactive `Line2DROI`, the initial plot is not plotted correctly.

```python
import numpy as np
import hyperspy.api as hs

s = hs.signals.Signal2D(np.random.random((150, 150)))
s.plot(cmap='viridis')
line_roi = hs.roi.Line2DROI(x1=10, y1=10, x2=90, y2=90, linewidth=4)
line_roi.interactive(s, color='red')
```
Gives:
![line_roi_initial0](https://user-images.githubusercontent.com/1690979/35142719-0f9f0a82-fcf7-11e7-8efa-ee523373f52c.jpg)

After moving the ROI, it plots correctly:
![line_roi_initial1](https://user-images.githubusercontent.com/1690979/35142751-2b8eda38-fcf7-11e7-93d7-fe694176c7c4.jpg)

This mostly an annoyance in normal workflows, but it makes trying to generate user guide images from scripts for `Line2DROI` much more tedious: https://github.com/magnunor/hyperspy/blob/6b2d344867d83bdedcf9a770c37fbfab6fdd9163/doc/user_guide/images/get_line_profile_2d_signal_0.png

**Comment by ericpre** [comment]
Fixed in #1685.
