### ISSUE TITLE
align_zero_loss_peak ignores the `crop=False`

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#1809]
The following reproduces the bug:

```python

%matplotlib qt
from hyperspy.tests.signal.test_eels import TestAlignZLP

t = TestAlignZLP()
t.setup_method("")
s = t.signal.deepcopy()
s.align_zero_loss_peak(subpixel=False,calibrate=False, crop=False)

s.plot()
```

The result should be the following figure:
![screenshot from 2018-01-23 16-40-16](https://user-images.githubusercontent.com/989719/35284995-884675ac-005c-11e8-9593-f807c0ffd582.png)

But currently we get this one instead:

![screenshot from 2018-01-23 16-41-14](https://user-images.githubusercontent.com/989719/35284983-7e0939bc-005c-11e8-9dd3-318aefe200a8.png)

**Comment by ericpre** [comment]
Fixed in #1809.
