### ISSUE TITLE
freetype 2.6 conflicts with pyqt5.6

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#1811]
Therefore, it is not possible to install it in order to run the hspy mpl tests in an environment with the latest qt installed (default as required by anaconda-navigator). Could we use freetype 2.8 instead?

**Comment by ericpre** [comment]
I guess this should be possible now, since freetype 2.8 is available for the platforms that we need. If I remember correctly this was not the case a few months ago when I set it to 2.6 in #1760.
The baseline images will need to be updated.

**Comment by ericpre** [comment]
Fixed in #1814.
