### ISSUE TITLE
Colored and overlayed elemental maps

### ISSUE THREAD

**Issue by jdsugar** [hyperspy/hyperspy#1812]
I am trying to maker overlaid and colored elemental maps from eds data. Much like the very simple operations that vendor software performs where I pick an element pick a color and then make a layered image that has all the elements in it. When I use get_lines_intensity, I can create greyscale maps, but I can’t figure out how to change their color and overlay multiple maps. And, when I try to plot them separately from the get_lines_intensity command I get an error.  Does anyone have any suggestions for how to do this? Thanks.

**Comment by francisco-dlp** [comment]
There is a very old (maybe broken) function to overlay up to 3 images using the RGB channels, `plot_RGB_map`. You can import it as follows:

```python

from hyperspy.drawing.utils import plot_RGB_map
```

However, it is very limited. If you need something more powerful you could use directly matplotlib to overlay the images. See e.g. https://matplotlib.org/examples/pylab_examples/layer_images.html

The ``make_cmap``  from #1793 could help you with this.

I am sure that somebody else would have some more suggestions.

In  any case, it would be really nice to implement this feature is hyperspy. A possible syntax could be:

```python

hs.plot.plot_overlay_images((im1, "red", 0.3), (im2, "violet", 0.6))

```
where the 3rd argument is the weight or alpha parameter. Then one can imagine a ipywidgets GUI that enables changing the color and weight and nav index of the image interactively.

**Comment by tjof2** [comment]
See also #19: 
> *@stefano-m commented on 21 Sep 2011*
> It would be nice to be able to create a composite "RGB" image from more than just three components
> E.g. see:
> http://dip4fish.blogspot.com/2011/05/making-mfish-image.html

Updated mfish link: https://dip4fish.blogspot.com/2014/03/combining-five-images-into-one-rgb.html

**Comment by ericpre** [comment]
Done in #2599.
