### ISSUE TITLE
Remove spurious exec bits from csv and txt files

### ISSUE THREAD

**Issue by dhaneshsabane** [hyperspy/hyperspy#1816]
## Background

I am a Fedora contributor and one of the things I do is package software for Fedora. Hyperspy is on my to-do list of Python software to be packaged. 

## The issue

While creating a hyperspy package for Fedora, there are a bunch of csv and txt files which are interpreted as executable scripts.

## The reason

Turns out these files have their exec bit set due to which the packaging software throws a bunch of errors. 
You can have a look at how it reacts here: https://paste.fedoraproject.org/paste/Zyz4jjBjIhFRFYf~CjEhIQ

**Comment by dhaneshsabane** [comment]
I believe this to be a 'low-hanging-fruit' kind of job. I would like to help and submit a pull request for the same if I can get some help.

**Comment by francisco-dlp** [comment]
@Dhanesh95, thanks for reporting the issue. Feel free to send a PR to fix the issue by branching for RELEASE_next_patch and sending your PR to that branch. If you need any guidance on the process don't heasitate to ask here on in the gitter chat https://gitter.im/hyperspy/hyperspy .

**Comment by dhaneshsabane** [comment]
@francisco-dlp Thanks for the quick response! Also, there are a couple of `__init__.py` files which, I believe, should not contain the interpreter script. Can I include the fix in the same pull request or shall I open up a new issue for the same?

**Comment by francisco-dlp** [comment]
It's fine to include them in the same PR as long as you describe the changes and the motivation in the PR.

**Comment by francisco-dlp** [comment]
@Dhanesh95, does #1892 fixes the exec permissions and sha-bang issues?

**Comment by ericpre** [comment]
@Dhanesh95, closing this, since it is fixed in #1892.

**Comment by dhaneshsabane** [comment]
@ericpre @francisco-dlp 

I didn't get the time to check if the package builds correctly with the latest commit, but I'll trust you guys on this one. Will come back here if I still run into issues. Thanks for fixing this!

**Comment by ericpre** [comment]
Sure, please let us know if it needs some fixes! Being a fedora user, I am looking forward to hyperspy to be package in Fedora. Also when it is done, it would be good to update the documentation, so please let us know or make a PR. Thanks!
