### ISSUE TITLE
Loading data: specify dataset

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#1823]
Many file formats can contain several dataset in the same file, for example EMD-style HDF5 files.

Currently, when loading EMD files which contain several datasets a list of all the datasets is returned. However, in many cases it would be convenient to be able to specify the exact dataset you want to access. 

This is especially useful when working with files which contain several large datasets, where loading all of them would make your computer run out of memory, but loading one of them would work fine. This too-large-file issue can be avoided by using `lazy=True`, but that can be a bit unwieldy.

So it would be nice to have some kind of argument (`dataset_name`?), which could be used to specify the exact dataset.

```python
import hyperspy.api as hs
s = hs.load("afile.emd", dataset_name='adatasetname')
```

**Comment by ericpre** [comment]
Done in #1963.
