### ISSUE TITLE
Saving .tiff from FEI velox emd files

### ISSUE THREAD

**Issue by CorentinLG** [hyperspy/hyperspy#1829]
Trying to save STEM-HAADF FEI velox STEM images to '.tif'.

s.save('MyFile', extension = 'tif') returns images with the wrong contrast, as if most of the information had disappeared. This does not happen when saving in .png for instance. 

Any idea?

**Comment by ericpre** [comment]
It have just tried it, it seems to work perfectly.
Is it possible that the software you are using to read your image doesn't support properly the tif format? Have you tried with ImageJ/Fiji? Otherwise could you share the file to see if we can reproduce?

**Comment by CorentinLG** [comment]
So this is the image as saved on the microscope and as it appeasr when saved in .png:
![figure_haadf_signal](https://user-images.githubusercontent.com/23366094/36028073-ea72de34-0d9d-11e8-9899-55b4a47529df.png)

And this is is what I get after saving in .tiff
![test](https://user-images.githubusercontent.com/23366094/36028136-28d65336-0d9e-11e8-96f5-504c85f1db01.jpg)

Actually, I just realized that the info is not exactly, but that the contrast is simply drastically extended. 
So it seems to be the contrast info which is lost while saving in tiff....

**Comment by ericpre** [comment]
Please compare the actual values in both images (in hyperspy and your other software with the tiff file), they should be the same, if there is no bug. It is very likely that this is just a matter of display, which relies on the software you are using.

**Comment by CorentinLG** [comment]
I agree it must be a display thing, but both photoshop and window viewer display these FEI/hyperspy Tiff images with no constrast while they do not for other tiff images - and neither for  FEI png images actually. So there is likely something specific to them. Maybe a 8 vs. 16 bit issue? Or the way contrast is recalled from FEI image metadata when saving into tiff??

**Comment by francisco-dlp** [comment]
Standard image processing software don't usually support scientific formats. Maybe you could try imagej?

**Comment by CorentinLG** [comment]
You re right. ImageJ opens it allright.
A bit weird, but most likely not an hyperspy issue then...
