### ISSUE TITLE
Different boundaries for parameters with number of elements >1

### ISSUE THREAD

**Issue by ZanettaPM** [hyperspy/hyperspy#1834]
Boundaries for parameter with number of elements > 1 (as `coefficients` in polynomial background for example) are just repeated for the different elements.  

here:  https://github.com/hyperspy/hyperspy/blob/137cfdadd2a7212f5104adb20fdd8c68a99af19a/hyperspy/component.py#L426

It could be important to be able to set different boundaries for the different elements, Notably for background components.

**Comment by ericpre** [comment]
Closing since the Polynomial component have been rewritten and this is now possible to bound the coefficient values independently.
