### ISSUE TITLE
Postdoc in Machine Learning

### ISSUE THREAD

**Issue by jeinsle** [hyperspy/hyperspy#1836]
Hi All-

I know this is a little unusual, but I have been asked to contact this community to see if any of the contributors here would be interested in the following postdoc in Japan. 
 
I am currently a post-doc in the Cambridge Nanopalemagnetism project and use machine learning for mineral identification purposes. 

Our group is part of a wider network which applies principal component analysis to pull apart magnetic components in First Order Reversal Curves(FORC).  Current applications of PCA often result in non-physical endmembers and this project looks to help address this through the development of more advanced machine learning approaches.   This role will be a great experience for someone looking to develop more advanced coding skills and apply machine learning to a verity of challenging physical problems.  Contact me, Prof Richard Harrison(Cambridge) or Prof Andrew Roberts(ANU) or Dr Hirokuni Oda (Institute of Geology and Geoinformation) if you have more questions.   Bellow is the full project description:

**************************************************************************************************************

> POSITION DESCRIPTION

The appointee will work a part of a team led by Professor Andrew Roberts and Dr Hirokuni Oda on an international project funded by the Japanese National Institute of Advanced Industrial Science and Technology (AIST); "Development of machine learning approaches in magnetic recording and climate research". 

Position Dimension & Relationships: 
The appointee will contribute to the aims of the project, which involves the application of machine learning to automated processing of experimental rock magnetic data. The appointee will have a specific role within a larger team, which will involve the development of Bayesian-based machine learning techniques and the design/deployment of processing software on a cloud computing platform. Additionally, the appointee will be expected to contribute collaboratively to the broader endeavours of the international research group.

Role Statement:

The appointee will be expected to:

undertake research under the direction of Professor Andrew Roberts and Dr Hirokuni Oda that contributes to the aims of the project, with a view to the development of new machine learning software and contributing to the publication of papers in international refereed journals;
collaborate with project team members in developing new machine learning techniques to analyse rock magnetic data;
lead the design and development of cloud-based processing software to deploy new data analysis techniques in a form suitable for adoption by the broader scientific community;
take responsibility for their own workplace health and safety and not willfully place at risk the health and safety of another person in the workplace; and
other duties as allocated by the supervisors consistent with the classification of the position.
SELECTION CRITERIA:

A Ph.D. in computer science, machine learning, mathematics, statistics or related discipline, with a track record of independent research as evidenced, for example, by publications in peer-reviewed journals and conference presentations.
 Evidence of an ability to prosecute innovative research in the field of machine learning.
A track record of user-friendly software design, development and maintenance, with a specific focus on deployment on cloud-based platforms.
Excellent oral and written English language skills with a demonstrated ability to communicate and interact effectively with a variety of researchers in an international and cross-disciplinary academic environment and to foster respectful and productive working relationships with staff, students, and colleagues at all levels.
A demonstrated understanding of equal opportunity principles and a commitment to the application of these policies in a University context.

**Comment by magnunor** [comment]
I don't think stuff like this is appropriate for the issue tracker: it should be used for things like development discussions and bug reports.

The gitter chat (might) be more appropriate, since it is more informal.

**Comment by jeinsle** [comment]
umm fair enough and sorry for inappropriateness.  though as this was the only place I knew of related to hyperspy.  a link to the correct place would be useful. cheers

**Comment by thomasaarholt** [comment]
Personally I would have let this stay open for a little while, since the "harm" was already done :)
I know this is way late (I didn't see this because the issue was closed), but here is the link for the gitter chat, which indeed is the more appropriate place:
https://gitter.im/hyperspy/hyperspy

Project sounds very interesting! I hope they found someone!
