### ISSUE TITLE
Multiple fit

### ISSUE THREAD

**Issue by MurilooMoreira** [hyperspy/hyperspy#1837]
Hello, my first time here making questions. Nice to meet you guys, I am working with EDS data and I fitted a reference spectrum with hyperspy. I am tryng now apply the parameters(sigma and centre) of this reference spectrum in other spectrum into a loop  for the quantification of multiple spectras. I found the function  set_parameters_value() but, I don't know exactly how to use. I have multiple lines to set the sigma and the centre, someone can help me please?

Thank you,
Murilo

**Comment by ZanettaPM** [comment]
Hi @MurilooMoreira if you have other questions, the best place for this is here : https://gitter.im/hyperspy/hyperspy

For your question i think that `s.get_calibration_from()` should work cause the sigma and the center will depend of your resolution at MnKa which is indicated in the metadata and of your scale/shift. etc.

**Comment by thomasaarholt** [comment]
@MurilooMoreira How are you doing with this? I didn't fully understand your question, but I suspect you've learnt a lot about hyperspy in the past three weeks :) Do you still need help?

**Comment by MurilooMoreira** [comment]
@thomasaarholt Hi, 
No, I don't need help with this anymore, thank you. :+1: 

@ZanettaPM thank you for your help.

**Comment by thomasaarholt** [comment]
Then you can probably close the issues, button below :)
