### ISSUE TITLE
discussion: zlib'ing test files

### ISSUE THREAD

**Issue by sem-geologist** [hyperspy/hyperspy#1838]
during discussion #1833 , the test file compression suggestion was raised.

I thought about that for a while. Initially I was enthusiastic about idea of shrinking size of hyperspy, after some thinking I came to conclusion that it is not only little useful, but even brings some dissadvantages.

So why the idea of custom compressing test files is not universally good?
* It would not positively affect source distributions, as they are distributed in compressed formats.
* it would not affect git as during `pull`, `checkout`, `push` and etc, `git` automatically compresses/decompresses. Actually unnecesarry zipping puts more overhead to git (see some arguiments in [https://www.reddit.com/r/git/comments/1ydvpg/does_git_compress_files_efficiently/](https://www.reddit.com/r/git/comments/1ydvpg/does_git_compress_files_efficiently/)
* I believe NSIS installer zlibs the files too.

(summarising the above: "onion"-like zlibing gives no benefits, but only brings the overhead).
The only pros of single file compression I can see is when file is too big for `github`, where compression is able to shrink the size enought (that however depends very much from the files, some are impossible to fit into these limits), and that is the case for some edax files in hyperspy test. None of the bcf files in tests gets near limit of 50MB, and those which are published in tests are very minimal examples specifically gathered to be as minimal as possible.
So the only situation, where we would want that test files would take little space as possible is inhyperspy installation on user pc. But I don't think this is kind of software which should worry user about additional 100MB (which takes only disk memory, no impact for RAM), while software is intended to work with hundreds of GB of data. In case of some rare cases of lets say rasppberry-pi, test folder can be just deleted after installation (and running tests). For other cases customally zlibing files just brings overhead for testing code, CI and of course wastes our time (every time we will need to implement one more test file, we will need those extra steps with manual rezipping).

**Comment by magnunor** [comment]
I think having them compressed is useful. For example, in `fpd` the uncompressed test files are 400+ MB, while compressed they're only 25 MB: https://gitlab.com/fpdpy/fpd/tree/master/fpd/tests/file_datasets

How much overhead is it uncompressing the files during CI?

I also think having as small as possible user install is nice, as often the python libraries are installed on the operating system drive, which is separate from the data storage drive. This operating system drive is often much smaller, due to being an SSD.

**Comment by sem-geologist** [comment]
The reduction of user install space is the only benefit. CI will get overhead (git will get overhead). Every CI test cycle will get overhead. You as developer will get overhead if you want to add or change test files. Fine if you have 400+ MB file, that is probably the only option. But the real question should be is this 400+MB file really necessary, and lets say 40MB one would not give the same testing medium?

**Comment by tjof2** [comment]
Indeed rather than compressing and uncompressing on every cycle, the files should just be as small as possible for the test. Closing in favour of #2048 to consolidate the issues.
