### ISSUE TITLE
EELS model components scaled incorrectly due to convolution with low-loss

### ISSUE THREAD

**Issue by theodoho** [hyperspy/hyperspy#1847]
When creating an EELS model, if I convolve the high-loss signal with the low-loss signal, the model components are scaled incorrectly. I tried to normalize the low-loss, but the problem persists.

In [this](https://nbviewer.jupyter.org/github/theodoho/Gaussian_Amplitude/blob/master/EELS%20fine%20structure%20analysis%20Mn-L%20Sum%20and%20Ratio%203.ipynb) notebook, I do not convolve the high-loss with the low-loss, **cell 14**, and the model components are consistent with the actual model and data, as can be seen in **cell 38**.

In [this](https://nbviewer.jupyter.org/github/theodoho/Gaussian_Amplitude/blob/master/EELS%20fine%20structure%20analysis%20Mn-L%20Sum%20and%20Ratio%20Convolved.ipynb) notebook, I convolve the high-loss with the low-loss, **cell 14**, and the model components are clearly not consistent with the actual model and data, as can be seen in **cell 38**. They are way too low.

In both cases I plot the normalized white-line sum (**cell 45**) and the white-line ratio (**cell 46**). The qualitative trends are the same, but the absolute values change; the change is slight for the white-line ratio and very big for the normalized white-line sum.

**Comment by francisco-dlp** [comment]
@theodoho, the way in which HyperSpy displays the model is confusing and, to make things worst, it is explained nowhere. However, internally it does the right things. The confusion comes from the fact that the model line displayed is the result of convolving the model with the low-loss, while the individual components displayed using e.g. ``enable_plot_components`` are displayed non-convolved. The right thing to do would be to display the model components also convolved when the model is convolved as it is your case. But, in any case, there is no inconsistency in the actual data: those are the right results of fitting your model to the data.

**Comment by ericpre** [comment]
A couple of weeks ago, I make a branch to fix plotting with convoluted component and if I remember correctly it just needs to improve the documentation to explain what a convolution does... because when people are going to look at the value of the parameters, they will be still surprised to see that the value is small when convoluting with a high intensity signal...

**Comment by francisco-dlp** [comment]
Fixed in #1851
