### ISSUE TITLE
setup.py cleanup bugs?

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1848]
Trying to work out #1575 and #1585, I came across this little line of code:
https://github.com/hyperspy/hyperspy/blob/e64a7e01d0923dbb174eecb54b4eb955548d9828/setup.py#L101

When checking out / installing hyperspy, I always get this error:
```
rm: cannot remove 'C:\Users\thomasaar\hyperspy\hyperspy\io_plugins\unbcf_fast.c*': No such file or directory
```
I'm wondering if `'.c*'` perhaps should be `'*.c'` or perhaps even just `'.c'`? Or maybe it's an incorrectly placed wildcard? The file `unbcf_fast.c` gets correctly removed (and re-created) when I change to '.c'.

In addition, I always get the following line:
```
rm: cannot remove 'C:\Users\thomasaar\hyperspy\hyperspy\io_plugins\unbcf_fast.cpython-*.pyd': No such file or directory
```
In my folder (on Windows), `unbcf_fast.cp36-win_amd64.pyd` exists, but `unbcf_fast.cpython-*.pyd` does not.

**Comment by sem-geologist** [comment]
cough cough... this ugly thing is my take on the rare problem when checking out in between the branches with newly introduced c or c++ modules. It was useful when bcf cython code for bcf was introduced, as it was needed to solve issue of not cleaning up (leaving c and compiled so/pyd files) when checking out to older branch. It could be useful in the future is some more cython/c/c++ code would get involved.  Also it partially was taking care of making sure that re-cythonization takes place in between checkouts. Shortcomings are listed in #1754 . I looked into scikit-image and I see there  is some different hack which I see as just moving from one hack to other complicated hack. I can't remember clearly, but I think I am waiting for cython to bring in some kind of clean way to deal with our and scikit-image cases. Probably thats why I am waiting.

Now commenting your points:
1. `.c*` is for being future-prepared as it is possible to use `.c` and `*.cpp` files. The feature is useless at the moment, as only limited .c files are in hyperspy (unbcf_fast).
2. `unbcf_fast.cpython-*.pyd` clearly fails to catch  `unbcf_fast.cp36-win_amd64.pyd` – probably it should be changed into `unbcf_fast.*.pyd`

**Comment by thomasaarholt** [comment]
Thanks for bringing #1754 to my attention :) I'm very surprised that there isn't a cleaner way of doing this, but then again, that's often the way it is!

As it currently stands, `unbcf_fast.c` is not caught. What is the reason for that?

**Comment by sem-geologist** [comment]
it was reported, and I saw with my own eyes, that post-checkout-hook sometimes gets tripled, quadrupled and even worse, it can then try to delete the file a few times.

**Comment by tjof2** [comment]
Is this still an issue @thomasaarholt ?

**Comment by tjof2** [comment]
I don't think it is because I think it may date from a time when some branches didn't have the Cython code in them. Since it's likely now that most branches will be up-to-date, this is unlikely to still be an issue.
