### ISSUE TITLE
mrcz breaks hyperspy if extras not installed

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1849]
As I discovered just now when pulling RELEASE_next_minor to my local master.
The issue is that I don't have blosc (`conda install blosc` for anyone coming here).

However, since mrcz is considered an "extra" according to setup.py, it should not fail on import.

**Edit: I thought blosc was all that was needed, but I ended up having to use `pip install mrcz`. It is indeed listed correctly, in setup.py**

```python
>>> import hyperspy.api as hs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\thomasaar\hyperspy\hyperspy\api.py", line 1, in <module>
    from hyperspy.api_nogui import *
  File "C:\Users\thomasaar\hyperspy\hyperspy\api_nogui.py", line 75, in <module>
    from hyperspy import signals
  File "C:\Users\thomasaar\hyperspy\hyperspy\signals.py", line 42, in <module>
    from hyperspy.signal import BaseSignal
  File "C:\Users\thomasaar\hyperspy\hyperspy\signal.py", line 36, in <module>
    from hyperspy import io
  File "C:\Users\thomasaar\hyperspy\hyperspy\io.py", line 32, in <module>
    from hyperspy.io_plugins import io_plugins, default_write_ext
  File "C:\Users\thomasaar\hyperspy\hyperspy\io_plugins\__init__.py", line 22, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc, mrcz, ripple,
  File "C:\Users\thomasaar\hyperspy\hyperspy\io_plugins\mrcz.py", line 19, in <module>
    import mrcz as _mrcz
ModuleNotFoundError: No module named 'mrcz'
```

**Comment by thomasaarholt** [comment]
Closed per edit in issue.

**Comment by jat255** [comment]
FWIW, I just experienced this as well. I wonder if there should be a mailing-list or some other type of notification to people that are installed from source when requirements change... I'm not sure of the specifics how that would work, but it could prevent people from having to debug this sort of thing.

**Comment by ericpre** [comment]
This will happen only when switching branch and if the mrcz dependency is not installed.
To be honest, I am not convinced that an announcement to contributors is necessary, because the error message is fairly clear and if you are using the development version and switching between branches, it would be fair to assume that you are experience enough to sort this out easily?!
I agree that it does happen once in a while...

And to make clear, mrcz is a dependency, only blosc is optional.

**Comment by thomasaarholt** [comment]
I think it's ok to leave as is. Worst case, someone like me creates a closed github issue about it, and then it's got a searchable solution.
