### ISSUE TITLE
Sugestion about the documentation of Kfactors used in quantification()

### ISSUE THREAD

**Issue by MurilooMoreira** [hyperspy/hyperspy#1850]
Hi, just mentioning here as discussed in the gitter chat, I don't know if the documentation is clear enough about the Kfactors which should be used as input in the quantification() function. The Kfactors must be calibrated for weight even when the output of the quantification() function is in atomic percent. I don't think this information is immediately available in the documentation.

Other suggestion is implement a Cliff-Lorimer Kfactor calibration function. 

Thank you,
Murilo

**Comment by francisco-dlp** [comment]
I've marked it as bug as this is a documentation flaw that can lead to wrong results the same was as a code bug would.

**Comment by thomasaarholt** [comment]
@MurilooMoreira Out of curiosity, what detector were you using k-factors for, and where did you get them from? I've been really wanting to get k-factors for our Bruker detector, but have no idea where to start.

**Comment by CorentinLG** [comment]
@MurilooMoreira  : Textbooks on EDS quantification have defined k-factors from weight percent.
besides, I am not sure what you mean by cliff-lorimer calibration function?

@thomasaarholt : In theory, k-factors are provided by the detector constructor. A k-factor includes mainly 3 parameters (the cross section of a given x-ray line, the detector geometry with respect to the sample, and the efficiency of the detector as a function of energy).
The first parameter is known, but the last one is generally kept secret by the constructor. Annoying. 
In Esprit and Velox, there are default values provided. 
The alternative is to measure them yourself using standards. Quite time consuming....I did it for the Super-X on a themis and found a good agreement with values provided by Esprit, except for light elements (<1 keV).

**Comment by MurilooMoreira** [comment]
@thomasaarholt  I am using X-max SDD from Oxford Instruments and the microscope is JEM 2100F 200kV. But I am not using the kfactor from the software. I am using a standard thin film with composition already known to obtain the kfactor.

@CorentinLG  What I tried to say with cliff-lorimer calibration function is a function implemented into hyperspy to you obtain the kfactors from your standards. Actually isn't something really necessary, is very simple to do yourself, it's just an idea to make all the quantification steps inside of hyperspy functions.

**Comment by k8macarthur** [comment]
@thomasaarholt I think with Espirit you press the quant button and then either it shows you k-factors from the results or you can work them out from the results because you have intensities and compositions.

@MurilooMoreira this sounds like a simple line in the documentation and the docstrings would suffice to clarify the units of each quantification method?

**Comment by k8macarthur** [comment]
A Cliff-lorimer calibration function should I think be put into an example notebook. I have already written one for calculated cross sections from a wedge sample here: https://github.com/k8macarthur/hyperspy_workbooks/tree/master/EDX%20Quantification

#1780 might also be of interest.

**Comment by ericpre** [comment]
Documentation improved in #2680.
