### ISSUE TITLE
Loading .emd: AssertionError: Dataset location is ambiguous!

### ISSUE THREAD

**Issue by hentr** [hyperspy/hyperspy#1887]
Hi, I am trying to load STEM videos recorded with Velox (last updated in January, I think) as .emd files. All my files gives the same error, here's a [sample file](https://polybox.ethz.ch/index.php/s/QwCBfdgZaTRjyyf).

`s = hs.load('STEM HAADF 1613.emd')` gives: 

``` 
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-14-bbbc643c53d6> in <module>()
----> 1 s = hs.load('STEM HAADF 1613.emd')

~\AppData\Local\Continuum\Anaconda3\lib\site-packages\hyperspy\io.py in load(filenames, signal_type, stack, stack_axis, new_axis_name, lazy, **kwds)
    241             objects = [load_single_file(filename, lazy=lazy,
    242                                         **kwds)
--> 243                        for filename in filenames]
    244 
    245         if len(objects) == 1:

~\AppData\Local\Continuum\Anaconda3\lib\site-packages\hyperspy\io.py in <listcomp>(.0)
    241             objects = [load_single_file(filename, lazy=lazy,
    242                                         **kwds)
--> 243                        for filename in filenames]
    244 
    245         if len(objects) == 1:

~\AppData\Local\Continuum\Anaconda3\lib\site-packages\hyperspy\io.py in load_single_file(filename, signal_type, **kwds)
    284                                 reader=reader,
    285                                 signal_type=signal_type,
--> 286                                 **kwds)
    287 
    288 

~\AppData\Local\Continuum\Anaconda3\lib\site-packages\hyperspy\io.py in load_with_reader(filename, reader, signal_type, **kwds)
    293     lazy = kwds.get('lazy', False)
    294     file_data_list = reader.file_reader(filename,
--> 295                                         **kwds)
    296     objects = []
    297 

~\AppData\Local\Continuum\Anaconda3\lib\site-packages\hyperspy\io_plugins\emd.py in file_reader(filename, log_info, lazy, **kwds)
    407 def file_reader(filename, log_info=False,
    408                 lazy=False, **kwds):
--> 409     emd = EMD.load_from_emd(filename, lazy)
    410     if log_info:
    411         emd.log_info()

~\AppData\Local\Continuum\Anaconda3\lib\site-packages\hyperspy\io_plugins\emd.py in load_from_emd(cls, filename, lazy)
    321         # One node should remain, the data node (named 'data', 'signals',
    322         # 'experiments', ...)!
--> 323         assert len(node_list) == 1, 'Dataset location is ambiguous!'
    324         data_group = emd_file.get(node_list[0])
    325         if data_group is not None:

AssertionError: Dataset location is ambiguous!

```

Help is much appreciated :)

**Comment by ericpre** [comment]
What version of hyperspy are you using? Velox emd file is not supported in the current release version (1.3), in the meantime, you can use the release_next_minor branch or a pre-release version (1.4-beta).

**Comment by hentr** [comment]
I was using 1.3, it works with 1.4-beta. However, the loading is awfully slow with longer/larger videos. 

Running
```
tic = time.time()
s_test = hs.load(file)
name = os.path.splitext(os.path.basename(file))[0] #takes the name of the file without the file extension
s_test.save(name+'.tif', overwrite=True)
toc = time.time() - tic
print(toc)
```

for series of different sizes and amount of frames gives:
1 frame, 1024x1024, 2mb - 0.2 sec
17x512x512, 8mb - 1 sec
50x512x512, 25mb - 2 sec
35x1024x1024, 70mb - 109 sec
50x1024x1024, 100mb - 162 sec
100x1024x1024, 200mb - 320 sec

difference between the 25mb and 70mb is ~50x when it should be ~3x?

**Comment by ericpre** [comment]
Yes, indeed, we have noticed that that loading stack of images is slow.... If you are keen to improve it, I would suggest that you try to find a faster way to open it with h5py to avoid any overhead. It is quite likely that accessing the data with h5py is the cause of the performance issue here.

**Comment by ericpre** [comment]
@hentr, #1934 fixes the perfomance issue that you reported here.

**Comment by hui-cc** [comment]
Hi, @hentr I downloaded the pre-release version (1.4-beta) zip. I tried to install it by using the command line python setup.py install, but one error occurred "[WinError 5] Access is denied: 'C:\\Users\\huchen\\AppData\\Local\\Continuum\\anaconda3\\Scripts\\jupyter.exe". Any suggestions to solve this issue? Thanks a lot.

**Comment by ericpre** [comment]
@hui-cc, as the error message says, this seems to be a right issue.
Installing from source can be more complicated than the recommended way of installing hyperspy using conda or the winpython based bundle. Therefore, it requires more python experience and also to be comfortable with installing python package "manually".
If you can't solve your right access issue and you still want to have the velox emd reader, you should use the bundle installer, as it is the easiest way of installing hyperspy. Alternatively, you can wait for the next minor release in a couple of weeks and you will be able to install it using the conda anaconda.

**Comment by hui-cc** [comment]
@hentr I succeeded installing HyperSpy-v1.4-beta-Bundle-Windows-64bit.exe, thanks.
