### ISSUE TITLE
map() can return a ragged "signal of signals" but this object can't be saved with hyperspy

### ISSUE THREAD

**Issue by dnjohnstone** [hyperspy/hyperspy#1889]
The hyperspy map() method can handle the case where a different length output is returned by the function at each navigation position. The object returned in such a case is a "Signal of Signals", which is a bit unusual and I suspect this functionality has not been used that much(?).

It seems that this object cannot be saved as a hdf5 with the current save function due to the steps in approximately line 554 in hspy.py because the shape of the data is confusing.

**Comment by dnjohnstone** [comment]
Short term I'm getting round this by saving the ragged_signal.data with numpy then reloading that and shoving it back in a Signal class, which is ok but a bit clunky.

**Comment by ericpre** [comment]
Can you please provide a minimal example?

**Comment by ericpre** [comment]
http://docs.h5py.org/en/stable/special.html#arbitrary-vlen-data

**Comment by ericpre** [comment]
Fixed in #2196.
