### ISSUE TITLE
issue of gui_traitsui when load hyperspy

### ISSUE THREAD

**Issue by Anneyuner** [hyperspy/hyperspy#1898]
WARNING:hyperspy_gui_traitsui:The TkAgg matplotlib backend is not supported by the installed traitsui version and the ETS toolkit has been set to null. To set the ETS toolkit independently from the matplotlib backend, set it before importing matplotlib.
WARNING:hyperspy_gui_traitsui:The traitsui GUI elements are not available.

I always have this warning when load hyperspy. How to solve that?
It was installed in windows.

**Comment by ericpre** [comment]
The warning tells you to use a matplotlib backend supported by traitsui and to set it before import hyperspy, that means:

```python
%matplotlib qt
import hyperspy.api as hs
```
This is explained in the [getting started](http://hyperspy.readthedocs.io/en/stable/user_guide/getting_started.html) part of the documentation.

**Comment by jat255** [comment]
I wonder, would it be possible to detect this during our import through some sort of `try` block, and output a more useful warning message? It could help with usability (especially for new users)...

**Comment by jat255** [comment]
In my experience, this is a common mistake for new users. Maybe we either add a link to [here](http://hyperspy.readthedocs.io/en/stable/user_guide/getting_started.html#starting-hyperspy-in-the-notebook-or-terminal) or explicitly show and example of loading the `qt` backend in [this](https://github.com/hyperspy/hyperspy_gui_traitsui/blob/master/hyperspy_gui_traitsui/__init__.py#L62-L66) warning?

**Comment by ericpre** [comment]
Sure, the content of the warning can always be improved and it could be possible to write a longer warning with more explanation, basically repeating the user guide. However, considering that users don't always read the user guide, I am not convinced that it will be really useful. :confused:

**Comment by ericpre** [comment]
Maybe just adding a link to the user guide would be beneficial/enough without making the warning too long or too complicated?
http://hyperspy.readthedocs.io/en/stable/user_guide/getting_started.html

**Comment by ericpre** [comment]
Done in https://github.com/hyperspy/hyperspy_gui_traitsui/pull/13.
