### ISSUE TITLE
SpanROI is (left, width) not (left, right)

### ISSUE THREAD

**Issue by erh3cq** [hyperspy/hyperspy#1906]
For SpanROI the arguments for SpanROI are not (left, right) as the documents suggest. They are (left, width) as defined by the range widget in \hyperspy\hyperspy\drawing_widgets\range.py. BUT, SpanROI checks to make sure right>left, so you have to have width>left.

**Comment by francisco-dlp** [comment]
For me it seems to works as expected:

```python
>>> import hyperspy.api as hs
>>> s = hs.signals.Signal1D(np.arange(100))
>>> r = hs.roi.SpanROI(10, 11)
>>> r(s).data
array([10])
```

If it was `(left, width)` the result would be `array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])`

**Comment by ericpre** [comment]
As far I can tell, the SpanROI works and is documented (in both user guide and docstring) as expected. It very likely that you get confused between the widget and the roi.

You can use the example from the user guide to convince yourself:
http://hyperspy.readthedocs.io/en/stable/user_guide/signal1d.html?highlight=spanroi#cropping

Closing this for now, feel free to reopen if there is something wrong.
