### ISSUE TITLE
Autogenerated API doc in RtD

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#1908]
Currently, the API docs are not available in HyperSpy's RtD documentation. In https://github.com/rtfd/readthedocs.org/issues/1139#issuecomment-312626491 there is the code that we need to fix this.

**Comment by jat255** [comment]
@francisco-dlp @ericpre this is still an issue. The API docs are empty, currently (for example the [EDS](http://hyperspy.org/hyperspy-doc/current/api/hyperspy._signals.eds.html) page). Running `make html` on my system generates the docs as expected, so perhaps this is a RtD problem?

**Comment by jat255** [comment]
In the [latest build](https://readthedocs.org/projects/hyperspy/builds/8220537/) on RtD, there are a number of repeated errors:

```
WARNING: autodoc: failed to import module 'hyperspy._components.arctan'; the following exception was raised:
No module named 'numpy'
WARNING: autodoc: failed to import module 'hyperspy._components.bleasdale'; the following exception was raised:
No module named 'numpy'
WARNING: autodoc: failed to import module 'hyperspy._components.eels_cl_edge'; the following exception was raised:
No module named 'numpy'
WARNING: autodoc: failed to import module 'hyperspy._components.eels_double_power_law'; the following exception was raised:
No module named 'numpy'
WARNING: autodoc: failed to import module 'hyperspy._components.eels_vignetting'; the following exception was raised:
No module named 'numpy'
WARNING: autodoc: failed to import module 'hyperspy._components.error_function'; the following exception was raised:
No module named 'numpy'
WARNING: autodoc: failed to import module 'hyperspy._components.exponential'; the following exception was raised:
No module named 'numpy'
.....
WARNING: autodoc: failed to import module 'hyperspy.drawing.widgets'; the following exception was raised:
No module named 'matplotlib'
......
WARNING: autodoc: failed to import module 'hyperspy.tests.drawing.test_plot_signal1d'; the following exception was raised:
No module named 'traits'
......
```

The build is listed as "succeeding", but the API docs aren't actually getting generated. Presumably we have to tell RtD somehow to install these dependency modules in its environment?
