### ISSUE TITLE
RtD docs build failing

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#1911]
See https://readthedocs.org/projects/hyperspy/builds/7036680/

**Comment by sem-geologist** [comment]
oh heck... deja vu...

**Comment by sem-geologist** [comment]
I think this is time for me to get the mess with those hooks sorted out...

**Comment by francisco-dlp** [comment]
@sem-geologist, what about solving this by i) removing the hook or ii) making it detect if `unbcf_fast.pyx` has changed and print an informative warning if yes with instructions on how to rebuild the extension if wanted.

I am for i) because fiddling with people's hooks is probably a bad idea in general.

**Comment by francisco-dlp** [comment]
Option 1) "implemented" in #1919.

**Comment by ericpre** [comment]
It would still convenient to have an informative message when appropriate during a checkout.
