### ISSUE TITLE
Releases v1.4 and v2.0 plan

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#1912]
There are plenty of new features already in Rnm and many more awesome PRs ready for review. Also, after discussing about it for years, it is about time to split HyperSpy i.e. release HyperSpy v2.0.

I suggest the following release plan:

* Release v1.4 in late May with as many of the PRs already submitted merged as possible. In other words, from now until the release of v2.0 *we should focus our energies in reviewing and finishing the current PRs rather than on implementing new features*. This is because the PRs that don't make it into v1.4 will need to be resubmitted to HyperSpy or one of its new extesions.
* Start working on splitting HyperSpy soon after v1.4 with the objective of releasing HyperSpy v2.0 and its multiple subpackages in late June. During this period we should display a warning against forking HyperSpy and submitting PRs not related to the split.

I will create a v1.4 milestone to track all the target PRs for v1.4. Feel free to add (or suggest adding) PRs that you consider that are important enough to make it without a doubt into v1.4 to the v1.4 milestone.

Does it sound good?

**Comment by k8macarthur** [comment]
Great to have a timeline to work towards. At the latest it might be useful to have Hyperspy fully split before M&M in August. We want people to be able to find the code well after the conference if we point them in that direction.

**Comment by ericpre** [comment]
Yes, this sounds a good plan. I expect to have a busy June month so I can't make sure that I will able to help much as I would like to.

**Comment by magnunor** [comment]
Sounds good! Things are finally getting a little less busy, so I'll try to get my Release_next_minor pull requests finished for the 1.4 release.

**Comment by jat255** [comment]
@ericpre This one can be closed too?
