### ISSUE TITLE
Discussion: Apodization/window implementation

### ISSUE THREAD

**Issue by woozey** [hyperspy/hyperspy#1917]
As I promised to @thomasaarholt I'm working on implementation of apodization window in particular to remove streaks in FFT to make it look publication ready. I faced several design questions which hopefully you can help me to answer:

1. So far HS has 1D and 2D signals. Is it envisioned to work with higher dimensionality signals? Shall I aim for apodizing higher dimensional signals?
2. Ones I implement apodisation it will probably make sense putting it in a general method of Signal1D and Signal2D (or BaseSignal), i.e. not only an optional parameter in FFT method. So the question is if you think it will be useful or should it be kept as a part of FFT only?
3. Term apodization is originally coming from optics, whereas in signal processing it is can be also called window (function). What shall we call the method/parameter? Window? Apodization?
4. There are thousands of different apodization windows available. Most of them are part of scipy so it will be straight forward to add several of them. In case if I implement apodization outside FFT as a method of BaseSignal for example, shall I create a separate method for each window function (e.g. `s.hann_window`, `s.tukey_window`) or put them all in one (`s.apply_apodization('hamming')`)? Obviously disadvantage of first one is overpopulating namespace and disadvantage of the second one is difficulty to control parameters of the windows.

FYI: @ericpre, @francisco-dlp, @magnunor, @jan-car

**Comment by thomasaarholt** [comment]
Great!

1. If scipy's filters handle ndarrays and it isn't too much work for supporting nd-hs signals, then I suggest supporting it. Even if we don't have plotting tools for them, I've used BaseSignal with 3 signal dimensions before (Atom Probe).

2. Once* ;) Since apodisation is a general feature, it would be nice if it was available for the other signals. It does clutter things a bit, but after HS splitting that shouldn't be a problem.

3. Apodization is probably fine. I see wikipedia calls them "window functions". I'm not sure.

4. Unless you're just adding two, I vote the latter. Would it be difficult to add something along the lines of `fft_signal.window.hann_window`?

**Comment by woozey** [comment]
@thomasaarholt Thanks for feedback!
So I will implement apodization in a general way, i.e. that it can be applied for all signals and will also try to get it working with nd ones.

> Unless you're just adding two, I vote the latter. Would it be difficult to add something along the lines of `fft_signal.window.hann_window`?

The last one sounds the best. Does anyone has an idea how to do it?

**Comment by thomasaarholt** [comment]
@woozey I'm not quite sure how pythonic this is, but I would do something like this. Perhaps someone else has a better way to do it?

To represent the windows I just do some simple multiplication.

```python
import numpy as np 

class Signal1D():
    def __init__(self, data):
        self.data = np.array(data)
        self.window = window_class(self)

class window_class():
    'Window class containing several methods for apodization'
    def __init__(self, s):
        self.Signal1D = s
    def __repr__(self):
        return 'Window class containing several methods for apodization'

    def hanning(self):
        print('this would do a hanning window')
        self.Signal1D.data = 10*self.Signal1D.data
    
    def tukey(self):
        print('this would do a tukey window')
        self.Signal1D.data = 100*self.Signal1D.data
```
Then
```python
>>> s = Signal1D([1,2,3])
>>> s.data += 3
>>> s.window.tukey()
'this would do a hanning window'
>>> s.data
array([400, 500, 600])
```

**Comment by ericpre** [comment]
@woozey, correct me if I am wrong -I haven't look at this in details- but this sounds what you want to implement is a specific kind of filter? If so, this is a matter of using the `map` method to signal with the correct parameters? I don't really see the need of making a class for this.
It is worth looking at how data filtering is currently done in hyperspy and there are a few examples for `Signal1D` with their corresponding guis.
As usual, it should be as generic as possible.

**Comment by woozey** [comment]
@ericpre window function is more like masking - i.e. it is a simple multiplication in real space. The motivation to implement it in HS originally was FFT as this would be the way to reduce streaking and make it looking nicer. Using `map` would only work for 1D signal as there no function that can output higher dimensionality windows. In addition one can use `...axis.offset` in order to centre the window.
I will check how the filters implemented in `Signal1D`.

**Comment by woozey** [comment]
I've checked filters. In case of apodization it would require creating similar but completely separate set of classes, which I think is an overkill. So finally I ended up with a method in `BaseSignal` which contains three window functions. I could easily put more, but I don't see the demand at the moment. Here is the PR: https://github.com/hyperspy/hyperspy/pull/1933 . Feedback will be appreciated.
