### ISSUE TITLE
Feature request: 'axis.chunks' for Lazy signals

### ISSUE THREAD

**Issue by woozey** [hyperspy/hyperspy#1931]
It would be convenient to have an access to chunk size through `axes_manager` for each axis. At the moment one can get chunk size through `s.data.chunks`, which need some efforts to translate into navigation or signal axes notation.

The syntax can be as simple as that:
``` python
>>> s.axes_manager.signal_axes[0].chunks
((5,5,5,5), )
```

**Comment by ericpre** [comment]
An alternative syntax has been implemented in #2855:

```python
>>> s.get_chunks_size(s.axes_manager.signal_axes[0])
((5,5,5,5), )
```
