### ISSUE TITLE
Samfire/matplotlib backend errors

### ISSUE THREAD

**Issue by waffaffales** [hyperspy/hyperspy#1941]
Hello all,

I posted a question on the gitter and was told to create an issue here.

I have been trying to use Samfire to fit my spectra. My installation of hyperspy is v1.3 in anaconda with python 3.6 installed. 

I have successfully plotted data and been able to use m.fit() to fit individual pixels and sometimes these seed pixels are used by samfire but are the only pixels plotted in the samfire plot window. I believe it happens when my `samf.metadata.goodness_test.tolerance` is set to a very large number (1000). I don't know if it has actually fitted my data, nor how to call the fit parameters.

When I try to use some realistic goodness tolerances I get the following traceback:

> Traceback (most recent call last):
  File "C:\Users\AppData\Local\conda\conda\envs\plotting\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 197, in __draw_idle_agg
    FigureCanvasAgg.draw(self)
  
> File "C:\Users\AppData\Local\conda\conda\envs\plotting\lib\site-packages\matplotlib\backends\backend_agg.py", line 464, in draw
    self.figure.draw(self.renderer)
  
> File "C:\Users\AppData\Local\conda\conda\envs\plotting\lib\site-packages\matplotlib\artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  
> File "C:\Users\AppData\Local\conda\conda\envs\plotting\lib\site-packages\matplotlib\figure.py", line 1151, in draw
    self.canvas.draw_event(renderer)
  
> File "C:\Users\AppData\Local\conda\conda\envs\plotting\lib\site-packages\matplotlib\backend_bases.py", line 1823, in draw_event
    self.callbacks.process(s, event)
  
> File "C:\Users\AppData\Local\conda\conda\envs\plotting\lib\site-packages\matplotlib\cbook.py", line 554, in process
    proxy(*args, **kwargs)
  
> File "C:\Users\AppData\Local\conda\conda\envs\plotting\lib\site-packages\matplotlib\cbook.py", line 416, in __call__
    return mtd(*args, **kwargs)
  
> File "C:\Users\AppData\Local\conda\conda\envs\plotting\lib\site-packages\hyperspy\drawing\figure.py", line 31, in _on_draw
    self._draw_animated()
  
> File "C:\Users\AppData\Local\conda\conda\envs\plotting\lib\site-packages\hyperspy\drawing\figure.py", line 36, in _draw_animated
    if self.ax.figure and self.figure.axes:

> AttributeError: 'NoneType' object has no attribute 'figure'

Im really not sure what is going on? Am I using Samfire correctly or is there something wrong with my installation? Any help would be greatly appreciated.

**Comment by francisco-dlp** [comment]
Could you try upgrading to v1.3.1 and let us know if the issue persists? We've fixed a lot of plotting issues in the latest release.

**Comment by waffaffales** [comment]
Thanks Francisco! I upgraded to v1.3.1 and all seems to be working.

**Comment by francisco-dlp** [comment]
Great, thanks for the feedbadk!
