### ISSUE TITLE
Fitting EELS-Lowloss/Zeroloss/Coreloss

### ISSUE THREAD

**Issue by mgrove-wwu** [hyperspy/hyperspy#1955]
Hello again,

I am currently fitting some EELS data with the create_model class and some gaussians/the edge-models for corelosses. 
Sadly even though the fitting routine works, i have trouble setting correct initial parameters and get kinda rubbish parameters back. I was first confused looking at the issue. The binned signal is not an issue though. What i am wondering is why the fitting routine puts out incredibly high (sometimes negative) amplitude values. So i guess that while i am looking at the electron counts hyperspy uses other data for each channel - dont bother if i am on the completly wrong track. 
Additionally, some sigma values are negativ and during a fit of ZLP + Plasmon i get some negative values for the Amplitudes of the Plasmons also in the order of -x*e+6. 
Is it a bad idea to use three gaussians to fit ZLP + 2 Plasmons in the same time /do i need to fit them independently - i tried this and it works at least for the negative sigmas but still the amplitude values dont seem to represent my data while the plotted functions do...? and do you guys know why i get amplitudes in the order of e+6 while i only have e+4 up to e+5 and negative values though the fitted functions seem to be correct in the actual plots - especially the negative or high amplitudes bother me while the centre values and somewhat even the negative sigmas fit well if correct initial parameters are given?
Sorry for the wall of text!

PS: I really hope it is not again due to the version of gatan they use at my university

**Comment by francisco-dlp** [comment]
I am closing this because it is not a HyperSpy issue but an analysis question that is more suited for the gitter chat.

In general it is hard to reply to analysis questions that come without the script used to analyse the data and the data itself. Maybe you can share a notebook with us via the gitter chat?

**Comment by magnunor** [comment]
Link to the gitter chat: https://gitter.im/hyperspy/hyperspy
