### ISSUE TITLE
BUG: plot_spectra() does not correctly plot a decreasing axis

### ISSUE THREAD

**Issue by jat255** [hyperspy/hyperspy#1972]
If the scale of the x-axis is negative (common in IR spectroscopy), using the `plot_spectra` function will plot the data in increasing order:

Example plotting using `s.plot()`:
![image](https://user-images.githubusercontent.com/1278301/40995130-40a7783a-68cc-11e8-90ac-33f30a0c2abf.png)

Example using `plot_spectra()`:
![image](https://user-images.githubusercontent.com/1278301/40995165-56a43394-68cc-11e8-96b2-ad5453a66fa9.png)

This is because matplotlib defaults to an increasing axis, and there is no explicit setting of axes limits like there is in `signal.plot()` (see https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/hyperspy/drawing/signal1d.py#L113-L116).

This shouldn't be too hard to fix by copying those lines or similar into `plot_spectra`

**Comment by ericpre** [comment]
Fixed in #1973.
