### ISSUE TITLE
Unused parameter in blind_source_separation()

### ISSUE THREAD

**Issue by jat255** [hyperspy/hyperspy#1975]
There is a parameter for this method called `pretreatment`. It does not have a docstring, and does not appear to be used anywhere in the code. Is it needed? Should it be removed to prevent confusion?

https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/hyperspy/learn/mva.py#L479

**Comment by thomasaarholt** [comment]
I can't find anything about pretreatment as part of the function on scikit. I vote remove it.

**Comment by tjof2** [comment]
It's no longer there (certainly as of #2383) so this can be closed?
