### ISSUE TITLE
s.add_gaussian_noise() must check s.data dtype

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1990]
The user guide explains how to use s.add_gaussian_noise() to add noise to a signal. However, the example from the guide raises an exception since the `s.data` dtype is `int`, while the noise is `float`. 
This happens because of the `+=` in `s.data += noise` from [the method](https://github.com/hyperspy/hyperspy/blob/58850b17a3457a9d608a13774db69ddd93c47f6f/hyperspy/signal.py#L4673). 

This can be fixed by copying the code from three lines above it, but at the cost of more memory. Alternatively, we can change the dtype of the signal to match the noise dtype.

`+=` only works if the left hand side dtype is "more complex" (lack of a better word) than the right hand term. The example below demonstrates.
```
a = np.arange(10, dtype=int)
a += 1 # works
a += 2.0 # error
b = np.arange(10, dtype=float)
b += 2+1j # error
```

**Comment by ericpre** [comment]
This has been discussed in #1895 and since then the docstring explicitely says that: 
```
This method requires a float data type, otherwise numpy raises a ``TypeError``.
```

**Comment by thomasaarholt** [comment]
Thanks. It might be nice to raise our own error message instead, although the docstring does help.

**Comment by tjof2** [comment]
I think the numpy error in combination with the docstring is sufficient.
