### ISSUE TITLE
Release v1.4

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#2005]
Given the big amount of new features already in Rnm and pull requests to Rnm almost ready, I think that it is time for a minor release.

I have gone through the Rnm and Rnp issues and assigned them to the v1.4 and v1.3.3 milestones respectively. We don't need to close them all to release (there is plenty of material already in Rnm), but it'll be nice to review and merge as many as possible before releasing. I have set the release date to Wednesday 25 of July in order to leave us time to do just that.

**Comment by thomasaarholt** [comment]
As a heads-up, due to the implementation of `t.Str` in #1870 and hyperspy/hyperspy_gui_ipywidgets#3, we need a new release of hyperspy-gui-ipywidgets when releasing v1.4.

**Comment by francisco-dlp** [comment]
Something unexpected came in my way and I didn't have the time to work towards this release. I'll set the target to Semptember if that's ok.

**Comment by k8macarthur** [comment]
Just going through documentation as I write my slides for September. Looks like our readable formats list is out of date. I'm assuming the Velox .emd format has now been rolled in?

**Comment by ericpre** [comment]
The documentation you are reading is possibly from 1.3.2? Support for reading emd velox will be in the 1.4 version and the Rnm branch is up to date accordingly.

**Comment by thomasaarholt** [comment]
Katherine, if you're reading on readthedocs.io, make sure you're
reading on latest
<https://hyperspy.readthedocs.io/en/latest/user_guide/io.html#supported-formats>and
not stable
<https://hyperspy.readthedocs.io/en/stable/user_guide/io.html#supported-formats>
.

**Comment by k8macarthur** [comment]
Always new things to learn :) 
Thanks guys.
