### ISSUE TITLE
Graph-window disappear when using remove_background()

### ISSUE THREAD

**Issue by AinomN** [hyperspy/hyperspy#2023]
Hi,

I use hyperspy 1.3.2, and the graph window closes when I try to use remove_background()

(First of all, sometimes the dialogbox disappear. However, I saw that issue is already reported.)
Then, when the dialogbox does not disappear, and I am able to fit the PowerLaw in the graph and click "ok" in the dialogbox, then every window closes down. Am I doing something wrong?

import matplotlib
import hyperspy.api as hs
import matplotlib.pyplot as plt

 EELS_data = hs.load("file")
 EELS_data.remove_background()

plt.show()

**Comment by ericpre** [comment]
Your issue may be that you haven't set matplotlib properly. There are different way to do it but the easiest is to run the following in a newly started jupyter qtconsole or notebook.

```python
%matplotlib qt
import hyperspy.api as hs
```
and after your remove the background, the background subtracted dataset should be displayed.
If matplotlib is set properly, there is no need to call `plt.show()`.

**Comment by AinomN** [comment]
Okay, but I am trying to run this through python script (from mac), and use the plt.show() to see the graph.

So, as I have understood the "%matplotlib qt" is for jupyter notebook, but it is to set the backend, right?

So, I tried to add the following line in the script, but nothing happened.

matplotlib.rcParams["backend"] = "Qt4Agg"

Does "Qt4Agg" not correspond to "%matplotlib qt" or am I doing something wrong?

**Comment by ericpre** [comment]
Ok, then you may want to set matplotlib to "interactive mode", we just talked about it in the gitter chat!
```python
import matplotlib
matplotlib.use('Qt5Agg')
matplotlib.interactive(True)
import hyperspy.api as hs
```

[Spyder](https://www.spyder-ide.org/) is a good alternative to run python script interatively in an ipython console.

**Comment by ericpre** [comment]
More about the matplotlib ipython magic command:
https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-matplotlib

**Comment by AinomN** [comment]
I am sorry, I didn't get it in the gitter chat.

Furthermore, I am sorry that my python knowledge is very limited, so I need help with even the basic things.

For some reason I cannot get matplotlib.use() to work, which is why is use matplotlib.rcParams["backend"].

However, when using matplotlib.rcParams["backend"] = "Qt5Agg" I get an error:
...
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: cannot import name 'QtCore'

Then I thought, perhaps I don't have "Qt5Agg" installed, and installed with pip. However, now I get the following error:
...
    from PyQt4.QtCore import *
ValueError: PyCapsule_GetPointer called with incorrect name

**Comment by ericpre** [comment]
You have issue(s) with your python distribution.
If you are using mac and you are not familiar with python, you should follow the [installation instruction for mac](http://hyperspy.readthedocs.io/en/stable/user_guide/install.html#quick-instructions-to-install-hyperspy-using-anaconda-linux-macos-windows). This is expected to work out of the box.

**Comment by AinomN** [comment]
I still think I am doing something wrong, since I don't see how I can fuck up "pip install hyperspy[all]"?

**Comment by ericpre** [comment]
> I still think I am doing something wrong, since I don't see how I can fuck up "pip install hyperspy[all]"?

@AinomN: please avoid using vulgar language, this is not an appropriate place.

Have you tried to follow the installation instructions for mac?

**Comment by AinomN** [comment]
@ericpre I am sorry, it will not happen again.
By installation for mac, do you mean the conda bundle? I have previously had problems using bundles, so I am trying to avoid it. So I only did a "pip install".

**Comment by ericpre** [comment]
Until a couple of months ago, there were dependencies issues (incompatibility) using the anaconda installer and it was necessary to downgrade qt to version 4. Now, this is working fine and the easiest way to installer hyperspy on mac is to use the anaconda installer.

**Comment by ericpre** [comment]
Please reopen if the issue is occurring again.
