### ISSUE TITLE
EELS-Fitting: component already in model

### ISSUE THREAD

**Issue by mgrove-wwu** [hyperspy/hyperspy#2034]
Hello again,
i am sorry to bother you guys again but i am unable to understand what is going wrong with a fitting routine i implemented.

```
def fit_eels(self):        
        
        m = self.Data.create_model() # takes the hs.signal and creates a model
        
        name_1 = 'Zero_Loss_Peak'
        name_2 = 'First_Plasmon_Peak'
        name_3 = 'Second_Plasmon_Peak'
        
        function_1 = self.Gaussian # self defined gaus. alternatively: hs.model.components1D.Gaussian()
        function_2 = self.Gaussian # self defined gaus. alternatively: hs.model.components1D.Gaussian()
        function_3 = self.Gaussian # self defined gaus. alternatively: hs.model.components1D.Gaussian()

        # Add description of every Gaus-fit
        function_1.name = name_1
        # Set expected initial values for ZLP
        function_1.height.value = 100000.
        function_1.centre.value = 0.
        function_1.fwhm.value = 2.5
        m.append(function_1)
            
        function_2.name = name_2
        # Set expected initial values for Plasmon Peak first order
        function_2.height.value = 10000.
        function_2.centre.value = 30.
        function_2.fwhm.value = 5.
        m.append(function_2)

        function_3.name = name_3
        # Set expected initial values for Plasmon Peak second order
        function_3.height.value = 1000.
        function_3.centre.value = 50.
        function_3.fwhm.value = 10.
        m.append(function_3)
        
        # Plasmon_Peak_2nd deactivated, because not needed
        # might change with testing and perhaps as an additional source of information
        # will increase calculation effort though
        m.components.Plasmon_Peak_2nd.active = False
        m.fit()
```

The execution has to use the class i implemented which includes the fit_eels function.
Also i tried to use extend with same result.

```
a=STZ_mapper(simple_eels_spectrum)
a.eels_fit_routine() # this calls the differentiation routine between image, stack, or simple spectrum 
#and executes the fitting routine
```

The error gives the hint that component 2 and 3 already exist in the model created.
I therefore added the lines to rename all components to avoid it. Surprisingly in other scripts i wrote it worked fine. It appears i miss something kinda basic.

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-25-18601e902bc1> in <module>()
>       3 a.plot()
>       4 #len(a.Data)
> ----> 5 a.eels_fit_routine()
>       6 #m = im[0].create_model()
>       7 #print(m)
> 
> <ipython-input-24-a7c365f6acfc> in eels_fit_routine(self)
>      99         # Initialize the fitting model and use the initialized gaussian models for one EELS
>     100         if (self.Type == 'EELS'):
> --> 101             self.fit_eels()
>     102 
>     103         # Initialize the fitting model and use the initialized gaussian models for an EELS-stack
> 
> <ipython-input-24-a7c365f6acfc> in fit_eels(self)
>     144         function_2.centre.value = 30.
>     145         function_2.fwhm.value = 5.
> --> 146         m.append(function_2)
>     147 
>     148         function_3.name = name_3
> 
> ~\AppData\Local\conda\conda\envs\Hyperspy\lib\site-packages\hyperspy\models\eelsmodel.py in append(self, component)
>     114 
>     115     def append(self, component):
> --> 116         super(EELSModel, self).append(component)
>     117         if isinstance(component, EELSCLEdge):
>     118             tem = self.signal.metadata.Acquisition_instrument.TEM
> 
> ~\AppData\Local\conda\conda\envs\Hyperspy\lib\site-packages\hyperspy\models\model1d.py in append(self, thing)
>     348 
>     349     def append(self, thing):
> --> 350         super(Model1D, self).append(thing)
>     351         if self._plot_components:
>     352             self._plot_component(thing)
> 
> ~\AppData\Local\conda\conda\envs\Hyperspy\lib\site-packages\hyperspy\model.py in append(self, thing)
>     332         # Check if any of the other components in the model has the same name
>     333         if thing in self:
> --> 334             raise ValueError("Component already in model")
>     335         component_name_list = [component.name for component in self]
>     336         if thing.name:
> 
> ValueError: Component already in model
> 

I tried to use the hyperspy-demo Fitting_tutorial.ipynb as an example on how to do that.
You can find the whole hyperspy ipynb-file also appended
[STZ_Heatmap.zip](https://github.com/hyperspy/hyperspy/files/2289782/STZ_Heatmap.zip)
It would be really kind, if you guys could help me understanding whats going on here. Thank you in advance!

PS: I hope you forgive bad coding behaviour :/ it is kind of still in early state

Scincerely, Max

**Comment by magnunor** [comment]
I'm guessing the issue in is:

```python
function_1 = self.Gaussian # self defined gaus. alternatively: hs.model.components1D.Gaussian()
function_2 = self.Gaussian # self defined gaus. alternatively: hs.model.components1D.Gaussian()
function_3 = self.Gaussian # self defined gaus. alternatively: hs.model.components1D.Gaussian()
```

Since (I'm guessing) `self.Gaussian` is an already created Gaussian class object, `function_1`, `function_2` and `function_3` is indeed the same component.

Try replacing it with:

```python
function_1 = hs.model.components1D.Gaussian()
function_2 = hs.model.components1D.Gaussian()
function_3 = hs.model.components1D.Gaussian()
```

Also, in case you haven't seen it, there is a EELS demo as well: https://github.com/hyperspy/hyperspy-demos/blob/master/electron_microscopy/EELS/EELS_analysis.ipynb

It focuses on core loss EELS processing, but might be useful for what you are trying to do as well.

**Comment by mgrove-wwu** [comment]
Ah, thanks. That definitely makes sense and explains why only in the class the assignment failed. That is kinda a feature seperating between a reference and a newly allocated memory segment, isnt it?
I will look into the EELS_analysis as well, but if i remember correctly it helped sometimes as well as it confused me.
