### ISSUE TITLE
Can't import BaseSignal through hyperspy.signal

### ISSUE THREAD

**Issue by dmlundeby** [hyperspy/hyperspy#2053]
The following line raises an ImportError in HyperSpy v1.4

`import hyperspy.signal`

This was possible in HyperSpy v1.3. This is possibly what causes HyperSpyUI not to launch with HyperSpy v1.4, see https://github.com/hyperspy/hyperspyUI/issues/170

**Comment by francisco-dlp** [comment]
Good catch, the issue is that [this line](https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/hyperspy/_components/power_law.py#L24) leads to a circular import. Base signal should be imported from ``signal`` instead.

**Comment by francisco-dlp** [comment]
I've just submitted a fix in #2054.

Thanks @dmlundeby for reporting the issue.
