### ISSUE TITLE
Issue loading FEI/Thermo Fisher .EMD file

### ISSUE THREAD

**Issue by Sputn1k7** [hyperspy/hyperspy#2060]
I have an FEI EMD file that is failing to load in hyperspy 1.4. I am attempting to load the file, and getting this error. I'm not getting the output example where you get a list of files. Does anyone have a tip?

What i'm seeing:

![image](https://user-images.githubusercontent.com/31019888/45835343-aaca6880-bcbe-11e8-9f4c-5e3c6e47ebea.png)

What I'm expecting is something like this:

![image](https://user-images.githubusercontent.com/31019888/45835410-e5340580-bcbe-11e8-975b-0103c550b2f7.png)

**Comment by Sputn1k7** [comment]
I have the example file, but it's still 40+ MB zipped.

**Comment by ericpre** [comment]
Can you confirm that you are using a version of hyperspy which support reading velox emd file (hyperspy >=1.4)?
If you have the issue with hyperspy 1.4 can you share a file with any of the online service (dropbox, google drive, etc.)?

**Comment by Sputn1k7** [comment]
I will do so today.

**Comment by ericpre** [comment]
@Sputn1k7, was the file "pruned" (as in https://github.com/hyperspy/hyperspy/pull/1662#issuecomment-361601300)?

**Comment by Sputn1k7** [comment]
@ericpre probably yes. Here is a link to the file:

https://www.dropbox.com/s/pzuzf85t667d2d9/September20.zip?dl=0

**Comment by Sputn1k7** [comment]
![image](https://user-images.githubusercontent.com/31019888/46432759-dfe5aa80-c703-11e8-826b-f6f03e62fd2a.png)

I am getting the "pruned" error from FeiEMDReader class.

**Comment by francisco-dlp** [comment]
@Sputn1k7, are you happy to close this now that you have confirmed that the file has been pruned?

**Comment by ericpre** [comment]
The data are saved in a proprietary format, which is not supported. The warning was not formatted properly and raise an error instead and it has been fixed in #2071.
