### ISSUE TITLE
Error in heaviside function gradient?

### ISSUE THREAD

**Issue by LMSC-NTappy** [hyperspy/hyperspy#2067]
While browsing through model components to help me figure out how to make my one of my own I stumbled upon something in the Heaviside function: 
https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/hyperspy/_components/heaviside.py

I think that the function currently defined as grad_n is in reality grad_A:
since we fit A*H(x-n), A-gradient should be H(x-n)

and then I am unsure about grad_n, analytically I would say -A*delta(x-n) but this cannot be numerically evaluated...

Anyways, this is certainly not a big deal. 

Cheers

Nicolas

**Comment by ericpre** [comment]
@LMSC-NTappy: for writing custom own components, it is advised to [write it as an Expression](https://hyperspy.readthedocs.io/en/stable/user_guide/model.html#specifying-custom-components) when possible because this is the easiest way. Moreover, the best performance is obtained with expressions supported by numexpr.

We are in the process of rewriting all possible components as an expression and this one should be rewritten too. This should be possible since there is now an implementation of the heaviside function in numpy (since 1.13), even  if this is not yet in numexpr (for 3.0).

**Comment by LMSC-NTappy** [comment]
Thanks for the fast reply!

I figured out it should be possible with an expression, but I didn't manage to get it to work so I switched to writing the class, which works fine.

I use heaviside functions to stitch together two halves of Lorentzian functions with varying fwhm. It allows me to fit asymmetrical peaks (no Idea if that's the best way to do it tbh, but works in my application)

**Comment by ericpre** [comment]
Indeed, if you are stitching two different functions, it is not sure if you can write it as an expression.
They exists quite a few functions to describe asymmetrical peaks and it could be also possible to combine some of these, but it you may have already through most of them.

xref #1863 for discussion on asymmetrical peaks.

**Comment by francisco-dlp** [comment]
In any case, this is a bug. Thanks @LMSC-NTappy for reporting it.

**Comment by tjof2** [comment]
Did #2262 fix this @jlaehne @LMSC-NTappy ?

**Comment by LMSC-NTappy** [comment]
@tjof2 Thanks for touching base on this. Well, actually I am not sure that #2262 fixes the issue

In the present state I get:
```python
h1 = hs.model.components1D.HeavisideStep(A=3,n=2)
x = np.arange(0,5,step=0.2)
h1.function(x)
#array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])
h1.n.grad(x)
#array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
```
which is not correct in my opinion. When I use the heaviside step function what I do is

```python
heaviexpr = "A*(heaviside(x-centre,0.5))"
h2 = hs.model.components1D.Expression(
    expression=heaviexpr,
    name="Heaviside",
    position="centre",
    A = 3,
    centre = 2,
    module="numpy",
    compute_gradients=True
    )
```
which works nicely:
```python
h2.function(x)
#array([0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 1.5, 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. ])
h2.A.grad(x)
#array([0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.5, 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ])
```
the gradient w.r.t. `centre` parameter raises an error though, but it is a dirac delta which is only well defined upon integration so I would not care too much about it.

**Comment by LMSC-NTappy** [comment]
@ericpre Regarding asymmetrical lorentzian peaks (in case anyone in search for answers reads this issue), in the past I have used:
```python
splitlorentz = """2*A/(pi*(sigma_l + sigma_r))
                *(heaviside(centre-x,0.5)*lorentzleft + 
                  heaviside(x-centre,0.5)*lorentzright) ; 
                  lorentzleft = sigma_l**2/((x-centre)**2 + sigma_l **2) ; 
                 lorentzright = sigma_r**2/((x-centre)**2 + sigma_r **2)"""
sl = hs.model.components1D.Expression(
    expression=splitlorentz,
    name="SplitLorentz",
    position="centre",
    A = 1,
    sigma_l = 0.1,
    sigma_r = 0.1
    centre = 3.0,
    module="numpy")
```
which worked wonder.

**Comment by ericpre** [comment]
If I remember correctly, last time I checked #2262, it didn't fix this issue.

In my opinion, an asymmetrical Lorentzian function could be useful, particularly if they come with an `estimate_parameters` method!

**Comment by LMSC-NTappy** [comment]
@ericpre Alright. I will try to make it into a PR then, with estimate_parameters using the method from Lorentzian

**Comment by jlaehne** [comment]
In #2514, I now fixed the `HeavisideStep` gradients (or better switched to automatically calculated ones) and in that course also used the `numpy` function as done here.
