### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by jykim1299** [hyperspy/hyperspy#2068]
OS : win 10, 64 bit

I enter 'pip install hyperspy[all]'.

and there issues

Failed building wheel for numba

 Failed building wheel for numba
  Running setup.py clean for numba
Failed to build numba
sparse 0.5.0 has requirement numba>=0.39, but you'll have numba 0.38.1 which is incompatible.

---
my pip list is that numba 0.39.0 , llvmlite 0.24.0 version.
---

please...

I'm very sad...

**Comment by ericpre** [comment]
The error comes from the last sparse release (3 days ago) that create a conflict with our numba version requirement.

Have you tried if hyperspy is working?

If it doesn't work, use
```
pip install hyperspy[learning, gui-jupyter, gui-traitsui]
```
As mentioned in the [documentation](https://hyperspy.readthedocs.io/en/stable/user_guide/install.html#install-using-python-installers), the `[]` is optional, if you don't need it, you can just run:
```
pip install hyperspy
```

Numba is already installed, so you should be fine.

**Comment by francisco-dlp** [comment]
Marking this as a bug as we should fix the version conflict. Thanks @jykim1299 for reporting this.

**Comment by francisco-dlp** [comment]
#2065 should fix this.

**Comment by ericpre** [comment]
#2065 has been merged.
