### ISSUE TITLE
how to use cython and fix memoryerror

### ISSUE THREAD

**Issue by jykim1299** [hyperspy/hyperspy#2070]
1.
![1](https://user-images.githubusercontent.com/44154065/46996772-c9563f00-d158-11e8-93a9-22c73a0cf1c1.PNG)

I see this warning message. then install Cython 0.28.5, sphinx-rtd-theme 0.4.2, sphinxcontrib-napoleon 0.7.

but not yet warning

and 

2.
how to fix memoryerror?

In [   ] : tmp = news.get_bss_model(5)

---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-12-d2b5ff8ef3cd> in <module>()
----> 1 tmp = news.get_bss_model(5)

D:\Miniconda3\lib\site-packages\hyperspy\learn\mva.py in get_bss_model(self, components)
    908         Signal instance
    909         """
--> 910         rec = self._calculate_recmatrix(components=components, mva_type='bss',)
    911         return rec
    912 

D:\Miniconda3\lib\site-packages\hyperspy\learn\mva.py in _calculate_recmatrix(self, components, mva_type)
    869         finally:
    870             if self._unfolded4decomposition is True:
--> 871                 self.fold()
    872                 sc.fold()
    873                 self._unfolded4decomposition = False

D:\Miniconda3\lib\site-packages\hyperspy\signal.py in fold(self)
   2711             folding.unfolded = False
   2712             folding.signal_unfolded = False
-> 2713             self._assign_subclass()
   2714             if self.metadata.has_item('Signal.Noise_properties.variance'):
   2715                 variance = self.metadata.Signal.Noise_properties.variance

D:\Miniconda3\lib\site-packages\hyperspy\signal.py in _assign_subclass(self)
   4415         if self._alias_signal_types:  # In case legacy types exist:
   4416             mp.Signal.signal_type = self._signal_type  # set to default!
-> 4417         self.__init__(**self._to_dictionary(add_models=True))
   4418         if self._lazy:
   4419             self._make_lazy()

D:\Miniconda3\lib\site-packages\hyperspy\signal.py in _to_dictionary(self, add_learning_results, add_models)
   1918         if add_learning_results and hasattr(self, 'learning_results'):
   1919             dic['learning_results'] = copy.deepcopy(
-> 1920                 self.learning_results.__dict__)
   1921         if add_models:
   1922             dic['models'] = self.models._models.as_dictionary()

D:\Miniconda3\lib\copy.py in deepcopy(x, memo, _nil)
    148     copier = _deepcopy_dispatch.get(cls)
    149     if copier:
--> 150         y = copier(x, memo)
    151     else:
    152         try:

D:\Miniconda3\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    238     memo[id(x)] = y
    239     for key, value in x.items():
--> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
    241     return y
    242 d[dict] = _deepcopy_dict

D:\Miniconda3\lib\copy.py in deepcopy(x, memo, _nil)
    159             copier = getattr(x, "__deepcopy__", None)
    160             if copier:
--> 161                 y = copier(memo)
    162             else:
    163                 reductor = dispatch_table.get(cls)

MemoryError: 

Thank you for help.

**Comment by ericpre** [comment]
What are the dimension of your dataset? Could it be possible that you don't have enough memory?

**Comment by jykim1299** [comment]
@ericpre my dataset is 2 dimeional. and my memory is 16GB

**Comment by ericpre** [comment]
Sorry I was not very accurate in the wording I used: what is the size of your dataset when it is "unpack"? The bcf iself may be small but if you have large number of pixel in your spectrum image and 4096 channels in the energy axis, then the whole dataset can be easily larger than your memory.

You can use `downsample` parameter to rebin the data when loading the file, see https://hyperspy.readthedocs.io/en/stable/user_guide/io.html#bruker-s-formats

**Comment by ericpre** [comment]
Closing this because of the lack of reply and it seems that the dataset is too large to fit into memory. Please re-open if you think that this is not the case.

On a side nore, if you still have the warning `unbcf_fast library is not present`, install hyperspy using pip or conda. If you really want to install the development version, you need to have a C compiler available on your system. Please refer to the [documentation](http://hyperspy.org/hyperspy-doc/current/user_guide/install.html#install-from-source) for details, but it is good to have an idea of what your are doing.
