### ISSUE TITLE
Markers in 4D datasets not working

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#2080]
Using markers in signals with i) more than 1 navigation dimensions, ii) not same size in the navigation dimensions, does not work.

Example of this:

```python
data = np.zeros((2, 3, 5, 6))
s = hs.signals.Signal2D(data)
s
<Signal2D, title: , dimensions: (3, 2|6, 5)>
marker = hs.markers.point(
        [[1, 2], [2, 3], [3, 4]],
        [[1, 2], [2, 3], [3, 4]],
        color='red')
s.add_marker(marker, plot_signal=False, permanent=True)
s.plot()
```

Moving the navigator to one of the righthand navigation positions gives the error:

```python
  File "hyperspy/hyperspy/hyperspy/drawing/image.py", line 336, in update
    marker.update()
  File "hyperspy/hyperspy/hyperspy/drawing/_markers/point.py", line 91, in update
    self.marker.set_offsets([self.get_data_position('x1'),
  File "hyperspy/hyperspy/hyperspy/drawing/marker.py", line 167, in get_data_position
    return data[ind].item()[indices]
IndexError: index 2 is out of bounds for axis 1 with size 2
```

This does not occur if the two navigation dimensions has the same size.

Changing https://github.com/hyperspy/hyperspy/blob/RELEASE_next_patch/hyperspy/drawing/marker.py#L166 from `indices = self.axes_manager.indices[::-1]` to  `indices = self.axes_manager.indices` seems to fix the issue, but I'm not certain if that will break something else.

**Comment by ericpre** [comment]
Fixed in #2098.
