### ISSUE TITLE
v1.4.1 Python 3.7 windows wheels missing

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#2082]
Strangely, appveyor built py36 wheels instead of py37 wheels when running the py37 jobs and, therefore, the py37 wheels are missing. See e.g. [this appveyor log](https://ci.appveyor.com/project/hyperspy/hyperspy/builds/19712693/job/jp82102krk38onpt).

I don't have access to a Windows machine. Can somebody build the wheels for Py37 to upload them?

**Comment by ericpre** [comment]
Yes, I can try make one for 64 bits.

**Comment by ericpre** [comment]
Done but I can't test it yet because I have issue(s) with installing the dependencies in anaconda, I am suspecting that a very recent build of h5py may be broken...
I am waiting for the bundle to finish to build (https://ci.appveyor.com/project/ericpre/hyperspy-bundle/builds/19723660) to test it.

**Comment by francisco-dlp** [comment]
Great, thanks!

**Comment by sem-geologist** [comment]
I think you are rushing too much with py37, it would be better to wait until most of the libraries will be built for py37.

**Comment by francisco-dlp** [comment]
I don't think that that's the case: all of our requirements in conda-forge are already available for Python 3.7, so we're lagging behind on this! Beside, the conda forge bot has automatically removed our py35 builds in conda-forge, so their policy seems to be to support only the latest 2 Python minor releases.

I don't know why appveyor didn't behave as expected here, but it may well be that there is something that we must fix in appveyor.yml.

**Comment by sem-geologist** [comment]
The shared log is for 32 bits, does 64bit version behave the same?

**Comment by francisco-dlp** [comment]
I'm afraid yes https://ci.appveyor.com/project/hyperspy/hyperspy/builds/19712693/job/s4364micxli0g3nf

**Comment by francisco-dlp** [comment]
If that's fine, I will simply upload the py37 win wheels from https://www.lfd.uci.edu/~gohlke/pythonlibs/

**Comment by sem-geologist** [comment]
what about using `pip` instead of conda (inside environment), that will take longer, but it should build everything nicely (or not as many libraries have wheels).

**Comment by francisco-dlp** [comment]
I would rather prefer to use the same approach for all Python versions and OS for consistency and to minimise the maintenance overhead. A workaround for the current issue that wouldn't require a substantial departure from the current approach would be to install python3.7 in miniconda "manually" (like we do in travis). However, it may well be an appveyor issue that we'll soon be fixed.

**Comment by francisco-dlp** [comment]
I've just uploaded Gohlke's wheels to pypi, so I'll close this.

**Comment by ericpre** [comment]
There are dependency resolution issues with conda at the moment when using the default and conda-forge channels and it downgrades python3.6 to python3.7, as it can be seen in this [log](https://ci.appveyor.com/project/hyperspy/hyperspy/builds/19723156/job/g0e5ich8mtic3ee1?fullLog=true). This should possible to find a workaround.
I have uploaded the python3.7 wheel on the github release but only for 64 bits yesterday, sorry I forgot to mention it here.
