### ISSUE TITLE
Using model.as_signal() after set_signal_range() yields NaNs

### ISSUE THREAD

**Issue by gguzzina** [hyperspy/hyperspy#2085]
I'm using hyperspy 1.3.1 and Anaconda 5.2.0. When I specify a signal range for my model and then convert the model to a signal with the `model.as_signal()` method, the signal contains plenty of NaNs. However, performing the same operation again yields the correct result, as shown in this example:

    import numpy as np
    import hyperspy.api as hs
    
    dataset = hs.signals.EELSSpectrum(np.random.random((10,10,100)))
    
     dataset.set_microscope_parameters(beam_energy=300,collection_angle=20,convergence_angle=20)
    model = dataset.create_model()
    model.set_signal_range(20,50)
    model.multifit()
    #model.reset_signal_range()
    
    mdl_signal1 = model.as_signal()
    testvalue1 = mdl_signal1.sum().integrate1D(0).data
    
    mdl_signal2 = model.as_signal()
    testvalue2 = mdl_signal2.sum().integrate1D(0).data

Every single time `testvalue1` will be a NaN and `testvalue2` won't.
By plotting `mdl_signal1.plot()` we can see that not all the spectra are NaNs, but only part of them. Uncommenting the ` #model.reset_signal_range()` line makes the two testvalues identical.

**Comment by ericpre** [comment]
Thanks for the bug report: it demonstrates two issues, which should be fixed in #2197 and #2198.

**Comment by francisco-dlp** [comment]
Fixed in #2197 and #2198
