### ISSUE TITLE
The take off angle function does not work for double tilt sample holder

### ISSUE THREAD

**Issue by CorentinLG** [hyperspy/hyperspy#2089]
this function was implemented for single tilt holder only.
Requires clarification of how each tilt angle is documented in the metadata and an update of the geometrical calculation.

**Comment by thomasaarholt** [comment]
For future reference, would you clarify for what sort of signal and calculation you are referring to?

**Comment by CorentinLG** [comment]
in utils.py, there is a function called 'take_off_angle', which is used to calculate the angle at which X-rays are leaving the sample going to the EDS detector. It is a function of the elevation angle of the detector, which depends on each microscope, but also of the sample holder tilt.

The take_off_angle function is used by other functions, and at present the tilt angle value is taken from the metadata. 
However, it works only for single tilt holder.  For double tilt holder, the metadata is structured into sub section (tilt alpha and tilt beta), and the take_off_angle function then raises an error.
