### ISSUE TITLE
could not get hyperspy_gui_traitsui to work

### ISSUE THREAD

**Issue by pandakay** [hyperspy/hyperspy#2091]
Hi, I am new to hyperspy and struggling with getting hs.preferences.gui() to work on Mac.  Any help is greatly appreciated. Thanks.

I installed hyperspy_gui_traitsui using conda install, and traitsui is showed up in conda list, 
```
$ conda list

traits                    4.6.0                    py36_1    conda-forge
traitsui                  6.0.0                      py_1    conda-forge
```

but when I import hyper spy.api as hs, in Jupyter notebook, I got the following warning: 
```python
/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:hyperspy.api:The traitsui GUI elements are not available, probably because the hyperspy_gui_traitsui package is not installed.
```

then when type in hs.preferences.gui() , I got the following error messages:
```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-3-5724e4f31951> in <module>()
----> 1 hs.preferences.gui()

/anaconda3/lib/python3.6/site-packages/hyperspy/ui_registry.py in pg(self, display, toolkit, **kwargs)
    172     def pg(self, display=True, toolkit=None, **kwargs):
    173         return get_gui(self, toolkey=toolkey, display=display,
--> 174                        toolkit=toolkit, **kwargs)
    175     return pg
    176 

/anaconda3/lib/python3.6/site-packages/hyperspy/ui_registry.py in get_gui(self, toolkey, display, toolkit, **kwargs)
    152         if toolkit in toolkits:
    153             used_toolkits.add(toolkit)
--> 154             thisw = f(obj=self, display=display, **kwargs)
    155             if not display:
    156                 widgets[toolkit] = thisw

/anaconda3/lib/python3.6/site-packages/hyperspy_gui_ipywidgets/utils.py in wrapper(*args, **kwargs)
     69     def wrapper(*args, **kwargs):
     70         display = kwargs.pop("display", True)
---> 71         wdict = f(*args, **kwargs)
     72         if display:
     73             IPython.display.display(wdict["widget"])

/anaconda3/lib/python3.6/site-packages/hyperspy_gui_ipywidgets/preferences.py in show_preferences_widget(obj, **kwargs)
     63         for trait_name in getattr(obj, tab).editable_traits():
     64             trait = tabtraits[trait_name]
---> 65             widget = TRAITS2IPYWIDGETS[type(trait.trait_type)](
     66                 trait, get_label(trait, trait_name))
     67             ipytab.append(widget)

KeyError: <class 'traits.trait_types.Str'>
```

**Comment by pandakay** [comment]
also as additional information, from conda list, I get the following version:

hyperspy                  1.4.1            py36h470a237_0    conda-forge
hyperspy-gui-ipywidgets   1.0.0                    py36_0    conda-forge
hyperspy-gui-traitsui     1.1.1                 py36_1000    conda-forge
pyqt                      5.6.0            py36he5c6137_6  
...
qt                        5.6.2               h9975529_14  

but %matplotlib qt5 doesn't work for me
%matplotlib qt showed no error

**Comment by ericpre** [comment]
You are using old version of `hyperspy-gui-ipywidgets` and `hyperspy-gui-traitsui`. Can you update them?

To update all packages with conda:
```
conda update --all
```

Regarding
> but %matplotlib qt5 doesn't work for me
%matplotlib qt showed no error

Both work fine on my system but some reported this issue. It would be sensible to report this issue to matploltib.
To load hyperspy, it is recommanded to use `%matplotlib qt`, see the [getting started section of the documentation](https://hyperspy.readthedocs.io/en/stable/user_guide/getting_started.html#starting-hyperspy-in-the-notebook-or-terminal). This should be more robust across different install.

**Comment by pandakay** [comment]
Hi Ericpre,

Thanks for the quick reply.

I updated all packages as you suggested and now the versions are:
hyperspy                  1.4.1            py36h470a237_0    conda-forge
hyperspy-gui-ipywidgets   1.0.0                    py36_0    conda-forge
hyperspy-gui-traitsui     1.1.1                 py36_1000    conda-forge
pyqt                      5.9.2            py36h655552a_2 
qt                        5.9.6                h45cd832_2  
qtawesome                 0.5.2                    py36_0  
qtconsole                 4.4.2                    py36_0  
qtpy                      1.5.2                    py36_0  
traits                    4.6.0            py36h1de35cc_3  
traitsui                  6.0.0                    py36_1  

It seems that hyperspy-gui-ipywidgets and hyperspy-gui-traitsui stayed the same?

when I run %matplotlib qt or qt5, there is no error messages; then run import hyperspy.api as hs, still get a warning:
"WARNING:hyperspy.api:The traitsui GUI elements are not available, probably because the hyperspy_gui_traitsui package is not installed."

Is there other way to update to the new version of hyperspy-gui-ipywidgets and hyperspy-gui-traitsui?

Thanks a lot for your help.

**Comment by ericpre** [comment]
To update the package, see the [conda documentation](https://conda.io/docs/commands/conda-update.html), but in short you should be able to update it using:
```
conda update hyperspy-gui-ipywidgets hyperspy-gui-traitsui
```

**Comment by pandakay** [comment]
Thanks Eric. I tried this.  It didn't update these two. Maybe the current version I have is the latest one?

hyperspy-gui-ipywidgets   1.0.0                    py36_0    conda-forge
hyperspy-gui-traitsui     1.1.1                 py36_1000    conda-forge

**Comment by ericpre** [comment]
The two last versions are 1.1.1 for both (see https://anaconda.org/search?q=hyperspy). Can you try:
```
conda install hyperspy-gui-ipywidgets=1.1.1
```
You may have dependencies conflict which will depends on what you did in your conda environment previously. Installation from a clean environment works fine.

**Comment by pandakay** [comment]
Thanks Eric!
Finally got it to work by typing in:
conda install -c conda-forge hyperspy-gui-ipywidgets=1.1.1

Don't understand why it still shows "WARNING:hyperspy.api:The traitsui GUI elements are not available, probably because the hyperspy_gui_traitsui package is not installed".

Is this how it supposed to look?
<img width="585" alt="screen shot 2018-11-28 at 9 34 24 pm" src="https://user-images.githubusercontent.com/45086491/49201369-74ac0380-f355-11e8-88bc-0675674192fe.png">

Thanks a lot!

**Comment by ericpre** [comment]
Please refer to the documentation to make sure you are starting hyperspy correctly.

http://hyperspy.org/hyperspy-doc/current/user_guide/getting_started.html#starting-hyperspy-in-the-notebook-or-terminal
http://hyperspy.org/hyperspy-doc/current/user_guide/getting_started.html#configuring-hyperspy

**Comment by pandakay** [comment]
Hi Eric,

Thanks for taking your time helping me out here.  I did follow the instructions. I tried both qt and qt5 and got the same results as the following:
<img width="734" alt="screen shot 2018-12-02 at 12 05 59 pm" src="https://user-images.githubusercontent.com/45086491/49344349-bfb26900-f62a-11e8-9201-244942de0101.png">

It doesn't look the same as the image shown in the website, and maybe they are changed in the current version? And it seems to me that if I don't use qt, the calculation after each command is much faster...

Thanks again for your help.

**Comment by ericpre** [comment]
What is the output of `conda list hyperspy`?

Can you import `hyperspy_gui_traitsui`? You can check it with `import hyperspy_gui_traitsui`.

**Comment by pandakay** [comment]
Hi Eric,

The output is:
```
# packages in environment at /anaconda3:
#
# Name                    Version                   Build  Channel
hyperspy                  1.4.1            py36h470a237_0    conda-forge
hyperspy-gui-ipywidgets   1.1.1                      py_1    conda-forge
hyperspy-gui-traitsui     1.1.1                 py36_1000    conda-forge
```

Did you mean typing `import hyperspy_gui_traitsui` after `import hyperspy.api as hs`?  I got the following result:
```python
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-be6e20052baf> in <module>
----> 1 import hyperspy_gui_traitsui

ModuleNotFoundError: No module named 'hyperspy_gui_traitsui'
```

**Comment by ericpre** [comment]
You may have broken you anaconda distribution or you are mixing up different python distribution, i.e. you are not actually running the distribution you think you are using. Anyway, the easiest for you is possibly to uninstall and reinstall because it is going to be too complicated to sort this out if you are not familiar enough with python and anaconda.

**Comment by pandakay** [comment]
got it.  uninstalled everything and reinstalled anaconda and hyperspy. Now no warning messages, and response to the command is much faster.

The problem is solved. Thanks a lot for your help, Eric!
