### ISSUE TITLE
ValueError: API 'QVariant' has already been set to version 1

### ISSUE THREAD

**Issue by Zhanchenhaha** [hyperspy/hyperspy#2096]
--------------------------------------------------------------------
ValueError                         Traceback (most recent call last)
<ipython-input-6-090f4148c6d2> in <module>()
      1 
----> 2 import hyperspy.api as hs
      3 get_ipython().magic(u'matplotlib qt')

/root/anaconda2/lib/python2.7/site-packages/hyperspy/__init__.py in <module>()
      2 try:
      3     import sip
----> 4     sip.setapi('QVariant', 2)
      5     sip.setapi('QDate', 2)
      6     sip.setapi('QDateTime', 2)

ValueError: API 'QVariant' has already been set to version 1

**Comment by sem-geologist** [comment]
for me this looks like legacy code for pyQt4, what version of hyperspy are using?

**Comment by sem-geologist** [comment]
Any reason You are using Python 2.7. The hyperspy is actively developed for python 3 (>=3.5) support for python2  has been dropped.

**Comment by sem-geologist** [comment]
The same with your issue #2097
