### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Signal1D'

### ISSUE THREAD

**Issue by Zhanchenhaha** [hyperspy/hyperspy#2097]
import numpy as np
my_np_array = np.random.random((10,20,100))
print my_np_array.shape
s = hs.signals.Signal1D(np.arange(10))

hyperspy==0.8.3

AttributeError                     Traceback (most recent call last)
<ipython-input-10-d97b717af731> in <module>()
      2 my_np_array = np.random.random((10,20,100))
      3 print my_np_array.shape
----> 4 s = hs.signals.Signal1D(np.arange(10))

AttributeError: 'module' object has no attribute 'Signal1D'

**Comment by ericpre** [comment]
The API has changed since the 0.8.3 release and `Signal1D` was possibly named differently. Anyway, as @sem-geologist suggested in #2096, it is strongly recommended to use python 3 and more a recent hyperspy version.

**Comment by thomasaarholt** [comment]
It used to be called `Signal`, I think.
