### ISSUE TITLE
Storing list of objects

### ISSUE THREAD

**Issue by pburdet** [hyperspy/hyperspy#210]
For more flexibility, it would be useful to store several objects (spectra or images) in a single file as a list or array. One easy way might be to store the list in an arbitrary signal and save it. 

    ls = [s1,s2,s3]
    s = signals.Signal(None)
    s.metadata.set_item('list',ls)
    s.save('s')

It shouldn't be too hard to implement, isn't it?

**Comment by to266** [comment]
Closed via https://github.com/hyperspy/hyperspy/pull/646 and https://github.com/hyperspy/hyperspy/pull/402
