### ISSUE TITLE
Anaconda Windows ImportError PIL

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#2100]
I'm having some issues using HyperSpy in the Anaconda environment in Windows 10. A fresh install of Anaconda (Anaconda3-5.3.1-Windows-x86_64), and installing HyperSpy from conda-forge `conda install hyperspy -c conda-forge`.

Importing HyperSpy in a Jupyter Notebook gives the error:

```python
~\Anaconda3\lib\site-packages\skimage\io\manage_plugins.py in <module>()
     26 from glob import glob
     27
---> 28 from .collection import imread_collection_wrapper
     29
     30
 
~\Anaconda3\lib\site-packages\skimage\io\collection.py in <module>()
     10 import numpy as np
     11 import six
---> 12 from PIL import Image
     13
     14 from ..external.tifffile import TiffFile
 
~\Anaconda3\lib\site-packages\PIL\Image.py in <module>()
     62     # Also note that Image.core is not a publicly documented interface,
     63     # and should be considered private and subject to change.
---> 64     from . import _imaging as core
     65     if __version__ != getattr(core, 'PILLOW_VERSION', None):
     66         raise ImportError("The _imaging extension was built for another "
 
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by ericpre** [comment]
This is a dependency resolution issue in conda-forge, can you open an issue about it in the hyperspy-feedstock? https://github.com/conda-forge/hyperspy-feedstock/pull/27 should fix by forcing installing pillow > 5.2 at runtime.

The workaround is to install pillow=5.3.

**Comment by magnunor** [comment]
@ericpre: https://github.com/conda-forge/hyperspy-feedstock/issues/28

**Comment by magnunor** [comment]
In case anyone else bumps into this problem: running `conda install pillow=5.3` in Anaconda prompt fixes it.

**Comment by magnunor** [comment]
Fixed now!
