### ISSUE TITLE
Memory Leak when Saving Data

### ISSUE THREAD

**Issue by k8macarthur** [hyperspy/hyperspy#2105]
So I have been working on a script which saves a series of hyperspy spectrum in a for loop. Each subsequent save takes more a more RAM, leading to over 100Gb memory usage when each individual file is less than 100Mb in size. 

Using memory_profiler we were able to establish that the leak occurs during saving hspy files when writing to file using h5py. I looks like it might be that hyperspy automatically chunks data which triggers the memory leak existing in h5py (https://groups.google.com/forum/#!topic/h5py/_a35vzQzRrg). It might be to do with the fact that hyperspy automatically chunks data before saving?

![memory_leak1](https://user-images.githubusercontent.com/15925705/49512619-d2c57300-f88e-11e8-80cd-dfaa63368344.JPG)
![memory_leak2](https://user-images.githubusercontent.com/15925705/49512622-d2c57300-f88e-11e8-9f4f-6093e19a9660.JPG)

**Comment by francisco-dlp** [comment]
That forum thread is from 2014, if there was such an issue in h5py I would think that it's been fixed by now. Could you share the code leading to the issue? If you're using Windows, I've found in that past that the garbage collector sometimes doesn't work as expected in that platform but this experience was also some years ago, so it may be fixed by now too.

**Comment by k8macarthur** [comment]
I agree its an outdated thread but this was the closest we found to the same problem. So the full script is below but the section of code which is causing the memory leak is:

```
    for ev in stream_data:
        if ev == 65535:
            idx += 1
            x = idx % w
            y = (idx % (w*h)) / w
            if mathOp.isclose(x, 0) and mathOp.isclose(y, 0):
                print(memory_usage_psutil())
                np.savez_compressed('multiframes/{0}'.format(total_frames), cube)
                #Using hyperspy has been removed during to a memory leak during saving.
                s  = hs.signals.Signal1D(cube)
                s = s.isig[:3000]
                s = s.rebin(scale=scale)
                s.save('multiframes/{0}'.format(total_frames))
                s = None
                total_frames += 1
                print('Frames complete = ', total_frames)
                #print('Frame sum =', sum(sum(sum(cube))))

                cube = sc.zeros((h, w, b), dtype='int8')
        else:
            cube[int(y), int(x), ev] += 1
```

[Import_Emd_EDX_Data_Cube.txt](https://github.com/hyperspy/hyperspy/files/2648891/Import_Emd_EDX_Data_Cube.txt)

**Comment by k8macarthur** [comment]
It's for importing emd files from velox and saving each of the EDX frames individually.

**Comment by francisco-dlp** [comment]
Indeed I don't see why that should cause a memory leak. Could you try calling ``gc.collect()`` after deleting the s variable?

By the way, isn't it easier loading the dataset lazily and using standard HyperSpy syntax to save the individual frames?

**Comment by k8macarthur** [comment]
In theory that would be easier yes. But when I tried that I found the hyperspy files I saved were empty when I later went to reopen them....

gc.collect() seems to solve the problem. If I don't wipe s with s = None the same memory escalation arrises. Do you know why this is or am I just being stupid?

**Comment by francisco-dlp** [comment]
That seems to be a garbage collection issue. I have limited (but mainly bad) experience with it in Windows. In Linux it normally works fine for me.

Saving the lazily-read files to file should work. If it doesn't, then you've found a bug...

**Comment by k8macarthur** [comment]
So if I run:
```
s = hs.load(filename, first_frame=0, last_frame=1)
s[5].save('multilayer/test.hspy')
print(sum(sum(sum(s[5].data))))

s2 = hs.load('multilayer/test.hspy')
print(sum(sum(sum(s2.data))))
```
I get:
```
>>>129743
>>>0
```

**Comment by francisco-dlp** [comment]
It looks like a bug indeed. HyperSpy uses a little trick to load the data "lazily" (it's not truly lazy) that works for most operations but it seems not to work for saving, which is surprising but not impossible. Could you open an issue about it?

A workaround is calling ``s[5].compute()`` before saving. Could you confirm if that works?

**Comment by k8macarthur** [comment]
s.compute doesn't help but I'll open a separate issue to keep things easier to track.
