### ISSUE TITLE
s.save() does not save any data when saving some files.

### ISSUE THREAD

**Issue by k8macarthur** [hyperspy/hyperspy#2106]
Running the following for an .emd file:

```
s = hs.load(filename, first_frame=0, last_frame=1)
s[5].save('multilayer/test.hspy')
print(sum(sum(sum(s[5].data))))

s2 = hs.load('multilayer/test.hspy')
print(sum(sum(sum(s2.data))))
```

I get:

```
>>>129743
>>>0
```

So somehow the data has not be loaded properly enough or is not writing properly.

**Comment by k8macarthur** [comment]
So if I run:

Running the following assuming the specified file is an .emd file from velox:

```
s = hs.load(filename, first_frame=0, last_frame=1)
s[5].save('multilayer/test.hspy')
print(sum(sum(sum(s[5].data))))

s2 = hs.load('multilayer/test.hspy')
print(sum(sum(sum(s2.data))))
```

Produces the follow:

```
>>>129743
>>>0
```

**Comment by ericpre** [comment]
I can't reproduce this issue using the Velox emd files of the test suite.

**Comment by k8macarthur** [comment]
I also haven't had problems more recently. I'll close this issue.
