### ISSUE TITLE
How to set the colormap of the Signal1D plot navigator ?

### ISSUE THREAD

**Issue by etienne-monier** [hyperspy/hyperspy#2115]
Hi,

I may spam the issue discussions, but is there a way to change the 2D navigator colormap of a Signal1D navigator plot ? The default is gray but I'd like to use viridis :s 

Thanks.

**Comment by francisco-dlp** [comment]
The following line should do it:

```python
haadf1D._plot.navigator_plot.ax.images[-1].set_cmap("viridis")
```

You can also change the default cmap using matplotlib at the beginning of the session:

```python
import matplotlib
import matplotlib.pyplot as plt

plt.set_cmap("inferno")
```

We should document this, so I'll tag the issue as documentation bug and leave it open until we fix it. Thanks for asking!

**Comment by ericpre** [comment]
A more simple way of doing this is to use the `navigator_kwds` of the `plot` method, as explained in 
http://hyperspy.org/hyperspy-doc/current/user_guide/visualisation.html#customising-image-plot

```python
import hyperspy.api as hs
s = hs.signals.Signal2D(np.arange(10000).reshape(10, 10, 10, 10))

# set the colormap of the signal plot only:
s.plot(cmap='viridis')
# set the colormap of the navigator plot only:
s.plot(navigator_kwds={'cmap':'viridis'})
```
