### ISSUE TITLE
Velox EMD: File contains single spectrum stream

### ISSUE THREAD

**Issue by marksari** [hyperspy/hyperspy#2118]
I'm currently having an issue when loading data obtain in Velox (version 2.4 and 2.6) into HyperSpy (version 1.4.1). I'm unsure if it's something I'm doing wrong, a problem with Velox or a problem with HyperSpy but all of the .emd files I load in HyperSpy generate the following message: 

"WARNING:hyperspy.io_plugins.emd:The file contains only one spectrum stream"

Then when I attempt to plot the data the images all look like the image below, which I assume is due to the data not being loaded properly.

![hyperspy_velox_loading_issue](https://user-images.githubusercontent.com/46534196/50916598-690f2a80-1433-11e9-9696-237f94973c7a.png)

I know that HyperSpy cannot load data that has been pruned and none of the datasets I'm working with have been. Would anybody be able to suggest a way that I can save the .emd file with all the spectrum stream data or any other workaround that would allow me to load the data properly into HyperSpy?

Thanks.

**Comment by francisco-dlp** [comment]
I think that you can ignore the warning, it is normal to get it when loading data acquired with a microscope that does not have the capability to store one spectrum image per quadrant. Regarding the data, is it different from what you get when loading it with Velox?

**Comment by marksari** [comment]
All the data loads fine in Velox. I've tried multiple datasets too and the same problem occurs with all of them.

**Comment by francisco-dlp** [comment]
In order to identify the issue, it'll be useful if you could share one of your spectrum images with us.

**Comment by marksari** [comment]
No problem. I've included a HAADF image in the zip folder to show what the image should look like.
https://drive.google.com/file/d/1HH8syNNNbkkRm-zRiS_GgUzuCfI4KgbX/view?usp=sharing

**Comment by francisco-dlp** [comment]
Thanks, how should the spectrum image look like? If you can't export it to e.g. ser/emi, a screenshot from velox should do.

**Comment by francisco-dlp** [comment]
At first sight there is nothing wrong with the SI other than the very low number of counts. After binning the sum image displays some contrast that correlates well with the contrast of the HAADF image.

**Comment by marksari** [comment]
Sorry, I see that the counts are very low so that probably was not the best dataset to of given.

![np_spectrum](https://user-images.githubusercontent.com/46534196/50974213-9a92ff00-14e2-11e9-9b1d-3fd23ce57dcd.png)

Here is one that has more counts with an example of the navigator window and what I see using Velox.

https://drive.google.com/open?id=13dBIZXzUv2m4Qj-eJlA0Vby8uRM6LXGt

**Comment by francisco-dlp** [comment]
I think that HyperSpy loads properly your dataset, but it doesn't display the same thing as Velox. The spectrum displayed in Velox is the sum of all spectra in the spectrum image (that's Area #1 in your HAADF image), not the spectrum at a single pixel. In order to display it with HyperSpy simply compute the sum and plot it:


```python
%matplotlib qt
import hyperspy.api as hs

objs = hs.load("edsmap_1529.emd")
objs[-1].sum().plot()
```
![figure_eds_signal](https://user-images.githubusercontent.com/989719/50983064-e0f65700-14fe-11e9-93f4-d8121a0025cc.png)

If you agree, could you close this issue?

**Comment by marksari** [comment]
Yep, all the data does appear to be there. Thanks.
