### ISSUE TITLE
Warnings when changing navigation position for zero value Signal1D

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#2140]
When changing the navigation position for `Signal1D` objects with only zero values while plotting, a warning is generated in the console. Each time the navigator is changed to a position with zero values, another warning is generated.

This is especially bad for EDS maps, where often the signal counts is zero. So when navigating over such a dataset, the console gets filled with these warnings.

```python
import numpy as np
import hyperspy.api as hs
s = hs.signals.Signal1D(np.zeros((2, 10)))
s.plot() # Move the navigation slider
```

The warning:
```python
HyperSpy/hyperspy/hyperspy/drawing/signal1d.py:396: UserWarning: Attempting to set identical bottom==top resus
in singular transformations; automatically expanding.
bottom=0.0, top=0.0
  self.ax.set_ylim(y_min, y_max)
```

**Comment by ericpre** [comment]
Fixed in #2143.
