### ISSUE TITLE
Update plot after align_zero_loss_peak

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#2141]
If a plot is open, and `s.align_zero_loss_peak` is called, the plot is not updated with the align spectrum. To update it, `s.plot()` has be called again manually.

Example:
```python
import numpy as np
import hyperspy.api as hs
g = hs.model.components1D.Gaussian(A=1, sigma=2, centre=20)
s = hs.signals.EELSSpectrum(g.function(np.arange(100)))
s.axes_manager.signal_axes[0].offset = -10
s.plot()
s.align_zero_loss_peak() # Plot does not update
s.plot() # Plot updates
```

Since many of the signal methods automatically update the plot, `align_zero_loss_peak` not doing this can lead to confusion, with the user thinking that the method didn't work correctly.

Ideally `align_zero_loss_peak` should update plots associated with it.

Before replot:
![align_zlp_before_replot](https://user-images.githubusercontent.com/1690979/54457906-8d042a80-475a-11e9-939e-a054b61ae884.jpg)

After replot:
![align_zlp_after_replot](https://user-images.githubusercontent.com/1690979/54457920-942b3880-475a-11e9-8163-b4e6fbe086f5.jpg)

**Comment by ericpre** [comment]
#2144 is merged.
