### ISSUE TITLE
Lazy compute return signal type

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#2142]
[pixStem](https://pixstem.org/) implements much of its functionality by creating two new classes, `PixelatedStem` and `LazyPixelatedStem`, which inherit either `Signal2D` or `LazySignal2D`. Most the inherited functions return the same signal type, which makes this approach of extending HyperSpy very practical.

However, `s.compute()` returns only HyperSpy signals, not any of the extended ones in `pixStem`. Example of this:

```python
import dask.array as da
import hyperspy.api as hs
from hyperspy._signals.signal2d import LazySignal2D, Signal2D

class LazyTestSignal(LazySignal2D):

    pass

s = LazyTestSignal(da.random.random((100, 100)))
print(s) # <LazyTestSignal, title: , dimensions: (|100, 100)>
s.compute()
print(s) # <Signal2D, title: , dimensions: (|100, 100)>
```

It would be nice to be able to specify which type of signal class should be returned, in the signal itself. This could be made by overloading the `compute` (and `as_lazy`) methods. For example:

```python
import dask.array as da
import hyperspy.api as hs
from hyperspy._signals.signal2d import LazySignal2D, Signal2D

class LazyTestSignal(LazySignal2D):

    def __init__(self, *args, **kwargs):
        self._non_lazy_version = TestSignal
        super().__init__(*args, **kwargs)

    def compute(self, *args, **kwargs):
        super().compute(*args, **kwargs)
        self.__class__ = self._non_lazy_version
        self.__init__(**self._to_dictionary())


class TestSignal(Signal2D):

    def __init__(self, *args, **kwargs):
        self._lazy_version = LazyTestSignal
        super().__init__(*args, **kwargs)

    def as_lazy(self, *args, **kwargs):
        res = super().as_lazy(*args, **kwargs)
        res.__class__ = self._lazy_version
        res.__init__(**res._to_dictionary())
        return res

s = LazyTestSignal(da.random.random((100, 100)))
print(s) # <LazyTestSignal, title: , dimensions: (|100, 100)>
s.compute()
print(s) # <TestSignal, title: , dimensions: (|100, 100)>
s1 = s.as_lazy()
print(s1) # <LazyTestSignal, title: , dimensions: (|100, 100)>
```

However, it would be better if HyperSpy had support for this directly, for example by the `compute` method checking for a `self._non_lazy_version` attribute, and if it exist use that class instead of one found by `_assign_subclass`.

This way, these derived class could more easily control what is returned with `compute` and `as_lazy`.

**Comment by ericpre** [comment]
Fixed in #2180.
