### ISSUE TITLE
Ambiguity on "Power Law" vs "Powerlaw"

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#2176]
`s.remove_background` takes the `background_type="Power Law"` argument and default value. However, its docstring suggests that "PowerLaw" is correct, and the _model_ docs ([model](http://hyperspy.org/hyperspy-doc/current/user_guide/model.html) and [eels](http://hyperspy.org/hyperspy-doc/current/user_guide/eels.html)) refer to `PowerLaw` not `Power Law` in both component and attribute names.

This is confusing, particularly so for new users, so i suggest we change it to be consistent. "Power Law" is the only component that includes a space in its name, so unless anyone feels strongly about it, I suggest we make it "PowerLaw", not "Power Law".

**Comment by francisco-dlp** [comment]
+1

**Comment by jlaehne** [comment]
The component's correct name is `PowerLaw` indeed. The only place where `Power Law` was used was in the `remove_background()` function. To follow the suggestion by @thomasaarhodlt, I created #2184 to implement the change.

**Comment by thomasaarholt** [comment]
@francisco-dlp this does technically break the API. What do you suggest?

**Comment by francisco-dlp** [comment]
I think that it doesn't because ``remove_background`` still access ``"Power Law"``, regardless of if it is a good idea or not. Probably we should deprecate it this alias and remove it in 2.0,

**Comment by jlaehne** [comment]
I made `PowerLaw` the default naming, but left the lines where `Power Law` is identified as alias. So as @francisco-dlp says, it should not break the API. Whether, that alias should be removed at some point, is another question.

**Comment by thomasaarholt** [comment]
Neat! I withdraw my previous statement!

Yes, @jlaehne if you could add a `if background_type=="Power Law": raise_warning` line, then that would be great.

**Comment by ericpre** [comment]
This issue has changed with #2184. Now the `remove_background` method accept all version of `Power Law` with space and capitalise:
https://github.com/hyperspy/hyperspy/blob/03cb77f1417dc349c0184b3489812f6c9af7f71c/hyperspy/signal_tools.py#L1198

I think this issue can be closed, because the possible values of the `background` argument of the `remove_background` method doesn't need to be consistent the actual component name.

**Comment by thomasaarholt** [comment]
Agreed
