### ISSUE TITLE
Opening .dpt or .txt files

### ISSUE THREAD

**Issue by slyver08** [hyperspy/hyperspy#2181]
I just found heard of your project on reddit, I installed it on anaconda and it seems I just can't load .dpt or .txt files with it.

Since github doesn't support .dpt I'm joining a .txt.

[ATR.txt](https://github.com/hyperspy/hyperspy/files/3204383/ATR.txt)

**Comment by magnunor** [comment]
@slyver08,

This should load the data:
```python
import numpy as np
import hyperspy.api as hs

data = np.loadtxt("ATR.txt")
scale = data[0, 0] - data[1, 0]
s = hs.signals.Signal1D(data[:, 1][::-1])
s.axes_manager[0].scale = scale
```

**Comment by slyver08** [comment]
It did work! 

[ATR2.txt](https://github.com/hyperspy/hyperspy/files/3206945/ATR2.txt)

![Figure__Signal](https://user-images.githubusercontent.com/26194189/58167546-757e7c00-7c8c-11e9-8d9c-4a825b4e4139.png)

The only thing I see a problem with is that my x scale shouldn't be 0 to 3500 but 499 to 3999 approximately, but I can work around that.
 
Now I read your code can do a bunch of stuff, and curve fitting seems to be one of them. I mostly want to create a baseline, subtract it and fit curves to get the area of each peak. Is the EDS curve fitting section the right one to look at?

**Comment by magnunor** [comment]
@slyver08, the x-scale was due to a missing offset. For curve fitting, you can use the `Model` class directly, see below for an example of this.

```python
import numpy as np
import hyperspy.api as hs

data = np.loadtxt("ATR2.txt")
scale = data[0, 0] - data[1, 0]
offset = data[-1, 0]
s = hs.signals.Signal1D(data[:, 1][::-1])
s.axes_manager[0].scale = scale
s.axes_manager[0].offset = offset

m = s.create_model()
gaussian0 = hs.model.components1D.Gaussian()
gaussian1 = hs.model.components1D.Gaussian()
m.append(gaussian0)
m.append(gaussian1)
m.fit_component(gaussian0, signal_range=(840, 1090))
m.fit_component(gaussian1, signal_range=(724, 808))

m.set_signal_range(724, 1090)
m.fit()
m.reset_signal_range()
```

**Comment by slyver08** [comment]
Thank you so much!

**Comment by thomasaarholt** [comment]
@slyver08 Have you had any trouble with the script or using hyperspy in general? Or general feedback?

**Comment by jat255** [comment]
I'm going to close this, since it seems like the problem was resolved. @slyver08 please reopen if you need additional assistance.
