### ISSUE TITLE
EDS plot() function docstring is not correct

### ISSUE THREAD

**Issue by jordiferrero** [hyperspy/hyperspy#2188]
Trying to modify the default plot from a EDSTEMSpectrum.plot() plot, I have found that the arguments that it should inherit from the parent `plot()` function are not.

E.g. I tried to change the title by adding:
`eds.plot(True, title='Title changed')`

And triggers the following error:
`TypeError: plot() got an unexpected keyword argument 'title`

The same happens with other arguments like the 'fig'... However, Python suggests these arguments in the auto-completion mode...

**Comment by ericpre** [comment]
The docstring of `EDSTEMSpectrum.plot` is a bit confusing and actually refers to the `plot` method of `Signal1D` and not the `plot` of `matplotlib.pyplot`.

If you want to change the title you can set the title in the metadata.

```python
import hyperspy.api as hs
s = hs.datasets.example_signals.EDS_TEM_Spectrum() 
s.metadata.General.title = 'New title'
s.plot
```

**Comment by jordiferrero** [comment]
And is there a way to place the "plot" from the `s.plot` call in a subfigure box in the `matplotlib.subplot`.
I would like to create subplots with EDS intensity maps with their corresponding EDS labelled spectrum (that is after decomposition analysis).
@ericpre

**Comment by thomasaarholt** [comment]
@jordiferrero you may just want to write your own plotting function, drawing from the numpy data in `s.data`, the energy-axis in `s.axes_manager[-1].axis` and labels in `s.axes_manager[-1].name` and `s.axes_manager[-1].units`

**Comment by ericpre** [comment]
Have a look at the documentation on plotting spectra and images:
http://hyperspy.org/hyperspy-doc/current/user_guide/visualisation.html#plotting-several-images

You can provide matplotlib figure or axes objects as parameter of these functions.

**Comment by ericpre** [comment]
The docstring is clarified in #2193.
