### ISSUE TITLE
Probleme with fourier ratio deconvolution function

### ISSUE THREAD

**Issue by Tenkaichi2** [hyperspy/hyperspy#2191]
Hello,
I'm trying to work on my EELS datas with HyperSpy, I succed to align the zero Loss and extract the background of my Core-Loss, but I have some problems with the fourier_ratio_deconvolutions function. When I'm trying to apply it on my CoreLoss datas I have the following error message : 

AttributeError: 'EELSSpectrum' object has no attribute 'fourier_ratio_deconvolutions'

Thank you for your help

**Comment by ericpre** [comment]
Here is an example using synthetic dataset, which is working:

```python
import hyperspy.api as hs

# Use synthetic EELS dataset
ll = hs.datasets.artificial_data.get_low_loss_eels_signal()
cl = hs.datasets.artificial_data.get_core_loss_eels_signal()

# Do the deconvolution by passing the spectrum to deconvolve as a parameter.
cl.fourier_ratio_deconvolution(ll)
```

Can you try to reproduce?

**Comment by ericpre** [comment]
Please re-open if you still have this issue.
