### ISSUE TITLE
Heaviside docs latex representation broken

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#2192]
The [heaviside latex representation doc](http://hyperspy.org/hyperspy-doc/current/api/hyperspy._components.heaviside.html) is having a bad day.
I'm not sure if this was fixed or introduced by #2168, but I'm also noticing that the [readthedocs page ](https://hyperspy.readthedocs.io/en/latest/api/hyperspy._components.heaviside.html)doesn't have any page content at all!

**Comment by ericpre** [comment]
I can build the doc without problem with respect to latex rendering, so I don't think #2168 is related to this issue and I would rather blame the readthedocs builds.
If I remember correctly, it is only recently that the API was built on readthedocs, so there may be a few tweaks necessary.

**Comment by ericpre** [comment]
Fixed in #2211.
