### ISSUE TITLE
ComplexModel1D does not exist

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#2194]
What are the limitations behind there not existing a model handling complex numbers?

Is there any problem at all lie with components? Or do we simply need to create a child of Model1D?

```python
data = np.ones(3)
s = hs.signals.Signal1D(data)
s.change_dtype('complex')
m = s.create_model()
--
AttributeError: 'ComplexSignal1D' object has no attribute 'create_model'

```

**Comment by francisco-dlp** [comment]
At present the way to fit a model to complex data is to fit the real and imaginary parts separately using 2 instances of ``Model1D``.  I think that that should be good enough for most applications that come to my mind. Can you think on any application for a complex model class that is not covered by this approach?

**Comment by thomasaarholt** [comment]
Let's close this, and let anyone who has a problem reopen it. I can't think of an application off the top of my head, but that doesn't mean there isn't one. At least this way the issue is searchable.
