### ISSUE TITLE
The different conda-forge flavours of HyperSpy are not documented in the User Guide

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#2221]

**Comment by ericpre** [comment]
This is now documented in https://hyperspy.org/hyperspy-doc/current/user_guide/install.html#installation-in-an-anaconda-miniconda-distribution and https://hyperspy.org/hyperspy-doc/current/user_guide/install.html#installation-in-a-anaconda-minconda-distribution.
@francisco-dlp, can this issue be closed?
