### ISSUE TITLE
Update doc at hyperspy.readthedocs.io?

### ISSUE THREAD

**Issue by ericpre** [hyperspy/hyperspy#2233]
The documentation is up to date (v1.5) at: http://hyperspy.org/hyperspy-doc/current/index.html but not at https://hyperspy.readthedocs.io/en/stable/index.html (still at v1.4, not 1.4.2)

**Comment by francisco-dlp** [comment]
The build fail due to an  issue with sphinx-mermaid https://github.com/mgaitan/sphinxcontrib-mermaid/pull/32. The issue has been fixed but they haven't released a new version yet.

I'll translate the diagram to graphviz tomorrow morning to workaround the issue.

**Comment by francisco-dlp** [comment]
Done in #2234, now they're building, although the diagrams are not as nice as with mermaid.
