### ISSUE TITLE
Map garbles the output dimensions when applied to ragged arrays

### ISSUE THREAD

**Issue by dnjohnstone** [hyperspy/hyperspy#2266]
This is fixed in #1497 via an update to map_result_construction.

Since we've been waiting about 2.5 years for that thing to get completed - would it be possible to get just that fix to map in within a short time frame, say a few weeks?

**Comment by francisco-dlp** [comment]
We can make a patch release soon, but we can't release 1.6 anytime soon. So, if that fix is badly needed, I suggest to make a PR with just the fix to this issue extracted from #1497. Then we'll release asap after it gets merged.

**Comment by tjof2** [comment]
Closed in #1497
