### ISSUE TITLE
Spikes removal tool

### ISSUE THREAD

**Issue by Lrgrasso** [hyperspy/hyperspy#2268]
Hey guys, 
I need to remove spikes from luminescence spectra and was trying the hyperspy spikes_removal_tool() to do that. However, i´m facing a serious problem: i have too many spectras (more than 200) and the tool requires me clicking to remove each spike, and it takes a lot of time. Is there some way i can do this automatically ?
Thanks for the attention.

**Comment by tjof2** [comment]
As suggested elsewhere (https://gitter.im/hyperspy/hyperspy?at=5db9cb0fe1c5e9150801c6c3) - robust PCA might be a good way to approach this. See also #1011 as per @thomasaarholt

**Comment by Lrgrasso** [comment]
Thanks for the help !! I'll try the PCA.

**Comment by tjof2** [comment]
Great, let me know if you have issues

**Comment by ericpre** [comment]
For future readers, some more answers at https://gitter.im/hyperspy/hyperspy?at=5db858a32f8a034357faf30d and https://gitter.im/hyperspy/hyperspy?at=5db9cb0fe1c5e9150801c6c3

Closing this in favour of #1011 to avoid parallel discussions on the same topic.
