### ISSUE TITLE
Decomposition for EDS signals

### ISSUE THREAD

**Issue by dhruti96shah** [hyperspy/hyperspy#2270]
How does Hyperspy implement decomposition (pca, nmf) for EDS data, since the input would have to be a 3-d matrix.

**Comment by ericpre** [comment]
Answered on gitter by @jat255: https://gitter.im/hyperspy/hyperspy?at=5dbc6a68e469ef4358a546c3

> Dhruti Shah @dhruti96shah Nov 01 15:57
> How does Hyperspy implement decomposition (pca, nmf) for EDS data, since the input would have to be a 3-d matrix.
>
> Joshua Taillon @jat255 Nov 01 17:24
> @dhruti96shah AFAIK the spatial dimensions (x-y) are collapsed into a 1-D array, and then the ?
> result is transformed back into 2D after the decomposition is performed
>
> Joshua Taillon @jat255 Nov 01 17:30
> This is called "folding" and happens at
> https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/hyperspy/learn/mva.py#L202
>
> Dhruti Shah @dhruti96shah Nov 01 18:31
> I tried doing the same by extracting the data, and collapsing into a 1-D array, and then performing the decomposition using scikit learn packages, and got different results.
>
> Joshua Taillon @jat255 Nov 01 18:45
> if you look at the code in the link above, there are a few pretreatments that the code does including normalizing poissonian noise, so that might be were the discrepancy lies
> the operations are done with scikit learn, so you should be able to recreate the same results if you > follow what the code is doing
> https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/hyperspy/learn/mva.py#L280 is the actual call to the scikit learn method for NMF, for example
> 
> Dhruti Shah @dhruti96shah Nov 02 08:36
> Got it, thanks! :D
