### ISSUE TITLE
align_zero_loss-peak(subpixel=True) not working?

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#2275]
In the current RELEASE_next_minor.

```python
import numpy as np
import hyperspy.api as hs

data = np.zeros(1000)
data[50] = 100
data[51] = 101
s = hs.signals.EELSSpectrum(data)
s.align_zero_loss_peak(subpixel=True)
```

And zooming in on the peak at [50, 51]:

![subpixel_not_working](https://user-images.githubusercontent.com/1690979/68673025-276b7680-0553-11ea-99a0-1db91db1126f.jpg)

I'd expect the 0 on the x-axis to be at approximately the middle of the peak, at 50.5, i.e. -0.5 in the plot.

**Comment by tjof2** [comment]
It uses `scipy.interpolate.interp1d` under the hood. This is what the interpolated data looks like with the default interpolation settings, and explains why the peak is where it is. Perhaps if it used quadratic or spline interpolation it would be where you expect it to be, but not with the default linear interpolation.

![index](https://user-images.githubusercontent.com/6626247/89646458-b8d60200-d8b3-11ea-8876-1cbc0cbe41e0.png)

Note that what you posted is a `step` plot (see [demo in docs](https://matplotlib.org/3.1.1/gallery/lines_bars_and_markers/step_demo.html)) which can often cause confusion.

The behaviour in your example is to do `.step(x, y, where="mid")` it seems.

![o2](https://user-images.githubusercontent.com/6626247/89647088-dbb4e600-d8b4-11ea-9a6c-504a8cb8a507.png)
