### ISSUE TITLE
EELSModel.fit bounded docstring information

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#2276]
In the current RELEASE_next_minor, it says in `EELSModel.fit`'s docstring, that `bounded=True` only works with `fitter="mpfit"`.

However, when I use it with `fitter="leastsq"`, bounding still seems to work fine.

Is this docstring information out of date?

https://github.com/hyperspy/hyperspy/blob/5cc1d15344e71ace89cca35cd1027502c976d979/hyperspy/models/eelsmodel.py#L315

**Comment by tjof2** [comment]
@magnunor I think I looked at this a little ~3 years ago when I changed the scipy.optimize stuff behind the scenes, but never returned to it.

**Comment by askorikov** [comment]
Judging by these lines, bounded optimization should now be implemented for several fitters:

https://github.com/hyperspy/hyperspy/blob/f35970d38019c65cd837e4d06d35b537b72e3c6c/hyperspy/model.py#L1013-L1016

I guess, the docstring needs updating.
