### ISSUE TITLE
Bug: estimate_shift2D() fails with scipy 1.4.1

### ISSUE THREAD

**Issue by Janghyun-jo** [hyperspy/hyperspy#2308]
`estimate_shift2D` fails executing following :
```python
import hyperspy.api as hs
holo_stack = hs.stack([hs.datasets.example_signals.object_hologram(),
                       hs.datasets.example_signals.object_hologram()])
shifts_holo = holo_stack.estimate_shift2D()
```
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-35-42de35025b02> in <module>
      3                        hs.datasets.example_signals.object_hologram()])
      4 # shifts = phase_stack.estimate_shift2D()
----> 5 shifts_holo = holo_stack.estimate_shift2D()
      6 # phase_stack.axes_manager

~\Anaconda3\envs\hardware\lib\site-packages\hyperspy\_signals\signal2d.py in estimate_shift2D(self, reference, correlation_threshold, chunk_size, roi, normalize_corr, sobel, medfilter, hanning, plot, dtype, show_progressbar, sub_pixel_factor)
    485                         hanning=hanning, plot=plot,
    486                         normalize_corr=normalize_corr, dtype=dtype,
--> 487                         sub_pixel_factor=sub_pixel_factor)
    488                     if reference == 'cascade':
    489                         shift += nshift

~\Anaconda3\envs\hardware\lib\site-packages\hyperspy\_signals\signal2d.py in estimate_image_shift(ref, image, roi, sobel, medfilter, hanning, plot, dtype, normalize_corr, sub_pixel_factor, return_maxval)
    200             im[:] = sobel_filter(im)
    201     phase_correlation, image_product = fft_correlation(
--> 202         ref, image, normalize=normalize_corr)
    203 
    204     # Estimate the shift by getting the coordinates of the maximum

~\Anaconda3\envs\hardware\lib\site-packages\hyperspy\_signals\signal2d.py in fft_correlation(in1, in2, normalize)
     99     # Use 2**n-sized FFT
    100     fsize = (2 ** np.ceil(np.log2(size))).astype("int")
--> 101     fprod = fftn(in1, fsize)
    102     fprod *= fftn(in2, fsize).conjugate()
    103     if normalize is True:

~\Anaconda3\envs\hardware\lib\site-packages\scipy\fftpack\basic.py in fftn(x, shape, axes, overwrite_x)
    334 
    335     """
--> 336     shape = _good_shape(x, shape, axes)
    337     return _pocketfft.fftn(x, shape, axes, None, overwrite_x)
    338 

~\Anaconda3\envs\hardware\lib\site-packages\scipy\fftpack\helper.py in _good_shape(x, shape, axes)
    104     scipy.fftpack does not support len(shape) < x.ndim when axes is not given.
    105     """
--> 106     if shape and not axes:
    107         shape = _helper._iterable_of_int(shape, 'shape')
    108         if len(shape) != np.ndim(x):

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

```

I am using freshly installed hyperspy from pip with python 3.7 and scipy 1.4.1.

**Comment by ericpre** [comment]
Thanks for the bug report!
Scipy changed their `fft` API in their release 1.4 (14th December 2019)... This issue has been fixed in #2295 but other `fft` calculation in hyperspy are using numy fft and does not have this issue.

In the mean time and until the next hyperspy release, you may need to downgrade your scipy version to version 1.3.3.

**Comment by ericpre** [comment]
The same failure can be seen in https://travis-ci.org/hyperspy/hyperspy/jobs/634148602.

**Comment by francisco-dlp** [comment]
As this is hitting users, I think that it is time to:

* Make a new build in conda-forge with a ``scipy<1.4`` constraint
* Make a patch release

What do you think @ericpre?

**Comment by dnjohnstone** [comment]
I've previously had code rejected from core installs on multi-user platforms for having < constraints, which I also did to bodge issues like this, because it can mess with wider python environments. Given it seems that Eric has already fixed this - can't we just speed up the release of the version including that fix?

**Comment by Janghyun-jo** [comment]
I've installed "RELEASE_next_patch" from #2295, and it solved the problem.

**Comment by ericpre** [comment]
> As this is hitting users, I think that it is time to:
> 
> * Make a new build in conda-forge with a `scipy<1.4` constraint
> * Make a patch release
> 
> What do you think @ericpre?

Having a feedstock with `scipy<1.4` on conda-forge can be quite annoying to solve some conda environment. Most importantly, the issue will still remain when installing hyperspy with pip, so I would prefer a release.

**Comment by francisco-dlp** [comment]
Sorry for not having phrased the question correctly: I was not proposing to do one thing or the other, I was proposing to do both of them asap. It is true that adding the constraint can lead to other issues, but, in this way, somebody  who needs to install v1.5.2 in the future via conda, will get a fully working hyperspy.

**Comment by ericpre** [comment]
Yes, making a built for both will be good too!

**Comment by ericpre** [comment]
Installing hyperspy from `conda-forge` with `conda` should now work but installation with `pip` still not.

**Comment by tjof2** [comment]
Can this be closed?
