### ISSUE TITLE
pip install hyperspy on Windows 10

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#2315]
I'm investigating what's necessary to install hyperspy on a clean install of Windows 10 on behalf of a couple of users. Note that none of this is necessary if one installs using `conda install hyperspy` in the Anaconda/Miniconda Python distribution/package manager.

I test the following in a clean anaconda environment with python 3.7. I then called `python -m pip install hyperspy`. According to the docs, this should install only the strictly required libraries.
The following packages are installed:
`pillow, imageio, dill, toolz, dask, mpmath, sympy, natsort, llvmlite, numba, sparse, traits, pyzmq, decorator, colorama, backcall, ipython-genutils, traitlets, pickleshare, wcwidth, prompt-toolkit, pygments, parso, jedi, ipython, tornado, pywin32, jupyter-core, jupyter-client, ipykernel, ipyparallel, pyyaml, h5py, PTable, chardet, idna, urllib3, requests, networkx, PyWavelets, scikit-image, pint, tqdm, patsy, pytz, pandas, statsmodels, numexpr, hyperspy`
Of these, it looks like at least `traits` requires a compiler for a successful installation. There's a lot of red text, which ends with ` error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/`

Go to that website, download the community tools and from the "Individual Components" install Windows. I found that it was not necessary to install the older (2015) v14.0 compiler. Choosing the most recent 2019 compiler, I found that the following tools were necessary:

- .Net Framework 4.6.1 targeting pack
- .Net Framework 4.8 SDK
- MSVC v 142 - VS 2019 C++ x64/x86 build tools (v14.24)
- Windows 10 SDK
- C++/CLI support for v142 build tools (14.24)

![image](https://user-images.githubusercontent.com/2721423/73123855-d89b7d80-3f94-11ea-8ff9-2325e484e9fb.png)

This amounts to 4.3 GB :/

After that, `pip install hyperspy` installs as expected. `pip install hyperspy[all]` however, does not work, raising an error when building `blosc`. I will investigate that tomorrow. I believe it has to do with my python (Anaconda) being built with the 2017 compiler (I found this by typing `python` in cmd, and seeing which MSC version is reported in the first line, and then cross-referencing on this [documentation](https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=vs-2019).

**Comment by ericpre** [comment]
The main issue really is with traits, which does not provide wheels on pypi. Blosc is used to support compression of mrcz file.

Getting wheels for traits would be useful (https://github.com/enthought/traits/issues/357).

Downloading wheels from https://www.lfd.uci.edu/~gohlke/pythonlibs/ is the easy option but not automated...

**Comment by ericpre** [comment]
xref https://github.com/enthought/traits/issues/357

**Comment by ericpre** [comment]
I would suggest to close this issue, because this doesn't below to hyperspy documentation. Basically, If you want to compile code, you need to make sure that you are using a compiler compatible with your distribution (whether it is an anaconda, official python or any other python distribution) and this information is documented in the relevant place - not in hyperspy documentation.

We do provide the bundle and packaging on conda-forge so that users don't have to worry about these issue and we don't have to maintain a documentation for a number of platforms/distributions.

Moreover, there are a lot of details which matters when dealing with compilers (beside the fact that these things can be fairly brittle) and trying to documenting it without understanding it does sound right to me.

**Comment by tjof2** [comment]
I agree with @ericpre, this is a minefield and there is a way round it (conda).

**Comment by ericpre** [comment]
Traits wheels are now provided on pypi (https://github.com/enthought/traits/issues/357), which means that hyperspy can be installed on the three main platforms from pypi without compiler.

**Comment by thomasaarholt** [comment]
That's fantastic!!
