### ISSUE TITLE
Set signal type from Signal1D(signal_type)

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#2319]
It would be nice to be able to create signals of a given type as argument to the signal class. Currently it is necessary to set the signal type after instantiation.
```python
>>> s = hs.signals.Signal1D([1,2,3], signal_type='EELS')
>>> print(s)
<Signal1D, title: , dimensions: (|3)>

>>> s.set_signal_type('EELS')
>>> print(s)
<EELSSpectrum, title: , dimensions: (|3)>
```

**Comment by ericpre** [comment]
Is the following not simple enough?

``` python
s = hs.signals.EELSSpectrum([1, 2, 3])
```

**Comment by thomasaarholt** [comment]
You're right, that should be enough. Kinda forgot about that.
