### ISSUE TITLE
Tests failing with PhotometricInterpretation KeyError

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#2325]
Looks like the move to the tifffile package introduced an error associated with `PhotometricInterpretation`, [specifically this debug line](https://github.com/hyperspy/hyperspy/blob/f156a6e42c4cb082e2f79bd8b7a2055aacc48ba8/hyperspy/io_plugins/tiff.py#L165). I find no mention of PhotometricInterpretation on the [tifffile github repo](https://github.com/cgohlke/tifffile).

I don't really see why we include that bit of information as debug output in the logger.

**Comment by tjof2** [comment]
@thomasaarholt  isn't this what #2323  is for from @ericpre

**Comment by thomasaarholt** [comment]
Yeah, I noticed it just after posting. I searched for the PhotometricInterpretation error and the PR didn't come up in it. I'm assuming "PhotometricInterpretation" is a tag inside all tiffs or something, which is why that PR doesn't remove the reference to it.
