### ISSUE TITLE
align_zero_loss_peak( ) can not work on EELS SI

### ISSUE THREAD

**Issue by winston-song** [hyperspy/hyperspy#2339]
imc=hs.load('croped_ADF.tif')
cl_roi=hs.load('croped_cl.rpl')
ll_roi=hs.load('croped_ll.rpl')
    #if I only align the low loss region
ll_roi.align_zero_loss_peak(crop=False)
![image](https://user-images.githubusercontent.com/60322339/77302870-ebf36c80-6ce9-11ea-8069-82dd3c243ac9.png)
ll_roi.plot()
     #the image gives wrong align, navigator window is white
![image](https://user-images.githubusercontent.com/60322339/77303045-2ceb8100-6cea-11ea-815b-0a206f847893.png)
     #if Ialign the low loss and core loss region
imc=hs.load('croped_ADF.tif')
cl_roi=hs.load('croped_cl.rpl')
ll_roi=hs.load('croped_ll.rpl')
ll_roi.align_zero_loss_peak(also_align=[cl_roi],calibrate=True, print_stats=True, subpixel=True, crop=False)
cl_roi.plot()

![image](https://user-images.githubusercontent.com/60322339/77303300-9f5c6100-6cea-11ea-85ce-4b0c40932c56.png)

I can both SI after align are wrong, and the data is cropped even I crop=False, 
what is the meaning of green and blue bars in progress
can anyone help? thanks

**Comment by thomasaarholt** [comment]
The colour of the progress bar doesn't matter. Sometimes they just don't all go green.

Could you upload the files here? Alternatively, load the raw low-loss, crop it to just a few pixels and save it, with `ll_roi.inav[:2, :2].save('small_lowloss.hspy')`. You may have to zip it first. Then we'll take a look. You may want to have a look at the chat over at gitter as it is quicker to respond to questions. https://gitter.im/hyperspy/hyperspy

**Comment by winston-song** [comment]
[croped_ll.zip](https://github.com/hyperspy/hyperspy/files/4374582/croped_ll.zip)

I do not know whether the SI containing vacuum area matters the ZLP align, so upload a full file.

**Comment by thomasaarholt** [comment]
Hi @winston-song, you've just uploaded the rpl file which is just a header file. You must also upload the .raw file that accompanies it.

**Comment by winston-song** [comment]
[eelsmap2.zip](https://github.com/hyperspy/hyperspy/files/4377325/eelsmap2.zip)
both rpl and raw files are inside, thanks

**Comment by thomasaarholt** [comment]
Here you go. The problem was that a X-ray spike was making the alignment think the ZLP was at a different point.

[Fix ZLP.zip](https://github.com/hyperspy/hyperspy/files/4377534/Fix.ZLP.zip)

**Comment by thomasaarholt** [comment]
See the notes in the notebook for more info.

**Comment by thomasaarholt** [comment]
Did this help you? When you're happy, close this issue.

**Comment by winston-song** [comment]
Thanks a lot, it is working well now.
