### ISSUE TITLE
fourier_ratio_deconvolution to remove plural EELS scattering shows errors 

### ISSUE THREAD

**Issue by winston-song** [hyperspy/hyperspy#2344]
I have come across 2 problems when I try to remove plural scattering:

s_thickness=ll_roi.estimate_thickness(threshold=3.0)
  output:RuntimeWarning: invalid value encountered in logt_over_lambda = np.log(total_intensity / I0)

cl_deconvolved = cl_rb.fourier_ratio_deconvolution(ll_roi, extrapolate_coreloss=True, extrapolate_lowloss=True)
TypeError: cannot unpack non-iterable bool object

Q1: what is the runtime warning meaning? and the invalid value.
Q2: When I open extrapolate_ =True, it shows the TypeError, when I use False instead, this function can work. I do not find any reason and did not find any more explanation regarding the extrapolation function.

Thanks

**Comment by winston-song** [comment]
Even when I False the extrapolate_, the deconvolved navigator shows very dark region, how to change the signal intensity axis or the contrast.
![image](https://user-images.githubusercontent.com/60322339/77753674-e2d40980-7021-11ea-8b0e-5d603cbd6c96.png)

**Comment by tjof2** [comment]
I don't think there's enough information in the traceback here to see where the TypeError actually comes from.
