### ISSUE TITLE
Navigation square in the wrong image

### ISSUE THREAD

**Issue by iceaiai** [hyperspy/hyperspy#2359]
Dear all,
I was trying to load a nano beam diffraction map with dm3 or dm4 data type. The plot sequence is diffraction pattern on the left and then the SI (spectrum image) on the right. So the navigation square was shown in the diffraction pattern image instead of in the SI.
P.S. I have tried to used 'pixstem' package based on hyperspy. The same thing happened.
%matplotlib qt
import hyperspy.api as hs
import numpy as np
import matplotlib.pyplot as plt
s = hs.load("2-1000mmDiffraction SI.dm4")
s.plot()
s
 title: 2-1000mmDiffraction SI, dimensions: (### **512, 512**|20, 21)

**Comment by thomasaarholt** [comment]
You can easily swap the navigation and signal space by taking the transpose, either with `hs.transpose()` or by the simpler shorthand `s.T`

**Comment by iceaiai** [comment]
Thanks a lot, it works perfect.
