### ISSUE TITLE
Live_time changes in metadata during get_lines_intensity()

### ISSUE THREAD

**Issue by k8macarthur** [hyperspy/hyperspy#2362]
During the integrate step of get_lines_intensity the live_time changes in the maps metadata and is different for each element depending on the integration window used. 
In the integrate1D step the live_time is being multiplied by the integration window.
```
s = hs.datasets.example_signals.EDS_TEM_Spectrum()
s.set_microscope_parameters(live_time = 1)
lines = s.get_lines_intensity()
print(s.metadata.Acquisition_instrument.TEM.Detector.EDS.live_time)
print(lines[0].metadata.Acquisition_instrument.TEM.Detector.EDS.live_time)
```

**Comment by thomasaarholt** [comment]
The relevant line in the eds `get_lines_intensity` is the following:
https://github.com/hyperspy/hyperspy/blob/4be888574e5fc3df0725beb198ea7a3a79e89d0a/hyperspy/_signals/eds.py#L632

This translates into a simple `s.sum()` for binned eds signals, which triggers this `eds` specific behaviour:
https://github.com/hyperspy/hyperspy/blob/4be888574e5fc3df0725beb198ea7a3a79e89d0a/hyperspy/_signals/eds.py#L179

The live time should increase with summed navigation pixels but not with summed signal channels in my opinion. I think part of the solution is to avoid that sum when the axis passed is the signal axis? But we need to handle the case where the entire signal, including signal axes, are summed.

**Comment by k8macarthur** [comment]
Additionally  and probably connect it looks like the live_time goes negative when doing sc = s.get_decomposition_model(4).

**Comment by askorikov** [comment]
Maybe something like:
```python
time_factor = (np.prod([ax.size for ax in self.axes.manager.navigation_axes])
               / np.prod([ax.size for ax in s.axes.manager.navigation_axes])
mp.Detector.EDS.live_time = mp_old.Detector.EDS.live_time * time_factor

**Comment by askorikov** [comment]
Now I'm thinking: should the live time change at all when summing? Isn't it defined for the whole spectrum, rather than on per pixel basis?

**Comment by k8macarthur** [comment]
So live_time is and should change when rebinning the spectrum because it is the per pixel dwell time. Real time should not change at all.

**Comment by askorikov** [comment]
Hm, it was my understanding that real time is the total time of acquisition for the spectrum, and live time is the portion when EDS detector was active (see hyperspy/rosettasciio#239). Also, `rebin` function now scales the value of real time as well as the live time:
```python
>>> s = hs.signals.EDSTEMSpectrum(np.zeros([2, 4, 10]))
>>> s.metadata.Acquisition_instrument.TEM.Detector.EDS.real_time = 1.0
>>> s = s.rebin(scale=[2, 2, 1])
>>> print(s.metadata.Acquisition_instrument.TEM.Detector.EDS.real_time)
4.0
```
Now that I'm recalling the previous conversation, for spectrum images live time should ideally be an array corresponding to each pixel, since it can change from pixel to pixel depending on the X-ray count rate in the respective regions.

On the other hand I'm not even sure which file formats / IO plugins support live time information at the moment. So far I've only seen it for single spectra in SPX format, where navigation axes are irrelevant.

**Comment by ericpre** [comment]
> Hm, it was my understanding that real time is the total time of acquisition for the spectrum, and live time is the portion when EDS detector was active (see hyperspy/rosettasciio#239). Also, `rebin` function now scales the value of real time as well as the live time:

My understanding was the same! I have just checked on a few datasets:
- AZtec: live and real time are for the spectrum image (not per spectrum)
- GMS: live and real time are for the spectrum image but when summing a spectrum also sum the live and real time (and I end up with a real time of about 3 years... :D)
- Velox: live and real time are for ~~the whole spectrum image~~  a frame (edit: see @k8macarthur comment below).

This should be more explicit in the [metadata specification](http://hyperspy.org/hyperspy-doc/current/user_guide/metadata_structure.html).

**Comment by k8macarthur** [comment]
Actually velox doesn’t have a real time and live time. It just has one time which is per pixel and is the live time per frame. I agree though that the rebin function probably shouldn’t sum the real time but should sum the live time.

**Comment by ericpre** [comment]
Yes, sorry it seems to be per frame! I don't understand what do you mean with
> It just has one time which is per pixel and is the live time per frame

This is what is in the metadata:
```python
>>> s.original_metadata['Detectors']['Detector-8']
├── AnalyticalDetectorShutterState = 0
├── AzimuthAngle = 5.497787143782138
├── BeginEnergy = 169
├── CollectionAngle = 0.22500000000000001
├── DetectorName = SuperXG24
├── DetectorType = AnalyticalDetector
├── Dispersion = 10
├── ElectronicsNoise = 31
├── ElevationAngle = 0.38397244000000003
├── Enabled = true
├── InputCountRate = 4812
├── Inserted = true
├── LiveTime = 43.41829963037933
├── OffsetEnergy = -1000
├── OutputCountRate = 3614
├── PulseProcessTime = 3.0000000000000001e-006
└── RealTime = 52.428678249999997
```
with the frame time being:
```python
>>> m.original_metadata['Scan']['FrameTime']
'54.476800000000004'
```

**Comment by k8macarthur** [comment]
I didn’t see that before. Couldn’t find it in the velox software either...

Best wishes,

Katherine MacArthur

**Comment by tjof2** [comment]
Does hyperspy/hyperspy#2364 resolve this or is there still a need to keep this open?

**Comment by k8macarthur** [comment]
Nope looks like that fixes the problem! Great. 

Best wishes,

Katherine MacArthur
