### ISSUE TITLE
scipy.sqrt and scipy.exp are deprecated

### ISSUE THREAD

**Issue by tjof2** [hyperspy/hyperspy#2366]
Spotted these warnings in the Travis build from @ericpre in #2363 - see [the log here](https://travis-ci.org/github/hyperspy/hyperspy/jobs/676846703#L695).

```bash
hyperspy/tests/component/test_components.py::test_creation_components1d[Erf]
  <lambdifygenerated-584>:2: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
    return (0.5*A*erf((1/2)*sqrt(2)*(-origin + x)/sigma))
...
hyperspy/tests/component/test_components.py::test_creation_components1d[SkewNormal]
  <lambdifygenerated-620>:2: DeprecationWarning: scipy.exp is deprecated and will be removed in SciPy 2.0.0, use numpy.exp instead
    return (0.797884560802865*A*(0.5*erf((1/2)*sqrt(2)*shape*(x - x0)/scale) + 0.5)*exp(-1/2*(x - x0)**2/scale**2))
```

**Comment by ericpre** [comment]
I have seen this before and it was supposed to be fixed in #2305...

**Comment by tjof2** [comment]
@ericpre  is RELEASE_next_patch up to date? #2305 was merged to Rnm

**Comment by tjof2** [comment]
Otherwise can we avoid calling scipy full stop for these instances? i.e. always call numpy?

**Comment by ericpre** [comment]
> @ericpre is RELEASE_next_patch up to date? #2305 was merged to Rnm

Yes, this should be the reason.

> Otherwise can we avoid calling scipy full stop for these instances? i.e. always call numpy?

If I remember correctly, for some components it is necessary to have scipy, but it is possible to pass a list of module to sympy and, in this case, the order the modules in the list did matter to avoid the warning.

**Comment by tjof2** [comment]
Ok understood, so merging in Rnm should solve it?

**Comment by tjof2** [comment]
I'll close this because it looks like syncing release next minor with next patch solves it.
