### ISSUE TITLE
What is the EELSCLEdge "A" attribute

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#2372]
There appears to exist the `EELSCLEdge.A` attribute. It looks like it could be the integrated intensity of the edge, but it seems to be undocumented. Would be good to update that.

From the code, this its only definition (last line):
https://github.com/hyperspy/hyperspy/blob/a8a92a941fe8b28cbca2caa18936a99efc0d7681/hyperspy/_components/eels_cl_edge.py#L279

```python
    def _integrate_GOS(self):
        # Integration over q using splines
        angle = self.effective_angle.value * 1e-3  # in rad
        self.tab_xsection = self.GOS.integrateq(
            self.onset_energy.value, angle, self.E0)
        # Calculate extrapolation powerlaw extrapolation parameters
        E1 = self.GOS.energy_axis[-2] + self.GOS.energy_shift
        E2 = self.GOS.energy_axis[-1] + self.GOS.energy_shift
        y1 = self.GOS.qint[-2]  # in m**2/bin */
        y2 = self.GOS.qint[-1]  # in m**2/bin */
        self.r = math.log(y2 / y1) / math.log(E1 / E2)
        self.A = y1 / E1 ** -self.r
```

**Comment by francisco-dlp** [comment]
Good catch! Those are the parameters of the power law function used to extrapolate the curve. They should be private, would you like to fix it?
