### ISSUE TITLE
intensity.value differ from .twin but A is the same

### ISSUE THREAD

**Issue by winston-song** [hyperspy/hyperspy#2373]
**First, using multifit(kind=smart)**
![image](https://user-images.githubusercontent.com/60322339/79866990-87edc200-83d5-11ea-9988-f069198e741d.png)

print('{: .2e}'.format(m2.components.Mn_L3.A))
print('{: .2e}'.format(m2.components.Mn_L2.A))
1.18e+11
 7.07e+10
print('{: .2e}'.format(m2.components.Mn_L3.intensity.value))
print('{: .2e}'.format(m2.components.Mn_L2.intensity.value))
3.57e-04
 3.57e-04
print(m2.components.Mn_L3.onset_energy.value, m2.components.Mn_L2.onset_energy.value )
640.0 651.0

**Second using CL.edge.twin = None**
m2.components.Mn_L3.intensity.twin = None
m2.components.Mn_L2.intensity.twin = None

print('{: .2e}'.format(m2.components.Mn_L3.A))
print('{: .2e}'.format(m2.components.Mn_L2.A))
1.18e+11
 7.07e+10
print('{: .2e}'.format(m2.components.Mn_L3.intensity.value))
print('{: .2e}'.format(m2.components.Mn_L2.intensity.value))
5.00e-04
 7.31e-05

I am confused about how the .twin change intensity while keep A unchanged?

**Comment by francisco-dlp** [comment]
Thanks for reporting this issue. `A` is an internal attribute that should be private but it is not. That's a bug, see #2372. As it is unrelated to `intensity` it doesn't change when the `intensity.value` changes.

**Comment by winston-song** [comment]
> Thanks for reporting this issue. `A` is an internal attribute that should be private but it is not. That's a bug, see #2372. As it is unrelated to `intensity` it doesn't change when the `intensity.value` changes.

Thanks. 
In this case, intensity will be an important factor from smart fit. If L3 L2 twinned, they have a same intensity value, say X. if they are non-twin, they give different values. say Y and Z. however, I can not see any relationship between them, I orginally think X = Y+Z, but apparently not from data fitting. I wonder when we quantify the atom number, which intensity should use?

**Comment by winston-song** [comment]
> Thanks for reporting this issue. `A` is an internal attribute that should be private but it is not. That's a bug, see #2372. As it is unrelated to `intensity` it doesn't change when the `intensity.value` changes.

Thanks. 
In this case, intensity will be an important factor from smart fit. If L3 L2 twinned, they have a same intensity value, see X. if they are non-twin, they give different values. say Y and Z. however, I can not see any relationship between them, I orginally think X = Y+Z, but apparently not from data fitting. I wonder when we quantify the atom number, which intensity should use?

**Comment by ericpre** [comment]
Fixed in #2376.
