### ISSUE TITLE
Cannot load my hdf5

### ISSUE THREAD

**Issue by oroue** [hyperspy/hyperspy#2377]
Hi,
I would like to to try out hyperspy for visualisation of the hyperspectral imaging data
coming from synchrotron Quick EXAFS experiments.
The possibility of lazy loading is particularly attractive for this data.

I installed hyperspy with all its numerous dependencies and I'm trying to make work
the following code:
```python
%matplotlib qt
import hyperspy.api as hs
s = hs.load(datafile, lazy=True)
```
where datafile is a full path of the attached hdf5 file ,
containing a hyperspectral (EXAFS) image (cube 49x2x248).
(I had to create a zip it as hdf5 is not accepted by the git issues interface.)

[m3_charge_ROI0-160-2048-2_noav_00001.zip](https://github.com/hyperspy/hyperspy/files/4522130/m3_charge_ROI0-160-2048-2_noav_00001.zip)

I get the traceback as in the attached traceback.txt.
[traceback.txt](https://github.com/hyperspy/hyperspy/files/4522155/traceback.txt)

I however tried to mimic the stem_abf_data.hspy when creating this hdf5.
Thanks in advance for explaining me what do I misunderstand about the hdf5 format
expected by hyperspy.

**Comment by farhi** [comment]
Hi Olga,

probably the file `hyperspy/io_plugins/hspy.py` should probably be updated around lines 201 so that instead of setting the metadata name as hardcoded symbol:
- either `metadata` or `mapped_parameters` depending on the file version

a check in the `group` dict could be made for either `metadata` or the older `mapped_parameters`. 
```python
if 'metadata' in group.keys():
  blah
else:
  blah
```


This way the code could cope with both old and new API since version 1.2.

Probably a PR can be sent in this direction.

Emmanuel.

**Comment by ericpre** [comment]
hdf5 is a format which allow storing data and metadata in a structure way and hyperspy knows about a few file specifications (hspy, emd Berkeley and Velox and USID). When reading hdf5 file, hyperspy will expect a hdf5 file with "hspy specification".

How was your hdf5 file created? It is very likely that the io_plugin in hyperspy doesn't read this hdf5 file specification out of the box.

In case, this is a nexus file, https://github.com/hyperspy/hyperspy/pull/2328 may be useful.

**Comment by francisco-dlp** [comment]
@oroue, could you provide more details on what exactly you are trying to achieve? The easiest way to create a hspy file in Python is using HyperSpy itself. Are you trying to create a hspy file using a different programming language?

**Comment by oroue** [comment]
Was it probably not very clear from my first message, sorry. I would like to use hyperspy
to easily visualize 3-4 dimensional hyperspectral data in different projections taking 
advantage of the lazy loading. 

I created my hdf5 using Python after having read the documentation quite carefully and using 
the examples from https://github.com/hyperspy/hyperspy-demos/blob/master/image_data/datasets
so as to mimic their structure. I thought, a person familiar with the code could easily tell me where was I mistaken having a look at the traceback that I joined to my first message.

Ideally, I would not like my hdf5 files to become hspy files as in the same notebook I will probably use other python packages for data analysis, which are familiar with HDF5 but not necessarily with hspy extension.

**Comment by francisco-dlp** [comment]
Regardless of what you are planning to do with the files afterwards, the easiest way to create a hspy file is using hyperspy itselt. For example:

```python
import hyperspy.api a hs
s = hs.signals.Signal1D(your_data)
# calibrate your axes
s.axes_manager[0].name = "time"
s.axes_manager[0].scale = 0.1
s.axes_manager[0].units = "s"
s.metadata.anything_here_you_like = [1, "a", np.zeros((32,32))]
s.save("my_hspy_file.hdf5")
```
Does the above work for you?

**Comment by tjof2** [comment]
Unclear if this is still an issue, or indeed what category it falls under.
