### ISSUE TITLE
plot_spectra legend in wrong order

### ISSUE THREAD

**Issue by winston-song** [hyperspy/hyperspy#2382]
cls = []
lls = []
for x in range (0,5):
    cls.append(cl_rbO[x])
    lls.append(ll_crop[x])
    
ax = hs.plot.plot_spectra(cls, legend=['{}'.format(i) for i in range (0, 5)], style='overlap', padding = -1.0)
bx = hs.plot.plot_spectra(lls, legend= ['0','1','2','3','4','5'], style='overlap', padding = -1.0)

![image](https://user-images.githubusercontent.com/60322339/80386339-2cbd4300-889f-11ea-8364-7067000619ae.png)

I tried two cases, in cls plot, although I plot from lengend =0 to 5, why the image only show 0 to 4?
in second case of lls, I manually type legend stir, they are not in the related order. anyone can help?
thanks

**Comment by tjof2** [comment]
Are you sure about that Python range() usage? range(0,5) is the same as range(5), which returns 0-4 inclusive (i.e. five elements)

**Comment by winston-song** [comment]
> Are you sure about that Python range() usage? range(0,5) is the same as range(5), which returns 0-4 inclusive (i.e. five elements)

yes, thanks
