### ISSUE TITLE
Request: Arbitrary DataAxis

### ISSUE THREAD

**Issue by nitrocalcite** [hyperspy/hyperspy#2384]
First off, awesome library!

I've been wondering what I should do if I have measurements spaced at non-uniform intervals.  For example, maybe I have measurements at [72, 85, 93] Celsius, and I want to scroll through them on a navigation axis.
 
I figured that this would require a new `DataAxis` subclass.  So, I wrote an `ArbitraryDataAxis` class, which essentially just overrides `value2index` with this logic:
```
np.argmin(np.abs(self.arbscale-value))
```
where `self.arbscale = [72,85,93]`, in this case.  This hack seems to work fine for graphing values, but I'm not yet too familiar with the library internals.

So: Is it possible to support arbitrary values in `DataAxis`, or does that break some other functionality?  If it is possible, is this the way to go about it?

I assume that values have to be unique and monotically increasing, or else that *will* break other things.

Thanks!

**Comment by nitrocalcite** [comment]
Apologies, it looks like PR #2304 covers this; I couldn't find anything in Issues.

**Comment by francisco-dlp** [comment]
Thanks you for your timely remark @nitrocalcite. We are planning to include support for non-uniform axes in the next release due in a couple of weeks. In addition to #2304, you could have a look at #2299 and its ancestor #1927. We'll  be very interested in your feedback.
