### ISSUE TITLE
Suggested improvement to FEI stream reader + avoid FrameLookupTable

### ISSUE THREAD

**Issue by din14970** [hyperspy/hyperspy#2385]
In my experience, reading in large EMD stream frames can be quite slow with Hyperspy. I've found a fast vectorized way to convert the data to a COO sparse matrix. I looked into the `fei_stream_readers` and they are quite messy using lots of for loops. My solution is the following:

```
import scipy.sparse as spa

def _convert_stream_to_sparse(d1d, dim, dv=65535):
        '''
        Converts an EMD stream to a COO sparse representation

        Converts a given numpy array formatted like the emd
        SpectrumStream data into a scipy sparse matrix.
        The rows of this matrix include all the scan positions,
        the columns represent the number of channels.

        Parameters
        ----------
        d1d : 1D numpy.ndarray
            The array representing the stream to be converted
        dim : tuple
            The (x, y, channel, frame) dimension of the
            full dataset. Frame can be none,
            then it is calculated based on the size of d1d.
        dv : int
            The value in the SpectrumStream that encodes "next pixel"
            Default is 65535.
 
        Returns
        -------
        temp : scipy.sparse.spmatrix or np.ndarray
            The converted spectrumstream
        '''
        # unpack the dimensions
        xs, ys, ch, frm = dim
        # find the indexes where counts are registered (!= dv)
        cinx = np.argwhere(d1d != dv)[:, 0]
        # query the counts
        chans = d1d[cinx]
        # calculate the number of frames based on the size
        # if frm is unknown
        if frm is None:
            pxlcount = d1d.shape[0] - cinx.shape[0]
            frm = pxlcount // xs // ys
        # calc the dimensions of the sparse matrix
        dim_sparse = (xs*ys*frm, ch)
        # calc the pixel index to which these counts must be mapped
        pixind = cinx - np.arange(cinx.shape[0]) - 1
        # create an array of 1 representing the count
        ns = np.ones(chans.shape[0], dtype=d1d.dtype)
        # create the sparse matrix
        temp = spa.coo_matrix((ns, (pixind, chans)), shape=dim_sparse)
        return temp
```
Once you have this sparse matrix you can do all kinds of reshaping/summing over axes pretty quickly.

I think it looks much more elegent and with this I was able to import a SpectrumStream of 1e8 elements in about 5 seconds on my computer. If you think this is a good solution perhaps you can incorporate it into the code. Thought of making a pull request but the way you've implemented the readers is a bit different and I don't know anything about Numba so I don't want to break it.

Also I saw in `FeiEMDReader.__init__`:
```
# TODO: Finish lazy implementation using the `FrameLocationTable`
        # Parallelise streams reading
```
Just wanted to mention that this might break backwards compatibility with files created in older Velox versions where FrameLocationTables were not used in all datasets.

**Comment by ericpre** [comment]
This would be great and useful if you could make a PR. Please feel free to rewrite the Velox emd reader.
This reader is fairly well covered in term of testing, so if something is broken, we will know it fairly quickly!

**Comment by tjof2** [comment]
This was looked at in #2412 but the performance gain was not realized.
