### ISSUE TITLE
Gaussian and GaussianHF fit model shows different results, which should trust

### ISSUE THREAD

**Issue by winston-song** [hyperspy/hyperspy#2394]
I use two gussian components to fit my data, they give different results, and see the fitted A value, it is far from the integrated counts in this region, anyone can help?

case1, when use two GaussianHF
ga1 = hs.model.components1D.GaussianHF(centre=529.3, fwhm=0.94, height=0.81)
ga2 = hs.model.components1D.GaussianHF(centre=531.2, fwhm=2.9, height=0.2)
![image](https://user-images.githubusercontent.com/60322339/81510841-ed660c00-930c-11ea-8ad4-ced6edb285dd.png)
                  |  Center /eV   |   A ratio%  |
|------------------|---------------|-------------|
| ga1              |     529.25    |    41.16%   |
| ga2              |     530.55    |    58.84%   |
|------------------|-----------------------------|

ga1.A  2.137e-05
ga2.A  3.055e-05

Case2: when use two Gaussian
ga11 = hs.model.components1D.Gaussian(A=3.3, sigma=0.6, centre=529.3)
ga22 = hs.model.components1D.Gaussian(A=1.7, sigma=1.1, centre=531.5)
![image](https://user-images.githubusercontent.com/60322339/81510885-37e78880-930d-11ea-9247-e25dd407c374.png)

                  |  Center /eV   |   A ratio%  |
|------------------|---------------|-------------|
| ga1              |     529.28    |    65.46%   |
| ga2              |     531.35    |    34.54%   |
|------------------|-----------------------------|
ga1.A  3.328e-05
ga2.A  1.756e-05

**Comment by jat255** [comment]
To me, it looks not like a different in the underlying function definitions (i.e. both sets of answers look like Gaussians), but more that (for whatever reason) the second example converged to a different local minimum than the first example. I suppose if you converted the values of the "HF" parameters to A and sigma, and then repeated the fit with those values as starting points, the resulting fits for the two would look more similar.

As to which you should use... I would extract the model as a signal, and then subtract it from your original signal and look at how large the difference is (for both fits). I suspect they're both very "accurate" in the sense that they both correctly model the total data, but this means little for the underlying components, which appear to have more freedom than you want. You could also try bounding the parameters to certain values to ensure you converge to a similar solution in both cases.
