### ISSUE TITLE
[Test fail] Possible unicode matching error: AssertionError: assert 'Âµm' == 'um'

### ISSUE THREAD

**Issue by kevinsmia1939** [hyperspy/hyperspy#2401]
Hello,
I am trying to package hyperspy into openSUSE Linux.
I encounter an error during testing on headless server

Specifically this stand out, which look like some unicode matching error?

```
[ 1047s] >       assert s.axes_manager[0].units == "um"
[ 1047s] E       AssertionError: assert 'Âµm' == 'um'
[ 1047s] E         - Âµm
[ 1047s] E         + um
```

Repository: https://build.opensuse.org/package/show/home:andythe_great/python-hyperspy
Full log where error can be found: https://build.opensuse.org/build/home:andythe_great/openSUSE_Tumbleweed/x86_64/python-hyperspy/_log
openSUSE Tumbleweed
Hyperspy 1.5.2
Build dependecies:
BuildRequires:  %{python_module Cython}
BuildRequires:  %{python_module PTable}
BuildRequires:  %{python_module Pint >= 0.8}
BuildRequires:  %{python_module dask}
BuildRequires:  %{python_module PyYAML}
BuildRequires:  %{python_module dask-array >= 0.18}
BuildRequires:  %{python_module dill}
BuildRequires:  %{python_module h5py >= 2.3}
BuildRequires:  %{python_module imageio}
BuildRequires:  %{python_module ipyparallel}
BuildRequires:  %{python_module matplotlib >= 2.2.3}
BuildRequires:  %{python_module mrcz}
BuildRequires:  %{python_module natsort}
BuildRequires:  %{python_module numexpr}
BuildRequires:  %{python_module numpy >= 1.10}
BuildRequires:  %{python_module pytest}
BuildRequires:  %{python_module pytest-mpl}
BuildRequires:  %{python_module python-dateutil >= 2.5.0}
BuildRequires:  %{python_module requests}
BuildRequires:  %{python_module scikit-image >= 0.13}
BuildRequires:  %{python_module scipy >= 0.15}
BuildRequires:  %{python_module setuptools}
BuildRequires:  %{python_module sparse}
BuildRequires:  %{python_module statsmodels}
BuildRequires:  %{python_module sympy}
BuildRequires:  %{python_module tqdm >= 0.4.9}
BuildRequires:  %{python_module traits >= 4.5.0}

Thanks.

**Comment by francisco-dlp** [comment]
Thanks for reporting the issue. That was fixed in https://github.com/hyperspy/hyperspy/pull/2298 but we haven't made a new release yet. We will release v1.6 in one month, see #2251 . You could also consider packaging HyperSpy v1.5.2 with a `pip<0.10` constraint.

**Comment by kevinsmia1939** [comment]
Thanks, got it.
