### ISSUE TITLE
register_translation of scikit-image is deprecated but not applied

### ISSUE THREAD

**Issue by schanjo** [hyperspy/hyperspy#2415]
https://scikit-image.org/docs/stable/api/skimage.feature.html#skimage.feature.register_translation

Due to the above change, the following error occurs.

  File "/usr/local/lib/python3.6/site-packages/hyperspy/_signals/signal2d.py", line 26, in <module>
    from skimage.feature.register_translation import _upsampled_dft
ModuleNotFoundError: No module named 'skimage.feature.register_translation'

**Comment by ptim0626** [comment]
See #2402, this is fixed in the latest development version.

**Comment by schanjo** [comment]
Thank you for answer.
