### ISSUE TITLE
Covariance warnings

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#2419]
With latest master, I'm getting a covariance warning with all leastsq model fittings:

> `WARNING:hyperspy.model:Covariance of the parameters could not be estimated. Estimated parameter standard deviations will be np.inf. This could indicate that the model is a poor description of the data.`

I get this error on all `m.fit()`, even when the fit fits the data exactly. Is this correct behaviour?
```python
import numpy as np
import hyperspy.api as hs
x = np.linspace(-5, 5, 1001)
g = hs.model.components1D.Gaussian()
data = g.function(x)
s = hs.signals.Signal1D(data)
s.axes_manager[-1].offset = -5
s.axes_manager[-1].scale = x[1] - x[0]

m = s.create_model()
G = hs.model.components1D.Gaussian()
m.append(G)
m.fit()
# WARNING:hyperspy.model:Covariance of the parameters could not be estimated. Estimated parameter standard deviations will be np.inf. This could indicate that the model is a poor description of the data.
(s - m.as_signal()).data.sum()
# results in 1e-15
```
With `fitter='mpfit'` I get reasonable values for the error, in `G.A.std`.

I believe this is a result of [a commit by @tjof2 17 days ago](https://github.com/hyperspy/hyperspy/commit/caf983fda14cf518a5853e8e6d51376841d7b6b3).

**Comment by tjof2** [comment]
Well yes, it's right...in that your parameter standard deviations couldn't be estimated correctly.

For legacy reasons (I think), HyperSpy never handled issues where the estimated covariance didn't work. This was in contrast to SciPy curve_fit, which is effectively what the code replicates. In fact, if you look at https://github.com/scipy/scipy/blob/v1.4.1/scipy/optimize/minpack.py#L793, you'll see it actually raises a warning there too. All I did was replicate the same behaviour (slightly adapted in the nature of the message though).

Why might this warning arise? Well, the estimated covariance matrix is taken from the inverse of the Hessian. If the Hessian is singular, which implies the curvature in the region of the parameters is flat, then obviously the inverse of this won't work. Here's a related SO question: https://stackoverflow.com/questions/50371428/scipy-curve-fit-raises-optimizewarning-covariance-of-the-parameters-could-not. Again, the SciPy documentation covers this, and the whole section of code in HyperSpy could arguably be replaced by a call to curve_fit.

There are plenty of examples I've seen here and in dependent packages where the covariance matrix was happily containing negative values, or overflows, and then an unclear warning about the square root (to get the parameter standard deviation) of a negative number was all that indicated an issue at all. It used to raise:

```python
hyperspy/model.py:1134: RuntimeWarning: invalid value encountered in sqrt
    self.p_std = np.sqrt(np.diag(pcov))
```

When actually the calculation of `pcov` was the issue. Indeed most of the tests in the HyperSpy test suite for fitting will encounter this warning message, if you turn on logging in pytest. See #2405 .

This warning is much clearer, though I'll accept the last sentence is perhaps not helpful as it might suggest to the user that things are worse than they really are.

**Comment by thomasaarholt** [comment]
I think my point is: I am **always** getting covariance warnings. I suspect the commit introduced code that always raises the warning.

Here are two examples:
### Simple polynomial fitting example:
```python
import hyperspy.api as hs
import numpy as np

x = np.arange(10)
def f(x):
    return 2*x**2 - 10*x + 2
s = hs.signals.Signal1D(f(x))
m = s.create_model()
P = hs.model.components1D.Polynomial(legacy=False)
m.append(P)

m.fit()
m.plot()
```

### Gaussian fitting comparison with `scipy.optimize.curve_fit` with uncertainties
Here is a simple "fit a gaussian to noisy data" example. `scipy.optimize.curve_fit` does not raise an error, but hyperspy does with `leastsq`. `mpfit` gets the same uncertainty as `curve_fit`.

```python
import hyperspy.api as hs
import numpy as np

np.random.seed(1)
G = hs.model.components1D.Expression(
    expression="A * exp(-(x - centre)**2 / (2*sigma ** 2))",
    name="Gaussian",
    position="centre",
    A=1,
    sigma=1,
    centre=0,
    module="numpy")

x = np.linspace(-5, 5, 1001)
data = G.function(x)

data += 0.1*np.random.normal(size=data.shape)

s = hs.signals.Signal1D(data)
s.axes_manager[-1].offset = -5
s.axes_manager[-1].scale = x[1] - x[0]

m = s.create_model()
m.append(G)
m.fit(fitter='leastsq')
leastsq_error = G.A.std
m.fit(fitter='mpfit')
mpfit_error = G.A.std

from scipy.optimize import curve_fit
def func(x, A, centre, sigma):
    return A * np.exp(-(x-centre)**2/(2*sigma**2))

popt, pcov = curve_fit(func, x, s.data)
perr = np.sqrt(np.diag(pcov))
scipy_error = perr[0]

print('hyperspy leastsq error:', leastsq_error)
print('hyperspy mpfit error:', mpfit_error)
print('scipy optimize error:', scipy_error)
# hyperspy leastsq error: inf
# hyperspy mpfit error: 0.00905860325763757
# scipy optimize error: 0.009058628868748137
```

**Comment by tjof2** [comment]
Check the logic for warn_cov around line 1155. Like I say the whole thing ought to be replaced with curve_fit (rather than leastsq vs leastsquares)

**Comment by thomasaarholt** [comment]
Okay, I don't disagree that we should consider replacing the fitting code with `curve_fit`, but for the second example above, `curve_fit` also includes negative values in `pcov`. 

With `elif pcov.min() < 0:`, did you intend / would you consider `elif pcov.diagonal().min() < 0:` instead? Since we're only interested in the variance, I don't see why overflow errors in the covariance would be a major issue.

**Comment by tjof2** [comment]
Yeah @thomasaarholt  that's it - that's the issue + fix. I was looking at negative diagonals for overflow but dropped the ball on writing it properly!
