### ISSUE TITLE
get the error message when trying to load ser 

### ISSUE THREAD

**Issue by DeepHeisenberg** [hyperspy/hyperspy#2428]
Hi, i got the following error message when i was trying to load a **ser** data:

     74     """Read 4 bytes as *little endian* integer in file"""
     75     read_bytes = file.read(4)
---> 76     return struct.unpack('<L', read_bytes)[0]
     77 
     78 

error: unpack requires a buffer of 4 bytes

does anyone know the solution to this? thanks a lot!

**Comment by jat255** [comment]
Can you share the file, or some details on where it came from? Does it have an associated .emi file?

**Comment by DeepHeisenberg** [comment]
Thanks, yes
the code (running on google  colab) is:

import hyperspy.api as hs
x=hs.load('work1.ser')

[work1.zip](https://github.com/hyperspy/hyperspy/files/4807907/work1.zip)

Strange enough, this morning i ran it again and it gives me anothor error:

/usr/local/lib/python3.6/dist-packages/hyperspy/io.py in load(filenames, signal_type, stack, stack_axis, new_axis_name, lazy, convert_units, **kwds)
    215                                if os.path.isfile(f)])
    216         if not filenames:
--> 217             raise ValueError('No file name matches this pattern')
    218     elif not isinstance(filenames, (list, tuple)):
    219         raise ValueError(

ValueError: No file name matches this pattern

**Comment by tjof2** [comment]
> `ValueError: No file name matches this pattern`

Well that suggests the file path is wrong - are you certain the file exists? It is indeed a different problem to the original one.

**Comment by DeepHeisenberg** [comment]
> > `ValueError: No file name matches this pattern`
> 
> Well that suggests the file path is wrong - are you certain the file exists? It is indeed a different problem to the original one.

Yes thanks, indeed i realized i made a mistake in setting the path and fixed it.  
It turns out i can run the code on Colab :D
regarding the error: unpack requires a buffer of 4 bytes
I think the file itself is somehow corrupted. We exported the same image from TEM again and it works.
