### ISSUE TITLE
Introduce component.as_signal()

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#2442]
It would be good to be able to export the fit of each component, not just the entire model *or* the parameters.

Currently this is possible to do by performing the fitting, then deactivating all except one component, and then exporting the model `as_signal` activating only one component at a time.

**Comment by ericpre** [comment]
> Currently this is possible to do by performing the fitting, then deactivating all except one component, and then exporting the model `as_signal` activating only one component at a time.

This is not correct: there is no need to disable the component and the example from the docstring works fine:

https://github.com/hyperspy/hyperspy/blob/f4fec0d790b43ab2db17104ed359e2fa4cc3d048/hyperspy/model.py#L426-L461

```python
import hyperspy.api as hs
import numpy as np
s = hs.signals.Signal1D(np.random.random((10,100)))
m = s.create_model()
l1 = hs.model.components1D.Lorentzian(centre=20)
l2 = hs.model.components1D.Lorentzian(centre=40)
m.append(l1)
m.append(l2)
s1 = m.as_signal()
s2 = m.as_signal(component_list=[l1], parallel=False)
s1.plot()
s2.plot()
```

**Comment by thomasaarholt** [comment]
Ah! I hadn't realised that. I vaguely remember this from before. I'll leave the issue open, however, as this is something that would be nice to be able to do from a specific component directly.

**Comment by ericpre** [comment]
Since this is already possible using a more generic approach, I don't think, there is a need to duplicate it here, except if there is a good reason for it?

**Comment by tjof2** [comment]
Agree with @ericpre, if a good reason arises this can of course be reopened
