### ISSUE TITLE
masks for signal_range in fits

### ISSUE THREAD

**Issue by LMSC-NTappy** [hyperspy/hyperspy#2454]
I opened this issue to discuss whether the `model.set_signal_range` function should be modified to accept masks arrays or possibly signals, similar to what is used in `signal.decomposition` and `signal.spikes_removal_tool`.

I am in favor of this. My central argument is that it is easier to extend this approach to n-d signals. Also, would find it  "cleaner" than having set_signal_ranges functions with an increasing number of arguments, or `*args`. disjoint ranges can be set at once as well.

Original post on gitter
> Indeed, sorry for not going straight to the point ^^. I am using 2D models where it is currently not implemented. So I started an implementation and now I am stuck with a dilemma: either I extend the signature of `set_signal_range` to `set_signal_range(x11=None, x12=None, x21= None, x22 = None)` or I set the range with a bool array of the right shape: `set_signal_range(mask=None)`. This former choice presenting the advantage of being coherent with 1D implementation, the latter should be generalisable to ND which is an other advantage. So I was wondering if this discussion had been raised in 1D, and how the community would feel about such change of paradigm. Maybe there is a way to extend the function to `set_signal_range(self, x1=None, x2=None,mask=None)`, where passing a mask would override `x1` and `x2 ` but preserve their use for backward compatibility?

**Comment by LMSC-NTappy** [comment]
Quick update on this: 

I implemented `_set_signal_range_in_pixels(signal_mask)` in `model2D` with good results. 

Fitting works, model.as_signal() works (it resets the signal range like in model1D) and tests pass.

I will now try to make it more general. I propose to implement the changes in the following way, in both `model1D` and `model2D`:
- [ ] change `model.channel_switches` from a numpy array to a `Signal` instance obtained through `model.signal._get_signal_signal()`.
- [ ] `set_signal_range` signature can then be changed to `set_signal_range(self,*intervals,signal_mask=None)` and handle both Int, Float, 2-tuples arguments or a mask of the same shape as `channel_switches`
- [ ] `model.channel_switches.isig[] = True/False` can then be used to set ranges, `model.channel_switches.data` should be at all time strictly equivalent to the current numpy array

I don't know if any of this is in conflict with already planned development? I can get around the need to change channel_switches to a Signal instance but I have to admit it would make things really handy.

**Comment by ericpre** [comment]
If I understand correctly, your aim is to able to use arbitrary mask to define the fitting ranges. `channel_switches` is actually the mask, so you can simply do:
```python
m.channel_switches = your_mask
```
The only thing missing really is to document it in the user guide and in a couple of docstrings!

**Comment by LMSC-NTappy** [comment]
This is exactly it.

Even though it works already in 1D, it is unfortunately not possible for 2D models, where `m.channel_switches` , `m.xaxis `and `m.yaxis` rely on `np.meshgrid`

https://github.com/hyperspy/hyperspy/blob/8bef0e5ce60dd4d141899cc38c4cd0fe2b636367/hyperspy/models/model2d.py#L99-L104

I lacked time to work on this but I will try to PR something soon (In case anyone wonders, I need this feature for the modelling of my spectral maps, where I fit some features in the 2D imaging space and some others in the 1D spectral space)

**Comment by LMSC-NTappy** [comment]
Short update on this. PR #2556 adds support for what describes @ericpre.

**Comment by ericpre** [comment]
@LMSC-NTappy, now that you fixed the `channel_switches` bug in #2556, I would suggest to close this issue and continue the mask improvement discussion in #2208 or #2375. What do you think?

**Comment by LMSC-NTappy** [comment]
Absolutely! Separately, I will write some documentation for the user guide, as you mentioned
