### ISSUE TITLE
histogram doesn't allow iterables as a bins argument

### ISSUE THREAD

**Issue by pc494** [hyperspy/hyperspy#2475]
Numpy's histogram functionality (https://numpy.org/doc/stable/reference/generated/numpy.histogram.html) offers three types for bins:

```
bins : int or sequence of scalars or str, optional

If bins is an int, it defines the number of equal-width bins in the given range (10, by default).
If bins is a sequence, it defines a monotonically increasing array of bin edges, including the rightmost edge,
allowing for non-uniform bin widths.
```

The wrapping in hist_tools isn't set up to handle arrays, and currently (I think) will also throw an error on an `int` as the `.get` method needs a hashable object.

```
 if isinstance(a, da.Array):
        return histogram_dask(a, bins=bins, max_num_bins=max_num_bins, **kwargs)

    _deprecated_bins = {"scotts": "scott", "freedman": "fd"}
    new_bins = _deprecated_bins.get(bins, None)
```
I think the wrap should handle all three cases and would be happy to write a fix.

**Comment by tjof2** [comment]
@pc494 Can you add a test or two along with the fix? Evidently the existing ones didn't check for this and it was overlooked. Thanks for catching this!

Presumably it just needs the handling for anything that is `np.iterable` moved to above the `.get()`?
