### ISSUE TITLE
Incorrect ylim on m.plot(True) when stepping through indices

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#2481]
When stepping through a multidimensional Signal1D, the `ylim` on the Signal plot resizes to the size of the final component in the model. I would expect it to keep track of the lowest value and the highest value of all the spectra that are plotted, and then set `plt.ylim(lowest, highest)`

In the example below, the horizontal red line is the signal data (`s`), the blue gaussian is the total model fit, and the green and red gaussians are the first and second components, respectively. In the second image, where I have stepped forward one index, the ylim currently scales to the red gaussian, hiding the rest of the plot.

```python
# %matplotlib widget
import hyperspy.api as hs
import numpy as np
from hyperspy.components1d import GaussianHF

data = np.ones((3, 200,))
s = hs.signals.Signal1D(data)

m = s.create_model()
G1 = GaussianHF(height=3, centre = 50, fwhm=20)
G2 = GaussianHF(height=2, centre = 50, fwhm=20)
m.extend([G1, G2])
m.plot(plot_components=True)
```

<img src="https://user-images.githubusercontent.com/2721423/90026393-882d0880-dcb7-11ea-9289-b31d6eefccc8.png" height="300">
<img src="https://user-images.githubusercontent.com/2721423/90026394-88c59f00-dcb7-11ea-956c-dc5c56757f56.png" height="300">

**Comment by ericpre** [comment]
Indeed, I have seen a couple of times, this should be fixed in #2501.
