### ISSUE TITLE
Widget created and removed: unnecessary message

### ISSUE THREAD

**Issue by AEljarrat** [hyperspy/hyperspy#2505]
# Issue description
Since my last update whenever I add or remove a ROI widget to a signal plot some messages are printed. I believe these messages are annoying, and would like to hide them as the default option. The main reason is that I have applications in which many ROI widgets are added and removed, unnecessarily polluting the output. There's maybe a reason for these messages, although it escapes my understanding. 

# Example of this issue
```python
img = hs.signals.Signal2D(np.random.random([64, 64]))
img.plot()
lroi = hs.roi.Line2DROI(10, 10, 20, 20, linewidth=5)
s = lroi.interactive(img)
s.plot()
>>> using interactive roi
>>> removing widget
```

**Comment by ericpre** [comment]
These shouldn't be there...most likely left over from debugging something, they simply need to be removed!

**Comment by ericpre** [comment]
Actually, a git blame shows that I am the one to be blamed! 😱😅
https://github.com/hyperspy/hyperspy/blame/5e8cdbb3e7a3aa6d76bcdd7b0ba45c2dd1345660/hyperspy/roi.py#L488

**Comment by AEljarrat** [comment]
Thanks for the quick fix @ericpre!
