### ISSUE TITLE
fei.py cannot handle multiple .ser files due to metadata failure

### ISSUE THREAD

**Issue by jat255** [hyperspy/hyperspy#2530]
Another weird error for the `fei.py` reader discovered from one of our microscopes...

Under certain conditions (I'm not exactly sure how), TIA will write one `.emi` file and greater than one `.ser` file. The `.emi` file will only have one `<ObjectInfo>` element in its metadata however, which will cause an error at [line 281](https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/hyperspy/io_plugins/fei.py#L281).

The error condition arises because `ser_files` will have a length > 1, while `objects` will be length = 1. This causes `objects[index]` to raise an `IndexError` since `index` is too large for the `objects` list. Some more defensive programming here would allow the reader to be more robust to this condition.

**Comment by francisco-dlp** [comment]
Closed by #2531
