### ISSUE TITLE
fei.py coerces metadata values to float no matter their value

### ISSUE THREAD

**Issue by jat255** [hyperspy/hyperspy#2532]
Apologies, as I should have probably made all these FEI reader things one issue...

Another "feature" of TIA on one of our microscopes is that it will write non-decimal values for certain metadata values (for mysterious reasons). This causes a hard failure at [line 229](https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/hyperspy/io_plugins/fei.py#L229) of `fei.py` due to a `ValueError`. A better approach would be to be more defensive and try the conversion, but accept values that fail, since a bogus metadata value should not prevent reading of the whole file.

**Comment by francisco-dlp** [comment]
Closed by #2533
