### ISSUE TITLE
hyperspy 1.6.0 fails on mybinder 

### ISSUE THREAD

**Issue by jan-janssen** [hyperspy/hyperspy#2547]
With the switch from hyperspy 1.5.2 to 1.6.0 it seems like the dependencies increased drastically resulting in mybinder reaching the memory limit during the resolution of the conda dependencies: 
https://github.com/jan-janssen/hyperspy-mybinder-bug
This is unfortunate as I was using mybinder to share hyperspy based examples, but those no longer work with 1.6.0 and require 1.5.2 instead.

**Comment by francisco-dlp** [comment]
I've tried your example and it just worked for me. 
As far as I can tell, hyperspy's dependencies didn't increase drastically in the last release. However, the increasing number of packages in conda-forge is known to slow down conda's environment resolution, see https://github.com/conda/conda/issues/8197

**Comment by ericpre** [comment]
They may be several way to speed up solving the environment if this is an issue:
- install `hyperspy-base` instead of `hyperspy`
- set `defaults` higher priority than `conda-forge`? Not really sure if it will be useful in this case but it may be worth giving a try
- get mamba to work on mybinder...
