### ISSUE TITLE
Scalebar does not display upon mirroring axis

### ISSUE THREAD

**Issue by LMSC-NTappy** [hyperspy/hyperspy#2557]
Upon mirroring an axis, the scalebar on the display does not display anymore.

```python
#generate a sample gaussian lineshape dataset
shape = (8,4,1000)
dat = np.zeros(shape)
for i in range(shape[0]):
    for j in range(shape[1]):
        dat[i,j,:] = np.histogram(np.random.normal(360,8,int(1e5)),bins=1000,range=(300,800))[0].astype('int32')
ax0 = {'size': shape[1], 'name':'X', 'units':'um', 'scale':1.05, 'offset':0, 'navigate': True}
ax1 = {'size': shape[0], 'name':'Y', 'units':'um', 'scale':1.05, 'offset':0, 'navigate': True}
ax2 = {'size': 1000, 'name':'WL', 'units':'nm', 'scale':0.5, 'offset':300, 'navigate': False}

a = hs.signals.Signal1D(dat,axes=[ax1,ax0,ax2])
a.metadata.General.title = "a"

b = a.inav[:,::-1]
b.metadata.General.title = "b"

a.plot(scalebar=True)
b.plot(scalebar=True)
````

![image](https://user-images.githubusercontent.com/37581871/95170097-346d0600-07b4-11eb-9252-e96af6435faf.png)

The annotation position must not be adapted to the new axis values. I've noticed that upon running

```python
bprime = a.inav[:,::-1]
bprime.axes_manager[1].scale = a.axes_manager[1].scale
bprime.axes_manager[1].offset = a.axes_manager[1].offset
bprime.metadata.General.title = "b prime"

bprime.plot()
```

The bug disappears

![image](https://user-images.githubusercontent.com/37581871/95170457-c1b05a80-07b4-11eb-8e5f-35aeaa1d03a5.png)

Any insight on how to patch this? It's probably a simple trait update missing but I couldn't find it.
Also, possible link with #1228 ?

Best Regards

Nico

**Comment by ericpre** [comment]
Could it because the two axis doesn't have the same scale anymore? One of the two in `b` is now negative?

**Comment by ericpre** [comment]
#1228 should be a different issue to do with how the scale bar is anchored or not, or something along these lines.
