### ISSUE TITLE
some problems when using 'align_zero_loss_peak' for my data

### ISSUE THREAD

**Issue by PhysXu** [hyperspy/hyperspy#2571]
I have tried to align my EELS ZLP by using _**align_zero_loss_peak(subpixel=True, signal_range=(-0.15,0.15), crop=True)**_，but had some problems:
Some data points on the left of ZLP always are cropped by this process, seeing below:
This is the raw data before _**align_zero_loss_peak**_:
![image](https://user-images.githubusercontent.com/35793078/97996861-3eba0880-1e23-11eb-8192-98e2bc3e28f9.png)

This is the data after _**align_zero_loss_peak**_:
![image](https://user-images.githubusercontent.com/35793078/97996909-50031500-1e23-11eb-9ec8-84954724a053.png)

Because those spectra have features in the gain part (left parts of ZLP), I also tried it with _**crop=False**_.
The result is strange, seeing below:
![image](https://user-images.githubusercontent.com/35793078/97998102-aa50a580-1e24-11eb-82e5-b175852ac96a.png)

Any suggestions for me to fix these problems?
Thanks!

PS: the display of my raw data:
![image](https://user-images.githubusercontent.com/35793078/97998446-0f0c0000-1e25-11eb-8340-7af92a92fb86.png)

**Comment by ericpre** [comment]
Can you provide a minimum reproducible example?

**Comment by PhysXu** [comment]
> Can you provide a minimum reproducible example?

Hi, ericpre, thanks for your reply.
Please check the attached file.
[Crop data.zip](https://github.com/hyperspy/hyperspy/files/5485079/Crop.data.zip)

I loaded it into HyperSpy by _**s = hs.load('filename').as_signal1D(0)**_, so that I can use _**align_zero_loss_peak**_.
Thanks again!

**Comment by PhysXu** [comment]
> Can you provide a minimum reproducible example?

BTW, if I want to know how the function of _**align_zero_loss_peak**_ works, I mean that the codes in it.
Where can I find the answer?
Thanks!

**Comment by thomasaarholt** [comment]
You can search for the function name here on GitHub. The code you're interested in is here: https://github.com/hyperspy/hyperspy/blob/ebe06c043fa637a2cfca2c16e4909ca5a3fcf205/hyperspy/_signals/eels.py#L314

**Comment by ericpre** [comment]
The following is working fine:

```python
import hyperspy.api as hs

s = hs.load('Crop data.dm3')
s = s.as_signal1D('x')
s.set_signal_type('EELS')
s.align_zero_loss_peak(signal_range=[0.0, 0.05])
```

**Comment by PhysXu** [comment]
> The following is working fine:
> 
> ```python
> import hyperspy.api as hs
> 
> s = hs.load('Crop data.dm3')
> s = s.as_signal1D('x')
> s.set_signal_type('EELS')
> s.align_zero_loss_peak(signal_range=[0.0, 0.05])
> ```

Thanks very much, it works well.
Additional question: how to determine the suitable _**signal_range**_ .

**Comment by thomasaarholt** [comment]
@PhysXu I suggest you read the docstring of the function, and see if that answers your question :)
