### ISSUE TITLE
Writing to USID not working?

### ISSUE THREAD

**Issue by din14970** [hyperspy/hyperspy#2573]
Is writing to USID supported? From the [v1.6.0 user guide](https://hyperspy.org/hyperspy-doc/current/user_guide/io.html#writing) I gather writing should be supported with `signal.save(filename.h5)`. However, I get the message:
```
ValueError: .h5 does not correspond to any supported format. Supported file extensions are: hspy, png, unf, tif, nxs, blo, emd, msa and rpl
```

**Comment by din14970** [comment]
Nevermind it's just because `pyUSID` was not installed. Maybe a better error message warning users of this might be helpful. The writing is still not working but this seems to be a pyUSID issue.

**Comment by ericpre** [comment]
Indeed, the error message should definitely be improved and we should test against it - using the _minimum requirement_ build on travis.
