### ISSUE TITLE
Mass thickness unit in CL absorption correction in TEM-EDS quantification 

### ISSUE THREAD

**Issue by petergraat** [hyperspy/hyperspy#2575]
It seems that the mass thickness returned by the CL_get_mass_thickness method in the _signals/eds_tem.py file has the wrong unit. That method should return the mass thickness in kg/m2. But I think it returns the mass thickness in g/cm2. On line 911 in eds_tem.py:
```python
elemental_mt = element_composition * thickness_map * 1E-9 * density
```
the elemental mass thickness is calculated as the product of composition (in %), thickness (in nm) and density (in g/cm3) and a factor of 1e-9 to get from % to fraction (1e-2) and from nm to cm (1e-7), resulting in a mass thickness in g/cm2.

**Comment by k8macarthur** [comment]
Hi Peter, thanks for flagging. So density in g/cm3 is the same as kg/m3 which means the equation is:
kg/m2 = unit_less * nm * 1E-9 * kg/m3
Therefore I don't think this is the origin of the error you found on Gitter.

**Comment by k8macarthur** [comment]
Good spot! @petergraat maybe you could make a quick pull request to fix this. I rarely use the CL section of the code so it's great that someone it trying it out!

**Comment by k8macarthur** [comment]
I think 1E-9 should be changed to 1E-6. g/cm3 *1E3 = kg/m3.

**Comment by ericpre** [comment]
I had a look at this yesterday and came up with a different number - see #2580.

**Comment by ericpre** [comment]
Done in #2580.
