### ISSUE TITLE
Loading data not working

### ISSUE THREAD

**Issue by sulaymandesai** [hyperspy/hyperspy#2582]
Hi, 

I am trying to load this mtrx file and python comes with an error 'module 'hyperspy' has no attribute 'load'. 

```
s = hs.load(r'default_2017Jun09-162147_STM-STM_Spectroscopy--180_1.I(V)_mtrx')
```

Above is my code. Any help would be appreciated. Thanks!

Best wishes,
Sulayman

**Comment by hakonanes** [comment]
How did you import HyperSpy? The load function is available from `hyperspy.api.load()`, so you need to import like this

```python
>>> import hyperspy.api as hs
>>> s = hs.load()
```

**Comment by sulaymandesai** [comment]
ahh ok I did:
```
import hyperspy as hs
```

Thanks. It worked.

**Comment by hakonanes** [comment]
Glad it worked, @sulaymandesai!
