### ISSUE TITLE
travis CI situation

### ISSUE THREAD

**Issue by ericpre** [hyperspy/hyperspy#2591]
https://travis-ci.community/t/org-to-com-migration-deadline/10260
https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
https://docs.travis-ci.com/user/migrate/open-source-repository-migration

We are currently on travis-ci.org which will close in December 2020. There are two solutions:
- migrate travis-ci.com
- migrate to github action

I would be in favour of migrating to github action, because:
- this is working nicely
- this is much easier to use and now seems mature enough
- it has significantly higher capacity than travis CI.

**Comment by pc494** [comment]
If you hadn't seen https://github.com/pyxem/pyxem/issues/661 the migration to `.com` came with lots of problems, and pyxem is currently looking for a new CI option.

EDIT: And github action does look pretty good (compared to the other things out there at least) - how much build time are you currently getting from them?

**Comment by ericpre** [comment]
Thanks @pc494, sounds like github action would be a better option then!

**Comment by ericpre** [comment]
Done in #2592
