### ISSUE TITLE
signal_type='DigiScan'

### ISSUE THREAD

**Issue by yy-ssang** [hyperspy/hyperspy#2606]
I upgrade my hyperspy from 1.5.2 to 1.6.1.
However, there is some error in loading dm4 image with the message 'WARNING:hyperspy.io:`signal_type='DigiScan'` not understood. See `hs.print_known_signal_types()` for a list of known signal types, and the developer guide for details on how to add new signal_types.' 
This error didn't occur at hyperspy 1.5.2.

Is there any solution about that? Thank you.

**Comment by thomasaarholt** [comment]
Could you provide an example signal?

**Comment by yy-ssang** [comment]
[15MX 200kV Image1 1268.zip](https://github.com/hyperspy/hyperspy/files/5747273/15MX.200kV.Image1.1268.zip)

@thomasaarholt  This is the image file that have the problem. Thank you!

**Comment by ericpre** [comment]
This is a warning and this can be safely ignored!

**Comment by ericpre** [comment]
Fixed in #2608.
