### ISSUE TITLE
Take off angle calculation fails in auto mode

### ISSUE THREAD

**Issue by CorentinLG** [hyperspy/hyperspy#2609]
When running quantification on a EDS data acquired on velox (HS 1.6.1),  the calculation of the take off angle in auto mode leads to an error.  I think this is because the value of the tilt angles of the stage are of the type strings instead of float. The values appears to be imported from the metadata (which are strings), through the get_item function. 
See here : https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/hyperspy/_signals/eds.py#L722

**Comment by ericpre** [comment]
Do you have an example to reproduce? Is it related to #2610?

**Comment by ericpre** [comment]
The stage tilt values of velox emd file are parsed as float value:
https://github.com/hyperspy/hyperspy/blob/3bd9622593da8e377ce9c9979e83b82b1fa52aa0/hyperspy/io_plugins/emd.py#L1512-L1517

We need an example to reproduce.
