### ISSUE TITLE
Confusion between tilt stage and tilt_alpha

### ISSUE THREAD

**Issue by CorentinLG** [hyperspy/hyperspy#2610]
Reading velox files, the imported metadata include both a tilt stage value and a tilt_alpha value. I think it should be the same, isn't it ?
If that's correct, maybe we should use only alpha, beta and the elevation angle for simplication. Based on these three, the take-off angle can be recalculated.

**Comment by ericpre** [comment]
> Reading velox files, the imported metadata include both a tilt stage value and a tilt_alpha value. 

I can't reproduce, can you provide an example of velox file which have the "tilt stage" you are referring to? For example, from one of my velox EDS spectrum image:
```python
>>> s.metadata
├── Acquisition_instrument
│   └── TEM
│       ├── Detector
│       │   └── EDS
│       │       ├── azimuth_angle = 0.0
│       │       ├── elevation_angle = 35.0
│       │       ├── energy_resolution_MnKa = 130.0
│       │       └── number_of_frames = 170
│       ├── Stage
│       │   ├── tilt_alpha = -6.043
│       │   ├── tilt_beta = 10.01
│       │   ├── x = 4e-05
│       │   ├── y = 0.000155
│       │   └── z = 8e-06
│       ├── beam_energy = 200.0
│       ├── camera_length = 91.1
│       ├── magnification = 160000.0
│       └── microscope = Titan
├── General
│   ├── date = 2019-06-07
│   ├── original_filename = SI EDS-HAADF 1019.emd
│   ├── time = 09:19:37
│   ├── time_zone = GMT
│   └── title = EDS
├── Sample
│   └── elements = ['O', 'Si', 'Mn', 'Fe', 'Ni']
└── Signal
    ├── binned = True
    └── signal_type = EDS_TEM

>>> s.get_take_off_angle()
28.475
```

**Comment by CorentinLG** [comment]
This is weird, 
Maybe because It is a different velox version? This spectrum image data was acquired in Nov 2019 (ca't remeber which Velow version was installed at the time)

` eds.metadata

    Acquisition_instrument
        TEM
            Detector
            Stage
                tilt_alpha = 0.005
                tilt_beta = 0.000
                x = 0.000336
                y = 0.000055
                z = -0.000172
            beam_energy = 300.0
            camera_length = 115.9
            magnification = 40000.0
            microscope = Titan
            tilt_stage = 0
 `

**Comment by ericpre** [comment]
Do you have a file to share to reproduce?

**Comment by ericpre** [comment]
Needs a file to reproduce. Re-open when you have such a file.
