### ISSUE TITLE
Add update instructions

### ISSUE THREAD

**Issue by ericpre** [hyperspy/hyperspy#2618]
Some suggestion from @NathalieBrun in https://gitter.im/hyperspy/hyperspy?at=5ff87239252c0a6dedf9de1d to improve the installation instruction in the user guide:
- add section about updating hyperspy
- specify version

Since a couple of month, `conda-forge` is fully independent of anaconda `defaults` channel, and using `conda-forge` only channel will simplify a *lot* updating pacakges on all platforms because these two channels are not fully compatible, there may some corner case with issues and in some situation conda may struggle to resolve the dependencies incompatibilities...

Recommending users to install the hyperspy-bundle or [miniforge](https://github.com/conda-forge/miniforge) over miniconda/anaconda will avoid having the anaconda `defaults` channel and the issues related to it.
The only remaining advantage of using the anaconda distribution is the [`anaconda-navigator`](https://docs.anaconda.com/anaconda/navigator/). Since it is not open-source, it can't de distributed through conda-forge and this means that since it is built against qt, it doesn't always play well with packages of the `conda-forge` and can cause trouble with solving environment. There alternative such as [nb_conda](https://github.com/Anaconda-Platform/nb_conda) or [gator](https://github.com/mamba-org/gator), which will be a good alternative once it has mature enough!

**Comment by ericpre** [comment]
Done in #2621.

**Comment by jlaehne** [comment]
Could be closed now.

**Comment by ericpre** [comment]
Indeed, thanks!
