### ISSUE TITLE
s.export_bss_results save_figures bug?

### ISSUE THREAD

**Issue by winston-song** [hyperspy/hyperspy#2619]
When I use 
cl_ex.export_bss_results(comp_ids=[3],save_figures=False), the bss model is saved in .hspy

When change to 
cl_ex.export_bss_results(comp_ids=[3],save_figures=True), so that I can export .png files, but there is error

IndexError                                Traceback (most recent call last)
IndexError: index 3 is out of bounds for axis 1 with size 1

anyone can help answer?

**Comment by ericpre** [comment]
I can't reproduce. Can you provide a minimum example and the full traceback?

**Comment by winston-song** [comment]
> I can't reproduce. Can you provide a minimum example and the full traceback?

sorry Eric, I forget to update, I restart the kernel and it works, I run too manu jupyters at the same time.
