### ISSUE TITLE
change_dtype and rechunking of lazy signals

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#2637]
Currently when using `change_dtype` on a lazy signal, an automatic rechunking is done by the function. For large datasets, this can have some sub-optimal consequences.

For example (using the nice `compute_navigator` from https://github.com/hyperspy/hyperspy/pull/2631):

```python
import hyperspy.api as hs

# Size: (512, 512, 256, 256). Chunks: (32, 32, 32, 32)
s0 = hs.load("test_experimental_data0.hspy", lazy=True)
s0.change_dtype('float32', rechunk=False)

s0.compute_navigator() # 3.9 s, chunksize (32, 32, 32, 32)
s0T = s0.T
s0T.compute_navigator() # 1.0 s, chunksize (32, 32, 32, 32)

# Size: (512, 512, 256, 256). Chunks: (32, 32, 32, 32)
s1 = hs.load("test_experimental_data1.hspy", lazy=True)
s1.change_dtype('float32', rechunk=True)

s1.compute_navigator() # 181 s, chunksize (16, 16, 256, 256)
s1T = s1.T
s1T.compute_navigator() # 0.8 s, chunksize (256, 256, 16, 16)
```

| Rechunk	| Transpose	| `compute_navigator()`	| `plot()`	|	Chunksize		|
| -----		| -----		| ---			| ---		|	-----			|
| False		| False		| 3.9 s			| 1.4 s		|	(32, 32, 32, 32)	|
| False		| True		| 1.0 s			| 3.0 s		|	(32, 32, 32, 32)	|
| True		| False		| 181 s			| 0.9 s		|	(16, 16, 256, 256)	|
| True		| True		| 0.8 s			| 180 s (use 50 GB memory!)		|	(256, 256, 16, 16)	|

Thus, running `change_dtype(rechunk=True)` increases the time to compute the navigator by 460%.
In addition, while the transpose + rechunk doesn't look bad time wise, actually plotting the signal (`s1T.plot`) requires 1/4 of the dataset to be loaded into memory, as the navigation dimension chunks are so large.

------------------------------------------
I'm not sure what the best solution is... The thing which is causing this is that the automatic rechunking tries to put the signal dimensions within one chunk. So there are two main options:

- Make the automatic rechunking "balance" the chunks across the navigation and signal dimensions, so that the chunks does not span the whole signal dimension
- Disable automatic rechunking for certain datatypes and functions, for example `Signal2D` or `change_dtype`.

The last option assumes that the file or file loading sets reasonable chunk sizes, and I'm not sure if this is always valid.

**Comment by ericpre** [comment]
Can you provide a reproducible example - including the creation of the file if necessary?

**Comment by magnunor** [comment]
If a dataset on Zenodo is ok, this can be used: https://zenodo.org/record/4312960/files/fe60al40_stripe_pattern.hspy?download=1 (6 GB file)

If not, I can make a script to generate the test dataset.

Slightly modified script for testing with this file.

```python
import time
import hyperspy.api as hs

def test_compute_navigator(signal):
    t0 = time.time()
    signal.compute_navigator(show_progressbar=False)
    print("s.compute_navigator(): {0}".format(time.time() - t0))

def test_plot_runtime(signal):
    t0 = time.time()
    signal.plot()
    print("s.plot(): {0}".format(time.time() - t0))

# Dataset from: https://zenodo.org/record/4312960/files/fe60al40_stripe_pattern.hspy?download=1
s0 = hs.load("fe60al40_stripe_pattern.hspy", lazy=True)
s0.change_dtype('float32', rechunk=False)

print("Rechunk=False, transpose=False")
test_compute_navigator(s0)
test_plot_runtime(s0)
s0T = s0.T
print("Rechunk=False, transpose=True")
test_compute_navigator(s0T)
test_plot_runtime(s0T)
s0.close_file()

s1 = hs.load("fe60al40_stripe_pattern.hspy", lazy=True)
s1.change_dtype('float32', rechunk=True)

print("Rechunk=True, transpose=False")
test_compute_navigator(s1)
test_plot_runtime(s1)
s1T = s1.T
print("Rechunk=True, transpose=True")
test_compute_navigator(s1T)
test_plot_runtime(s1T)
```

**Comment by ericpre** [comment]
Generating dataset with parameters we can change easily would be more useful indeed to figure out what is going on.
Also it could be used as part of a benchmark (https://github.com/hyperspy/hyperspy/issues/2469, https://github.com/hyperspy/hyperspy/pull/2480)

**Comment by magnunor** [comment]
This can be made with various degrees of complexity. From the simple with just random data:

```python
import dask.array as da
import hyperspy.api as hs
chunks = (32, 32, 32, 32)
dask_array = da.random.random((256, 256, 256, 256), chunks=chunks)
s = hs.signals.Signal2D(dask_array).as_lazy()
s.save("test_data.hspy", chunks=chunks)
```

Which might not be very representative for typical data. In addition, it compresses really badly.

There is also this script I made when implementing beam-centering functionality in pyxem. Not implemented in a very "elegant" way, as the dataset could probably be directly written to a HyperSpy compatible file.

```python
import numpy as np
from tqdm import tqdm
import h5py
import dask.array as da
import pyxem as pxm

#################################################
f = h5py.File("001_test_data_256x256.hdf5", mode='w')
data = f.create_dataset(
        'data', shape=(256, 256, 256, 256), dtype=np.uint16, chunks=(32, 32, 32, 32),
        compression='gzip')

x_pos_list = np.linspace(128-20, 128+20, 256, dtype=np.uint16)
y_pos_list = np.linspace(128-40, 128+40, 256, dtype=np.uint16)

image = np.zeros((256, 256), dtype=np.uint16)
pbar = tqdm(total=256*256)

for ix_cube in range(8):
    for iy_cube in range(8):
        data_cube = np.zeros((32, 32, 256, 256), dtype=np.uint16)
        for ix in range(32):
            for iy in range(32):
                ix_pos = ix_cube * 32 + ix
                iy_pos = iy_cube * 32 + iy
                x_pos = x_pos_list[ix_pos]
                y_pos = y_pos_list[iy_pos]
                image[x_pos, y_pos] = 10
                data_cube[ix, iy, :, :] = image
                image[x_pos, y_pos] = 0
                pbar.update(1)
        data[ix_cube*32:(ix_cube+1)*32, iy_cube*32:(iy_cube+1)*32, :, :] = data_cube
        del data_cube

f.close()

#################################################
dask_array = da.from_array(h5py.File("001_test_data_256x256.hdf5")['data'], chunks=(32, 32, 32, 32))
s = pxm.LazyDiffraction2D(dask_array)
s.save("001_test_data_256x256.hspy", chunks=(32, 32, 32, 32), overwrite=True)
```

I also made a rather complicated function in pixstem, which is now in pyxem for making artificial 4-dimensional datasets: https://github.com/pyxem/pyxem/blob/master/pyxem/dummy_data/make_diffraction_test_data.py#L1086

**Comment by ericpre** [comment]
I guess, the relevant parameters here are the `dtype` and the `chunks`, it doesn't matter if there are zeros everywhere.

I don't know why the default of rechunk in `change_dtype` is `True`, and it should be `"dask_auto"` or `False` because this operation is too generic to have a default which set large chunks to to the signal space. Reading what was discuss in previous PR (#1995 and #1986) seems to implies that this should be the case!

**Comment by ericpre** [comment]
Done in #2645.
