### ISSUE TITLE
Signal slicing, transposing and navigator signal

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#2640]
Replotting a signal with a navigator signal produces an error, after using `.inav` (the latest `RELEASE_next_patch`, with https://github.com/hyperspy/hyperspy/pull/2631):

```python
import dask.array as da
import hyperspy.api as hs
s = hs.signals.Signal2D(da.random.random((10, 10, 100, 100))).as_lazy()
s.plot()
s1 = s.inav[:5, :5]
s1.plot()
```

This gives the error: `ValueError: The dimensions of the provided (or stored) navigator are not compatible with this signal.`

Likewise for transposing:
```python
sT = s.T
sT.plot()
```
Gives the same error.

------------------------------
I think the easiest way for solving the issue for `.inav`, is cropping the navigator signal if it exist.

For the `.T`, I think the easiest way is to remove the `navigator` in the new signal.

**Comment by magnunor** [comment]
This also extends to other methods where the metadata is copied:

```python
s.plot()
s_sum = s.sum(axis=0)
s_sum.plot()
```
Gives `ValueError: The dimensions of the provided (or stored) navigator are not compatible with this signal.`

**Comment by ericpre** [comment]
Yes, we should delete the navigator when performing these operations. In #2631, I have changed the error message so that it is clear that the navigator needs to recalculated! ;)

**Comment by ericpre** [comment]
Done in #2644.
