### ISSUE TITLE
Radial Integration of Signal2Ds

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#2643]
For working with Diffraction data, it would be really nice to have a Radial Profile ROI feature, similar to CircleROI, which can integrate radially on an image.

**Comment by ericpre** [comment]
Just to clarify a ROI doesn't perform any signal calculation and ROIs are designed to "slice" signal so that it can be either plotted or an operation can be applied to it. What would a "RadialProfileROI" do?

The `Line2DROI` has a `profile_line` method, maybe you mean something similar?

**Comment by thomasaarholt** [comment]
I might have gotten a little carried away with what the hyperspy ROI concept should be used for :)

The purpose would be to turn the image on the left into the plot on the right, where the origin on the plot is the centre of the image.

![image](https://user-images.githubusercontent.com/2721423/107635223-12582880-6c6b-11eb-91b3-c54955e08ede.png)

Diffraction patterns (especially taken with TEM) are often not centered on the image, so there some room for an interactive ROI that a user could move on the image to define the centre. It's probably better to combine CircleROI with `events`/`observe` and a radial integration function.

**Comment by thomasaarholt** [comment]
If anyone is interested in having a go at this, I found a [numpy approach on stackoverflow](https://stackoverflow.com/questions/21242011/most-efficient-way-to-calculate-radial-profile):

```python
import numpy as np

def radial_profile(data, center):
    y, x = np.indices((data.shape))
    r = np.sqrt((x - center[0])**2 + (y - center[1])**2)
    r = r.astype(np.int)

    tbin = np.bincount(r.ravel(), data.ravel())
    nr = np.bincount(r.ravel())
    radialprofile = tbin / nr
    return radialprofile
```

Here `data` would be `s.data`, and the `center` could be gotten from value of `CircleROI.cx` and `.cy`, in pixel units.

**Comment by ericpre** [comment]
> Diffraction patterns (especially taken with TEM) are often not centered on the image, so there some room for an interactive ROI that a user could move on the image to define the centre. It's probably better to combine CircleROI with events/observe and a radial integration function.

Then, this is just a matter of finding the center and there would be better way than positioning a ROI by hand.

For radial integration, I am not sure this is generic enough to be added to `Signal2D` and instead it should be done by an extension For example, I would check what pyxem can do - see for example https://github.com/pyxem/pyxem-demos.

**Comment by ericpre** [comment]
Considering that pyxem provides this functionality, should this PR be closed?

**Comment by thomasaarholt** [comment]
Thanks, yes.
