### ISSUE TITLE
When loading EMD files (NCEM v0.2), axes are interpreted differently in 1.5.2 and 1.6.1

### ISSUE THREAD

**Issue by uellue** [hyperspy/hyperspy#2650]
## How to reproduce

Open a EMD HDF5 file following the [format for version 0.2](https://emdatasets.com/format/#EMDcont): `hs.load(emd_path, lazy=True)` with Hyperspy version 1.5.2 and version 1.6.1

## What happens

* 1.5.2: `<BaseSignal, title: /experimental/science_data, dimensions: (|128, 128, 256, 256)>`
* 1.6.1: `<LazySignal, title: science_data, dimensions: (|256, 256, 128, 128)>`

1.6.1 interprets the axes differently than 1.5.2. This can make scripts that worked fine with the previous behavior throw errors or return nonsensical results. In the worst case the script will continue to run without errors and the nonsensical results pass unnoticed.

## What should happen

The behavior remains consistent or the code throws an error unless the new behavior is explicitly activated.

Is this possibly related to adding support for EMD (NCEM) in 1.6?

**Comment by ericpre** [comment]
Most likely related to https://github.com/hyperspy/hyperspy/pull/2396. This may be contentious but I suspect that the previous behaviour could be considered as a bug - this is off the top of my head and would need to look into details.

**Comment by uellue** [comment]
Thx for the quick feedback!

> I suspect that the previous behaviour could be considered as a bug

Uff, that is one of the nasty bugs where people started to code around it and evidently learned to expect the "wrong" behavior... At least it is documented now.

**Comment by ericpre** [comment]
Closing for now. Please re-open if you would like to discuss alternative(s).
