### ISSUE TITLE
Better handling of changelog

### ISSUE THREAD

**Issue by ericpre** [hyperspy/hyperspy#2674]
Since the 1.6.1 release, we are adding an entry to the changelog for each PR in order to make release more easily (and more often!). However, this creates conflict in the changelog... I was not sure how painful it would be and I do find it quite annoying! Therefore, I would suggest that after 1.6.2, we change the way we manage the changelog.

It would be good to know what alternatives are available and what others libraries are doing. Here is the beginning of a list:
- [rever](https://regro.github.io/rever-docs/) 
- [towncrier](https://github.com/twisted/towncrier)

Relevant discussion/PR:
- https://github.com/h5py/h5py/issues/1835
- https://github.com/scikit-image/scikit-image/issues/4544
- https://github.com/napari/napari/pull/1138

**Comment by jlaehne** [comment]
- https://github.com/sympy/sympy/pull/14942

**Comment by ericpre** [comment]
Done in #2717.
