### ISSUE TITLE
Bruker M6 Jetstream SPX file type not supported

### ISSUE THREAD

**Issue by ffsedd** [hyperspy/hyperspy#2689]
Structure of M6 Jetstream SPX is different, there is node "TRTESMAHeader"

Voltage and Angle data are stored in node "RTXrfHeader"

During load of SPX file following error is raised:

  File "/home/m/.local/lib/python3.8/site-packages/hyperspy/io_plugins/bruker.py", line 995, in spx_reader
    spectrum = EDXSpectrum(sp_node)
  File "/home/m/.local/lib/python3.8/site-packages/hyperspy/io_plugins/bruker.py", line 536, in __init__
    self.esma_metadata = dictionarize(esma_header)
  File "/home/m/.local/lib/python3.8/site-packages/hyperspy/io_plugins/bruker.py", line 469, in dictionarize
    d = {t.tag: {} if t.attrib else None}
AttributeError: 'NoneType' object has no attribute 'tag'

Spectrum can be loaded without errors with this code inserted at line 540 in bruker.py:

        if esma_header:
            self.esma_metadata = dictionarize(esma_header)
        else:
            xrf_header = TRTHeader.find(
            "./ClassInstance[@Type='TRTXrfHeader']")

            xrf_header_dict = dictionarize(xrf_header)
            self.esma_metadata = {'PrimaryEnergy':xrf_header_dict['Voltage'],
                                  'ElevationAngle':xrf_header_dict['ExcitationAngle']}

[bruker_m6_jetstream_file_example.zip](https://github.com/hyperspy/hyperspy/files/6188503/bruker_m6_jetstream_file_example.zip)

**Comment by ericpre** [comment]
Thanks @ffsedd, would you be interested in making a pull request to incorporate the changes you are suggesting? If so, a good place to start is to have a look at the [developer guide](https://hyperspy.readthedocs.io/en/latest/dev_guide/intro.html) and we can guide you through it.
A [patch release](https://github.com/hyperspy/hyperspy/milestone/42) is almost completed and your fix could be included in it, if done in the next couple of days.

Your example file is small enough to be added readily to the test suite.

**Comment by ffsedd** [comment]
Fix works perfectly, thanks!!!
