### ISSUE TITLE
integrate1D of binned signals

### ISSUE THREAD

**Issue by jlaehne** [hyperspy/hyperspy#2735]
For binned signals, `integrate1D` currently uses `sum` to perform the integration. In principle, this is a simplified version of the rectangle rule (Riemann sum: https://en.wikipedia.org/wiki/Riemann_sum), where the signal intensity is assumed to be constant over the complete interval associated with an axis point.

However, for uniform axes, this simplification means that `scale == 1` is assumed. Otherwise the result of `sum` is not really the `integral`, but in fact `integral/scale`.

For non-uniform axes, using the `sum` function does not really make sense mathematically. To calculate an integral using the rectangle rule, the data would first need to be multiplied with `np.gradient(axis)`, before the sum is performed.

I would propose to implement a new function `integrate_rectangle` or `integrate_riemann` that basically calculates:
- for uniform axes: `sum(data)*scale`
- for non-uniform axes: `sum(data*np.gradient(axis))`

This function would be called by `integrate1D` when integrating over a binned axis.

**Comment by thomasaarholt** [comment]
Am I correctly interpreting that the current `integrate1D` behaviour actually is a bug for `is_binned == False`, which would be fixed by multiplying by `scale`? (assuming uniform axis)

I think you make a good case and completely agree with your approach.

**Comment by thomasaarholt** [comment]
~~Does this issue have any implications for the case when the signal/axis is binned?
Actually, should the second word in your issue be "unbinned"? :)~~

**Comment by jlaehne** [comment]
No, I am talking about the behavior for `is_binned == True`: https://github.com/hyperspy/hyperspy/blob/ea89fe2a12609b7fe272e048a9bd83af8a51dfda/hyperspy/signal.py#L4225

For unbinned signals, it used `integrate_simpson`: https://github.com/hyperspy/hyperspy/blob/ea89fe2a12609b7fe272e048a9bd83af8a51dfda/hyperspy/signal.py#L4223
which is totally fine and should work both for uniform and non-uniform axes, as the axis vector is explicitly passed to the scipy routine doing the integration: https://github.com/hyperspy/hyperspy/blob/ea89fe2a12609b7fe272e048a9bd83af8a51dfda/hyperspy/signal.py#L4009

**Comment by thomasaarholt** [comment]
Apologies, my brain expected the first line in `integrate1D`, `if is_binned(self, axis=axis)` to be "`if True`", rather than `if ... is False`.

Regardless, yep, agreed with what you're saying.

**Comment by jlaehne** [comment]
Maybe we should turn that if statement around once we fix this ;-)

**Comment by ericpre** [comment]
@francisco-dlp should know what is the reason for the current implementation. Looking at the git history and the github repository, there is not much information about it.

**Comment by francisco-dlp** [comment]
@jlaehne, I think that simply simming should be correct also for "binned" non-uniform axes. This is because, in this case, this is not  an approximation but the proper way of performing the integral when the signal is binned because in this case the detector itself "performs" the integral of all the counts in the bins. Therefore, in order to get the integral in the signal range you only have to sum the counts of all the bins. Does it make sense?

**Comment by jlaehne** [comment]
But the "width" of the bins can vary depending on the detector, which for the uniform axis is described by the `scale` factor, so I would expect to multiply by `scale` to get the true integral.

As long as you compare just measurements having the same scale, it is of course fine to work with the sum as representation of the integral. I guess, the case where people want to quantitatively compare integrals from e.g. different detectors would be rare.

**Comment by francisco-dlp** [comment]
I am not sure if we are talking about the same thing. For binned axes it doesn't matter if the bins have different sizes as long as the bins cover the signal range e.g. 0-0.1,0.1-0.3,0.3-1. Are you talking about binned axes that don't fill the signal range e.g. 0-0.1, 0.2-0.5 etc? In that case, if we plan to support it, I imagine that we'll need to use some sort of interpolation indeed. Or maybe   we could simply divide by each bin size and use ``integrate_simpson``?

**Comment by jlaehne** [comment]
> @jlaehne, I think that simply summing should be correct also for "binned" non-uniform axes. This is because, in this case, this is not an approximation but the proper way of performing the integral when the signal is binned because in this case the detector itself "performs" the integral of all the counts in the bins. Therefore, in order to get the integral in the signal range you only have to sum the counts of all the bins. Does it make sense?

OK, you are totally right @francisco-dlp. I think I was too stuck in the mindset of integrating a function. Indeed, if you use `sum()` for binned signals, you get the total number of counts and of course that is the integral.

I will adapt sum(), to warn only for non-uniform axes which are not binned and maybe add a half sentence to the docstring of integrate1D.

**Comment by ericpre** [comment]
@francisco-dlp, could you also explain how does it relate with the probability density function as mentioned in the  [user guide](https://hyperspy.readthedocs.io/en/stable/user_guide/signal.html#binned-and-unbinned-signals): "Signals that are a histogram of a probability density function (pdf) should have the signal.metadata.Signal.binned attribute set to True".
As I understand it, this has to do with the fact that EELS and EDS count random events ("counting statistics"), and I think it would be good to explain it with a more simple wording or provide references. This is the type of thing, which is asked on a regular basis but it is overlooked quite often and hidden under the carpet most of the time!

**Comment by francisco-dlp** [comment]
Yes, that's a good point: a single sentence is not enough to explain a concept that most users encounter for the first time in our documentation. However, since ``binned`` is going to become a ``DataAxis`` attribute once we merge #2399, I suggest to close this issue in favour of an item in  #2398 todo list (I've already added it there).

**Comment by jlaehne** [comment]
@francisco-dlp,  @ericpre proposed to do so in #2737, but I would need some input and references of yours. Alternatively, it might be better if you do a separate PR and we comment on it?

**Comment by ericpre** [comment]
Yes, I am fine either way!

**Comment by francisco-dlp** [comment]
OK for sending a PR.
