### ISSUE TITLE
Reading .raw files

### ISSUE THREAD

**Issue by shirley4869** [hyperspy/hyperspy#2738]
Hi developers, I am trying to read .raw files generated from EMPAD by HyperSpy (1.6.2) in a Python IDE.
Here is my code:

import hyperspy.api as hs
data = hs.load("file.raw")

I got the following error: 
ValueError: cannot reshape array of size 218103808 into shape (5368,1932)

In the document, it says the filename of .raw is defined in .xml file. Is it possible to read .raw without .xml file? Any help is appreciated. Thank you.

**Comment by ericpre** [comment]
You should use:
```python
import hyperspy.api as hs
s = hs.load("file.xml")
```

as explained in https://hyperspy.readthedocs.io/en/stable/user_guide/io.html#empad-format.

If you don't have the `xml` file, it should still possible to read the data, but it is not straightforward.

**Comment by shirley4869** [comment]
Thank you for your reply.
Unfortunately, I don't have the .xml file. Since I met with the above error when I tried to read the .raw file directly, do you have any other suggestions?

**Comment by ericpre** [comment]
To understand how to read the data, you can have a look at the file reader of empad file:
https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/hyperspy/io_plugins/empad.py

Below is a code snippet to read the raw file without calibration and assuming that the scanning dimension is 2.

```python
import hyperspy.api as hs
import numpy as np

# provide scan_x and scan_y
scan_x = 
scan_y =

data = np.fromfile(file.raw, dtype='<f4')
size = (scan_x, scan_y, 130, 128)
data = data.reshape(size)[..., :128, :]

s = hs.signals.Signal2D(data)
```

If this doesn't work, again, I would advise you to get the `xml` file to read the data.

**Comment by ericpre** [comment]
In case you get your xml file and you are using a recent version of EMPAD files, issue #2755 may be relevant.
