### ISSUE TITLE
rounding error while parsing input in value2index

### ISSUE THREAD

**Issue by LMSC-NTappy** [hyperspy/hyperspy#2746]
When 

```python
from hyperspy.axes import UniformDataAxis
import math

uax = UniformDataAxis(size=10, scale=0.1, offset=10)
uax.units = 'nm'

list_in = ['0.01um', '0.0101um', '0.0103um']
uax.value2index(list_in,rounding=math.floor)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-64-8cc342c9f05b> in <module>
      6 
      7 list_in = ['0.01um', '0.0101um', '0.0103um']
----> 8 uax.value2index(list_in,rounding=math.floor)

c:\users\nicolastappy\documents\git\hyperspy\hyperspy\axes.py in value2index(self, value, rounding)
   1180         if value is None:
   1181             return None
-> 1182 
   1183         value = self._parse_value(value)
   1184 

c:\users\nicolastappy\documents\git\hyperspy\hyperspy\axes.py in value2index(self, value, rounding)
    602                 f'The value {value} is out of the limits '
    603                 f'[{self.low_value:.3g}-{self.high_value:.3g}] of the '
--> 604                 f'"{self._get_name()}" axis.'
    605                 )
    606 

ValueError: The value [10.  10.1 10.3] is out of the limits [10-10.9] of the "Unnamed" axis.
```

This is due to the way `str `inputs are parsed

```python
uax._parse_value(list_in)[0]
9.999999999999998
```

I think the culprit is this line of code in `_parse_value_from_string`:
https://github.com/hyperspy/hyperspy/blob/ea89fe2a12609b7fe272e048a9bd83af8a51dfda/hyperspy/axes.py#L520

anyone has a feeling of what's going on and how to fix it? I have no other idea than rounding to an arbitrary precision.

**Comment by ericpre** [comment]
Indeed, to narrow down the issue:
```python
import pint

_ureg = pint.UnitRegistry()

value = _ureg.parse_expression('0.01um')
converted_value = value.to('nm').magnitude
```

`converted_value` is `9.999999999999998` which doesn't play well with `floor`...
Does your rounding implementation from https://github.com/hyperspy/hyperspy/pull/2743/commits/914bebd2944f3d63d9ffe02a52aa11d0f311e5a9 suffers from the same issue? If not, I would suggest to get ride of `UniformDataAxis.value2index` and use `BaseDataAxis.value2index` as implemented in https://github.com/hyperspy/hyperspy/pull/2743/commits/914bebd2944f3d63d9ffe02a52aa11d0f311e5a9. The maintenance will be easier!

**Comment by LMSC-NTappy** [comment]
Unfortunately, 914bebd can't help. It will always evaluate out of bounds...

The problem lies in the `UnitConversion` class, and only 'UniformDataAxis' heritates from it. This is also what prevents me from getting rid of `UniformDataAxis.value2index` and use `BaseDataAxis.value2index` as you suggested. I will try to evaluate the possibility of moving `UnitConversion `to `BaseDataAxis` but it's a large amount of work.

Ultimately, this bug needs to be fixed independently.

**Comment by ericpre** [comment]
I would suggest to close this issue because with https://github.com/hyperspy/hyperspy/pull/2765, it doesn't raise an error anymore.

There is still a case where the returned index is not correct with units conversion.
```python
from hyperspy.axes import UniformDataAxis
import math

uax = UniformDataAxis(size=10, scale=0.1, offset=10)
uax.units = 'nm'

list_in = ['0.01um', '0.0101um', '0.0103um', '10.3 nm']
uax.value2index(list_in,rounding=math.floor) # incorrect, the last two should be the same
# array([0, 0, 2, 3]) 
uax.value2index(list_in,rounding=math.ceil) # correct
# array([0, 1, 3, 3])
```

**Comment by LMSC-NTappy** [comment]
I agree. I don't think getting this perfect can be done anyway
