### ISSUE TITLE
Error : Minor issue with density_of_mixture

### ISSUE THREAD

**Issue by adriente** [hyperspy/hyperspy#2771]
I encountered a minor issue using the `density_of_mixture` function from `hyperspy.misc.material`. My version of hyperspy is 1.6.2 and here is the code to reproduce the error : 

```
import hyperspy.misc.material as m
m.density_of_mixture([1.0],elements=["At])
```
It yields a `TypeError : unsupported operand type(s) for /: 'float' and 'numpy.str_'`

I could not reproduce this error for other elements (I did not test them all). I guess there is a small mistake in the tables, probably only for Astate.

**Comment by ericpre** [comment]
The issue is that there is no density for this element in the database: https://github.com/hyperspy/hyperspy/blob/2ddc359c5a6c0ff300507c383dfcc1de644ff11a/hyperspy/misc/elements.py#L4083

Do you know a reference, which could be used to add this missing value?

**Comment by adriente** [comment]
Indeed there doesn't seem to be a density value in the litterature ....

Would it be worth it to add a more explicit error ?

**Comment by ericpre** [comment]
Yes, it should raise a more suitable error message. Would you be interested in making a pull request to improve it?

A quick internet search shows that the density could be ~7 g/cm3 (https://education.jlab.org/itselemental/ele085.html) but other databases such as the RSC one says "unknown": https://www.rsc.org/periodic-table/element/85/astatine...

I didn't try to find the original source, but if it is possible to get it, then it would be better to put a value. Since you are working with element, I would expect that you would known better!

**Comment by adriente** [comment]
I am not really working with Astate. I am simulating EDXS spectra with random composition to assess the performances of a machine learning algorithm. I had the bad luck to run into Astate. 

It seems that it is very unlikely for people to work with Astate in the EDXS community. 

It seems more correct to leave At density as "NaN" since I would expect the RSC to be more reliable. 

I can try to write a fix to this issue. I think it would be better if it threw a ValueError with a corresponding message.

**Comment by ericpre** [comment]
OK, sounds good! In case you haven't came across before, there is a developer guide: https://hyperspy.readthedocs.io/en/stable/dev_guide/intro.html. If there is anything unclear, please don't hesitate to ask!

**Comment by adriente** [comment]
Hello,

I think I need a little bit of help to work around with github. Here are the commands I used : 
```
git clone https://github.com/hyperspy/hyperspy.git
git checkout -b issue2771
```
I made the modifications we talked about and tested them. Then : 
```
git add hyperspy/misc/material.py
git commit -m "Fix of issue 2771"
git push --set-upstream origin issue2771
```
I had to input my github credentials but then I got : 
```
remote: Permission to hyperspy/hyperspy.git denied to adriente.
fatal: unable to access 'https://github.com/hyperspy/hyperspy.git/': The requested URL returned error: 403
```

**Comment by ericpre** [comment]
You need to push to `origin` and not `upstream`, `origin` is your fork on github and it should be `adriente/hyperspy`, which you need to create it using the fork button on github.

This is normal that you don't have permission to write to the upstream repository (`hyperspy/hyperspy`), but you have permission to your own fork and when you make a pull request from your fork to the upstream, we will merge (pull) your changes into a branch of `hyperspy/hyperspy`!
