### ISSUE TITLE
ValueError("signal must have 2 dimensions, not {0}".format(sig_dims))

### ISSUE THREAD

**Issue by somboon39** [hyperspy/hyperspy#2776]
I've got a error coding.
I try to use a function ('get_atom_positions') from Atomap.
But I got error code appear.

![image](https://user-images.githubusercontent.com/84850133/123073150-c0a98100-d448-11eb-8264-83bc74e37d5c.png)

**Comment by magnunor** [comment]
@somboon39, this is the issue tracker for HyperSpy, not Atomap. Questions about Atomap should be posted at: https://gitlab.com/atomap/atomap/-/issues

With regards to your error, this is due to your dataset being a stack of images. Not a single image. Try this:

```python
STO_0 = STO.inav[0]
bird = get_atom_positions(STO_0, separation=9)
```

**Comment by somboon39** [comment]
It's work.
I'm very new for coding.
Thank You

ขอบคุณครับ
