### ISSUE TITLE
`compute_navigator` for non-lazy signals

### ISSUE THREAD

**Issue by din14970** [hyperspy/hyperspy#2782]
Lazy signals have the `compute_navigator` method which is used for plotting, but is also handy for generating a VBF in the blo writer. By contrast, there does not seem to be such a method in `BaseSignal`; instead the calculation is wedged into the `plot` function, I suppose for interactivity. Still it might be handy to have a similar function for all signals and if possible simplify the `plot` function a bit.

**Comment by ericpre** [comment]
Duplicate of https://github.com/hyperspy/hyperspy/issues/2639
