### ISSUE TITLE
HyperSpy 1.6.3 uses importlib_metadata.entry_points() param "group" not available in v1.6.0 of that package

### ISSUE THREAD

**Issue by hakonanes** [hyperspy/hyperspy#2792]
A clean install of the kikuchipy repo on Binder cannot be run because of this error message:

```python
>>> import hyperspy.api as hs
TypeError                                 Traceback (most recent call last)
<ipython-input-1-bf9ae40eec4f> in <module>
      4 import tempfile
      5 import matplotlib.pyplot as plt
----> 6 import hyperspy.api as hs
      7 import numpy as np
      8 from orix import sampling, plot, io

/srv/conda/envs/notebook/lib/python3.7/site-packages/hyperspy/api.py in <module>
     17 # along with  HyperSpy.  If not, see <http://www.gnu.org/licenses/>.
     18 
---> 19 from hyperspy.api_nogui import *
     20 import logging
     21 _logger = logging.getLogger(__name__)

/srv/conda/envs/notebook/lib/python3.7/site-packages/hyperspy/api_nogui.py in <module>
     23 _logger = logging.getLogger(__name__)
     24 from hyperspy.logger import set_log_level
---> 25 from hyperspy.defaults_parser import preferences
     26 set_log_level(preferences.General.logging_level)
     27 from hyperspy import datasets

/srv/conda/envs/notebook/lib/python3.7/site-packages/hyperspy/defaults_parser.py in <module>
     29 from hyperspy.misc.config_dir import config_path, data_path
     30 from hyperspy.misc.ipython_tools import turn_logging_on, turn_logging_off
---> 31 from hyperspy.ui_registry import add_gui_method
     32 
     33 defaults_file = Path(config_path, 'hyperspyrc')

/srv/conda/envs/notebook/lib/python3.7/site-packages/hyperspy/ui_registry.py in <module>
     33 
     34 from hyperspy.misc.utils import isiterable
---> 35 from hyperspy.extensions import ALL_EXTENSIONS
     36 
     37 

/srv/conda/envs/notebook/lib/python3.7/site-packages/hyperspy/extensions.py in <module>
     39 _external_extensions = [
     40     entry_point.module
---> 41     for entry_point in metadata.entry_points(group="hyperspy.extensions")]
     42 
     43 for _external_extension_mod in _external_extensions:

TypeError: entry_points() got an unexpected keyword argument 'group'
```

Checking versions on Binder and minimal working example to reproduce the error

```python
>>> from hyperspy import __version__
>>> __version__
'1.6.3'
>>> import importlib_metadata
>>> importlib_metadata.version("importlib-metdata")
'3.4.0'
>>> importlib_metadata.entry_points(group="hyperspy.extensions")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-e5c2c05b2ac0> in <module>
----> 1 importlib_metadata.entry_points(group="hyperspy.extensions")

TypeError: entry_points() got an unexpected keyword argument 'group'
```

The oldest supported version of `importlib_metadata` is 1.6.0 in HyperSpy 1.6.3:

https://github.com/hyperspy/hyperspy/blob/6226eabd25a0f703364f6f363fa163585a7f0e82/setup.py#L73-L75 

which does not have the `group` keyword argument. The requirement is updated to `>= 3.6` on `RELEASE_next_minor`.

While I haven't checked, I assume that none of our Binder instances after HyperSpy 1.6.3 have worked. I'm just about to release kikuchipy v0.4.0, and can set our oldest supported version of importlib_metadata to 3.6, so this isn't a huge problem going forward. Is a HyperSpy release far off, so I know roughly when I can remove that version requirement?

**Comment by francisco-dlp** [comment]
Thanks for the bug report, would you like to send a PR fixing the issue?

@ericpre, I think that this is serious enough for an emergency release, what do you think?

**Comment by hakonanes** [comment]
Thanks for the quick reply!

I assume the fix would only include updating the minimal requirement of importlib_metadata to >= 3.6 in setup.py on `RELEASE_next_patch`.

**Comment by francisco-dlp** [comment]
That's it!

**Comment by ericpre** [comment]
`importlib_metadata` 3.6 has been released in February 2021 and this could an issue for packaging in linux distribution?

**Comment by hakonanes** [comment]
I believe this is an issue in any environment with HyperSpy 1.6.3 and importlib_metadata < 3.6, regardless of distributions?

**Comment by francisco-dlp** [comment]
With a bit of luck, a linux distribution that offers an up-to-date version of HyperSpy will also offer an up-to-date version of Python (that includes ``importlib_metadata``) and/or ``importlib_metadata``. For example, Debian testing (where hyperspy is available) ships with Python 3.9.2.

**Comment by hakonanes** [comment]
> offer an up-to-date version of Python (that includes `importlib_metadata`) and/or `importlib_metadata`

... meaning >= 3.6, got it. Thank you for the explanation. I only encountered this issue just now on our Binder builds, so most likely no users of kikuchipy have experienced this issue in their environments.

**Comment by ericpre** [comment]
Yes, looking at https://pkgs.org/search/?q=hyperspy, it seems that there is only ubuntu and debian we should worry about and their latest version are on python 3.9, which should be fine.

@hakonanes: it is surprising that the binder image includes an old version of `import_metadata` and this shouldn't be the case.

**Comment by hakonanes** [comment]
> it is surprising that the binder image includes an old version of `import_metadata` and this shouldn't be the case.

Yeah, I guess it is surprising... Binder builds from our setup.py with no configuration specific to Binder. Perhaps I should add such a Binder config file, that might have prevented this from being an issue.

Thank you both for taking the time to respond so quickly to this issue.
