### ISSUE TITLE
Incorrect fitting with fixed components

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#2801]
When fixing a component that has been fitted, and then running multifit, then the fitting may fail. This is on latest RELEASE_next_minor.

In the following example, I create a `(3|1000)` Signal1D using one first-order polynomial and two gaussians. Then I fit the polynomial in a straight-line region, and fix it. Then I run multifit with default parameters and inspect the result. As you can see, the fit fails completely in the first index, and partially fails in the second index. The final index is correct.

```python
import hyperspy.api as hs
import numpy as np

x = np.linspace(0, 50, 1000)
gaussian_centres1 = [5, 10, 15]
gaussian_centres2 = [10, 15, 20]


slope_values = [-1, 0, 1]

G1 = hs.model.components1D.Gaussian(A=50)
G2 = hs.model.components1D.Gaussian(A=50)

G1.set_parameters_not_free(('centre', 'sigma'))
G2.set_parameters_not_free(('centre', 'sigma'))


S = hs.model.components1D.Polynomial(order=1, legacy=False)
S.set_parameters_not_free(('a0'))


signal_data = []
for i in range(3):
    G1.centre.value = gaussian_centres1[i]
    G2.centre.value = gaussian_centres2[i]

    S.a1.value = slope_values[i]
    data = G1.function(x) + G2.function(x) + S.function(x)
    signal_data.append(data)
    
    
nav_axis = UniformDataAxis(size=len(signal_data))
sig_axis = UniformDataAxis(scale = x[1] - x[0], offset = x[0], size = len(x))

s = hs.signals.Signal1D(signal_data, axes=[nav_axis, sig_axis])

m = s.create_model()
m.extend((G1, G2, S))

# Fit polynomial using the range after the gaussians, then fix it
m.fit_component(S, only_current=False, signal_range=(30, 50))
S.set_parameters_not_free()

# Now multifit the other Gaussians
m.multifit()

m.plot() # inspect the three indices
```

The three indices now display rather unexpected behaviour:

<img width="557" alt="image" src="https://user-images.githubusercontent.com/2721423/127035598-a4a677ff-5e03-4676-b2be-1bdd3ac199fd.png">

<img width="561" alt="image" src="https://user-images.githubusercontent.com/2721423/127035698-f556b999-7442-49e7-8328-aa42e16b1357.png">

<img width="589" alt="image" src="https://user-images.githubusercontent.com/2721423/127035671-15e30f90-b875-40cf-9eea-ab3dcdfc23db.png">

**Comment by ericpre** [comment]
This is like a typical bad starting parameter issue. If you give a good estimate of the position of the gaussian, it works fine:

```python
G1.centre.map['values'] = gaussian_centres1
G2.centre.map['values'] = gaussian_centres2

m.multifit()
```

I can't see any issue with fixed components.

**Comment by thomasaarholt** [comment]
You're absolutely right...  I'm also an idiot. I had frozen the `G1.centre.free` above...

My issue in my original code (the above was a flawed minimum working example) lay with `G1.centre.map['is_set']`. I had forgotten about that toggle. In the MWE, it is set to `True` during the `m.fit_component(S, only_current=False, signal_range=(30, 50))` call, which I didn't expect originally. By using `fit_independent=True` I avoid that, and can set `is_set` to `True` in my own time.

Thanks Eric, I needed the sanity check and clearly I failed it :p

**Comment by ericpre** [comment]
No worries, should it be closed then? Or there is something that doesn't behave sensibly?

**Comment by thomasaarholt** [comment]
I was leaving it open while double checking something, but no, all is good :)
