### ISSUE TITLE
Deleting non_uniform_axis branch

### ISSUE THREAD

**Issue by jlaehne** [hyperspy/hyperspy#2807]
@ericpre and @francisco-dlp : Any objections to deleting the non_uniform_axis branch as it is now merged into RELEASE_next_minor? I guess further developments for the non-uniform axes can now directly go to RnM.

**Comment by ericpre** [comment]
Indeed, there is no need to keep it!

**Comment by jlaehne** [comment]
Deleted the `non_uniform_axes` branch as #2399 is merged. See #2398 for tracking issue on further progress.
