### ISSUE TITLE
Character encoding in JEOL EDS file (jeol.py in the developper version)

### ISSUE THREAD

**Issue by nem1234** [hyperspy/hyperspy#2812]
In JEOL EDS data file, character encoding of "ShiftJIS" is used instead of "utf-8".
(In my case, Analysis Station 3. 8. 0. 53)

For example , in Line 376,
kwrd == b"\xce\xdf\xb0\xc4"
This is the Japanese word of "port" in ShiftJIS encoding, "ﾎﾟｰﾄ"

Line 206, reading "memo" often generate this encoding error, so, please just skip this without "utf-8" decode.
        _ = fd.read(132).rstrip(b"\x00").decode("utf-8")
should be
        _ = fd.read(132)

I don't know the case of new JEOL software, but, 
If the file reading with "utf-8" encoding is failed, retry with "ShiftJIS" encoding will get better result.

**Comment by ericpre** [comment]
Thanks for the bug report, would you be interested to [make a pull request](https://hyperspy.org/hyperspy-doc/current/dev_guide/intro.html) to fix it?

Your suggestion to simply skip the decoding part is sensible, because this value is not used. I guess that it has been used for debugging purposes.

**Comment by nem1234** [comment]
Thank you very match.
Currently I'm not yet friendly with git operation, 
so, I attach a patch at here.
[jeol.diff.gz](https://github.com/hyperspy/hyperspy/files/7046504/jeol.diff.gz)

**Comment by ericpre** [comment]
OK, there is actually more to change than originally reported so it may be better to use a different approach. Can you share a file to reproduce the encoding issue?

Would it work to have a convenient function for decoding
```python
def decode(bytes_string):
    try:
        string = bytes_string.decode("utf-8")
    except:
        string = bytes_string.decode("shift_jis")

    return string
```

**Comment by nem1234** [comment]
I check my EDS files, and I found that only "Memo" fields in pts file and filenames in asw file contains Japanese characters with ShiftJIS encoding.
So, charset of other fields seems to be ignored, except for the field name of "ﾎﾟｰﾄ"/"Port".


Details
Since the AnalysisStation.exe and other components are linked with traditional MBCS library, it does not handle Unicode / utf-8 encoding.

1. By default install in Japanese environment, and default run of EDS acquisition, 
"Memo" field was filled with Japanese string in ShiftJIS, "視野000", that means ViewPort000 or Field000.
2. in ASW file, Filename field is written in ShiftJIS

00000600  01 09 00 00 00 46 69 6c  65 6e 61 6d 65 00 0c 00  |.....Filename...|
00000610  00 00 2a 00 00 00 2e 5c  83 54 83 93 83 76 83 8b  |..*....\.T...v..|
00000620  5c 30 30 5f 8e 8b 96 ec  30 30 30 5c 8e 8b 96 ec  |\00_....000\....|
00000630  30 30 30 5f 30 30 30 30  30 30 30 2e 69 6d 67 00  |000_0000000.img.|

This is ".\サンプル\00_視野000\視野000_0000000.img" in ShiftJIS encoding.
This means ".\Sample\00_Filed000\Filed000_0000000.img" 
(may be in english installation of JEOL software)

the sample ASW file is attached in this post.
[181019-BN.ASW.gz](https://github.com/hyperspy/hyperspy/files/7051185/181019-BN.ASW.gz)

**Comment by nem1234** [comment]
Since I don't use asw file,
may be  string.decode("utf-8","ignore") is enough....

**Comment by ericpre** [comment]
@nem1234, I have used the fix [mentioned above](https://github.com/hyperspy/hyperspy/issues/2812#issuecomment-905422069) in https://github.com/ericpre/hyperspy/tree/fix_encoding_JEOL_reader and you can install this branch using:
```
pip install https://github.com/ericpre/hyperspy/archive/refs/heads/fix_encoding_JEOL_reader.zip
```
I have check with the file you [provided above](https://github.com/hyperspy/hyperspy/issues/2812#issuecomment-906057645) and it doesn't raise the encoding error anymore but since there is only the `asw` fiel, so I can't really verify whether this works properly or not.

Are you fine with this being added to the test suite? This is to ensure that this encoding is well supported and avoid regression in future releases.

**Comment by nem1234** [comment]
Thank you very much.

I tried to open asw and pts files, it works fine with filename written in japanese characters.
(I don't know the default encoding of JEOL softwares in other language environment,)
