### ISSUE TITLE
How to read selected frame for integration (in developper version jeol.py)

### ISSUE THREAD

**Issue by nem1234** [hyperspy/hyperspy#2814]
In case of high spatial resolution (ex: atomic scale) EDS, we usually setup multiple scanning with very short dwell time.
In such case, we need to 
  1. remove broken frame, (vibration, position jump, and so on)
  2. spatial alignment (drift correction) between frames using STEM signal, 
  3. summing up good frames until the sample become broken or contaminated (STEM signal disappeared).
The current code seems that full signals are simply summing up in readcube, 
without any alignment and checking, and there is no way to select useful frames.
Is there any idea to select good frames?

(Data values of 0xa000-0xafff in PTS file have the STEM intensity values,
 0x9000 0x8000 (y=0, x=0) is a frame separator,
 value of doc/"sweep" has the value of "(number of frames) + 2"

**Comment by nem1234** [comment]
Sorry, readcube_frames have such functionality.

But still I have two problems.

1. The STEM intensity image for each frame can not be extracted from pts file.
2. Too much memory is required.
  When I try to read 128 pixel x 128 pixel x 4096 ch x 1000 frame JEOL EDS data,
  it uses over 20 GB memory for 100 MB pts file.
  I want a way to get selected frames of the file.  

codes:

import hyperspy.api as hs
data_pts = hs.load('test.pts', sum_frames=0)
data_pts.plot()

**Comment by ericpre** [comment]
For the memory, this is expected, please read https://hyperspy.readthedocs.io/en/latest/user_guide/io.html#jeol-asw-format.

From the documentation, it doesn't seem that reading the stack of images is implemented. After a quick look, it is not obvious where it is saved. Maybe @arnduveg or @ialxn can advice?

**Comment by ialxn** [comment]
Hi @nem1234
you might want to try out ``JEOL_eds`` (https://github.com/ialxn/JEOL_eds) for an initial preprocessing of your data and use the result as a hyperspy signal (or stack). JEOL_eds solves parts of you problems (alignment of selected, individual frames). You could decrease the memory pressure somewhat by using ``E_cutoff=`` and ``dtype=uint8`` when reading the data. For further processing with ``JEOL_eds`` you can allready specify a list of frames to be included (``frames=``) but I have not implemented this for reading the data set yet. It should be rather easy, however, as ``split_frames`` is implemented and one just needs to keep track of the frame counter while reading.

**Comment by nem1234** [comment]
Thank you ialxn, 
I have my own C++ code for such analysis, and I'm planning to replace it by hyperspy.
I recognize that current hyperspy does not fullly support pts file, and need an extra
code like this.
May be I need to think again how to treat pts files.

**Comment by ialxn** [comment]
@nem1234 I have mostly implemented in ``JEOL_eds`` the possibility to read only a subset of frames (tests/verification is still missing). However, I am really busy with other things now but I should be able to push a new version in the next few days. I would be glad if you could have a look at test the feature.

**Comment by ericpre** [comment]
@nem1234, you can use the [`rebin_energy` argument](https://hyperspy.readthedocs.io/en/latest/user_guide/io.html#id20) to further reduce data size.

There a two things, which would be good to do here:
- add an option to read a range of frame, in the same it is done with the [Velox EMD reader](https://hyperspy.readthedocs.io/en/latest/user_guide/io.html#extra-loading-arguments-fei-emd), it would need a tweak of the  [loop reading the data steam](https://github.com/hyperspy/hyperspy/blob/8c74de87855a7e6cf53acfa85ca6b1e77367d619/hyperspy/io_plugins/jeol.py#L460-L485), which is already frame aware. Then it is a matter of setting the dimension of the array before hand and skipping frames.
- add support for lazy loading, more difficult but the same approach as used for the Velox EMD could be used. The advantage is that with a lazy signal it will be possible to use `inav`/`isig` syntax to have the full flexibility for further processing without having to worry about memory usage and tweak keywords argument.

@ialxn, @nem1234, there is still one question unanswered: do you know where are the STEM images saved?

**Comment by nem1234** [comment]
Thank you very much, I'll try the lazy loading, but it will take long time for me.

>there is still one question unanswered: do you know where are the STEM images saved?

The STEM image is stored inside PTS file. The STEM intensity is stored in the value range of 0xa000-0xafff (0-4095), which is ignored in the readcube function in the current version of jeol.py.

**Comment by ericpre** [comment]
> The STEM image is stored inside PTS file. The STEM intensity is stored in the value range of 0xa000-0xafff (0-4095), which is ignored in the readcube function in the current version of jeol.py.

Great, this is good to know!

Doing the lazy implementation would definitely be the best approach.  The lazy implementation of spectrum image velox reader is not very usual but it will most likely become more standard in the future. If I remember correctly, it works as follow:
1. the data stream is converted to a COO spare array which is stored in memory. We use
 ["pydata sparse"](https://github.com/pydata/sparse) and not [scipy sparse ](https://docs.scipy.org/doc/scipy/reference/sparse.html) because the former supports multi-dimensional and is designed to play well with dask.
2. When creating the lazy signal, the CCO sparse array is used as source of the dask array.
3. When processing needs to be done (i.e. calling `compute`), the sparse is converted to a dense array and subsequent processing can be done as usual.

This approach is not optimal, but this is working decently - at least until sparse arrays are natively supported in hyperspy. Changing the JEOL reader to enable this is a bit technically (conversion of the JEOL data stream to a COO sparse array) but the rest should be simple. I can provide guidance and help to sort out issues/difficulties.

**Comment by ialxn** [comment]
@nem1234 you could use the new version (1.8) of ``JEOL_eds`` that supports now reading a subset of frames and use the result as a HyperSpy signal.
@nem1234 apart from x, y, counts and STEM images there seems to be additional data stored in the .pts files (values of 24576 and 28672). Do you have any idea what these signify?

@ericpre , @nem1234 reading a subset of frames and lazy loading would be really usefull. I am pretty (over)loaded with other stuff, but I might help in future.

**Comment by arnduveg** [comment]
Hi everyone,
Thanks @nem1234 for the information concerning a000-afff data. I didn't have it in my dataset which explain why it was ignored by the readcube function. Implementing STEM reading will be really helpful.
@ialxn , I am not sure but 6000 and 7000 data are similar to 100*readtime and 100*livetime stored in the pts file. For example in my case, the sum of 6000 data give 125815 (1257.98 in the pts) and sum of 7000 data give 102580 (1025.61 in the pts).

**Comment by nem1234** [comment]
I'm now trying to use sparse array.
Not yet completed but this seems to work.
Still under construction....
[jeol_a.txt](https://github.com/hyperspy/hyperspy/files/7210313/jeol_a.txt)
.

**Comment by ericpre** [comment]
I think, this is all done in #2846?

**Comment by nem1234** [comment]
Already finished. 
I'll close this.
