### ISSUE TITLE
Abimguous labeling of edges in elements.py and degenracy scaling with the 'factor' property

### ISSUE THREAD

**Issue by gguzzina** [hyperspy/hyperspy#2817]
The P. Rez dataset of generalised oscillator strengths contains only the "odd" subshells, i.e. L1, N3, M5, etc.
This is, I suppose, due to the fact that the approximation used in the computation does not include any spin-orbit coupling. In this situation the missing edges are just shifted and scaled copies of the ones that are present.
This scaling accounts for the different degeneracy of the different levels (see Egerton, Appendix D).

For instance we have that, neglecting the shift in energy, L2 = 0.5*L3 or M4 = 2/3*M5.
This scaling is mostly handled by indicating for each edge which GOS file should actually be used, and including such scaling factors as 'factor' in the "elements.py" database.
See for instance the entry for the M4 edge of Europium:

```python
'M4': {'relevance': 'Major', 
     'threshold': 'Sharp peak',
     'edge': 'Delayed maximum',
     'factor': 0.6666666666666,
     'onset_energy (eV)': 1061.0,
     'filename': 'Eu.M5'},
```

These factors are in principle the same for all edges with the same 'name', and the edge-filename correspondence is trivial, so why store it in each entry with a lot of repetition?

It turns out that the database does not always distinguish between the subshells. A few elements, such as Na, Cl, or Al include only a combined L2,3 edge. The convention adopted, however, is to only label it L3 and scale it with a factor of 1.5 to account for the missing L2 edge:

```python
'L3': {'relevance': 'Major',
       # overlaps
       # with L2
       'threshold': 'Sharp peak',
       'edge': 'Delayed maximum',
       'factor': 1.5,
       'onset_energy (eV)': 31.0,
       'filename': 'Na.L3'},
```

The problem is that if we want to include more options for the generalised oscillator strengths it may be worth removing from the elements database the information which is specific for one single GOS dataset.

My proposal is:
- I change all the peaks such as the latter one to names like L2,3 to remove ambiguity
- I remove all the 'filename' and 'factor' field. This information can easily be included in a very small dictionary inside hartree_slater_gos.py with entries like {'L2':['L3', 0.5], 'L2,3':['L3', 1.5]} and the names can be generated on the fly in the loader function.
- The representation of the component remains unvaried, the information is just shifted out of elements.py

I can do this quite quickly, as soon as I get a go-ahead.
On the other hand, I won't bother if this kind of change in not welcome.

**Comment by ericpre** [comment]
This sounds like a very sensible plan, I agree that keeping the `factor` and the `filename` in this dictionary is not suitable.

From a quick look, it seems that there is no test checking that calculating the cross section is working and correct! I would speculate 2 reasons for this:
1. we need the GOS to calculate them and we don't always them when running the test suite!
2. this was implemented when testing was not as much enforce as of today - this part of the code is most likely the oldest with very little change over the years!

Before doing your refactor, I think that it would be good to generate cross sections for all edges from a script and store the results as a `npy` file and add a test to the test suite asserting the values. This would make sure that no regression is introduced! If the GOS are not available, the test can be skip easily using one of the pytest decorator.
