### ISSUE TITLE
The API documentation of a few signals is broken

### ISSUE THREAD

**Issue by ericpre** [hyperspy/hyperspy#2823]
- For example:
  - https://hyperspy.readthedocs.io/en/latest/api/hyperspy._signals.eds.html
  - https://hyperspy.readthedocs.io/en/latest/api/hyperspy._signals.eels.html
- Private methods shouldn't be generated automatically

**Comment by jlaehne** [comment]
from the links, looks like it is fixed @ericpre ?

**Comment by ericpre** [comment]
No, the issue is that in the html version of the API, the methods of these signals are missing.
