### ISSUE TITLE
Lazy loading code for JEOL EDS (PTS) File Reader

### ISSUE THREAD

**Issue by nem1234** [hyperspy/hyperspy#2832]
Hi,
I wrote a small patch for latest jeol.py in the developer branch.
This patch contains 
  1. Support lazy loading for multi frame pts data. This dramatically reduce the memory usage if the number of sweep is large. 
      eds_data = hs.load(eds_data_file, sum_frames = False, lazy = True)
  2.  Fix the "sweep" value (The number of frames is smaller than the value of "sweep" in some version of JEOL software)

I'm sorry I didn't understand the system of pull request yet.
So. this time I attach a patch to this message.

[jeol_lazy.diff.gz](https://github.com/hyperspy/hyperspy/files/7292309/jeol_lazy.diff.gz)

**Comment by ericpre** [comment]
@nem1234, thank you for the patch!
The best approach would be if you could make a pull request yourself and I will explain why. You will get credits for your contribution and even if git/github can be a bit tedious/takes a bit of time to learn, it is something useful to learn. I would imagine that it you can write "not straightforward" code, you would be able to pick up fairly easily git/github. In the long run, it also has advantage to keep your own code in a good shape if you use git and github but also it would allow you to contribute to any open source library or to checkout development code easily available online!

Regarding code credits and in case you are not interested in making a pull request for now, I could take your patch and commit on your behalf using `git commit --author <name> <email>` to [give you credit](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---authorltauthorgt) and for this I would need your name and email. Github uses email address to link git commits with github account, in other words, if both email addresses are the same, which is the case most of the time, the contribution will appear in your github account. This is relevant to get credit in the [hyperspy contributors list](https://github.com/hyperspy/hyperspy/graphs/contributors), which is in turn used in the [zenodo author entry](https://zenodo.org/record/5082777).

We have a [contributor guide](https://hyperspy.readthedocs.io/en/latest/dev_guide/intro.html) to help first contribution. There is quite a lot of information but not everything is necessarily very clear... You are very welcome to comments on what could be improved! In any case, we can help if there is something unclear, here or on [gitter](https://gitter.im/hyperspy/hyperspy).

Which approach would you like to take?

**Comment by nem1234** [comment]
Thank you.

May be I had better learn "git pull request".
At first I'll try pull request with a small patch.
After that I'll try to make pull request for this.

**Comment by ericpre** [comment]
Done in #2846.
