### ISSUE TITLE
beginner question about bcf files in hyperspy

### ISSUE THREAD

**Issue by rockdocta08** [hyperspy/hyperspy#2834]
Hello, I'm brand new to hyperspy and python and am trying to simply load some EDS map data as a .bcf file and then change the file type to a .hdf5 file so I can manipulate the data in MATLAB (I just want to plot element ratios on a the map instead of individual elements).  

I tried the following code but got an error message when trying to save the file as hdf5: "AttributeErrorL 'list' object has no attrivute to 'save'

  %matplotlib qt
import hyperspy.api as hs

d = hs.load("Map1.bcf")

d.save('Map1.hdf5')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-33-6ec57c6b91aa> in <module>
----> 1 d.save('Map1.hdf5')

AttributeError: 'list' object has no attribute 'save'

Thanks!

**Comment by ericpre** [comment]
In your case, the `load` function returns a list of signal instead of a single signal, see https://hyperspy.org/hyperspy-doc/current/user_guide/io.html#loading-files-the-load-function for more details.
