### ISSUE TITLE
Release 1.7

### ISSUE THREAD

**Issue by ericpre** [hyperspy/hyperspy#2845]
There are a number of enhancements and new features in the 1.7 milestone: https://github.com/hyperspy/hyperspy/milestone/40?closed=1

There are also a few PRs closed to be completed and could easily go into the 1.7 release:
- https://github.com/hyperspy/hyperspy/pull/2422
- https://github.com/hyperspy/hyperspy/pull/2797
- https://github.com/hyperspy/hyperspy/pull/2839
- Two PRs will need to be coordinate with pyxem (https://github.com/pyxem/pyxem/pull/780)
  - https://github.com/hyperspy/hyperspy/pull/2842
  - https://github.com/hyperspy/hyperspy/pull/2703
- Support for matplotlib 3.5: see https://github.com/hyperspy/hyperspy/pull/2922
- https://github.com/hyperspy/hyperspy/pull/2568
- #2670
- #2878

I would also suggest to get the following PR in. It is not as crucial as others but it is on the similar topic as #2842 and #2703:
- #2830 

Are there others PR which should be considered for the release 1.7?
- #2874 (depends on #2913)
- #2781
- #2908
- #1791

**Comment by ericpre** [comment]
https://github.com/hyperspy/hyperspy/pull/2422 is big but it is in in a very state and already working very well. I have started a review and should be able to finish it in the coming few days.

**Comment by magnunor** [comment]
The improvements to lazy plotting could also be considered: https://github.com/hyperspy/hyperspy/pull/2568

**Comment by ericpre** [comment]
> The improvements to lazy plotting could also be considered: #2568

Yes, added to the list, I have a pending review for this one! :)

**Comment by magnunor** [comment]
With regards to the pull requests related to `pyxem`, `s.map` and ragged arrays. I suggest finishing the ragged array one first, https://github.com/hyperspy/hyperspy/pull/2842 , as this will fix some of the failing functionalities in `pyxem`. In addition, it will probably affect the `s.map` pull request https://github.com/hyperspy/hyperspy/pull/2703, as changing how `BaseSignal`s behave is quite a "low level" change.

**Comment by ericpre** [comment]
Added #2839 to the list.

**Comment by ericpre** [comment]
Added #2670 to the list.

**Comment by jat255** [comment]
If it's accepted, I would like to include #2873 on this list

**Comment by jlaehne** [comment]
Should we put a timeframe on the 1.7 release for currently open issues to be included?

There are quite some major PRs sleeping in here. In particular, it would be good to have the `non_uniform_axis` support out so that people can reliably use it and after more than half a year in RnM it should be thoroughly tested. Recently, there have been several questions on gitter that would have been obsolete if it were released. Also I am trying to convince some colleagues to use HyperSpy and LumiSpy, but they are not keen on installing the development branch.

**Comment by magnunor** [comment]
I agree! From my perspective, getting the various `map` changes sorted out would be very nice. Specifically https://github.com/hyperspy/hyperspy/pull/2878 and @CSSFrancis's follow-up addressing `ragged` array edge cases.

One slight complication is that this release will break `pyxem`, due to the changes in `map`. So we're aiming to have a new release of `pyxem` ready to go right after `hyperspy` 1.7 is released. @CSSFrancis `ragged` array improvements is going to be especially relevant for this, as many of the "breaks" is due to how the ragged arrays are handled.

**Comment by CSSFrancis** [comment]
+1 for releasing 1.7 soon, I'll try to get out the ragged `map` stuff this week.  That should help us testing in pyxem to make sure everything is working there.

**Comment by jlaehne** [comment]
How about putting a due date in three weeks on this release then to give it a clear timeframe?

**Comment by ericpre** [comment]
> How about putting a due date in three weeks on this release then to give it a clear timeframe?

Sounds good! Who could review https://github.com/hyperspy/hyperspy/pull/2422 and/or https://github.com/hyperspy/hyperspy/pull/2670?

**Comment by jlaehne** [comment]
Three weeks have passed. #2422 and #2670 could be merged, unless someone else wants to contribute a review. What is the status on the pyxem side, would you be ready for v1.7?

**Comment by CSSFrancis** [comment]
I think we pretty much ready for a 1.7 release at 'pyxem'. I was going to try to get all of the tests passing tonight. So unless @pc494 or @magnunor has any more things they are looking at finishing we should be mostly good to go.

**Comment by din14970** [comment]
I think #2781 could still go in? Fixing up the last bits there

**Comment by magnunor** [comment]
@jlaehne, in pyxem we should be pretty close to ready. We're tracking the remaining issues here: https://github.com/pyxem/pyxem/issues/788

**Comment by jat255** [comment]
#2874 is likely close enough if we can get a review on it in the next couple of days

**Comment by magnunor** [comment]
I*m tempted to suggest https://github.com/hyperspy/hyperspy/pull/1791 as well for 1.7, if people think that is ok. Currently working on improving the pull request, by adding more unit tests to improve the coverage.

**Comment by jlaehne** [comment]
I would give it another week? 

A few last PRs seem almost ready to go and the last weeks have seen quite some productivity to get things ready and include some bug fixes.

#2670 and #2830 can be merged from my side, but maybe someone else wants to have another look?

**Comment by ericpre** [comment]
> I would give it another week?
> 
> A few last PRs seem almost ready to go and the last weeks have seen quite some productivity to get things ready and include some bug fixes.
> 
> #2670 and #2830 can be merged from my side, but maybe someone else wants to have another look?

In order to get this moving, @jlaehne can you please have a last review at #2670? There were enough time for others to review it.
I will review #1791 and #2908.

**Comment by magnunor** [comment]
With regards to making a new HyperSpy bundle with the new 1.7 release, I'll do a new Atomap release as soon as 1.7 is out to fix up some minor issues.

So it would be nice to wait a day or two after the 1.7 release, before making a bundle release.

**Comment by ericpre** [comment]
Yes, it would be good to get [pyxem 0.14](https://github.com/pyxem/pyxem/issues/788) too! :)

**Comment by jlaehne** [comment]
Same holds for [lumispy 0.2](https://github.com/LumiSpy/lumispy/pulls?q=is%3Aopen+is%3Apr+milestone%3Av0.2.0) :-)

**Comment by jlaehne** [comment]
In view of the epsic workshop approaching, we should probably have the release out on Monday/Tuesday, so that the bundle could follow later in the week?

**Comment by magnunor** [comment]
How much is remaining for the https://github.com/hyperspy/hyperspy/pull/2908 pull request? Is it feasible to complete it tomorrow (tuesday)?

If not, should it be shifted to the next release?

**Comment by ericpre** [comment]
https://github.com/hyperspy/hyperspy/pull/2932

**Comment by magnunor** [comment]
With HyperSpy 1.7 released, we're going through the outstanding issues in pyxem (https://github.com/pyxem/pyxem/issues/788), and I'm updating Atomap to work with the new version.

Both of these should be ready in a day or two, which means a HyperSpy bundle release Thursday or Friday should be doable?

**Comment by ericpre** [comment]
That would be great! The bundle needs the conda-forge packages.

**Comment by magnunor** [comment]
I sorted out all the Atomap issues (really only one), and I'll do a release tomorrow.

pyxem is also progressing nicely, so I think a release tomorrow is feasible.

**Comment by jlaehne** [comment]
Being on a conference, I am not sure if I manage to do the LumiSpy release this week.

**Comment by magnunor** [comment]
> I sorted out all the Atomap issues (really only one), and I'll do a release tomorrow.

I just released a new version on both pypi and conda-forge, so Atomap is good to go!

**Comment by pc494** [comment]
pyxem is released now too, just waiting on pypi and conda-forge.

**Comment by pc494** [comment]
Having to put a patch out due to a zenodo error, so it'll be 0.14.1 that would be best in the bundle (although 0.14.0 will still work)

**Comment by jlaehne** [comment]
LumiSpy is released now too
