### ISSUE TITLE
Zarr<2.9.0 Won't Save Data

### ISSUE THREAD

**Issue by CSSFrancis** [hyperspy/hyperspy#2851]
I was checking out and using the next minor branch today and had some issues with saving the data using the `zspy` format.  It appears that there is a bug for versions of `zarr` < 2.9.0 where the data isn't actually being stored.  Instead an array of zeros is stored. 

I can create a PR which forces `zarr>=2.9.0`.  That should fix the problem.

@ericpre Just something to note before the Next Minor Release

**Comment by ericpre** [comment]
Yes, thanks!
