### ISSUE TITLE
Error gdos for the k edge using hydrogenic calculations

### ISSUE THREAD

**Issue by daenjannis** [hyperspy/hyperspy#2854]
Hello,

I have been looking into the implementation of the gdos for the k edge using the hydrogenic approximation.
It seems that in line 164 for hydrogenic_gos.py: kh2 should be replaced with akh.
The formula I use to compare the implementation with is 3.125 of the Egerton book (Electron Energy-Loss Spectroscopy
in the Electron Microscope)

Cheers,

Daen Jannis

**Comment by ericpre** [comment]
I don't see where `hk2` should be replaced by `akh` and it may be the number of the line you are referring to has changed over version, etc.
Can you please provide the "permanent link" from github by navigating to the file on github, clicking on the line and using the context menu?

![image](https://user-images.githubusercontent.com/11851990/142758483-59cc55b1-0b0f-4b8e-86cd-121f3679659a.png)

and copy the link here: https://github.com/hyperspy/hyperspy/blob/b63f94cb3e7c48874a1248bfb7cddf7a7dda638b/hyperspy/misc/eels/hydrogenic_gos.py#L164

The alternative is that you send a git diff or make a pull request. The pull request will have the advantage of showing clearly what are the changes you are suggesting and will be easy to discuss these.

It looks to me that this part is a python translation from the [sigmak3 matlab code](https://sites.google.com/site/temsemeels/).

**Comment by daenjannis** [comment]
Thanks for the explanation, I have created a pull request from which the 
suggested modification is seen.

**Comment by francisco-dlp** [comment]
You are right, there was typo in the code! Thanks for reporting it and submitting a fix #2858. How have you realized the issue?

**Comment by daenjannis** [comment]
I was looking into the implementation and at the same time checking the formulas from the Egerton book and I noticed that this discrepancy. It was mainly by sheer luck that I noticed it.

**Comment by ericpre** [comment]
Fixed in #2859.
