### ISSUE TITLE
Support for Python 3.10

### ISSUE THREAD

**Issue by hakonanes** [hyperspy/hyperspy#2867]
Hi all,

has anyone checked whether HyperSpy can be installed in Python 3.10? I've checked for kikuchipy's dependencies [here](https://github.com/pyxem/kikuchipy/issues/490), and HyperSpy is the remaining listed dependency that cannot be installed in a fresh conda environment with Python 3.10.

**Comment by ericpre** [comment]
`numba` 0.55 released 2 days ago is required for python 3.10 support.

**Comment by hakonanes** [comment]
Do you mean I should expect some time between the `numba` 0.55 release and HyperSpy being installable on 3.10?

There are perhaps other HyperSpy dependencies not supporting 3.10? The output from `pip install hyperspy` in a 3.10 environment [linked above](https://github.com/pyxem/kikuchipy/issues/490#issuecomment-1012998626) shows that errors occur when building `matplotlib`, however `pip install matplotlib` by itself works.

**Comment by ericpre** [comment]
Sorry if I was not clear, what I meant is that without numba supporting python 3.10 it wasn't possibly for hyperspy to support python 3.10.

matplotlib 3.4 should work fine with python 3.10, as there are packages for 3.10 on conda-forge.

**Comment by hakonanes** [comment]
You were clear, thanks.

The errors I got are unrelated to HyperSpy and even matplotlib (had an issue with gcc compilers)... I can confirm that HyperSpy installs fine on 3.10.
