### ISSUE TITLE
Allow roi.interact to work with 0 dimensional signal data 

### ISSUE THREAD

**Issue by 0Hughman0** [hyperspy/hyperspy#2872]
Thanks for the great library. 

I'm encountering a frustrating issue. 

In my work I acquire a range of maps of various data types over the same area e.g. secondary electron and hyperspectral cathodoluminescence maps (hence using this library!). 

Very often there will be a feature in one signal that I would like to correlate with another signal. 

The roi feature is very good for picking out interesting parts of my hyperspectral data. However, cross comparing it with SE data for example is not possible due to some limitations in the roi implementation e.g.

```
from hyperspy import signals
from hyperspy import roi

spectra = signals.Signal1D(np.linspace(0, 1, 64 * 64 * 128).reshape(64, 64, 128))  # some toy data
reference = signals.Signal1D(np.sin(np.linspace(-1, np.pi, 64 * 64 * 1)).reshape(64, 64, 1))  # e.g. my SEM data

line = roi.Line2DROI(0, 0, 0, 32)
spectra.plot()
reference.plot()
line.interactive(reference)
line.interactive(spectra).plot()

 ---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_8040/2440577625.py in <module>
      2 spectra.plot()
      3 reference.plot()
----> 4 line.interactive(reference)
      5 line.interactive(spectra).plot()

C:\ProgramData\Anaconda3\envs\PhD\lib\site-packages\hyperspy\roi.py in interactive(self, signal, navigation_signal, out, color, snap, **kwargs)
    421         if navigation_signal is not None:
    422             if navigation_signal not in self.signal_map:
--> 423                 self.add_widget(navigation_signal, color=color, snap=snap,
    424                                 axes=kwargs.get("axes", None))
    425         if (self.update not in

C:\ProgramData\Anaconda3\envs\PhD\lib\site-packages\hyperspy\roi.py in add_widget(self, signal, axes, widget, color, snap, **kwargs)
    510         if widget.ax is None:
    511             if signal._plot is None or signal._plot.signal_plot is None:
--> 512                 raise Exception(
    513                     f"{repr(signal)} does not have an active plot. Plot the "
    514                     "signal before calling this method.")

Exception: <Signal1D, title: , dimensions: (64, 64|1)> does not have an active plot. Plot the signal before calling this method.
```

I cannot display a line profile linked between a hyperspectral and 2D dataset.

Essentially, the roi widget is complaining because it doesn't have a `signal_plot` to update when the roi moves. In the case of a 0D signal it makes sense that we cannot explore a pixel through a `signal_plot`, but clearly when taking a line profile, for example, ideally it would be possible to plot this. 

The exception raised makes it impossible to find a region on the 2D dataset nav and see where that lines up on the 3D dataset.

Happy to provide more info if needed.

Am currently using '1.7.0.dev0', so sorry if this is already being fixed!

**Comment by ericpre** [comment]
In this case, `interactive` is not suitable, because `roi.interactive` expect to return a signal, as sliced by the ROI. Instead, you should the `add_widget` method:

```python
import numpy as np

from hyperspy import signals
from hyperspy import roi

spectra = signals.Signal1D(np.linspace(0, 1, 64 * 64 * 128).reshape(64, 64, 128))  # some toy data
reference = signals.Signal2D(np.sin(np.linspace(-1, np.pi, 64 * 64)).reshape(64, 64))  # e.g. my SEM data

line = roi.Line2DROI(0, 0, 0, 32)
spectra.plot()
reference.plot()

line.add_widget(reference, axes=None) # depending on the signal, it may necessary to specify the `axes`
line.interactive(spectra).plot()
```

It would be to have more example to illustrate how to use the ROI, because it is easy to get confused!

**Comment by 0Hughman0** [comment]
Ah ok, thanks!

Yes is a bit confusing. Seems like the same operation to me.
