### ISSUE TITLE
Adding io_plugin and HyperSpy version to metadata?

### ISSUE THREAD

**Issue by jat255** [hyperspy/hyperspy#2873]
For the sake of future interoperability and reproducibility, I think it would be a good idea to add a couple of pieces of information to the Signal metadata under General. In particular, my proposal is that we note which `io_plugin` was used, as well as the version of HyperSpy at the time the Signal was loaded. I would propose that the metadata go from:

```
└── General
    ├── original_filename = test-1.dm3
    └── title = test
```

to 

```
└── General
    ├── File
    │   ├── io_plugin = hyperspy.io_plugins.digital_micrograph
    |   ├── hyperspy_version = 1.6.5
    |   └── load_timestamp = 2022-01-19T10:08:59.798538
    ├── original_filename = test-1.dm3
    └── title = test
```

I won't start working on this until there's some discussion about. What does everyone think?

**Comment by jat255** [comment]
As far as implementation, the `io_plugin` can be accessed via `__loader__.name`, while the timestamp and version would be `datetime.datetime.now().isoformat()` and `hyperspy.__version__`, respectively.

**Comment by ericpre** [comment]
Yes, sounds good. A few comments:
- would this information be overwritten each time or deleted when saving?
- if you put the date, is it worth putting the time zone?
- this information will be used only at runtime, when loading the file, instead of adding the `hyperspy_version` metadata, you may well get it from `import hyperspy; hyperspy.__version__` or by using `importlib.metadata`

**Comment by jat255** [comment]
Some responses:

- My thoughts are that this information should be a snapshot of the software used to load the Signal from the original file, so the metadata would not be changed by subsequent operations (such as saving). In this way, I view it similarly to the existing `original_filename` parameter.  
- I think I would make it a timezone aware datetime in UTC time, to be safe
- I was planning on putting the value of `hyperspy.__version__` into the metadata at the time the file is loaded.

Some questions for discussion:

- is `metadata.General.File` the right path to put this under? Perhaps `metadata.General.FileLoader` to be more explicit?
- Should `original_filename` be moved into this grouping? My thought is no, since that would potentially break backwards compatibility. It could be duplicated under `metadata.General.File`, but that's not ideal either. Not sure what the right solution here is.

These changes should be documented in the user guide as well.

**Comment by ericpre** [comment]
> Some responses:
> 
> * My thoughts are that this information should be a snapshot of the software used to load the Signal from the original file, so the metadata would not be changed by subsequent operations (such as saving). In this way, I view it similarly to the existing `original_filename` parameter.

How would deal with the situation where you save a file to a different format and load it again?

> * I think I would make it a timezone aware datetime in UTC time, to be safe
> * I was planning on putting the value of `hyperspy.__version__` into the metadata at the time the file is loaded.
> 
> Some questions for discussion:
> 
> * is `metadata.General.File` the right path to put this under? Perhaps `metadata.General.FileLoader` to be more explicit?

This sounds better indeed.

> * Should `original_filename` be moved into this grouping? My thought is no, since that would potentially break backwards compatibility. It could be duplicated under `metadata.General.File`, but that's not ideal either. Not sure what the right solution here is.

It is possible to deprecate some metadata if necessary with a transition period and a warning.

> These changes should be documented in the user guide as well.

Yes, it should be describe in https://hyperspy.readthedocs.io/en/stable/user_guide/metadata_structure.html

**Comment by jat255** [comment]
I just submitted a draft PR; I'll change `File` to `FileReader`. As for

> How would deal with the situation where you save a file to a different format and load it again?

Currently, the code would overwrite the metadata since it was reloaded, which admittedly is not probably what we want:

```
>>> s = hs.load('~/tmp/msa_file.msa')
>>> s.metadata
...
├── General
│   ├── File
│   │   ├── hyperspy_version = 1.7.0.dev0
│   │   ├── io_plugin = hyperspy.io_plugins.msa
│   │   └── load_timestamp = 2022-01-19T12:57:21.222973-07:00
...
>>> s.save('~/tmp/msa.hspy')
>>> s2 = hs.load('~/tmp/msa.hspy')
>>> s2.metadata
...
├── General
│   ├── File
│   │   ├── hyperspy_version = 1.7.0.dev0
│   │   ├── io_plugin = hyperspy.io_plugins.hspy
│   │   └── load_timestamp = 2022-01-19T13:56:04.739100-07:00
...
```

In some ways this is literally correct, but I think it makes more sense to persist the original metadata

**Comment by jat255** [comment]
I've submitted #2874, which persists the metadata in `FileReader` through a save/load cycle as expected.

I wasn't sure how to handle `original_filename`, so I've left it untouched at this point, but I'm open to suggestions on how to deprecate. I suppose I could just duplicate it for now under `FileReader` as well.
