### ISSUE TITLE
Test failing: oldest supported dependencies

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#2892]
Currently the test which checks the oldest supported versions of the dependencies is failing.

The error message is a bit difficult to understand: 
```python
 hyperspy/tests/utils/test_stack.py ................                      [ 99%]
Error: The operation was canceled.
```
so not sure what is causing it.

Might be related to the runtime being over 30 minutes? I vaguely remember the limit being 30 minutes.

**Comment by ericpre** [comment]
The test suite run in less than 10 mins on github CI/linux. It looks like more a test hanging.

**Comment by jlaehne** [comment]
> Might be related to the runtime being over 30 minutes? I vaguely remember the limit being 30 minutes.

Yes, it is a timeout after 30 min. So @ericpre is probably right that some test is hanging.

**Comment by ericpre** [comment]
Log of last passed workflow:
[log_passed.txt](https://github.com/hyperspy/hyperspy/files/8240466/log_passed.txt)

Log of following (failed) workflow:
[log_failed.txt](https://github.com/hyperspy/hyperspy/files/8240468/log_failed.txt)
