### ISSUE TITLE
Bruker M4 Tornado X-ray fluorescence BCF file import works incorrectly

### ISSUE THREAD

**Issue by mstatkus** [hyperspy/hyperspy#2898]
BCF files are handled by `bruker.py` module, developed for SEM/TEM Bruker data. X-Ray fluorescence (XRF) mapping instrument Bruker M4 Tornado uses the same overall BCF file structure, but with many differences in metadata structure. Accelerating voltage data, required for processing of SEM files, is not provided in XRF BCF file header.

(I'm not sure whether it's a bug report or feature request, because there's no 'official' support of XRF BCFs.)

When `bruker.py` processes XRF BCF, `HyperHeader._set_microscope()` method is called in `HyperHeader. __init__()` (line 599) , voltage metadata is not found and `self.hv` is set to default value 0.0 (line 625).

`self.hv = self.sem_metadata.get('HV', 0.0)  # in kV`

Next, `HyperHeader.estimate_map_channels()` method is called by `BCF_reader.parse_hypermap` method (line 957); with `self.hv` set to zero, it results in incorrect cropping of energy axis (lines 768-772).

```
        bruker_hv_range = self.spectra_data[index].amplification / 1000
        if self.hv >= bruker_hv_range:
            return self.spectra_data[index].data.shape[0]
        else:
            return self.spectra_data[index].energy_to_channel(self.hv)
```

Example code, test BCF file is attached as .zip ([M4-xrf-test.zip](https://github.com/hyperspy/hyperspy/files/8193214/M4-xrf-test.zip) - sorry, it is about 25 Mb, I wasn't able to produce smaller one ).

```
import hyperspy.api as hs

hmap_full_load = hs.load('M4-xrf-test.bcf')
print (hmap_full_load[4].data.shape) 
# energy axis has 96 channels - incorrect
```

A simple workaround is to call file import with `cutoff_at_kV=40.` (or whatever the upper limit of energy axis is):

```
hmap_cutoff_load = hs.load('M4-xrf-test.bcf',cutoff_at_kV=40.)
print (hmap_cutoff_load[4].data.shape) 
# energy axis has 4095 channels - correct
```

However, for correct processing of X-ray lines, it is necessary to set 'fake' beam energy value after loading BCF file. 
```
hm = hmap_cutoff_load[4]
im = hm.get_lines_intensity()
# several lines are above limit of 50/2 kEv - errors

hm.set_microscope_parameters(beam_energy = 80)
# setting fake beam energy to 2*spectra energy range
im = hm.get_lines_intensity()
```

'Fake beam energy' value should be twice as upper limit of energy axis in hypermap [(see manual)](https://hyperspy.org/hyperspy-doc/current/user_guide/eds.html#:~:text=The%20most%20excited%20X%2Dray%20line%20is%20selected%20per%20element%20(highest%20energy%20above%20an%20overvoltage%20of%202%20(%3C%20beam%20energy%20/%202)))

As far as I know, full support of XRF BCF files (#1734) and creation of specialized XRF signal (#1783) were planned, but not yet implemented. In this regard, what is the best approach to the issue of handling XRF BCF's now? Maybe a warning should be raised by `bruker.py` when no HV data is found during import?

**Comment by ericpre** [comment]
It looks to me that your observations are spot on and find the relevant information! You are more than welcome to make a pull request and just in case this is useful, we have a [developer guide](https://hyperspy.readthedocs.io/en/stable/index.html).

> As far as I know, full support of XRF BCF files (#1734) and creation of specialized XRF signal (#1783) were planned, but not yet implemented.

Indeed, nothing happen with respect to XRF signal because it seems that nobody have been pushing for it. I have never used XRF but given the similarity with EDS and what is implemented in hyperspy, it shouldn't need much work. There are plan to split specialized signal type, such as EDS, EELS, etc. into separate libraries to enable lighter and independent code development, [the infrastructure is already in place](https://hyperspy.readthedocs.io/en/stable/dev_guide/writing_extensions.html) and used by various libraries but the split hasn't happen yet. If you are interested in creating a XRF signal, you could either a hyperspy extension or add it to hyperspy.

>  In this regard, what is the best approach to the issue of handling XRF BCF's now? Maybe a warning should be raised by `bruker.py` when no HV data is found during import?

Is there no beam energy in the metadata of the file? Is it possible that it is saved somewhere else?

**Comment by mstatkus** [comment]
I think that changes to `bruker.py` should be kept to minimum, for not to break its main functionality of SEM/TEM data import - BCF files have an intricate and confusing structure. So I propose to keep things simple and just add a warning message if no HV value is found:

```
self.hv = self.sem_metadata.get('HV', 0.0)  # in kV - line 625
if self.hv == 0:
	_logger.warning("""No accelerating voltage data found during BCF import.
                              Voltage set to zero by default, which could result in errors in further data processing.
                              Consider setting manual cutoff_at_kV parameter for BCF file import.""")
```

I'll make a pull request for this modificaion in a couple of days (I've got some Python coding experience, but I'm not yet familiar with github forks, pull-ups etc).

> Is there no beam energy in the metadata of the file? Is it possible that it is saved somewhere else?

XRF BCF files contain X-ray tube voltage value, which is somewhat similar to accelerating voltage in SEM. This value is extracted in lines 539-543 of `bruker.py`:

```
if xrf_header:
	xrf_header_dict = dictionarize(xrf_header)
	self.esma_metadata = {
		'PrimaryEnergy':xrf_header_dict['Voltage'],
		'ElevationAngle':xrf_header_dict['ExcitationAngle']
		}
# USED:
self.hv = self.esma_metadata['PrimaryEnergy']
```

However, this `self.hv` is in `EDXSpectrum` class, not `HyperHeader` class - and cropping of spectrum energy range is made on the basis of `HyperHeader`.  Moreover, XRF `self.hv` could not be used for simple estimation of spectrum energy range, because XRF lines exitation efficiency depends not only on tube voltage, but also on tube anode matherial.

So, I think that a seperate XRF signal plugin would be necessary for strict handling of this issue. I've been working with Bruker microXRF data in Hyperspy for about a year, and I've made some quick-and-dirty XRF data processing scripts - so, I hope to rework them for a Hyperspy XRF signal plugin - in the more or less distant future.

I've spotted one more possible bug related to Bruker microXRF BCF import - but not related to voltage value. Would it be better to open a seperate issue - or to post it to this thread as a next message?

**Comment by ericpre** [comment]
Overall, this sounds all sensible.

> I've spotted one more possible bug related to Bruker microXRF BCF import - but not related to voltage value. Would it be better to open a seperate issue - or to post it to this thread as a next message?

Smaller PR are better and recommended, as it helps to isolate specific issue and avoid mixing up different issues. Large PRs take more time to get done properly and for us to review but sometimes, there are not avoidable. In your case, it should be small changes per PR and as many as necessary. Also, if you are not very familiar with github, making small PR is good to keep it simple and not getting confused with git/github!

**Comment by ericpre** [comment]
@mstatkus: this package may be relevant: https://github.com/pquinn-dls/flupy

**Comment by sem-geologist** [comment]
I see, I had left some mess in place. This cutting of at HV backfires now - ouch. The feature of cutting at acceleration voltage was intended for memory saving. Maybe this memory saving option should be made to be optional - not default and enforced as is now - that would make this XRF work. I was developing library while being a poor student, and my laptop had only 4GB of ram, thus I put into bruker reader lots of these memory saving "features" there and here. It looked then for me that such default memory saving is good and universally wished feature, and there is nothing bad at saving memory (I wish all those snowflake developers making programs in electron and other RAM-hungry frameworks would have low end gear).

@ericpre , actually this whole SEM/TEM metadata branching nonsense drives me crazy (I already opened a discussion 4 years ago hyperspy/hyperspy#2095 ), and making this µXRF to work would need to put that under SEM or TEM even if it is neither, and separate package will not change the fact that it will need a hack around this SEM/TEM (#2052). There should be no SEM_EDS, TEM_EDS, XRF_EDS signals, but only EDS with `source_mode` as an attribute instead making that to be parent branch of near identical metadata branch of EDS. Modes could be SEM, TEM, XRF... but hell, there is more ways to excite Xrays in the  solid matter i.e. proton bombardment (PIXE), we should always be open for even more new possibilities. EDS detector don't care about how You generate the X-rays it does not absolutely change anything in EDS hardware. Is EDS above sample, below, perpendicular, 30 degrees to electron beam, 30 degrees to XRF beam, 2 degrees to proton source? - the  EDS hardware does not care and just register the incoming X-rays. Xrays from proton, secondary flourescence (XRF), electron interaction (SEM,TEM) will have same properties of EDS (channel size, throughput/shaping time, spectral resolution, spectrometer efficiency/energy) - and that is properties of a Signal. It is the researcher who register that signal and does care and wants to have different set of tools to  treat that signal, depending from its orientation to sample and the source of energy for Xray generation in the matter. With how HyperSpy API requires EDS Signal types to be one of EDS_SEM/EDS_TEM puts a cart before horse, no wait - that is wrong metaphor - it actually merges the horse with a cart! It merges two different parts of science "the measurement" and "the interpretation" into single piece - convenient when You interpret what You expect. Or this is just a classical side effect of OOP (not that I would be against OOP, but here it gets clearly in the way).

So I think the easiest way and temporary workaround is to make the cutting to hv be not used by default, and for saving memory make it optional. I can open the PR to make that change.

**Comment by sem-geologist** [comment]
@mstatkus , wait.
Warning message is not proper thing (The user had done nothing wrong).
I see where the real problem generates.
it is calling of method from header `estimate_map_channels()` and its content; the logic there is simply completely not adequate as is not taking into account any other xray production than from electron bombardment.
The header contains always the sum spectra, which could be here overused to cut at last non-zero channel. I would leave the current method too, the Bruker scales energies to 10, 20, 40 and 80 kV, but we can set sources to arbitrary excitation voltage (i.e. 15kV) and thus it makes sense to cutoff at precise voltage.

**Comment by sem-geologist** [comment]
> I've spotted one more possible bug related to Bruker microXRF BCF import - but not related to voltage value. Would it be better to open a seperate issue - or to post it to this thread as a next message?

What is it?

**Comment by mstatkus** [comment]
Dear @sem-geologist , first of all I want to express my sincere gratitude to you for developing a library for BCF files and for willing to support this code since 2016.

I've tried version of `bruker.py` from your proposed pull request hyperspy/hyperspy#2910 on my test BCF file without setting `cutoff_at_kV`, and import passed successfully.

However, there's a second part of this uXRF-bug, that is related to method `get_lines_intensity()` of EDS Signal. If no beam energy is found during BCF import, it is silently set to zero by default, and, afterwards, calling `get_lines_intensity()` yields a bunch of UserWarnings, e.g.:
```
eds.py:533: UserWarning: Y_Ka is not in the data energy range. 
You can remove it with: `s.metadata.Sample.xray_lines.remove('Y_Ka')
```

Maybe `get_lines_intensity()` should check wheter beam energy is zero, and print some info to user?

**Comment by mstatkus** [comment]
> > I've spotted one more possible bug related to Bruker microXRF BCF import - but not related to voltage value. Would it be better to open a seperate issue - or to post it to this thread as a next message?
> 
> What is it?

Import of BCF files containing microXRF data from Bruker Tornado M4 spectrometer sometimes results in strange visual patterns on element intensity maps - vertical stripes of alternating intensity. These artifacts are usually visible for areas where line intensity is high. Two images below are Fe Ka intensity maps from the same BCF file: image on the right was produced by Hyperspy (after import by `bruker.py` module), image on the left - exported from Bruker software. Example BCF file is attached as .zip (the [same file](https://github.com/hyperspy/hyperspy/files/8193214/M4-xrf-test.zip)   as in the first post, python code used for import and generation of image is here:

![map_artifact](https://user-images.githubusercontent.com/28139441/160246079-52a9c7bc-42e3-4326-95e2-dd6ee2b307dd.png)

```
import hyperspy.api as hs
hm = hs.load('M4-xrf-test.bcf',cutoff_at_kV=40.)

# setting fake beam energy to 2*spectra energy range
hm.set_microscope_parameters(beam_energy = 80)

im = hm.get_lines_intensity()
fe=im[7]
fe.plot() # stripes?
```

I've checked whether import with pure python py_unbcf function would solve this problem - but unfortunately it did'n help.

Debugging cython code for unpacking binary file with complicated undocumented structure is way beyond my coding skills. Hovewer, when I examined `unbcf_fast.pyx`, which contain code for BCF binary hypermap unpacking, I've found this comment (lines 43-45)
```
cdef uint64_t read_64(unsigned char *pointer):
    # skiping the most high bits, as such a huge values is impossible
    # for present bruker technology. If it would change - uncomment bellow and recompile.
```

M4 microXRF spectrometer is equipped with relatively new large area SDD detector, which is capable of processing up to 275 thousands counts per second. 
I've got a gut feeling that stripes on hypermaps might be caused by some kind of segmentation faults in processing binary data, when map pixel contains spectrum with unusually high sum intensity.

Unfortunately, I've got no experience with cython and/or compiling C modules...

**Comment by sem-geologist** [comment]
@mstatkus , Thank You for the kind words.
I got a bit distant from HyperSpy development lately as I have very little to do anymore with SEM, but do EPMA everyday (high precision/ accuracy WDS stuff), and get to SEM for some advanced non-everyday techniques rarely. Fortunately I still have to deal with bruker formats as EPMA is equipped with XFlash Nano of Bruker.

The stripe problem.
To overflow 2^32 (32bit unsigned integer) with count rate of 275 kcps You would need to gather data for more than 10 days.
That is pretty medium count rate. Our SEM 2 EDS simultaniously can push more than 1Mcps. The largest me known EDS technologically achievable throughput is about 8Mcps (AMPTEK). That is pushing current counting and signal amplifying to the very limits, to go over that would require a completely some new technological breakthrough.
Even so I often try not to use such a high rates as it will produce very huge dead times which introduce lots of unresolvable spectral artifacts. High count rate and high deadtime could be the reason here. Esprit could show dead time corrected values, but Hyperspy is showing only the raw counts as I had not implemented dead time decoding from pixels. I have few issues open with dead time for Bruker (it is coded inside spectra, per pixel) - I could not figure out how does it exactly work.
Currently I am investigating very fundamentals of deadtime on proportional counters on our WDS EPMA, and it starts to be for me more clear how that could work in Bruker EDS. Is it possible to change counts per second to total counts in the Esprit (cts should be not dead time corrected, where counts per second would be dead time corrected)? With high count rates it is very possible to get such vertical stripes. I will look into file, maybe I can find out what is causing (also, Esprit has possibility to look to data through filters "median", "gaussian" - those would blur those stripes. Please ensure that it was None)

**Comment by sem-geologist** [comment]
BTW, to produce smaller file You can (1) configure small image size (AFAIK it is 100pixels wide) then, (2) hyper cube can be limited to smallest ROI of 16 pixels, that will make small file. It can be compressed even more using builtin compression (there should be compression checkbox at save as window).

**Comment by sem-geologist** [comment]
@mstatkus , Yes this looks absolutely dead time thing, I made a quick and dirty check up (now that I think I know more how hardware works).
I load the file:
```python
hm = hs.load("M4-xrf-test.bcf", cutoff_at_kV=60, select_type="spectrum_image")
hm.set_microscope_parameters(beam_energy=80)
```
First of all I look how wide 0V peak is as it is saving the live time (I see it is from -0.15 to 0.15 keV). So I select it and sum at axis 2 (channels) and divide by ZeroPeakFrequency (which is times per second and most of Bruker EDS has that 10000, which would be every 0.1 ms pulse is checked if it can pass the detection pipeline - if it pass - then fragment of time can be counted as livetime. It is looking for most time consuming event - full discharge of capacitor in charge sensitive preamplifier, which blocks any pulses from being registered for few (or hundred+) miliseconds)
```python
hm_live_time = hm.isig[-0.15:0.15].sum(2) / hm.original_metadata.Hardware.ZeroPeakFrequency
```
That is signal with live time in seconds. Damn, that is so simple, and few years ago I could not completely grasp how that all works and tried to over-engineer and reverse engineer that...
So having live time array, we can now recalculate hypermap to deadtime corrected values:
```python
hm_corrected = hm / hm_live_time
```
.... but that would be memory inefficient. Much better is to get the intensities for iron from not recalculated hypermap (where we still are dealing with compact 16bit unsigned integer arrays). `hm_corrected` however would be 64 bit floating point - that is 4 times more RAM. This simple file is ok, but with normal dataset that would easily bring us to trouble.

So after doing this:
```python
im = hm.get_lines_intensity()
```
to get Fe intensities we should do this:
```python
fe = im[7] / hm_live_time
```
`fe.plot()` wil produce this:
![date_time_corrected](https://user-images.githubusercontent.com/12324068/160258064-9ecdeb34-d69c-44b4-b815-3b0832a1a259.png)

There is small caveat that fe units is no more `counts` (that is wrong in the plot), but `counts per second`.

**Comment by mstatkus** [comment]
> Yes this looks absolutely dead time thing

Dear @sem-geologist , thank you once more - now for solving the "stripes" mystery. It is obviously related to dead/live detector time, and not to reading binary data from BCF. 

After reading your post, I've recalled that I've seen a piece of data called `PixelTimes` in Bruker BCF XML header, when I tried to find out a way to extract mosaic images (which can be a topic of a separate future post).

Here's my quite clumsy code to get this data - mostly bits and pieces borrowed from your `bruker.py` library:

```python
import hyperspy.io_plugins.bruker as bruker
import xml.etree.ElementTree as ET
import numpy as np
import codecs

#extracting BCF header as XML
bcf=bruker.BCF_reader("M4-xrf-test.bcf")
header_file = bcf.get_file('EDSDatabase/HeaderData')
header_byte_str = header_file.get_as_BytesIO_string().getvalue()
hd_bt_str = bruker.fix_dec_patterns.sub(b'\\1.\\2', header_byte_str)
root = ET.fromstring(hd_bt_str)
root = root.find("./ClassInstance[@Type='TRTSpectrumDatabase']")

#finding PixelTimes Image node
pixel_times_node = root.find("./ClassInstance[@Name='PixelTimes']")

#getting shape of image
width = int(pixel_times_node.find('./Width').text)  # in pixels
height = int(pixel_times_node.find('./Height').text)  # in pixels

#getting PixelTimes Image data
pixel_times_data_raw = pixel_times_node.find('./Plane0/Data').text
pixel_times_data = codecs.decode(pixel_times_data_raw.encode('ascii'), 'base64')
pixel_times_array = np.frombuffer(pixel_times_data, dtype='u4')
pixel_times_array = pixel_times_array.reshape((height, width))
```

Now, if we plot these two arrays (`pixel_times_array` and `hm_live_time.data`) side by side,...


```python
#plotting
fig, axes = plt.subplots(nrows=1, ncols=2, dpi=300)

axes[0].imshow(pixel_times_array)
axes[0].set_title('pixel times livetime')

axes[1].imshow(hm_live_time.data)
axes[1].set_title('zero peak livetime')

```
...we get a very similar picture:

![pixel_times](https://user-images.githubusercontent.com/28139441/160412390-54fc7d85-6c36-4b31-8b6d-d14477347a87.png)


The difference is noticeable on the parts of image, where the sample-detector distance was greater (due to rough surface of the sample).

So, it looks like in uXRF BCF files, Bruker stores dead/live time pixel data separately from the hypermap itself.

**Comment by sem-geologist** [comment]
which esprit version? some early esprit 2 versions contained allready this live time array - but it was all zeroes, thus its reading was not implemented. This at last brings better understanding to our first attempt hyperspy/rosettasciio#239 to solve this. Now this is very clear evidence - esprit cuts corners. zero voltage peak comes straight from hardware - it is registered during spectra acquisition. In above case the righ side is more true than what esprit presents, as live time increases when there is less pulses to count.

**Comment by mstatkus** [comment]
> which esprit version?

Well, it's not exactly Esprit - it is M4 Tornado software based on Esprit, its version is 1.6.262.0
![screenshot](https://user-images.githubusercontent.com/28139441/160467828-36a29bd7-99f1-4906-9d72-8b3124918ca6.png)

**Comment by sem-geologist** [comment]
I see, I am keen more on the zero peak method, as it is (1) universal for old and new bcf; (2) it clearly is more correct live time. The dark parts of image (lower counts) should have more live time, as less pulses (1) saturates preamplifier and its capacitor in lesser rate (minimizing need for long reset), (2) and less pulses means less short dead-times after every pulse. I am trying to understand why Bruker is not using zero voltage peak correctly (maybe it is using lesser energy window...?), or maybe it really use the pulse density as described in hyperspy/rosettasciio#239? Knowing many other hardware/software quirks of other Vendors, some absolutely bizarre reason behind this would not surprise me at all... Anyway, I think at HyperSpy we should use  the correct livetime even if that differs a bit from Bruker's software behaviour (in the end our reader already differs positively in reading speed).

**Comment by mstatkus** [comment]
I also think that using zero peak dead time calculation is a better approach than extracting `PixelTimes` array from BCF.

There are several questions related to zero peak method:

1. How should we choose the width of the integration window? Should it be fixed (in units of keV or in the number of channels)?

2. Should we calculate the width of integration window for each new spectrum (new pixel) from the zero peak half-width?

3. Should the dead time correction be applied automatically to raw data when importing?

**Comment by sem-geologist** [comment]
Good questions.
1. `zero_peak_1sigma = np.sqrt(loaded_eds.original_metadata.Signal.SigmaAbs)` funnily that is just one of many other inconsistently (wrongly) named XML nodes in Bruker formats. What it saves under `SigmaAbs` is in real the variance variance. So to get the sigma square root needs to be taken. Then that gaussian peak can be fit in range of 3sigmas to both sides. However as I had found in hyperspy/rosettasciio#239 using a bit more than 3 sigmas (i.e. 3.45) gives better result. We should remember that 0V is close to ground noise, and there can be other energy deviation sources. Going anything above that can lead to contaminate integral of 0V with some real very low energy X-ray counts. In the real life there is no absolute sharp boundary between 0V pulse and low energy Xrays, the boundary is not clear cut, always a bit washed out. The most important thing the 0V peak integral  is completely automatable. It can't be fixed to static value as it changes depending from chosen throughtput (as all peaks broadens so do 0V too, and then the real Xray energy linespace is cut from the low energy side. I.e. in low throughtput mode and most best resolution B Ka is completely exposed, and on some spectrometers (this is where spectrometer spectral resolution starts to matter for real) even partly Be Ka is available. however setting to highest throughtput and lowest resolution the Be and B Ka is no more measurable, the C Ka is first element which can be measured as more of energy axis is reserved for much broader 0V peak.
2. It is same for whole file. (1) `SigmaAbs` is written down once in the sum spectrum inside bcf in XML header. (2) It does not depend from dead time and count rates and depends from the pulse processing pipeline which is fixed during acquisition. Well, normally, except... unfortunately Bruker leaves possibility to do some most useless and worst anti-feature thing - set the throughput to "auto". Would we get mixed sigmas at single pixel? would next pixel reduce shapping time (increase throughput) What is response of the system to high counts? - all those are enigma. It is such bias antifeature which is extremely hard to cope with. (Theoretically, 0V peak could be used for fitting pseudo-Voigt function (few itterations of interfereing gausian bells with different sigma would produce something like that.). Then such function could be enlarged and fitted to lines of elements with corresponding widening (does `SigmaLin` stays same between shapping time changes?). Generally, I don't think anyone would appear here with such tremendous amount of time which such pointless en-devour would require to be implemented.  
3. In my opinion that is an absolute "no". Multiplying with livetime should be delayed as much as possible in processing to preserve memory (RAM). If we would multiply with livetime whole loaded hyperspectra (spectral_image) we basically would get in worse case twice sized array (32uint -> 64double), or in worst case 8 times the size (8uint -> 64float). In some case such n-dimensional array 64bit could be cast into 32 float (single precision), but then there should be taken care to do no math with integers as that triggers numpy casting the dtype of array into 64bit floating point. The work around is to cast everything to 32bit float, and with some care going to 64bit float then can be prevented.

**Comment by sem-geologist** [comment]
@ericpre, discussing 3rd point I just thought that probably ML algorithms and these PCA and etc requires floating point arrays (32 or 64bit?)? could You elaborate shortly?

**Comment by ericpre** [comment]
> @ericpre, discussing 3rd point I just thought that probably ML algorithms and these PCA and etc requires floating point arrays (32 or 64bit?)? could You elaborate shortly?

We check that the data are float type:
https://github.com/hyperspy/hyperspy/blob/c7dc06cc4d98233cea30cc2474850edd1db00a7f/hyperspy/learn/mva.py#L238-L246

**Comment by sem-geologist** [comment]
so np.float32 would also work?

**Comment by ericpre** [comment]
Yes

**Comment by sem-geologist** [comment]
@mstatkus, the cutoff_at_kV bug got fixed (consider closing this issue). Lets move the discussion on livetime to the dedicated issue hyperspy/rosettasciio#239  for the dead/livetimes in bcf. Is zero_peak method correct and Bruker method not? It actually start to doubt the correctness of zero_peak, I will present situation more clearly in the hyperspy/rosettasciio#239 issue.

**Comment by mstatkus** [comment]
Dear @sem-geologist and @ericpre , thank you for your efforts. The problem with cutoff is fixed.
Dead/live time and stripes problem is worth separate discussion, I'll post some comments in hyperspy/rosettasciio#239 later.

**Comment by divyadeepharbola** [comment]
Does Hyperspy support .BCF file of micro-XRF now? I am getting error File format not supported.

I even Tried with RosettaSciIO bcf import function

```
import rsciio 
rsciio.bruker.file_reader(r'MS-1b_S.bcf', cutoff_at_kV='auto')
```



I am getting error

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[45], line 1
----> 1 rsciio.bruker.file_reader(r'MS-1b_S.bcf', cutoff_at_kV='auto')

File ~\miniconda3\envs\xrd_analysis\Lib\site-packages\rsciio\bruker\_api.py:1314, in file_reader(filename, lazy, select_type, index, downsample, cutoff_at_kV, instrument)
   1312 ext = splitext(filename)[1][1:].lower()
   1313 if ext == "bcf":
-> 1314     to_return = bcf_reader(
   1315         filename=filename,
   1316         lazy=lazy,
   1317         select_type=select_type,
   1318         index=index,
   1319         downsample=downsample,
   1320         cutoff_at_kV=cutoff_at_kV,
   1321         instrument=instrument,
   1322     )
   1323 elif ext == "spx":
   1324     to_return = spx_reader(
   1325         filename=filename,
   1326         lazy=lazy,
   1327     )

File ~\miniconda3\envs\xrd_analysis\Lib\site-packages\rsciio\bruker\_api.py:1374, in bcf_reader(filename, lazy, select_type, index, downsample, cutoff_at_kV, instrument)
   1346 """
   1347 Reads a bruker ``.bcf`` file and loads the data into the appropriate class,
   1348 then wraps it into a list of dictionaries typically used by the
   (...)
   1370     Can be either 'TEM' or 'SEM'.
   1371 """
   1373 # objectified bcf file:
-> 1374 obj_bcf = BCF_reader(filename, instrument=instrument)
   1375 if select_type == "image":
   1376     return bcf_images(obj_bcf)

File ~\miniconda3\envs\xrd_analysis\Lib\site-packages\rsciio\bruker\_api.py:888, in BCF_reader.__init__(self, filename, instrument)
    887 def __init__(self, filename, instrument=None):
--> 888     SFS_reader.__init__(self, filename)
    889     header_file = self.get_file("EDSDatabase/HeaderData")
    890     self.available_indexes = []

File ~\miniconda3\envs\xrd_analysis\Lib\site-packages\rsciio\bruker\_api.py:310, in SFS_reader.__init__(self, filename)
    308 # read the file header
    309 with open(filename, "rb") as fn:
--> 310     a = fn.read(8)
    311     if a != b"AAMVHFSS":
    312         raise TypeError("file '{0}' is not SFS container".format(filename))

OSError: [Errno 22] Invalid argument
```

Apologise if I Posted in wrong forum

**Comment by ericpre** [comment]
@divyadeepharbola, it seems that your comments fell through the cracks...

There are some micro-XRF files that have been provided by various users and they all works. I am trying to improve the documentation on what XRF bcf files are supported but if you still have some files that are not working, could you please provide smallest possible test files as mentioned in https://github.com/hyperspy/rosettasciio/pull/471.
