### ISSUE TITLE
How can I return 'energy loss axis value' from EELS mapping data?

### ISSUE THREAD

**Issue by jykim1299** [hyperspy/hyperspy#2923]
I want to return the x-axis value(energy loss, eV) from the EELS mapping data where each pixel has a spectrum.
(ex. 500eV, 500.25eV ... 699.75eV, 700eV numpy dtype)

Data is a 3-dimensional structure(256*256|2048).

When a signal is returned, the x-axis value disappears or is returned as 1 to 2048.

![111](https://user-images.githubusercontent.com/44154065/162646031-042c9941-dad9-48b3-bcb1-f6542a4ad133.PNG)

Please help.

**Comment by ericpre** [comment]
You can access the `axis` through:

```python
import hyperspy.api as hs

s = hs.datasets.artificial_data.get_core_loss_eels_line_scan_signal()
energy_axes = s.axes_manager.signal_axes[0].axis
energy_axes.axis
```

This is documented in the [development version](https://hyperspy.readthedocs.io/en/latest/user_guide/axes.html#summary-of-axis-properties), which should be released soon, but not in the release version.

**Comment by jykim1299** [comment]
I checked this code and it runs fine.

thank you for reply. :)
