### ISSUE TITLE
.Seq File Format Loading

### ISSUE THREAD

**Issue by CSSFrancis** [hyperspy/hyperspy#2934]
#### Addition of .seq File format loading for hyperspy
Direct Electron cameras load using a .seq file format which is developed by Stream Pix.  
#### Describe the context
There is support in `LiberTEM` for .seq files from some cameras and I have a general module for loading the data for all of their cameras [here](https://github.com/CSSFrancis/SeqIO).  It could be made better by using `np.memmap` which might increase the performance a little bi.t

#### Additional information
I will talk with Direct Electron a little more about their plans for the future. The file format has been changing slightly over the last year or so but is probably stable enough to seriously consider adding to `Hyperspy`

@uellue Do you have any comments here? I was planning on getting to this in the next month or so trying to combine some of the work already done.

**Comment by uellue** [comment]
@CSSFrancis sure! Maybe it would make sense to allocate one or two days on a short "hackathon" to get it working? Together we have both the HyperSpy and the LiberTEM know-how to make quick progress. Let me know what time works for you! Next month should be rather flexible until the 15th of June.

By the way, LiberTEM can use different I/O back-ends for most dataset types, so not only mmap, but also direct I/O and conventional I/O. Direct I/O can work wonders on systems with fast SSDs and constrained RAM. :-)

CC @sk1p

**Comment by CSSFrancis** [comment]
That sounds good to me. I'm interested in how you handle the different I/O backends and the benefits of them.  It seems like there is a lot of potential optimization as it seems like in most cases the operations I am using are mostly I/O bound. 

I am rather flexible at the end of May and the first week of June but I'm getting married June 18th so I probably should avoid scheduling myself for anything in the week before or after that :)

**Comment by uellue** [comment]
What about Tuesday 31st of May until early afternoon, and/or Thursday 2nd of June afternoon?

**Comment by sk1p** [comment]
> What about Tuesday 31st of May until early afternoon, and/or Thursday 2nd of June afternoon?

I'm free on both dates

**Comment by CSSFrancis** [comment]
Both of those work for me as well!

**Comment by matbryan52** [comment]
👋 Chiming in from the LiberTEM side, both dates are good for me, with a slight preference for the Thursday afternoon.

**Comment by uellue** [comment]
Should we maybe go for Tuesday and potentially a follow-up on Thursday? I have a feeling that we'll have quite some things to discuss and try, so we should use the time. :-)

**Comment by CSSFrancis** [comment]
> Should we maybe go for Tuesday and potentially a follow-up on Thursday? I have a feeling that we'll have quite some things to discuss and try, so we should use the time. :-)

Would you still like to meet tomorrow? We have to figure out time zones a little bit as I am I think 7 hours behind you.

**Comment by uellue** [comment]
Ah, on Tuesday afternoon Berlin time I have appointments. Maybe we can go for Thursday afternoon Berlin / Thursday morning your time @CSSFrancis?

**Comment by CSSFrancis** [comment]
Works for me!

**Comment by sk1p** [comment]
Works for me, too! Should we say Thursday 15:00 Berlin time?

**Comment by sk1p** [comment]
We can meet here: https://webconf.fz-juelich.de/b/cla-0hh-vsb-rre

**Comment by ericpre** [comment]
Closing as this is now rosettasciio concern!
https://github.com/hyperspy/rosettasciio/pull/11
