### ISSUE TITLE
EELS remove background doesn't work

### ISSUE THREAD

**Issue by Ruiky94** [hyperspy/hyperspy#2939]
Hi.

I want to remove EELS SI background using s.remove_background with fixed energy window.

A "interactive" option works well. (Setting energy window manually)

```highlossalign.remove_background(background_type = "Power law", zero_fill=True, fast=True)```

But when I set the energy window, It cannot remove background

```highlossalign.remove_background(signal_range=(825., 849.), background_type = "Power law", zero_fill=True, fast=True)```
(energy size(channel): 2048, offset 800eV)

How can I solve removing background without setting manually?

**Comment by francisco-dlp** [comment]
Thanks for reporting the issue.

The following works for me:

```python 
import hyperspy.api as hs

s = hs.datasets.artificial_data.get_core_loss_eels_signal(add_powerlaw=True)
snb = s.remove_background((550., 650.), fast=True, zero_fill=True, background_type="Power law")
```

What's exactly the issue in your case?

By the way, to report a bugs, it is usually more efficient to use our [bug report template](https://github.com/hyperspy/hyperspy/issues/new?assignees=&labels=type%3A+bug&template=bug_report.md&title=).

**Comment by ericpre** [comment]
@Ruiky94, when specifying `signal_range`, the background is not removed "in place", but a different signal is returned with background substraction: check the `snb` signal in @francisco-dlp example above.

Closing for now, please re-open, it you think that there is still an issue.

**Comment by Ruiky94** [comment]
Thank you!
