### ISSUE TITLE
h5py save errors in V1.7

### ISSUE THREAD

**Issue by erh3cq** [hyperspy/hyperspy#2940]
#### Describe the bug
Updated from1.6.X to 1.7.0 and now I am having save errors. I ran a notebook that was worked yesterday before I updated, and it also no longer saves and the same step.
Other trouble shooting:
- I placed `si.save(save+'si.hspy')` at beginning of the code block to test if saving the raw dm4 file works. Saving the original spectrum works, but the spliced one does not.
- I have tried saving the `sil` and `sih` signals they save fine. This points to the save error originating after stacking.
- I am inclined from the error to believe that the issue originates from the metadata in the stacked signal. I have tried setting `stack_metadata=0, lazy=False` as keywords but this did not help. Similarly with `stack_metadata=False`
- 

#### To Reproduce
```
si.save(save+'si.hspy')
        
Sr_zero = 1938.
Ti_zero = 440.
El, Eh = 40, 260
​
sil = si.isig[Ti_zero-El:Ti_zero+Eh]
sih = si.isig[Sr_zero-El:Sr_zero+Eh]
print(sil, sil.data.shape)
print(sih, sih.data.shape)
​
si = hs.stack([sil,sih], new_axis_name='E offset', lazy=False)
si.axes_manager['E offset'].offset = 0
si.axes_manager['E offset'].scale = Sr_zero-Ti_zero
si.axes_manager['E offset'].units = 'eV'
#si.axes_manager['z'].name = 'frame'
print(si, si.data.shape)
print(si.axes_manager)
​
si.save(save+'spliced.hspy')
<EELSSpectrum, title: SI000, dimensions: (150, 500|600)> (500, 150, 600)
<EELSSpectrum, title: SI000, dimensions: (150, 500|600)> (500, 150, 600)
[########################################] | 100% Completed |  0.1s
<EELSSpectrum, title: Stack of SI000, dimensions: (150, 500, 2|600)> (2, 500, 150, 600)
<Axes manager, axes: (150, 500, 2|600)>
            Name |   size |  index |  offset |   scale |  units 
================ | ====== | ====== | ======= | ======= | ====== 
               x |    150 |      0 |       0 |    0.03 |     nm 
               y |    500 |      0 |       0 |    0.03 |     nm 
        E offset |      2 |      0 |       0 | 1.5e+03 |     eV 
---------------- | ------ | ------ | ------- | ------- | ------ 
     Energy loss |    600 |      0 |   4e+02 |     0.5 |     eV 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_7844/4094641686.py in <module>
     18 print(si.axes_manager)
     19 
---> 20 si.save(save+'spliced.hspy')

~\Programs\mambaforge\envs\data-analysis-noDev\lib\site-packages\hyperspy\signal.py in save(self, filename, overwrite, extension, **kwds)
   3002             if extension is not None:
   3003                 filename = filename.with_suffix(f".{extension}")
-> 3004         hyperspy.io.save(filename, self, overwrite=overwrite, **kwds)
   3005 
   3006     def _replot(self):

~\Programs\mambaforge\envs\data-analysis-noDev\lib\site-packages\hyperspy\io.py in save(filename, signal, overwrite, **kwds)
    851         signal = _add_file_load_save_metadata('save', signal, writer)
    852         if not isinstance(filename, MutableMapping):
--> 853             writer.file_writer(str(filename), signal, **kwds)
    854             _logger.info(f'{filename} was created')
    855             signal.tmp_parameters.set_item('folder', filename.parent)

~\Programs\mambaforge\envs\data-analysis-noDev\lib\site-packages\hyperspy\io_plugins\hspy.py in file_writer(filename, signal, close_file, **kwds)
    255     try:
    256         writer = HyperspyWriter(f, signal, expg, **kwds)
--> 257         writer.write()
    258     except BaseException:
    259         raise

~\Programs\mambaforge\envs\data-analysis-noDev\lib\site-packages\hyperspy\io_plugins\_hierarchical.py in write(self)
    648 
    649     def write(self):
--> 650         self.write_signal(self.signal,
    651                           self.group,
    652                           **self.kwds)

~\Programs\mambaforge\envs\data-analysis-noDev\lib\site-packages\hyperspy\io_plugins\_hierarchical.py in write_signal(self, signal, group, write_dataset, chunks, **kwds)
    679 
    680         if write_dataset:
--> 681             self.overwrite_dataset(
    682                 group,
    683                 signal.data,

~\Programs\mambaforge\envs\data-analysis-noDev\lib\site-packages\hyperspy\io_plugins\_hierarchical.py in overwrite_dataset(cls, group, data, key, signal_axes, chunks, **kwds)
    627                     # If chunks is True, the `chunks` attribute of `dset` below
    628                     # contains the chunk shape guessed by h5py
--> 629                     dset = group.require_dataset(key, **these_kwds)
    630                     got_data = True
    631                 except TypeError:

~\AppData\Roaming\Python\Python39\site-packages\h5py\_hl\group.py in require_dataset(self, name, shape, dtype, exact, **kwds)
    227         with phil:
    228             if not name in self:
--> 229                 return self.create_dataset(name, *(shape, dtype), **kwds)
    230 
    231             if isinstance(shape, int):

~\AppData\Roaming\Python\Python39\site-packages\h5py\_hl\group.py in create_dataset(self, name, shape, dtype, data, **kwds)
    147                     group = self.require_group(parent_path)
    148 
--> 149             dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
    150             dset = dataset.Dataset(dsid)
    151             return dset

~\AppData\Roaming\Python\Python39\site-packages\h5py\_hl\dataset.py in make_new_dset(parent, shape, dtype, data, name, chunks, compression, shuffle, fletcher32, maxshape, compression_opts, fillvalue, scaleoffset, track_times, external, track_order, dcpl, allow_unknown_filter)
     73         errmsg = "Chunk shape must not be greater than data shape in any dimension. "\
     74                  "{} is not compatible with {}".format(chunks, shape)
---> 75         raise ValueError(errmsg)
     76 
     77     if isinstance(dtype, Datatype):

ValueError: Chunk shape must not be greater than data shape in any dimension. (17, 7, 7, 600) is not compatible with (2, 500, 150, 600)
```

#### Expected behavior
I expect the signal to stack then save.

#### Python environement:
Package                       Version   Location
----------------------------- --------- -----------------------------------------
abtem                         1.0.0b24
ansi2html                     0.0.0
appdirs                       1.4.4
argon2-cffi                   21.1.0
asciitree                     0.3.3
ase                           3.22.0
asteval                       0.9.23
async-generator               1.10
atomap                        0.3.1
attrs                         21.2.0
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
bleach                        4.1.0
blosc                         1.10.4
bokeh                         2.4.0
Brotli                        1.0.9
brotlipy                      0.7.0
cached-property               1.5.2
certifi                       2021.5.30
cffi                          1.14.6
chardet                       4.0.0
charset-normalizer            2.0.6
click                         8.0.1
cloudpickle                   2.0.0
colorama                      0.4.4
cryptography                  3.4.7
cycler                        0.10.0
Cython                        0.29.24
cytoolz                       0.11.0
dash                          2.3.0
dask                          2021.9.1
debugpy                       1.4.3
decorator                     5.1.0
defusedxml                    0.7.1
diffpy.structure              3.0.1
diffsims                      0.4.2
dill                          0.3.4
distributed                   2021.9.1
entrypoints                   0.3
fabio                         0.12.0
fasteners                     0.17.3
Flask                         2.0.3
Flask-Compress                0.0.0
fsspec                        2021.9.0
future                        0.18.2
Glymur                        0.9.4
h5py                          3.4.0
HeapDict                      1.0.1
hyperspy                      1.7.0
hyperspy-gui-ipywidgets       1.4.0
hyperspy-gui-traitsui         1.4.0
idna                          3.2
imagecodecs                   2021.8.26
imageio                       2.9.0
importlib-metadata            4.8.1
importlib-resources           5.2.2
ipykernel                     6.4.1
ipympl                        0.8.7
ipyparallel                   7.0.1
ipython                       7.27.0
ipython-genutils              0.2.0
ipywidgets                    7.6.5
itsdangerous                  2.1.2
jedi                          0.18.0
Jinja2                        3.0.1
joblib                        1.0.1
jsonschema                    3.2.0
jupyter-client                7.0.3
jupyter-core                  4.8.1
jupyter-dash                  0.4.1
jupyterlab-pygments           0.1.2
jupyterlab-widgets            1.0.2
kaleido                       0.2.1
kiwisolver                    1.3.2
link-traits                   1.0.3
llvmlite                      0.37.0
lmfit                         1.0.2
locket                        0.2.1
lxml                          4.6.3
MarkupSafe                    2.0.1
matplotlib                    3.4.3
matplotlib-inline             0.1.3
matplotlib-scalebar           0.7.2
mistune                       0.8.4
mpmath                        1.2.1
mrcz                          0.5.6
msgpack                       1.0.2
natsort                       7.1.1
nbclient                      0.5.4
nbconvert                     6.1.0
nbformat                      5.1.3
nest-asyncio                  1.5.1
networkx                      2.6.3
notebook                      6.4.4
numba                         0.54.0
numcodecs                     0.9.1
numexpr                       2.7.3
numpy                         1.20.3
olefile                       0.46
orix                          0.7.0
packaging                     21.0
pandas                        1.3.3
pandocfilters                 1.5.0
parso                         0.8.2
partd                         1.2.0
pickleshare                   0.7.5
Pillow                        8.3.2
Pint                          0.17
pip                           21.2.4
plotly                        5.6.0
pooch                         1.5.1
prettytable                   2.2.0
prometheus-client             0.11.0
prompt-toolkit                3.0.20
psutil                        5.8.0
PyCifRW                       4.4.1
pycparser                     2.20
pyface                        7.3.0
pyFAI                         0.20.0
pyFFTW                        0.12.0
Pygments                      2.10.0
pyOpenSSL                     20.0.1
pyparsing                     2.4.7
pyrsistent                    0.18.0
PySocks                       1.7.1
python-dateutil               2.8.2
pytz                          2021.1
pyUSID                        0.0.10
PyWavelets                    1.1.1
pywin32                       301
pywinpty                      1.1.4
pyxem                         0.13.3
PyYAML                        5.4.1
pyzmq                         22.3.0
requests                      2.26.0
retrying                      1.3.3
scanning-drift-corr           1.0.1
scikit-image                  0.18.3
scikit-learn                  0.24.2
scipy                         1.7.1
Send2Trash                    1.8.0
setuptools                    58.1.0
sidpy                         0.0.5
silx                          0.15.2
six                           1.16.0
sortedcontainers              2.4.0
sparse                        0.13.0
stem-4ddw                     0.1       c:\users\owner\documents\github\stem_4ddw
sympy                         1.8
tblib                         1.7.0
tenacity                      8.0.1
terminado                     0.12.1
testpath                      0.5.0
threadpoolctl                 2.2.0
tifffile                      2021.8.30
toolz                         0.11.1
tornado                       6.1
tqdm                          4.62.3
traitlets                     5.1.0
traits                        6.2.0
traitsui                      7.2.1
transforms3d                  0.3.1
typing-extensions             3.10.0.2
uncertainties                 3.1.6
urllib3                       1.26.7
wcwidth                       0.2.5
webencodings                  0.5.1
Werkzeug                      2.0.3
wheel                         0.37.0
widgetsnbextension            3.5.1
win-inet-pton                 1.1.0
zarr                          2.11.3
zict                          2.0.0
zipp                          3.5.0

#### Additional context
Add any other context about the problem here. If necessary, add screenshots to help explain your problem.

**Comment by francisco-dlp** [comment]
I can reproduce the bug as follows:

```python
import hyperspy.api as hs
import numpy as np

s = hs.signals.Signal1D(np.zeros((2, 500, 150, 600)))
s.save("test2.hspy")
```

It looks like the issue is with the chunk guessing function in HyperSpy rather than ``stack``.

As a workaround, you could use ``dask``'s ``guess_chunks`` instead as follows:

```python
si.save(save+'spliced.hspy', chunks=True)
```
or pass your own customized chunks.

**Comment by erh3cq** [comment]
adding `chunks=True` worked well. Thank you

**Comment by ericpre** [comment]
Done in #2943.
