### ISSUE TITLE
BaseSignal.map() does not show progressbar

### ISSUE THREAD

**Issue by hakonanes** [hyperspy/hyperspy#2946]
Am I correct in expecting a progressbar in HyperSpy v1.7 for this operation?

```python
>>> import numpy as np
>>> import scipy.ndimage
>>> import hyperspy.api as hs
>>> s = hs.signals.Signal2D(np.random.random((10, 64, 64)))
>>> s.map(scipy.ndimage.gaussian_filter, show_progressbar=True, inplace=True, sigma=2.5)
```

I'm not getting one. It seems like this call

https://github.com/hyperspy/hyperspy/blob/5f15a5497d27718adda17a7e89b79fff88207e69/hyperspy/signal.py#L5042

should be wrapped in a `dask.diagnostics.ProgressBar()` context if `show_progressbar=True`.

**Comment by ericpre** [comment]
Done in #2947.
