### ISSUE TITLE
SpanROI broken?

### ISSUE THREAD

**Issue by AEljarrat** [hyperspy/hyperspy#2950]
#### Bug description
When interactively slicing a signal using `SpanROI`, the result does not seem to update. This includes the resulting signal and the ROI coordinates. 

#### Code to reproduce
Here are some steps to reproduce the behavior. First, run the following code:

```python
import hyperspy.api as hs
import numpy as np

s = hs.signals.Signal1D(np.random.rand(1024))
s.plot()
roi = hs.roi.SpanROI()
s_span = roi.interactive(s)
s_span.plot()
```
Move the widget in the signal plot. No updates???

#### Expected behavior
The coordinates and the result should update.

#### Python environment:
I've tested this in:
 - HyperSpy version 1.7.1.dev0 (RELEASE_next_minor branch)
 - Python version 3.10.2
And also:
 - HyperSpy version 1.7.0 (conda-forge)
 - Python version 3.10.4

#### Additional context
It's not the first time I think I've found a bug and it turns out I did something wrong! I've tried to troubleshoot this one as best as possible, but I only have reduced time. Thank you in advance for trying this on your machine and letting me know how it went!

**Comment by magnunor** [comment]
I tested this on my own computer for `RELEASE_next_minor`, and I see the same thing: no updates.

Testing this on `1.6.5`, the plot updates. (But for this version, there `xlim` does not update properly, so the plotting is a bit strange).

**Comment by AEljarrat** [comment]
Thank you for testing this! I did a bit of testing myself and found out the widget seems to be working as intended. It looks like there could be some issue with the event handling. I am not very experienced with this so there's not much more I can do. 

Here's what I've tried so far in case you're interested. 

### ROI does not update when adding widget
```python
import hyperspy.api as hs
import numpy as np

s = hs.signals.Signal1D(np.random.rand(1024))
s.plot()
roi = hs.roi.SpanROI()
roi.add_widget(s)
```

### However, the widget does update
```python
import hyperspy.api as hs
import numpy as np

s = hs.signals.Signal1D(np.random.rand(1024))
s.plot()
roi = hs.roi.SpanROI()
roi.add_widget(s)

for rw in roi.widgets:
    break
```

After the plot is created, I try to see if the widget position and size update when moving the widget around, and they do.

```python
rw.position, rw.size # these update
```

Interestingly, there seems to be some broken method in the widget.

```python
rw.get_centre() #  this one is broken
```
I believe this shouldn't be an issue, since the ROI is not using the `get_centre` method.

**Comment by ericpre** [comment]
@AEljarrat: thanks for the bug report, this is a regression introduced in https://github.com/hyperspy/hyperspy/pull/2922 and it should be fixed in #2952. Could you please check if this is any issue remaining with the fixes in #2952?

**Comment by jlaehne** [comment]
At least #2952 fixes the related/duplicate bug reported in [LumiSpy/lumispy-demos#12](https://github.com/LumiSpy/lumispy-demos/issues/12)

Testing the snippet provided by @AEljarrat , the regression is fixed. The behavior is again as reported by @magnunor vor v1.6.5, the plot updates, but the xlims are fixed (which would be nice if they are updated as well for this specific constellation of an interactive roi).

**Comment by ericpre** [comment]
> At least #2952 fixes the related/duplicate bug reported in [LumiSpy/lumispy-demos#12](https://github.com/LumiSpy/lumispy-demos/issues/12)
> 
> Testing the snippet provided by @AEljarrat , the regression is fixed. The behavior is again as reported by @magnunor vor v1.6.5, the plot updates, but the xlims are fixed (which would be nice if they are updated as well for this specific constellation of an interactive roi).

To auto-update the x-axis of the plot, you need to specify `autoscale`, which by default is `'v'`:

```python
import hyperspy.api as hs
import numpy as np

s = hs.signals.Signal1D(np.random.rand(1024))
s.plot()
roi = hs.roi.SpanROI()
s_span = roi.interactive(s)
s_span.plot(autoscale='xv')
```

**Comment by AEljarrat** [comment]
Hi everyone! I have tried the `RELEASE_next_patch` branch and it looks like it's fixed. Thanks for checking out this bug and fixing it.
