### ISSUE TITLE
Plotting EELS Spectrum in .dm4 file

### ISSUE THREAD

**Issue by Psiche91** [hyperspy/hyperspy#2959]
#### Describe the bug
Hello, I am new to this Forum and in the use hyperspy, probably my bug is a stupid thing. 
I have a problem with plotting the EELS spectrum, inside in .dm4 file (Gatan File) 

#### To Reproduce
import hyperspy.api as hs
%matplotlib notebook

s = hs.load("data/[...].dm4")
s
<Signal2D, title: ADF Image (SI Survey), dimensions: (|512, 512)>,
 <EELSSpectrum, title: EELS Spectrum Image, dimensions: (364, 363|1638)>]

**s.plot()**
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_1736\1823596060.py in <cell line: 1>()
----> 1 s.plot()

AttributeError: 'list' object has no attribute 'plot'

#### Expected behavior
Why I can't plot the spectrum? 
What is a 'list file'?
Can I split the data?

Thanks to all

**Comment by francisco-dlp** [comment]
You get a list of Python objects because you are loading several files at once. You can simply index it to plot the object that you want e.g.:

```Python
s[0].plot()
s[1].plot()
```

You could also assign each object to a variable:

```python
adf, s = hs.load("data/[...].dm4")
s.plot()
adf.plot()
```

**Comment by Psiche91** [comment]
Thanks, So much Francisco !!!
