### ISSUE TITLE
model parameters bounds not respected

### ISSUE THREAD

**Issue by andrealorenzon** [hyperspy/hyperspy#2976]
I'm trying to fit a model with n Gaussian components to a signal.
I need to introduce boundaries to Gaussian components (A>0, sigma in a range, etc).  After fitting, model parameters are out of bounds.

```
# signal is imported from a csv file
y = np.array(spectrum.values)  # array of ~1000 readings, all positive, no noise, rather smooth
signal = hs.signals.Signal1D(y)
signal.axes_manager[0].name = "Frequency"
signal.axes_manager[0].units = "MHz"
signal.axes_manager[0].low_value = x.min()
signal.axes_manager[0].high_value = x.max()
signal.axes_manager[0].size= len(x)
signal.axes_manager[0].scale = x[1]-x[0]
signal.axes_manager[0].offset = x[0]

peaks = [1650, 1670, 1680]
n_components=3
max_sigma = 5
max_delta = 20
model = signal.create_model()

for n in range(n_components):
    comp =hs.model.components1D.Gaussian()
    comp.centre.bmin = float(peaks[n]-float(max_delta)) # i want to force gaussians to stay around provided peaks, or fail
    comp.centre.bmax = float(peaks[n]+float(max_delta))
    comp.A.bmin = 0.05
    comp.sigma.bmin = 0
    comp.sigma.bmax = max_sigma
    comp.name = f"Gaussian_{n}"
    model.append(comp)

model.multifit(method="leastsq")
```
Result:
![image](https://user-images.githubusercontent.com/43496697/180003327-dfd6f58a-b9ad-40fc-80b0-fdbac83ef789.png)

I expected parameters to remain between boundaries, and the model failing to fit (or to converge, with another fitter). Instead I have:
![image](https://user-images.githubusercontent.com/43496697/180003435-7c1eede6-257d-452c-bf64-b9a36ca34c4e.png)

What did I miss? Is there a way to really FORCE the parameters to remain in boundaries?

#### Python environement:
 - HyperSpy version: latest
 - Python version: 3.9.6
 - Everything runs inside a Streamlit application, if it may be in context

**Comment by francisco-dlp** [comment]
Try with `model.multifit(method="leastsq", bounded=True)`

**Comment by andrealorenzon** [comment]
`model.multifit(optimizer="leastsq", bounded=True)` seems to work. Thank you, I'll close the issue. :)

![image](https://user-images.githubusercontent.com/43496697/180016684-f9e832e6-a751-4a36-9c17-5b7add63c05f.png)
