### ISSUE TITLE
EDSSEMSpectrum wrong axis dimensions

### ISSUE THREAD

**Issue by omnivus** [hyperspy/hyperspy#2985]
Just updating: I've made some tests using versions from the conda-forge repo and verified that this issue appeared with HyperSpy 1.7.0 and is present in 1.7.1 as well. I've rolled back my system to 1.6.5.

#### Describe the bug

I am getting wrong axis dimensions from my .bcf files since Bundle-2022.05.02 was released.  My data files generated at 15keV on the same instument used to have the exact same energy dimension axis with 1595 points (see image 1, attached). In the last two releases (Bundles 2022.05.02 and 2022.06.19) the same files are now showing different energy dimension axis sizes (see image 2).

#### To Reproduce
Simply open a .bcf file with different bundles and see the change in energy axis size! The issue is present in the last two relases (Bundles 2022.05.02 and 2022.06.19) apparently. Older bundles present the correct energy axis size!
```
Minimum working example of code
```
%matplotlib qt
import hyperspy.api as hs
import numpy as np
import matplotlib.pyplot as plt

mp1 = hs.load("minerio_mapa-1.bcf")
mp2 = hs.load("minerio_mapa-2.bcf")

mp1
[<Signal2D, title: Ch 0, dimensions: (|100, 100)>,
 <Signal2D, title: Ch 0, dimensions: (|256, 224)>,
 <EDSSEMSpectrum, title: EDX, dimensions: (100, 100|2013)>]

mp2
[<Signal2D, title: Ch 0, dimensions: (|100, 100)>,
 <Signal2D, title: Ch 0, dimensions: (|256, 224)>,
 <EDSSEMSpectrum, title: EDX, dimensions: (100, 100|1989)>]

#### Expected behavior
These files should present the same energy axis size!!!!
![image-1_portable_2021-10-30_correct](https://user-images.githubusercontent.com/85632121/183531078-865e1d3d-1a9a-42e4-bd3f-32992055bdd6.jpg)
![image-2_portable_2022-06-19_wrong](https://user-images.githubusercontent.com/85632121/183531081-fc5a4e1b-fb11-485a-98d1-75cba9644776.jpg)

#### Python environement:
 (Bundles 2022.05.02 and 2022.06.19)
Previous bundles do not show the issue.

#### Additional context
Add any other context about the problem here. If necessary, add screenshots to help explain your problem.

**Comment by ericpre** [comment]
Thanks @omnivus for opening the issue. This is most likely related to changes introduced in #2910. Can you share these files to check if this is expected behaviour?

**Comment by omnivus** [comment]
Hi there @ericpre ! The EDS that I use is indeed a Brucker and the problem is surely related to #2910 and #2898 as well. I'm attaching zip versions of the bcf files. They are from tests I've been running and fortunately are very small!
I don't know about Brucker XRF bcf files, but the EDS files do have the beam energy in the metadata. Did 1.7.0 came out with changes in bcf handling for Brucker XRF files? From what i've read here, maybe that's what got EDS energy axis to extrapolate the maximum expected value. I hope my bcf files can help!
[minerio_mapa-1.zip](https://github.com/hyperspy/hyperspy/files/9339822/minerio_mapa-1.zip)
[minerio_mapa-2.zip](https://github.com/hyperspy/hyperspy/files/9339823/minerio_mapa-2.zip)

**Comment by ericpre** [comment]
This is behaving consistently as described in https://hyperspy.org/hyperspy-doc/current/user_guide/io.html#id10: it reads all channels by default and these two dataset have intensities at energy higher than 15 keV.

```python
import hyperspy.api as hs

s1 = hs.load('minerio_mapa-1.bcf')[-1]
s2 = hs.load('minerio_mapa-2.bcf')[-1]

hs.plot.plot_spectra([s1.sum(), s2.sum()])
# check the intensity in the last channel for both spectra, you will see that there is some above 15 keV
```

Maybe, what you would expect is:

```python
import hyperspy.api as hs

s1 = hs.load('minerio_mapa-1.bcf', cutoff_at_kV='auto')[-1]
s2 = hs.load('minerio_mapa-2.bcf', cutoff_at_kV='auto')[-1]

hs.plot.plot_spectra([s1.sum(), s2.sum()])
```
where `'auto'` will use the beam energy in this case.

I would say that if you care about the last energy channel, you should specify it and the parameter `cutoff_at_kV` allow you to do this in various ways. Does it make sense?

**Comment by omnivus** [comment]
Thank you @ericpre ! I've read #2910 but didn't got it the first time. I think I've got it now:

Until HS 1.6.5, when you loaded a bcf file with no parameters (resulting in cutoff_at_kV='None'), this produced a cutoff  based on the beam energy. So, all my data (fixed at 15keV) had exactly the the same energy axis(channels), as desired.

From HS 1.7.0 forward, if you load a bcf with no parameters (cutoff_at_kV='None'), there is no cutoff whatsoever ( a more correct approach, I concur!) and all channels/energy values up to the last one with a non zero value were read. 

So, despite of having the same beam energy, since HS 1.7.0, my files started to get a "random" cutoff above 15keV, due to "1 counts" appearing randomly on higher channels (normal behavior I guess). That´s why each one of my files started to show a different number of energy channels!  Now I can get it right if I remember to load the files setting the cutoff_at_kV at the desired value or 'auto'. 

Is this  interpretation correct? If so, since it was all a "newbie" misinterpretation from my part, the issue never existed and is therefore closed!

Just one last question: is there a way to load a bcf/spf file starting from a given energy value (like 1keV), so as to allow a "partial load", from 1keV to 10keV, for example, instead of only setting the upper cutoff value?

Once again thank you for your help!

**Comment by ericpre** [comment]
Yes, this is all correct!

> Just one last question: is there a way to load a bcf/spf file starting from a given energy value (like 1keV), so as to allow a "partial load", from 1keV to 10keV, for example, instead of only setting the upper cutoff value?

No, but you can use slicing (`isig`) syntax to keep the energy range.
