### ISSUE TITLE
Typo _ Hyperspy/tree/bremsstrahlung_rebased/hyperspy/misc/eds/detector_efficiency.py

### ISSUE THREAD

**Issue by OliDG** [hyperspy/hyperspy#2989]
#### Describe the bug
in Hyperspy/tree/bremsstrahlung_rebased/
Using "m_b.add_physical_background(detector='Super_X') " as in the docstring raises an error: KeyError: Super_X

#### Solution:
in Hyperspy/tree/bremsstrahlung_rebased/hyperspy/misc/eds/detector_efficiency.py

**there is a typo l.457 :** 
detector_efficiency['**'SuperX'**]
Should be: detector_efficiency['**Super_X**'] 
to match the docstring of the instance and the naming style of the others.

#### Python environement:
 - HyperSpy version: 1.8.0dev

**Comment by ericpre** [comment]
Transfered this report to the corresponding pull request - https://github.com/hyperspy/hyperspy/pull/2836#issuecomment-1222598871.

Note that this branch isn't in the hyperspy repository as it hasn't been merged; the pull request is not finished.
