### ISSUE TITLE
_Map_iterate is always Parallel

### ISSUE THREAD

**Issue by CSSFrancis** [hyperspy/hyperspy#2997]
#### _Map_iterate is always Parallel
Not sure if this is actually a bug or something that we should keep as the default.  Regardless it should be better documented. 

As every array which is passed to _map_iterate is cast to a dask array it is always run in parallel. The `parallel` kwarg isn't really used and the `num_workers` kwarg is only used when the data is stored in place or the data is computed on the spot for a non lazy output. 

#### Potential Solution
I think the best solution is to rewrite the documentation and remove the `parallel`  kwarg and maybe throw and warning when num_workers is passed to a lazy signal?

For the lazy case these arguments should be passed to the `s.compute` following #2971 or set when a scheduler is initialized. 

Just for reference this is how I usually handle setting my `dask` backend. 
```python
# using threaded scheduler
s.compute(num_workers=20)
```

```python
# set up a local cluster using distributed scheduler
from dask.distributed import Client
client = Client() 

s.compute(num_workers=20)
```

```python
# creating a remote distributed scheduler on a cluster using a SLURM Manager
from dask_jobqueue import SLURMCluster

cluster = SLURMCluster(cores=40,
                       memory ='120GB',
                       walltime="12:00:00")
from dask.distributed import Client
cluster.scale(1)
client = Client(cluster)

s.compute() #uses all available workers

```

**Comment by jlaehne** [comment]
Close as #3198 merged?

**Comment by CSSFrancis** [comment]
Yea
