### ISSUE TITLE
AttributeError on spikes_removal_tool() when using "show derivative histogram" 

### ISSUE THREAD

**Issue by Janghyun-jo** [hyperspy/hyperspy#3004]
#### Describe the bug
"show derivative histogram" in the "spikes_removal_tool()" causes AttributeError for the EELSSpectrum and Signal1D objects created by "hs.signals.EELSSpectrum()" and "hs.signals.Signal1D()". But, it works well for the data loaded by "hs.load()".

#### To Reproduce
```
%matplotlib qt
import hyperspy.api as hs
```

This is the example in Signal1D Tools in the User guide. 
```
s = hs.signals.Signal1D(np.arange(5*10*20).reshape((5, 10, 20)))
s.isig[8:17].spikes_removal_tool()
```

This causes AttributeError below. When executed, "Spikes removal tool" window pops up well. But, when "Show derivative histogram" button is clicked, the error happens. This always happens for any objects created by "hs.signals.EELSSpectrum()" and "hs.signals.Signal1D()".
```
AttributeError                            Traceback (most recent call last)
File ~\anaconda3\envs\Hyperspy\lib\site-packages\hyperspy_gui_ipywidgets\tools.py:802, in spikes_removal_ipy.<locals>.on_show_diff_clicked(b)
    801 def on_show_diff_clicked(b):
--> 802     obj._show_derivative_histogram_fired()

File ~\anaconda3\envs\Hyperspy\lib\site-packages\hyperspy\signal_tools.py:1953, in SpikesRemovalInteractive._show_derivative_histogram_fired(self)
   1952 def _show_derivative_histogram_fired(self):
-> 1953     self.signal.spikes_diagnosis(signal_mask=self.signal_mask,
   1954                                  navigation_mask=self.navigation_mask,
   1955                                  max_num_bins=self.max_num_bins)

File ~\anaconda3\envs\Hyperspy\lib\site-packages\hyperspy\_signals\signal1d.py:327, in Signal1D.spikes_diagnosis(self, signal_mask, navigation_mask, **kwargs)
    321 plt.gca().set_title('')
    322 plt.gca().fill_between(tmph.axes_manager[0].axis,
    323                        tmph.data,
    324                        facecolor='#fddbc7',
    325                        interpolate=True,
    326                        color='none')
--> 327 ax = tmph._plot.signal_plot.ax
    328 axl = tmph._plot.signal_plot.ax_lines[0]
    329 axl.set_line_properties(color='#b2182b')

AttributeError: 'NoneType' object has no attribute 'signal_plot'
```

But, interestingly, this error does not happen for the real experimental data loaded by "hs.load()". "Show derivative histogram" works well.
```
s = hs.load('01_EELS_Ref_core loss_aligned.dm4')
s.spikes_removal_tool()
```

#### Expected behavior
It was expected that "Show derivative histogram" works well, and show me the histogram when clicking the button.

#### Python environement:
 - HyperSpy version: 1.7.1
 - Python version: 3.8.5

**Comment by ericpre** [comment]
The issue with the first example is that the derivative is constant and it is not handled well! I opened https://github.com/hyperspy/hyperspy/pull/3005 to improve it.
