### ISSUE TITLE
SAMFire: red_chisq and goodness_test bug

### ISSUE THREAD

**Issue by HanHsuanWu** [hyperspy/hyperspy#3021]
#### Describe the bug
SAMFire uses reduced chi-squared (red_chisq) to check whether a pixel is well fitted. For the pixels that passed such test, they become the seed points (starting pixels) when SAMFire starts fitting.
https://github.com/hyperspy/hyperspy/blob/c3bd14bc88e1b0a979721d714814557d5bd6d49a/hyperspy/samfire_utils/goodness_of_fit_tests/red_chisq.py#L24-L32
By default, the expected red_chisq = 1. However, I have noticed that the red_chisq of my data changes depending on whether I normalize them. They are about ~1e-9 (normalized) and ~4 (not normalized).
My guess is that there is some problem calculating the variance during fitting when the data contains numbers smaller than 1, which leads to small chi-squared.
In the normalized case, every fit is considered a good fit, since red_chisq is almost 0 for all fits.

#### To Reproduce
I will add this later.

#### Expected behavior
Reduced chi-squared should be able to scale when data is normalized.

#### Python environement:
HyperSpy version: 1.7.1

**Comment by francisco-dlp** [comment]
The `red_chisq` is computed using the variance information in `.metadata.Signal.Noise_properties.variance`. If your data's variance is Poissonian, you can use `.estimate_poissonian_noise_variance()` to set it automatically. Otherwise you can set it manually. In any case, the `variance` has to be correct for the `red_chisq` to be correctly computed.

**Comment by HanHsuanWu** [comment]
@francisco-dlp Thanks for clarifying!
https://github.com/hyperspy/hyperspy/blob/11122c86a28feb0d171a8722b5fc864366bcfdf9/hyperspy/model.py#L1201-L1227
Because I never did .estimate_poissonian_noise_variance(), the variance have been 1 by default, which most likely leads to incorrect red_chisq for my case.
It seems like chi_sq is automatically calculated after each fit. So after the variance value is set up correctly, I would need to re-fit the pixels which has already been fitted to update their chi_sq.

![image](https://user-images.githubusercontent.com/112028355/191081750-286fc466-bc9a-478c-9967-b2cab9873d9d.png)
I found this instruction by Thomas a while back. So essentially what he proposed here was to fix red_chisq and goodness_test.

Update:
https://github.com/hyperspy/hyperspy/blob/11122c86a28feb0d171a8722b5fc864366bcfdf9/hyperspy/signal.py#L5346-L5350
So whenever the data is normalized and contains data value of lower than 1, np.clip(variance, gain_offset * correlation_factor, np.inf) prevents variance to be lower than 1. 
Is this just to prevent variance = 0 or there are better reasons for gain_offset * correlation_factor to be the lower bound of variance?

**Comment by francisco-dlp** [comment]
The thing is that, while a correct model should have a red_chisq of ~1, sometimes it is not possible to incorporate in the model experimental artifacts such as readout noise, and we get higher red_chisq values. @to266 strategy should work in such a case.

Regarding the estimation of the variance, it is just a simple linear model in which we suppose the the noise is a combination of poisson noise (from the statistical distribution of the beam's emission) and gaussian noise from the detector + electronics. Therefore, the variance cannot be smaller than the gaussian noise variance.

Have you considered fitting your raw data (i.e. without normalizing it) and then normalize the results if needed?

**Comment by HanHsuanWu** [comment]
I see! That's why it wouldn't make sense to have a fraction of an electron as gaussian noise.

**Comment by HanHsuanWu** [comment]
I think the user guide for SAMFire right now is not very clear. Is it possible for me to contribute to that?

**Comment by francisco-dlp** [comment]
You are very welcome to contribute to the documentation. Don't hesitate to ask for help if needed.

**Comment by HanHsuanWu** [comment]
Do I just make a pull request at the hyperspy/website repository?

**Comment by ericpre** [comment]
This repository ([hyperspy/hyperspy](https://github.com/hyperspy/hyperspy)), because the user guide is in the doc folder of the source code.

There are information about contributing in the [developer guide](https://hyperspy.readthedocs.io/en/latest/dev_guide/intro.html). If there are things unclear in the developer guide, you are also more than welcome to improve it too! ;)
