### ISSUE TITLE
Velox EMD Complex dtype issue

### ISSUE THREAD

**Issue by bryandesser** [hyperspy/hyperspy#3029]
#### Bug Description
There remains a small bug in reading Velox EMD files with FFTs. In _read_image(): fft_dtype = [('realFloatHalfEven', '<f4'), ('imagFloatHalfEven', '<f4')]; however, this is not always the case. If, for example, an FFT is taken of a region with odd number of pixels, then Velox saves the data as fft_dtype = [('realFloatHalfOdd', '<f4'), ('imagFloatHalfOdd', '<f4')]

This issue causes hs.load() to fail in the presence of an FFT with odd number of pixels.

#### To Reproduce
In Velox, create an "FFT from selection" that has an odd number of pixels (i.e. 2047x2047)
Save .emd file
Attempt to load in hyperspy
```
import hyperspy.api as hs
hs.load('image_with_oddFFT.emd')
# ERROR:hyperspy.io:If this file format is supported, please report this error to the HyperSpy developers.
```

#### Expected behavior
Hyperspy should manage to import odd pixel width FFTs just as it can even pixel FFTs from Velox EMD files.

#### Python environement:
 - HyperSpy version: 1.7.1
 - Python version: 3.10.5

Pull request generated [https://github.com/hyperspy/hyperspy/pull/3028#issue-1380192233](https://github.com/hyperspy/hyperspy/pull/3028#issue-1380192233)

**Comment by ericpre** [comment]
The fix should also be included in https://github.com/hyperspy/rosettasciio - see https://github.com/hyperspy/hyperspy/issues/2996 for more details on progress.

It is not known at the moment if another patch release will be necessary before the 2.0 release - RosettaSciIO will be only be used from hyperspy 2.0.

**Comment by ericpre** [comment]
Done in https://github.com/hyperspy/rosettasciio/pull/49.
