### ISSUE TITLE
align_zero_loss_peak(mask=[array]), definition of array shape might be not consistent through out the implementation

### ISSUE THREAD

**Issue by mmw0909** [hyperspy/hyperspy#3053]
#### Describe the bug
When implementing align_zero_loss_peak with mask, the definition of x and y-axis of the navigation axes might not be consistent throughout the implementation. 
`bulk = hs.load('EELS')`
`mask = bulk.mean(axis=2).data>300`
`bulk.align_zero_loss_peak(mask=mask)`
This gives an error `ValueError: The shape of the navigation mask array must match `navigation_shape`.`

If I use `bulk.align_zero_loss_peak(mask=mask.swapaxes(0,1))`, this gives an error `ValueError: operands could not be broadcast together with shapes (166,95) () (95,166) `

#### Python environment:
 - HyperSpy version: 1.7.1
 - Python version: 3.9

**Comment by ericpre** [comment]
It is very likely that the shape of your mask doesn't match the navigation dimension. The following example works fine:

```python
import hyperspy.api as hs

# Generate some data
s = hs.datasets.artificial_data.get_low_loss_eels_line_scan_signal()
s2 = hs.stack([s, s*2])

# Generate a mask
s3 = s2.sum(axis=-1)
mask = (s3 < 1000)

s2.align_zero_loss_peak(mask=mask)
```

**Comment by ericpre** [comment]
Closing this issue for now. If you think that there is an issue, it would be useful to have a reproducible example to help understand what it could be.
