### ISSUE TITLE
Enforce positive residuals on model fitting

### ISSUE THREAD

**Issue by andrealorenzon** [hyperspy/hyperspy#3066]
I have created custom components for a model. When I fit them, I get this result. (red=signal, blue,orange= components, green=residuals)

![image](https://user-images.githubusercontent.com/43496697/203344904-ea1fddc1-d7dc-4861-9596-06a71f82dff7.png)

The fitting is good, but from a physical point of view I cannot consider negative residuals, and I'd like to have a (worse) fit, enforcing that residuals must always be positive.

Which road should I take here?

**Comment by francisco-dlp** [comment]
I am afraid that it is possible to impose constraints on the parameters but not on the residuals. For that you'll need to create your own optimizer. Currently hyperspy uses scipy optimizers, but we could let it accept any optimizer with a `scipy.optimize.minimize` API.

**Comment by andrealorenzon** [comment]
Thank you.
