### ISSUE TITLE
saving image resolution down (dm4 or emd to jpg)

### ISSUE THREAD

**Issue by jykim1299** [hyperspy/hyperspy#3083]
#### Describe the bug
When saving an dm4 file as a jpg file through python, the resolution goes down.

#### To Reproduce
```
%matplotlib nbagg
import hyperspy.api as hs
s = hs.load("1.dm4")
s.save('1.jpg', overwrite=True)
```
![제목 없음](https://user-images.githubusercontent.com/44154065/212703073-611bd92d-d352-4d87-be84-c9dd84e7ef72.png)

#### Expected behavior
Save with the same resolution as the image saved using gms.

#### Python environement:
 - HyperSpy version: 1.6.1
 - Python version: 3.6.12

#### Additional context
Add any other context about the problem here. If necessary, add screenshots to help explain your problem.

**Comment by CSSFrancis** [comment]
There are a couple of different things you can consider doing.  If you read through the documentation you _can_ increase the resolution by interpolating using the `outputsize` keyword https://hyperspy.org/hyperspy-doc/current/user_guide/io.html#id5. I'm not sure that this is actually the problem, rather it looks like the contrast is stretched more in the GMS program.  Jpegs are a form of lossy compression and so often times they can do weird things depending on the level of compression.  You can adjust this using the `quality` [keyword](https://imread.readthedocs.io/en/latest/formats.html?highlight=jpeg#jpeg) but just note that doing any sort of analysis jpeg should be avoided and jpegs should be only used in the rare case of presenting images where you care about minimizing the size of an image. 

If you want more consistent images a [tiff](https://hyperspy.org/hyperspy-doc/current/user_guide/io.html#tiff) might be a better way to save data.

**Comment by ericpre** [comment]
The number of the pixel shouldn't change, except if you use the `output_size` keyword as mentioned above by @CSSFrancis.

By default, GMS adjust the contrast to display only the value above and below some percentiles values of the intensities range. This is illustrated with the following example:

```python
import hyperspy.api as hs

s = hs.datasets.example_signals.object_hologram()

# Display all intensities
s.plot(vmin=None, vmax=None)

# Display only intensities above 1 percentile and below 99 percentile.
s.plot(vmin='1th', vmax='99th')
```

This is one of these, that it would be good to have in the gallery of example.

You will need to normalise the images before saving the data to get a similar results.

**Comment by jykim1299** [comment]
Thanks for @CSSFrancis @ericpre reply.
I'll try saving with that code. :) 👍
