### ISSUE TITLE
Plot the parameter of Gaussian

### ISSUE THREAD

**Issue by Psiche91** [hyperspy/hyperspy#3105]
Hello everyone,
I have make a fitting with nine Gaussian on my sample.
Is possible plot the parameters of all Gaussian (center, FWHM and height), on the same scatter plot ? 

I try many times with many method, one of these is: 
`C1 = G1.centre.as_signal()`
`C2 = G2.centre.as_signal()`
`...`
and using these two command 
`hs.plot.plot_spectra` and `hs.plot.plot_images`. 
But I have lot "attributError".

Probably I make a stupid error or I don't know the right method.
But I lost many hours for make this plotting.

Thanks for your Patience
Ad Maiora

**Comment by ericpre** [comment]
The `as_signal` returns a hyperspy signal, you can simply use `C1.plot()`.
It may better that you use the [gitter chat ](https://gitter.im/hyperspy/hyperspy) for this type of question than the github issue tracker, which is for bug report rather usage question or look at the tutorials available online (https://github.com/hyperspy/hyperspy-demos or other).
