### ISSUE TITLE
Clustering Crash 

### ISSUE THREAD

**Issue by Psiche91** [hyperspy/hyperspy#3131]
Hello Everyone,
I work on 4DSTEM data and I make the clustering of my data.
But when I operate the clustering the "kernel dies".
I don't know why.

I tried changing the parameters, for example, n_init and/or n_cluster. 
I tried to use the lazy signal 
I tried to reduce the dimension of the data.
But don't work.

`s = hs.load('./Data/Diffraction [...].hspy')`
`s.set_signal_type('electron_diffraction')`

`s.cluster_analysis(cluster_source="signal", n_clusters=10, preprocessing="norm", algorithm="kmeans", n_init='auto')`

Thanks a lot for the help.
Psiche91

**Comment by CSSFrancis** [comment]
@Psiche91 Can I ask what you are trying to do. K means clustering works much better on vectorized data. 

K means is also a super RAM intensive equation. I think that it calculates a full distance matrix so the amount of RAM needed is very very large. (Like many TBs) There are ways to make it use slightly less RAM such as KDTrees but you would be much better doing something like first finding peaks and secondly using KMeans on the peak positions.

**Comment by CSSFrancis** [comment]
@Psiche91 A good place to start is something like this. https://pyxem.readthedocs.io/en/latest/demos/06%20Nanocrystal%20segmentation%20in%20SPED%20data%20-%20Demonstration%20on%20partly%20overlapping%20MgO%20cubes.html

If you are are tying to do something like segmentation.  Generally you will get a bit farther using something like Non Negative matrix factorization.

**Edit: if you want to do these lazily look at 
http://hyperspy.org/hyperspy-doc/current/user_guide/big_data.html#machine-learning

There is some further optimization there that might be possible but I haven't looked into it too much

**Comment by Psiche91** [comment]
Hello @CSSFrancis ,
Thanks for your response, but the code is perfect.
The problem is my work station, I asked the help of my technician.

 Thaks a lot
 A. Griesi

**Comment by CSSFrancis** [comment]
@Psiche91 Glad that you figured out the problem.  You might want to look at the mini batch kmeans algorithm as well which should have less RAM requirements.
