### ISSUE TITLE
improvements to tiff parser

### ISSUE THREAD

**Issue by sem-geologist** [hyperspy/hyperspy#3133]
#### Describe the functionality you would like to see
Get the ability to load original metadata from every multipage tiff page.

#### Describe the context
Do you want to extend existing functionalities, what types of signals should it apply to, etc.

I want to modify tiff reader to accept keyword to read tiff pages as separate signals. Currently it uses tifffile built-in `series` mechanism, which allows for memory mapping, but series ignores any metadata except from first page. Thus I want to add alternative method which would return list of signals instead of stacked single signal.

#### Additional information
I have datasest from few years ago, where FIB-SEM milling tomography had to be subdivided into sessions. Unfortunately, few sessions overwrote few previous runs, and data from those are available only in multipage tiff files generated at end of every session. ZEISS software interface (installed in 2014) is quite susceptible to these kind of overwriting mistakes. Original metadata has some quite important data which is dynamically changing during the milling, and its inspection is important to filter out some analytical anomalies. My aim is to concatenate data from all sessions and want original metadata stacked accordingly so that could select and consolidate those into arrayed metadata.

This again brings me to limitations of Hyperspy metadata oversimplification. There are many experimental techniques where some of parameters are changed (scanned) while acquiring series of measurements. It can be such fundamental parameters like acceleration voltage, working distance, beam current and many more. Having an access to original_metadata is practical in many cases.

Which branch I should aim for PR?
After successful merge I will forward the changes to rsciio.

**Comment by ericpre** [comment]
The release should be 2.0 or a patch release. If these changes are no small, I would suggest to do them directly to rsciio.

**Comment by sem-geologist** [comment]
Thanks @ericpre . BTW, looking through code I have such an urge to cleanup that tiff code, there are many workarounds to handle older tifffile lib. code in many places could be simplified. I will address this in `rsciio` then.
