### ISSUE TITLE
Flush metadata to Signal

### ISSUE THREAD

**Issue by CSSFrancis** [hyperspy/hyperspy#3136]
#### Describe the functionality you would like to see.
There are a couple of times when it is useful to just save the metadata to some .zspy or .hspy file rather than rewriting the entire dataset.  

#### Describe the context
Mostly this occurs when I have a large dataset and I don't want to rewrite the data to disk but I want to save a navigator alongside the data.  There are other things like learning results, setting axes labels/ calibrating scales or filling in metadata where you have to load the entire dataset into ram/ and resave the data only to change some small data.

#### Additional information

This should be possible but might require some interoperability with rosettasciio as well.

**Comment by ericpre** [comment]
This should be possible already for these format - see the `write_dataset` argument in https://hyperspy.org/hyperspy-doc/current/user_guide/io.html#extra-saving-arguments

**Comment by CSSFrancis** [comment]
@ericpre Once again I should probably spend some more time reading the documentation.... It even is in the doc string so there isn't even that excuse :) 

Probably something that I should add to the pyxem example workflows.
