### ISSUE TITLE
How to run multifit() in parallel?

### ISSUE THREAD

**Issue by PZH525** [hyperspy/hyperspy#3157]
My current code is this, but it runs very slowly, how to make this run in parallel so that it can run faster on the CPU cluster?

m.multifit(optimizer="lm", bounded=True, iterpath='serpentine')

**Comment by ericpre** [comment]
You can try to use [SAMFire](https://hyperspy.org/hyperspy-doc/current/user_guide/model.html#smart-adaptive-multi-dimensional-fitting-samfire) but it is not very well documented
