### ISSUE TITLE
Branch in navigator selection routine is always overwritten

### ISSUE THREAD

**Issue by pietsjoh** [hyperspy/hyperspy#3193]
#### Describe the bug
The following code snippet shows 2 if-statements in the selection routine of the navigator. If I am not mistaken the first if/else (signal_dimension==0) will always be overwritten by the second if/else (navigation_dimension==1). Should I open a PR and remove that?

https://github.com/hyperspy/hyperspy/blob/8ef1a73ff21bbe440e89db76bb84cece372788a8/hyperspy/signal.py#L2862C1-L2885C26

**Comment by ericpre** [comment]
Here are some cases, where it is necessary:
```python
import hyperspy.api as hs
import numpy as np

rng = np.random.default_rng()
data = rng.integers(10, size=100**3).reshape([100]*3)
s = hs.signals.BaseSignal(data).T

s.plot()

data = rng.integers(10, size=100**4).reshape([100]*4)
s2 = hs.signals.Signal1D(data)

s2.plot()
```

This the type of situation where comments would be useful to explain the intended behaviour! Moreover, the example above doesn't seem to be covered by tests!
The logic seems to come from https://github.com/hyperspy/hyperspy/commit/43fc3111af1ec17423006bec9f1a8be662943cde and as I understand, this is necessary to be able to plot navigator with dimension >2.

**Comment by pietsjoh** [comment]
Thanks for the clarification. I see now why it is the way it is. The first if/else sets navigator, which is needed in the second if/else. Closing this then.
