### ISSUE TITLE
Can roi be used interactively on the energy axis for EELS data?

### ISSUE THREAD

**Issue by HanHsuanWu** [hyperspy/hyperspy#3209]
#### Describe the functionality you would like to see.
I think currently the roi and interactive method only work on the navigation axis? It would be nice to do slicing on the energy axis interactively .

#### Describe the context
This would be helpful for both EELS and EDS data.

**Comment by HanHsuanWu** [comment]
The SpanROI works as long as the energy axis is in the navigation axis.

**Comment by ericpre** [comment]
Now that we have the documentation in better shape and a gallery of example, we need more examples to illustrate how to do this type of tasks. I added some in #3221. @HanHsuanWu, are these example useful for what you are trying to do?

**Comment by HanHsuanWu** [comment]
Hi Eric,

Yes with the SpanROI. It works by having the energy axis in the navigation axis. Thanks!

**Comment by ericpre** [comment]
I don't know what you are trying to do but transposing the signal is not required to get it to work, as shown in the examples of #3221, see https://hyperspy--3221.org.readthedocs.build/en/3221/auto_examples/index.html#region-of-interest

**Comment by HanHsuanWu** [comment]
Ah I see. I did not specify the axe in the roi.interactive. Thanks Eric.Sent from my iPhoneOn Sep 1, 2023, at 11:11 AM, Eric Prestat ***@***.***> wrote:﻿
I don't know what you are trying to do but transposing the signal is not required to get it to work, as shown in the examples of #3221, see https://hyperspy--3221.org.readthedocs.build/en/3221/auto_examples/index.html#region-of-interest
