### ISSUE TITLE
align_zero_loss_peak(subpixel=True)

### ISSUE THREAD

**Issue by HanHsuanWu** [hyperspy/hyperspy#3230]
align_zero_loss_peak(subpixel=True) takes considerable amount of time when the navigation axis is large for me.
Is it possible using multiple cores like map() for align1D()?
Any pointer on how to implement that will be appreciated.

https://github.com/hyperspy/hyperspy/blob/70ca0762a332a7239a4c1eb75001062ab6c7495d/hyperspy/_signals/eels.py#L436-L461

**Comment by ericpre** [comment]
Can you try to use some profiling tool to identify what takes time? See for example: https://github.com/hyperspy/hyperspy/pull/3101

**Comment by HanHsuanWu** [comment]
Hi Eric this is the code I run.
`with cProfile.Profile() as pr:
    s = hs.load(path+"\\"+filename)
    s.set_signal_type("EELS")
    s.align_zero_loss_peak(signal_range=(-10., 10.), subpixel=True)`

![image](https://github.com/hyperspy/hyperspy/assets/112028355/f150d7b1-446c-4c4e-ae90-f6503366ceee)

**Comment by HanHsuanWu** [comment]
Here is another set of data
![image](https://github.com/hyperspy/hyperspy/assets/112028355/cf09ab17-aff3-408c-9ea9-38cde50618f9)

**Comment by ericpre** [comment]
As this should already be using multiprocessing through dask, and in this case, this profiling doesn't help! 😅 You will need to use diagnostics tools from dask instead: https://docs.dask.org/en/stable/debugging-performance.html

The dask dashboard or the task graph should point out at where it is slow and if the multi-processing works well or not.

**Comment by CSSFrancis** [comment]
@HanHsuanWu So most likely you are experiencing some effect of 2 things:

1. `subpixel=True` means there is some interpolation which is happening which is fairly slow.
2. You aren't actually running things in parallel.  See #3152 for more details on how to get around this.   (specifically [this](https://github.com/hyperspy/hyperspy/issues/3152#issuecomment-1545523420) comment) With the new 2.0.0 version of hyperspy there are more options around this but currently you can just cast the signal to a lazy signal and then run the function.

**Comment by HanHsuanWu** [comment]
Hi guys,

Thank you for the insights! @CSSFrancis I am on '2.0.dev0' version of hyperspy. Ran the test again after updating to the newest version, but it takes the same time. What are the options you mentioned?

@ericpre I can't really figure out to implement the diagnostics tools on hyperspy function lol perhaps if there is any example on this?

**Comment by CSSFrancis** [comment]
@HanHsuanWu cool then you should be able to set the `navigation_chunks` parameter.  What you want is to chunk the data in the navigation dimension so the number of chunks is at least 2x the number of cores.

```python
s = hs.signals.Signal2D(np.ones((10,10,10,10)))

s.map(func, navigation_chunks=(2,2)) # split into 25 different chunks of 2x2
```

The easiest way to run some diagnostics is with the `dask-distributed` backend.   Just run:

```python
from dask.distributed import Client
from dask.distributed import LocalCluster
import dask.array as da
import hyperspy.api as hs

cluster = LocalCluster()
client = Client(cluster)
display(client) # in Jupyter to see the link to the dashboard
# Any calculation will now use the distributed scheduler
```
and then operate normally as all of the computations in hyperspy will now run through the distributed scheduler.  You can see if you are using all of the cores available and if they are running at 100% etc.  

https://docs.dask.org/en/latest/dashboard.html is a good place to start walking your through how the dashboard works. 

If you want to optimize performance that is the first place I would look

**Comment by HanHsuanWu** [comment]
Hi @CSSFrancis Thanks for the suggestion!

So I ran the code with the dask-distributed backend like so and a long list of error messages appeared.

![image](https://github.com/hyperspy/hyperspy/assets/112028355/87070e83-bbf8-4948-8581-2e88dff26355)
![image](https://github.com/hyperspy/hyperspy/assets/112028355/ae20a0d1-c96a-45a6-ac8a-6fc84a5b1a9a)

Without the dask-distributed backend, the code runs without error tho so I am not sure if it is just a problem with the backend. 

TypeError: ('Could not serialize object of type HighLevelGraph', '<ToPickle: HighLevelGraph with 1 layers.\n<dask.highlevelgraph.HighLevelGraph object at 0x29134711190>\n 0. 2822674259520\n>')

![image](https://github.com/hyperspy/hyperspy/assets/112028355/1240d32b-eca7-45a3-b801-71a232083358)

![image](https://github.com/hyperspy/hyperspy/assets/112028355/76aeab76-d19e-438b-9a11-f5d9c9b2815a)

**Comment by CSSFrancis** [comment]
@HanHsuanWu I realize that I might have given you a little bit of bad advice.  I think the problem might be something to do with the  dask-distributed only working with `.zspy` file format. 

Maybe try loading the data regularly then saving in the `.zspy` format and then trying things again. 

If you have a small test dataset you are willing to share I can try as well!

**Comment by HanHsuanWu** [comment]
@CSSFrancis I see lol. I appreciate your help nonetheless. I have a test dataset of 30x195x2048.
[test Spectrum Image.zip](https://github.com/hyperspy/hyperspy/files/12742236/test.Spectrum.Image.zip)

**Comment by HanHsuanWu** [comment]
[test Spectrum Image.zip](https://github.com/hyperspy/hyperspy/files/12742235/test.Spectrum.Image.zip)
