### ISSUE TITLE
Incompatibilities Between Files from 2.0.0 to 1.7.x

### ISSUE THREAD

**Issue by CSSFrancis** [hyperspy/hyperspy#3239]
#### Describe the bug
I was just going to track some of the backward incompatibilities.  Some of these we should just ignore but some are quite frustrating and it would be good to release a patch.

- [ ] Saving a signal with some unset axis name or units causes a traits error. 
- [ ] Saving new markers to some signal will causes issues when loading in a previous version
- [ ] Loading ragged arrays isn't completely supported

#### Expected behavior
It would be nice to have some ability to load future versions of hyperspy files into older versions of the software.  The easiest way would be to have a error which points users to `rosettasciio` as a fix for loading newer versions of hyperspy files into older software. 

The other option would be to hard code it directly into the 1.7.x version of hyperspy so that it can handle (most) cases to some degree. 

#### Additional context
I'm not a huge fan of over engineering the solution here as I feel like pushing people towards 2.0.0 is a good thing. The minimum should be:

- Have a common sense error "Try updating hyperspy to load this file type or use rosettasciio etc."
- Have documentation on how to load a file from 2.0.0 into 1.7.x.

**Comment by ericpre** [comment]
To warn about loading future version, there is already: https://github.com/hyperspy/hyperspy/blob/411ae3d2731a78c17dde3b69ad5b98a0d1c3f7c0/hyperspy/io_plugins/_hierarchical.py#L105-L110
Maybe the message can be improved to be more clear?

**Comment by CSSFrancis** [comment]
> To warn about loading future version, there is already:
> 
> https://github.com/hyperspy/hyperspy/blob/411ae3d2731a78c17dde3b69ad5b98a0d1c3f7c0/hyperspy/io_plugins/_hierarchical.py#L105-L110
> 
> Maybe the message can be improved to be more clear?

I think that is good in most cases. I was more saying that we should try to test so that most basic signals load to some extent. It might be good to also point towards rosettasciio.

That being said currently loading a signal with the `axes.name` not set causes problems loading from the future.  I think that is really the only thing that we should try to fix.  It's a small thing but for me it's been frustrating over the last couple of months when jumping between versions.

**Comment by ericpre** [comment]
> That being said currently loading a signal with the `axes.name` not set causes problems loading from the future. I think that is really the only thing that we should try to fix. It's a small thing but for me it's been frustrating over the last couple of months when jumping between versions.

Indeed, as this is an easy fix that enable loading old files it is a good justification. For the two others, I am a bit septical that this is worth the efforts:
- markers: some markers can be converted but not all and I suspect that it will be painful to convert the one that are possible. Maybe it would worth enabling loading the file without the markers and raise a warning accordingly?
- ragged arrays: would it be a matter of backporting https://github.com/hyperspy/rosettasciio/pull/164 and https://github.com/hyperspy/rosettasciio/pull/169 to the patch branch? If you think that this is worth it, then please make a pull request! :)

**Comment by ericpre** [comment]
@CSSFrancis, @francisco-dlp, in addition to https://github.com/hyperspy/hyperspy/pull/3241, is there anything you would like to be done for the 1.7.6 release?

**Comment by CSSFrancis** [comment]
@ericpre This seems good!  I think we can go ahead with the 1.7.6 release.
