### ISSUE TITLE
Is hs._signals.signal1d.align1D() doing interpolation or cross-correlation?

### ISSUE THREAD

**Issue by HanHsuanWu** [hyperspy/hyperspy#3247]
I am just a bit confused in the introduction of the function it says: 
`Estimate the shifts in the signal axis using
        cross-correlation and use the estimation to align the data in place.
        This method can only estimate the shift by comparing`
But in the actual code it seems to be using interpolation instead. 
https://github.com/hyperspy/hyperspy/blob/70ca0762a332a7239a4c1eb75001062ab6c7495d/hyperspy/_signals/signal1d.py#L696-L802

https://github.com/hyperspy/hyperspy/blob/70ca0762a332a7239a4c1eb75001062ab6c7495d/hyperspy/_signals/signal1d.py#L583-L694
Can anyone educate me on this?

**Comment by CSSFrancis** [comment]
@HanHsuanWu the method uses the cross correlation to first determine the shift to align the spectrum and then shifts the data.  

You can set interpolate=False which will just shift the data or interpolate=True which uses a subpixel alignment.
