### ISSUE TITLE
Importing error in RELEASE_next_major

### ISSUE THREAD

**Issue by HanHsuanWu** [hyperspy/hyperspy#3248]
I am using the RELEASE_next_major. When I try to import hyperspy an error message comes up.

![image](https://github.com/hyperspy/hyperspy/assets/112028355/793c459a-1d8d-4700-ae0d-d58d81ffb861)

**Comment by ericpre** [comment]
After https://github.com/hyperspy/hyperspy/pull/3202 has been merged, https://github.com/hyperspy/hyperspy_gui_ipywidgets/pull/48 and https://github.com/hyperspy/hyperspy_gui_traitsui/pull/66 are required to use the `RELEASE_next_major` branch.

If you prefer not to install these branch, you can use the commit before #3202 was merged:
```
pip install https://github.com/hyperspy/hyperspy/archive/a3a038194d9168b2535c9f1b4003a6b953b93c5a.zip
```
I haven't checked that this is the correct link/syntax but this is what I would try and I expect that it would work!

**Comment by ericpre** [comment]
To get setup with `exspy` until it is released you can use:
```
pip install https://github.com/hyperspy/exspy/archive/main.zip#egg=exspy[all]
```
which will install the current development version of `exspy` and the corresponding branches of the gui libraries.

**Comment by HanHsuanWu** [comment]
In my, hyperspy.extensions.ALL_EXTENSIONS

Both hyperspy and exspy are here and caused the error message. I think the older hyperspy part was not removed in the extension tree. Would it be easier if I just wait till the next couple updates?
'hyperspy.microscope_parameters_EELS',
   'hyperspy.microscope_parameters_EDS_TEM',
   'hyperspy.microscope_parameters_EDS_SEM',
   'exspy.Preferences',
   'exspy.EELSCLEdge_Component',
   'exspy.microscope_parameters_EELS',
   'exspy.microscope_parameters_EDS_TEM',
   'exspy.microscope_parameters_EDS_SEM',

![image](https://github.com/hyperspy/hyperspy/assets/112028355/9d5347af-2e6e-49a9-b769-39b4a4d97330)

**Comment by ericpre** [comment]
Could it be that you are using an out of date branch?
These toolkeys have been removed:
https://github.com/hyperspy/hyperspy/blob/ab8617f043a9abf1ea752250bda8dfa0565bfcbd/hyperspy/hyperspy_extension.yaml#L164C2-L171

Installing release version are always easier, so waiting for the release is a sensible option.

**Comment by HanHsuanWu** [comment]
> To get setup with `exspy` until it is released you can use:
> 
> ```
> pip install https://github.com/hyperspy/exspy/archive/main.zip#egg=exspy[all]
> ```
> 
> which will install the current development version of `exspy` and the corresponding branches of the gui libraries.

Tried it again with a new environment, now it works! Thanks Eric
