### ISSUE TITLE
Convolution of a model component with another model component.

### ISSUE THREAD

**Issue by HanHsuanWu** [hyperspy/hyperspy#3257]
Hi guys,
I would like to create a fitting model that consists of [function1, Lorentzian1 convolved with function1, Lorentzian2 convolved with function1....custom number of lorentzians convolved with function1]

I tried using the custom fit model template but changing the number of lorentzians is pretty troublesome this way. I think instead having function 1 and the convolved lorentzians as seperate model components should be a better way, but how would I feed the information needed for convolution from function1 to the lorentzian components? 

`

class test_convolve(Component):
    
    def __init__(self, A=1.0, w=1, a1=1., p1=0., gamma1=1.):

        # Define the parameters
        Component.__init__(self, ("A","w","a1","p1","gamma1"))
        # function1
        self.A.value = A
        self.w.value = w

        # lorentzian variables
        self.a1.value = a1
        self.p1.value = p1
        self.gamma1.value = gamma1

    def function(self,x):
        #funtion1
        A = self.A.value
        w = self.w.value
        m = self.m.value

        #lorentzian variables
        a1 = self.a1.value
        p1 = self.p1.value
        gamma1 = self.gamma1.value
        
        return (function1(x, A, w) + a1*convolve1d(lorenztian(x, p1, gamma1),function1(x, A, w)))
    `

**Comment by ericpre** [comment]
Can you provide more  information on function1?
- Is function1 the same for all navigation positions?
- Has function1 some fitted parameters?

What is the motivation for using convolution? Are you trying to convolved with a low loss spectrum? Or is it the system response that you are trying to include in your model? 
Convolution was removed from hyperspy to `exspy` as part of the split - see discussion in https://github.com/hyperspy/hyperspy/pull/3202 for more details.

**Comment by HanHsuanWu** [comment]
Thank you for the reply Eric!
Function 1 would be any function that could be used to fit the zero-loss peak at 0 eV, for low-loss spectra. So function1 will have some fitted parameters. In my case, they will change with navigation positions. If I understand you correctly I want to include the system response in my model.

**Comment by ericpre** [comment]
Have you tried to use the `ll` argument of the EELS model: https://hyperspy.org/exspy/reference/models.html#exspy.models.EELSModel? This is intended to model plural scattering due to plasmon by doing a convolution of low loss spectrum with component. It sounds like you are interested in doing a convolution of the the zelo loss peak with the low loss and it may work also work in this case?

**Comment by francisco-dlp** [comment]
@HanHsuanWu, I think that the simplest way to implement that functionality is to add multiple components like the one in your example to  the model. If I understand you well, `function1` should be the same (have the same parameter values) for all those components. To achieve this, you could use the "twin" functionality. For example, supposing the `c1`, `c2`, and `c3` are all instances of your custom component, you could setup the model as follows:

```python
m.extend((c1, c2, c3))
m.c2.A.twin = m.c1.A
m.c2.w.twin = m.c1.w
m.c3.A.twin = m.c1.A
m.c3.w.twin = m.c1.w
```

**Comment by HanHsuanWu** [comment]
@ericpre @francisco-dlp than you both so much! I think the twin function is what I need. I totally forgot about it. Although this way changing function1 would require writing a new component class, I think it's enough. Thanks again!
