### ISSUE TITLE
Serialisation of custom component fails

### ISSUE THREAD

**Issue by ericpre** [hyperspy/hyperspy#3261]
I have tried to use the following code to generate a file with a saved custom component to dumps the class and I can't even saved the file:

```python
import hyperspy.api as hs
from hyperspy.component import Component

class CustomComponent(Component):

    def __init__(self, p1=1, p2=2):
        Component.__init__(self, ('p1', 'p2'))

        self.p1.value = p1
        self.p2.value = p2

        self.p1.grad = self.grad_p1
        self.p2.grad = self.grad_p2

    def function(self, x):
        p1 = self.p1.value
        p2 = self.p2.value
        return p1 + x * p2

    def grad_p1(self, x):
        return 0

    def grad_p2(self, x):
        return x


s = hs.signals.Signal1D(range(10))
m = s.create_model()

c = CustomComponent()
m.append(c)
m.store('a')

import hyperspy
version = hyperspy.__version__
s.save(f"hs{version}_custom_component.hspy")
```

It seems that saving custom component is broken., but surprisingly, the code is covered [according to codecov](https://app.codecov.io/gh/hyperspy/hyperspy/blob/RELEASE_next_major/hyperspy%2Fcomponent.py#L1215)...

_Originally posted by @ericpre in https://github.com/hyperspy/hyperspy/issues/3255#issuecomment-1800106824_

**Comment by CSSFrancis** [comment]
@ericpre are you getting an error read out?  It just keeps on crashing the kernel that I am using when I test this in Jupyter.

**Comment by ericpre** [comment]
There is error message as it kills the python process... Running from script is the same...

**Comment by CSSFrancis** [comment]
Just adding some more information here... The problem is related to cloud pickle not serializing the __class__ for a custom component. 

https://github.com/hyperspy/hyperspy/blob/4cafc47daf68f0e01b9d64822736fe875c63f690/hyperspy/component.py#L1214-L1217

```python 
import cloudpickle
cloudpickle.dumps(CustomComponent)
```
 has the same result


Edit:

And interestingly:

```python
class ComponentSub(Component):
    pass

cloudpickle.dumps(ComponentSub)
```
Fails as well  even though 

```python
cloudpickle.dumps(Component)
```

works

**Comment by CSSFrancis** [comment]
As @francisco-dlp suggested it seems to be a traits error specifically something to do with ??`t.Property`?? attributes. 

Just playing around with some stuff to see what does and doesn't work...


```python

import traits.api as t
import cloudpickle
class TraitsObj(t.HasTraits):
    name = t.Property(t.Str(''))
    def __init__(self, name=""):
        self._name = name
    def _get_name(self):
        return self._name
    def _set_name(self, value):
         self._name = value

cloudpickle.dumps(TraitsObj)
```
Appears to fail but this is a little weird because the `Component` class doesn't fail...

**Comment by CSSFrancis** [comment]
Just a note that my linter also picked this up a the wrong type for the `t.Property()` function based on the documentation for the traits package.  :)

**Comment by CSSFrancis** [comment]
Sorry for all of the comments :) I was just trying to logically track down the reason for the bug. @ericpre The fix I just pushed should work!

**Comment by ericpre** [comment]
Fixed in https://github.com/hyperspy/hyperspy/pull/3262.
