### ISSUE TITLE
Marker Clean up

### ISSUE THREAD

**Issue by CSSFrancis** [hyperspy/hyperspy#3269]
#### Describe the bug
Before the 2.0.0 release there are some little bugs related to the Markers.

- Markers str representation fails if the marker isn't added to a signal
- The `from_signal` class doesn't work for anything other than `Points` 

#### To Reproduce
```
print(hs.plot.markers(points(np.random.random((10,2)))
```

#### Expected behavior
We should have the string representation work without a signal and you should be able to do things like:
```
hs.plot.markers.Lines.from_signal(s)
```

I'll submit a PR and maybe add an example...

**Comment by ericpre** [comment]
Done in https://github.com/hyperspy/hyperspy/pull/3270.
