### ISSUE TITLE
Hyperspy 2.1.0 Release Tracker

### ISSUE THREAD

**Issue by CSSFrancis** [hyperspy/hyperspy#3272]
This is probably getting ahead of ourselves (as the 2.0.0 release hasn't been released, but there are quite a few new features which would be nice to include in hyperspy which didn't quite make it into the 2.0.0 release and it would be good to track these.

Refactor the Axes Class:
------------------------
- [ ] #3031 
- [ ] #3055 
- [ ] #2756

Better Deal with Vectors:
-------------------------
- [ ] #2876 
- [ ] #3196 

Plotting Improvements:
-----------------------
- [ ] #3030 
- [ ] #3271 
- [x] #3199 
- [ ] #3309
- [ ]  #3343 

Other Things Worth Doing:
---------------------------
- #3302 

I might wait on the pyxem 1.0.0 release until some of these are implemented as some of the vector based operations might be very helpful.

**Comment by CSSFrancis** [comment]
@ericpre What are your thoughts on a 2.1.0 release by the end of the month before the Diamond Training session?  I think some of the plotting tools would be interesting to showcase.

**Comment by ericpre** [comment]
There isn't much in the 2.1 milestone at the moment but if we can do the the work on the axis/vector handling that would be good. How would it align with the pyxem release?

**Comment by CSSFrancis** [comment]
@ericpre I think I missed this comment :)

> There isn't much in the 2.1 milestone at the moment but if we can do the the work on the axis/vector handling that would be good. How would it align with the pyxem release?

I'd like a pyxem 1.0.0 release before the end of the month but we've been a little suck with getting `orix` and `diffsims` where we want them to be. I can help out a bit with the `axis` and vector handling if we want to get that done but also feel like those are not completely necessary.  Smaller more often releases would be nice, especially if we have some fun new plotting capabilities.

**Comment by ericpre** [comment]
I can't agree more with smaller and more often releases! 😃
I have the updated the [v2.1 milestone](https://github.com/hyperspy/hyperspy/milestone/53) according to your latest comment (leaving out vector handling) and to what I think would be realistic and priority. Are they any others that you think should be done for 2.1?

**Comment by CSSFrancis** [comment]
@ericpre I can spend the next couple of days working on this.  Do you think it is worth trying to get this done before the Diamond workshop in 2 weeks?

**Comment by ericpre** [comment]
Yes, that would be good.
For #3343, I have updated the progress list in https://github.com/hyperspy/hyperspy/pull/3343#issue-2209507841.
We should sort out #3358 with #3360 or #3364.

**Comment by ericpre** [comment]
If we want to have a release in the coming days, I suspect that we will not be able to merge much more than these PRs:
- #3364
- #3368 (need for a https://github.com/hyperspy/hyperspy_gui_traitsui/pull/76)
- #3366 (trivial and avoid importing gui packages when not necessary)

What do you think?

**Comment by CSSFrancis** [comment]
@ericpre yea as much as #3343 might be nice. I don't know if it is super necessary.  It might be more useful to spend our time doing other things :)

**Comment by ericpre** [comment]
Release 2.1 done in #3370.
