### ISSUE TITLE
Protect RELEASE_next_major

### ISSUE THREAD

**Issue by CSSFrancis** [hyperspy/hyperspy#3289]
Hi all, 

I was not the smartest this morning and when I went to close #3285 I just deleted the RELEASE_next_major branch based on muscle memory. 🤦  I restored it but it did cause lots of PR's to be auto closed...  Suffice to say I woke up very quickly after that.

We should be able to protect this branch from deletion (at the minimum) which seems like a good idea. 

Thanks to for catching all of the PR's that got closed @ericpre.  At least we know which PR's need to be rebased onto RELEASE_next_minor.

**Comment by ericpre** [comment]
> Thanks to for catching all of the PR's that got closed @ericpre. At least we know which PR's need to be rebased onto RELEASE_next_minor.

Indeed, I thought about this as a sliver lining! 😄

**Comment by CSSFrancis** [comment]
> Indeed, I thought about this as a sliver lining! 😄

I wouldn't recommend adding it to the workflow for making a major release  :)

**Comment by ericpre** [comment]
I have setup a rule that should protect all branch starting with `RELEASE`

**Comment by ericpre** [comment]
I meant to add that if there is a number of options, if something is inconvenient to use, maybe this can be tweaked.
