### ISSUE TITLE
Redo Hyperspy website

### ISSUE THREAD

**Issue by CSSFrancis** [hyperspy/hyperspy#3290]
#### Describe the functionality you would like to see.
As @jlaehne  and @ericpre pointed out the hyperspy website needs a little bit of updating. https://hyperspy.org

I might try to see what I can do to modernize it today if no one else wants to/ has already started that. 

- I would also like to add a section about upcoming workshops etc where people can advertise different events etc and am open to other suggestions. 
- A section about different sub packages (and links) would also be nice

**Comment by ericpre** [comment]
That would be great!

A few comments:
- if I remember correctly, the reason sphinx is pinned at <6 is because of an issue with the gitter banner... maybe this can be replaced by something else?
- I am happy to help with automating the build and push when the source is being updated
- it would be useful to setup readthedocs preview on PR
- indeed, a section on workshop would be great but it should be simple and easy to update (and documented!) :) I think it long time, there was one, but it wasn't maintained, most likely because it is a bit tedious to update, but nowadays there are tooling which can make it very easy.

Are you thinking of changing the theme too?

**Comment by CSSFrancis** [comment]
> That would be great!
> 
> A few comments:
> 
> * if I remember correctly, the reason sphinx is pinned at <6 is because of an issue with the gitter banner... maybe this can be replaced by something else?

Are we supporting the gitter? It appears to be used but I haven't been keeping up with it #2252 discussed it a bit and it kind of died off

> * I am happy to help with automating the build and push when the source is being updated
Thanks!  I'll ping you if I need help.

> * it would be useful to setup readthedocs preview on PR

I can do that
> * indeed, a section on workshop would be great but it should be simple and easy to update (and documented!) :) I think it long time, there was one, but it wasn't maintained, most likely because it is a bit tedious to update, but nowadays there are tooling which can make it very easy.


> Are you thinking of changing the theme too?

How do we feel about just copying https://github.com/scientific-python/scientific-python-hugo-theme/tree/c8ea3212ccbb322dbeb8bfe788f2662d06b2c8a8   I think that the numpy website is pretty clean and a good example.

**Comment by jlaehne** [comment]
I wouldn't mind the Hugo theme :-)

Now, after the split, we should introduce the HyperSpy ecosystem on the front page. I could imagine a graphical representation based on the logos (e.g. RSciIO above and the extension below HyperSpy itself). Alternatively a table, like for the Array Libraries on [numpy.org](https://numpy.org). I would imagine that part to come where currently the Covid box is placed. The first introductory part could be kept or replaced by boxes in the style of numpy/scipy

By the way, the link to the citing page is outdated with the new user guide.

PS: Would it be feasible in the mid-term to get on the listing of scientific domains on the numpy page?

**Comment by jlaehne** [comment]
If we are at it, can we redo the banner as a vector graphic (maybe taking up the snakehead from the LumiSpy and RosettaSciIO logos?).

**Comment by CSSFrancis** [comment]
> I wouldn't mind the Hugo theme :-)
> 
> Now, after the split, we should introduce the HyperSpy ecosystem on the front page. I could imagine a graphical representation based on the logos (e.g. RSciIO above and the extension below HyperSpy itself). Alternatively a table, like for the Array Libraries on [numpy.org](https://numpy.org). I would imagine that part to come where currently the Covid box is placed. The first introductory part could be kept or replaced by boxes in the style of numpy/scipy

Sounds good :). I've got a working example here: https://github.com/hyperspy/hyperspy-website/pull/49 if you want to look at it. 

I just added the extensions as just little cards, but a table might be a better way to do things. 

> By the way, the link to the citing page is outdated with the new user guide.

I think that can be easily replaced with the documentation.  I feel like having too much on this website kind of splits the documentation and isn't good.  I'd rather have the webpage be for like focused news type stuff. Links to documentation and to the developer team. Links to the Gitter and Github as well as maybe a blog for longer form stuff?

> PS: Would it be feasible in the mid-term to get on the listing of scientific domains on the numpy page?

That sounds like a great idea. I guess we can make a PR :)

**Comment by CSSFrancis** [comment]
> If we are at it, can we redo the banner as a vector graphic (maybe taking up the snakehead from the LumiSpy and RosettaSciIO logos?).

Sounds like a good idea!  We also need logos for exspy and holospy, however, we could just take the hyperspy logo and adjust it.

**Comment by jlaehne** [comment]
> > If we are at it, can we redo the banner as a vector graphic (maybe taking up the snakehead from the LumiSpy and RosettaSciIO logos?).
> 
> Sounds like a good idea! We also need logos for exspy and holospy, however, we could just take the hyperspy logo and adjust it.

See https://github.com/hyperspy/exspy/issues/17 and https://github.com/hyperspy/holospy/issues/20, as well as https://github.com/hyperspy/hyperspy/issues/3292

**Comment by ericpre** [comment]
I think that this is all done!
