### ISSUE TITLE
Producing sum-spectra of non rectangular ROIs from Bruker M4 Tornado X-ray fluorescence  BCF files

### ISSUE THREAD

**Issue by AbaPanu** [hyperspy/hyperspy#3324]
Hi there,

I cannot find a solution to the following in the documentation:
I am trying to use hyperspy on Bruker M4 Tornado X-ray fluorescence BCF files in order to extract sum-spectra of regions of interest (ROIs). My ROIs are exported from ImageJ as text files containing a list of x and y coordinates. The shapes of the ROIs are arbitrary and generally not rectangular.
Can I tell hyperspy to give me the sum of all spectra from the pixels of the ROI and export this, e.g., as an EMSA or MSA file?
I have only recently started working with hyperspy, so if there is more context needed, I can try to specify.

Thanks!

**Comment by CSSFrancis** [comment]
Hi @AbaPanu any chance you have a smaller dataset and an example of the xy files you can share? 

I think there is an outstanding PR for a polygon ROI which would work. There is also the new axes PR which would allow you to pass masks and that might work as well.

**Comment by AbaPanu** [comment]
Hi @CSSFrancis 
I added the smallest bcf file I found (hope it loads) along with the ROI indexed image with two of the ROIs as xy-coordinate-txt file. All I want from hyperspy is to get access to the EDX-spectra stored in the pixels of the ROIs. If the "sumspectra" command is not capable of adding the spectra together, I could also extract the EDX spectrum of a single pixel and then write a loop for all required pixels of an ROI and then sum them up. 
![AL-1-Al-K-Ti_Ti-seg_ROI_white](https://github.com/hyperspy/hyperspy/assets/161328485/931d6afb-722b-419d-aca1-8bb64b90c55f)
[ROI_0081.txt](https://github.com/hyperspy/hyperspy/files/14418239/ROI_0081.txt)
[ROI_0084.txt](https://github.com/hyperspy/hyperspy/files/14418240/ROI_0084.txt)

**Comment by AbaPanu** [comment]
I can't upload the bcf file, since the file type is not supported... Is there a workaround?

**Comment by CSSFrancis** [comment]
@AbaPanu Maybe something like this will work:

```python

import hyperspy.api as hs
import numpy as np

#signal = hs.load("...")

pretend_signal = hs.signals.Signal1D(np.ones((4000,4000,100)))

xy = np.loadtxt("ROI_0084.txt", skiprows=1, dtype=int)

all_in_area = hs.signals.Signal1D(pretend_signal.data[xy[:,0], xy[:,1]]) # You might have to reverse these depending on how the xy coordinates are read.

summed = all_in_area.sum(axis=0)
```

That kind of fancy indexing should be available in hyperspy at some point but we need to think about how we handle the axes. 

If you want to upload the data to something like a google drive I can provide more complete example. 

For reference: https://numpy.org/doc/stable/user/basics.indexing.html#advanced-indexing

**Comment by AbaPanu** [comment]
Thanks  for the suggestion.  However, I don't quite understand it. Here is what I get:

You are setting up a data structure called pretend_signal.
Then the pixels of the ROI are picked out of that data structure and summed up.

Where do the actual spectral data "signal" come in?

Also, I am starting to think that I may be wanting too much. An easier approach might be to try and extract each pixel individually into a normal 2D array and sum them up in a loop. So all I would need to know, is how to get the spectrum at pixel XY into an array.  This must be possible somehow, right?

Thanks!

**Comment by AbaPanu** [comment]
Hi there!

so after a few tries and thanks to @CSSFrancis suggestions, the following procedure works for BCF files < 5 GB (at least on my computer). For larger files that require to be handled in "Lazy"-mode, the "fancy indexing" used in the following code is not working because "Fancy indexing is not jet implemented in LazySignal" (according the the error I rescieved when trying it with a file of 26 GB). For larger files there is a workaround I will add here, but I first have to find a way of dealing with hyperspy/rosettasciio#241:  

```
import hyperspy.api as hs
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt

###############
## Functions ##
###############


def load_bcf_hypermap():
    for file_path in Path.cwd().glob('*.bcf'):
        print(file_path)
        bcf_hypermap = hs.load(file_path, lazy=False)
    return bcf_hypermap

def average_spectra_per_roi(file_path,bcf_hypermap):
    xy = np.loadtxt(file_path, skiprows=1, dtype=int)
    all_in_area = hs.signals.Signal1D(bcf_hypermap[4].data[xy[:,0], xy[:,1]])
    sum_spectrum = all_in_area.sum(axis=0)
    average_spectrum = sum_spectrum/len(xy)
    return sum_spectrum, average_spectrum


##################
## Main program ##
##################

bcf_hypermap = load_bcf_hypermap()
dir_path = Path('./rois')
for file_path in dir_path.glob('*.txt'):
    sum_spectrum, average_spectrum = average_spectra_per_roi(file_path,bcf_hypermap)
#    plt.plot(average_spectrum)
#    plt.show()
    average_spectrum.save(str(Path(file_path).stem) + '.msa', encoding = 'utf8')
```

**Comment by AbaPanu** [comment]
So finally in order to read the xy coordinates from the bcf file correctly:
`all_in_area = hs.signals.Signal1D(bcf_hypermap[4].data[xy[:,1], xy[:,0]])`
and it works for "smaller" bcf-hypermaps.
