### ISSUE TITLE
Plotting `BaseSignal` with no signal dimension gives error with `ipywidgets`

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#3329]
Plotting a `BaseSignal` with no signal dimension gives an error when using `%matplotlib widget`, but not with `%matplotlib qt5`:

#### To Reproduce
Run this in a Jupyter Notebook:

```python
%matplotlib widget
import hyperspy.api as hs
s = hs.signals.Signal1D(range(10))
s.plot() # Works nicely
s.T.plot() # Gives error
```

The error:

```python
File hyperspy/drawing/mpl_he.py:214, in MPL_HyperExplorer.plot.<locals>.plot_sig_and_nav(plot_style)
    212     display(self.signal_plot.figure.canvas)
    213 elif plot_style == "horizontal":
--> 214     display(HBox([self.navigator_plot.figure.canvas,self.signal_plot.figure.canvas]))
    215 else: # plot_style == "vertical":
    216     display(VBox([self.navigator_plot.figure.canvas, self.signal_plot.figure.canvas]))

AttributeError: 'NoneType' object has no attribute 'figure'
```

Using `%matplotlib qt5` does not give the error.

#### Python environment:

 - HyperSpy 2.0.0

**Comment by ericpre** [comment]
This is fixed in https://github.com/hyperspy/hyperspy/pull/3304.

Can you install latest version of hyperspy and confirm?

**Comment by magnunor** [comment]
Indeed! I think I tested it with `RELEASE_next_minor` in addition to `2.0.0`. In any case it now works with `RELEASE_next_minor`!
