### ISSUE TITLE
Saving Axes in metadata Doesn't work with saving

### ISSUE THREAD

**Issue by CSSFrancis** [hyperspy/hyperspy#3339]
#### Describe the bug
Right now we don't handle the saving of axes in the metadata which results in lost metadata.  Right now this happens in the find_peaks function.

We should either save the axes dictionary or just support saving axes in the metadata.

#### To Reproduce
```
s.find_peaks()

s.save("peaks.zspy") # saves the data but throws a warning that the axes aren't saved.
```

#### Expected behavior
This should be supported or handled differently 

#### Python environment:
 - HyperSpy version: 2.0.1
 - Python version: 3.11

@ericpre  any thoughts on the best way to handle this?

**Comment by ericpre** [comment]
This is a bug, axes saved in the metadata should be savable. Usually, objects are converted there:

https://github.com/hyperspy/hyperspy/blob/3b350ff80b68b0928b284e76d3dc0a2b31e6dbf5/hyperspy/misc/utils.py#L519-L529

and it doesn't cover `axes`.

**Comment by CSSFrancis** [comment]
@ericpre let me see about submitting a patch

**Comment by ericpre** [comment]
Done in #3342.
