### ISSUE TITLE
Dark spot locator algorithm

### ISSUE THREAD

**Issue by aidanc151** [hyperspy/hyperspy#3344]
#### Describe the functionality you would like to see.
A function that automatically detects the positions and radii of dark spots in an image, and the ability to perform manual corrections by the clicking in a figure to add or remove positions.

#### Describe the context
I've developed a function in matplotlib that uses the skimage [Laplacian of Gaussian blob detection algorithm](https://scikit-image.org/docs/stable/api/skimage.feature.html#skimage.feature.blob_log)  for locating and counting threading dislocations (dark spots) in cathodoluminescence panchromatic images ) I would then use these results to calculate a threading dislocation density in InGaN samples.

#### Additional information

I've managed to do this with HyperSpy Markers, where the results and marker positions are saved to Signal2D metadata for panchromatic image. However, I'm still working on how to do the manual adjustments with a hyperspy figures.

```
def dark_spot_locator(image, max_sigma=30, min_sigma=12, num_sigma=30, threshold = 0.1, 
                      permanent = False, color = 'r', linewidth = 2, invert_img = True):
    import numpy as np 
    import matplotlib.pyplot as plt 
    import hyperspy.api as hs
    import lumispy as lum   
    from skimage.util import invert
    from skimage.feature import blob_log

    # Assigns image intensity values of Signal2D
    image_array = image.data
    
    # Inverts color as blob_log detects white blobs on black background
    if invert_img == True:
        image_array = invert(image_array)  

    
    # Laplacian of Gaussian algorithm, outputting array of shape [..., 3]
    # containing dark spot offsets and radii
    blobs = blob_log(image_array, 
                         max_sigma=max_sigma, 
                         num_sigma=num_sigma, 
                         threshold=threshold)
   
    # Scales pixel pos to real space, and multiplies by reccommended factor
    # of sqrt(2) for radii
    y = blobs[:, 0] * image.axes_manager[0].scale
    x = blobs[:, 1]* image.axes_manager[0].scale
    r = blobs[:, 2] * image.axes_manager[0].scale * np.sqrt(2)

    
    # Declares markers object, and takes in offsets and radii found by LoG alogorithm 
    markers = hs.plot.markers.Circles(
        sizes=r,
        offsets=np.stack((x, y), axis=1),
        edgecolor=color,
        linewidth=linewidth,
        units = 'width')
    
    # Adds markers to Signal2D
    image.add_marker(markers, permanent = permanent)


image = hs.load('Data\M1910-3_pmt_map05.dm4')
dark_spot_locator(image, permanent = True, max_sigma=5, 
                  min_sigma=0.5, num_sigma=5, threshold = 0.01, invert_img = True)
```

Raw panchromatic image, showing dark spots (threading dislocations) and dark lines (misfit dislocations):
![planar_dis_panchromatic](https://github.com/hyperspy/hyperspy/assets/41931869/87c689de-a4e9-4ddd-88e1-0a5b525ed194)

LoG algorithm found positions in matplotlib function and figure:
![planar_dis_log_counting](https://github.com/hyperspy/hyperspy/assets/41931869/ffa39411-31ee-4863-8f40-4791ce8e4479)

LoG algorithm found positions (green) + manual corrections make by clicking on incorrect positions  to remove and adding other positions (red)
![planar_dis_manual_counting](https://github.com/hyperspy/hyperspy/assets/41931869/108a7bdb-2cb1-4c16-a78d-f74da336d61c)

This has definitely been personally useful for my mentioned cathodolumescence data but we (@jlaehne) wonder if there are other potential applications for which it would be worth integrating a feature like this into LumiSpy/HyperSpy.

When I load the .dm4 CL image into hyperspy it stores it as a Signal2D. It doesn't look like LumiSpy currently has a signal for storing monochromatic/panchromatic images. We were wondering if a feature like this would be best placed in LumiSpy in which case we would consider how to best implement it with a signal for CL pan/mono images, or if on the otherhand this may be more suited to be upstreamed to HyperSpy.

**Comment by jlaehne** [comment]
@ericpre and @CSSFrancis do you see a more general use for such an algorithm in HyperSpy (basically a specific variant of peak finding with option for interactive manual intervention). Otherwise, we would aim for an implementation in LumiSpy as in CL it has multiple applications: e.g. a similar approach was used in https://pubs.acs.org/doi/10.1021/acs.nanolett.1c01295?goto=supporting-info to count point defects and not dislocations.

**Comment by CSSFrancis** [comment]
So I think this should be added. 

I'd suggest something like.

```
blobs = s.find_peaks(method='laplacian_of_gaussian',invert=True)
```

Where the blobs would be a vector with x, y and sigma. That shouldn't be too hard.

It would also be interesting to be able to visualize the space scale representation as well. I'm a bit of a purest when it comes to these kind of things as I've been burned a lot by not visualizing the intermediary steps when peak finding.

Something like:

```
filtered = s.map(log_filter, ...) 

filtered.transpose(2).plot() # visualize the space scale representation 

filtered.find_peaks() # find peaks in the 3D space scale representation 
```

At the very least this would be a good example to include

**Comment by ericpre** [comment]
If I understand correctly, the main difference with [find_peaks](https://hyperspy.org/hyperspy-doc/dev/reference/api.signals/Signal2D.html#hyperspy.api.signals.Signal2D.find_peaks) is the inversion of the intensity?

When `find_peaks` was originally implemented in https://github.com/hyperspy/hyperspy/pull/1497, if I remember correctly, there was some discussion about making it slightly more generic (starting with the name itself) but since there wasn't a strong case and in the interest of completing the PR, we left it as it is.

It would make sense to integrate it to `Signal2D.find_peak` by adding an invert argument that can also be changed from the GUIs.

Other potential improvement:
- set the color of the markers based on the intensity (or other metric?) of the peaks/blobs.
- as @CSSFrancis, add more example/tutorial (using some data available on zenodo?) showing to diagnose analysis - this would also be complementary to the use of the GUIs to visualise how varying parameters change the results.

Maybe we should add a `Signal2D.find_blobs` method, which would more generic than the `Signal2D.find_peaks` method? @CSSFrancis, there are API changes you want to make to `Signal2D.find_peaks`, do these changes rely on better handling of vectors in hyperspy? If so, it may take some time to get the vector handling sorted first... 😃

**Comment by jlaehne** [comment]
Adding an `invert`  argument to `find_peaks` does sound like a sensible approach for the basic functionality.

On the GUI side, another difference is that the method from @aidanc151 allows for interactively doing a manual removal or addition of certain spots. If that is not of interest more generically, we could implement it within a wrapper function in LumiSpy. Though, recently I was using the `find_peaks_1Dohaver` for some XRD data of a colleague and I would have wished for a manual cleanup possibility on top of the automatic peak identification. So maybe we could implement that even more generally in 1D and 2D.

**Comment by ericpre** [comment]
> On the GUI side, another difference is that the method from @aidanc151 allows for interactively doing a manual removal or addition of certain spots. If that is not of interest more generically, we could implement it within a wrapper function in LumiSpy. 

Adding and removing spots is used in [atomap](https://atomap.org/gui_functions.html#adding-atoms-using-gui), so it would be useful (@magnunor) so it would be useful to have it in hyperspy.

The aim of the interactive functionality of `Signal2D.find_peaks` is to to find good parameters that work across different position of the navigation space and then apply the settings for the whole dataset. In that sense a manual curation of the peaks will not work very well, but this could be done a two steps process.

> Though, recently I was using the `find_peaks_1Dohaver` for some XRD data of a colleague and I would have wished for a manual cleanup possibility on top of the automatic peak identification. So maybe we could implement that even more generally in 1D and 2D.

Indeed, it should be possible to generalise to other markers too.

**Comment by aidanc151** [comment]
> If I understand correctly, the main difference with [find_peaks](https://hyperspy.org/hyperspy-doc/dev/reference/api.signals/Signal2D.html#hyperspy.api.signals.Signal2D.find_peaks) is the inversion of the intensity?
> 
> When `find_peaks` was originally implemented in #1497, if I remember correctly, there was some discussion about making it slightly more generic (starting with the name itself) but since there wasn't a strong case and in the interest of completing the PR, we left it as it is.
> 
> It would make sense to integrate it to `Signal2D.find_peak` by adding an invert argument that can also be changed from the GUIs.
> 
> Other potential improvement:
> 
> * set the color of the markers based on the intensity (or other metric?) of the peaks/blobs.
> * as @CSSFrancis, add more example/tutorial (using some data available on zenodo?) showing to diagnose analysis - this would also be complementary to the use of the GUIs to visualise how varying parameters change the results.
> 
> Maybe we should add a `Signal2D.find_blobs` method, which would more generic than the `Signal2D.find_peaks` method? @CSSFrancis, there are API changes you want to make to `Signal2D.find_peaks`, do these changes rely on better handling of vectors in hyperspy? If so, it may take some time to get the vector handling sorted first... 😃

Good to know that this LoG function has already been integrated into hyperspy. I noticed one difference between the skimage LoG function and find_peaks2D, being that the find_peaks2D does not return the radius of the identified blob. I realise this parameter doesn't make so much sense when the function is named find_peaks2D, although I thought it may be useful for some applications.

I've adapted the interactive functionality I was describing before, so that it uses hyperspy markers. I couldn't see a way of appending the dictionary in the signal metadata that contains the markers, so instead I basically extract an array from the dictionary, where I append or remove markers in the array with numpy. I then delete the current signal marker metadata entirely and then apply the updated array as markers to the signal. 

Something that I've not yet solved, is when repeatedly using image.add_marker() the previous array of markers is still visible in the figure, so basically each time I add or remove a marker a new layer of markers is applied to the figure. A consequence being that when I remove a marker it doesn't disappear because the previous array is still visible in the figure, even if it is no longer in the signal metadata.

I was wondering if anyone was aware of some kind of clear or update functionality regarding the markers in a figure that may solve this? I've tried using signal.update() but it's not having the effect I was expecting. (code below)


> > On the GUI side, another difference is that the method from @aidanc151 allows for interactively doing a manual removal or addition of certain spots. If that is not of interest more generically, we could implement it within a wrapper function in LumiSpy.
> 
> Adding and removing spots is used in [atomap](https://atomap.org/gui_functions.html#adding-atoms-using-gui), so it would be useful (@magnunor) so it would be useful to have it in hyperspy.
> 
> The aim of the interactive functionality of `Signal2D.find_peaks` is to to find good parameters that work across different position of the navigation space and then apply the settings for the whole dataset. In that sense a manual curation of the peaks will not work very well, but this could be done a two steps process.
> 
> > Though, recently I was using the `find_peaks_1Dohaver` for some XRD data of a colleague and I would have wished for a manual cleanup possibility on top of the automatic peak identification. So maybe we could implement that even more generally in 1D and 2D.
> 
> Indeed, it should be possible to generalise to other markers too.



I had a look at how Atomap does this but it looks like its mostly through matplotlib and doesn't make use of the same hyperspy markers and .plot() function



```
def dark_spots_interactive(image):      
    
    image.plot()
    
    def on_click(event):     
        if event.inaxes is not None:
            if image.metadata.has_item('Markers'):
                # Obtains current marker offsets and sizes from metadata
                marker_offsets = image.metadata.Markers.as_dictionary()['Circles']['kwargs']['offsets']
                marker_sizes = image.metadata.Markers.as_dictionary()['Circles']['kwargs']['sizes']
                
                # Obtains the index position of markers which falls into a given tolerance of the clicked position
                index = np.where(np.all(np.isclose(marker_offsets, [event.xdata, event.ydata], atol=0.06), axis=1))             
                         
                # If the length of index is 0, then there is no marker at this position, so a new one is 
                # appended to marker_offset as the clicked position and size arrays as an arbitrary value 
                if len(index[0]) == 0:    
                    print('Added')
                    marker_offsets = np.append(marker_offsets, [[event.xdata, event.ydata]], axis=0)
                    marker_sizes = np.append(marker_sizes, [0.05], axis=0)
                
                # If the length of index is 1, then there is a marker at this position, so use the index 
                # position to remove the marker from the array
                if len(index[0]) == 1:
                    print('Removed')
                    marker_offsets = np.delete(marker_offsets, index[0][0], axis=0)
                    marker_sizes = np.delete(marker_sizes, index[0][0], axis=0)
                
                # Removes metadata of existing permanent markers
                del image.metadata.Markers

           
            else:  # when no existing markers are found
                print('Added')
                marker_offsets = np.stack([[event.xdata, event.ydata]], axis=0)
                marker_sizes = np.stack([0.05], axis=0)        
        
        # Creates marker collection using arrays with added or removed markers, adds marker collection to signal
        image.add_marker(hs.plot.markers.Circles(offsets = marker_offsets, sizes = marker_sizes, edgecolor = 'b', linewidth = 2, units = 'width'), permanent = True)
        image.update_plot()
        
    plt.connect('button_press_event', on_click)



image = hs.load('Data\M1910-3_pmt_map05.dm4')
dark_spots_interactive(image)

```

**Comment by ericpre** [comment]
> Good to know that this LoG function has already been integrated into hyperspy. I noticed one difference between the skimage LoG function and find_peaks2D, being that the find_peaks2D does not return the radius of the identified blob. I realise this parameter doesn't make so much sense when the function is named find_peaks2D, although I thought it may be useful for some applications.

It would be good to add it (@CSSFrancis already hinted in that direction [above](https://github.com/hyperspy/hyperspy/issues/3344#issuecomment-2026457976)), maybe with a parameter to enable it (similarly as `get_intensity`) in order not to break the API and `False` as default?

> I've adapted the interactive functionality I was describing before, so that it uses hyperspy markers. I couldn't see a way of appending the dictionary in the signal metadata that contains the markers, so instead I basically extract an array from the dictionary, where I append or remove markers in the array with numpy. I then delete the current signal marker metadata entirely and then apply the updated array as markers to the signal.
>
> Something that I've not yet solved, is when repeatedly using image.add_marker() the previous array of markers is still visible in the figure, so basically each time I add or remove a marker a new layer of markers is applied to the figure. A consequence being that when I remove a marker it doesn't disappear because the previous array is still visible in the figure, even if it is no longer in the signal metadata.

I don't remember off the top of my head and anyway I am not sure if I fully understand what do you mean. To go into more details it would be easier to discuss with a pull request. There are an example about [adding/removing markers](https://hyperspy.org/hyperspy-doc/current/auto_examples/Markers/add_remove_marker.html) and it is documented in the API references: https://hyperspy.org/hyperspy-doc/current/reference/api.plot/markers.html#hyperspy.api.plot.markers.Markers.add_items, but what you need may be different.

> I had a look at how Atomap does this but it looks like its mostly through matplotlib and doesn't make use of the same hyperspy markers and .plot() function

Yes, this is the correct approach.

**Comment by aidanc151** [comment]
Topic is being re-addressed and specialised towards cathodoluminescence maps in https://github.com/LumiSpy/lumispy/pull/214
