### ISSUE TITLE
ROI selection

### ISSUE THREAD

**Issue by ozgurculfa** [hyperspy/hyperspy#3353]
Hello everyone, 
I just started using hyperspy and I noticed that I cannot select customized ROI. I need to select triangles for ROI and I was wondering if there is anyway of doing it with hyperspy? 
Thanks

**Comment by CSSFrancis** [comment]
There is something that is currently being worked on #3030 and should be included with the 2.1.0 release sometime in the next month or so.  

Otherwise you can always build from that branch and that should give you some of the features you are interested in.
