### ISSUE TITLE
Using CircleROI with plot_roi_map

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#3358]
I just discovered `plot_roi_map` (thanks @0Hughman0 !), which is really useful! For scanning electron diffraction datasets, it would be very nice to be able to use `CircleROI`. I have tested this a little bit, and it seems to (kinda) work, but there seems to be some issues related to how `CircleROI` operates.

--------

First make some test data:

```python
import numpy as np
import hyperspy.api as hs

data = np.random.random(size=(50, 40, 50, 60))
data[20, 30, 10, 25] = 10000
s = hs.signals.Signal2D(data)
circ_roi0 = hs.roi.CircleROI(cx=10, cy=10, r=10, r_inner=0)
rois = [circ_roi0, ]
```

Plotting this:
```python
all_sum, rois, roi_signals, roi_sums = hs.plot.plot_roi_map(s, rois=rois)
```

Also plotting the `roi_signals`:

```python
roi_signals[0].plot()
```

The results of this:

[plot_roi_map_circle_roi.webm](https://github.com/hyperspy/hyperspy/assets/1690979/0f8dbcb2-76a6-410b-99a5-9cae095efd66)

----------------

So the `CircleROI` updates correctly: it can be moved, and the radius (inner and outer) can be changed. However, currently it effectively works as a rectangle ROI, which seems to be due to the circle mask being applied after the data from the roi itself is updated.

**Comment by 0Hughman0** [comment]
Hiya Magnunor, glad you've found this feature useful!

Does seem like there's an issue here.

Just to make sure I understand correctly.

When you select a region in diffraction space with the circle tool, it seems to be mapping out intensities from areas outside the circle, specifically including regions that fit within a square around the circle.

I think this is something to do with the interactive implementation because if I do:

```
%matplotlib qt

import numpy as np
import hyperspy.api as hs

data = np.zeros((50, 40, 50, 60))
data[0, 0, 0, 0] = 10000
s = hs.signals.Signal2D(data)
roi = hs.roi.CircleROI(cx=4, cy=4, r=4.5, r_inner=0)

all_sum, rois, roi_signals, roi_sums = hs.plot.plot_roi_map(s, rois=[roi])
roi_signal, = roi_signals
roi_sum, = roi_sums
```

```
>>> roi_signal.data[0, 0]  # 0,0 not in roi signal
array([[nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan,  0.,  0.,  0.,  0.,  0.,  0., nan],
       [nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [nan, nan,  0.,  0.,  0.,  0.,  0.,  0., nan]])
>>> roi_sum.data  # 0,0 not in roi sum
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])
>>> roi.cx = 5  # force update
>>> roi.cx = 4
>>> roi_signal.data[0, 0]  # 0,0 still not in roi signal
array([[nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan,  0.,  0.,  0.,  0.,  0.,  0., nan],
       [nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [nan, nan,  0.,  0.,  0.,  0.,  0.,  0., nan]])
>>> roi_sum.data  # but is included in roi sum
array([[10000.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       ...,
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.]])
```

**Comment by 0Hughman0** [comment]
Ok I think the issue might be here: 

https://github.com/hyperspy/hyperspy/blob/18caceb7a7a777d970023725071e8a7b9505a80f/hyperspy/drawing/utils.py#L1941

We are only listening for axes changes, which is appropriate for Rect and Span ROIs, where they only change the axes, whereas CircleROI changes the axes and then the data.

A potential hot fix might be:

```
def _plot_roi_map(s, rois):
    all_sum, rois, roi_signals, roi_sums = hs.plot.plot_roi_map(s, rois=1)

    for roi_signal, roi_sum in zip(roi_signals, roi_sums):
        hs.interactive(
            roi_signal.nansum,
            event=roi_signal.events.data_changed,
            axis=roi_signal.axes_manager.signal_axes,
            out=roi_sum,
            recompute_out_event=None,
        )
    return all_sum, rois, roi_signals, roi_sums
```

i.e. listen for `roi_signal.events.data_changed` signals rather than `roi_signal.axes_manager.events.any_axis_changed`.
