### ISSUE TITLE
Inconsistent axes ticks with Signal2D.plot and plot_images

### ISSUE THREAD

**Issue by viljarjf** [hyperspy/hyperspy#3361]
#### Describe the bug
When plotting a signal using `plot_images`, the axis ticks and scales are different than using `Signal2D.plot`. 
`Signal2D.plot` has the centers of the pixels as the ticks, whereas `plot_images` uses the edges.
Furthermore, for an axis with negative scale, the ticks gets flipped in `plot_images`. This would be fine for me, if the data was also flipped.

#### To Reproduce
```python
from hyperspy.axes import UniformDataAxis
from hyperspy.signals import Signal2D
from hyperspy.utils.plot import plot_images
import numpy as np

data = np.random.random((4,4))

positive_axis = UniformDataAxis(scale= 1, size=4, name="positive", units="px")
negative_axis = UniformDataAxis(scale=-1, size=4, name="negative", units="px")

s = Signal2D(data, axes=[positive_axis, negative_axis])

plot_images([s], label=["plot_images"])
s.plot(axes_ticks=True)
```
![bilde](https://github.com/hyperspy/hyperspy/assets/57151700/ede2ea7d-09ff-4988-a4d4-d08321c219ad)
![bilde](https://github.com/hyperspy/hyperspy/assets/57151700/cb0c10fb-331f-4c36-a73e-0c0d8cdd746c)

#### Expected behavior
Both outputs should look identical

#### Python environment:
 - HyperSpy version: 2.0.1
 - Python version: 3.12

#### Additional context
Add any other context about the problem here. If necessary, add screenshots to help explain your problem.

**Comment by CSSFrancis** [comment]
@viljarjf This should probably be changed!

For reference:
https://github.com/hyperspy/hyperspy/blob/5816c40412725aa6a836d6f05f3c47ea6aae8d85/hyperspy/drawing/utils.py#L1114-L1119


https://github.com/hyperspy/hyperspy/blob/5816c40412725aa6a836d6f05f3c47ea6aae8d85/hyperspy/drawing/image.py#L228-L234

Do you want to make the PR to fix this?  ~~@ericpre I think this is fine going into `ReleaseNextMinor` rather than `ReleaseNextBugfix`~~

Add this to `RELEASE_next_patch` then :)

**Comment by ericpre** [comment]
> Do you want to make the PR to fix this? @ericpre I think this is fine going into `ReleaseNextMinor` rather than `ReleaseNextBugfix`

Bug fixes goes to `RELEASE_next_patch`, which is merged regularly into `RELEASE_next_minor`.

**Comment by CSSFrancis** [comment]
> Bug fixes goes to `RELEASE_next_patch`, which is merged regularly into `RELEASE_next_minor`.

I didn't really know where this PR should go as it slightly changes the plotting behavior, even if it does so in a way that is more in line with hyperspy's standard behavior.

**Comment by CSSFrancis** [comment]
@viljarjf This is just a heads-up that you might run into some problems with the plotting testing the hyperspy does for this PR. I'm unsure if the `plot_images` function is tested using those. 

There is documentation related to it if you do; otherwise, you can always ask for help if necessary.

https://hyperspy.org/hyperspy-doc/current/dev_guide/testing.html#plot-testing

**Comment by viljarjf** [comment]
Checking whether two plots are different seems like a seperate problem to what `pytest.mark.mpl_image_compare` is designed for.
From what I understand, the test functions are run and their outputs collected once, and then used as a baseline for comparison for later tests. This is not really what I'm after, since I want to compare two different figures which might as well be generated on the fly each time. But then again, what I really want to test is the axes ticks, which I can probably just get from the figures.

**Comment by CSSFrancis** [comment]
@viljarjf Sorry, I'm maybe jumping a bit ahead. 

Tests like this will probably fail:

https://github.com/hyperspy/hyperspy/blob/5816c40412725aa6a836d6f05f3c47ea6aae8d85/hyperspy/tests/drawing/test_plot_signal2d.py#L501-L511

As they depend on the old axes ticks :).  Those tests aren't run by default and require specific matplotlib versions so they are sometimes tricky to pass.

**Comment by ericpre** [comment]
> > Bug fixes goes to `RELEASE_next_patch`, which is merged regularly into `RELEASE_next_minor`.
> 
> I didn't really know where this PR should go as it slightly changes the plotting behavior, even if it does so in a way that is more in line with hyperspy's standard behavior.

@CSSFrancis, this is bug, because the axis ticks are incorrect in the `hs.plot.plot_images`. Any side effects, such as image comparison in plotting test relying on this, will need to be updated to the new correct ticks.

**Comment by viljarjf** [comment]
I can make a PR with a fix and test in a couple hours
