### ISSUE TITLE
Relationship to xarray?

### ISSUE THREAD

**Issue by TomNicholas** [hyperspy/hyperspy#3404]
Hi, I just heard about this package & ecosystem via your upcoming talk at SciPy 2024. It looks very well-developed and powerful!

I'm wondering why you don't just use [xarray](https://github.com/pydata/xarray) for your core implementation of handling multidimensional data? (Perhaps this project simply predates xarray?) 

As far as I can tell from a quick scan of your project, you have separate implementations of many features already supported in xarray, such as:
- distinguishing between multiple axes of an array via named dimensions https://hyperspy.org/hyperspy-doc/current/user_guide/axes.html
  - In your case the named dimensions seem to be `signal` and `navigation`, but xarray can distinguish arbitrary numbers of arbitrarily-named axes
- lazy loading of large datasets https://hyperspy.org/hyperspy-doc/current/user_guide/io.html#lazy-loading-of-large-datasets
  - xarray can do this for any file format, and supports [lazy indexing](https://docs.xarray.dev/en/stable/internals/internal-design.html#lazy-indexing-classes) into those arrays also (even without dask!)
- parallel and out-of-core computation via dask https://hyperspy.org/hyperspy-doc/current/user_guide/big_data.html#lazy-signals-from-external-data
  - this is a [major selling point](https://docs.xarray.dev/en/stable/user-guide/dask.html) of xarray. We can also support [other parallel frameworks](https://github.com/cubed-dev/cubed) that act as alternatives to `dask.array`
- quick access to 1D and 2D visualizations https://hyperspy.org/hyperspy-doc/current/user_guide/visualisation.html
  - xarray has [many plotting functions](https://docs.xarray.dev/en/stable/user-guide/plotting.html)
- automatically reading data from multiple file formats https://hyperspy.org/hyperspy-doc/current/user_guide/io.html#specifying-reader
  - xarray has first-class support for HDF5 files, but it also has an [entrypoint system](https://docs.xarray.dev/en/stable/internals/how-to-add-new-backend.html) that allows you to write a reader for any file format you like
- loading data from multiple files via a glob syntax https://hyperspy.org/hyperspy-doc/current/user_guide/io.html#loading-multiple-files
  - xarray has the extremely powerful function [`open_mfdataset`](https://docs.xarray.dev/en/stable/generated/xarray.open_mfdataset.html) for this, which can do N-dimensional [combining operations](https://docs.xarray.dev/en/stable/user-guide/combining.html#combining-along-multiple-dimensions), and even do the arranging automatically by ordering datasets based on reading coordinate values
- tracking of arbitrary metadata https://hyperspy.org/hyperspy-doc/current/user_guide/io.html#metadata
  - xarray supports an [arbitrary dictionary of attributes](https://docs.xarray.dev/en/stable/getting-started-guide/quick-overview.html#attributes)
- `.interactive` operations https://hyperspy.org/hyperspy-doc/current/user_guide/interactive_operations.html#interactive-operations
  - [this discussion](https://github.com/pydata/xarray/issues/3709) on doing this in xarray led to first-class support for [interactively operating on xarray datasets in holoviews](https://hvplot.holoviz.org/user_guide/Interactive.html)

There are multiple features which you seem interested in supporting that xarray already supports:
- reading and writing very large datasets via the zarr format https://github.com/hyperspy/hyperspy/issues/2784
  - again this is a major selling-point of xarray. I would go so far to say that one of the biggest use cases for zarr is to open it lazily via xarray and process it in parallel via dask.
- wrapping duck-typed arrays, including sparse arrays https://github.com/hyperspy/hyperspy/issues/3171
  - xarray supports wrapping any array type that conforms to the array API standard, including sparse arrays
- unit-handling via pint https://hyperspy.org/hyperspy-doc/current/user_guide/pint_unit_registry.html
  - xarray supports this, and there is a [convenience package `pint-xarray`](https://github.com/xarray-contrib/pint-xarray)

There are also features that you seem interested in which we are also interested in supporting, for example:
- wrapping "ragged" arrays https://github.com/hyperspy/hyperspy/issues/3373
  - xarray doesn't support this yet, but mostly because it doesn't have a main person to champion its development. Nevertheless the [`ragged` package](https://github.com/scikit-hep/ragged) as a subset of awkward-array was actually [motivated](https://github.com/pydata/xarray/issues/4285#issuecomment-1200110315) by trying to make awkward compatible with xarray!

Is there some killer feature that you need that xarray does not or could not provide?

Xarray is [extremely flexible](https://docs.xarray.dev/en/stable/internals/interoperability.html), and whilst the majority of our users are in the geosciences, our design is deliberately domain-agnostic, and we actually have significant userbases in many different fields of science. Often these domain-specific users build their own package atop of xarray which provides domain-specific functionality using [xarray accessors](https://docs.xarray.dev/en/stable/internals/extending-xarray.html) or other features.

Is there anything that we could do as xarray developers to help facilitate collaboration here? (I'll be at scipy from tomorrow if any of you want to chat in-person @jat255 @CSSFrancis @francisco-dlp)

**Comment by jat255** [comment]
@TomNicholas and I are going to chat this week. In the meantime, I'm going to move this to discussions as it's more appropriate there.
