### ISSUE TITLE
Unable to access marker collection applied to signal

### ISSUE THREAD

**Issue by aidanc151** [hyperspy/hyperspy#3415]
#### Describe the bug
There seems to be an issue when trying to access a marker collection that has been applied to a signal.

#### To Reproduce

```
import numpy as np
import hyperspy.api as hs
import matplotlib.pyplot as plt 

s = hs.signals.Signal2D(np.ones((125, 125)))

offsets = np.array([np.arange(0, 100, 10)]*2).T
sizes = np.array([np.arange(0, 10, 1)])

m = hs.plot.markers.Circles(
    sizes=sizes,
    offsets=offsets)

s.add_marker(m, permanent = True)
```
![Output](https://github.com/user-attachments/assets/1722ccb7-34c2-4e90-b0fa-f7699cba16a7)

Both
```
m = hs.plot.markers.Markers.from_signal(s, collection = 'CircleCollection')
m

# <Markers, length: 125>
```
and 
```
m = hs.plot.markers.Circles.from_signal(s, sizes = 1)
m

# <Circles, length: 125>
```
seem to return the navigational extent (125x125) of the signal rather than the 10 markers that were applied to the signal. The `offsets` also show this:

```
m.get_current_kwargs()

# {'offsets': array([[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]]),
 'sizes': (1,),
 'facecolors': 'none',
 'units': 'x'}
```

Unsure if I'm misunderstanding the purpose the function, I was expecting to be able to access the offset values of the circle markers in the dictionary that they're stored. Any help is appreciated.

#### Python environment:
 - HyperSpy version: 2.1.1
 - Python version: 3.11.9

**Comment by ericpre** [comment]
If you want to access the parameters of the markers, you will do that using: `m.kwargs` and `m.get_current_kwargs`.
To access the marker collection, you need to keep the handle of the marker collection (in your example `m`).
If this is a permanent marker, it is [stored in the metadata](https://hyperspy.org/hyperspy-doc/current/user_guide/visualisation.html#permanent-markers).

To clarify, [`hs.plot.markers.Markers.from_signal`](https://hyperspy.org/hyperspy-doc/current/reference/api.plot/markers.html#hyperspy.api.plot.markers.Markers.from_signal
) creates markers from the values of signal, which are typically used to define the `offsets`. There is an example illustrating this: https://hyperspy.org/hyperspy-doc/current/auto_examples/Markers/from_signal.html#sphx-glr-auto-examples-markers-from-signal-py.
This is not to be used to access markers.

**Comment by aidanc151** [comment]
Thank you for the clarification!
