### ISSUE TITLE
Release 2.2

### ISSUE THREAD

**Issue by ericpre** [hyperspy/hyperspy#3451]
As mentioned in https://github.com/hyperspy/hyperspy/issues/3448#issuecomment-2402413433 and https://github.com/hyperspy/hyperspy/pull/3449#issuecomment-2408968354, it would be good to make a release. I think we should do a minor release, because there are a number a features that would be good to release.

## PRs to merged before release 
- [x] #3449
- [x] #3450
- [x] #3333 
- [x] #3456
- [x] #3457

## Optional
- [ ] #3436
- [ ] #3441
- [x] #3030 (still need some work)

@jlaehne, @CSSFrancis, what do you think?

**Comment by jlaehne** [comment]
Sounds like a plan. The optional PRs indeed seem to be low hanging fruit to include, but I do not really have time to review these at the moment.

#3333 could possibly make it in @CSSFrancis ?

Looking at older PRs: #2445 and #3031 might be worth a look whether they could be finished?

**Comment by CSSFrancis** [comment]
@jlaehne #3333 Should be ready to go, it's also just documentation so no big deal. I added the Changlog which was the last part to test there. 

#3031... I would love to get something like that in but I think that at the moment that might hold things up more than we would like.

**Comment by ericpre** [comment]
@CSSFrancis, @jlaehne, I added two small PRs and we should be ready to go.
