### ISSUE TITLE
How to use the GOS to fit EELS with exspy?

### ISSUE THREAD

**Issue by winston-song** [hyperspy/hyperspy#3463]
I enabled the access to the Gatan GOS table,

exspy.preferences.EELS.eels_gos_files_path = 'C:\ProgramData\Gatan\EELS Reference Data\HS GOS Tables'
exspy.preferences.save()

M_L3 = exspy.components.EELSCLEdge("Co_L3", GOS="Hartree-Slater")

It gives error that I cannot figure out since my code can work well for previous hyperspy version without exspy. Can anyone help me out?

UnicodeDecodeError Traceback (most recent call last)
Cell In[39], line 1
----> 1 M_L3 = exspy.components.EELSCLEdge("Co_L3", GOS="Hartree-Slater")

File ~\AppData\hyperspy-bundle\lib\site-packages\exspy\components\eels_cl_edge.py:189, in EELSCLEdge.init(self, element_subshell, GOS, gos_file_path)
185 self.GOS = GoshGOS(
186 element_subshell, gos_file_path=gos_file_path, source="dirac"
187 )
188 elif GOS == "Hartree-Slater": # pragma: no cover
--> 189 self.GOS = HartreeSlaterGOS(element_subshell)
190 elif GOS == "hydrogenic":
191 self.GOS = HydrogenicGOS(element_subshell)

File ~\AppData\hyperspy-bundle\lib\site-packages\exspy_misc\eels\base_gos.py:115, in TabulatedGOS.init(self, element_subshell)
113 self.element, self.subshell = element_subshell.split("_")
114 self.read_elements()
--> 115 self.read_gos_data()

File ~\AppData\hyperspy-bundle\lib\site-packages\exspy_misc\eels\hartree_slater_gos.py:142, in HartreeSlaterGOS.read_gos_data(self)
134 raise FileNotFoundError(
135 "Parametrized Hartree-Slater GOS files not "
136 f"found in {gos_root}. Please define a valid "
137 "location for the files in the preferences as "
138 "preferences.EELS.eels_gos_files_path."
139 )
141 with open(gos_file) as f:
--> 142 GOS_list = f.read().replace("\r", "").split()
144 # Map the parameters
145 info1_1 = float(GOS_list[2])

File ~\AppData\hyperspy-bundle\lib\encodings\cp1252.py:23, in IncrementalDecoder.decode(self, input, final)
22 def decode(self, input, final=False):
---> 23 return codecs.charmap_decode(input,self.errors,decoding_table)[0]

unicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 71: character maps to <undefined>

**Comment by ericpre** [comment]
By default, the default EELSModel now uses open GOS and doesn't need anymore the Gatan GOS - see exspy documentation: https://hyperspy.org/exspy/user_guide/eels.html#generalised-oscillator-strengths.

In the interest of avoiding duplicated issues, I close in favour of https://github.com/hyperspy/exspy/issues/95.
