### ISSUE TITLE
BUG: slicing not working as expected when out of range

### ISSUE THREAD

**Issue by pburdet** [hyperspy/hyperspy#372]
Slicing with float do not always return an error when slicing outside the limit. 

For s:

>>> s = signals.Spectrum(range(1000))
>>> s.axes_manager[0].scale = 0.01
>>> s.axes_manager[0].units = "keV"

Then

>>> s[15.]

Return ``ValueError: The value is out of the axis limits`` as expected. But 

>>> s[15.:16.]

Return a spectrum but it should return a ``ValueError``

**Comment by pburdet** [comment]
Another bug of slicing:


```python

    >>>s = signals.Signal(range(5))
>>> s[3.6:4.1]

```

**Comment by vidartf** [comment]
For something labeled "bug", this has been around for quite a long while. I see @pburdet has a commit that supposedly fixes (parts/all) of this?

**Comment by francisco-dlp** [comment]
Which commit is it?

**Comment by vidartf** [comment]
" pburdet added a commit to pburdet/hyperspy that referenced this issue on 31 Mar 2015
	@pburdet 	BUG: prevent bug in slicing see issue #372"

**Comment by francisco-dlp** [comment]
Mmm, that looks like a hack to get some EDS feature working despite the bug.

**Comment by francisco-dlp** [comment]
I'll change the milestone to the RELEASE_next_patch

**Comment by to266** [comment]
https://github.com/hyperspy/hyperspy/pull/1194
