### ISSUE TITLE
Remove `Model` component with `del` raises error

### ISSUE THREAD

**Issue by pburdet** [hyperspy/hyperspy#380]
Component cannot be removed with ``del m[0]``

```python

import hyperspy.hspy as hs
s = hs.signals.Spectrum(random.random([100]))
m = create_model(s)
g1 = components.Gaussian()
m.append(g1)
del m[0]

```

**Comment by francisco-dlp** [comment]
Given that it is written nowhere that `del m[0]` removes the first component, this is not a bug but an enhancement proposal ;) (I've changed the label accordingly).

**Comment by francisco-dlp** [comment]
I've also changed the title.

**Comment by francisco-dlp** [comment]
Sorry, I was wrong, we do support `del` for `Model`.
