### ISSUE TITLE
NEW: EDS model

### ISSUE THREAD

**Issue by pburdet** [hyperspy/hyperspy#390]
Given the specificity of EDS spectrum, it is important to have an EDSmodel. I'm working on it currently, see branch https://github.com/pburdet/hyperspy/tree/NEW_edsModel

![edsmodel](https://cloud.githubusercontent.com/assets/3855190/4789872/7a4d145c-5dca-11e4-8f63-bb7079a25b3f.PNG)
![edsmodel2](https://cloud.githubusercontent.com/assets/3855190/4789897/d52b2ee0-5dca-11e4-9fe5-fbca17fba37b.PNG)

**Comment by dnjohnstone** [comment]
This is now resolved through #786
