### ISSUE TITLE
Add support for 64 bits FEI ser files

### ISSUE THREAD

**Issue by pburdet** [hyperspy/hyperspy#397]
It seems that FEI has a new version of their emi/ser file. I cannot read newly acquired files. I obtained an error about array of different shapes that cannot be broadcasted

**Comment by thomasaarholt** [comment]
[This sentence in the attached spec may be relevant](http://www.er-c.org/cbb/info/TIAformat/):
> The information relates to ES Vision 3.x, in later versions of TIA the format was updated to use 8 byte integers allowing files greater than 2GB.

**Comment by francisco-dlp** [comment]
Can anybody provide an example of a file that HyperSpy can't read? Notice that #835 enhances FEI  ser reading support.

**Comment by francisco-dlp** [comment]
Fixed in #883
