### ISSUE TITLE
BUG: fitting eels background

### ISSUE THREAD

**Issue by pburdet** [hyperspy/hyperspy#432]
The nosetests are generating an issue (on windows) related to fitting eels background

![capture](https://cloud.githubusercontent.com/assets/3855190/5775028/9472072a-9d6c-11e4-9b10-f92b5c1f735b.PNG)

**Comment by francisco-dlp** [comment]
I cannot reproduce the issue in Linux and Windows using the anaconda 64 bits python distribution.

**Comment by pburdet** [comment]
The outcome of the fit depends on some preset in preference. The test is past with default value in preferences
