### ISSUE TITLE
Implement summing over pixels

### ISSUE THREAD

**Issue by gdonval** [hyperspy/hyperspy#44]
The cursor does not sums over the pixels it includes.

**Comment by vidartf** [comment]
This is now possible via ROI -> mean/sum, however, it is not possible to change the default navigator to a sum/mean. I'm more than happy to put this as resolved as it is, but if we want to be able to change navigator type, these issues needs awareness:
 - If the navigator is larger than 1x1, how do we treat edge case? I.e. when axes manager is indexed to higher than DataAxis.size - ROI.size?
 - Will this summed/meaned signal only be used for plotting, or should it affect `signal.__call__()` and `signal.get_current_signal()` as well?

**Comment by francisco-dlp** [comment]
Giving that this is now easily achievable and highly customisable with the new ROI, I don't think that there is much point in implementing this as an optional navigator. +1 for closing this issue.

**Comment by vidartf** [comment]
Closing for now, comment if you feel that the current behavior is insufficient or unintuitive, and it can be reopened.
