### ISSUE TITLE
Guide for developers

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#445]
We desperately need to write a guide for developers.

Topics
--------

(This is a draft, please feel free to edit)

- [ ] Reporting bugs
- [ ] PR checklist:
    - [ ] best practices
    - [ ] Where to PR: master and maintenance branches
- [ ] Milestones: wishlists

**Comment by pburdet** [comment]
What about this https://github.com/hyperspy/hyperspy/wiki/Guidelines-for-developers

**Comment by francisco-dlp** [comment]
Sorry that I forgot to mention the one in the wiki. I think that it is largely incomplete and not easy to find.

**Comment by vidartf** [comment]
Superseeded by #782.
