### ISSUE TITLE
Use skimage histogram equalization tools

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#486]
Currently HyperSpy automatically stretches the contrast of images by using percentiles. It would be nice to also add the [histogram equalization tools available in scikit-image](http://scikit-image.org/docs/dev/auto_examples/plot_equalize.html).

**Comment by vidartf** [comment]
Out the gate, I immediately think that this should/could be implemented using the ```norm``` argument to imshow, using a custom Normalize (http://matplotlib.org/api/colors_api.html#matplotlib.colors.Normalize). For hyperspyUI I add log image contrast something like this:
```python
n = SymLogNorm(1e-9, **kw)
# 1e-9 is linearization region, should maybe be less than the minimal 
# absolute value of image instead
signal._plot.signal_plot.ax.images[-1].norm = n
```

**Comment by vidartf** [comment]
PS: The reason I champion the normalization is because it is simply display processign, and you always retain the original data.

**Comment by tjof2** [comment]
The custom normalize argument is supported: https://github.com/hyperspy/hyperspy/blob/5e8cdbb3e7a3aa6d76bcdd7b0ba45c2dd1345660/hyperspy/docstrings/plot.py#L128
