### ISSUE TITLE
EHN: kwargs for plot_navigator (image)

### ISSUE THREAD

**Issue by pburdet** [hyperspy/hyperspy#515]
If signal dimension is zero, then we hit a bug

``` Pythons

    >>> import scipy
    >>> image = signals.Image([scipy.misc.lena()]*6)
    >>> image.axes_manager.set_signal_dimension(0)
    >>> image.plot()

```

**Comment by pburdet** [comment]
This solve the problem:

``` Pythons
>>> import scipy
>>> image = signals.Image([scipy.misc.lena()]*6)
>>> image.axes_manager.set_signal_dimension(0)
>>> image.set_signal_type('Image')
>>> image.plot()
```

**Comment by pburdet** [comment]
In fact, this is not a bug but more a request of feature. Should we add an easy way (kwargs) to change the setting of the navigator images?

**Comment by francisco-dlp** [comment]
Any ideas on how to implement this?

**Comment by vidartf** [comment]
How about if we pass in a dict `nav_kwargs` (better name suggestions welcome)? E.g. for a spectrum image (2D nav, 1D signal) something like:
```python
s.plot(lw=5, nav_kwargs=dict(norm=PowerNorm(0.95))
```

**Comment by ericpre** [comment]
`navigator_kwds` exists since a while!

**Comment by ericpre** [comment]
Done in #1286.
