### ISSUE TITLE
BUG: eds spectrum sum

### ISSUE THREAD

**Issue by pburdet** [hyperspy/hyperspy#519]
s.sum('x') crashs

**Comment by francisco-dlp** [comment]
I couldn't reproduce this. For example, the following works for me:

```python
>>> s = hs.signals.Spectrum(np.empty((10, 20, 30)))
>>> for i, label in enumerate(["x", "y", "z"]):
    s.axes_manager[i].name = label
...     
>>> s.sum("x")
<Spectrum, title: , dimensions: (10|30)>

```

Could you provide an example that triggers the bug?

**Comment by pburdet** [comment]
``Python
s = hs.signals.EDSSEMSpectrum(np.empty((10, 20, 30)))
for i, label in enumerate(["x", "y", "z"]):
    s.axes_manager[i].name = label 
s.set_microscope_parameters(live_time=1.)
s.sum("x")
```

Really easy to fix

**Comment by vidartf** [comment]
#586 should fix this.
