### ISSUE TITLE
BUG: incomplete copying when using spectrum slicing and copy

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#533]
When trying to align a low loss spectrum using a slice of itself, I noticed some weird behavior. The zero loss peak was not properly aligned. This can be replicated using the code: 

```
import hyperspy.hspy as hspy
import numpy as np
import copy

g = hspy.components.Gaussian(A=100., sigma=10., centre=20)
data = []
for i in range(10):
    g.centre.value = i*10+120
    data.append(g.function(np.arange(1000)))
s = hspy.signals.EELSSpectrum(data)

s1 = copy.deepcopy(s)
s2 = copy.deepcopy(s)
s3 = copy.deepcopy(s)

s1.copy()[...,80:240].align_zero_loss_peak(also_align=[s1])
s2[...,80:240].align_zero_loss_peak(also_align=[s2])
copy.deepcopy(s3)[...,80:240].align_zero_loss_peak(also_align=[s3])
```
Original spectrum (s):
![spectrum_original](https://cloud.githubusercontent.com/assets/1690979/7378660/5834fe42-edef-11e4-8618-244d6e7a5813.png)

Spectrum (s1) using s.copy:
![spectrum_copy](https://cloud.githubusercontent.com/assets/1690979/7378667/67d4aca8-edef-11e4-94a3-6da2e582e4f2.png)

Spectrum (s2):
![spectrum_align](https://cloud.githubusercontent.com/assets/1690979/7378670/70968c4e-edef-11e4-842a-1c9bee65d82a.png)

Spectrum copied using deepcopy (s3):
![spectrum_deepcopy](https://cloud.githubusercontent.com/assets/1690979/7378674/790f677e-edef-11e4-8f61-193fcd8e73a9.png)

Only the last spectrum using deepcopy is as expected. 

So I'm guessing there is some kind of bug in the slicing code, leaving some part of the new spectrum linked to the old one.

**Comment by francisco-dlp** [comment]
Indeed, when using `copy` or slicing the data of the new `Signal` instances are a view of the original data but this is supposed to be a feature not a bug ;) Therefore, I would expect only the `deepcopy` approach to work in this case.

Some comments:
* `s1.copy()[...,80:240]` and `s2[...,80:240]` are equivalent.
* You could get a deepcopy more conveniently using `s3.deepcopy()` instead of `copy.deepcopy(s3)`

Just out of curiosity, `align_zero_loss_peak` automatically restricts the alignment operation to the region around the zero loss peak when internally calling `align1D`, why do you restrict the spectral range of the operation manually?

**Comment by magnunor** [comment]
I didn't know about that feature :) I guess it makes sense, since using view is a lot more memory efficient.  

I was having some problems on low signal-to-noise low loss spectra, where stray radiation could create peaks which where higher than the zero loss peak. This caused `align_zero_loss_peak` to mistake this peak as the zero loss peak, causing the low loss signal to be shifted and cropped wrongly. I'm guessing a solution to this specific problem could be to check if there are some extreme outliers in ZLP position, since I rarely see any energy shifts above +- 10 eV.

At what point is the reference to the original signal broken? For example:
```
s = load("...")
s1 = s[...,100.:200.]
s1.remove_background()
```
Here the `remove_background` will not change the original signal `s`. However when using `align_zero_loss_peak` as shown in my first post, there will be some weird effects.

**Comment by to266** [comment]
Here you picked two quite different functions. The `remove_background` actually returns a new signal, whereas `align{1D / zero_loss_peak / 2D}` actually operates on the signal from where it was called + any additional signals (the `align_also` flag). If you do want to still have a copy of not-aligned signals, I would deepcopy it first, as in your examples. 

I am also a proponent of the `isig` and `inav` slicing, so everything would look like so:

```python
s = load("...")
s_aligned = s.isig[100.:200.].deepcopy().align_zero_loss_peak()
```
..and of course swapping slicing and deepcopy should result in the same.

**Comment by francisco-dlp** [comment]
@magnunor wrote:

> I was having some problems on low signal-to-noise low loss spectra, where stray radiation could create peaks which where higher than the zero loss peak. This caused align_zero_loss_peak to mistake this peak as the zero loss peak, causing the low loss signal to be shifted and cropped wrongly. I'm guessing a solution to this specific problem could be to check if there are some extreme outliers in ZLP position, since I rarely see any energy shifts above +- 10 eV.

I see your point. It may make sense then to add a `spectrum_range` argument to `align_zero_loss_peak`. @magnunor, would you like to open a separate issue about it? An alternative—that would probably be the best option in most cases—would be to remove the spikes before aligning.

**Comment by magnunor** [comment]
I implemented a `signal_range` parameter: https://github.com/hyperspy/hyperspy/pull/544

Removing the spikes is usually the best approach, but I got some _very_ large datasets. So manually removing the spikes is too time consuming, simply narrowing down the energy range fixes most of the these issues.
