### ISSUE TITLE
hyperspy starting script doesn't work with IPython 3 notebook

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#541]
The main purpose of the `hyperspy` script is to setup IPython and traitsui to run properly with the chosen toolkit. It relies on the `--pylab` flag that was available for all IPython interfaces until IPython 3.0. However, the `--pylab` flag has been removed for the notebook in IPython 3.0 and, although it's still available for the other interfaces, [its usage is discouraged](http://nbviewer.ipython.org/github/Carreau/carreau.github.io/blob/master/posts/10-No-PyLab-Thanks.ipynb).

Currently this is what happens when executing `hyperspy notebook` if IPython > 3 is installed:

```
$ ana-hyperspy notebook
[E 16:07:15.695 NotebookApp] Support for specifying --pylab on the command line has been removed.
[E 16:07:15.695 NotebookApp] Please use `%pylab qt` or `%matplotlib qt` in the notebook itself.

```

Worst, when starting the "HyperSpy Notebook" entry in the Window file explorer context menu, the notebook doesn't start but there is no warning.

We could fix the issue by setting up the environment in an IPython profile, however I think that the `--pylab` flag is gone for good reasons and for the same reasons we should consider not providing the feature anymore when using the IPython notebook. With this is mind, this is the "fix" that I propose:

* Replace the "Start HyperSpy Notebook here" windows by "Start IPython Notebook here" and add "Start IPython QtConsole here" without replacing "Start HyperSpy QtConsole here".
* When using IPython > 3, simply start the IPython notebook without any flag and print a warning explaining the "hyperspy notebook" will be deprecated in the next release.
* Modify the documentation so that all the imports are explicit e.g.:
 ```python
 import numpy as np
 import matplotlib.pyplot as plt
 import hyperspy.hspy as hs

 ```

What do you think?

**Comment by to266** [comment]
I agree.

As a minor thing, many warnings should probably be given for the users less familiar with python and/or hyperspy structure - by that I mean that with your given explicit imports now suddenly they will have to rewrite all their scripts to use the hyperspy and/or will not know how to create signals (i.e. now suddenly `signals.Spectrum()` does not work, but you have to write `hs.signals.Spectrum()` instead)

Of course the alternative is to do what we did all the time (i.e. `from hyperspy.hspy import *` ), however I am aware that is very much so discouraged. 

Nevertheless, I think the change will be for the better and quite like your 'fix'

**Comment by pburdet** [comment]
It sounds good. Going in the same direction than issue  #494. It will make people more aware fo the different package of python. It will also make hyperspy more natural for python users.

**Comment by francisco-dlp** [comment]
Thank you for pointing to #494, somehow I missed that one!

**Comment by jrminter** [comment]
I've been playing with this today after upgrading the notebook... I have a few more items in my 'import list' than `francisco-dlp`. Here is my list, in case it helps porting old scripts. 

```
%matplotlib inline
import os
import numpy as np
import matplotlib.pyplot as plt
import hyperspy.hspy as hs
# set the default figure size
plt.rcParams['figure.figsize'] = 11, 7
```

I think the discipline of paying closer attention to imports will pay great dividends in the long term. Again, my thanks to those who are doing the "heavy lifting" developing hyperspy.

**Comment by pburdet** [comment]
Thanks John, I tried as well. I did a few things to run hyperspy with ipython 3.1:

I needed to change the Pyqt values of pyface (`C:\Anaconda\Lib\site-packages\pyface\__init.py__`) to 1:   `sip.setapi('QString', 1)` and `sip.setapi('QVariant', 1)`

I edited my ipython profile. I created a .py file in `C:\Users\pburdet\.ipython\profile_default\startup` containing:

```python
import numpy as np
import matplotlib.pyplot as plt
import hyperspy.hspy as hs
def figsize(x, y):
    plt.rcParams['figure.figsize'] = x, y
```
After running `ipython profile create` in the console, I modified the `C:\Users\pburdet\.ipython\profile_default\iypthon_config.py` to get `c.InteractiveShellApp.matplotlib = 'qt'`
