### ISSUE TITLE
Log scale on Y-axis

### ISSUE THREAD

**Issue by rgpdx** [hyperspy/hyperspy#543]
Currently in Hyperspy v0.8 there is no way to plot with Y-axis in log-scale. Can this be incorporated in a future version? Spectral data in linear scale is not always useful, and a semi-log plot is critical in many instances to clearly discern peaks and visualize/characterize the data for decision-making.

**Comment by francisco-dlp** [comment]
Currently pressing the "l" key with the spectrum windows on focus toggles the y axis log scale. Do you have in mind a more convenient way to perform the task? For example, something like this:

```python
s.plot(yscale="log")
```

**Comment by rgpdx** [comment]
My use case with Hyperspy will be to automatically take a bunch of
emsa files, plot them out and do some basic analysis on the files for
smoothing and peak detection. I want to put the plots into a pdf or in
a pptx file (using python-pptx) for automated reports. The kinds of
plots I look at are just easier to understand in semi-log scale and
therefore I'd like the feature to be something like what you stated
below -


s.plot(yscale="log")


is perfectly acceptable. Thank you for considering it.

**Comment by francisco-dlp** [comment]
Ok, we'll leave it in our wish-list waiting for some attention. In the meantime you could perform the task less conveniently as follows:

```python

import matplotlib.pyplot as plt
ax = plt.gca()
ax.set_yscale("log")
ax.figure.canvas.draw()

```

**Comment by rgpdx** [comment]
Francisco

Can you give me a py file I can use to try this out? I tried the following
code and it doesn't work for me. Am I missing something?

import hyperspy as hsp
import matplotlib.pyplot as plt
ax = plt.gca()
ax.set_yscale("log")
ax.figure.canvas.draw()
s = load('test_emsa.emsa')
s.plot()

**Comment by francisco-dlp** [comment]
Your script doesn't work because `ax.set_yscale("log")` modifies the y scale of the axes in the active figure, but you create the figure after setting the scale. The following works for me:

```python
import hyperspy.hspy as hs
import numpy as np
import matplotlib.pyplot as plt
%matplotlib qt


s= hs.signals.Spectrum(np.random.rand(100))
s.plot()
ax = plt.gca()
ax.set_yscale("log")
ax.figure.canvas.draw()

```
![example_log_scale](https://cloud.githubusercontent.com/assets/989719/7608741/2b893658-f964-11e4-9b1a-d423d9f46c94.png)

**Comment by rgpdx** [comment]
Yes, that worked. Thanks!
