### ISSUE TITLE
Default dtype for saving and float operations

### ISSUE THREAD

**Issue by AEljarrat** [hyperspy/hyperspy#55]
Dear all, 

This issue is about some numpy arrays that change dtype in between calculations to bigger types, making the following calculations more time consuming, and saving the data afterwards a lot more memory expensive.

My problem in particular is with FFT calculations in fourier_log_deconvolution, and kramers_kronig_analysis that produce complex128 ndarrays as output when the input is a float32 ndarray. For example, the deconvolved spectrum image (float64) will occupy the double than the original SI. This is annoying, but then again, when working with big SI, kramers_kronig_analysis will sometimes spend several minutes in one calculation only to get a memory error!

This issue, I think, is inherent of the FFT package in numpy, and I don't know (and haven't been able to find) an easy workaround to it.

A partial solution to this issue is piping the result of every FFT through astype. It improves a bit the speed and you get the float32 result, so when saving there is no problem. But I am not sure if the loss of precision involved is critical. 

An example of this(notice the astype at the ends and the operation in between with complex arrays):
        z = np.fft.rfft(zlp.data, n=size, axis=axis.index_in_array).astype('complex64')
        j = np.fft.rfft(s.data, n=size, axis=axis.index_in_array).astype('complex64')
        j1 = z \* np.nan_to_num(np.log(j / z))
        sdata = np.fft.irfft(j1, axis=axis.index_in_array).astype('float32')

old version (without astype):
CPU times: user 11.40 s, sys: 3.12 s, total: 14.52 s
Wall time: 14.80 s

new version (with astype):
CPU times: user 9.06 s, sys: 2.74 s, total: 11.80 s
Wall time: 11.99 s

My aim with this post was only to draw attention to the issue, not to propose this method as a solution. But, I will secretly put astypes in my copy of the code till a better solution appears :P 

cheers and happy new year to everyone!

EDIT

Also, the astype method does not produce the desired effect in harddrive space optimization. For instance, one spectrum image that occupies 37.1 Mb in float32, produces another spectrum image after deconvolution, also in float32. When saving this deconvolved SI, it weighted 70.7 Mb. Why this increase?

the worst is that after kramers_kronig_deconvolution (output=complex64, that is 2 times float32), the SI produced weights 284 Mb. Which is huge. 

So I have a data storage problem...

**Comment by tjof2** [comment]
I don't think this is really still an issue is it? Setting/changing dtype of the signal is easy enough, RAM and hard drive space is quite cheap nowadays, and HyperSpy currently uses numpy fft routines which continue to promote float32 to float64 (SciPy maybe offers an alternative but only in recent versions >= 1.4).
