### ISSUE TITLE
unicode problem with iPy notebook 3 on Windows using hyperspy 0.8.x

### ISSUE THREAD

**Issue by jrminter** [hyperspy/hyperspy#550]
I have been trying to migrate to iPython notebook 3. I also need to work on both Mac OSX (home) and Windows (lab). The current Anaconda distribution with `conda update all` works well on macOSX. On windows with the same Anaconda distribution I get this:

```
â”œâ”€â”€ Acquisition_instrument
â”‚   â””â”€â”€ SEM
â”‚       â”œâ”€â”€ Detector
â”‚       â”‚   â””â”€â”€ EDS
â”‚       â”‚       â”œâ”€â”€ azimuth_angle = 0.0
â”‚       â”‚       â”œâ”€â”€ elevation_angle = 35.0
â”‚       â”‚       â””â”€â”€ energy_resolution_MnKa = 130.0
â”‚       â””â”€â”€ tilt_stage = 0.0
â”œâ”€â”€ General
â”‚   â””â”€â”€ title = Paint Cross Section
â””â”€â”€ Signal
    â”œâ”€â”€ binned = True
    â”œâ”€â”€ record_by = spectrum
    â”œâ”€â”€ signal_origin = 
    â””â”€â”€ signal_type = EDS
```

I tried my .iPython profile from my mac on windows box with no difference. I also got the same problem when upgrading the binary release windows python (2.7.9) to iPython 3.1.0 from 2.4.1. I would appreciate any ideas on how to fix this.

**Comment by jrminter** [comment]
I should have mentioned that the binary distribution was `HyperSpy-0.8-Bundle-Windows-64bit.exe`

**Comment by jrminter** [comment]
The solution on Windows was to set an environment variable `PYTHONIOENCODING` to `UTF-8`
I found it on [stackoverflow](http://stackoverflow.com/questions/3828723/why-we-need-sys-setdefaultencodingutf-8-in-a-py-script). Last answer (big surprise...)

I had noticed that commit ` ad8022962f3fda25702fb46f1483bd8def29f347` by `to266` had suggested an approach I had seen before

```
import sys
reload(sys)
sys.setdefaultencoding('utf8')
```

I had tried this before. it worked for a while but then broke. Many on SO warn against this.  If the solution above doesn't break across a few branches, I'll close the issue.

**Comment by francisco-dlp** [comment]
Thank you for reporting this issue and providing a workaround. It may well be a bug on our side, we'll look into it.

**Comment by dnjohnstone** [comment]
So far this doesn't seem to have come back I don't think and probably isn't a HyperSpy issue anyway - can we close?

**Comment by jrminter** [comment]
Agree with D. N. Johnstone. Closing.
