### ISSUE TITLE
EDS-TEM quantification LABEL

### ISSUE THREAD

**Issue by Stefania862** [hyperspy/hyperspy#559]
Label on EDS maps 
<Image, title: atomic percent of Au, dimensions: (|100, 90)>

might be replaced by a shorter ones

**Comment by francisco-dlp** [comment]
Could you provide more details e.g. an example?

**Comment by dnjohnstone** [comment]
Did anyone ever figure out what was actually wanted here? e.g. which label is supposed to be made shorter? @Stefania862?

**Comment by dnjohnstone** [comment]
Having spoken with Stefania in person about this she can't remember what the issue was - so unless anyone else has a strong opinion on some labels I think we can close this...

**Comment by vidartf** [comment]
Reopen if someone still thinks it's an issue.
