### ISSUE TITLE
Windows opening in background (qt4 backend)

### ISSUE THREAD

**Issue by jat255** [hyperspy/hyperspy#560]
I realize that this might be an issue with PyQt4, rather than with HyperSpy (since it happens with other dialog boxes and such that I create), but every time that I create a window from an iPython notebook (e.g. `s.plot()` or something), it opens in the background rather than jumping to the front (like one would expect). Also, the windows open directly on top of one another, rather than tiled. This isn't a huge problem, but is a mild inconvenience to the user that does not necessarily reflect well on the program (making it appear more 'beta'-like than it actually is). 

So I guess this is two issues that I thought could be discussed:
1. Windows open in the background, requiring a click on the taskbar to bring them into focus.
2. Windows open on top of each other, rather than tiled so they are displayed nicely to the user, requiring the user to drag them around to see what is in each window. This gets to be a pain with a function like `plot_decomposition_results()` that creates 4 windows.

Note, all of this is on Windows 8.1 using 64-bit python with PyQt4 4.11.3 installed, using the 0.8 release of Hyperspy.

**Comment by jat255** [comment]
I'll also add that this behavior occurs when running from `hyperspy console` as well as in the notebook, so it is not specific to the iPython notebook.

**Comment by francisco-dlp** [comment]
Those are good points.

The focus issue doesn't affect Linux systems as far as I know. Also, I suspect that the focus problem affects other toolkits in Windows and possibly also MacOS, although Windows and MacOS users should confirm this. May a solution be found [here](http://stackoverflow.com/questions/8202228/make-matplotlib-plotting-window-pop-up-as-the-active-one)?

Regarding the window placement, HyperSpy doesn't attempt to manage it at all, this is (not) done by matplotlib. I agree that it'll be very nice to improve on this directions. This [SO post](http://stackoverflow.com/questions/7449585/how-do-you-set-the-absolute-position-of-figure-windows-with-matplotlib) is relevant to this discussion. For windows they suggest to use [PyFig](https://pypi.python.org/pypi/Pyfig/).

**Comment by jat255** [comment]
With regards to the focusing of windows, I did some exploration with PyQt4, and it appears the following code will bring an input window to the front (this is an example where I'm writing a simple gui to get a value from the user):

```python
app = QtGui.QApplication(sys.argv)
input_d = QtGui.QInputDialog()
input_d.activateWindow()
input_d.raise_()
smoothing_parameter = input_d.getDouble(None,
                                        'Input dialog',
                                        'Enter smoothing',
                                        decimals=2,
                                        value=0.05)
```

I am not sure if or where the Qt code is utilized within Hyperspy, since it sounds like `matplotlib` is probably doing a lot of the heavy lifting. As suggested in that first SO link that @francisco-dlp included, it looks like the `raise_()` command can be accessed by `get_current_fig_manager().window.raise_()` within `matplotlib`. Perhaps this is worth exploring?

**Comment by thomasaarholt** [comment]
matplotlib v2.0 fixes this.
Try it with hyperspy: `pip install https://github.com/matplotlib/matplotlib/archive/v2.x.zip`

**Comment by ericpre** [comment]
Matplotlib is managing the focus of figure windows and this is backend and platform dependent. Hyperspy shouldn't deal with this and I don't think there is much we can do!
