### ISSUE TITLE
Add `Model.components.<component name>` attribute as an alternative to Mode["<component name>"]

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#569]
Currently there is `__getitem__` so that one can do the following:

```python

>>> s = signals.Spectrum(np.empty((10, 20, 30)))
>>> m = create_model(s)
>>> m.append(components.Gaussian())
>>> m["Gaussian"].A.value
1.0
```

What I propose is to implement

```python
>>> m.components.Gaussian.A.value
1.0
```

The advantage is that with the latter we can enjoy IPython's tab completion. If this gets implemented then we can get rid of the ugly functionality that add the EELSCLEdge component variables to the user namespace automatically.

What do you think?

**Comment by francisco-dlp** [comment]
Thinking about it the following will probably be better:

```python

m.components.Gaussian.A.value

```

I'll update the header.

**Comment by pburdet** [comment]
It sounds good

**Comment by to266** [comment]
Do you want to replace the model structure, or just create a new additional way to reference the components? (meaning do you want to remove `m[0]` way of referencing)?

**Comment by francisco-dlp** [comment]
That's a good question. Here I was simply proposing to add a new attribute `Model.components` with a `__getattr__` method that should enable easier component setup when working in IPython. However, I agree that `Model` may benefit from some drastic redesigning to make its structure more intuitive and simple. For example, why inheriting from `List` when actually the order of the components in the list should make no difference?

**Comment by to266** [comment]
In the end the functionality we need from the `list` is not the order of the components (which is useful, as you can always reference "the last component you added", or the "first", etc.), but:

1. adding things 
2. removing things

So `tuple` does not work (as you cannot remove things, only add), but a `set` might. (A dictionary would work as well, but I feel it's just an overkill). On the other hand, you cannot slice sets (BAD) , but you can use set operations on it (intersection / difference / union /...) (not sure if worth it).

Also, from the set you cannot access the components themselves, you can only check if they actually are in the set.

Unless of course we don't want to base the model on any existing structure. But then we should at least come up with very good reasons (i.e. things that will be easier / better / faster to run / are not possible to implement now) to overhaul the structure

**Comment by francisco-dlp** [comment]
I agree that, in hindsight, it would have been better to base Model in `set`. I think that set operations should indeed be worth the burden. Would you like to open a separate issue about this?

**Comment by francisco-dlp** [comment]
(I'm adding this to the 0.8.1 milestone because, once this is implemented, we're going to deprecate the code that injects variables in user namespace, so it'll be good to present the users with the alternative.)
