### ISSUE TITLE
Automatically detect linear fitting problems

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#574]
It'll be useful to add an `is_linear` attribute to `Parameter` so that, if at fitting time all parameters are found to be linear it fits using least squares instead of non-linear least squares. This should dramatically increase the fitting speed in those cases.
## TODO

[ ] Add `is_linear` attribute to all components.
[ ] Add linear least squares to fitters
[ ] Automatically use linear least squares when the problem is found to be linear
[ ] User Guide documentation
[ ] Docstring documentation
[ ] Tests

**Comment by tjof2** [comment]
See #1453 and #1462.

**Comment by thomasaarholt** [comment]
I've taken this up again as of this week. The fitting algorithm works, but not yet with convolution. I'd really enjoy it if someone would check out the PR (#1462), where I've merged the linear_parameters PR.

**Comment by tjof2** [comment]
See #2422 to replace the above links
