### ISSUE TITLE
Moving out of Sourceforge

### ISSUE THREAD

**Issue by to266** [hyperspy/hyperspy#575]
Hi,

Currently our windows install bundles are hosted on sourceforge, and with their recent activities I suggest thinking about alternatives. The problem is that (please correct me if I'm wrong though) we don't actually have any budget for hosting, and our bundles are quite sizeable (~400MB each).

So far the best list of alternatives I've found seems to be here:
https://helb.github.io/goodbye-sourceforge/

Lets discuss it, maybe we'll come up with decent solutions :)

**Comment by jat255** [comment]
I know that Github has a built-in release system (that we are already [using](https://github.com/hyperspy/hyperspy/releases)) that allows hosting of binary files up to 1GB in size. Would this be a possibility?

See [here](https://help.github.com/articles/distributing-large-binaries/) for more info.

**Comment by to266** [comment]
Yep, that's the preferred possibility. I guess the size limit used to be too small for us, hence we picked sourceforge? Anyway, I updated the 0.8 release with the binaries, and things seem to work fine

**Comment by francisco-dlp** [comment]
Good point, I have just updated the download links to point to GitHub. If we experience no issues and nobody has anything against it, I'll proceed to delete the SourceForge account in ~one week.

**Comment by to266** [comment]
I believe we can proceed with the "delete sourceforge", as things seem to go smoothly :)

**Comment by vidartf** [comment]
Bumping this as SourceForge is still around.

**Comment by francisco-dlp** [comment]
I've just noticed that the download rate of the bundle from github is actually pretty slow. It takes ~10min to download the bundle. I don't know if this is a temporary issue, but if it is not, should't we reconsider hosting in sourceforge? Note that winpython still uses sourceforge, and I bet that the download rate is the reason.

**Comment by tjof2** [comment]
Is this still an issue?
