### ISSUE TITLE
Add saving options for .tiff files

### ISSUE THREAD

**Issue by Divitini** [hyperspy/hyperspy#593]
It would be useful to add an option for bit depth in the "save" function. Currently the data (coming from a spectrum image) are exported with the same bit depth than the processed data they come from, often resulting in 64-bit .tiff files. Although this is the correct behaviour in principle, only 32-bit .tiff files are commonly used and compatible with other software.
The issue has been experienced by several users; it can be avoided by changing the data type before saving, but a different saving option would be more user-friendly and allow more flexibility of use.

**Comment by francisco-dlp** [comment]
Very good point, I have added this to the wish list. Thanks!

**Comment by tjof2** [comment]
Is this included in tifffile?

**Comment by francisco-dlp** [comment]
No. Would adding a warning when saving to 64bit tiff files be enough?

**Comment by tjof2** [comment]
I guess so. annoying though.
