### ISSUE TITLE
HyperSpy 0.8.1

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#609]
I think that it is above time that we release HyperSpy 0.8.1 given the number of important issues that have been reported and fixed. Also, worryingly, #541 is probably discouraging a good number of prospective users and a fix has been pull requested #564. What do you think about setting the release date to Friday the 31st of July?  

TODO
--------

* [x] Review all [pending pull requests](https://github.com/hyperspy/hyperspy/pulls?q=is%3Aopen+is%3Apr+milestone%3A0.8.1)
* [x] Upload documentation
* [x] Upload to pypi
* [x] Create Windows installer and upload to github
* [x] Update website
* [x] Upload website
* [x] Send release message to mailing list

**Comment by francisco-dlp** [comment]
I suggest to postpone the release until all authors have the chance to verify that their contributions are well represented in CHANGES and in the releted GitHub issues, see #673. A compiled version of the current docs can be found [here](http://hyperspy.org/hyperspy-doc/dev/index.html).

Is everybody fine with waiting until Tuesday next week for this?

**Comment by francisco-dlp** [comment]
We'll finally release tomorrow. Everything should be ready on the coding side but we don't want to rush the last bit just in case...

**Comment by vidartf** [comment]
Weee! :+1:
