### ISSUE TITLE
Context manager for unfold/fold

### ISSUE THREAD

**Issue by vidartf** [hyperspy/hyperspy#615]
Several places in the code we use the pattern
```python
unfolded = signal.unfold()
... Do what is needed ...
if unfolded:
    signal.fold()
```

I'm proposing to add a context manager to ease this pattern, with the added benefit of making the code more robust to exceptions in the middle part:
```python
with signal.unfolded():
    ... Do what is needed ...
```
where the signal would automatically refold (if needed) when exiting the code block.

**Comment by francisco-dlp** [comment]
I'm +1 on this.
