### ISSUE TITLE
Prevent ignore of DeprecationWarnings

### ISSUE THREAD

**Issue by vidartf** [hyperspy/hyperspy#627]
In hyperspy we try to warn the user of deprecations by using `warnings.warn` with `DeprecationWarning`. However, [its doc says](https://docs.python.org/2/library/warnings.html#updating-code-for-new-versions-of-python):

> Having certain warnings ignored by default is done to prevent a user from seeing warnings that are only of interest to the developer. [...] While you as a developer want to be notified that your code is using a deprecated module, to a user this information is essentially noise and provides no benefit to them.

For most users, this does not fit with how hyperspy is used (the users are typically scripting, making them "developers" for the purposes of this discussion).

There are several option for how to deal with it:
 - The users could of course fix this themselves by setting their own warning filter, but that is cumbersome, and defeats the helpfulness of the warnings.
 - We could bypass this by not using `DeprecationWarning` and similar for this. We could then either use the default type `Warning` or use numpy's `numpy.VisibleDeprecationWarning`, or make our own.
 - We could change the warning filter when launching hyperspy (qtconsole, notebook etc.)
 - We could change the warning filter on import of hyperspy.hspy
 - We could change the warning filter on import of hyperspy (`hyperspy.__init__.py`).

Personally, I think I would prefer option two with our own warning class hyperspy.(Visible)DeprecationWarning (as using numpy's class can cause confusion with regards to the source of the warning), while still enabling the suppression of other deprecations (hyperspy's dependencies and similar).

**Comment by francisco-dlp** [comment]
I am +1 on @vidartf proposed solution: our own `VisibleDeprecationWarning`.

**Comment by to266** [comment]
https://github.com/hyperspy/hyperspy/pull/657
