### ISSUE TITLE
spectrum.find_peaks1D_ohaver() when a datapoint is zero

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#628]
The following code with [this](http://folk.ntnu.no/magnunor/r4535h4t35345nh43n5h43tn5h34tn5h34/dataset.hdf5) dataset does not work:

> s = load("dataset.hdf5")
> s.find_peaks1D_ohaver()

It causes a `hyperspy/misc/spectrum_tools.py:133: RuntimeWarning: divide by zero encountered in log10` and the terminal becomes unresponsive. And HyperSpy uses 100% of one of the CPU cores.

The following works:

> s = load("dataset.hdf5")
> s.data = s.data + 0.0000001
> s.find_peaks1D_ohaver()

**Comment by francisco-dlp** [comment]
Thank you for reporting this bug. Is anybody available to work on this before the 0.8.1 release?

**Comment by vidartf** [comment]
I had a look at the offending code, and have to say I'm not able to follow it. From the docstring this code seems like it has been lifted from somewhere else, perhaps we should look around and check whether there is an existing fix at the source?

**Comment by francisco-dlp** [comment]
@vidartf, I think that the original author of the code, @msarahan, translated the code from the MATLAB code that can be found [here](http://terpconnect.umd.edu/~toh/spectrum/PeakFindingandMeasurement.htm). Those were HyperSpy's early days. Today I would inclined to think that a peak finding routine does not belong to HyperSpy. Of course the same can be said of many parts of the code and, indeed, if we're serious about seeking adoption from beyond the EM community, we should start considering splitting HyperSpy into separate projects. For example: io plugins to a Python microscopy file format repository, EELS code to an EELS repository etc...

**Comment by magnunor** [comment]
This fixes it for my dataset at least: https://github.com/magnunor/hyperspy/commit/3957ea6d907e03daa4714baa965ba55e0669ddf9

But I think we should use something from scipy/skimage/... instead for future versions.
