### ISSUE TITLE
Delay the 0.8.1 release by a week

### ISSUE THREAD

**Issue by to266** [hyperspy/hyperspy#641]
It seems there are a number of important issues that we are very close to fixing, however they are still not there. @francisco-dlp and I propose to delay the release to the next Friday (7th of August). Hopefully most of the critical pieces will be there by the time, and everyone else can also finish up and/or polish whatever they are working on if they did not have the time.

Aye / nay? :)

**Comment by magnunor** [comment]
Aye! Sounds good to me. Better to have stuff sorted out than rushing it.

**Comment by jat255** [comment]
I agree, it seems it would be better to wait a week and have more features than leaving them in 0.8.x or 0.9 and delaying their introduction to users.

BTW, is anyone from this team planning on attending the [M&M](http://conference.microscopy.org/MandM/2015/) meeting next week? I'll be there and figured I'd check.

**Comment by to266** [comment]
While not a developer, I believe [Sean](http://www-hrem.msm.cam.ac.uk/people/collins/) will be there. For what it's worth, he is a rather experienced hyperspy user.
