### ISSUE TITLE
default colormap is jet

### ISSUE THREAD

**Issue by to266** [hyperspy/hyperspy#660]
Somewhere along the various merges (I guess) the matplotlib preferences were not updated as required

**Comment by francisco-dlp** [comment]
This was intentional, sorry for not having written about this: I think that it is not HyperSpy's business to change the default mpl cmap. We could do have the same effect by setting ``Image.plot(cmap="gray") as the default. Should we go for this?

**Comment by to266** [comment]
Hm, not necessarily. I'd prefer to incorporate seaborn package for the sane colours, but in the end it's users choice. Though defaulting to something sane (i.e. with obvious luminosity profile) would be/was nice

**Comment by francisco-dlp** [comment]
It seems that at MPL they'll [update the default styles](http://matplotlib.org/style_changes.html) for version 2.0 so I suggest that we wait to see if we like the new ones more and, if we still don't, we can then consider seaborn.

Should we go for the `Image.plot(cmap="gray")`` solution for this release?

**Comment by to266** [comment]
I think it's not necessary, thanks

**Comment by francisco-dlp** [comment]
Let's leave this open in case that some else wants to express their opinion. However, if this is to go in 0.8.1 they'll have to hurry up...

**Comment by pburdet** [comment]
Mmmmh good looking default images are important for advertisement purpose. I think Hyperpsy can have its own visual identity, not depending on MPL. A software using jet as default colour (and in its documentation) is not attractive for me. Too aggressive. I think gray is the best default choice.

**Comment by francisco-dlp** [comment]
+1 for setting the default cmap in ``Image.plot``

**Comment by to266** [comment]
additionally, with `jet` the navigator selector square (whatever it's called) is not visible on most of the plots... At least for me

**Comment by to266** [comment]
#671
