### ISSUE TITLE
%hyperspy inline broken

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#682]
```python

>>> %hyperspy inline
Gtk-Message: Failed to load module "canberra-gtk-module"
UsageError: Invalid GUI request u'inline', valid ones are: pyglet, osx, qt5, qt, glut, gtk, gtk3, tk, wx

```

**Comment by to266** [comment]
Not broken - just not supported, as it is not a valid backend, just plotting preference. I don't think it even makes sense to support it, given we are going for clarity, just to set-up hyperspy backends correctly and for users to be as much aware of python as possible. If the `inline` option was available, it would add another obscurity layer... And it's not even essential for hyperspy.

**Comment by francisco-dlp** [comment]
I fully agree. Closing.
