### ISSUE TITLE
Add support for FEI emd file format

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#698]
The file format turns out to be standard HDF5. A file containing 4 images in this format can be downloaded from the link in [this post](https://groups.google.com/d/msg/hyperspy-users/voA3eutSPG4/-ismMx0SBwAJ)  in the HyperSpy users mailing list.

Thank you Mingjian Wu for drawing our attention to this and providing the file.

**Comment by magnunor** [comment]
Nice! I've actually been in contact with Colin Ophus before, discussing the EMD-format. They've got a project here: http://emdatasets.lbl.gov/view/

This is a very nice development, which avoids the tedious reverse-engineering usually associated with data from these kinds instruments. Hoping the other manufactures follow suit :)

**Comment by magnunor** [comment]
Do we know who is developing this at (or for) FEI? Would be nice to directly communicate with them.

**Comment by francisco-dlp** [comment]
[This suggests](https://www.enthought.com/company/news/nthought-canopy-helps-fei-revolutionize-transmission-electron-microscopy) that Enthought has been involved in the development.

**Comment by magnunor** [comment]
There is also an example file from Colin here: http://emdatasets.lbl.gov/category/emd-examples/ , but that is probably slightly different from the FEI one, according to Mingjian Wu.

**Comment by francisco-dlp** [comment]
Given the similarities between Colin's hdf5 format and HyperSpy's one, it should be simple to support that one too. @magnunor, would you like to open an issue about this?

**Comment by magnunor** [comment]
I opened an issue about it: https://github.com/hyperspy/hyperspy/issues/699

**Comment by francisco-dlp** [comment]
New example files kindly provided by Mingjian Wu can be downloaded from the link in [his post in the mailing list](https://groups.google.com/d/msg/hyperspy-users/voA3eutSPG4/xrJ_-teVIgAJ).

**Comment by francisco-dlp** [comment]
By the way, if somebody plans to start working on this, please mention it here before starting so that we don't get several of us working on it at the same time.

I can't commit to this at the moment but I'll be happy to help anybody who wishes to give it a try.

**Comment by magnunor** [comment]
I can try to implement a reader for this and the NCEM one https://github.com/hyperspy/hyperspy/issues/699 . Unless someone else wants to :)

Timeframe: about a week for basic functionality

**Comment by francisco-dlp** [comment]
Great. Once there is a PR, if everybody agree, we can set its milestone 
to 0.8.3.

**Comment by magnunor** [comment]
I've started on the implementation here: https://github.com/hyperspy/hyperspy/pull/710

**Comment by henklaak** [comment]
Hey people. I know I'm very late on this, but I could get you in touch with the actual developers of the EMD files at FEI. I used to be one myself. Gimme a shout when you still need it.

**Comment by ericpre** [comment]
FEI finally got a _usable_ version of Velox with basic functionalities. The need to be able to read these files may come fairly quickly.

We need to sort out the compatibily between the different velox version. I have files generated with velox v1.3 and velox v1.4. These files are significantly different from the ones created with the python velox, for which @magnunor implemented an io reader.

How should we proceed? @henklaak, would you able to contribute to this? If so, that would be great! Anybody else got an update on this?

**Comment by magnunor** [comment]
Is the new "FEI EMD" file format still based on HDF5? If yes, that simplifies everything.

**Comment by ericpre** [comment]
Yes, the format is still hdf5, but what they put inside changes quite a bit!

**Comment by robindegen** [comment]
I'm one of the developers for FEI EMD. I can tell you it's based on HDF5 1.10+. The format itself is however still in constant improvement, so be aware of this when implementing support for this.

I'm not sure how much I'm allowed to contribute to this; I'd have to discuss this internally.

**Comment by robindegen** [comment]
@magnunor I've been given a green light to help out where needed. If you have any questions about the file format, just let me know.

**Comment by magnunor** [comment]
@robindegen, very nice that you're helping out with this! That makes the implementation much easier, and the functionality better!

As you might have guessed from https://github.com/hyperspy/hyperspy/pull/1662, I'm not really involved with the implementation of the reader itself. (As I do not work on a TEM with Velox).

But I might assist in getting the annotations loaded correctly, as I've been working on the HyperSpy marker functionality, and working on getting DM-annotations working correctly in this framework: https://github.com/hyperspy/hyperspy/pull/1491

**Comment by ericpre** [comment]
Done in #1662.
