### ISSUE TITLE
Add support for EMD-file format from NCEM

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#699]
EMD (Electron Microscopy Dataset) is a file format based on HDF5, developed at National Center for Electron Microscopy: http://emdatasets.lbl.gov/spec/

It should be fairly easy to implement a reader for it, since it is a standard HDF5-file.

FEI is also making a EMD-format: https://github.com/hyperspy/hyperspy/issues/698 . So the readers will have to distinguish between the two.

**Comment by magnunor** [comment]
I've been in touch with the maintainer of http://emdatasets.lbl.gov/ about getting some test-files for implementing this, since currently there is only one outdated file: http://emdatasets.lbl.gov/category/emd-examples/

**Comment by magnunor** [comment]
FDES (https://github.com/woutervandenbroek/FDES) a TEM/STEM simulation software also uses this kind of EMD-files as output format. I'll see if can get some output-files so we can make sure they work nicely in HyperSpy.

**Comment by francisco-dlp** [comment]
It seems to me that the hspy hdf5 format is a valid EMD format except for some details e.g. the versioning. Am I wrong?

Wouldn't it be make sense to have a general EMD reader which simply reads all the datasets in the file and sets the `original_parameters` attribute properly? Then, adding "full support" would involve, in simple cases (the hspy format not falling in this category), just mapping from `original_parameters` to `mapped_parameters`.

**Comment by magnunor** [comment]
I think you're right, the only thing which is needed to have a valid EMD-file is having the right attribute tags + a dataset called "data"

That should work, but I think we should separate the FEI and NCEM version in two different readers since they look quite different.

In addition there are two different versions of the NCEM, 0.1 and 0.2. The 0.2 version is a little less strict, so waiting for Colin to generate some sample files.

**Comment by magnunor** [comment]
Firstly, a big thanks to @CodeMonkeyJan for implementing support in the https://github.com/hyperspy/hyperspy/pull/813 pull request.

A small on update on the EMD-project:

They've open sourced their EMD viewer, which is implemented in C++ and Qt: https://github.com/pophus/emdviewer. Also a reader/writer for EMD, written in C++: https://github.com/pophus/emdlib. 

The project webpage at http://emdatasets.lbl.gov/ is down at the moment, but should be back up soonish.

**Comment by to266** [comment]
FYI #953 is merged now.

**Comment by CodeMonkeyJan** [comment]
Thanks a lot :-)!

**Comment by magnunor** [comment]
Very nice!

I guess we can close this issue?
