### ISSUE TITLE
FEI reader fails when loading single spectrum

### ISSUE THREAD

**Issue by msarahan** [hyperspy/hyperspy#7]
https://bitbucket.org/francisco/hyperspy/issue/33/fei-reader-fails-when-loading-single

**Comment by ericpre** [comment]
Is this still a bug? There are two tests files containing single spectrum, which were added in #883 and they seem to be working OK.

However, I can't see the issue on bitbucket, because it doesn't seem to be public, so I am not very sure what it is about...

**Comment by francisco-dlp** [comment]
That's interesting as I don't remember anybody fixing this. However, it may well be that the single spectra files that we tested this on were simply faulty and, therefore, this has never actually been a bug. Have you tested single spectra loading with other files?

**Comment by ericpre** [comment]
No I haven't tested other files.

**Comment by tjof2** [comment]
Is it still a bug?

**Comment by ericpre** [comment]
I don't think we can reproduce it, so I would suggest to close it.
