### ISSUE TITLE
Load .vasp-files as image_simulation signal

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#707]
Many people use DFT to simulate/relax atomic structures, and one possible output from this is 3D-atomic positions. For example: https://github.com/cryos/avogadro/blob/master/testfiles/VASP-5.2-POSCAR.vasp

It would be nice if HyperSpy could load these files as image_simulation signals, and visualize them.

Since the files are flat text-files, is it should be fairly easy. The data could be turned into raster data using scipy.interpolate.griddata, and the intensity for each atom could be proportional to its atomic number. The image_simulation class could then contain a Gaussian convolve function to "simulate" experimental broadening.

**Comment by magnunor** [comment]
https://github.com/hyperspy/hyperspy/pull/868

**Comment by ericpre** [comment]
Moved to atomap, see #868.
