### ISSUE TITLE
user guide for MAC install incomplete

### ISSUE THREAD

**Issue by to266** [hyperspy/hyperspy#709]
As per users mailing list, the hyperspy installation instructions for a mac are at least incomplete. Instructions for other platforms may also require a better formulation (I haven't checked if they actually do).

**Comment by ericpre** [comment]
Installation instructions for Mac are good enough now:
http://hyperspy.org/hyperspy-doc/current/user_guide/install.html#quick-instructions-to-install-hyperspy-using-anaconda-linux-macos-windows
