### ISSUE TITLE
align2D can introduce artefacts in the images

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#731]
Currently `Signal.align2D` uses spline interpolation to shift the images. While this is fine in some cases, in others (e.g. when SNR is poor) it can introduce artifacts such a negative values and spurious oscillations. A better choice could be linear interpolation.

**Comment by francisco-dlp** [comment]
#730 attempt to fix this by using to linear interpolation instead.

**Comment by vidartf** [comment]
Changing the default is ok, but maybe it is better to also add a keyword argument that can be passed along when needed? Only down-side is that the argument lists for the functions get longer. If that is a concern we could potentially pu it as a hyperspy preference.

**Comment by francisco-dlp** [comment]
Thanks, I have added an `interpolation_order` argument to `align2D`

**Comment by vidartf** [comment]
#730 is set to submitted for pull to master, while this issue is on the 0.8.3 milestone.

**Comment by francisco-dlp** [comment]
Waiting for @dnjohnstone to resubmit a fix.
