### ISSUE TITLE
Align 2D should apply Sobel filter before Hanning filter

### ISSUE THREAD

**Issue by vidartf** [hyperspy/hyperspy#739]
Currently, `hyperspy.misc.image_tools.estimate_image_shift` applies the hanning filter before the sobel filter. This means that a lot of spurious edges will be made, as the gradient of the hanning creates concentric circles in the intensity, making the shift estimation error prone. If instead the hanning filter is applied last, the registration becomes much more accurate.

[Relevant lines in code](https://github.com/hyperspy/hyperspy/blob/master/hyperspy/misc/image_tools.py#L151-L156):
```python
if hanning is True:
   im *= hanning2d(*im.shape)
if medfilter is True:
    im[:] = sp.signal.medfilt(im)
if sobel is True:
    im[:] = sobel_filter(im)
```
Switch to:
```python
if medfilter is True:
    im[:] = sp.signal.medfilt(im)
if sobel is True:
    im[:] = sobel_filter(im)
if hanning is True:
   im *= hanning2d(*im.shape)
```
I think that this will also improve the median filter, but I'm not exactly sure how that works, so the effect on that needs to be checked.

**Comment by francisco-dlp** [comment]
It makes sense, would you like to send a PR?

**Comment by vidartf** [comment]
PR'd as #752.
