### ISSUE TITLE
[Website] Gitter sidecar chat

### ISSUE THREAD

**Issue by to266** [hyperspy/hyperspy#742]
Hi, so there is this thing:
https://sidecar.gitter.im/

Would you guys think it useful? Either for quick chat amongst ourselves, or for the users to quickly ask simple questions?

**Comment by magnunor** [comment]
Might be useful, we can try it and see how it turns out.

**Comment by francisco-dlp** [comment]
Very  cool!

I suggest that we don't close this issue until we

* [ ] Add a badge to the homepage.
* [ ] Mention it in the support section.
* [ ] Add a badge to README. The automatic one does not fit well with the ones already in.

**Comment by francisco-dlp** [comment]
I have just added the following two points to the TODO list:

* [ ] We announce this in the website news.
* [ ] We announce it in the forum.

**Comment by to266** [comment]
I've added it to the website repo (https://github.com/hyperspy/hyperspy-website/commit/f2250da063ccadfe11f091567c7437f90ecb79cd), however I have no clue how to actually make it visible in the website itself.
So the first two points are done, I guess? It certainly does not break anything, so at least that's great :)

**Comment by to266** [comment]
For the sake of doing things nicely, I've reverted the commit and created a proper PR: https://github.com/hyperspy/hyperspy-website/pull/10

**Comment by vidartf** [comment]
Reopen if still not fully resolved.
