### ISSUE TITLE
Implement logging

### ISSUE THREAD

**Issue by vidartf** [hyperspy/hyperspy#749]
Depending on your situation, you might want varying degrees of output from hyperspy (and its dependencies). Currently, the code includes the sporadic `print` statements, but its use is inconsistent, as highlighted in PR #748. A better alternative would be to use the [standard logging package](https://docs.python.org/2/library/logging.html), as that allows for a grading of importance of messages, which can then be filtered before being displayed to the user. It would also ease development, as a detailed/verbose output can help when debugging and/or trying to understand exactly what something does.

In the short term, this would only affect how `print` statements are removed (i.e. replaced by logging calls), but in the long term this would hopefully also include new logging statements in existing code. The most important logging level to include would be `information`, as that would serve best to replace today's print statement. Also, `critical`/`error`/`warning` is already handled by exceptions/warnings. Then `debug` could be added slowly over time (unless someone volunteers for performing an overhaul).

Specifically, I'd suggest using named loggers:
> A good convention to use when naming loggers is to use a module-level logger, in each module which uses logging, named as follows:
> `logger = logging.getLogger(__name__)`

**Comment by francisco-dlp** [comment]
Good proposal, I fully agree.

**Comment by to266** [comment]
Agreed

**Comment by vidartf** [comment]
While I think most current `print` statements can fit well with the standard logging levels, we should consider if there are any custom log levels that we want to add (especially if the current `print` statements would fit better into these levels).

I see that some people like to add full tracing (function entry/exit) on the debug level. If we do something similar, I think it should be added below the `DEBUG` level (e.g. a custom level `TRACE`). We might also consider another level between `INFORMATION` and `DEBUG` which can give user relevant information that would normally flood the log (e.g. a custom `VERBOSE` level).

If such custom levels are not appropriate for the current `print` statements, then changing the current code is simple (search and replace with `INFORMATION` level, possibly with `WARNING` level for a few). Either way I think we should establish a convention/guideline for future additions early on to keep things consistent.

**Comment by vidartf** [comment]
This should supersede `hyperspy.messages`.

**Comment by dnjohnstone** [comment]
@vidartf Is this one done now? I thought #877 would close this, or did I miss something that remains to be done?
