### ISSUE TITLE
Importing of EDAX EDS data

### ISSUE THREAD

**Issue by jat255** [hyperspy/hyperspy#756]
Having recently acquired an EDAX EDS/EBSD system, it has made me realize that there is no simple way to read the EDAX .spd (maps), .spc (spectra), and .ipr (image) files produced by EDAX's TEAM software in Hyperspy. 

I contacted EDAX applications and they provided me with the binary specifications for each of these files, so it shouldn't be too tricky to be able to implement at least read (and maybe even write) functionality for these formats. 

Apparently I cannot upload these documents without write permission to the repo, but they are available here: https://umd.box.com/s/nf4eqti4g07b76hh9zud25h6y1b6mmht

I am going to begin working on this in the next few days and will create a PR when I have some progress, but I wanted to put this issue here so we had a record of it. Any suggestions or tips would be be appreciated!

**Comment by vidartf** [comment]
Congratulations on the new instrument, and neat that you were able to get the specs on the file formats.

> Any suggestions or tips would be be appreciated!

Not sure what you have experience with or not, so to cover the basics first, its best to do the reading in as few operations as possible, and then process it inbetween reads. The formats seem (from a cursory look) to at least have simple headers, and not too much complicated stuff per file. Try either numpy binary routines, and/or the [`struct` standard library](https://docs.python.org/2/library/struct.html). From there it's just to pack everything into a signal `dict` somehow, but there I think others / existing code is a better help than me :)

**Comment by jat255** [comment]
@vidartf, thanks for the comments. I know the spd map files are just raw files with an additional header, so I may be able to offload some of the work to that plug in. I'm looking through the other i/o plug-ins to get a sense for the best way to approach it. I'll send a PR fairly early on so people can comment if it looks like I'm headed a bad direction.

**Comment by to266** [comment]
[SpcMap-spd file format.pdf](https://github.com/hyperspy/hyperspy/files/29505/SpcMap-spd.file.format.pdf)
[SPECTRUM-V70.pdf](https://github.com/hyperspy/hyperspy/files/29506/SPECTRUM-V70.pdf)
[ImageIPR.pdf](https://github.com/hyperspy/hyperspy/files/29507/ImageIPR.pdf)


Just for reference, I've uploaded pdf versions of the files @jat255 attached. They were converted using libreoffice from .doc, so the formatting may be off in some cases, but generally you can understand things.

In addition to excellent @vidartf suggestions, our [mrc](https://github.com/hyperspy/hyperspy/blob/master/hyperspy/io_plugins/mrc.py) file reader employs the numpy binary reading, if you want an example.

**Comment by jat255** [comment]
Thanks for the comments. Looking at the mrc reader, I've decided to try to emulate it. I'm trying right now just to practice reading values from an .spc file using numpy's `fromfile`. I've gotten through a few of the data fields, but I'm having some trouble reading a text string. Hopefully someone has some pointers that could help...

Here's the test code:
```python
spc_fn = 'Live Map 1.spc'
spc_F = open(spc_fn,'rb')
spc_F.seek(0)
print np.fromfile(spc_F, dtype='<f4', count=1)
print np.fromfile(spc_F, dtype='<f4', count=1)
print np.fromfile(spc_F, dtype=(np.str_,8), count=1)
print np.fromfile(spc_F, dtype='<u2', count=1)
print np.fromfile(spc_F, dtype=(np.str_,1), count=1)
print np.fromfile(spc_F, dtype=(np.str_,1), count=1)
spc_F.close()
``` 

And the output:
```python
[ 0.61000001]
[ 1.]
['\xdf\x07\x1c\n \x0b\x00!']
[2015]
['\x1c']
['\n']
```

According to the specification, this should be:
```
file format version (32 bit float)
application version (32 bit float)
file name (64 bit char array)
collection date struct: {
    16 bit int year, 
    8 bit char day, 
    8 bit char month
}
```

The floats and the ints that are read look correct, but the char arrays appear to be encoded as hex strings (I think?). I am very unexperienced with reading binary files, so hopefully there is a simple solution to get these values read in correctly. Any ideas?

**Comment by to266** [comment]
I'm not exactly experienced with reading binary files either, but in python most problems with strings are usually encoding and decoding errors. 

I've had a quick go at solving it, but could not figure it out - maybe I did not create an appropriate copy of the file to read from? Anyway, try reading the strings as other encodings (I assume the default is either `utf8` or `ascii`, and the latter should be avoided if possible). I think windows in particular prefer `latin1`..

oh and the `\xdf` are not hex, they are just bytes in string, in particular `ord('\xdf') = 233`. Hex have `0x` at the start :)

**Comment by AndrewHerzing** [comment]
The following code works to read the .SPD files from the EDAX TEAM software.  The output variables are a dictionary of the metadata contained in the files header and a 3D numpy array of 4-byte floating point numbers with shape: [rows, columns, energy_channels].  I'm not sure how best to integrate this with the Hyperspy load() command but it should be fairly straightforward.  Unfortunately, it seems as though the spatial calibration for the data is stored elsewhere the result of this script is uncalibrated.

def ReadSPD(infile):
    header = {}

    h = open(infile,'rb')
    
    header['tag'] = np.fromfile(h,'int8',16)
    header['version'] = np.fromfile(h,'int32',1)[0]
    header['nSpectra'] = np.fromfile(h,'int32',1)[0]
    header['nCols'] = np.fromfile(h,'int32',1)[0]
    header['nRows'] = np.fromfile(h,'int32',1)[0]
    header['nChannels'] = np.fromfile(h,'int32',1)[0]
    header['countBytes'] = np.fromfile(h,'int32',1)[0]
    header['dataOffset'] = np.fromfile(h,'int32',1)[0]
    header['nFrames'] = np.fromfile(h,'int32',1)[0]
    header['fName'] = np.fromfile(h,'int8',120)
    header['filler'] = np.fromfile(h,'int8',900)
    
    data = np.zeros([header['nSpectra'],header['nChannels']],'int16')
    
    for i in range(0,header['nSpectra']):
        data[i,:] = np.fromfile(h,'int16',header['nChannels'])
    h.close()
    
    data = np.float32(data)
    data = np.reshape(data,[header['nRows'],header['nCols'],header['nChannels']])
    return(header, data)

**Comment by jat255** [comment]
@AndrewHerzing, thanks a lot for this code. It solves an issue that I was having with reading in the text values (`tag`, `fName`, etc.). Reading them as `int` values and then casting to `char` works. 

The calibration and EDS information (such as takeoff angle, accelerating voltage, etc.) are all stored in the .spc and .ipr files. I'm working on one import plugin that will read all of this information into one Hyperspy signal. I should have a PR ready for it in the next couple days.

**Comment by AndrewHerzing** [comment]
@jat255, the integrated plugin sounds great.  Is the spatial calibration in these files as well?  I was unable to locate it.

**Comment by jat255** [comment]
It is in the .ipr file that is saved with the map. The calibration is saved as microns per pixel in tags `mppX` and `mppY` as floats at offset 64 and 68, respectively.
