### ISSUE TITLE
dm-images, stackbuilder metadata

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#762]
When loading dm3-imagestacks made using the StackBuilder plugin, metadata like acceleration voltage and camera length is not loaded. This metadata is located in the original_metadata in the spectrum. 

I'm guessing the dm3-file loading script doesn't load it properly due to the imagetags being stored in non-standard places in the dm3-file itself.

**Comment by francisco-dlp** [comment]
To fix this you could add the location of this entries and where to map them [here](https://github.com/hyperspy/hyperspy/blob/master/hyperspy/io_plugins/digital_micrograph.py#L788).
