### ISSUE TITLE
Migration to Python 3

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#768]
Now that all of our dependencies has finally been ported to Python 3 (thanks @vidartf  for poiting this out) we should start considering porting HyperSpy too.

I'm opening this issue to discuss how to proceed.

A number of core packages support both Py2 and 3. Many of them using the [six library](https://pythonhosted.org/six/).  Personally I would prefer to port HyperSpy to Python 3 for good without relying in any extra library dependency to maintain support with Py3. Then we could run 3to2 or [these other tools](http://python-future.org/) to create the Py2 versions for the releases until we drop Py2 support. What do you think?

TODO
--------
(This is a draft, all is open for discussion)

* [ ] Merge as much as possible for HyperSpy 0.9
* [ ] Run 2to3 + manual polishing
* [ ] Run to 3to2 or similiar to support Py2 just for release.

**Comment by francisco-dlp** [comment]
Regarding to timing, I think that this could be the last task before releasing 0.9. We should aim at merging most pending branches before running 2to3...

**Comment by vidartf** [comment]
Note that `traitsui`'s support for python3 is currently listed as "experimental", and does not support the wx backend. We should therefore test the port (#769) to see if there are anything that gets broken, and if so, submit bug reports to `traitsui`'s repo. If there's any showstoppers, I would be -1 on switching master to pure python3 until those are fixed.

Regarding the use of `six` vs using pure python3 with back-porting, I'm not sure. If we go pure python3, then the dev versions become incompatible with other packages that are only on python2. Not sure if that is an issue. Other than that it depends on how much manual tweaking is necessary for backporting (I guess #769 should illuminate that).

**Comment by jrminter** [comment]
This is timely. I just noticed that Ubuntu is dropping python 2.7 from 16.04LTS (https://wiki.ubuntu.com/Python/FoundationsXPythonVersions)

> Feature freeze is the drop dead date for dropping Python 2.7 from the images. We will be hard-nosed about this! Once python2.7 and libpython2.7 are removed from a seed, we'll blacklist them so they can't be accidentally reseeded.

Perhaps this will spur some of the package maintainers to accelerate their efforts.

**Comment by magnunor** [comment]
To clarify: Ubuntu is dropping Python 2.7 from the default install, so the install ISO will only contain Python 3. However, Python 2.7 will still be in the repository for a very long time, probably as long as Debian has it.

But we should still get HyperSpy over to Python 3 as soon as possible :)

**Comment by vidartf** [comment]
Looking at #769, there shouldn't be much of an issue backporting future releases (do you agree @to266?).

Regarding timing, I'm unsure. In terms of merge order, it would definitely be easiest to take the python3 transition last. Either way conflicts shouldn't be too difficult to resolve. I do, however, also feel it would be appropriate to keep the dev version on python3 for a while to let it "settle in" and check that it is truly ready for release.

**Comment by francisco-dlp** [comment]
For me there is not question that HyperSpy 0.9 should be released for Py2 and 3.Will we support 2.7 after HyperSpy 0.9? If yes, how are we going to do it?

Regarding the timing, the number of new and exciting features are accumulating, so, does a amjor release soon after Christmas sound reasonable? If yes, what about merging  #769 just before Xmas and try to get as many PRs in master as possible by then?

**Comment by magnunor** [comment]
After 0.9 I think we should just stick to Python 3, since maintaining two different versions is (in my opinion) not really worth it. Unless some of our dependencies turn out to have unstable Py 3 implementations, but I'm guessing we'll see during the "multirelease" in 0.9.

**Comment by francisco-dlp** [comment]
@to266, how do you propose that we proceed with making master Py3? In particular, should we carry on supporting (i.e. merging into) the 0.8.x branch? That would involve merging the already Py3 0.8.x branch into master. Or should we drop support for 0.8 now and focus on the next major release to avoid the possible merging hassle?

**Comment by to266** [comment]
I though that when I finally get around to updating https://github.com/hyperspy/hyperspy/pull/769, I would merge both 0.8.x and master and clean everything up? Then we would only work in python3 in all branches, and all PRs that have not been resolved would have to do it themselves

**Comment by francisco-dlp** [comment]
We can continue pull-requestion and merging into 0.8.x then, sounds good!

**Comment by sem-geologist** [comment]
while adding stuff for brukers bcf io plugin I noticed that stdeb.cfg probably should be updated for python3. I think all dependencies there should change from python-xxx into python3-xxx as that is the debian packages with python 3.x.. I see that EHN python 3 #769 is already merged, so I don't know where to commit the fix.

**Comment by francisco-dlp** [comment]
Thanks for reporting this. If you would like to fix it you could branch from 0.8.x, modify `stdeb.cfg` there, and PR your branch to `0.8.x`.
