### ISSUE TITLE
Line endings

### ISSUE THREAD

**Issue by to266** [hyperspy/hyperspy#771]
After https://github.com/hyperspy/hyperspy/pull/741 I noticed that the two files have a different line-endings when I pulled to my local machine.

Should we normalize this thing ([here](https://help.github.com/articles/dealing-with-line-endings/) is a tutorial) or leave the default as `auto`?

**Comment by francisco-dlp** [comment]
Is this a problem? Wouldn't git set the appropiate line ending on
checkout with our current .gitattributes?

**Comment by to266** [comment]
Did not seem to work that time. Now after refreshing the repository, everything seems fine... So don't know

**Comment by to266** [comment]
For reference:

 `core.autocrlf = true` from [here](http://adaptivepatchwork.com/2012/03/01/mind-the-end-of-your-line/)
