### ISSUE TITLE
Model interactive widgets

### ISSUE THREAD

**Issue by to266** [hyperspy/hyperspy#773]
I was playing with models and figured it's relatively simple to add interactive widgets to a model:

```python
from IPython.html.widgets import interact
from IPython.html import widgets

def create_kwargs(comp):
    
    def figure_out_bounds(param):
        fraction = 10.
        _min, _max = None, None
        if param.bmin is not None:
            _min = param.bmin
        if param.bmax is not None:
            _max = param.bmax
        if _max is None and _min is not None:
            _max = param.value + fraction*(param.value - _min)
        if _min is None and _max is not None:
            _min = param.value - fraction*(_max - param.value)
        if _min is None and _max is None:
            _min = param.value / fraction
            _max = param.value * fraction
        step = (_max - _min)*0.001
        return {'min' : _min, 'max' : _max, 'step' : step}
    kwargs = {par._id_name: widgets.FloatSlider(value = par.value, **figure_out_bounds(par)) for par in comp.parameters}
    return kwargs

def interactive_sliders(model):
    
    def get_update_model_func(comp):        
        def update_model(**kwargs):
            for k, v in kwargs.iteritems():
                getattr(comp, k).value = v
        return update_model
    
    for component in model:
        interact(get_update_model_func(component), **create_kwargs(component))
```

The code is not elegant or general or a number of other things, but seems to work.

There is an issue with very small values for floats, though: https://github.com/ipython/ipywidgets/issues/259

Do you think something similar, in-built into hyperspy would be useful?

**Comment by francisco-dlp** [comment]
Cool! I'll be really nice to have this feature. `Model.interactive_widgets`, `Component.interactive_widgets` and `Parameter.interactive_widgets`?

Indeed, is there anything that stop us from replacing traitsui with ipywidgets? Qt/Wx/GtK widgets belong to HyperSpyUI not HyperSpy.

**Comment by to266** [comment]
I'm not experienced enough with how we do that. I think the most difficult part is navigators and interactive range selector things..? 

Any way, in the ipywidgets gitter I also found this:
http://mybinder.org/repo/sylvaincorlay/bqplot-binder

Looks impressive :)

**Comment by dnjohnstone** [comment]
I think this is done as of 0.8.5 and should be closed.
