### ISSUE TITLE
Semper format not documented

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#777]
#741 added read/write support for the semper file format. However, #741 didn't include include documentation

* [x] In the User Guide
* [x] In the `load` dosctring
* [x] In the `Signal.save` docsting

**Comment by CodeMonkeyJan** [comment]
Thanks for the reminder!
Is a mention in the beginning of the `load` docstring (where compatible extensions are listed) plus a description of extension-specific keywords (in my case only `print_info`) enough (same for the `save` docstring I assume)?
And am I correct in the assumption that I should write the user guide documentation in the `io.rst` file or did I miss another location?
Thanks!

**Comment by francisco-dlp** [comment]
AFAIK, no, that should be it. Easy to miss: the supported file formats table in `io.rst`.

**Comment by francisco-dlp** [comment]
Fixed in #781
