### ISSUE TITLE
test_hdf5 nostest crashes ubuntu

### ISSUE THREAD

**Issue by dnjohnstone** [hyperspy/hyperspy#783]
The method test_in_memory_loading in test_hdf5 just fills my RAM and the test gets stuck at this point -  I think speaking to @to266 that this is because my operating system is not giving the expected error message so it all gets stuck.

I'm using Ubuntu 15.10 and have updated to the newest version of anaconda to avoid obvious questions about updatedness. Not really sure why this is so.

**Comment by vidartf** [comment]
I think this is related to memmaps / #774.
Does adding `overwrite=True` to the `setUp()` function do anything? If the file exists, and `overwrite=True` is not specified, the test will typically hang.

**Comment by dnjohnstone** [comment]
Just to update this - I think I found the issue and why it was so machine specific. I forgot that I have a large amount of swap memory allocated! So I think this test will fail eventually, but only after a file of a few hundred Gb has been created.

Perhaps this test needs to check if swap memory is allocated, or even how much memory is available, it's conceivable that a scientific computing facility may have a couple of hundred Gb RAM.

**Comment by dnjohnstone** [comment]
This has now been resolved with various updates to tests.
