### ISSUE TITLE
RELEASE: HyperSpy 0.8.3

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#790]
TODO - RELEASE
-----------------------

* [x] Merge remaining PRs
* [x] Make Python3 branch
* [x] Create RELEASE_0.8.3 branch
    * [x] Update version
    * [x] Update changes
* [x] Discuss `start_jupyter_cm` in User Guide.
* [x] Add `start_jupyter_cm` to WinPython bundle.
* [x] Create Release in GitHub (as pre-release)
* [x] Update DOI in ``README.rst`` and ``citing.rst``
* [x] Py 2
  * [x] Create Python installers
  * [x] Test Python installers
  * [x] Create Windows installers
  * [x] Test Windows installers
* [x] Py 3
  * [x] Create Python installers
  * [x] Test Python installers
  * [x] Create Windows installers
  * [x] Test Windows installers
* [ ] Test Bundle installer

TODO - FINAL RELEASE
--------------------------------

* [x] Update Release in GitHub (remove pre-release)
* [x] Upload documentation
* [x] Upload installers to pypi
* [ ] Update website
* [ ] Upload website
* [ ] Send release message to mailing list

**Comment by to266** [comment]
Agreed. Do we only release it in `pip`, or with Windows binaries as well? Additionally, since mkl-compiled numpy is available from anaconda, we should probably just add a conda recipe..

**Comment by to266** [comment]
cc https://github.com/hyperspy/hyperspy/pull/792

**Comment by francisco-dlp** [comment]
I think that the bundle distribution is very important for users who are
new to Python, which I suspect are a majority. So, going back to asking
people to install anaconda and then install hyperspy "manually" may not be
welcome by many.Installing a Python distribution and typing in a terminal
may discourage a number of users. Also, the instructions many not always
work. For examples, some weeks ago h5py was not working in Windows Anaconda
due to some compiled libraries mismatch. In my experience, these sort of
problem are common and may deter not few users.

We could have a similar installer for Anaconda though. This has the
advantage of being much easier to maintain, and the disadvantage that the
Anaconda, unlike WinPython, is not portable (e.g. it cannot be moved to an
USB key). That's fine enough for me.

What do others think?

2015-12-11 16:35 GMT+00:00 Tomas Ostasevicius <notifications@github.com>:

**Comment by dnjohnstone** [comment]
Strongly agree that the bundle distribution is very important - in practical classes that I gave recently I got the students to install HyperSpy using the Windows installer with the right click option enabled... They were amazed (to the point that they commented on it) how easy it was and how easy it was to used because they were almost all scared of "Python" after another practical that they had had where they'd had to use  command line.

**Comment by vidartf** [comment]
Lets assume this is mainly of interest for people who already have hyperspy installed. If so, we only need a windows installer for the hyperspy package, i.e.
`python setup.py bdist --format=msi OR wininst`
Seems to work OK here, but not tested extensively.

**Comment by magnunor** [comment]
+1 on the windows binary installer, so much easier when introducing new people to HyperSpy.

**Comment by francisco-dlp** [comment]
Today, after a fresh install of Anaconda I've installed HyperSpy and faced this:

```
Creating config directory: /home/fjd29/.hyperspy
Traceback (most recent call last):
  File "/home/fjd29/bin/ana-hyperspy", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/fjd29/git/hyperspy/bin/hyperspy", line 40, in <module>
    import hyperspy.defaults_parser
  File "/home/fjd29/git/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/git/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc, ripple,
  File "/home/fjd29/git/hyperspy/hyperspy/io_plugins/tiff.py", line 25, in <module>
    from skimage.external.tifffile import imsave, TiffFile
  File "/home/fjd29/anaconda2/lib/python2.7/site-packages/skimage/external/tifffile/__init__.py", line 4, in <module>
    from .tifffile_local import imread, imsave, TiffFile
  File "/home/fjd29/anaconda2/lib/python2.7/site-packages/skimage/external/tifffile/tifffile_local.py", line 154, in <module>
    from . import _tifffile
RuntimeError: module compiled against API version a but this version of numpy is 9
```

These are the sort of troubles that the bundle prevents. People experienced with Python can fine their way around this, but this must be very discouraging for beginners.

**Comment by vidartf** [comment]
Actually, since #724 is still unresolved, I'm all for full bundles.

**Comment by francisco-dlp** [comment]
With Anaconda shipping now with IPython 4 and the fact that most scientific Python users have already migrated to Python 3, releasing 0.8.3 becomes an urgent matter. I suggest to aim at releasing asap—tomorrow?

**Comment by vidartf** [comment]
Let's shut down the 0.8.3 milestone tomorrow (PR/issues either resolve/merge, or move to 0.9), and then have a few days grace period for quality assurance before release. That way, we avoid having to ship a 0.8.4 as a quick fix for errors introduced in last minute merge frenzy.

**Comment by francisco-dlp** [comment]
Sounds good!

**Comment by francisco-dlp** [comment]
The scripts to add the "IPython * here" entries to the context menu are now an independent package, [start_jupyter_cm](https://github.com/hyperspy/start_jupyter_cm). I have tested it in Python 2/3 in Windows 7 and GNOME 3 and it works fine for me. However, it'll be nice if somebody could review it and test it before making a release.

**Comment by francisco-dlp** [comment]
Could we try to release today?

**Comment by vidartf** [comment]
PS: The original thought was that the grace period should start *when the last commit was added*. I suggest we create a release today, mark it as a pre-release, and then test it. If no show stoppers are found, we can upgrade the release to an official one (remove pre-release mark), and push to pypi/webpage.

**Comment by francisco-dlp** [comment]
Yes, that sounds like a good plan, as long as you agree with changing the pre-release date from today to tomorrow ;)

**Comment by vidartf** [comment]
Sure :) I tried to split up the todo list for better overview.

**Comment by francisco-dlp** [comment]
I have just submitted a fix to some issue that I've identified with the bundle distribution, see hyperspy/hyperspy-bundle#11 .  Can somebody review it?

Once this is merged, we should be almost ready to release. I would suggest to wait until #883 is ready to merge though. #883 just need to be sent to 0.8.x instead and fix some minor issues.

**Comment by francisco-dlp** [comment]
I have just uploaded the new documentation to the website.

**Comment by francisco-dlp** [comment]
I have also created and tested the py2 sdist and windows installers and all looks fine.

**Comment by vidartf** [comment]
Looking at the todo list, shouldn't the DOI be updated before creating the installers in order for them to contain the updated value? Not very critical, but thought I should point it out.

**Comment by francisco-dlp** [comment]
Good point @vidartf. Unfortunately, I've just created the installers. You can download them for testing from [this link](http://cook.msm.cam.ac.uk/~hyperspy/dist/).  I don't think that anybody will get the DOI from the README so, I am inclined to forget the issue for this release and do it better the next time.

**Comment by to266** [comment]
https://github.com/to266/hyperspy/releases/tag/0.8.3_py3

**Comment by francisco-dlp** [comment]
On uploading the new release to pypi I have encountered a major issue: it is not possible to create 2 source distributions, one for py2 and another for py3. Projects that support both versions tend to use e.g. six to provide support for both py2 and py3 using the same source. What do you suggest to do?

One possible solution is to release 0.8.3py3 only for py3 and 0.8.3py2 only for python 2 just for this release.

Note that 0.8.3 with py2 support only is already in pypi and there is no way back.

Another solution is to release 0.8.4 as a transition, py3 only release.

If you have an opinion on this, please reply quickly.

**Comment by to266** [comment]
If we use 0.8.4 as py3 only release and a python2 user runs `pip install --upgrade hyperspy`, will it download 0.8.3? If so, then I would go this way

**Comment by francisco-dlp** [comment]
I bet that the answer is yes, as long as we set 0.8.4 as py3 only. Anyway, the py3 version will fail to install in Python2, so there is no risk that someone ends up with a broken hyperspy by trying to upgrade.

Let's go for a HyperSpy 0.8.4 release then?

**Comment by francisco-dlp** [comment]
I really want to finish with this today, so I'll start working on a 0.8.4 release for py3 to be released today. If anybody things that there is a better solution speak now.
