### ISSUE TITLE
HDF5 reader plugin for DM

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#793]
As far as I know there is no way to import HDF5-files directly into Digital Micrograph. It is possible to do it indirectly by converting it to raw binary or using the RPL-plugin https://github.com/hyperspy/ImportRPL . 

However, it would be nice if there was some way to directly load HDF5 into DM. 

Has anyone tried this? I'm guessing one way could be to compile the official HDF5 C++ reader into a DLL compatible with DM using the DM SDK.

Not certain if this is the right place to post this, but guessing it is relevant since it could reduce the barrier of using HyperSpy a little bit. An extra bonus would be making the NCEM EMD format loadable in DM as well...

**Comment by thomasaarholt** [comment]
I'd definitely use this. Rpl is a bit annoying. Would also be nice since hdf5 is the standard we use for Hyperspy.

**Comment by niermann** [comment]
Hi there!

As I'm also using HDF5 to store most of my python processed TEM data, I created a plugin for DigitalMicrograph some time ago. I've stumbled over this feature proposal here, thus I uploaded the plugin's source to GitHub (after polishing the plugin a bit):
https://github.com/niermann/gms_plugin_hdf5

The plugin registers a set of functions to DM's scripting engine, which provide access the HDF5 files from scripts. Within the repository in the tests/ directory there is a DM script, which can be installed into the DM menu to load HDF5 files. However, this script currently only interprets my own internal metadata, but might be easily adapted to be used with other HDF5 based formats.

Best regards,
Tore

**Comment by niermann** [comment]
You're absolutely right, especially when you need a different visual studio environment for different versions of DM. Currently the DLLs are not publically available. I have compiled ones for DM versions 1.8 and 2.X (the latter 32 and 64 bit). As far as I'm informed the DM 2.X ones should also work for 3.X.  I will look into ways of making them somewhere downloadable...

**Comment by magnunor** [comment]
How big are they? You could probably include them in your https://github.com/niermann/gms_plugin_hdf5 repository.

**Comment by ericpre** [comment]
That's great! Looking forward the DLL! :)
Currently the GMS rpl plugin has a limitation: it can't import large dataset (> ~1 Go) and several Go datasets are becoming very common...

**Comment by niermann** [comment]
I created a release in GitHub repository, which contains a zip file with all the binaries. Enjoy them!
https://github.com/niermann/gms_plugin_hdf5/releases

**Comment by magnunor** [comment]
@niermann, great! I'll have a look and see if I can get them running on my computer.

**Comment by magnunor** [comment]
@niermann, just tested on two HDF5-files exported using HyperSpy. And both loaded nicely in DM using your plugin. Very nice!

Also, it should be easy to get the metadata to load as well, due to most of those parts being implemented in the `CMD_import_hdf5.s` file. Is this file also in the repository?

**Comment by niermann** [comment]
@magnunor, nice to hear that it works to your convenience. 

Currently the  `CMD_import_hdf5.s` file imports some metadata (using my own conventions). As you already noticed, the metadata handling is done by the DM script itself. So one should be able to adjust the required handling to one owns needs using the DM scripting interface (in all its glory ;) ). The file `CMD_import_hdf5.s` is included in the repository in the `tests` directory (even if it is more an example of the plugins usage than a test...)

**Comment by magnunor** [comment]
It would be nice to have a DM-script which can load metadata from the most "common" types of HDF5-files. Like the HyperSpy "format".

Would it maybe be an idea to have the DM-plugin script as a separate repository? Since such a plugin can be improved much easier compared to the compiled version, since the compiled version requires a very specific compile environment.

**Comment by tjof2** [comment]
Closed in #2542
