### ISSUE TITLE
Random failure of test `hyperspy.tests.mva.test_decomposition.TestGetExplainedVarinaceRation.test_data`

### ISSUE THREAD

**Issue by vidartf** [hyperspy/hyperspy#798]
`hyperspy.tests.mva.test_decomposition.TestGetExplainedVarinaceRation.test_data` keep failing at seemingly random in the CI builds. Is there a reason for this? Is it possible to fix it?

**Comment by francisco-dlp** [comment]
Yes, I've noticed previously those hard to understand random failures in such a simple test. May `np.empty` be the one to blame?

**Comment by dnjohnstone** [comment]
I guess this might be with reference to the pull request I just made for absorption corrections? I think I had this the other day with Model2D as well one of Tomas's suggestions suddenly broke this test (on my local machine) - seemed quite odd.

**Comment by vidartf** [comment]
I've had it as well. I think you are right @francisco-dlp , as the docs state:
> out : ndarray
Array of uninitialized (arbitrary) data with the given shape, dtype, and order.

**Comment by vidartf** [comment]
`np.zeros` should fix it?

**Comment by francisco-dlp** [comment]
I've tested it and it fixes it, I'll PR in a second.

2015-12-15 14:46 GMT+00:00 Vidar Tonaas Fauske <notifications@github.com>:
