### ISSUE TITLE
Element database in HyperSpy

### ISSUE THREAD

**Issue by dnjohnstone** [hyperspy/hyperspy#804]
There exists an elemental database in HyperSpy containing X-ray line energies and some other limited values like density. Two developments spring to mind:

1. This is documented under EDS but probably deserves its own entry as it ought to have values useful to other things in the long run.

2. What is the best way to structure an elemental database of values given I think we should expect this to grow to include much other data but also probably don't want to be responsible for maintaining a database...

**Comment by vidartf** [comment]
I think we should still keep it in a python format, as it is easily readable, making it easy to maintain and keep track of in git. It is also a read-only databank. In terms of usability from the end-user's point of view, I'd at least be in favor of adding attribute access instead of only by keys, so that we got autocomplete (if it's not already there?).

Given this, it seems mostly to me to be an issue of whether we should split the storage up according to categories, and then recombine them all in `elements.py` at runtime to get back the current layout. This way we could have one file called `xraylines.py` and one `atomicweights.py`. This would also allow the user the choice whether to access the combined databank, or access only xraylines directly.

**Comment by dnjohnstone** [comment]
Just came across the following library produced by some people at NIST: https://github.com/pkienzle/periodictable

This uses a structure similar to what @vidartf describes above and I'm wondering if we might consider extending this library for our needs? Or at least taking what they've done and incorporating that plus more specific stuff for particular signal classes.

Should also note that I found this because DiffPy (http://www.diffpy.org/products/diffpycmi/contents.html#contents) depends on it, which is a rather interesting project.

**Comment by francisco-dlp** [comment]
I agree that it'll be good to externalize the elements database, either by splitting ours into a separate package or extending an established  one with the extra information that we need by pull requesting to the relevant project.

This is just one example. I think that the time is ripe for splitting HyperSpy into a number of separate projects as it is becoming a little bit bloated.

**Comment by dnjohnstone** [comment]
Ok, so do I understand correctly that we would aim to have a structure with a number of projects perhaps meaning that the current code would become something like:

hyperspy/hyperspy -- general multidimensional data analysis tools
hyperspy/edsanalysis -- all the eds stuff
hyperspy/eelsanalysis -- all the eels stuff
hyperspy/elementdatabase --  database of physical parameters associated with elements
hyperspy/fileformats -- tools for reading file formats specific to user signals

If this is what we're going to aim for -- I'd be willing to take on doing a review of available element databases and after agreeing on the best route forward set up what we need for the current code. This could potentially involve speaking with developers of an external project, although my gut is that establishing our own, perhaps initially based on another, is a better route.

**Comment by francisco-dlp** [comment]
Yes, something of that sort. Splitting the project has advantages and disadvantages. I think that the advantages outweight the disadvantages, but this is something important enough to be discussed in its own issue.

**Comment by dnjohnstone** [comment]
Picking this up again -- having a separate elements database seems to be something we agree on in principle, the key question is then do we make our own elements database as a separate package, or aim to draw on one existing elsewhere?

Having thought about it a bit I think that the only feasible long term solution is to start developing our own, which will hopefully become rather wide reaching and general - but database maintenance is a bit of a pig... Perhaps we should try to do this in some way that means we can update relevant parts with respect to more specialised databases easily?

**Comment by dnjohnstone** [comment]
On reflection I think this very much a secondary issue and is very unlikely to be solved in a fully general way any time soon. Therefore I'm closing and it will come up again when people add application specific code for which it would be useful.
