### ISSUE TITLE
Remove hyperspy script, magic and extension?

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#805]
Unlike most Python packages, hyperspy has a starting script. We decided to have one in order to make it more user friendly for the people unfamiliar with Python (most of our users). But that was a long time ago when Python wasn't as widespread in the scientific community as it is today. Until today, the only reason to keep it was to set up the chosen toolkit, which is particularly cumbersome in the case of the Qt toolkit due to the two coexisting APIs. However, #714 makes the starting script unnecessary. So, wouldn't it make sense to remove the start script?

 #767 fixes the issue of the Qt API version without needing a magic. If it gets merged, it'll be possible to start HyperSpy without issues as any other Python package e.g.

```python

import hyperspy.api as hs
%matplotlib qt4

```
Just two standard two lines that replaces the current less standard two lines:

```python
%load_ext hyperspy
%hyperspy

````

So, shouldn't we remove the extension and magic too?

TODO
--------
* [ ] Deprecate magic
* [ ] Deprecate extension
* [ ] Deprecate start script
* [ ] Remove `Preferences.General.default_toolkit`
* [ ] Add documentation
    * [ ] Importing HyperSpy
    * [ ] Importing HyperSpy headless

**Comment by francisco-dlp** [comment]
Any thoughts on this?

**Comment by to266** [comment]
With the #767 I agree that this is the way to go.
Does anyone else have any input?

**Comment by vidartf** [comment]
If it works, I'm all for it, but maybe unsure about this point:

> Remove `Preferences.General.default_toolkit`

Maybe we can set it to default to undefined? And if set we try to run:
```python
import matplotlib
matplotlib.use(Preferences.General.default_toolkit)
```

Most people won't notice it, but potentially very useful for some people? I'm not sure myself.

**Comment by francisco-dlp** [comment]
@vidartf, wouldn't setting a default toolkit in `matplotlibrc` enough for those users?

**Comment by vidartf** [comment]
@francisco-dlp: Sure. I was just considering options for lowering the low entry-level of hyperspy for those that are new to Python. However, if they always use hyperspy from e.g. qtconsole, it will automatically be done for them.
