### ISSUE TITLE
spikes_removal_tool() fails

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#820]
`spikes_removal_tool()` fails in Jupyter Notebook. The attached error is returned on both platforms, independent of matplotlib backend. Traitsui is updated to the latest version on Mac.

https://gist.github.com/thomasaarholt/d8fa0a53c7cca210d857

It works fine when running it in hyperspy through the terminal.

**Comment by vidartf** [comment]
After a bit of troubleshooting on gitter, starting the python session with the following works around the problem:
```python
import sip
for t in ["QDate", "QVariant", "QDateTime", "QTextStream", "QString", "QTime", "QUrl"]:
    sip.setapi(t, 2)
%matplotlib qt4
import hyperspy.api as hs
```
Not sure if this came through #767 or not, but there seems to be a bit of chicken and egg problem with `%matplotlib qt4` and `import hyperspy.api as hs`: During `import hyperspy.api as hs` somewhere `matplotlib.use()` is called, setting the backend so that the matplotlib magic is too late (backend can only be set once). And during `%matplotlib qt4` the Qt API is set to version 1...

**Comment by francisco-dlp** [comment]
The following works for me:

```python
import hyperspy.api as hs
%matplotlib
```

However, for this to work the default matplotlib backend must be qt. If that's not the case the following, executed before the two lines above, should fix the issue without having to modify matplotlibrc:

```python
matplotlib.rcParamsOrig["backend"] = "Qt4Agg"
matplotlib.rcParams["backend"] = "Qt4Agg"
````

The source of these problems is that the default PyQt api is v1 for Python2. matplotlib uses API v1 by default but traitsui v2. However, in Python3 the default is v2, so, once we transition to python 3 (#769), this should not longer be an issue.

In the meantime, wouldn't documenting the issue and the workaround be enough? For most users it should work out of the box anyway.

**Comment by vidartf** [comment]
@francisco-dlp : It's a little more nuanced than that: Matplotlib does not set the Qt API version, but IPython's `%matplotlib qt4` does set it to 1 if not the API version has explicitly been set to 2 already. If you look in the details of IPython's code, your suggested workaround is not viable:

Pseudocode from internal IPython docstring:
```
Import Priority:

if Qt4 has been imported anywhere else:
   use that  <-- This is where it sets it to v1 unless v2 has already been set

if matplotlib has been imported and doesn't support v2 (<= 1.0.1):
    use PyQt4 @v1

Next, ask ETS' QT_API env variable

if QT_API not set:
    ask matplotlib via rcParams['backend.qt4']
    if it said PyQt:
        use PyQt4 @v1
    elif it said PySide:
        use PySide

    else: (matplotlib said nothing)
        # this is the default path - nobody told us anything
        try:
            PyQt @v1
        except:
            fallback on PySide
else:
    use PyQt @v2 or PySide, depending on QT_API
    because ETS doesn't work with PyQt @v1.
```
For qtconsole, there is no way to reach the code where it looks at matplotlib's rcParams, as Qt will always be imported beforehand.

Now, we don't have to use the magic, we could use `matplotlib.use("Qt4Agg")`, but then it is not interactive by default. So then you run this:
```python
import matplotlib
matplotlib.interactive(True)
matplotlib.use("Qt4Agg")
import hyperspy.api as hs
s = hs.load()
s.plot()
```
This plots the figure, but the plots are completely frozen (my guess is that they're not hooked up to the main Qt event loop?). As such, the only option left (that I can find) is calling `sip.setapi()` as listed above before calling the matplotlib magic...

**Comment by vidartf** [comment]
Now, the last comment wasn't very constructive in terms of offering solutions, so my best bet would be to leave v0.8.x alone for now, and then perform all the suggested changes on the python 3 version, where we don't have to deal with this mess. The biggest down-side of that is of course that the way of running hyperspy will be completely different on python 2 and 3...

**Comment by francisco-dlp** [comment]
So then, how does it work for me? I'm using matplotlib 1.5.1, qtconsole 4.1.1 and traitsui 5.0.

**Comment by vidartf** [comment]
Do you have a modified IPython profile? I assume you're using PyQt4 (not 5 or PySide)?

**Comment by vidartf** [comment]
Its quite a lot easier to figure out why something is not working than why it IS working :P

**Comment by francisco-dlp** [comment]
I'm using PyQt and the default ipython profile. You wrote:

> For qtconsole, there is no way to reach the code where it looks at matplotlib's rcParams, as Qt will always be imported beforehand.

However, at least in my experience, Qt is not imported beforehand when running inside the qtconsole (the GUI is running as an independent process). Hence, if hyperspy is imported before running `%matplotlib`, it is hyperspy the one who sets the API to 2. 

I think that @thomasaarholt issue is most likely due to a mismatch between his default matplotlib backend and his `preferences.General.default_toolkit` in HyperSpy. When importing HyperSpy it sets the ETS toolkit to match the matplotlib backend if matplotlib has been imported. If not, it uses hyperspy defaults.

**Comment by vidartf** [comment]
I think I found the source of the confusion: My initial trace was a little inaccurate, so the RC file is looked at. Other than that, there are three more issues:
 1. The matplotlib RC parameter `qt4.backend` also has to be set to `PyQt4v2` (defaults to `PyQt4`).
 2. Even if set, matplotlib only does `sip.setapi('QString', 2)` and `sip.setapi('QVariant', 2)`. (as is normal). However, somewhere the API version of `QDate` gets locked to version 1??

**Comment by francisco-dlp** [comment]
Yes, I have also noticed that `QDate` gets locked to version 1 when importing `matplotlib.pyplot`. I couldn't find where in their code, so I bet that it is done by one of their dependencies. Anyway, none of this should be an issue now that we enforce version 2 in our `hyperspy.__init__` as long as hyperspy is imported first.

**Comment by vidartf** [comment]
The error that @thomasaarholt  was getting, I can reproduce by:
```python
import hyperspy.api as hs
hs.load()
```
Doesn't matter if I use pure python, or IPython.

**Comment by vidartf** [comment]
It's basically since the traitsui toolkit is 'null'.

**Comment by francisco-dlp** [comment]
What do you have in `hs.preferences.General.default_toolkit`?

**Comment by vidartf** [comment]
`preferences.General.default_toolkit` is set to 'pyqt'. Maybe that has become invalid in v5?

**Comment by francisco-dlp** [comment]
Strange, it works for me.

**Comment by francisco-dlp** [comment]
The relevant code is in `hyperspy\gui\__init__.py`.

**Comment by vidartf** [comment]
Yup.

**Comment by vidartf** [comment]
So... Basically change that file to use `preferences.General.default_toolkit` before trying to infer from matplotlib?

**Comment by francisco-dlp** [comment]
It tries to infer from matplotlib first so that e.g. the following works:

```python
%matplotlib wx
import hyperspy.api as hs
```

Ideally we would like to only infer from mpl and advice the users to run the mpl magic first. However, due to the QT API nightmare, we can't do that as hyperspy has to be imported first in order to set the API to v2. Getting the toolkit from hyperspy preferences is only useful when working with the inline backend.

**Comment by vidartf** [comment]
Then it is actually a requirement for running hyperspy to specify a default MPL backend that uses API v2 in the MPL rc parameters? Sounds tricky...

**Comment by francisco-dlp** [comment]
No, setting the `qt4.backend` is not necessary. Just `backend` should be enough. Most users use the bundle or anaconda, and in both everything should work out of the box.

**Comment by vidartf** [comment]
I'm on a WinPython distro, and I'm pretty sure my default backend is "TkAgg" (I don't think I have modified this, but who knows)? Or does the bundle set this before packaging?

**Comment by francisco-dlp** [comment]
You are right, in WinPython the default is "TkAgg". Then, what do you think about simply setting it to qt in the bundle? In anaconda the default is qt. Given that this problem is going to vanish in Python 3, I think that, as long as we document it well in the User Guide, it shouldn't stop us merging #818 and #819.

**Comment by to266** [comment]
.... Please consider that it might be easier to just move to python 3. I know it would traditionally require some sort of transition period, but this whole issue for me looks like a good reason to just jump the ship.

The branch is probably currently not up-to-date, but it's simple enough to merge current master. Just let me know if I should.

**Comment by francisco-dlp** [comment]
Yes, I think that it makes sense. What about this: make 0.8.3 the last release with Python 2 support. We add Python 3 support in a separate 0.8.3py3 branch. @vidartf, has HyperSpyUI been ported to Py3 yet?

**Comment by vidartf** [comment]
I agree to making sure bundle installer sets qt as default backend for python 2, and documenting it. Whether or not we drop python2 support for 0.9, I think we can still port to python 2, but say that it is unsupported (i.e. we will not make any effort to fix issues like this for the python 2 version).

@francisco-dlp : Yes, I've already ported the UI to python3.

**Comment by vidartf** [comment]
Added a PR to bundle code to include default matplotlibrc file with Qt4Agg as default backed. See hyperspy/hyperspy-bundle#5.

**Comment by vidartf** [comment]
This is basically resolved then?

**Comment by francisco-dlp** [comment]
I would say so.
