### ISSUE TITLE
Convergence angle needs clarification

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#826]
The convergence and collection angle, referred to in the following locations, should be specified and clarified to be semi-angles (i.e. half the full angle), as is convention in the EELS community. According to @francisco-dlp (as discussed on [Gitter](https://gitter.im/hyperspy/hyperspy?at=5698d8cfc391361d48eb3e0a)), this is what *should* be passed to the method.

[`.set_microscope_parameters()`](http://hyperspy.org/hyperspy-doc/current/api/hyperspy._signals.html?highlight=set_microscope_parameters#hyperspy._signals.eels.EELSSpectrum.set_microscope_parameters)
[`.effective_angle()`](http://hyperspy.org/hyperspy-doc/current/api/hyperspy.misc.eels.html#hyperspy.misc.eels.effective_angle.effective_angle)

I'd argue that the arguments they take should be called semi_convergence_angle and semi_collection_angle, rather than convergence_angle/collection_angle or alpha/beta.

Note, I don't actually know what the second example (`effective_angle`) does - I found it by searching for "convergence", and assume it should be changed as well.

**Comment by francisco-dlp** [comment]
@thomasaarholt, I have submitted a fix for this issue in #860. It basically clarifies in the docstrings and User Guide that convergence/collection angle refers actually to the semi-angle. 

Although renaming the keyword arguments and attributes could make things clearer, it could also break some people's script, so I have refrain from doing that. Unfortunately this means that we're helping to keep alive this widespread source of confusion in the TEM community.
