### ISSUE TITLE
Exporting calibrated PCA/BSS loadings

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#838]
After running Blind Source Separation (BSS) on a spectrum image, it would be great to be able to export the result (in particular the loadings) as spatially calibrated images (i.e. 1pixel = 1nm etc). `.export_bss_results(save_figures = True)` exports individual components, but saves them as picture with scale bars on the X and Y axes. It would be great to be able to save the file as a tiff or hdf5 and retain the calibration for each pixel.

At the moment, the closest I can get is:

```python
a = s.get_bss_loadings()
a.change_dtype("float32") #from float64, which all BSS models are saved as

a.save(“All_BSS_Layered_tiff.tif") #Save the whole thing as one layered tiff
a[0].save("First_BSS_Loading.tif”) # Saves the individual components.
```
Unfortunately, in these two cases the spatial calibration is lost.

**Comment by to266** [comment]
https://github.com/hyperspy/hyperspy/pull/839

You can try this, or, as mentioned in the PR, you can supply the resolutions yourself. The PR'ed thing should be able to convert units correctly as well, however keep in mind I have barely tested it

**Comment by francisco-dlp** [comment]
Is this fixed @thomasaarholt?

**Comment by thomasaarholt** [comment]
Yep, it's fixed! Thanks!
