### ISSUE TITLE
change progressbar to be a proper library

### ISSUE THREAD

**Issue by to266** [hyperspy/hyperspy#840]
How about we use https://github.com/tqdm/tqdm instead of our `external.progressbar`? Seems to be not only tested, but also actively developed as well :)

**Comment by francisco-dlp** [comment]
Looks really cool, +1

**Comment by vidartf** [comment]
Just check that it also looks good in terminals on other platforms :)

**Comment by to266** [comment]
Have a look https://github.com/hyperspy/hyperspy/pull/841

**Comment by sem-geologist** [comment]
This is really cool and simple :)

**Comment by vidartf** [comment]
Added in #841.
