### ISSUE TITLE
Value Error with Plot Tool

### ISSUE THREAD

**Issue by k8macarthur** [hyperspy/hyperspy#878]
I've come across a problem with the plot tool this morning. This is following some installation problems last week which I thought were solved but could be related. The output error message is copied below.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-32-ab3e206027f6> in <module>()
      3 s.add_lines()
      4 bw = s.estimate_background_windows(line_width=[5.0, 2.0])
----> 5 s.plot(background_windows=bw)
      6 s.get_lines_intensity(background_windows=bw, plot_result=True)
      7 s.plot(integration_windows='auto')

/Users/macark/Documents/hyperspy/hyperspy/_signals/eds.pyc in plot(self, xray_lines, only_lines, only_one, background_windows, integration_windows, **kwargs)
    917         get_lines_intensity, estimate_background_windows
    918         """
--> 919         super(EDSSpectrum, self).plot(**kwargs)
    920         self._plot_xray_lines(xray_lines, only_lines, only_one,
    921                               background_windows, integration_windows)

/Users/macark/Documents/hyperspy/hyperspy/signal.pyc in plot(self, navigator, axes_manager, **kwargs)
   3331 
   3332         self._plot.plot(**kwargs)
-> 3333         self.events.data_changed.connect(self.update_plot, [])
   3334         if self._plot.signal_plot:
   3335             self._plot.signal_plot.events.closed.connect(

/Users/macark/Documents/hyperspy/hyperspy/events.pyc in connect(self, function, kwargs)
    308         if function in self.connected:
    309             raise ValueError("Function %s already connected to %s." %
--> 310                              (function, self))
    311         if kwargs == 'auto':
    312             spec = inspect.getargspec(function)

ValueError: Function <bound method EDSTEMSpectrum.update_plot of <EDSTEMSpectrum, title: Original Data Cube, dimensions: (512, 512|2048)>> already connected to <hyperspy.events.Event: Event that triggers when the data has changed: set([<bound method Interactive.update of <hyperspy.interactive.Interactive instance at 0x125dd2d40>>, <bound method Interactive.update of <hyperspy.interactive.Interactive instance at 0x1270e7ab8>>, <bound method EDSTEMSpectrum.update_plot of <EDSTEMSpectrum, title: Original Data Cube, dimensions: (512, 512|2048)>>, <bound method Interactive.update of <hyperspy.interactive.Interactive instance at 0x132eabf80>>, <bound method Interactive.update of <hyperspy.interactive.Interactive instance at 0x1271101b8>>])>.

**Comment by dnjohnstone** [comment]
This is an issue with the very newest major development part of HyperSpy called 'events' that provides a platform for more advanced plotting tools and GUI - I had exactly the same problem as this last week as discussed in #844.

In my case I have found it to usually be resolved by closing open plot windows and sometimes going back a couple of cells in the notebook.

@vidartf will this be resolved with pending pull requests or do we need to do something about it - it's certainly very annoying for those using the current master for EDX quantification.

**Comment by k8macarthur** [comment]
Interesting, in my case this occurs straight after I’ve opened Hyperspy so there are no open plot windows.

**Comment by vidartf** [comment]
@k8macarthur : Does this error occur every time you run the same code, or only some of the times (how often)? Either way, would you mind posting all of the code run? What you pasted earlier is missing the first two lines.

**Comment by k8macarthur** [comment]
It turned out to be a qt back end problem which was solved by another issue. So I thought I would close this one.
