### ISSUE TITLE
plot spectra fails in master because Signal can't be indexed

### ISSUE THREAD

**Issue by dnjohnstone** [hyperspy/hyperspy#880]
In the current master hs.plot.plot_spectra(something) fails with an error as below. I think this is simply because we should now be using isig/inav rather than directly indexing? If so this is quick to fix and I'll do it in a second.

`` ---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-21-6abad2bda0d4> in <module>()
----> 1 fig_trace = hs.plot.plot_spectra(trace)

/home/dnj23/hyperspy/hyperspy/drawing/utils.pyc in plot_spectra(spectra, style, color, line_style, padding, legend, legend_picking, legend_loc, fig, ax, **kwargs)
    998                            ax,
    999                            color=color,
-> 1000                            line_style=line_style,)
   1001         if legend is not None:
   1002             plt.legend(legend, loc=legend_loc)

/home/dnj23/hyperspy/hyperspy/drawing/utils.pyc in _make_overlap_plot(spectra, ax, color, line_style)
    316         ax.plot(x_axis.axis, spectrum.data, color=color, ls=line_style)
    317     if len(spectra) > 1:
--> 318         _set_spectrum_xlabel(spectra[-1], ax)
    319     ax.set_ylabel('Intensity')
    320     ax.autoscale(tight=True)

TypeError: 'Signal' object does not support indexing``

**Comment by vidartf** [comment]
It seems to me that the code expects spectra to be a collection of signals, but it is actually a `Signal`.

**Comment by dnjohnstone** [comment]
Hmmm do you think that's indicative of a more fundamental change being needed then @vidartf stupid fix from me was to just use inav to do the indexing which got rid of the errors and seems to reproduce the previous functionality, which at least lets me get on with what I was doing...

**Comment by vidartf** [comment]
In your paste above, what is `trace` ? Can you get expected results by passing `[trace]`?

**Comment by dnjohnstone** [comment]
In that particular case it was a Signal class object that I'd made using your Line2D ROI tool - but I got the same error if it was get_decomposition_factors(), which I think is the more typical use. Inserting inav as I have makes both cases work.

**Comment by vidartf** [comment]
The `plot_spectra` code supports both a single `Spectrum` as well as a collection of `Spectrum` (e.g. `[s1, s2, s3]`). Your PR fixes the first case, but breaks the second case.

**Comment by dnjohnstone** [comment]
On right - I see what you're saying, I hadn't clocked on to the fact that get_decomposition_factors actually returns a single Signal instance as well so both cases were the same... sorry.

I'll think about it this afternoon to make sure it works for both cases.
