### ISSUE TITLE
Line2D ROI widget "linewidth" upon plotting are at wrong positions

### ISSUE THREAD

**Issue by to266** [hyperspy/hyperspy#886]
as per @dnjohnstone in https://github.com/hyperspy/hyperspy/pull/844

> Just come across a strangeness with Line2D... When specified with some finite linewidth the bounding lines initially plot in a really weird place as below. Dragging the widget updates the plot to the correct thing though.
> ![image](https://cloud.githubusercontent.com/assets/3384140/13355176/edf72f5e-dc96-11e5-925b-b41968921e7c.png)

**Comment by ericpre** [comment]
Fixed in #1685.
