### ISSUE TITLE
saving fit data

### ISSUE THREAD

**Issue by kinalytx** [hyperspy/hyperspy#902]
Hi, 
I am new to hyperspy but my code to fit EELS data was successful. I need to save the fit model data to an xy text or csv file to use in external plot software. I only managed to save the original data to an hdf5 file which still a pain as I need to convert that to csv! Currently I have no idea how to save the fit model. Could you please help.

This is how is saved the raw data:
s.save('spectrum')

**Comment by vidartf** [comment]
@kinalytx : You can always convert the model to a signal with `your_model.as_signal()` (off the top of my head, might be called slightly differently). Then you can save that as you would any hyperspy signal. Currently, I do not think CSV is directly supported in hyperspy (it probably should be), but you can work around it by doing `np,savetxt('filename.csv', your_signal.data, delimiter=', ')`. See the [numpy docs](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.savetxt.html) for further detail.

**Comment by to266** [comment]
the @vidartf comment would only help you save the resulting total model, but not parameter values. In order to store those, you would have to save each of the parameters individually - something like
```python
for component in model:
    for parameter in component:
        np.savetxt(component.name + '_' + parameter.name + '.csv', parameter.map, delimiter=', ')
```

This should (I did not test this) save both `values`, `std` and `is_set` fields of the map. If only one of them is required, just replace `parameter.map` with `parameter.map['values']` or adequate

**Comment by kinalytx** [comment]
Hi, Thanks for that. That works partly but I am still stuck with how to save the model fit? In fact, I had success plotting multiple EELS signals but now I need to add the model fit to this customised plot. Also I wish to normalize the intensity-axis (0-1). I hope you can help.

**Comment by wcdyang** [comment]
@to266 Hi, Thanks for the suggestion for saving the parameter values into *.csv. I attempted this for a fitting model 'm3'. It contained four Lorentzian functions and one polynomial function as shown below:
```javascript
m3.print_current_values(fancy=False)
```
```
EELSModel: EELS Spectrum Image (high-loss) after Richardson-Lucy deconvolution 3 iterations
current_component_values: Lorentzian
Active: True
Parameter Name |  Free |      Value |        Std |        Min |        Max
============== | ===== | ========== | ========== | ========== | ==========
             A |  True | 0.00250002 | 0.00018034 |        0.0 |       None
         gamma |  True | 0.14974065 | 0.00509781 |       None |        0.5
        centre |  True | 1.69429333 | 0.00133548 |       1.65 |        1.8

current_component_values: Lorentzian_0
Active: True
Parameter Name |  Free |      Value |        Std |        Min |        Max
============== | ===== | ========== | ========== | ========== | ==========
             A |  True | 0.00159916 | 0.00029573 |        0.0 |       None
         gamma |  True | 0.18538892 | 0.01319574 |       None |        0.5
        centre |  True | 2.05203289 | 0.00279926 |        2.0 |        2.2

current_component_values: Lorentzian_1
Active: True
Parameter Name |  Free |      Value |        Std |        Min |        Max
============== | ===== | ========== | ========== | ========== | ==========
             A |  True | 0.00321248 | 0.00046364 |        0.0 |       None
         gamma |  True | 0.23952649 | 0.01157517 |       None |        0.5
        centre |  True | 2.46043723 | 0.00235784 |        2.4 |        2.5

current_component_values: Lorentzian_2
Active: True
Parameter Name |  Free |      Value |        Std |        Min |        Max
============== | ===== | ========== | ========== | ========== | ==========
             A |  True | 0.00484692 | 0.00055371 |        0.0 |       None
         gamma |  True | 0.26303456 | 0.01161640 |       None |        0.5
        centre |  True | 2.96846668 | 0.00158688 |        2.9 |        3.1

current_component_values: 2nd order Polynomial
Active: True
Parameter Name |  Free |      Value |        Std |        Min |        Max
============== | ===== | ========== | ========== | ========== | ==========
            a0 |  True | -0.0096269 | 0.00235656 |       None |       None
            a1 |  True | 0.00394675 | 0.00246495 |       None |       None
            a2 |  True | 0.00050871 | 0.00049900 |       None |       None
```
When I tried to save these values using the suggested code:
```javascript
for component in m3:
    for parameter in component:
        np.savetxt(component.name + '_' + component.parameter + '.csv', component.parameter.map, delimiter=', ')
```
It returned the error below:
```javascript
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-108-902a35ca0f67> in <module>
      1 for component in m3:
----> 2     for parameter in component:
      3         np.savetxt(component.name + '_' + component.parameter + '.csv', component.parameter.map, delimiter=', ')

TypeError: 'Lorentzian' object is not iterable
```
I also tried the code below to test `component.parameter`:
```javascript
for component in m3:
    component.parameter
```
It returned the following error:
```javascript
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-109-b25ac51b9ec9> in <module>
      1 for component in m3:
----> 2     component.parameter
      
AttributeError: 'Lorentzian' object has no attribute 'parameter'
```
The Hyperspy version is 1.6.1. Do you have any suggestions? Anything will be highly appreciated. Thank you.

**Comment by francisco-dlp** [comment]
There were a couple of typos in @to266 code, the following should work, but I haven't tested it either, so please let us know if it does work:

```python
for component in model:
    for parameter in component.parameters:
        np.savetxt(component.name + '_' + parameter.name + '.csv', parameter.map["values"], delimiter=', ')
```

**Comment by wcdyang** [comment]
@francisco-dlp The updated code works well. Thank you so much for the input! I don't think I could ever have figured out `component.parameters` in line 2 from the hyperspy.model module description without your input. Was it the right place to look? Thanks again.  

> There were a couple of typos in @to266 code, the following should work, but I haven't tested it either, so please let us know if it does work:
> 
> ```python
> for component in model:
>     for parameter in component.parameters:
>         np.savetxt(component.name + '_' + parameter.name + '.csv', parameter.map["values"], delimiter=', ')
> ```
