### ISSUE TITLE
Next major release version number

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#904]
Although the next major release version number is tagged 0.9 at present, I propose to change it to 1.0 in order to start complying with [semantic versioning](http://semver.org/).

When releasing v0.8.3 and v0.8.4 our current version numbering caused some troubles because after uploading to pypi we realised that there were some issues with the installers. Normally we should have made a patch release to fix the issues with the installers, but we couldn't because our minor release number is the patch release number in semantic versioning.

Beside, most Python projects have transitioned to a 1.0 once they've felt that their API was stable enough. I think that HyperSpy has reached this status.

So, shall we make the next major version 1.0?

**Comment by vidartf** [comment]
+1

**Comment by to266** [comment]
Agreed +1

(oh and this looks nifty: http://poll.gitrun.com/hyperspy/hyperspy/issues/904 )

**Comment by dnjohnstone** [comment]
Makes sense to me.

**Comment by jat255** [comment]
Also agree.  +1.0?

**Comment by francisco-dlp** [comment]
Ok, granted and closing.
