### ISSUE TITLE
Axes limits

### ISSUE THREAD

**Issue by kinalytx** [hyperspy/hyperspy#907]
How can I set axis limits (min, max) when running e.g.:

s.plot()
Thanks.

**Comment by jat255** [comment]
Hi Imad,

You might take a look through the users guide if you haven't already, as this is answered in there pretty clearly. More specifically, you can find some info about slicing spectra and Signals here: http://hyperspy.readthedocs.org/en/latest/user_guide/tools.html#indexing

Note, the simple `[ ]` style indexing has been removed in recent versions of Hyperspy, replaced by the `inav` and `isig` syntax. See the following issue:
https://github.com/hyperspy/hyperspy/issues/388

In the future, the types of questions would probably be better asked in the user group email list (https://groups.google.com/forum/#!forum/hyperspy-users) or in the gitter chat for the project. GitHub issues are more for development questions (bugs, feature requests, etc.)

**Comment by jat255** [comment]
Also, once you have a plot, you can use any of the standard `matplotlib` tools to adjust the display of the plot (if you don't want to change the underlying data that is being plotted).

**Comment by kinalytx** [comment]
That's great! Thanks Josh.
