### ISSUE TITLE
BUG: closing navigator plot when none is present

### ISSUE THREAD

**Issue by to266** [hyperspy/hyperspy#912]
[Here](https://github.com/hyperspy/hyperspy/blob/master/hyperspy/drawing/mpl_he.py#L163). Not sure if it reappeared when merging the python3 branch, or we never fixed it to begin with....

Can be triggered with 
```python
s = hs.signals.Spectrum(np.arange(100))
s.integrate_in_range()
```

**Comment by francisco-dlp** [comment]
This was fixed (and is ok) in the 0.8.x branch, but returned to master, probably due to an incorrect merge. I'll PR a fix.
