### ISSUE TITLE
Less strict events?

### ISSUE THREAD

**Issue by vidartf** [hyperspy/hyperspy#921]
Currently, the new events raise exceptions if trying to connect/disconnect a function that is already/not connected. While this is useful for indicating potentially broken connections, it can be quite destructive to actual work being done, as your program state might be caught in a form of "limbo". Weighing these two considerations against each other is a pretty standard issue in programming, and for development, it is definitively beneficial to fail hard at errors. However, in terms of actual work, I sometimes might wish to ignore these in order to complete a piece of work efficiently. As such, I've found myself replacing the exceptions with `logging.error()` statements recently, and thought I'd bring it up for discussion whether to make this the official policy. The arguments for it are that you both get notified about the error (given a reasonable logging level), while still being able to continue working. The argument against it is that this can lead to these issues simply being ignored, which might cause bigger, unpredictable issues. 

Any thoughts?

I just want to make it clear from the start that I'm not decided myself what I think is the best policy, and will happily go along with whatever the consensus is :)

**Comment by francisco-dlp** [comment]
Unless there is an usage case in which trying to disconnect a function that is not connected is unavoidable, I personally prefer to let things as they are. Otherwise, to identify this sort of bugs we'll need to remember to check the log, meaning that we'll increase the chances of missing them...

**Comment by vidartf** [comment]
I always keep an eye on the console output of both logs and exceptions (and always run with log level of at least info), so I'm not so concerned about myself missing them. What I'm mostly concerned about are users who don't pay attention to either, but just say "It doesn't work". For those, the logging would be the best. On the other hand you have those that are tech-savvy enough to report an issue, but which can't be bothered to report something unless its preventing them from doing their work. For those, raising an exception should lead in more error reports at a slight cost of user happiness.

For the UI, possible solutions to both issues is to have a "Log window" to show log output (and allow the user to filter what is shown, and maybe also set at which levels it opens/highlights the window), and to install a program-wide exception handler that displays a message box on errors (possibly asking to abort, retry, or ignore?).

**Comment by vidartf** [comment]
As no one else has commented on this, I'm going to close this for now. However, if anyone has any new input, feel free to leave a comment and I'll reopen it.
