### ISSUE TITLE
Scipy 2016 abstract and authorship

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#928]
At the very last minute it has occurred to me that we should submit an abstract about HyperSpy to the Scipy conference. I've asked the current two main active contributors, @vidartf and @to266, if they'll be available to represent the project there, and @to266 has volunteered for this. We've been working on an abstract which is available to view and/or edit [here](https://docs.google.com/document/d/1Bbeor53gmFLLYPqxeBXUMbUNaiQEzy2JxK6OxzpKVUE/edit?usp=sharing). (If you would like to edit it, please "suggest" instead of editing directly. In this way, it will be easier to track changes, who wants what, etc . You can do that in the drop-down menu in the top-right in my case.)

We have to decide who will be added to the authors list. Many abstracts in past editions of the Scipy conference have only one author (the presenter). This is the simplest approach for us, as we have already 17 contributors and we can’t possibly add everybody to the abstract. Another option is to decide here who should be in.

As you know, there is no "HyperSpy paper". I have always been of the opinion that a paper about a software is bad for creating a community around it, since the authors of the paper cannot be amended when more people contribute to the project. However, not having a paper is also a bad thing for the project, as we have no way to show to funding agencies that the project is actually highly cited. So, although this is not the main topic, if we come out with a good answer to the "who should be author of abstracts and papers" question, we may actually start considering writing a paper about HyperSpy.

Unfortunately the time-frame to decide about the abstract is rather short (the deadline is tomorrow), so speak before it is too late!

@hyperspy/developers

**Comment by magnunor** [comment]
About HyperSpy author-list; I'm not really sure what the best solution is, I feel having the Zenodo is useful, and I'm using that reference in all the articles where I've used HyperSpy.

We could do something like the LIGO-article: http://journals.aps.org/prl/abstract/10.1103/PhysRevLett.116.061102 , where they've got "B. P. Abbott et al. (LIGO Scientific Collaboration and Virgo Collaboration)". "HyperSpy contributors"? But that doesn't really solve the problem with "updating" the author list as new people contribute...

**Comment by vidartf** [comment]
For the Scipy abstract, I'm not overly concerned either way (I see both kinds of patterns in the schedules of past conferences). However, there should probably be a reasonably clear acknowledgement at some point in a talk (or poster if that is applicable for Scipy). Preferably it should also be made clear in the abstract. Other than that, I would think that this would have been solved somewhere else in the open source landscape? If not, I'm not sure what I can contribute :)

**Comment by francisco-dlp** [comment]
Many thanks for all who have helped with the abstract.

@magnunor, I fully agree that the Zenodo DOI is useful. At some point I thought that it was the definitive solution to the problem, and maybe it is. However, the issue with it is that the most major academic databases don't track citations to software. The only exception that I know is [Microsoft Academic](https://academic.microsoft.com/). This is a general problem and, therefore, there are good chances that it'll get fixed for everybody at some point. The problem is that "at some point" may come too late for some.

The LIGO approach could be a solution. In this way, there'll be a standard paper that collects citations in the usual way, and we could direct people to github for up-to-date authorship. However, I think that it is unusual for a journal to accept papers without any single real author. Do you know of any that would be happy to do it? (I don't think that PRL would make another exception for us....)

Another intermediate possibility would be to have real authors (maybe just the developers and emeritus developers?), followed by "HyperSpy contributors". I think that this is more likely to be acceptable for a standard journal.

Or yet another would be to have absolutely everybody who has contributed until now, and aim at publishing papers about HyperSpy regularly with the sole purpose of updating the author's list. We'll have to have something new to say each time, but, the way things are going, that shouldn't be a problem.

A variation of the latter would be to publish the User Guide in Zenodo or maybe ArXiv. Citations to Zenodo documents are tracked by some academic search engines, and possibly Google Scholar would aggregate all previous citations to hyperspy in papers (if I'm not too wrong there should be ~100 now!).

The obvious drawback of having absolutely everybody who contributes in the author list is that some may contribute just 1 single small commit in order to get into the author list. This would be evident in the github contributors graph, but not in a list of authors in a paper or document. 

What do you think? (All opinions welcome!)

@vidartf, you wrote: "However, there should probably be a reasonably clear acknowledgement at some point in a talk (or poster if that is applicable for Scipy). Preferably it should also be made clear in the abstract. ". Could you (meaning all) suggest how would you like to make it clear this time (deadline today!)?

**Comment by to266** [comment]
I would also ask everyone to have a look at the title of the abstract - it's just something I made up when first writing it, so I'm slightly (though pleasantly) surprised that no one edited it...

**Comment by francisco-dlp** [comment]
It is above time to submit the abstract. Any comments?

**Comment by francisco-dlp** [comment]
For example: Tomas Ostasevicious and the HyperSpy developers?

**Comment by to266** [comment]
It seems difficult to add non-human co-authors... (You require name, surname, emails, etc.)

I will submit as the only author, but, if I (we) get the talk, I will definitely have a slide with all the contributors and their relative contributions.

I think I will share (in a similar manner as the abstract) at least part of the slides (maybe all?) for the other contributors to review before the talk at any rate.

**Comment by vidartf** [comment]
:+1:

**Comment by to266** [comment]
I am glad to let you know that the talk was accepted :)

**Comment by francisco-dlp** [comment]
Hooray!!

**Comment by vidartf** [comment]
As I'll be going to attend EuroSciPy this year, I've also planned to submit an abstract presenting HyperSpy. A modified version of the abstract is available [here](https://docs.google.com/document/d/1h8Diq1UkthTi9CB8c7-H_z4Ar01gmoKcx2P3Cm82jRQ/edit). To decrease the overlap with the SciPy entry, some cosmetic changes have been made, but I also intend for the focus of the presentation to be different (although the first half will probably be very similar).

Thoughts, suggestions, comments and corrections are all welcome :)

**Comment by francisco-dlp** [comment]
I forgot to mention that I got an oral at EuroScipy 2014 with an abstract that, in spirit, was similar to Tomas'. Therefore, I think that you'll increase your chances of getting an oral by shortening the description of the general purpose of HyperSpy and emphasizing the new features instead. I think that the succinct "I will also discuss the recent addition of several interactive tools, including chainable regions of interest." doesn't make these ultra-cool features justice. Also, wouldn't you like to speak about HyperSpyUI? I think that people will be very interested to hear about it.

**Comment by magnunor** [comment]
As a "HyperSpy" paper was mentioned earlier: I stumbled upon this on the Atomic Simulation Environment (ASE) mailing list. https://listserv.fysik.dtu.dk/pipermail/ase-developers/2015-November/003040.html 

In essence they're writing an article about the functionalities in ASE, which is a python based tool for analyzing atomistic simulations.

**Comment by vidartf** [comment]
@francisco-dlp Thanks. I've updated the abstract to take into account the points you made (all changes are in the last paragraph). I plan to submit it this evening.

**Comment by vidartf** [comment]
For HyperSpy paper, this new journal might be interesting (should take less than an hour): http://joss.theoj.org/about

**Comment by tjof2** [comment]
@vidartf that's what it was called! I totally forgot.

Also don't forget: http://depsy.org/package/python/hyperspy
