### ISSUE TITLE
interactive window doesn't popup 

### ISSUE THREAD

**Issue by Edsonp** [hyperspy/hyperspy#935]
I get the following error when trying to plot an SI with the command s.plot()

~/python3.5/site-packages/matplotlib/tight_layout.py:222: UserWarning: tight_layout : falling back to Agg renderer 
warnings.warn("tight_layout : falling back to Agg renderer")

I'm running hyperspy 0.8.4 on OSX el Capitan with python 3.5

**Comment by francisco-dlp** [comment]
Did you import hyperspy as follows?:

```python 

%matplotlib qt4
import hyperspy.api  as hs

```

**Comment by Edsonp** [comment]
thanks for your quick answer!!
I didn't import with `%matplotlib qt4` because it says invalid syntax, but yes I did import hyperspy with `import hyperspy.api  as hs`. I also chose qt4 as default toolkit in the preferences.
Apparently is an issue with matplotlib when opening interactive figures [http://stackoverflow.com/questions/15455029/python-matplotlib-agg-vs-interactive-plotting-and-tight-layout](url)
How could I go around this?

**Comment by jat255** [comment]
The `%matplotlib qt4` syntax is known as an IPython/Jupyter magic You need
to run that code from either a Jupyter shell or notebook (my preferred way
of doing it). (
http://jupyter-notebook-beginner-guide.readthedocs.org/en/latest/what_is_jupyter.html
)

On Mon, Apr 4, 2016 at 9:47 AM, Edsonp <notifications@github.com> wrote:

> thanks for your quick answer!!
> I didn't import with %matplotlib qt4 because it says invalid syntax, but
> yes I did import hyperspy with import hyperspy.api as hs. I also chose
> qt4 as default toolkit in the preferences.
> Apparently is an issue with matplotlib when opening interactive figures
> http://stackoverflow.com/questions/15455029/python-matplotlib-agg-vs-interactive-plotting-and-tight-layout
> <http://url>
> How could I go around this?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hyperspy/hyperspy/issues/935#issuecomment-205302483>
>



-- 
Joshua Taillon
Materials Science and Engineering
University of Maryland, College Park
www.joshuataillon.com

**Comment by francisco-dlp** [comment]
@Edsonp, did you manage to make it work. If yes, could you close the issue?

**Comment by Edsonp** [comment]
@francisco-dlp  yes it worked. Thank you!
