### ISSUE TITLE
Error when adding elements to an EDS Spectrum in hyperspy v. 0.8.4 with Anaconda 4.0 python v. 3.5

### ISSUE THREAD

**Issue by jrminter** [hyperspy/hyperspy#938]
I just did a clean install of the latest Anaconda python and installed hyperspy 0.8.4 via pip, creating a test environment with the supplied yml file in the git repository. 

When I create the test BAM EDS spectrum

> spec = hs.example_signals.EDS_SEM_Spectrum()

The metadata is fine. I wanted to test adding an element. There is a small Ar peak (it is a sputtered std...)

I can check the type of the existing array...

> spec.metadata.Sample.elements
array([b'Al', b'C', b'Cu', b'Mn', b'Zr'],  dtype='|S2')

which is as expected. When I add the element

> spec.add_elements(['Ar']) # it is sputtered...

I get an error that traces to line 297 _signals/eds.py (the add_elements function) that notes

297         self.metadata.Sample.elements = sorted(list(elements_))
TypeError: unorderable types: str() < numpy.bytes_()

I also tried

> spec.add_elements([b'Ar'])

but that did not help.

I can do this by brute force...

> el = np.array([b'Ar'])
> spec.metadata.Sample.elements = np.append(spec.metadata.Sample.elements, el) 

and add the element. Everything plots fine. But the add_elements() function should work...

**Comment by francisco-dlp** [comment]
Thank you for the (very detailed) bug report. This is a compatibility issue between HyperSpy for Py2 and HyperSpy 0.8.4 for Py3. A fix has just been submitted see #939.

**Comment by jrminter** [comment]
Thanks for the prompt action. Your knowledge of the package structure is invaluable. It never occurred to me that the issue was in the hdf5 save...

**Comment by francisco-dlp** [comment]
Thanks, happily HyperSpy's bus factor is well above one these days.

**Comment by to266** [comment]
https://github.com/hyperspy/hyperspy/pull/939
