### ISSUE TITLE
HyperSpy allows creation of illegal hdf5 files

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#942]
When writing to hdf5, hyperspy uses the `Signal` title as the name of a group inside the hdf5 structure. This works well in most cases, but "/" are illegal in hdf5 group names. HyperSpy doesn't complain on saving, but it raises an exception when loading the file.

This issue was reported by @thomasaarholt  in [gitter](@thomasaarholt )

**Comment by francisco-dlp** [comment]
How should we best fix this issue? Replace "/" with something else on saving? Stop using the title as the group name (this is convenient though...)?

**Comment by thomasaarholt** [comment]
I think replacing it with a "-" may be the best course of action? Saving as a ".dm3" also raises an error when trying to load it into DM or hyperspy. (otherwise I was going to propose perhaps making Hyperspy try to load it anyway)

**Comment by dnjohnstone** [comment]
Did we decide on a solution for this? @thomasaarholt's suggestion sounds not unreasonable to me.

**Comment by to266** [comment]
#1039
