### ISSUE TITLE
Signal indexing incorrectly listed in docs

### ISSUE THREAD

**Issue by bm424** [hyperspy/hyperspy#954]
Using the latest master version, I get
`TypeError: 'EDSTEMSpectrum' object is not subscriptable`
when attempting to slice any `Signal` or subclass. I tried to go back to basics with the simple examples [in the docs](http://hyperspy.org/hyperspy-doc/current/user_guide/tools.html#indexing), but get exactly the same issue:
```
>>> import hyperspy.api as hs
>>> import numpy as np
>>> s = hs.signals.Signal(np.arange(10))
>>> s[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'Signal' object does not support indexing
```

**Comment by to266** [comment]
It's not supposed to work - that is the old convention, and now we only support `inav` and `isig` indexing. There have been plenty of warnings that this behaviour will deprecate

**Comment by bm424** [comment]
Fair enough - should probably be removed from the docs then.

**Comment by dnjohnstone** [comment]
Working on this - will submit a documentation update for this later today.

**Comment by francisco-dlp** [comment]
#1023
