### ISSUE TITLE
FIX: tests preventing successful osx Travis CI

### ISSUE THREAD

**Issue by sem-geologist** [hyperspy/hyperspy#956]
as in #949 some test failures were detected only with newly enabled osx in Travis CI.

There are two tests where one hangs the test and time outs in 10 min whole build.

1. tests.io.test_hdf5.TestLoadingOOMReadOnly

Second is effect of too strict comparison of floating numbers, which on different platforms can fail (in our case it was always working on linux, but assertation fails on osx due to the last digit in very long floating point number differs):

```
FAIL: hyperspy.tests.signal.test_eds_sem.Test_metadata.test_take_off_angle
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/miniconda/envs/testenv/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/travis/build/hyperspy/hyperspy/hyperspy/tests/signal/test_eds_sem.py", line 189, in test_take_off_angle
    nt.assert_equal(s.get_take_off_angle(), 12.886929785732487)
AssertionError: 12.886929785732484 != 12.886929785732487
```

the problem here is that float numbers should be truncated to sane significant numbers and only then compared. By changing ```nt.assert_equal``` into ```nt.assert_almost_equal(s.get_take_off_angle(), 12.886929785732487, places=14)``` it is safe to run on different platforms. On python floating point numbers should be comparable with max 16 significant digits, thus the ```places=14```.

The fix of the second is very small and for now it is dealt in the #949.
However first needs to be investigated.
If wished it can be split to be separate pull request.

Update:
I noticed that there is many ```assert_equal``` used on the floating points in the tests. That causes random failure in Travis on Linux (and osx). I am opening separate issue and pull request for those.

**Comment by sem-geologist** [comment]
I investigated more the problem with osx at tests.io.test_hdf5.TestLoadingOOMReadOnly test

the lines at which travis osx hangs are those:

```python
260    @nt.raises(MemoryError, ValueError)
261    def test_in_memory_loading(self):
262        s = load('tmp.hdf5')
```

I am wondering what is the possibilities... maybe osx does not raise MemoryError but tries to finish the loading using swap (dynamic swap or some other tricks) so it slows down to such extent that test timeouts.
It would be best if somebody would have osx and could replicate the state.

**Comment by to266** [comment]
Yes, @dnjohnstone reported that as well - it loads to the swap, which is the expected behaviour for *NIX systems, but I did not anticipate when writing the test.

Could you test if you get the `MemoryError` if you try to create a numpy array that will not fit in both memory and swap?

It's a difficult problem to solve, as it requires to always explicitly create the file to be larger than all the available memory. Alternatively it may be possible to only run the test if the total memory is less than the required (hence testing that the "expected fail" is there on the test machines, like the travis and appveyor, but skipping the test on production machines)

**Comment by sem-geologist** [comment]
I am trying to do that.
firstly I injected psutil to setup.py to ckeck out how much memory there is.
I fear that test will not work, cause writing to swap can be too long than set timeout for travis (10min)

**Comment by sem-geologist** [comment]
looks travis for osx provides 4GB virtual memory for linux 8GB the wished hdf file have ~80Gb. that makes no surprise it hangs on osx. travis linux swap=0GB; travis osx have 1GB of swap... maybe it is dynamic swap? so it is trying to push that 80Gb into swap reclaiming disc space. I would try making the testing hdf5 array smaller, so that it would be larger than linux travis virtual memory, I would change one of dimention from 1000 to 110 so it would be about 9GB what do you think @to266 ?

**Comment by sem-geologist** [comment]
@to266 I have the idea, but that requires the psutils. we could decide dinamically at array creating moment to creat the array abit larger than available total memory.

**Comment by francisco-dlp** [comment]
@to266, what about removing this test all together? There must be a better way to check if the data was loaded to memory.

**Comment by to266** [comment]
Yeah, I will remove it and replace with a suitable combination of mocks....

**Comment by vidartf** [comment]
Did #959 fix this?

**Comment by sem-geologist** [comment]
as #949 got merged this can be closed
