### ISSUE TITLE
Built-in absorption correction in EDS quantification

### ISSUE THREAD

**Issue by siriagus** [hyperspy/hyperspy#962]
The mass-thickness is determined simultaneously with composition when using the zeta-factor method for EDS quantification. This makes it easy to implement absorption correction. In order to implement this, a database for mass absorption coefficients are needed. The database has been implemented in #797 and only needs a final review before it's ready to be merged. This issue should be resolved before the release of version 1.0.0. Absorption correction should also be implemented for the EDS cross section method.

**Comment by k8macarthur** [comment]
Absorption corrections doesn't currently exist for cross sections but I'm talking to Sergio (Lozano-Perez) who derived cross sections with me originally and we'll see what is possible to put together.

**Comment by dnjohnstone** [comment]
absorption correction is definitely a good move.... @pburdet was working on this - when he started adding stuff in this direction http://www.sciencedirect.com/science/article/pii/S0304399115300358

**Comment by k8macarthur** [comment]
Ok so just a point to note whilst I"m looking through this. The absorption correction equation used in zeta factors and originally taken from http://people.umass.edu/jig0/files/70.pdf has a geometric correction factor which is assuming a small side-entry EDX detector. Therefore it's not directly applicable to, for example, the ChemiSTEM quadrant detector. I don't believe anyone in the community is tackling this yet but it might be worth bearing in mind coding this in a way which allows the geometric factor to be adjusted or chosen in the future incase a better equation is found for modern detectors?

**Comment by dnjohnstone** [comment]
@k8macarthur this is an excellent point - I've had some conversations with people over here about this and we think the Manchester group may have presented something at EMAG on this vein -- I think this falls a touch outside the scope of immediate HyperSpying... If you want people to collaborate on that though I reckon hooking you up with some tomographers wouldn't be too difficult....

**Comment by k8macarthur** [comment]
I agree, it's not in the immediate scope of Hyperspy but it is worth bearing in mind when coding an absorption correction function that hopefully different geometric corrections might be available to new generations of detectors in the future.

**Comment by k8macarthur** [comment]
@siriagus the standard units of z-factors would be kg/m^2 right?

**Comment by siriagus** [comment]
@k8macarthur I usally give them as (kg * electron)/(m^2 photon) where electron comes from the total electron dose and photon comes from the intensity (integration over line peak). That is also the same notation used in Watanabe and Williams (2006).

In other news, I used the database in #797 to implement the absorption correction. It needs some changes before it's complete, but it appears to work rather well. :)

**Comment by dnjohnstone** [comment]
ok --- what are the changes?

**Comment by siriagus** [comment]
@dnjohnstone Sorry, bad wording. What I meant is that I am not sure that the way I implemented it is the best way. I've added the absorption correction as part of eds_tem.py, but I should probably add it in eds\utils.py instead as it currently does a lot of unoptimized step as I needed the composition to be a list of signals while it is sent as an np.array (thereby loosing element information, unless I pass this as a seperate argument) when calling quantification from eds\utils.py. Element information must be preserved in order to do absorption correction. What I could do is tidy up and make a pull request of what I think is a good solution and then rewrite it if somebody have a better suggestion.

**Comment by dnjohnstone** [comment]
@siriagus ah awesome, that's excellent news.... It sounds like you might be right that this method should go to eds/utils.py but we do need to bear in mind that in an ideal world there should probably be two methods each optimised for SEM and TEM.

I'd say go ahead with a PR as soon as you have something that broadly speaking works and then we can hash out the details online :)

**Comment by dnjohnstone** [comment]
PS... If that means this means that you think #797 is good to go, please say so on that PR so we can get that merged up and keep your new PR more managable in terms of difference from the master.

**Comment by siriagus** [comment]
@dnjohnstone I am pretty sure #797 is almost good to go, just need a bit more time to look through it properly to make sure.

**Comment by k8macarthur** [comment]
My side of absorption correction may take longer as I try to understand how best to implement. However in the short term I've written two quick functions which convert between zfactors and cross sections #988

**Comment by dnjohnstone** [comment]
Do you think it's important for cases where cross-sections are likely to be used (i.e. very small things) - to my mind it will basically boil down to people should use Zeta for thick stuff, and cross sections for small stuff where an output in atoms is good... Or did I miss something about why cross-sections has an advantage more generally?

**Comment by k8macarthur** [comment]
Cross sections also provide the benefit that they're on the same scale and units of quantification for EELS and ADF STEM. That's why they were designed. So I think long term absorption correction would be helpful. However, short-term people should be able to make use of the conversion functions.

**Comment by k8macarthur** [comment]
Resurrecting an old thread rather than starting a completely new one....

I've finished writing a function which does absorption correction for cross sections which could easily be modified/added to for z-factors/k-factors. I'd like to find some experimental data to apply the cross section party to really check that it works before I make up an actual pull request, but if anyone would like a copy to modify for the other methods just let me know. :)

**Comment by jeinsle** [comment]
I have a data set you could look at if interested. One analysis of it has got it to with 2% of what we expect but any improvements beyond that would be awesome. Let me know if interested. 

J

**Comment by tjof2** [comment]
Closed in #2258?
