### ISSUE TITLE
General documentation improvements

### ISSUE THREAD

**Issue by dnjohnstone** [hyperspy/hyperspy#964]
The documentation is improving slowly but there are various things that could be improved, which I keep noticing and then forgetting about because they're rarely an immediate priority. Nevertheless, I think it would be good if we collectively work to keep this improving particularly for upcoming workshops in the summer conference period.

Here is an initial list:

1.  Dielectric function tools should probably be documented under EELS for the time being, in my opinion.

2. In many places, right now I'm thinking EDS sections, there is quite a bit of dodgy grammar going on.

3. Decomposition sections could be improved to direct new users to some appropriate literature, or at least make it unavoidably obvious that the stuff in scikit-learn should be read. In the places where papers are already mentioned the referencing should be updated to be consistent with the Egerton paper and with recent EDS contributions.

4. There is absolutely no documentation associated with events (e.g. how that's implemented and therefore how to connect things properly for developers) nor is there anything associated with ROIs -- the latter is certainly necessary for 1.0.0 but it's unclear to me who is taking that forward now.

**Comment by tjof2** [comment]
@dnjohnstone I'm happy to look at grammar for starters (I'm looking at EDS right now, in fact...)

**Comment by francisco-dlp** [comment]
There is documentation for [ROIs](http://hyperspy.readthedocs.io/en/latest/user_guide/tools.html#region-of-interest-roi) and [events](http://hyperspy.readthedocs.io/en/latest/user_guide/events.html).

In a recent private communication, @mwalls pointed to some additional documentation issues and volunteered to enhance the Getting Started section of the User Guide to make it more newbie friendly.

To give to this issue the attention that it deserves, I propose to make this a permanent issue to discuss documentation improvements i.e. I'll assign it to the 1.0 milestone, but we'll  move it to the 2.0 once we release 1.0 and so on.

**Comment by dnjohnstone** [comment]
Ah thanks @francisco-dlp - incidentally, is it written anywhere how to read those docs associated with the master?

**Comment by francisco-dlp** [comment]
Good point, no, it's not.

**Comment by tjof2** [comment]
-  The Image tools documentation isn't particularly enlightening, e.g. _"The align2D() method provides advanced image alignment functionality, including subpixel alignment."_ - without going into what the rest of functionality is or how to use it!

**Comment by dnjohnstone** [comment]
Previously we've discussed raising the visibility of contributors - long term this may be through splitting the code or re-working the website... A simple approach is to make clear in the documentation where particular people have been responsible for large sections. For example a simple sentence explaining that Pierre Burdet did most of the EDX and that Kate MacArthur added her part, where it is described could be one approach.

**Comment by francisco-dlp** [comment]
I think that currently there is no better way to know who has done what than looking at the pull requests and commits in GitHub. In this way you can see who has coded what, who has offered guidance and help, where the idea originated etc. This is so much better than the equivalent in scientific papers: authors list and acknowledgements. I wish there was such a fair system in place for publishing scientific journals.

Therefore, I feel that adding who's done what in the docs is a step backwards, and may cause unnecessary friction in what at present is a very nice community. Also, normally the users are not interested in this information, and for them sentences describing who has done what come become just an annoyance. Recruiters are, but contributors can simply list what they've contributed to HyperSpy in their CVs and the recruiter can easily verify the information in GitHub if needed. Again, so much better than an ordinary list of papers in a CV where often it's impossible to know what each author has actually contributed.

**Comment by dnjohnstone** [comment]
http://hyperspy.readthedocs.io/en/latest/user_guide/tools.html#signal-indexing

This indexing section seems quite out of date to me - wont' a lot of these examples raise errors even in 0.8.4?

**Comment by tjof2** [comment]
The [Machine learning section](http://hyperspy.readthedocs.io/en/latest/user_guide/mva.html) could also do with a look - I'll see if get some time today

**Comment by francisco-dlp** [comment]
@dnjohnstone, yes, see #954

**Comment by tjof2** [comment]
Regarding "Machine Learning", based on a comment by @dnjohnstone stating _"the main issue with the machine learning section was that there is absolutely no reference to the fact that the decomposition() method allows you to use any of the methods from scikit-learn -- for example NMF or SparsePCA. We should be linking to the scikit-learn docs and explaining that these are all available I think...."_, the introductory paragraph needs expanding upon:

> HyperSpy provides easy access to several "machine learning" algorithms that can be useful when analysing multi-dimensional data. In particular, decomposition algorithms, such as principal component analysis (PCA), or blind source separation (BSS) algorithms, such as independent component analysis (ICA), are available through the methods described in this section.



Plus, at some point, it probably needs a complete section on NMF (I suggest after PCA+denoising, and either before or after BSS/ICA), with perhaps a link/reference to an example of the use of NMF, in the same vein as the PCA and ICA examples.

**Comment by dnjohnstone** [comment]
I have noticed inconsistency in the symbols that indicate header level...

As far as I can make out the correct set should be:

level 1 is *
level 2 is -
level 3 is ^

Please correct me if I'm wrong but this would be good to have consistent between all .rst files

**Comment by tjof2** [comment]
Yes, there are some that use =

**Comment by dnjohnstone** [comment]
@mwalls with respect to your recent pull request on install documentation this conversation may be the right place to log anything that you find inadequate - certainly very valuable to know.

**Comment by mwalls** [comment]
Ok I'm trying to get the hang... I will suggest stuff here - good idea, but since I do not wish just to carp, but to try and make improvements myself, I will make pull requests sometimes in the relevant section. 
While I'm on, does anyone have any comment about the "Conda environment" section in the installation instructions? I do not know what this is. I think it should be made clear whether it is optional/recommended/essential or what, and for which platforms, and what it actually does.

**Comment by francisco-dlp** [comment]
@to266 and I just discussed the future of the conda environment yesterday and we decided to simply remove it in favour of something more user friendly. It'll probably happen soon.

**Comment by mwalls** [comment]
Ok I'm now on the "Getting started" page. As I've mentioned to Francisco, I have some difficulties with this. I'll just start with the first couple. Remember that a user who has just installed the bundle, for example,  will next read this part next to try and get going. The section begins with:

> HyperSpy is a Python library for multi-dimensional data analysis. HyperSpy’s API can be imported as any other Python library as follows:
>>>
>>> import hyperspy.api as hs

A new user who has just installed the windows bundle has not yet got to a place where he can execute this command. I think this first part should be cut as it is included later on again anyway, after the notebook has been started. 

Anyway, the next thing we read is:

> "In all operating systems (OS) you can start IPython by opening a system terminal and executing ipython, optionally followed by the frontend"

In Windows I do not appear to have a terminal that can execute this command. The command line prompt and the power shell give an error message, although the bundle has been installed. In addition, we are several persons here who do not know what the frontend is. I cannot suggest a specific change since I don't know what to do,
There are more problems further on but maybe we could start with these?

**Comment by tjof2** [comment]
@mwalls all good points - I think there will be a Python executable in the bundle install location that *is* the terminal you're looking for...

**Comment by francisco-dlp** [comment]
You are absolutely right. Most people install HyperSpy using the bundle and, hence they can't start HyperSpy from a standard terminal, they need to use the `WinPython Prompt` that can be found in the `Start Menu` under `HyperSpy WinPython Bundle`.

(just saw @tjof2 comment which, more succinctly, says the same)

**Comment by tjof2** [comment]
@francisco-dlp @mwalls  it's perhaps also worth pointing out that, on my Windows 10 machine at home, I don't have a Start Menu entry for any of this...I don't know what exactly changed on Windows 10.

**Comment by francisco-dlp** [comment]
Probably it'll be best to suggest that all bundle users use the context menu entries.

**Comment by mwalls** [comment]
I agree. I've just tried with  WinPython terminal. after a bit of research I guessed at the "frontend". Trying "ipython qtconsole" seemed to work ok, but for the notebook it seems you don't type ipython, but just "jupyter notebook", except that when it opens, you get a 404. So yes, let's jut recommend the context menus for windows.

**Comment by francisco-dlp** [comment]
The Start Menu entries for the notebook and qtconsole should also work.

**Comment by mwalls** [comment]
In my case, the qt console Start menu entry works. The Jupyter Notebook tries, it launches an ephemeral command prompt, but does not produce a browser tab.

**Comment by mwalls** [comment]
I've just suggested some changes in a request, but it's far from complete...

**Comment by francisco-dlp** [comment]
This bundle thing is a nightmare... I'm very close to propose getting rid of it...

**Comment by francisco-dlp** [comment]
which request?

**Comment by mwalls** [comment]
I thought I'd done one?  I'll try and check. Incompetence...

**Comment by magnunor** [comment]
One idea for the "Getting started -> Starting HyperSpy" at http://hyperspy.readthedocs.io/en/latest/user_guide/getting_started.html#starting-hyperspy could be to split it into different operating systems, since they can vary a great deal. 

For example, having one for Windows, one for OS X and one for GNU/Linux users.

After the HyperSpy environment has been started, we go back to not having it split (like we currently have).

**Comment by magnunor** [comment]
Just read through https://github.com/hyperspy/hyperspy/pull/1032/files, and I see that is exactly what is being done :) So disregard my comments above.

**Comment by mwalls** [comment]
I have now been trying with the help of the docs to use "align1D()". I have an SI that I want to align according to a particular spectral peak around 465 eV. I typed `sa=s.align1D(start=463.0,end=466.0) ` The code seemed to run and I got a progress bar which ran twice. I'm guessing once to measure the shifts and once to apply them to the data?  However the object sa, which I hoped would be the re-aligned SI appear not to contain anything much. It can't be plotted or printed. I do not get a map of the shifts, or if I do I don't know where to find it. In the command description it gives the following description of what the command returns (which appears to be truncated):

> Return type:	  An array with the result of the estimation. The shift will be

How is this array visualised? What is it called? I'm afraid I cannot upgrade this part of the doc either, as I don't know what to put, but I think maybe it needs some attention

**Comment by to266** [comment]
the `align1D` command overwrites the current signal by default with the aligned version (so after running the `s` should be aligned).

The shifts are not returned explicitly if `align1D` is called. If you want shifts, the equivalent workflow is as follows:
```python
shifts = s.estimate_shifts1D()
s.shift1D(shifts)
```
This is essentially what the `align1D` does, just in one line, and not returning the intermediate results (shifts)

**Comment by francisco-dlp** [comment]
@mwalls, that is a documentation bug, thank you for reporting it. I've just sent a PR to fix it see #1051

**Comment by mwalls** [comment]
Ok thanks, I suspected maybe that was it, although I could see no difference in my data after this routine (maybe it's probably the data - I'll try and find a better set). However, I still think the doc needs some work. I'll try and make a suggestion later on, but may get the jargon wrong.

**Comment by dnjohnstone** [comment]
Closing because, on reflection, this was too general a topic an a number of separate issues are now all hard to find by searching because they're all tied up in here. Separate issue numbers for each bit of dodgy/lacking documentation will be better.
