### ISSUE TITLE
Linear least squares fitting - choosing the right algorithm

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#968]
I'm struggling trying to choose the right algorithm to incorporate into Hyperspy to do MLLS fitting. Currently I'm using [`LinearRegression`](http://scikit-learn.org/dev/modules/generated/sklearn.linear_model.LinearRegression.html) from scikit-learn. Unfortunately, the `residual` returned by its methods is being deprecated. I've raised an issue about this on [their github](https://github.com/scikit-learn/scikit-learn/issues/6734).

Alternatives include [numpy's `lstsq`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.lstsq.html) and [scipy's `lstsq`](https://docs.scipy.org/doc/scipy-0.17.0/reference/generated/scipy.linalg.lstsq.html).

I'm basically trying to find the easiest way to do this.

**Comment by francisco-dlp** [comment]
Personally I would simply pick  scipy's lstsq because sklearn's regression is just a wrapper around it. For something so simple, I think that we'll be better off getting it from the source.

We could also take it from numpy, but usually functions that are available from both scipy and numpy tend to be faster in scipy.

**Comment by tjof2** [comment]
A relevant thread: http://stackoverflow.com/questions/29372559/what-is-the-difference-between-numpy-linalg-lstsq-and-scipy-linalg-lstsq

But it looks like scipy now uses `xGELSD` by default anyway - plus offers a method option to change the LAPACK routine anyway,

**Comment by tjof2** [comment]
See ~#1321~ ~#1462~ #2422

**Comment by tjof2** [comment]
I think you can close this @thomasaarholt  given #2422 ?

**Comment by thomasaarholt** [comment]
4 years later :p
