### ISSUE TITLE
align2D

### ISSUE THREAD

**Issue by RowanLeary** [hyperspy/hyperspy#970]
Has the documentation for align2D completely disappeared, or am I looking in completely the wrong places?! :)

If/once found, it might be helpful to have a short example useage. (The previous documentation was a little unclear).

**Comment by dnjohnstone** [comment]
One for #964,

All that exists at present is http://hyperspy.org/hyperspy-doc/current/user_guide/image.html

Yes you're right, that would be better - do you feel like writing and example?

**Comment by francisco-dlp** [comment]
This is one of many examples of things that could be better documented in the User Guide. The docstring documentation, without being excellent, at least is complete. Obviously, for such a complex and useful functions, it would be better if we had it well documented in the User Guide too.

**Comment by dnjohnstone** [comment]
I was discussing align2D with a few people and we also need to improve clarity regarding when sub-pixel shifts are obtained/applied... A number of people find that they only get pixel level shifts which puts them off. Can be improved with documentation but I think also the implementation might be enhanced using scikit-image which has it's own alignment implementation now.

**Comment by dnjohnstone** [comment]
The phase correlation plot that can be output from this tool is also very strange - most people, I think, would expect this phase correlation to be peaked in the centre of the image and might use it to adjust image processing parameters for obtaining better alignment. At the moment all the plots I get have intensity primarily in the corners.

**Comment by francisco-dlp** [comment]
@vidartf sent a PR some time ago to get the subpixel accuracy feature from skimage. As I remember the only thing missing was phase correlation. 

I fully agree that the docs on this feature need a lot of care.

**Comment by dnjohnstone** [comment]
@francisco-dlp do you know why the phase correlation plot tends to look weird at the moment?

**Comment by tjof2** [comment]
@dnjohnstone  Are they at the corners due to an FFT origin shift? Often happens in MATLAB.

**Comment by dnjohnstone** [comment]
I think that's very likely.... we should probably stop that though, because it's a pain if you're trying to adjust image processing parameters and get a better alignment

**Comment by tjof2** [comment]
@dnjohnstone [`numpy.fft.fftshift`](http://docs.scipy.org/doc/numpy-1.10.4/reference/generated/numpy.fft.fftshift.html)?
