### ISSUE TITLE
Non-Integer Binning of Spectra

### ISSUE THREAD

**Issue by k8macarthur** [hyperspy/hyperspy#971]
I'm quite interested in a method for binning the spectra by a non-integer number of pixels (using a linear interpolation to preserve counts). This would be much like the imresize function in Matlab but extend into larger dimensions. Certainly for spectrum images it would be far better to bin the data before carrying out any spectral analysis for the best signal to noise. What are other people's interests in this?

**Comment by dnjohnstone** [comment]
definitely doable - you want to build it on the rebin() method here.... https://github.com/hyperspy/hyperspy/blob/ea59b223c5e1301c097d0b24d126e93c003d4ae0/hyperspy/misc/array_tools.py

**Comment by jat255** [comment]
This would be a very welcome addition! I use the `rebin` method frequently for EDS , and it is quite a pain to have to manually specify an evenly-divisible integer for rebinning. It would be much easier to not have to worry about the even divisor problem.

**Comment by magnunor** [comment]
This would be very nice!

I guess using https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interpn.html#scipy.interpolate.interpn would be a way to do this?

**Comment by k8macarthur** [comment]
Does anyone have the time or inclination to help me code it? I think it might be a little beyond my coding ability, at least I'm not really sure where to start.

**Comment by francisco-dlp** [comment]
I think that using `interpn` as @magnunor suggests followed by a normalisation step to guarantee that the number of counts stay the same sounds like a good approach. However, it think that `interpn` could be more demanding in computing resources than the current method when applied to the same problem. I ignore if there is a better way of doing this, but I suggest doing a little research on the best approach to solve this problem before starting coding.

**Comment by tjof2** [comment]
Would http://docs.scipy.org/doc/scipy-0.17.0/reference/generated/scipy.misc.imresize.html work?

**Comment by francisco-dlp** [comment]
That wouldn't work for ndim.

**Comment by k8macarthur** [comment]
Ok, so I've been playing around with this for the last couple of weeks and I've got something which is starting to work. However, I've only managed to get it to work on 2D np.arrays and not on spectral images. Any tips or advice on how to make it more general would be gratefully appreciated. :)

`width = 2
height = 2
step = float(0.35)
originalSpectrum = np.ones([3, 3])
Spectrum = np.zeros([math.ceil(width/step), height])
newSpectrum = np.zeros([math.ceil(width/step), math.ceil(height/step)])
for j in range(0, height):
    for i in range(0, math.ceil(width/step)):
        bottomPos = (i*step)
        topPos = ((1 + i) * step)
        if topPos > width:
            topPos = width
        if (math.ceil(bottomPos) - bottomPos) > step:
            Spectrum[i, j] = originalSpectrum[(math.floor(bottomPos)-1), j] * step
        else:
            Spectrum[i, j] = originalSpectrum[(math.floor(bottomPos)-1), j] * (math.ceil(bottomPos) - bottomPos)
        k = math.ceil(bottomPos) 
        while k < (math.floor(topPos)):
            if k <= width:
                Spectrum[i, j] = (Spectrum[i, j] + originalSpectrum[k, j])
                k += 1

        if k < topPos:
            if k < width:
                Spectrum[i, j] = (Spectrum[i, j] + originalSpectrum[k, j] * 
                          (topPos - k))


for i in range(0, math.ceil(width/step)):
    for j in range(0, math.ceil(height/step)):
        bottomPos = (j*step)
        topPos = ((1 + j) * step)
        if topPos > width:
            topPos = width
        if (math.ceil(bottomPos) - bottomPos) > step:
            newSpectrum[i, j] = Spectrum[i, (math.floor(bottomPos)-1)] * step
        else:
            newSpectrum[i, j] = Spectrum[i, (math.floor(bottomPos)-1)] * (math.ceil(bottomPos) - bottomPos)
        k = math.ceil(bottomPos)
        while k < (math.floor(topPos)):
            if k <= width: 
                newSpectrum[i, j] = (newSpectrum[i, j] + Spectrum[i, k])
                k += 1

        if k < topPos:
            if k < width:
                newSpectrum[i, j] = (newSpectrum[i, j] + Spectrum[i, k] * 
                                    (topPos - k))
print(Spectrum)
print(newSpectrum)`

**Comment by dnjohnstone** [comment]
@k8macarthur can you not simply convert your spectrum image to a stack of images (i.e. one for each energy channel) using the "as_signal2D" method. Then you can resize each image and convert it back to a spectrum image using "as_signal1D".... The job should then be done?

**Comment by to266** [comment]
The rebinning in each dimension is independent of the others, so you could in principle do something like this:
`(X, Y | Z) -> (X, Y | Z') -> (Z', Y| X) -> (Z', Y | X') -> etc.`

FYI This same operation could be done (assuming the original signal in question has more than 1 dimension) with the @tjof2 suggested function like so
`(X | Y, Z) -> (X | Y', Z') -> (Z' | Y', X) -> (Z' | Y', X')`

**Comment by k8macarthur** [comment]
@dnjohnstone I hadn't thought about that, but would that be rather computation intensive?

@to266 I was thinking along those lines to try and make it more general however the sticking point I'm having is how to get each vector/image to add element wise once I have sectioned the data cube?

**Comment by dnjohnstone** [comment]
My proposal is almost certainly not the most elegant - but based on the time it takes to apply an affine transform to a stack of say 15000 images I recon it will take less than a minute in total for something of a similar size... Certainly not more than a couple of minutes.

It will also take only about 5 mins to code - so that's a plus.

**Comment by to266** [comment]
https://gist.github.com/to266/886230b93617f6a1b0bc23b86272b83f

Here is a quick example

The slight problem is the interpolation and floats, which results in slightly drifting sum value of the array

**Comment by dnjohnstone** [comment]
Did the suggestion from @to266 do what you wanted @k8macarthur

**Comment by k8macarthur** [comment]
Unfortunately not had a chance to revisit this again yet. It has gotten rather knocked down my 'to do list' until after EMC.

**Comment by k8macarthur** [comment]
Ok so I think I have something that works! :)

**Comment by k8macarthur** [comment]
``` python
def linear_bin(originalSpectrum, step):

    """
    Binning of the spectrum image by a non-integer pixel value.

    Parameters
    ----------
    originalSpectrum: numpy.array
        the original spectrum 
    step: either float of new pixel diameter
        or list of floats with the pixel diameter for each dimension.

    Return
    ------
    numpy.array of the spectrum with new dimensions width/step.
    """

    shape = originalSpectrum.data.shape
    width = shape[0]
    height = shape[1]
    energy = shape[2]

    Spectrum = np.zeros([math.ceil(width/step), height, energy], dtype='float')

    newSpectrum = np.zeros([math.ceil(width/step), math.ceil(height/step), energy], dtype='float')

    for j in range(0, width):
        for i in range(0, math.ceil(height/step)):
            bottomPos = (i*step)
            topPos = ((1 + i) * step)
            if topPos > height:
                topPos = height
            while (topPos - bottomPos) >= 1:
                if math.ceil(bottomPos) - bottomPos != 0:
                    Spectrum[i, j] = Spectrum[i, j] + originalSpectrum.data[math.floor(bottomPos), j] * (math.ceil(bottomPos) - bottomPos)
                    bottomPos = math.ceil(bottomPos)
                else:
                    Spectrum[i, j] = Spectrum[i, j] + originalSpectrum.data[bottomPos, j] 
                    bottomPos += 1
            if topPos != bottomPos:
                Spectrum[i, j] = Spectrum[i, j] + originalSpectrum.data[math.floor(bottomPos), j] *(topPos - bottomPos)

    for i in range(0, math.ceil(height/step)):
        for j in range(0, math.ceil(width/step)):
            bottomPos = (j*step)
            topPos = ((1 + j) * step)
            if topPos > width:
                topPos = width
            while (topPos - bottomPos) >= 1:
                if math.ceil(bottomPos) - bottomPos != 0:
                    newSpectrum[i, j] = newSpectrum[i, j] + Spectrum[i, math.floor(bottomPos)] * (math.ceil(bottomPos) - bottomPos)
                    bottomPos = math.ceil(bottomPos)
                else:
                    newSpectrum[i, j] = newSpectrum[i, j] + Spectrum[i, bottomPos]
                    bottomPos += 1
            if topPos != bottomPos:
                newSpectrum[i, j] = newSpectrum[i, j] + Spectrum[i, math.floor(bottomPos)] * (topPos - bottomPos)

    return newSpectrum
```

**Comment by k8macarthur** [comment]
Currently it only does square binning and 3D spectrum. I also haven't worked out how to produce it a a spectrum format with all the metadata yet.

**Comment by tjof2** [comment]
`float of new pixel diameter`? Are we using circular pixels now?!?

**Comment by k8macarthur** [comment]
Oops! 

Stylistic-wise, this function has largely been written with the aim of 3D spectrum image data in mind. I'm not sure my coding ability is good enough to make it more general.

**Comment by tjof2** [comment]
@k8macarthur  Because I'm struggling to get this to work, if I have an EDS spectrum of size `(40, 40, 4000)` and I want it to be size `(40, 40, 2048)`, what should my input be?

**Comment by k8macarthur** [comment]
That's because this was I was thinking about spatial binning rather than binning in the energy dimension. I'll see if I can broaden it to allow that...

**Comment by to266** [comment]
I'm almost done writing a more general and possibly quicker function for this, which I'll post here. Once I do, please let me know if the behavior seems reasonable..

**Comment by to266** [comment]
``` python
from scipy.ndimage import zoom
import numpy as np

def any_rebin(signal, new_shape):
    """Rebins the given signal to a new shape.

    Linear interpolation is performed, the dtype of the data is preserved.

    Parameters
    ----------
    signal : BaseSignal
        the signal to rebin
    new_shape : iterable
        the new (required) signal (NOT DATA!) shape.

    Returns
    -------
    new_signal
    """
    data = signal.data
    this_shape = data.shape
    assert len(new_shape) == len(this_shape)

    am = signal.axes_manager
    temp = [i for i in zip(new_shape, am._get_axes_in_natural_order())]
    temp.sort(key=lambda x: x[1].index_in_array)
    new_data_shape = [i[0] for i in temp]

    zoom_factors = np.array(new_data_shape) / np.array(this_shape)
    this_sum = data.sum()
    new_data = zoom(data, zoom_factors, output=data.dtype, order=1, prefilter=False)
    new_data  *= this_sum / new_data.sum()
    newsignal = signal._deepcopy_with_new_data(new_data)
    for ax, zoom_factor in zip(newsignal.axes_manager._axes, zoom_factors):
        ax.scale /= zoom_factor
    newsignal.get_dimensions_from_data()
    return newsignal
```

**Comment by k8macarthur** [comment]
Ok, I made an attempt at cycling through each of the axis in turn with np.swapaxes but got myself confused.

**Comment by tjof2** [comment]
@to266 on my `40x40x4000` dataset to `40x40x2048` (my original problem), works a treat, takes ~0.2s

**Comment by k8macarthur** [comment]
Is it still linear? Do you keep the same total counts in the spectrum?

**Comment by tjof2** [comment]
Same counts and the summed spectrum looks good to me.

**Comment by k8macarthur** [comment]
Works well for up sampling on my simple test cases as well. :)

**Comment by to266** [comment]
My bad, this seems to work differently, not actually rebinning the data.

**Comment by tjof2** [comment]
What is it doing then?

**Comment by to266** [comment]
I "force" the total counts to be constant myself.

The way this does the "zooming" is by keeping the first and last arrays element of the dimension in question, and them interpolating linearly for the "in between" elements, i.e.

```
[0 1 2 3 4 5 6 7 8 9]
```

turns into 
`[0 <however many things you want in the middle> 9]`

this is then rescaled so that the total number of counts is preserved (by me)... This is not exactly what we want though. Just to make sure you are aware

**Comment by to266** [comment]
I'll have a think if, given now I kind of understand how this works, I can wrangle it to actually do the right thing...

**Comment by k8macarthur** [comment]
As an alternative I think I have my iterations working:

**Comment by k8macarthur** [comment]
`def linear_bin(originalSpectrum, step):

```
"""
Binning of the spectrum image by a non-integer pixel value.

Parameters
----------
originalSpectrum: numpy.array
    the original spectrum 
step: float of new pixel width
    or list of floats with the pixel diameter for each dimension.

Return
------
numpy.array of the spectrum with new dimensions width/step.
"""

shape = originalSpectrum.data.shape

spectrum = originalSpectrum.deepcopy()
s = spectrum.data

for k, step in enumerate(step):
    shape = s.shape
    newSpectrum = np.zeros((math.ceil(shape[0]/step), shape[1], shape[2]), dtype='float')
    if k != 0:
        np.swapaxes(s, 0, k)
        shape = s.shape
        newSpectrum = np.zeros((math.ceil(shape[0]/step), shape[1], shape[2]), dtype='float')
    for j in range(0, math.ceil(shape[0]/step)):
        bottomPos = (j*step)
        topPos = ((1 + j) * step)
        if topPos > shape[0]:
            topPos = shape[0]
        while (topPos - bottomPos) >= 1:
            if math.ceil(bottomPos) - bottomPos != 0:
                newSpectrum[j] = newSpectrum[j] + s[math.floor(bottomPos)] * (math.ceil(bottomPos) - bottomPos)
                bottomPos = math.ceil(bottomPos)
            else:
                newSpectrum[j] = newSpectrum[j] + s[bottomPos]
                bottomPos += 1
        if topPos != bottomPos:
            newSpectrum[j] = newSpectrum[j] + s[math.floor(bottomPos)] *(topPos - bottomPos)
    if k != 0:
        np.swapaxes(newSpectrum, 0, k)
    spectrum = spectrum._deepcopy_with_new_data(newSpectrum)
    s = spectrum.data

return spectrum`
```

**Comment by k8macarthur** [comment]
The only thing I'm not sure I've got is the correct metadata and how to update that for the new spectrum.

**Comment by k8macarthur** [comment]
@tjof2 this should now work on your data if you put [1, 1, 4000/2048] or whatever the ratio you want to bin by in the energy dimension is.

**Comment by k8macarthur** [comment]
step: a list of floats for each dimension specify the new:old pixel
    ratio 
    e.g. a ratio of 1 is no binning
         a ratio of 2 means that each pixel in the new spectrum is 
         twice the size of the pixels in the old spectrum.

**Comment by k8macarthur** [comment]
Fixed an error in axes switching, this should now work:

**Comment by k8macarthur** [comment]
``` python

def linear_bin(originalSpectrum, step):

    """
    Binning of the spectrum image by a non-integer pixel value.

    Parameters
    ----------
    originalSpectrum: numpy.array
        the original spectrum 
    step: a list of floats for each dimension specify the new:old pixel
    ratio 
    e.g. a ratio of 1 is no binning
         a ratio of 2 means that each pixel in the new spectrum is 
         twice the size of the pixels in the old spectrum.

    Return
    ------
    numpy.array of the spectrum with new dimensions width/step.
    """

    shape = originalSpectrum.data.shape
    if len(shape) != len(step):
        raise ValueError(
           'The list of bins must match the number of dimensions, including the energy dimension.'
            'In order to not bin in any of these dimensions specifically, simply set the value in shape to 1')

    spectrum = originalSpectrum.deepcopy()
    s = spectrum.data

    for k, step in enumerate(step):
        shape = s.shape
        newSpectrum = np.zeros((math.ceil(shape[0]/step), shape[1], shape[2]), dtype='float')
        if k != 0:
            s = np.swapaxes(s, 0, k)
            shape = s.shape
            newSpectrum = np.zeros((math.ceil(shape[0]/step), shape[1], shape[2]), dtype='float')
        for j in range(0, math.ceil(shape[0]/step)):
            bottomPos = (j*step)
            topPos = ((1 + j) * step)
            if topPos > shape[0]:
                topPos = shape[0]
            while (topPos - bottomPos) >= 1:
                if math.ceil(bottomPos) - bottomPos != 0:
                    newSpectrum[j] = newSpectrum[j] + s[math.floor(bottomPos)] * (math.ceil(bottomPos) - bottomPos)
                    bottomPos = math.ceil(bottomPos)
                else:
                    newSpectrum[j] = newSpectrum[j] + s[bottomPos]
                    bottomPos += 1
            if topPos != bottomPos:
                newSpectrum[j] = newSpectrum[j] + s[math.floor(bottomPos)] *(topPos - bottomPos)
        if k != 0:
            newSpectrum = np.swapaxes(newSpectrum, 0, k)
        spectrum = spectrum._deepcopy_with_new_data(newSpectrum)
        s = spectrum.data
        spectrum.get_dimensions_from_data()

    return spectrum

```

**Comment by k8macarthur** [comment]
@tjof2 Does the function work on your data set now?

**Comment by k8macarthur** [comment]
I've now made a pull request for this function #1305 :)

**Comment by k8macarthur** [comment]
I made the pull request to Release_Next_major by default but I've now moved it to Release_next_minor #1306

**Comment by thomasaarholt** [comment]
This should be closed, no? :)

**Comment by k8macarthur** [comment]
Ha! Probably :)
