### ISSUE TITLE
BUG: map() checks signal_axes scales and units incorrectly`

### ISSUE THREAD

**Issue by dnjohnstone** [hyperspy/hyperspy#975]
the map() method should check that the signal axes and units are identical, when there are multiple signal axes (e.g. a stack of images) to warn you if the units are not accounted for... However, if the signal dimension is 2 the code currently checks axes_manager[0], and axes_manager[1], which could be navigation axes - the result is that errors are raised when they shouldn't be.

This is easy to fix and a PR will follow.

**Comment by to266** [comment]
https://github.com/hyperspy/hyperspy/pull/977
