### ISSUE TITLE
Saving signals EMD requires certain metadata

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#983]
Trying to save a minimal `spectrum` in the EMD-file format does not work:

``` Python
s = hs.signals.Signal(range(100))
s.save("test.emd")
```

Does not work. To make it work, one needs to add several metadata fields like "user", "comments", ...

While the EMD-specification (http://emdatasets.lbl.gov/spec/#meta) encourages using metadata, all the metadata fields like this are optional.

So we should change the EMD file writer to allow for saving signals without these metadata fields.

**Comment by magnunor** [comment]
Having a look at this now

**Comment by CodeMonkeyJan** [comment]
I'm on vacation till Tuesday starting today, I'll also have a look as soon as I come back, thanks for pointing this out!

**Comment by magnunor** [comment]
@CodeMonkeyJan, sounds good. In case you've missed it, I've implemented some fixes here: https://github.com/hyperspy/hyperspy/pull/985

I'll wait until you've had time to look at it before doing additional changes.

**Comment by CodeMonkeyJan** [comment]
Thanks for all the work :-), I will post a longer reply there!

**Comment by magnunor** [comment]
Fixed in https://github.com/hyperspy/hyperspy/pull/1424
