### ISSUE TITLE
EMD-file reader requires string as metadata names

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#986]
Currently the EMD-file reader in HyperSpy requires the metadata values to be in utf8 encoding. However, it is possible to make attribute values in HDF5 be bytes.

So I think we should make HyperSpy able to _load_ EMD-files which has metadata byte values, but it should save the metadata values as utf8.

**Comment by CodeMonkeyJan** [comment]
I'll be back from vacation on Tuesday, I'll take a look then.

**Comment by CodeMonkeyJan** [comment]
Thanks for your patience :-). It seems that you already fixed this issue in #985. I did not have this issue in Python 2.7, I assume it stems from the new policy in Python 3 regarding Unicode...
Quoting https://docs.python.org/3.0/whatsnew/3.0.html:
"Everything you thought you knew about binary data and Unicode has changed".
Is there anything I can do to help?

**Comment by magnunor** [comment]
Fixed in https://github.com/hyperspy/hyperspy/pull/1439
