### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by RowanLeary** [hyperspy/hyperspy#987]
Unable to download the 0.8.4 windows bundle. Download time displays as hours or days. Is the github page down? (Have verified my wifi connection with other successfull large downloads).

**Comment by sem-geologist** [comment]
https://status.github.com/ shows that there were no issues with github. I also tried to download, it downloads without any issues in less than 2min (on linux system). So I guess something is blocking the download on your side (antivirus, system, internet browser...)

**Comment by dnjohnstone** [comment]
I think this can be considered closed.
