### ISSUE TITLE
s.integrate_in_range broken in 0.8.x

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#995]
Seems to be broken in 0.8.x, but works with the current master (unless I'm messing something up).

```Python
hyperspy/gui/tools.py in span_selector_switch(self, on)
    169                     onselect=self.update_span_selector_traits,
    170                     onmove_callback=self.update_span_selector_traits,
--> 171                     left_limit=self.axis.low_value,
    172                     right_limit=self.axis.high_value)
    173 

AttributeError: 'IntegrateArea' object has no attribute 'axis'
```

**Comment by to266** [comment]
Actually this is broken in master, as without the limits you can drag the selector outside the range, and then it crashes with the usually horrible traits errors.

No point in PR'ing to master separately though, as it should be merge with 0.8.x, I guess..

**Comment by francisco-dlp** [comment]
#1021
