### ISSUE TITLE
s.remove_background(estimate_background=False) giving wrong results

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#998]
There seems to be some strange results when using the `estimate_background=False` argument in `s.remove_background`, in the current master. This does not happen in 0.8.x, since the `estimate_background` is not implemented there.

```Python
s = hs.signals.Spectrum(np.arange(100000).reshape(10,10,1000))
s1 = s.remove_background(signal_range=(100.,200.), background_type='Polynomial', polynomial_order=1)
s1.data.max()
1.7462298274040222e-10
s1.data.min()
-5.8207660913467407e-10

s2 = s.remove_background(signal_range=(100.,200.), background_type='Polynomial', polynomial_order=1, estimate_background=False)
s2.data.max()
99000.000000064319
s2.data.min()
-538768.21877096978
```

The results also replicate to "real" datasets, where I tried to remove the power law plasmon background but it only seemed to change the first pixel.

**Comment by francisco-dlp** [comment]
#1117
